### ISSUE TITLE
Parquet Reading Failed due to `aiobotocore` release

### ISSUE THREAD

**Issue by r-luo** [dask/dask#8070] opened 2021-08-20 16:11 UTC
**What happened**:
I got this error
```
AttributeError: module 'aiobotocore' has no attribute 'AioSession'
```
When trying to read a parquet file from s3 with:
```python
import dask.dataframe as dd
data_dd = dd.read_parquet(data_path)
```

**What you expected to happen**:
The same line hasn't generated any errors before today.

**Minimal Complete Verifiable Example**:
Essentially any s3 parquet read with `aiobotocore==1.4.0`

**Anything else we need to know?**:

I think it's due to the `aiobotocore==1.4.0` release 6 hours ago.

**Environment**:

- Dask version: 2021.08.0
- Python version: 3.7
- Operating System: Linux
- Install method (conda, pip, source): pip

**Comment by r-luo** [comment] 2021-08-20 16:15
pinning `aiobotocore` to `1.3.3` solves the issue

**Comment by jrbourbeau** [comment] 2021-08-20 16:48
Thanks for raising an issue @r-luo. Closing as a duplicate of https://github.com/dask/s3fs/issues/514

**Closed by jrbourbeau** 2021-08-20 16:48 UTC
