### ISSUE TITLE
Unpredictable TypeError when computing on dataframe with datetime column

### ISSUE THREAD

**Issue by JnsLns** [dask/dask#9003] opened 2022-04-29 15:18 UTC
This is a very strange error that I cannot provide lots of information for. I have tried various conversions of the time columns (e.g. to int64) but the result does not change. 

**What happened**: `TypeError` is thrown when applying `sort_values` to a very simple dataframe of datetime objects. Very minor changes in the data make the error disappear or reappear  (single digits, removing any row in the dataframe, or changing partition number). 

**Minimal Complete Verifiable Example**: 

```python
import pandas as pd
import dask.dataframe as dd

# Completes without exception
dts = pd.to_datetime(
['2022-04-23 00:00:00.618000+00:00',
'2022-04-23 00:00:03.199000+00:00',
'2022-04-23 00:00:03.463000+00:00',
'2022-04-23 00:00:02.396000+00:00',
'2022-04-23 00:00:02.623000+00:01',]  # <-- Only difference to the next block is the last digit here
)
df = pd.DataFrame(dict(ts=dts))
ddf = dd.from_pandas(df, npartitions=2)
ddf.sort_values(by='ts').compute()         


# Throws TypeError
dts = pd.to_datetime(
['2022-04-23 00:00:00.618000+00:00',
'2022-04-23 00:00:03.199000+00:00',
'2022-04-23 00:00:03.463000+00:00',
'2022-04-23 00:00:02.396000+00:00',
'2022-04-23 00:00:02.623000+00:00',]
)
df = pd.DataFrame(dict(ts=dts))
ddf = dd.from_pandas(df, npartitions=2)
ddf.sort_values(by='ts').compute()            # TypeError: value should be a 'Timestamp', 'NaT', or array of those. Got 'StringArray' instead.

```
**Anything else we need to know?**: The error originally occurred with a large dataset and many partitions, so it is not related to the small data size in the example.

**Environment**:

- Dask version: 2022.04.1
- Python version: 3.9.1
- Operating System: Debian GNU/Linux 11 (bullseye)
- Install method (conda, pip, source): pip

**Comment by JnsLns** [comment] 2022-04-29 15:31
After further consideration I believe this issue might be related to https://github.com/dask/dask/issues/8999, in which identical datetimes lead dask to only process the last partition.

This is because in the provided example the exception disappears both

- when changing any of the last digits (nanoseconds) in the input dataframe (which incidentally means that the nanosecond values are not identical anymore across all rows). 
- when changing the partitions to one

**Comment by pavithraes** [comment] 2022-05-02 18:10
@JnsLns Thanks for reporting this!

Looks like the first DataFrame has `object` types, while the second has `datetime64[ns, UTC]`. I think this error is related to compatibility with custom pandas dtypes (there are a few open issues around this). I'll keep looking into it. :)

**Comment by park** [comment] 2022-05-06 08:47
Encountered the same issue in Dask 2022.05.

Removing `.sort_values()` after `ddf` resolves it.

**Comment by JnsLns** [comment] 2022-05-06 09:44
As @pavithraes said, the column datatype in the first dataframe in the initial example is `object` while the second is `datetime64[ns, UTC]`. I realize this does not seem to be related to Dask directly. Dask just chokes on the `object` column. But I cannot imagine it is expected pandas behavior to vary column data type depending on whether or not nanoseconds are identical or different across rows...

**Comment by JnsLns** [comment] 2022-05-06 09:56
@park 
I have found a workaround for the issue, which involves converting the datetime column to integer and doing the sort (or other operations) on the converted column:

MCVE
```
import dask.dataframe 
import pandas as pd

dts = pd.to_datetime(
['2022-04-23 00:00:00.618000+00:00',
'2022-04-23 00:00:03.199000+00:00',
'2022-04-23 00:00:03.463000+00:00',
'2022-04-23 00:00:02.396000+00:00',
'2022-04-23 00:00:02.623100+00:00',]  # <-- Only difference to the next block is the last digit here
)
df = pd.DataFrame(dict(ts=dts))

df['backup'] = df['ts']
df = dask.dataframe.from_pandas(df, npartitions=2)    
df['ts'] = df['ts'].values.astype('int64')       # without this -> TypeError
df = df.sort_values(by='ts').compute()
df['ts'] = df['backup']
df.drop(columns='backup')    
```
Hope it is applicable to your use case.

**Comment by fdzuJ** [comment] 2022-10-05 06:13
Another workaround is to use `.set_index()`

Example:
```python
import pandas as pd
import dask.dataframe as dd

dts = pd.to_datetime(
    [
        '2022-04-23 00:00:00.618000+00:00',
        '2022-04-23 00:00:03.199000+00:00',
        '2022-04-23 00:00:03.463000+00:00',
        '2022-04-23 00:00:02.396000+00:00',
        '2022-04-23 00:00:02.623000+00:00',
    ]
)
df = pd.DataFrame(dict(ts=dts))
ddf = dd.from_pandas(df, npartitions=2)
ddf.set_index('ts', drop=False).reset_index(drop=True).compute()
```

**Comment by jrbourbeau** [comment] 2022-12-06 17:31
Closing as I'm not able to reproduce with the latest `dask=2022.12.0` release

**Closed by jrbourbeau** 2022-12-06 17:31 UTC
Labels: dataframe, bug
