### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by secrettoad** [dask/dask#10328] opened 2023-06-01 21:26 UTC
Hi all,

Thank you, first of all for your time in reading and in maintaining this fantastic software.

I can't imagine that there is indeed a memory leak somewhere within distributed==2023.5.0, but that is what I am seeing. Would someone please be kind enough to see if they can reproduce?

I first noticed that some of my computations were ballooning in terms of unmanaged memory, even after all futures had been released and even with MALLOC_TRIM_THRESHOLD=0, and I eventually pared my way down to the most minimal of examples. It seems as though there is a memory leak somewhere in distributed, as i see the bytes stored on my idle cluster increasing by about 10mb/s. This seems to balloon in relation to the number of tasks submitted, and so perhaps is related to communications somehow?

10Mb/s may not seem huge, but it will eventually result in workers being killed even if the cluster is idle and, as i mentioned, with the ballooning when tasks are submitted, memory becomes entirely consumed by this very quickly, resulting in dead workers, idle workers and re-work of tasks.

Using Python 3.8.16.

```python
from dask.distributed import LocalCluster, Client

def test_memory_leak():
    with Client(LocalCluster()):
        time.sleep(99999)
```

bokeh==2.4.2
click==8.1.3
cloudpickle==2.2.1
dask==2023.5.0
distributed==2023.5.0
exceptiongroup==1.1.1
fsspec==2023.5.0
importlib-metadata==6.6.0
iniconfig==2.0.0
Jinja2==3.1.2
locket==1.0.0
MarkupSafe==2.1.2
msgpack==1.0.5
numpy==1.24.3
packaging==23.1
partd==1.4.0
Pillow==9.5.0
pluggy==1.0.0
psutil==5.9.5
pytest==7.3.1
PyYAML==6.0
sortedcontainers==2.4.0
tblib==1.7.0
tomli==2.0.1
toolz==0.12.0
tornado==6.3.2
typing_extensions==4.6.2
urllib3==2.0.2
zict==3.0.0
zipp==3.15.0

Please let me know if I can help resolve this in any way.

-- edit -- 

This could be solved with some way to force full garbage collection, but for the life of me I cannot find such a thing. I have tried the python test function in the docs, the MALLOC_TRIM_THRESHOLD_ and gc.collect() and this unmanaged memory does not seem to respond to anything.

**Comment by secrettoad** [comment] 2023-06-02 20:07
Figured out the processes managing connections and computations were staying alive after erroring and therefore preventing clearing of memory on workers. This is not a dask issue so this can be closed. Sorry for the clutter

**Comment by j-bennet** [comment] 2023-06-10 00:54
Thank you @secrettoad, happy to hear the issue is resolved. Closing.

**Closed by j-bennet** 2023-06-10 00:54 UTC
Labels: needs triage
