### ISSUE TITLE
`to_parquet` call fails with index of type `int` and data of type list of lists

### ISSUE THREAD

**Issue by FredericOdermatt** [dask/dask#8390] opened 2021-11-17 08:32 UTC
Hi everyone

I have recently started working a lot with `Dask` and I am facing an issue similar to what other people have described here [stackoverflow 1](https://stackoverflow.com/questions/52707190/dask-why-has-cpu-usage-suddenly-dropped), [stackoverflow 2](https://stackoverflow.com/questions/67319620/dask-computations-slow-down-with-time) and which might also be related to [issue 2835](https://github.com/dask/distributed/issues/2835).

While these posts even got some replies from Dask maintainers they had no minimal completable example, so I have tried to produce a usable one in this issue.

The issue appears when using a `dask.distributed` `LocalCluster` and applying the `repartition` function to time series data stored as a list-of-lists. 

In the code example I `read_parquet`, then `repartition(partition_size='20MB')` and call `to_parquet`. The code executes quickly at the beginning, but then never finishes as 

- `distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://172.17.0.2:40991 remote=tcp://172.17.0.2:51778>: TimeoutError: [Errno 110] Connection timed out`
- `distributed.worker - ERROR - failed during get data with tcp://172.17.0.2:46819 -> tcp://172.17.0.2:39897`

- `distributed.worker - ERROR - Worker stream died during communication: tcp://172.17.0.2:44899`

- `OSError: Timed out during handshake while connecting to tcp://172.17.0.2:44899 after 60 s`

 errors appear while the nanny starts restarting workers.

![image](https://user-images.githubusercontent.com/50372080/142156776-7d199a4c-2364-4766-9015-413706ad5564.png)

**Minimal Complete Verifiable Example**:

```python3
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster
import numpy as np
import pandas as pd
from scipy.stats import loguniform


def artificial_dataset():
    size = 45000000
    data = loguniform.rvs(1,1000, size=size)
    data = np.floor(data).astype(np.uint32)
    df = pd.DataFrame(data, columns=['occ'])

    def synthethic_timeseries(x):
        dates = np.random.choice(np.arange(1000), size=x, replace=False)
        order_volumes = np.random.randint(1,10, size=x)       
        return np.stack([dates, order_volumes]).T.tolist()

    with LocalCluster(n_workers=20,
                      processes=True,
                      threads_per_worker=1,
                      memory_limit='64gb',
                      dashboard_address='127.0.0.1:41927',
                      ) as cluster, Client(cluster) as client:
        ddf = dd.from_pandas(df, npartitions=300)
        ddf['timeseries'] = ddf['occ'].apply(lambda x: synthethic_timeseries(x), meta=('timeseries', object))
        ddf.to_parquet('synthethic', schema='infer', overwrite=True)


def main():
    y = input('y to regenerate\n')
    if y == 'y':
        artificial_dataset()
    with LocalCluster(n_workers=20,
                      processes=True,
                      threads_per_worker=1,
                      memory_limit='64gb',
                      dashboard_address='127.0.0.1:41927',
                      ) as cluster, Client(cluster) as client:
        timeseries_ddf = dd.read_parquet('synthethic')
        timeseries_ddf = timeseries_ddf.repartition(partition_size='20MB')
        timeseries_ddf.to_parquet('synthethic_repartitioned', overwrite=True)


if __name__ == '__main__':
    main()
```
- the `to_parquet` did not complete for me on 3 different machines
- the actual timeseries data that I'm working with is `log-uniform` distributed. This means most time series are short == sparse (not storing zero value), but some are up to 1000 days long. In my actual code I use a `group_by` operation to create the time series. The timeseries is saved as a list of lists, where the sublists have length 2 and describe `[date, value]`.
- I personally add `import logging`, `distr_logger = logging.getLogger("distributed.utils_perf")` and `distr_logger.disabled = True` to not have the garbage collection notifications, but they are not part of the minimal example.

**Things I have tried**:

- I have reproduced the error on two different CPU clusters that are available to me (where I am working in a docker container) as well as on my local laptop, where I am not in a docker container. Stackoverflow2 post's author [answers his question himself
](https://stackoverflow.com/a/67382754/17426385) saying that working outside the docker container helped him, but I have not observed that.
- I have tried a few different `num_workers` (8 on my laptop, up to 60 on the cluster) and have observed the issue regardless.
- increasing the timeout configs for `distributed.comm.timeouts.tcp` and `distributed.comm.timeouts.connect`

**I want to mention that**
- I'm new to Dask, so forgive me any noob mistakes.
- I feel like the extreme difference in lengths of timeseries might be the issue and might cause some issue in the `repartition` function. Maybe dask isn't made for such data, but that doesn't keep noobs like me from trying to use dask like that anyway. 
- when analyzing partition sizes using `.memory_usage_per_partition(deep=True).compute()` the data is nicely partitioned in the `synthethic dataset` of the minimal example, but still the repartition fails. In my actual time series data I *have* to repartition since my data is not as nicely partitioned after the `group_by`.

**Environment**:

- Dask version: 2021.10.0
- Python version: 3.8.11
- Operating System: linux/amd64
- Install method:
```bash
# environment for minimal example
conda create --name minimal_failing python=3.8.11
conda install dask
conda install -c anaconda scipy
conda install -c conda-forge pyarrow
```

**Comment by FredericOdermatt** [comment] 2021-11-17 09:01
I just did a sanity check and removed the `.repartition` function completely. So the second part of my code only looks like this:

```python3
    with LocalCluster(n_workers=20,
                      processes=True,
                      threads_per_worker=1,
                      memory_limit='64gb',
                      dashboard_address='127.0.0.1:41927',
                      ) as cluster, Client(cluster) as client:
        timeseries_ddf = dd.read_parquet('synthethic_basic')
        # timeseries_ddf = timeseries_ddf.repartition(partition_size='20MB')
        timeseries_ddf.to_parquet('synthethic_repartitioned', overwrite=True)
```
and **still** it is talking a lot of time for the final tasks to finish! So the issue is likely related to the `to_parquet` operation.

In my dashboard there is only two workers left doing the last `to_parquet` for more than 5 minutes

![image](https://user-images.githubusercontent.com/50372080/142169131-968c5623-5434-41ac-846e-2e1fd604db03.png)

One of the final workers logs doesn't show anything suspicious:
```bash
distributed.worker - INFO - Start worker at: tcp://127.0.0.1:44401

distributed.worker - INFO - Listening to: tcp://127.0.0.1:44401

distributed.worker - INFO - dashboard at: 127.0.0.1:40532

distributed.worker - INFO - Waiting to connect to: tcp://127.0.0.1:44826

distributed.worker - INFO - -------------------------------------------------

distributed.worker - INFO - Threads: 1

distributed.worker - INFO - Memory: 59.60 GiB

distributed.worker - INFO - Local Directory: /root/mlx-nfs/frederic/data/dask-worker-space/worker-3hsoneii

distributed.worker - INFO - -------------------------------------------------

distributed.worker - INFO - Registered to: tcp://127.0.0.1:44826

distributed.worker - INFO - -------------------------------------------------
```

**Comment by FredericOdermatt** [comment] 2021-11-18 08:12
I have kept looking at this and I have a new **minimal working code** that I believe is closer to the root cause of this:

```python3
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster
import numpy as np
import pandas as pd
from scipy.stats import loguniform

import logging
distr_logger = logging.getLogger("distributed.utils_perf")
distr_logger.disabled = True


def synthethic_timeseries(x, uniform):
    if uniform:
        x = 200
    dates = np.random.choice(np.arange(1000), size=x, replace=False)
    order_volumes = np.random.randint(1, 10, size=x)
    return np.stack([dates, order_volumes]).T.tolist()


def main():
    size = 1000000
    engine = 'pyarrow'
    uniform = False
    data = loguniform.rvs(1, 1000, size=size)
    data = np.floor(data).astype(np.int64)
    df = pd.DataFrame(data, columns=['occ'])

    with LocalCluster(n_workers=70,
                      processes=True,
                      threads_per_worker=1,
                      memory_limit='64gb',
                      dashboard_address='127.0.0.1:41922',
                      local_directory='/root/.dask'
                      ) as cluster, Client(cluster) as client:
        ddf = dd.from_pandas(df, npartitions=300)
        ddf['timeseries'] = ddf['occ'].apply(
            lambda x: synthethic_timeseries(x, uniform), meta=('timeseries', object))
        ddf.to_parquet(f'synthethic_{size}_{engine}', overwrite=True, engine=engine)


if __name__ == '__main__':
    main()
```
https://user-images.githubusercontent.com/50372080/142372603-16251b36-f995-495d-b0fc-8e65312269d3.mov

- in general a large `n_workers` and larger data `size` make the behavior worse
- if `n_workers` is not 1 and `size` is large enough I can get to a setting where the code does not complete
- setting `uniform` to `True` helps the code complete faster.
- a setting where I never complete: `uniform = False`, `size = 10000000`, `npartitions=1000`, `n_workers=1000`. Some other settings sometimes complete after a long period of errors and worker restarts.
- 
Here is a list of things I have tried so far:
- working with `floats` instead of `ints`
- working with `dicts` instead of `lists`
- working with `np.array`
- specifying a schema like: `schema = pa.schema([pa.field('timeseries', pa.list_(pa.list_(pa.int64())))])`
- I have again run this on multiple machines

**Comment by FredericOdermatt** [comment] 2021-11-19 09:10
Today I worked more on this and I think I have gotten even closer to the base of the issue:

The crux seems to lie in the combination of `index` of type `int` and data of the form `pa.list_(pa.list_(pa.int64())))`

A simpler **minimal reproducable example** making forth with the log-uniform list-length distribution, since it is not needed to reproduce the bug:

```python3
import logging

import dask.dataframe as dd
import numpy as np
import pandas as pd
import pyarrow as pa
from dask.distributed import Client, LocalCluster

distr_logger = logging.getLogger("distributed.utils_perf")
distr_logger.disabled = True


def main():
    index_dtype = np.float32  # success for np.float32, no completion for np.int64
    size = 5000000
    engine = 'pyarrow'
    df = pd.DataFrame(np.arange(size).astype(index_dtype), columns=['index'])

    with LocalCluster(n_workers=70,
                      processes=True,
                      threads_per_worker=1,
                      memory_limit='64gb',
                      dashboard_address='127.0.0.1:41927'
                      ) as cluster, Client(cluster) as client:
        ddf = dd.from_pandas(df, npartitions=300)
        ddf['timeseries'] = ddf['index'].apply(
            lambda x: np.stack([np.random.randint(1, 10, size=100)]).T.tolist(), meta=('timeseries', object))
        ddf = ddf.set_index('index', shuffle="disk")
        ddf.to_parquet(f'synthethic_{size}_{engine}', overwrite=True, compression='snappy',
                       engine='pyarrow', write_index=True)


if __name__ == '__main__':
    main()
```

a few notes here:
- simply not using `set_index` reproduces the bug, since the default index is also of type `int64`
- again just increasing the `size` of the data and increasing the `n_workers` it is easy to go from a setting where the job completes with a few hickups to a setting where the job does not complete anymore.
- setting `write_index=False` solved the issue
- going from list of lists of ints (`pa.list_(pa.list_(pa.int64())))`) to lists of ints (`pa.list_(pa.int64()))`) solves the issue

I'm a bit surprised by this weird connection of integer index and lists of lists. I have run a large job with `size` 45 million with no issue when setting the index to `np.float32`.

**Comment by FredericOdermatt** [comment] 2021-11-23 07:34
I want to give another update. I can now avoid this behavior, but it is still weird as to why it happens for me.

In case anyone else is having similar behavior, where `to_parquet` calls on a `LocalCluster` are kind of lagging at the end or even never finishing:

I could solve my issues by moving all data (including index) from `int` to `float` before writing to parquet and back to int when reading back:

```python3
def save_with_float_idx(ddf, save_path: str, **kwargs):
    """ save but index to float """
    ddf.index = ddf.index.astype(np.float64)
    try:
        ddf.to_parquet(save_path, overwrite=True, compression='snappy', engine='pyarrow',
                       write_index=True, **kwargs)
    except ValueError as e:
        print('ValueError occured, want to download logs from dashboard info?')
        input('any input to continue (local cluster will shutdown)')
        raise e


def load_from_float_idx(load_path: str):
    """ load and convert idx to int """
    ddf = dd.read_parquet(load_path, engine='pyarrow')
    ddf.index = ddf.index.astype(np.int64)
    return ddf
```

If you have data columns with `int` you need to move them as well. Turns out this issue was not related to lists-of-lists.

I have made a final minimal failing example that for me completely fails or computes with no issue at all depending only on whether any column has integers.

```python3
import logging

import dask.dataframe as dd
import numpy as np
import pandas as pd
from dask.distributed import Client, LocalCluster

distr_logger = logging.getLogger("distributed.utils_perf")
distr_logger.disabled = True


def main():
    size = 10000000
    ncols = 10
    engine = 'pyarrow'
    df = pd.DataFrame(np.tile(np.arange(size), (ncols, 1)).T.astype(np.float64),
                      columns=[f'col_{i}' for i in range(ncols)])
    with LocalCluster(n_workers=70,
                      processes=True,
                      threads_per_worker=1,
                      memory_limit='64gb',
                      dashboard_address='127.0.0.1:41927'
                      ) as cluster, Client(cluster) as client:
        ddf = dd.from_pandas(df, npartitions=1000)
        # uncomment to make index float --> runs with no issue
        # ddf = ddf.set_index('col_0', shuffle="disk", sorted=True)
        ddf.to_parquet(f'synthethic_{size}_{engine}', overwrite=True, compression='snappy',
                       engine='pyarrow', write_index=True)


if __name__ == '__main__':
    main()
```

**Comment by scharlottej13** [comment] 2022-03-01 21:20
Hi @FredericOdermatt and thank you for your patience on this issue!

I was able to reproduce your most recent reproducible examples (thank you for taking the effort to make these more minimal) both on Dask versions `2021.10.0` and `2022.02.1`. From what I can tell, this issue is not related to `parquet`, but is instead more about managing memory in Dask. Stepping through your snippet, I was able to reproduce your error at `ddf.set_index('some_col', shuffle="disk")`:
```python
import dask.dataframe as dd
import numpy as np
import pandas as pd
from dask.distributed import Client, LocalCluster

cluster = LocalCluster(
    n_workers=70,
    processes=True,
    threads_per_worker=1,
    memory_limit='64gb'
)
client = Client(cluster)

index_dtype = np.int64  # success for np.float32, no completion for np.int64
size = 5000000
engine = 'pyarrow'
df = pd.DataFrame(np.arange(size).astype(index_dtype), columns=['some_col'])
ddf = dd.from_pandas(df, npartitions=300)
ddf['timeseries'] = ddf['some_col'].apply(
    lambda x: np.stack([np.random.randint(1, 10, size=100)]).T.tolist(), meta=('timeseries', object))
# errors start happening here
ddf = ddf.set_index('some_col', shuffle="disk")
# ddf.to_parquet(f'synthethic_{size}_{engine}', overwrite=True, compression='snappy',
#                engine='pyarrow', write_index=True)
# ddf.to_csv('tmp/export-*.csv')
```
This makes sense, because setting an index is a shuffling operation, which is expensive (see the [Dask Best Practices docs)](https://docs.dask.org/en/stable/dataframe-best-practices.html#avoid-full-data-shuffling). I was able to run your code locally by changing this to `ddf = ddf.set_index('some_col', shuffle="disk", sorted=True)`. Even better would be to set the index earlier, persist, and then do any additional operations (per the [Dask docs on persisting intelligently](https://docs.dask.org/en/stable/dataframe-best-practices.html#persist-intelligently)).

I'm going to close this issue for now, but if this doesn't solve your problem I would encourage you to open up your question again on the [Dask Discourse](https://dask.discourse.group/). Thanks again for your patience.

**Closed by scharlottej13** 2022-03-01 21:20 UTC
Labels: dataframe, parquet
