### ISSUE TITLE
Dask creates folder when using dd.read_parquet() on a path that does not exist

### ISSUE THREAD

**Issue by RodrigoNeves95** [dask/dask#5526] opened 2019-10-23 09:14 UTC
The code should be straightforward to understand. But the problem is that when you try to read a parquet folder that does not exist dask is creating that exact path. I believe this shouldn't happen. Correct me if I'm wrong.

```python
In [1]: import os                                                                                                                                              

In [2]: import dask.dataframe as dd                                                                                                                            

In [3]: os.listdir()                                                                                                                                           
Out[3]: []

In [4]: dd.read_parquet('non_existing_folder')                                                                                                                 
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
/usr/local/lib/python3.7/site-packages/fastparquet/api.py in __init__(self, fn, verify, open_with, root, sep)
    109                 self.fn = fn2
--> 110                 with open_with(fn2, 'rb') as f:
    111                     self._parse_header(f, verify)

/usr/local/lib/python3.7/site-packages/fsspec/spec.py in open(self, path, mode, block_size, **kwargs)
    707             f = self._open(
--> 708                 path, mode=mode, block_size=block_size, autocommit=ac, **kwargs
    709             )

/usr/local/lib/python3.7/site-packages/fsspec/implementations/local.py in _open(self, path, mode, block_size, **kwargs)
    110             self.makedirs(self._parent(path), exist_ok=True)
--> 111         return LocalFileOpener(path, mode, fs=self, **kwargs)
    112 

/usr/local/lib/python3.7/site-packages/fsspec/implementations/local.py in __init__(self, path, mode, autocommit, fs, **kwargs)
    167         self.blocksize = io.DEFAULT_BUFFER_SIZE
--> 168         self._open()
    169 

/usr/local/lib/python3.7/site-packages/fsspec/implementations/local.py in _open(self)
    172             if self.autocommit or "w" not in self.mode:
--> 173                 self.f = open(self.path, mode=self.mode)
    174             else:

FileNotFoundError: [Errno 2] No such file or directory: '/workspace/schedulers/rodrigo/tmp/non_existing_folder/_metadata'

During handling of the above exception, another exception occurred:

IsADirectoryError                         Traceback (most recent call last)
<ipython-input-4-f0ef6aef5ccf> in <module>
----> 1 dd.read_parquet('non_existing_folder')

/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, **kwargs)
    207         gather_statistics=gather_statistics,
    208         filters=filters,
--> 209         **kwargs
    210     )
    211     if meta.index.name is not None:

/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py in read_metadata(fs, paths, categories, index, gather_statistics, filters, **kwargs)
    181         # correspond to a row group (populated below).
    182         parts, pf, gather_statistics, fast_metadata = _determine_pf_parts(
--> 183             fs, paths, gather_statistics, **kwargs
    184         )
    185 

/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py in _determine_pf_parts(fs, paths, gather_statistics, **kwargs)
    159             # There is only one file to read
    160             pf = ParquetFile(
--> 161                 paths[0], open_with=fs.open, sep=fs.sep, **kwargs.get("file", {})
    162             )
    163 

/usr/local/lib/python3.7/site-packages/fastparquet/api.py in __init__(self, fn, verify, open_with, root, sep)
    113             except (IOError, OSError):
    114                 self.fn = join_path(fn)
--> 115                 with open_with(fn, 'rb') as f:
    116                     self._parse_header(f, verify)
    117         self.open = open_with

/usr/local/lib/python3.7/site-packages/fsspec/spec.py in open(self, path, mode, block_size, **kwargs)
    706             ac = kwargs.pop("autocommit", not self._intrans)
    707             f = self._open(
--> 708                 path, mode=mode, block_size=block_size, autocommit=ac, **kwargs
    709             )
    710             if not ac:

/usr/local/lib/python3.7/site-packages/fsspec/implementations/local.py in _open(self, path, mode, block_size, **kwargs)
    109         if self.auto_mkdir:
    110             self.makedirs(self._parent(path), exist_ok=True)
--> 111         return LocalFileOpener(path, mode, fs=self, **kwargs)
    112 
    113     def touch(self, path, **kwargs):

/usr/local/lib/python3.7/site-packages/fsspec/implementations/local.py in __init__(self, path, mode, autocommit, fs, **kwargs)
    166         self.autocommit = autocommit
    167         self.blocksize = io.DEFAULT_BUFFER_SIZE
--> 168         self._open()
    169 
    170     def _open(self):

/usr/local/lib/python3.7/site-packages/fsspec/implementations/local.py in _open(self)
    171         if self.f is None or self.f.closed:
    172             if self.autocommit or "w" not in self.mode:
--> 173                 self.f = open(self.path, mode=self.mode)
    174             else:
    175                 # TODO: check if path is writable?

IsADirectoryError: [Errno 21] Is a directory: '/workspace/schedulers/rodrigo/tmp/non_existing_folder'

In [5]: os.listdir()                                                                                                                                           
Out[5]: ['non_existing_folder']

In [6]: dd.read_parquet('non_existing_folder')                                                                                                                 
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-6-f0ef6aef5ccf> in <module>
----> 1 dd.read_parquet('non_existing_folder')

/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, **kwargs)
    207         gather_statistics=gather_statistics,
    208         filters=filters,
--> 209         **kwargs
    210     )
    211     if meta.index.name is not None:

/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py in read_metadata(fs, paths, categories, index, gather_statistics, filters, **kwargs)
    181         # correspond to a row group (populated below).
    182         parts, pf, gather_statistics, fast_metadata = _determine_pf_parts(
--> 183             fs, paths, gather_statistics, **kwargs
    184         )
    185 

/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py in _determine_pf_parts(fs, paths, gather_statistics, **kwargs)
    122             # This is a directory, check for _metadata, then _common_metadata
    123             paths = fs.glob(paths[0] + fs.sep + "*")
--> 124             base, fns = _analyze_paths(paths, fs)
    125             relpaths = [path.replace(base, "").lstrip("/") for path in paths]
    126             if "_metadata" in relpaths:

/usr/local/lib/python3.7/site-packages/dask/dataframe/io/parquet/utils.py in _analyze_paths(file_list, fs, root)
    403     path_parts_list = [_join_path(fn).split("/") for fn in file_list]
    404     if root is False:
--> 405         basepath = path_parts_list[0][:-1]
    406         for i, path_parts in enumerate(path_parts_list):
    407             j = len(path_parts) - 1

IndexError: list index out of range

In [7]: import dask                                                                                                                                            

In [8]: dask.__version__                                                                                                                                       
Out[8]: '2.6.0'
```

**Comment by TomAugspurger** [comment] 2019-10-23 14:58
Is this just with fastparquet, or is does it occur with pyarrow too?

Can you reproduce with just fastparquet and not Dask?

**Comment by RodrigoNeves95** [comment] 2019-10-23 23:29
Yes, it only happens with fastparquet backend and I can't reproduce it only with fastparquet.

**Comment by jrbourbeau** [comment] 2019-11-25 22:33
After investigating some, it looks like this issue originates from `fsspec`'s `LocalFileSystem` having `auto_mkdir=True` by default:

https://github.com/intake/filesystem_spec/blob/6f2e733a144eb9620c789ea6dfd4c4b2e3187999/fsspec/implementations/local.py#L24

which causes parent directories to be automatically created:

https://github.com/intake/filesystem_spec/blob/6f2e733a144eb9620c789ea6dfd4c4b2e3187999/fsspec/implementations/local.py#L103-L107

@TomAugspurger does it seem sensible to override `auto_mkdir=False` if dealing with a local filesystem and `auto_mkdir` isn't specified in `storage_options`?

**Comment by TomAugspurger** [comment] 2019-11-26 12:41
The comment there says

```
This is assumed by pyarrow code.
```

which camge from https://github.com/intake/filesystem_spec/commit/06f9a9a9de9188c7917d29b19d8609e33a214d28

@martindurant do you recall any specifics on that? A simple `df.to_parquet("/a/b/c.parquet", engine="pyarrow")` will fail with a FIleNotFoundError. Perhaps the pyarrow behavior changed?

If so, I recommend that we deprecate `auto_mkdir` and in fsspec and change it here now.

**Comment by martindurant** [comment] 2019-11-26 13:39
No I don't really remember...
*Normally* you wouldn't expect to be able to write to a directory that doesn't exit, but I think this must have been specific to parquet directory trees. `auto_mkdir` is certainly ugly, would be happy to see it go away.

**Comment by TomAugspurger** [comment] 2019-11-26 14:07
I changed things locally, and we do have failures in Dask. I'll look into it a bit.

**Comment by TomAugspurger** [comment] 2019-11-26 14:23
The following suffices

```
diff --git a/fsspec/implementations/local.py b/fsspec/implementations/local.py
index 0f050e3..16368f8 100644
--- a/fsspec/implementations/local.py
+++ b/fsspec/implementations/local.py
@@ -21,10 +21,13 @@ class LocalFileSystem(AbstractFileSystem):
 
     root_marker = "/"
 
-    def __init__(self, auto_mkdir=True, **kwargs):
+    def __init__(self, auto_mkdir=False, **kwargs):
         super().__init__(**kwargs)
         self.auto_mkdir = auto_mkdir
 
+    def _isfilestore(self):
+        return True
+
     def mkdir(self, path, create_parents=True, **kwargs):
         path = self._strip_protocol(path)
         if create_parents:
```

I'm going to check with Arrow to see what can be done here. If `_isfilesystem()` is considered public for filesystems, we can go ahead an implement that.

**Comment by TomAugspurger** [comment] 2019-12-20 17:42
Closed by https://github.com/intake/filesystem_spec/pull/211.

**Closed by TomAugspurger** 2019-12-20 17:42 UTC
Labels: dataframe, io

**Comment by jrbourbeau** [comment] 2019-12-20 19:24
I think resolving this issue requires setting `auto_mkdir=False` still. xref https://github.com/intake/filesystem_spec/pull/222

**Comment by ayushdg** [comment] 2020-04-01 01:17
Given the updates made to fsspec setting `auto_mkdir=False` (xref intake/filesystem_spec#257) what should be the new behavior when writing dataframes to disk?

For context:
```
df = pd.DataFrame({'a':np.ones(100),'b':np.ones(100)})
ddf = dd.from_pandas(df,npartitions=2)
ddf.to_csv("df_result")
```
Will now fail if the path `df_result` doesn't already exist.

```
packages/fsspec/implementations/local.py", line 180, in _open
    self.f = open(self.path, mode=self.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/adattagupta/df_result/0.part'
```

**Comment by martindurant** [comment] 2020-04-01 12:34
to_csv and the like should explicitly create their dirs, one would think. Given that auto_mkdir wasn't possible a short while ago, I am surprised that it doesn't already.

**Comment by ayushdg** [comment] 2020-04-03 09:30
> to_csv and the like should explicitly create their dirs, one would think. Given that auto_mkdir wasn't possible a short while ago, I am surprised that it doesn't already.

Ah I see, it may not be because of that pr then. Looks like the error only impacts the `to_csv` codepath. Raised #6062 for further discussion.
