### ISSUE TITLE
Dask install via pip does not install all dependencies (toolz, cloudpicke)

### ISSUE THREAD

**Issue by ispmarin** [dask/dask#3899] opened 2018-08-23 12:27 UTC
When installing dask on Debian Stretch with python 3.5 using pip on a venv, when trying to import Dask dataframe, it complains about a few libraries missing:

    pip install dask
    # ok

    import dask.dataframe as dd
    ImportError: No module named 'toolz'

    pip install toolz

    import dask.dataframe as dd
    ImportError: No module named 'cloudpickle'

    pip install cloudpickle

    import dask.dataframe as dd
    # ok

Expected result:
When installed dask using pip, all dependencies would be installed.

**Comment by mrocklin** [comment] 2018-08-23 12:29
This is addressed in the pip installation instructions: http://dask.pydata.org/en/latest/install.html#pip

Closing this. If instructions there are unclear then please re-raise.

**Closed by mrocklin** 2018-08-23 12:29 UTC

**Comment by Ivan-HS** [comment] 2020-12-18 05:26
ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install
  
  
  ya segui las intrucciones de la documentacion para intalarlo y nada.

**Comment by jsignell** [comment] 2020-12-18 16:44
Did you try using conda or pip? If conda, try doing `conda list` and if pip: `pip freeze` then tell us what you get.

**Comment by sumit-lohan** [comment] 2021-01-04 03:25
> Did you try using conda or pip? If conda, try doing `conda list` and if pip: `pip freeze` then tell us what you get.

Nothing happened for me. Same error

**Comment by jsignell** [comment] 2021-01-04 16:35
I just confirmed that doing `python -m pip install "dask[dataframe]" --upgrade` installs all the expected dependencies.

**Comment by antoinecomp** [comment] 2021-06-21 09:56
I have the same issue.

I did installed `! python -m pip install dask[dataframe] --upgrade` in my collaboratory environment.

But when importing it returns

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/dask/dataframe/__init__.py in <module>()
      2     from ..base import compute
----> 3     from . import backends, dispatch, rolling
      4     from .core import (

2 frames
ImportError: cannot import name 'is_float_na_dtype' from 'dask.dataframe.utils' (/usr/local/lib/python3.7/dist-packages/dask/dataframe/utils.py)

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/dask/dataframe/__init__.py in <module>()
     55         '  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install'
     56     )
---> 57     raise ImportError(msg) from e

ImportError: Dask dataframe requirements are not installed.

Please either conda or pip install as follows:

  conda install dask                     # either conda install
  python -m pip install "dask[dataframe]" --upgrade  # or python -m pip install
;
```

**Comment by jsignell** [comment] 2021-06-21 15:29
If you ran that install command from inside a notebook, please make sure that you restart the kernel afterward.

**Comment by semenoffalex** [comment] 2022-02-21 09:18
`! python -m pip install dask[dataframe] --upgrade` results in `Requirement already satisfied`. Kernel has been restarted. However `import dask.dataframe as dd` returns the same suggestion to install dask.

**Comment by jsignell** [comment] 2022-02-21 17:10
If you can provide more of the error that you are seeing that would help. In a fresh environment I cannot reproduce @semenoffalex

**Comment by semenoffalex** [comment] 2022-02-23 14:26
@jsignell nevermind. 
Turned out the problem was with `cudf` breaking `pandas` installation in Ubuntu under WSL2.
