### ISSUE TITLE
DataFrame.to_hdf segfault

### ISSUE THREAD

**Issue by TomAugspurger** [dask/dask#1563] opened 2016-09-21 15:20 UTC
This script produces a segfault about 50-75% of the time for me

``` python
import numpy as np
import pandas as pd
import dask.dataframe as dd


fp = 'table*.hdf5'

def make():
    df = pd.DataFrame(np.random.randn(8000, 100))
    a = dd.from_pandas(df, npartitions=4)
    a.to_hdf(fp, 'a')


def read_write():
    print("Reading")
    a = dd.read_hdf(fp, 'a', mode='r')  # same results with mode='r+'
    a.head()
    X = a.drop(0, axis=1)
    print("Writing")
    X.to_hdf(fp, 'X')
    print("Success")


def main():
    make()
    read_write()

if __name__ == '__main__':
    main()
```

The output:

```
Reading
Writing
Python(88767,0x700001113000) malloc: *** error for object 0x7fcae4bb6520: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
fish: 'python foo.py' terminated by signal SIGABRT (Abort)
```

I'm still tinkering a bit to see what's going on, but I _think_ the issue is the same file is being used for both reading and writing. Just reading, or just writing (or writing to a different table) doesn't have this problem.

Maybe read and write each acquire their own lock independently?
Feel free to close if this is just user-error.

**Comment by mrocklin** [comment] 2016-09-21 15:26
It looks like there is currently some fancy-logic to determine if we need to lock or not.  I'd be tempted to always lock by default and let power users take on this responsibility.  Can you verify that things run ok if you call `to_hdf(..., lock=True)`

**Comment by TomAugspurger** [comment] 2016-09-21 15:30
That seems reasonable, though I think `lock=False` as a default is also fine. I'm guessing that my use-case is less common than wanting to read from a bunch of tables in parallel, and write the output to some other location.

**Comment by mrocklin** [comment] 2016-09-21 15:32
Your use case seems reasonable to me.  I think that it should work out-of-the-box.

I see your point though about multiple locks.  I suppose we could have a global registry of locks-per-file?

**Comment by TomAugspurger** [comment] 2016-09-21 15:32
Oh, I didn't realize `lock` is already an option. I still get a segfault with `lock=True` in just to_hdf

**Comment by TomAugspurger** [comment] 2016-09-21 15:34
Changing to `X.to_hdf(fp, 'X', get=dask.get)` seems to avoid the segfault. Would I also lose parallel reads in this case, or just parallel writing?

**Comment by mrocklin** [comment] 2016-09-21 15:34
Then the problem is probably as you suggested about read_hdf/to_hdf needing the same lock.  You could  do

```python
lock = Lock()
read_hdf(..., lock=lock)

to_hdf(..., lock=lock)
```

**Comment by mrocklin** [comment] 2016-09-21 15:35
Setting `get=dask.get` will lose parallel everything

**Comment by TomAugspurger** [comment] 2016-09-21 15:40
A shared lock in `read_hdf` and `to_hdf` did it, thanks Matt. A registry of locks / file seems like the solution to me. IIUC that'd still give parallel reads / writes (across files), whereas `lock=lock` doesn't, unless you expanded the `lock=` API to accept a dictionary of `{ filename: Lock }`.

**Comment by TomAugspurger** [comment] 2016-10-03 14:06
I've started on this btw, should have a fix later today.

**Comment by TomAugspurger** [comment] 2016-10-03 21:31
Can you tell if I'm doing something obviously wrong? https://github.com/dask/dask/compare/dask:34660a2...TomAugspurger:1e6842c

With that change, the following script, I get segfaults every time. The script here *only* does writing (no reading) yet (so this script works reliably on master).

```python
import numpy as np
import pandas as pd
import dask.dataframe as dd


fp = 'table*.hdf5'

def make():
    df = pd.DataFrame(np.random.randn(8000, 100))
    a = dd.from_pandas(df, npartitions=4)
    a.to_hdf(fp, 'a')


def read_write():
    print("Reading")
    a = dd.read_hdf(fp, 'a', mode='r')  # same results with mode='r+'
    a.head()
    X = a.drop(0, axis=1)
    print("Writing")
    X.to_hdf(fp, 'X')
    print("Success")


def main():
    make()

if __name__ == '__main__':
    main()
```

**Comment by mrocklin** [comment] 2016-10-04 15:10
Nothing jumps out at me for the `make` function

**Comment by TomAugspurger** [comment] 2016-10-04 18:13
Thanks for looking. The work project I've needed all this categorical / HDF5 stuff for has been pushed back a bit, so I'll revisit this in a couple weeks (though I might have some spare free time before then).

**Comment by thebeancounter** [comment] 2017-12-13 13:46
So, is there a fix yet? i still have this issue...

**Comment by mrocklin** [comment] 2018-10-23 21:56
The example in https://github.com/dask/dask/issues/1563#issuecomment-251233487 no longer seg faults for me.  Closing.

**Closed by mrocklin** 2018-10-23 21:56 UTC
Labels: dataframe, io
