### ISSUE TITLE
Protobuf support

### ISSUE THREAD

**Issue by Jeffrey04** [dask/dask#1434] opened 2016-08-02 09:42 UTC
Protocol buffer is usually described as an alternative to JSON. However, there's no easy way to get it working with dask (I use `dask.bag` mainly). The main problem with protocol buffer is that each message is serialized into a binary string, that is not delimited when there are multiple messages joined together. It would be nice if `dask.bag` can read/write protobuf messages properly, given a message class 

```
(my_bag
    .read_protobuf('foo.protobuf', message_class=SomeMessageClass)
    .to_protobuf('bar.protobuf'))
```

**Comment by mrocklin** [comment] 2016-08-02 11:22
It's worth noting that dask.bag doesn't have support for JSON either; users just map `json` functions against data.  Perhaps we can figure out how to do the same thing with Protobufs.

I don't have much on-the-ground experience with protobufs so I'm going to ask a few questions.  How do you read protobuf data now?  How would you read protobuf data in parallel?  Do you have many small files or a single large one?

**Comment by Jeffrey04** [comment] 2016-08-03 03:15
I don't currently have a file to read, and apparently there's no standardized approach to this from what I learned.

**Comment by Jeffrey04** [comment] 2016-08-03 08:19
```
It's worth noting that dask.bag doesn't have support for JSON either; users just map json functions against data. Perhaps we can figure out how to do the same thing with Protobufs.
```

I suppose read_text assumes each item is delimited by a newline, I have not tried with a file containing records in json without newlines though, not sure if this is true.

Considering there's no standardized way to put multiple protobuf messages into a file,  I suppose I should close this ticket. After some internal discussions within the team, we ended up decided to prefix each message with a count in `varint` (the data-interchange format needs to be consistent and usable in different programming languages).

So this means I need to figure out a way to feed sequence into `from_sequence` instead of `read_text` in future, and can no longer use `to_textfiles` to output multiple records (for each partition) in protobuf format (not sure if write_bytes is going to help though).

**Comment by mrocklin** [comment] 2016-08-03 12:12
If you want to put many records into large single files and then read those large files as many chunks then I recommend separating your records with *some* delimiter.  This is how Avro works; there is a header that includes the delimiter (usually around 40 random characters), records are always separated by that delimiter.  This approach works well with parallel computing systems like Dask, which have utilities to read anything-delimited files in chunks.  If this approach interests you then I recommend looking at `dask.bytes.read_bytes`.

If you want to write as many small files then yeah, anything should work and you can just use delayed to manage things yourself.

**Comment by shoyer** [comment] 2016-08-03 16:08
At Google, we internal file formats called SSTable and RecordIO for storing maps and lists of serialized protos. Open source variants of both can be easily found. For example, [TFRecords](https://www.tensorflow.org/versions/r0.10/api_docs/python/python_io.html#tfrecords-format-details) was open sourced as part of TensorFlow.

**Comment by Jeffrey04** [comment] 2016-08-04 03:51
> At Google, we use internal file formats called SSTable and RecordIO for storing maps and lists of serialized protos. Open source variants of both can be easily found. For example, TFRecords was open sourced as part of TensorFlow.

Just out of curiousity, if I adopt TFRecords for my project, how do I read it with `dask.bytes.read_bytes`? AFAIK each record is wrapped with some check code, and prefixed with a length, but there's no fixed delimiters between records... right?

I probably should close this, and re-post this to stackoverflow...

**Comment by mrocklin** [comment] 2016-08-04 12:24
Given that the functionality doesn't yet exist, leaving it here sounds good.

**Comment by mrocklin** [comment] 2016-08-04 12:27
Something like TFRecords is regular in size, you can expect every n*k + header_length byte to be the start of a new record.  I would load regularly spaced data like this with dask.delayed

```
@delayed
def read_chunk(filename, start, end):
    with open(filename, 'rb') as f:
        f.seek(start)
        return f.read(end - start)

chunks = [read_chunk(fn, i, i + chunksize) for i in range(header_length, filesize, chunksize)]
```

This only works because we know that data comes in regularly spaced bits.

**Comment by shoyer** [comment] 2016-08-04 15:14
Serialized protos come in arbitrary sizes -- that's why TFRecords has a length field for every record.

**Comment by shoyer** [comment] 2016-08-04 15:42
FWIW, I don't think you'll do better than simply streaming through a file format like these. They are not designed for random access. Does dask bag have a way to handle tasks that can emit multiple values?

One would also shard records across multiple TFRecords files to facilitate parallel access, but loading entire files into memory would be wasteful.

**Comment by mrocklin** [comment] 2016-09-14 14:14
OK, closing this.  Dask.bag probably won't attempt support for large monolithic files of formats that don't provide some ability to easily seek to "the next record after this byte".

**Comment by mrocklin** [comment] 2016-09-14 14:15
Of course, if you have many files then things are trivial

**Closed by mrocklin** 2016-09-14 14:14 UTC
Labels: bag, io

**Comment by chinmaychandak** [comment] 2022-04-21 12:48
Hey guys,

I have a use case where I need to read a bunch of `.protobuf` files. Each file has multiple records, and each record is prefixed with the length of the record (4 bytes as shown below). TFRecords is not being used, and there is no way to change this while generating these files, unfortunately.

This is what the current code to read/parse these files looks like:
```
import mystream.MyPacket_pb2 as pb
import struct

def read_uint32(data): # little endian
    return struct.unpack('<L', data)[0]

def parse(filepath):
    packets = []
    prefix = 4
    pos, data = 0, open(filepath, 'rb').read()
    count = 0
    while pos < len(data):
        next_pos = read_uint32(data[pos:pos+4])
        packet = pb.MyPacket()
        packet.ParseFromString(data[prefix+pos:prefix+pos+next_pos])
        pos += prefix + next_pos
        packets.append(packet)
    return packets

# Some more processing to follow after
```

I tried running this code over Dask using a simple `distributed.Client.submit()/map()`, but got the error: `Exception: cannot pickle 'google.protobuf.pyext._message.MessageDescriptor' object`.

If I understand correctly, the issue is with the Protobuf message itself not being pickle-able, so I'm thinking if using `dask.bag` or `delayed` can help in any way like mentioned in the above comments. I'm relatively new to both Protobuf and Dask collections, though, so I might be completely wrong.

This is the only place I could find a discussion b/w Dask & Protobuf (and it's been close to 6 years :)), so I thought I'd comment on this to see if any one has ideas on how we can get something like this to work.
