### ISSUE TITLE
AttributeError: 'SingleBlockManager' object has no attribute 'axes'

### ISSUE THREAD

**Issue by orf** [dask/dask#8096] opened 2021-08-29 18:18 UTC
**What happened**:

We're creating a distributed dataframe and are calling `.apply` on it, to run a model on each row. This results in the traceback shown below.

Lots of partitions appear to complete fine, but after some time it errors.

**What you expected to happen**:

It not to error.

**Minimal Complete Verifiable Example**:

```python
def load_dataset():
    dataframe = get_dataframe_from_service()  # 60,000 rows
    return ddf.from_pandas(dataframe, chunksize=10)

def run_model(row: pd.Series):
    video_uuid = row["video_uuid"]
    try:
        results = do_something_expensive()
    except Exception as e:
         return pd.Series({'video_uuid': video_uuid, 'frame': None, "bbox": None, 'error': str(e)})
    return pd.Series({'video_uuid': video_uuid, 'frame': results.frame, "bbox": results.bbox, 'error': None})

def task():
    dask.distributed.secede()
    client: dask.distributed.Client = dask.distributed.get_client()
    dataset: ddf.DataFrame = client.submit(load_dataset).result()

    frames = dataset.apply(run_model, axis=1, meta={"video_uuid": str, "frame": str, "bbox": object, "error": str})
    frames.to_parquet(
        f's3://bucket/frames/',
        schema="infer",
    )

with GatewayCluster(...):
    client: dask.distributed.Client = cluster.get_client()
    client.submit(task).result()

```

This results in:

```
...
    frames.to_parquet(
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/dataframe/core.py", line 4441, in to_parquet
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 725, in to_parquet
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/base.py", line 313, in compute_as_if_collection
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/distributed/client.py", line 2671, in get
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/distributed/client.py", line 1948, in gather
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/distributed/client.py", line 845, in sync
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/distributed/utils.py", line 326, in sync
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/distributed/utils.py", line 309, in f
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/distributed/client.py", line 1813, in _gather
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/optimization.py", line 969, in __call__
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/core.py", line 151, in get
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/core.py", line 121, in <genexpr>
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/core.py", line 121, in <genexpr>
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/core.py", line 115, in _execute_task
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/core.py", line 115, in <listcomp>
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/utils.py", line 35, in apply
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/dataframe/core.py", line 5832, in apply_and_enforce
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/dask/utils.py", line 977, in __call__
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 8736, in apply
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/pandas/core/apply.py", line 688, in apply
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/pandas/core/apply.py", line 805, in apply_standard
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/pandas/core/apply.py", line 825, in apply_series_generator
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/pandas/core/generic.py", line 5924, in copy
  File "/root/.cache/pypoetry/virtualenvs/src-LSA000g6-py3.8/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 593, in copy
AttributeError: 'SingleBlockManager' object has no attribute 'axes'
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.08.1
- Python version: 3.8
- Operating System: Debian Buster
- Install method (conda, pip, source): Pip

**Comment by jrbourbeau** [comment] 2021-08-30 15:35
Thanks for raising an issue @orf. It's unclear to me if this is an issue in Dask or pandas. Are you able to provide a minimal example for others to run? (see https://blog.dask.org/2018/02/28/minimal-bug-reports) Also, what version of `pandas` are you using?

**Comment by orf** [comment] 2021-08-30 19:26
I'm really sorry - I couldn't get a minimal reproduction to work and it was only appearing sporadically on a job that took several hours to run. Removing `schema="infer"` seemed to stop it from happening. I know this isn't too helpful, but if this bites us again I will allocate some time to dig into it more and update this issue. I thought that the traceback alone might be enough for someone more experienced with Dask internals to have a clue as to what the issue is. I actually assumed that `SingleBlockManager` was a Dask object, but it seems that it's a Pandas one instead. 

We're using the latest version of Pandas, `1.3.2`.

**Comment by jrbourbeau** [comment] 2021-08-30 20:50
I see. I certainly appreciate how difficult it can be to create a minimal reproducer, especially when the failure is sporadic. That said, I suspect it will be difficult for others to help debug things as is. 

One thing that sticks in your code snippet is that you're mixing Dask concurrent.futures interface and Dask collections (in this case a DataFrame)

```python
dataset: ddf.DataFrame = client.submit(load_dataset).result()
```

In general, we recommend not mixing these APIs as this type of "Dask inside of Dask" can lead to unexpected errors

**Comment by jsignell** [comment] 2021-09-07 13:30
I'm going to close this since it's not clear how to reproduce the issue, but please feel free to reopen if you are able to gather more information @orf

**Closed by jsignell** 2021-09-07 13:30 UTC
Labels: dataframe, needs info
