### ISSUE TITLE
Memory usage in map_blocks: drop_axis vs. chunks

### ISSUE THREAD

**Issue by striajan** [dask/dask#5594] opened 2019-11-15 09:13 UTC
Hello, I have found a possible wrong behaviour of the function `da.map_blocks`. The following code creates and persists 2D data matrix on on a worker and then maps the function `compute` on it, which returns 1D vector. This simulates application of a regression/classification on the data matrix, rows of which are formed by samples and columns by features.

```
import time
import dask.array as da
import dask.distributed as dd
import numpy as np

num_rows = 20_000
num_cols = 10_000
dtype = np.float32

def compute(_):
    return np.ones(shape=num_rows, dtype=dtype)

def main():
    with dd.LocalCluster(processes=True, n_workers=1, threads_per_worker=1, memory_limit=2e9) as cluster:
        with dd.Client(cluster) as client:
            data = da.ones(shape=(num_rows, num_cols), dtype=dtype, chunks=(num_rows, num_cols))
            data, = client.persist([data])
            dd.wait([data])

            time.sleep(2)

            # drop_axis -> data is somehow copied
            res_drop_axis = data.map_blocks(compute, dtype=dtype, drop_axis=1).compute()

            # chunks -> no data is copied
            # res_chunks = data.map_blocks(compute, dtype=dtype, chunks=(data.chunks[0], (1,))).compute()

if __name__ == '__main__':
    main()
```

If the result `res_drop_axis` is computed, the data matrix is probably somehow duplicated, as shown in the following plot of memory usage for the worker process:
![image](https://user-images.githubusercontent.com/1244058/68930769-638b1b00-078f-11ea-8945-5da454fd8bd9.png)

On the other hand, if the result `res_chunks` is computed, no data is copied:
![image](https://user-images.githubusercontent.com/1244058/68930866-9503e680-078f-11ea-92d9-f07d57147526.png)

This might be a serious issue, as the `res_drop_axis`-like approach is used in [dask-xgboost](https://github.com/dask/dask-xgboost/blob/b1cce998a4d95825d8095c7f96ce5f546ecd6fc0/dask_xgboost/core.py#L300), [dask-lightgbm](https://github.com/dask/dask-lightgbm/blob/e81fd869ec7e50d061791aaf44280c5aae1cef90/dask_lightgbm/core.py#L171) and probably in many other libraries as well.

If this was an intended behaviour, it should have been probably mentioned in the documentation of `da.map_blocks`.

**Comment by mrocklin** [comment] 2019-11-16 04:55
Thank you for the careful writeup @striajan 

> If this was an intended behaviour

Which behavior in particular?  Using too much memory?  If so then no, this is not intended behavior.

Unfortunately I don't have any particular insight to give to you.  I don't off hand know why it would use more memory here.  If you are able to track things down that would be well appreciated.

**Comment by jsignell** [comment] 2021-03-19 14:10
I am running this with the `ResourceProfiler` and can't reproduce. I am going to close this with the optimistic assumption that this issue has been resolved, but please reopen if you still see it.

```python
In [1]: import time
   ...: import dask.array as da
   ...: import dask.distributed as dd
   ...: from dask.diagnostics import ResourceProfiler
   ...: import numpy as np
   ...: 
   ...: num_rows = 20_000
   ...: num_cols = 10_000
   ...: dtype = np.float32
   ...: 
   ...: def compute(_):
   ...:     return np.ones(shape=num_rows, dtype=dtype)
   ...: 
   ...: 
   ...: with dd.LocalCluster(processes=True, n_workers=1, threads_per_worker=1
   ...: , memory_limit=2e9) as cluster:
   ...:     with dd.Client(cluster) as client:
   ...:         with ResourceProfiler() as prof:
   ...:             data = da.ones(shape=(num_rows, num_cols), dtype=dtype, ch
   ...: unks=(num_rows, num_cols))
   ...:             data, = client.persist([data])
   ...:             dd.wait([data])
   ...: 
   ...:             time.sleep(2)
   ...: 
   ...:             # drop_axis -> data is somehow copied
   ...:             res_drop_axis = data.map_blocks(compute, dtype=dtype, drop
   ...: _axis=1).compute()
   ...: 
   ...:             # chunks -> no data is copied
   ...:             # res_chunks = data.map_blocks(compute, dtype=dtype, chunk
   ...: s=(data.chunks[0], (1,))).compute()
   ...: prof.visualize()
```

![image](https://user-images.githubusercontent.com/4806877/111792847-0b8c8900-889b-11eb-9cd5-a19ce309844a.png)

```python
In [1]: import time
   ...: import dask.array as da
   ...: import dask.distributed as dd
   ...: from dask.diagnostics import ResourceProfiler
   ...: import numpy as np
   ...: 
   ...: num_rows = 20_000
   ...: num_cols = 10_000
   ...: dtype = np.float32
   ...: 
   ...: def compute(_):
   ...:     return np.ones(shape=num_rows, dtype=dtype)
   ...: 
   ...: 
   ...: with dd.LocalCluster(processes=True, n_workers=1, threads_per_worker=1
   ...: , memory_limit=2e9) as cluster:
   ...:     with dd.Client(cluster) as client:
   ...:         with ResourceProfiler() as prof:
   ...:             data = da.ones(shape=(num_rows, num_cols), dtype=dtype, ch
   ...: unks=(num_rows, num_cols))
   ...:             data, = client.persist([data])
   ...:             dd.wait([data])
   ...: 
   ...:             time.sleep(2)
   ...: 
   ...:             # drop_axis -> data is somehow copied
   ...:             # res_drop_axis = data.map_blocks(compute, dtype=dtype, drop
   ...: _axis=1).compute()
   ...: 
   ...:             # chunks -> no data is copied
   ...:             res_chunks = data.map_blocks(compute, dtype=dtype, chunk
   ...: s=(data.chunks[0], (1,))).compute()
   ...: prof.visualize()
```

![image](https://user-images.githubusercontent.com/4806877/111793052-40004500-889b-11eb-942b-be47027805a0.png)

**Closed by jsignell** 2021-03-19 14:10 UTC
Labels: array
