### ISSUE TITLE
Exception: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by bhagatsajan0073** [dask/dask#7540] opened 2021-04-08 09:17 UTC
**Code Base**

```python
import dask
from dask.distributed import Client,progress
import joblib
import pandas as pd
import dask.dataframe as dd

client = Client('127.0.0.1:8786')
client.ncores()
client.restart()

customer=pd.DataFrame({
    "customer_id":list(range(1,100)),
    "Rank" : list(range(1,100))
})

df = dd.from_pandas(customer,npartitions=1)
df.head()
```

### Same error is coming on dask cluster with dask version 2021.04.0

----------------------------------------------------------------
```python
client.get_versions(check=True)

{'scheduler': {'host': {'python': '3.8.0.final.0',
   'python-bits': 64,
   'OS': 'Linux',
   'OS-release': '5.4.72-microsoft-standard-WSL2',
   'machine': 'x86_64',
   'processor': '',
   'byteorder': 'little',
   'LC_ALL': 'C.UTF-8',
   'LANG': 'C.UTF-8'},
  'packages': {'python': '3.8.0.final.0',
   'dask': '2.30.0',
   'distributed': '2.30.1',
   'msgpack': '1.0.0',
   'cloudpickle': '1.6.0',
   'tornado': '6.1',
   'toolz': '0.11.1',
   'numpy': '1.18.1',
   'lz4': '3.1.1',
   'blosc': '1.9.2'}},
 'workers': {'tcp://172.21.0.2:46475': {'host': {'python': '3.8.0.final.0',
    'python-bits': 64,
    'OS': 'Linux',
    'OS-release': '5.4.72-microsoft-standard-WSL2',
    'machine': 'x86_64',
    'processor': '',
    'byteorder': 'little',
    'LC_ALL': 'C.UTF-8',
    'LANG': 'C.UTF-8'},
   'packages': {'python': '3.8.0.final.0',
    'dask': '2.30.0',
    'distributed': '2.30.1',
    'msgpack': '1.0.0',
    'cloudpickle': '1.6.0',
    'tornado': '6.1',
    'toolz': '0.11.1',
    'numpy': '1.18.1',
    'lz4': '3.1.1',
    'blosc': '1.9.2'}}},
 'client': {'host': {'python': '3.8.5.final.0',
   'python-bits': 64,
   'OS': 'Windows',
   'OS-release': '10',
   'machine': 'AMD64',
   'processor': 'Intel64 Family 6 Model 158 Stepping 10, GenuineIntel',
   'byteorder': 'little',
   'LC_ALL': 'None',
   'LANG': 'None'},
  'packages': {'python': '3.8.5.final.0',
   'dask': '2.30.0',
   'distributed': '2.30.1',
   'msgpack': '1.0.2',
   'cloudpickle': '1.6.0',
   'tornado': '6.1',
   'toolz': '0.11.1',
   'numpy': '1.19.2',
   'lz4': None,
   'blosc': None}}}
```

### Error Message coming on operation with dask dataframe wherever a compute operation is happening 
---------------------------------------------------------------------------
```python-traceback
Exception                                 Traceback (most recent call last)
<ipython-input-30-9074f592b684> in <module>
      1 df = dd.from_pandas(customer,npartitions=1)
      2 df = df.persist()
----> 3 df.head()

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\dask\dataframe\core.py in head(self, n, npartitions, compute)
   1004             Whether to compute the result, default is True.
   1005         """
-> 1006         return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
   1007 
   1008     def _head(self, n, npartitions, compute, safe):

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\dask\dataframe\core.py in _head(self, n, npartitions, compute, safe)
   1037 
   1038         if compute:
-> 1039             result = result.compute()
   1040         return result
   1041 

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\dask\base.py in compute(self, **kwargs)
    165         dask.base.compute
    166         """
--> 167         (result,) = compute(self, traverse=False, **kwargs)
    168         return result
    169 

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\dask\base.py in compute(*args, **kwargs)
    450         postcomputes.append(x.__dask_postcompute__())
    451 
--> 452     results = schedule(dsk, keys, **kwargs)
    453     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    454 

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2723                     should_rejoin = False
   2724             try:
-> 2725                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2726             finally:
   2727                 for f in futures.values():

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\client.py in gather(self, futures, errors, direct, asynchronous)
   1984             else:
   1985                 local_worker = None
-> 1986             return self.sync(
   1987                 self._gather,
   1988                 futures,

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    830             return future
    831         else:
--> 832             return sync(
    833                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    834             )

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\tornado\gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

c:\users\bhaga\anaconda3\envs\mlq-env\lib\site-packages\distributed\client.py in _gather(self, futures, errors, direct, local_worker)
   1849                             exc = CancelledError(key)
   1850                         else:
-> 1851                             raise exception.with_traceback(traceback)
   1852                         raise exc
   1853                     if errors == "skip":

Exception: maximum recursion depth exceeded while calling a Python object
```

**Comment by jrbourbeau** [comment] 2021-04-08 14:47
Closing as a duplicate of https://github.com/dask/distributed/issues/4684

**Closed by jrbourbeau** 2021-04-08 14:47 UTC
