### ISSUE TITLE
dask cannot read multi-columns pandas dataframe

### ISSUE THREAD

**Issue by TommasoBendinelli** [dask/dask#7643] opened 2021-05-11 13:06 UTC
I have a folder of pandas dataframe with date-time index, and two-level columns. They are stored as parquet files inside a folder.
When trying to load them via:

```python
df = dd.read_parquet(glob.glob("data/train_data_chunks/"))
```

I am getting the following value error:
```
*** ValueError: Length of new names must be 1, got 2
```

Loading anyone of these in vanilla pandas dataframe works just fine

**Comment by jsignell** [comment] 2021-05-13 14:22
Thanks for reporting this. I was able to reproduce this with the following code:

```python
import dask
import dask.dataframe as dd

ddf = dask.datasets.timeseries(freq="1H")
ddf2 = ddf.groupby("name").agg(["mean", "max"])
ddf2.compute().to_parquet("data")
dd.read_parquet("data")
```

Using both fastparquet and pyarrow I got the following error:

```python-traceback
~/dask/dask/dataframe/io/utils.py in _meta_from_dtypes(to_read_columns, file_dtypes, index_cols, column_index_names)
     93 
     94     if len(column_index_names) > 1:
---> 95         df.columns.names = column_index_names
     96     return df
     97 

~/conda/envs/dask-dev/lib/python3.8/site-packages/pandas/core/indexes/base.py in _set_names(self, values, level)
   1301             raise ValueError("Names must be a list-like")
   1302         if len(values) != 1:
-> 1303             raise ValueError(f"Length of new names must be 1, got {len(values)}")
   1304 
   1305         # GH 20527

ValueError: Length of new names must be 1, got 2
```

I am still looking into possible fixes.

**Comment by jsignell** [comment] 2021-05-13 14:30
It seems like there isn't support in the dask parquet for MultiIndex does that seem like an accurate assessment @martindurant @rjzamora?

**Comment by rjzamora** [comment] 2021-05-13 15:08
>It seems like there isn't support in the dask parquet for MultiIndex

Right - I think the column index is the primary challenge here on the read side (since you can always specify `index=False` to avoid creating a row multiIndex.   However, in general, Dask/parquet does not make any attempt to support a multiIndex (yet).

**Comment by bryanwweber** [comment] 2022-03-28 18:03
> > It seems like there isn't support in the dask parquet for MultiIndex
> 
> Right - I think the column index is the primary challenge here on the read side (since you can always specify `index=False` to avoid creating a row multiIndex. However, in general, Dask/parquet does not make any attempt to support a multiIndex (yet).

In that case, I think this is a duplicate of #1493. Can we close this issue in favor of that one (or vice versa)?

**Comment by bryanwweber** [comment] 2022-04-22 16:34
Since there was no reply, I'm closing this as a duplicate of #1493. Please feel free to reopen if it seems distinct.

**Closed by bryanwweber** 2022-04-22 16:34 UTC
Labels: dataframe, io, parquet
