### ISSUE TITLE
Creating a new index fails on the dask dataframe that already is indexed and has empty partition

### ISSUE THREAD

**Issue by bkyryliuk** [dask/dask#2408] opened 2017-06-03 01:56 UTC
Creating a new index fails on the dask dataframe that already is indexed and has empty partition.
The code fails here:
https://github.com/dask/dask/blob/master/dask/dataframe/shuffle.py#L61

Stacktrace:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-4-7fd9e5f4f156> in <module>()
      6 
      7 
----> 8 exploded_cs.set_index('geohash', npartitions=100)

/Users/bogdankyryliuk/miniconda3/envs/signals/lib/python3.6/site-packages/dask/dataframe/core.py in set_index(***failed resolving arguments***)
   2263             from .shuffle import set_index
   2264             return set_index(self, other, drop=drop, npartitions=npartitions,
-> 2265                              divisions=divisions, **kwargs)
   2266 
   2267     @derived_from(pd.DataFrame)

/Users/bogdankyryliuk/miniconda3/envs/signals/lib/python3.6/site-packages/dask/dataframe/shuffle.py in set_index(df, index, npartitions, shuffle, compute, drop, upsample, divisions, **kwargs)
     77                 divisions = [divisions[i] for i in indexes]
     78 
---> 79         if (mins == sorted(mins) and maxes == sorted(maxes) and
     80                 all(mx < mn for mx, mn in zip(maxes[:-1], mins[1:]))):
     81             divisions = mins + [maxes[-1]]

TypeError: '<' not supported between instances of 'str' and 'float'
> /Users/bogdankyryliuk/miniconda3/envs/signals/lib/python3.6/site-packages/dask/dataframe/shuffle.py(79)set_index()
     77                 divisions = [divisions[i] for i in indexes]
     78 
---> 79         if (mins == sorted(mins) and maxes == sorted(maxes) and
     80                 all(mx < mn for mx, mn in zip(maxes[:-1], mins[1:]))):
     81             divisions = mins + [maxes[-1]]
```

Reproducible example:
```
import pandas as pd
from dask import dataframe as dd
df = pd.DataFrame({'a':range(10)}); df['b'] = df['a'] % 3; df['c'] = df['b'].astype(str)
ddf = dd.from_pandas(df, npartitions=3)
ddf=ddf.set_index('b')
ddf=ddf.repartition(npartitions=3)
ddf.get_partition(0).compute()
ddf = ddf.set_index('c')
```

Looks like here are 2 issues:
1.  ddf.get_partition(0).compute() - somehow is empty
2. ddf = ddf.set_index('c') .- repartitioning fails when empty partitions exist

**Comment by bkyryliuk** [comment] 2017-06-03 02:07
cc @jdanbrown, @brianmartin

**Comment by mrocklin** [comment] 2017-06-03 03:09
Thanks for the repeatable example and the well written issue.  This is very helpful.  It looks like we're taking maxes of empty indexes, which produces nans which then get in the way of an optimization check.  We should be able to just filter these out.  If no one gets to this before me then I'll try to handle it in the next couple of days.  (or, if you all are interested, it'd be great to take on more contributors).

**Comment by mrocklin** [comment] 2017-06-05 17:08
I think that this is fixed in https://github.com/dask/dask/pull/2413

**Closed** 2017-06-07 12:27 UTC

**Comment by bkyryliuk** [comment] 2017-06-13 02:24
I've got the issue one more time somehow :(

```
/Users/bogdankyryliuk/miniconda3/envs/signals/lib/python3.6/site-packages/dask/dataframe/shuffle.py in set_index(df, index, npartitions, shuffle, compute, drop, upsample, divisions, **kwargs)
     80         maxes = remove_nans(maxes)
     81 
---> 82         if (mins == sorted(mins) and maxes == sorted(maxes) and
     83                 all(mx < mn for mx, mn in zip(maxes[:-1], mins[1:]))):
     84             divisions = mins + [maxes[-1]]

TypeError: '<' not supported between instances of 'float' and 'str'

```

Working on the reproducible example.

**Comment by bkyryliuk** [comment] 2017-06-13 02:36
```
import pandas as pd
import numpy as np
from dask import dataframe as dd
df = pd.DataFrame({'a':range(10)}); df['b'] = df['a'] % 3; df['c'] = df['b'].astype(str)
ddf = dd.from_pandas(df, npartitions=3)
ddf.set_index('c', divisions=[1, 2, np.NaN]).compute()
```

**Comment by mrocklin** [comment] 2017-06-13 11:22
The reproducible example is expected to fail because the data, `ddf['c']`, is of type `str` while the divisions are of type `float`.

**Comment by mrocklin** [comment] 2017-06-13 11:22
If this dtype mismatch is happening in the wild then it would be good to know how

**Comment by bkyryliuk** [comment] 2017-06-13 14:50
I am trying to find our what's the reason.  Somehow first and last
partitions are np.NaN, other ones are strings.
