### ISSUE TITLE
Dask not communicating to all workers in the cluster

### ISSUE THREAD

**Issue by dhanababum** [dask/dask#3912] opened 2018-08-28 17:24 UTC
Hi Team and @mrocklin ,

I am trying to configure dask distributed cluster from this https://distributed.readthedocs.io/en/latest/setup.html. And I did successfully with Scheduluer and 2 worker nodes. In each worker node I have created local test.csv file and code looks like

**worker1 test.csv:**

```
X,Y
x1,2
x2,3
x1,1
```
**worker2 test.csv:**

```
X,Y
x4,2
```
**Code Running in Master node :**
```
from dask.distributed import Client
import dask.dataframe as dd
client = Client('scheduler-address:8786')
df = dd.read_csv('*.csv')
df = client.persist(df)
df.head()
```

**Output of above code:**
```
X,Y
x1,2
x2,3
x1,1
```
`But Expected output:`
```
X,Y
x1,2
x2,3
x1,1
x4,2
```
From the above observation, if run the above code it is contacting only single worker node. I have removed Worker-1 from the cluster  then I ran the ```df.head()``` and interestingly I got Worker2 data,

```
X,Y
x4,2
```
I am not sure what I was missing here ?

**Comment by martindurant** [comment] 2018-08-29 20:42
This is expected behaviour. When you do `df = dd.read_csv('*.csv')`, the paths are resolved in the client, and sent to workers - in this case, just the one file, so one loader task is generated. It so happens that each worker has such a named file locally, so which data you get depends on which worker executes your one task.
What you actually want is a common file-system (on the cluster or remote) for the whole cluster, so you can find files on the client and read them from workers and be sure you are referring to the same thing. You *could* make custom `delayed` function that loads data from a known location on each worker machine and then use `dd.from_delayed()` to create your dataframe, but you will need to figure out how to ensure that the task gets executed exactly once on each worker. This is not a typical workflow.

Suggest to close as not a bug.

**Comment by dhanababum** [comment] 2018-08-30 02:43
Thank you for detailed information, Earlier I was thought dask will provide data locality but yesterday myself I did some research and found exactly what you said, Ofcourse dask relays on pandas to read_csv. I am looking for each worker node contains some data and client starts computation then each worker collect their own data and compute it then result send back to the client.

**Closed** 2018-08-30 02:44 UTC
