### ISSUE TITLE
Writing stacked delayed dask arrays raises exception

### ISSUE THREAD

**Issue by chrisroat** [dask/dask#5763] opened 2020-01-03 19:01 UTC
Here is code to read 4 arrays from a hdf5 file, stack them, and output to zarr. It reads via the delayed mechanism because my realworld application works on h5py files on GCS, which must be read this way. If I write a single array (change `data.to_zarr` to `arrays[0].to_zarr`), it works. Writing the stacked array leads to an exception.

Is there some argument I missed somewhere?

Using h5py 2.10.0 and dask 2.9.1.

```python
import dask
import dask.array as da
from dask.diagnostics import ProgressBar
import h5py
import numpy as np

num_chn = 2
shape = (8, 128, 128)
in_file_local = '/tmp/in_file_local.h5'
out_store = '/tmp/out_store.zarr'

# Write data                                                                                                             
arr = np.zeros(shape, dtype=np.uint16)
with h5py.File(in_file_local, 'w') as h5file:
   for i in range(num_chn):
        h5file.create_dataset('data%d' % i, data=arr, chunks=(8, 128, 128))

# Read data via delayed functions to mimic as real application that reads h5py from GCS                                  
def get_data(fname, group):
    h5f = open(fname, 'rb')
    return h5py.File(h5f, 'r').get(group)

lazy = [dask.delayed(get_data)(in_file_local, 'data%d' % i) for i in range(num_chn)]
arrays = [da.from_delayed(x, shape=shape, dtype=np.uint16) for x in lazy]
data = da.stack(arrays)

with ProgressBar():
    data.to_zarr(out_store, compression='gzip', overwrite=True)
```

Exception:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/selections.py", line 85, in select
    int(a)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "trial2.py", line 31, in <module>
    data.to_zarr(out_store, compression='gzip', overwrite=True)
  File "/usr/local/lib/python3.6/dist-packages/dask/array/core.py", line 2304, in to_zarr
    return to_zarr(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/array/core.py", line 2914, in to_zarr
    return arr.store(z, lock=False, compute=compute, return_stored=return_stored)
  File "/usr/local/lib/python3.6/dist-packages/dask/array/core.py", line 1367, in store
    r = store([self], [target], **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/array/core.py", line 923, in store
    result.compute(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/base.py", line 165, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/threaded.py", line 81, in get
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/usr/local/lib/python3.6/dist-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/usr/local/lib/python3.6/dist-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/dataset.py", line 553, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/selections.py", line 90, in select
    sel[args]
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/selections.py", line 348, in __getitem__
    args = _expand_ellipsis(args, len(self.shape))
  File "/usr/local/lib/python3.6/dist-packages/h5py/_hl/selections.py", line 440, in _expand_ellipsis
    raise TypeError("Argument sequence too long")
TypeError: Argument sequence too long
```

**Comment by mrocklin** [comment] 2020-01-04 16:23
You're creating a dask array from a delayed value that creates an H5Py dataset, not a Numpy-like array.  H5Py datasets in many ways look like Numpy arrays, but don't do many things, like advanced slicing or computational operations.  I recommend having the `get_data` function return a numpy array.  

This should work


```python
def get_data(fname, group):
    h5f = open(fname, 'rb')
    return h5py.File(h5f, 'r').get(group)[:]  # note the [:] which gets all data as a numpy array
```

Closing this for now.  If there is still some other problem then please let us know and we'll reopen.

**Closed by mrocklin** 2020-01-04 16:23 UTC

**Comment by chrisroat** [comment] 2020-01-04 17:49
Makes sense.  Thank you.  To check my understanding, this means there isn't a way to take advantage of the chunking within the hdf file?

**Comment by mrocklin** [comment] 2020-01-04 17:52
You would use the da.from_array function.  See
https://docs.dask.org/en/latest/array-creation.html

**Comment by chrisroat** [comment] 2020-01-04 17:54
I'm not sure I follow.  Does `get_data` use `da.from_array` and return a dask array?

**Comment by mrocklin** [comment] 2020-01-04 17:57
Have you read through that page yet?  It has an example using from_array
and stack that I think does exactly what you're trying to do.

**Comment by chrisroat** [comment] 2020-01-04 18:18
I did not see the same use case of using `from_delayed`, `from_array`, and `stack`.  I see `from_delayed` used once, with something returning a numpy array (your original suggestion).  And I do see `from_array` on h5py.File using in concatentation, but not in a delayed context.

It wasn't clear to me that one can return an array (which is already 'delayed' in some sense) in a function wrapped by `dask.from_delayed`.  Empirically, it works for me locally.

The reason I was asking is because I find when I change environment, say to different schedulers or to reading for GCS, I sometimes hit little snags.  This mini investigation started because h5py.File cannot be pickled.  Then I hit the snag that opened this issue.  I appreciate your help in showing me that additionally, the hdf datasets don't have all the functionality needed by dask, and so must be wrapped if used in a delayed context.

**Comment by mrocklin** [comment] 2020-01-04 18:32
Ah, I see.  Yes so from_delayed is used to produce single chunked dask arrays.  You could make a function that opens an h5py file, gets a specific chunk of that file, and then closes the file and returns the numpy array.  I think that this is what Xarray does.  There was some extensive conversation on this topic here: https://github.com/pydata/xarray/issues/798

With your current approach you're returning an h5py dataset object as a task.  If you now want other workers to pull pieces off of that dataset object it may need to move between workers, and so you're likely to run into serialization issues regardless.  There was some work to special case h5py dataset objects in dask (see `distributed/protocol/h5py.py`) and those may or may not help here, but it's hard to say.

**Comment by mrocklin** [comment] 2020-01-04 18:33
I encourage you to raise a new issue asking for documentation on how to load an HDF5 dataset hosted on cloud storage into a Dask array.  The bug report you've listed here is, I'm going to claim, "not a bug" but the general thing that you're trying to accomplish seems valuable to me.  It would be good to make it easier for users.

**Comment by mrocklin** [comment] 2020-01-04 18:34
It would be useful if, in that issue, you could also point to the work that caused h5py datasets to point to files on cloud storage as well as, if you have it, a public example of a simple file that devs can play with.
