### ISSUE TITLE
dask.DataFrame.mask doc wrong

### ISSUE THREAD

**Issue by paulochf** [dask/dask#2450] opened 2017-06-09 23:09 UTC
I was looking for some `pandas.DataFrame.replace` equivalent, then I found that [I can do with mask](https://stackoverflow.com/a/40899490).

So I went to [the docs](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.mask) and saw that there's some stuff:

![image](https://user-images.githubusercontent.com/107470/26997295-cbeecc30-4d4e-11e7-9ed4-3ba91f0482d7.png)

Then, I tried the `inplace` parameter, but I got the error `TypeError: mask() got an unexpected keyword argument 'inplace'`. I found [`mask` in the code](https://github.com/dask/dask/blob/master/dask/dataframe/core.py#L1377) but didn't see those parameters mentioned except for `cond` and `other`.

So I ask:
1) Is `dask.DataFrame.mask` doc wrong or outdated?
2) Do the other functions' docs have the same problem?

Thanks!

**Comment by mrocklin** [comment] 2017-06-10 12:26
Yes, see https://github.com/dask/dask/issues/1815

**Comment by paulochf** [comment] 2017-06-12 17:08
Oh, I see...

Although I did read the issue you referenced and the others they ref, I don't know where I should ask this. How are you going to tackle the problem? :thinking: 

I can only think about there could be some kind of effort in writing docstrings in the outer layer and use an automatic documentation framework to extract them.

I would help to write some docs, at least for those functions (the basic ones) I'm using right now, but I'm afraid to write something wrong or miss another because I'm getting used to dask yet.

I'm open to ideas, and I this issue can be closed, as there are others relating to the problem.

Thanks!

**Comment by mrocklin** [comment] 2017-06-12 17:10
I have no immediate plans to address the problem personally.  There are some mechanisms to intentionally omit certain lines I think (cc @sinhrks).  We could also just copy-paste existing docstrings (making sure that we copy the pandas license file) and then remove the lines that don't make sense for us.

**Comment by paulochf** [comment] 2017-06-14 19:51
As you see fit!

**Comment by jcrist** [comment] 2018-01-30 01:00
Closing as duplicate of #1815.

**Closed by jcrist** 2018-01-30 01:00 UTC
