### ISSUE TITLE
ValueError with renaming series after dd.read_csv

### ISSUE THREAD

**Issue by gerrymanoim** [dask/dask#6970] opened 2020-12-15 00:54 UTC
**What happened**:

`ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().` occurs when you try to rename a series from a dataframe created from `dd.read_csv`. This does not occur on 2.30.0 or when using `dd.from_pandas`. 

**What you expected to happen**:

A series with a renamed column. 

**Minimal Complete Verifiable Example**:

First, working in 2.30.0

```python
In [1]: import dask.dataframe as dd

In [2]: df = dd.read_csv("~/tmp/tmp.csv")

In [3]: df
Out[3]:
Dask DataFrame Structure:
                  v1      v2
npartitions=1
               int64  object
                 ...     ...
Dask Name: read-csv, 1 tasks

In [4]: df.v1
Out[4]:
Dask Series Structure:
npartitions=1
    int64
      ...
Name: v1, dtype: int64
Dask Name: getitem, 2 tasks

In [5]: df.v1.rename("test")
Out[5]:
Dask Series Structure:
npartitions=1
    int64
      ...
Name: test, dtype: int64
Dask Name: rename, 3 tasks

In [6]: df.v1.rename("test").compute()
Out[6]:
0    1
1    2
2    3
Name: test, dtype: int64

In [7]: import dask

In [8]: dask.__version__
Out[8]: '2.30.0'
```

Now - the same operation in 2020.12.0:

```python
In [1]: import dask.dataframe as dd

In [2]: df = dd.read_csv("~/tmp/tmp.csv")

In [3]: df.v1.rename("test").compute()
<large traceback>
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

However, the following works just fine:

```python
In [6]: import pandas as pd
In [8]: df2 = dd.from_pandas(pd.DataFrame({'v1': [1,2,3], 'v2':['a', 'b','c']}), npartitions=1)

In [9]: df2.v1.rename("tmp")
Out[9]:
Dask Series Structure:
npartitions=1
0    int64
2      ...
Name: tmp, dtype: int64
Dask Name: rename, 3 tasks

In [10]: df2.v1.rename("tmp").compute()
Out[10]:
0    1
1    2
2    3
Name: tmp, dtype: int64
```

**Anything else we need to know?**:

My csv file is structured as below, but it doesn't seem to really matter. 

| v1 | v2 |
| --- | --- | 
| 1 | a | 
| 2 | b |
| 3 | c | 
  

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.8.6
- Operating System: Ubuntu 18.04
- Install method (conda, pip, source): condas

**Comment by jsignell** [comment] 2020-12-15 15:58
Thanks for raising this I can reproduce with this test case:

```python
from dask.datasets import timeseries
import dask.dataframe as dd

df = timeseries(freq="1D").compute()
df.to_csv("tmp.csv")

ddf = dd.read_csv("tmp.csv")
ddf.name.rename("test").compute()
```

**Comment by jsignell** [comment] 2020-12-18 19:20
Just tried to reproduce again on dask master and it seems like the issue is resolved. I am going to close this, but please reopen if you run into it again.

**Closed by jsignell** 2020-12-18 19:20 UTC
