### ISSUE TITLE
read_csv() not reading data properly and dataframe.set_index() causing loss of data

### ISSUE THREAD

**Issue by LazyTrader** [dask/dask#6877] opened 2020-11-23 06:39 UTC
**What happened**:

I have a CSV file containing approximately 237 million rows of data ranging from 03/08/2003 - 17/11/2020. After loading the CSV file as a dataframe, I end up with only 1392158 rows. Setting the date column as the index also always results in the loss of more values and I get a dataframe containing data that ranges from 01/01/2004 - 31/12/2019.

**What you expected to happen**:

The resulting dataframe should contain all rows of data and should still contain data ranging from 08/03/2003 - 17/11/2020.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd

Ticks = dd.read_csv("Data.csv", parse_dates = True, names = ["Date", "Ask", "Bid" ,"Ask Vol", "Bid Vol"])
Ticks = Ticks.loc[  :  , "Date" : "Bid"]
Ticks["Mid"] = (Ticks["Ask"] + Ticks["Bid"]) / 2

print(Ticks.head())
print(Ticks.tail())

Ticks = Ticks.set_index("Date")

print(Ticks.head())
print(Ticks.tail())
```

Print outputs:

```
                      Date      Ask      Bid      Mid
0  03.08.2003 21:00:07.389  0.65157  0.65137  0.65147
1  03.08.2003 21:00:07.925  0.65163  0.65147  0.65155
2  03.08.2003 21:00:38.077  0.65170  0.65150  0.65160
3  03.08.2003 21:00:44.188  0.65178  0.65148  0.65163
4  03.08.2003 21:00:55.706  0.65172  0.65152  0.65162

                            Date      Ask      Bid       Mid
1392154  17.11.2020 23:59:34.907  0.72973  0.72962  0.729675
1392155  17.11.2020 23:59:45.940  0.72974  0.72962  0.729680
1392156  17.11.2020 23:59:57.351  0.72974  0.72961  0.729675
1392157  17.11.2020 23:59:57.452  0.72971  0.72960  0.729655
1392158  17.11.2020 23:59:57.554  0.72970  0.72958  0.729640

                             Ask      Bid      Mid
Date
01.01.2004 00:00:04.039  0.75167  0.75147  0.75157
01.01.2004 00:00:04.512  0.75180  0.75160  0.75170
01.01.2004 00:00:07.291  0.75190  0.75170  0.75180
01.01.2004 00:00:12.150  0.75164  0.75144  0.75154
01.01.2004 00:00:12.623  0.75181  0.75161  0.75171

                             Ask      Bid       Mid
Date
31.12.2019 21:59:43.026  0.70178  0.70159  0.701685
31.12.2019 21:59:43.878  0.70175  0.70150  0.701625
31.12.2019 21:59:44.029  0.70178  0.70152  0.701650
31.12.2019 21:59:45.070  0.70169  0.70138  0.701535
31.12.2019 21:59:45.121  0.70195  0.70115  0.701550
```

**Environment**:

- Dask version: 2.30.1
- Python version: 3.8.5
- Operating System: Windows 10 home
- Install method (conda, pip, source): Conda

**Comment by rjzamora** [comment] 2020-11-23 16:00
Thanks for raising @LazyTrader - Can you include a mechanism to generate `"Data.csv"` in your example.  It will be easier to help if I can reproduce the problem locally and it will save a lot of time if I can just copy paste an example :)

**Comment by LazyTrader** [comment] 2020-11-26 01:19
Could try this one as a contrived example. :)

```
import numpy as np

Array = np.random.randn(2000000, 3)
np.savetxt("Data.csv", Array, delimiter = ",")
```

**Comment by rjzamora** [comment] 2020-11-30 16:21
@LazyTrader - Thank you for sharing a full example.   I am unable to reproduce data loss on my end (`len(Ticks)` is `2000000` before and after setting the index).  Note that set_index will result in a global sort of your data with respect to the new index, so [your example above](https://github.com/dask/dask/issues/6877#issue-748517059) doesn't necessarily show any data loss either.

Can you confirm that your `len` result is not `2000000` for the `np.random.randn(2000000, 3)` example you shared?

**Comment by LazyTrader** [comment] 2020-12-01 00:54
`"Data.csv"` might be too small for the issue to show up. You could try playing around with `Array = np.random.randn(2000000, 3)` and varying the first value from 2000000 - 200000000. The actual file is about 12 close to 13 gigabytes

**Comment by rjzamora** [comment] 2020-12-01 22:54
I am not able to reproduce the issue with an `np.random`-generated CSV file (I tried up to 200mil rows).  I am not sure what would be causing you to lose data on the read, but the loss of data after `set_index` may be related to the datetime precision (see #6864).

**Comment by martindurant** [comment] 2021-03-19 14:22
I a closing this, as we were not able to recreate the problem. If a case can be generated that clearly shows it, then please reopen!

**Closed by martindurant** 2021-03-19 14:22 UTC
Labels: dataframe, needs info
