### ISSUE TITLE
Usage of numpy quantile/percentile functions on da.array broken on distributed scheduler in 2021.08.0

### ISSUE THREAD

**Issue by TAdeJong** [dask/dask#8182] opened 2021-09-27 15:25 UTC
Using `np.quantile`/`np.nanquantile`/`np.percentile`/`np.nanpercentile` on dask arrays while running a localcluster broke in 2021.08.0, while it still worked in 2021.06.2. 

Especially for `np.nanquantile` the workaround is non-trivial (`da.percentile(X[~np.isnan(X)].flatten(), q * 100).compute()` seems to give the desired result).

To be fair, using these functions has been throwing a future warning for some time now:

```
FutureWarning: The `numpy.quantile` function is not implemented by Dask array. You may want to use the da.map_blocks function or something similar to silence this warning. Your code may stop working in a future release.
```

But the suggested workaround using `map_blocks` will not work for such a reduction type operation and the error is not very descriptive.

When using a LocalCluster, a `KeyError: '__name__'` is now raised.

```python
import dask.array as da
import numpy as np
from dask.distributed import Client

X = da.random.random((1000,1000))
print(np.quantile(X, 0.1)) # Works with a FutureWarning

client = Client() # Create a client to switch to a LocalCluster

Y = da.random.random((1000,1000))
print(np.quantile(Y, 0.1))  # Does not work
```
<details>
<summary>trace</summary>

```python

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-5-7555cb29deeb> in <module>
----> 1 np.quantile(Y, 0.1)  # Does not work

<__array_function__ internals> in quantile(*args, **kwargs)

~/anaconda3/envs/pyL5/lib/python3.7/site-packages/dask/array/core.py in __array_function__(self, func, types, args, kwargs)
   1553 
   1554         if not hasattr(module, func.__name__):
-> 1555             return handle_nonmatching_names(func, args, kwargs)
   1556 
   1557         da_func = getattr(module, func.__name__)

~/anaconda3/envs/pyL5/lib/python3.7/site-packages/dask/array/core.py in handle_nonmatching_names(func, args, kwargs)
   1534                 # again and it gets the chance to dispatch to the right
   1535                 # implementation.
-> 1536                 args, kwargs = compute(args, kwargs)
   1537                 return func(*args, **kwargs)
   1538 

~/anaconda3/envs/pyL5/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    566         postcomputes.append(x.__dask_postcompute__())
    567 
--> 568     results = schedule(dsk, keys, **kwargs)
    569     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    570 

~/anaconda3/envs/pyL5/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2658             retries=retries,
   2659             user_priority=priority,
-> 2660             actors=actors,
   2661         )
   2662         packed = pack_data(keys, futures)

~/anaconda3/envs/pyL5/lib/python3.7/site-packages/distributed/client.py in _graph_to_futures(self, dsk, keys, workers, allow_other_workers, priority, user_priority, resources, retries, fifo_timeout, actors)
   2588                     "fifo_timeout": fifo_timeout,
   2589                     "actors": actors,
-> 2590                     "code": self._get_computation_code(),
   2591                 }
   2592             )

~/anaconda3/envs/pyL5/lib/python3.7/site-packages/distributed/client.py in _get_computation_code()
   2523         for fr, _ in traceback.walk_stack(None):
   2524             if pattern is None or (
-> 2525                 not pattern.match(fr.f_globals["__name__"])
   2526                 and fr.f_code.co_name not in ("<listcomp>", "<dictcomp>")
   2527             ):

KeyError: '__name__'
```
</details>

**Anything else we need to know?**:

This could have been titled "feature request: implement wider range of quantile-like functions for da.array", but the specificity of the error seemed like it might signal some lower-lying issues, so I hope this write-up with MWE can help.

**Environment**:

- Dask version: 2021.08.0
- Python version: 3.8
- Operating System: Ubuntu
- Install method (conda, pip, source): conda

**Comment by jcrist** [comment] 2021-09-27 19:38
Thanks for the reproducible example @TAdeJong. This is a duplicate of https://github.com/dask/distributed/issues/5224, recently fixed by https://github.com/dask/distributed/pull/5236. I can confirm that on distributed `main` things now work again (though with warnings still).

```python
In [1]: import dask.array as da
   ...: import numpy as np
   ...: from dask.distributed import Client
   ...: 
   ...: X = da.random.random((1000,1000))
   ...: print(np.quantile(X, 0.1)) # Works with a FutureWarning
   ...: 
   ...: client = Client() # Create a client to switch to a LocalCluster
   ...: 
   ...: Y = da.random.random((1000,1000))
   ...: print(np.quantile(Y, 0.1))  # Does not work
/home/jcristharif/miniconda3/envs/dask/lib/python3.9/site-packages/dask-2021.9.1-py3.9.egg/dask/array/core.py:1503: FutureWarning: The `numpy.quantile` function is not implemented by Dask array. You may want to use the da.map_blocks function or something similar to silence this warning. Your code may stop working in a future release.
  warnings.warn(
0.1000409420566798
/home/jcristharif/miniconda3/envs/dask/lib/python3.9/site-packages/dask-2021.9.1-py3.9.egg/dask/array/core.py:1503: FutureWarning: The `numpy.quantile` function is not implemented by Dask array. You may want to use the da.map_blocks function or something similar to silence this warning. Your code may stop working in a future release.
  warnings.warn(
0.1003397688066362
```

If you want to open an issue about those warnings instead that would be welcome, but I think the original issue here has already been resolved. Closing.

**Closed by jcrist** 2021-09-27 19:38 UTC
