### ISSUE TITLE
Dask bag read_sequence(...).map(...).compute() returning ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by TipsForGIS** [dask/dask#7962] opened 2021-07-30 02:52 UTC
Hello everyone,
I would appreciate it if you can help me of what is wrong in my code. I have a list of objects, specifically ArcGIS items. Let's say the list of objects is called `itms`, my code is basically:

```
import dask.bag as db

def get_attribute(i):
    return i.title

bag = db.from_sequence(itms)
result = db.map(lambda x: get_attribute(x) , bag).compute()
```

Then I am getting this error:

ValueError: too many values to unpack (expected 2)

**I thought maybe dask bag does not work with sequences of objects. It might be only for sequences of literal values. But I tried the same code with objects based on a simple class called Point:**

```
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def get_x(self):
        return self.x
    
    def get_y(self):
        return self.y
######################
######################
def get_x(p):
    return p.get_x()
    
p1 = Point(1,2)
p2 = Point(-3,-1)
p3 = Point(0,0)

pnts = [p1,p2,p3]

bag = db.from_sequence(pnts)
result = db.map(lambda x: get_x(x) , bag).compute()
```

**And it is working fine!!**

So please let me know what I'am doing wrong.

Thank you so much.

**Comment by douglasdavis** [comment] 2021-07-30 18:02
I tried to reproduce the `ValueError` you're seeing but I wasn't able to. Perhaps a specific example of what `itms` is might be helpful?

**Comment by TipsForGIS** [comment] 2021-07-30 19:57
Thank you Doug for your response. The objects I am using are referred to as [ArcGIS Python items](https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#item). This type of object has attributes like title and id, and it has methods such as [usage](https://developers.arcgis.com/python/api-reference/arcgis.gis.toc.html#arcgis.gis.Item.usage). I am trying to access the attributes and invoke the usage method in the user defined function inside the bag's map method.


```
import dask.bag as dbag
from arcgis.gis import GIS, Group
from datetime import datetime

# user defined function
# basically it returns a dictionary of usage metrics for each item object passed
def get_usage_dct(itm):
    today = datetime.now().strftime('%Y-%m-%d')
    i = mapit.ContentManager.get(itm)
    i_usage_df_1y = i.usage(date_range='1Y', as_df=True)
    i_usage_df_1y = i_usage_df_1y[i_usage_df_1y['Date'] < today]
    i_usage_df_6m = i.usage(date_range='6M', as_df=True)
    i_usage_df_6m = i_usage_df_6m[i_usage_df_6m['Date'] < today]
    i_usage_df_2m = i.usage(date_range='60D', as_df=True)
    i_usage_df_2m = i_usage_df_2m[i_usage_df_2m['Date'] < today]
    return {'item_name':i.title,'usage_count_1Y':i_usage_df_1y['Usage'].sum(),'usage_count_6m':i_usage_df_6m['Usage'].sum(),'usage_count_2m':i_usage_df_2m['Usage'].sum()}

# define the GIS object
# the gis object is used to acccess items in a specific account
# since I am running the code from Jupyter notebook inside the system, I don't have to pass credentials
mapit = GIS("home")

# getting items of a specific group
# a group is nothing but a logical grouping of items
g = Group(mapit,'xxxxxxxxx')
itms = g.content()

# create items bag from the itms list
itms_bag = dbag.from_sequence(itms, npartitions = 9)

# this line is causing the error
final_bag = dbag.map(lambda x: get_usage_dct(x), itms_bag).compute()
```

# This is the error:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-96bf44a8f85c> in <module>
     32 
     33 #final_bag = itms_bag.map(lambda x: get_usage_dct(x)).compute()
---> 34 final_bag = dbag.map(lambda x: get_usage_dct(x), itms_bag).compute()
     35 

/opt/conda/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    165         dask.base.compute
    166         """
--> 167         (result,) = compute(self, traverse=False, **kwargs)
    168         return result
    169 

/opt/conda/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    450         postcomputes.append(x.__dask_postcompute__())
    451 
--> 452     results = schedule(dsk, keys, **kwargs)
    453     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    454 

/opt/conda/lib/python3.7/site-packages/dask/multiprocessing.py in get(dsk, keys, num_workers, func_loads, func_dumps, optimize_graph, pool, **kwargs)
    216             pack_exception=pack_exception,
    217             raise_exception=reraise,
--> 218             **kwargs
    219         )
    220     finally:

/opt/conda/lib/python3.7/site-packages/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    469             # Seed initial tasks into the thread pool
    470             while state["ready"] and len(state["running"]) < num_workers:
--> 471                 fire_task()
    472 
    473             # Main loop, wait on tasks to finish, insert new ones

/opt/conda/lib/python3.7/site-packages/dask/local.py in fire_task()
    458                     args=(
    459                         key,
--> 460                         dumps((dsk[key], data)),
    461                         dumps,
    462                         loads,

/opt/conda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py in dumps(obj, protocol)
    100         with io.BytesIO() as file:
    101             cp = CloudPickler(file, protocol=protocol)
--> 102             cp.dump(obj)
    103             return file.getvalue()
    104 

/opt/conda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py in dump(self, obj)
    561     def dump(self, obj):
    562         try:
--> 563             return Pickler.dump(self, obj)
    564         except RuntimeError as e:
    565             if "recursion" in e.args[0]:

/opt/conda/lib/python3.7/pickle.py in dump(self, obj)
    435         if self.proto >= 4:
    436             self.framer.start_framing()
--> 437         self.save(obj)
    438         self.write(STOP)
    439         self.framer.end_framing()

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/pickle.py in save_tuple(self, obj)
    772         if n <= 3 and self.proto >= 2:
    773             for element in obj:
--> 774                 save(element)
    775             # Subtle.  Same as in the big comment below.
    776             if id(obj) in memo:

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/pickle.py in save_tuple(self, obj)
    772         if n <= 3 and self.proto >= 2:
    773             for element in obj:
--> 774                 save(element)
    775             # Subtle.  Same as in the big comment below.
    776             if id(obj) in memo:

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/pickle.py in save_tuple(self, obj)
    787         write(MARK)
    788         for element in obj:
--> 789             save(element)
    790 
    791         if id(obj) in memo:

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py in save_function(self, obj, name)
    743             else:
    744                 return self._save_reduce_pickle5(
--> 745                     *self._dynamic_function_reduce(obj), obj=obj
    746                 )
    747 

/opt/conda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py in _save_reduce_pickle5(self, func, args, state, listitems, dictitems, state_setter, obj)
    685             save(state_setter)
    686             save(obj)  # simple BINGET opcode as obj is already memoized.
--> 687             save(state)
    688             write(pickle.TUPLE2)
    689             # Trigger a state_setter(obj, state) function call.

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/pickle.py in save_tuple(self, obj)
    772         if n <= 3 and self.proto >= 2:
    773             for element in obj:
--> 774                 save(element)
    775             # Subtle.  Same as in the big comment below.
    776             if id(obj) in memo:

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/pickle.py in save_dict(self, obj)
    857 
    858         self.memoize(obj)
--> 859         self._batch_setitems(obj.items())
    860 
    861     dispatch[dict] = save_dict

/opt/conda/lib/python3.7/pickle.py in _batch_setitems(self, items)
    883                 for k, v in tmp:
    884                     save(k)
--> 885                     save(v)
    886                 write(SETITEMS)
    887             elif n:

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/pickle.py in save_dict(self, obj)
    857 
    858         self.memoize(obj)
--> 859         self._batch_setitems(obj.items())
    860 
    861     dispatch[dict] = save_dict

/opt/conda/lib/python3.7/pickle.py in _batch_setitems(self, items)
    888                 k, v = tmp[0]
    889                 save(k)
--> 890                 save(v)
    891                 write(SETITEM)
    892             # else tmp is empty, and we're done

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py in save_function(self, obj, name)
    743             else:
    744                 return self._save_reduce_pickle5(
--> 745                     *self._dynamic_function_reduce(obj), obj=obj
    746                 )
    747 

/opt/conda/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py in _save_reduce_pickle5(self, func, args, state, listitems, dictitems, state_setter, obj)
    685             save(state_setter)
    686             save(obj)  # simple BINGET opcode as obj is already memoized.
--> 687             save(state)
    688             write(pickle.TUPLE2)
    689             # Trigger a state_setter(obj, state) function call.

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/pickle.py in save_tuple(self, obj)
    772         if n <= 3 and self.proto >= 2:
    773             for element in obj:
--> 774                 save(element)
    775             # Subtle.  Same as in the big comment below.
    776             if id(obj) in memo:

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/pickle.py in save_dict(self, obj)
    857 
    858         self.memoize(obj)
--> 859         self._batch_setitems(obj.items())
    860 
    861     dispatch[dict] = save_dict

/opt/conda/lib/python3.7/pickle.py in _batch_setitems(self, items)
    883                 for k, v in tmp:
    884                     save(k)
--> 885                     save(v)
    886                 write(SETITEMS)
    887             elif n:

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/pickle.py in save_dict(self, obj)
    857 
    858         self.memoize(obj)
--> 859         self._batch_setitems(obj.items())
    860 
    861     dispatch[dict] = save_dict

/opt/conda/lib/python3.7/pickle.py in _batch_setitems(self, items)
    883                 for k, v in tmp:
    884                     save(k)
--> 885                     save(v)
    886                 write(SETITEMS)
    887             elif n:

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    547 
    548         # Save the reduce() output and finally memoize the object
--> 549         self.save_reduce(obj=obj, *rv)
    550 
    551     def persistent_id(self, obj):

/opt/conda/lib/python3.7/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    660 
    661         if state is not None:
--> 662             save(state)
    663             write(BUILD)
    664 

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/pickle.py in save_dict(self, obj)
    857 
    858         self.memoize(obj)
--> 859         self._batch_setitems(obj.items())
    860 
    861     dispatch[dict] = save_dict

/opt/conda/lib/python3.7/pickle.py in _batch_setitems(self, items)
    883                 for k, v in tmp:
    884                     save(k)
--> 885                     save(v)
    886                 write(SETITEMS)
    887             elif n:

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    547 
    548         # Save the reduce() output and finally memoize the object
--> 549         self.save_reduce(obj=obj, *rv)
    550 
    551     def persistent_id(self, obj):

/opt/conda/lib/python3.7/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    660 
    661         if state is not None:
--> 662             save(state)
    663             write(BUILD)
    664 

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    502         f = self.dispatch.get(t)
    503         if f is not None:
--> 504             f(self, obj) # Call unbound method with explicit self
    505             return
    506 

/opt/conda/lib/python3.7/pickle.py in save_dict(self, obj)
    857 
    858         self.memoize(obj)
--> 859         self._batch_setitems(obj.items())
    860 
    861     dispatch[dict] = save_dict

/opt/conda/lib/python3.7/pickle.py in _batch_setitems(self, items)
    883                 for k, v in tmp:
    884                     save(k)
--> 885                     save(v)
    886                 write(SETITEMS)
    887             elif n:

/opt/conda/lib/python3.7/pickle.py in save(self, obj, save_persistent_id)
    547 
    548         # Save the reduce() output and finally memoize the object
--> 549         self.save_reduce(obj=obj, *rv)
    550 
    551     def persistent_id(self, obj):

/opt/conda/lib/python3.7/pickle.py in save_reduce(self, func, args, state, listitems, dictitems, obj)
    657 
    658         if dictitems is not None:
--> 659             self._batch_setitems(dictitems)
    660 
    661         if state is not None:

/opt/conda/lib/python3.7/pickle.py in _batch_setitems(self, items)
    881             if n > 1:
    882                 write(MARK)
--> 883                 for k, v in tmp:
    884                     save(k)
    885                     save(v)

ValueError: too many values to unpack (expected 2)
```

I hope this is clear 🙂

**Comment by jrbourbeau** [comment] 2021-07-30 20:24
@TipsForGIS it looks like this is a serialization issue with some objects in your example. By default Dask Bags use the multiprocessing scheduler (https://docs.dask.org/en/latest/bag.html#default-scheduler) which requires objects to be able to be pickled and sent between processes. Can you try using the multi-threaded scheduler to see if that avoids the serialization issue? This would mean using `compute(scheduler="threads")` instead of just `compute()`

**Comment by TipsForGIS** [comment] 2021-07-30 22:58
I tried compute(scheduler="threads"). It started working but then it got me this error

```
Exception: Too many requests. Please try again later.
(Error Code: 400)
```

Correct me if I am wrong, every `usage` method call is actually an API call. So maybe that is the problem.

**Comment by jrbourbeau** [comment] 2021-07-30 23:15
Nice! Thanks for following up @TipsForGIS

> Correct me if I am wrong, every usage method call is actually an API call. So maybe that is the problem.

I'm not familiar with arcgis, but "Too many requests" indeed seems like you're hitting some sort of API limit. At this point, it looks like Dask is able to run your code in parallel, though you're now hitting concurrency limits with arcgis

**Comment by TipsForGIS** [comment] 2021-07-30 23:16
Thank you James. I appreciate your feedback.

**Comment by jrbourbeau** [comment] 2021-07-30 23:18
No worries, happy to help. I'm going to close this issue as it seems like things are resolved on the Dask-side. Good luck @TipsForGIS

**Closed by jrbourbeau** 2021-07-30 23:18 UTC
Labels: bag
