### ISSUE TITLE
`dask.bag.random.sample` throws various errors

### ISSUE THREAD

**Issue by MaximLippeveld** [dask/dask#9249] opened 2022-07-07 09:39 UTC
**What happened**: I want to undersample items in a Bag using `dask.bag.random.sample`

**What you expected to happen**: Receive a Bag with specified amount of items.

**Minimal Complete Verifiable Example**:

```python
import dask.bag
from dask.bag import random


def main():

    bag = dask.bag.range(n=100, npartitions=10)
    bag2 = random.sample(bag, k=10)
    bag2.compute() # throws ValueError: too many values to unpack (expected 2)

    bag = dask.bag.range(n=10, npartitions=10)
    bag2 = random.sample(bag, k=3)
    bag2.compute() # throws ValueError: Sample larger than population or is negative

if __name__ == "__main__":
    main()
```

**Anything else we need to know?**: 

**Environment**:

- Dask version: 2022.6.1
- Python version: 3.9.10
- Operating System: Fedora 34
- Install method (conda, pip, source): pip

**Comment by pavithraes** [comment] 2022-07-08 18:02
@mesejo I know you did some work on Bag Sampling recently, do you have thoughts on this?

I'm able to reproduce this even with dask=2022.02.1, which suggested this was happening even before your refactor. :/

**Comment by ian-r-rose** [comment] 2022-07-08 18:27
I think what's going on here is that the bag aggregation function for `sample()` returns something of a different shape of the inputs ( a `tuple[list, int]` vs just a `list`). As soon as the aggregation gets more than one level, the outputs of the agg function can no longer be fed into itself. `split_every` defaults to 8, so we start seeing the issue at 9 partitions.

This will require some changes to the reduction so that the outputs of the sampling aggregation function can be fed into itself (not sure what that looks like just yet).

**Comment by pavithraes** [comment] 2022-07-14 12:17
Ian and I looked at this yesterday, and we've created a fix of the first error (`too many values to unpack (expected 2)`
) which is related to `split_every` as Ian described above.

We're yet to figure out why the second error (`Sample larger than population or is negative`) is raised when `npartitions` is equal to bag size.

**Comment by jrbourbeau** [comment] 2022-08-02 16:58
@pavithraes should we re-open this issue or did https://github.com/dask/dask/pull/9272 fully close this? I see you said "Partially resolves" over in https://github.com/dask/dask/pull/9272

**Closed** 2022-08-09 13:59 UTC
Labels: bag, bug
