### ISSUE TITLE
Getting index of Groupby + sum with categoricals with different known values fails with 'Level values must be unique' / metadata inference failed

### ISSUE THREAD

**Issue by makmanalp** [dask/dask#4166] opened 2018-11-01 16:12 UTC
```python

import pandas as pd
import dask.dataframe as dd


df = pd.DataFrame({"a": [1,2,3,4,5], "b":[6,7,8,9,1], "c":[100,200,300,400,500], "d":[9, 99, 999, 9999, 99999]})
ddf = dd.from_pandas(df, npartitions=2) 

ddf.a = ddf.a.astype(pd.Categorical(range(1,10)))
ddf.b = ddf.b.astype(pd.Categorical(range(1,10)))
ddf.c = ddf.c.astype(pd.Categorical(range(100,1000)))

# All succeed as expected
ddf.groupby(["a", "b"]).d.sum()
ddf.groupby(["a", "b"]).d.sum().compute()
ddf.groupby(["a", "b"]).d.sum().index.compute()

# Here is where things get wonky
ddf.groupby(["a", "c"]).d.sum() # succeeds
ddf.groupby(["a", "c"]).d.sum().compute() # succeeds!
ddf.groupby(["a", "c"]).d.sum().index # fails

```

- Same wonkiness happens with `["b", "c"]` also.
- Order of columns specified doesn't seem to matter
- `.reset_index()` also fails the same way, which is how I came upon this bug - I need to reset the index after a groupby
- This happens with pandas `0.23.4` and dask `0.20.0`. If I roll back to pandas `0.22.0` it doesn't happen. Seems to break on `0.23.0` too so whatever change must have happened there.
- Is this a MultiIndex issue? In general, can we get a clear story with MultiIndexes? I've read that they're not supported, except it seems like if you do a groupby you do get a MultiIndex (you have to run `reset_index()` to get your columns back). So we get this situation where they're not supported, except when they are! This leads to a lot of confusion IMHO. I think not supporting them yet is totally understandable, but it would be wonderful to have a clear delineation of which things are expected to work vs not, either through documentation or checks and error messages, etc. x-ref #811 #1493

----

Full traceback:

```python
ValueError                                Traceback (most recent call last)
/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    136     try:
--> 137         yield
    138     except Exception as e:

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3596     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3597         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3598 

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py in _extract_meta(x, nonempty)
   3580     elif isinstance(x, tuple):
-> 3581         return tuple([_extract_meta(_x, nonempty) for _x in x])
   3582     elif isinstance(x, dict):

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py in <listcomp>(.0)
   3580     elif isinstance(x, tuple):
-> 3581         return tuple([_extract_meta(_x, nonempty) for _x in x])
   3582     elif isinstance(x, dict):

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py in _extract_meta(x, nonempty)
   3576     if isinstance(x, (Scalar, _Frame)):
-> 3577         return x._meta_nonempty if nonempty else x._meta
   3578     elif isinstance(x, list):

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py in _meta_nonempty(self)
    288         """ A non-empty version of `_meta` with fake data."""
--> 289         return meta_nonempty(self._meta)
    290 

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/utils.py in __call__(self, arg, *args, **kwargs)
    412         meth = self.dispatch(type(arg))
--> 413         return meth(arg, *args, **kwargs)
    414 

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/utils.py in _nonempty_series(s, idx)
    430     if idx is None:
--> 431         idx = _nonempty_index(s.index)
    432     dtype = s.dtype

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/utils.py in _nonempty_index(idx)
    387         labels = [[0, 0] for i in idx.levels]
--> 388         return pd.MultiIndex(levels=levels, labels=labels, names=idx.names)
    389     raise TypeError("Don't know how to handle index of "

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/pandas/core/indexes/multi.py in __new__(cls, levels, labels, sortorder, names, dtype, copy, name, verify_integrity, _set_identity)
    241         if verify_integrity:
--> 242             result._verify_integrity()
    243         if _set_identity:

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/pandas/core/indexes/multi.py in _verify_integrity(self, labels, levels)
    284                                      values=[value for value in level],
--> 285                                      level=i))
    286 

ValueError: Level values must be unique: [nan, nan] on level 0

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-54-9b08d20035f9> in <module>
----> 1 ddf.groupby(["c", "b"]).d.sum().index.compute()

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py in index(self)
    369     def index(self):
    370         """Return dask Index instance"""
--> 371         return self.map_partitions(getattr, 'index', token=self._name + '-index')
    372 
    373     def reset_index(self, drop=False):

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    541         >>> ddf.map_partitions(func).clear_divisions()  # doctest: +SKIP
    542         """
--> 543         return map_partitions(func, self, *args, **kwargs)
    544 
    545     @insert_meta_param_description(pad=12)

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py in map_partitions(func, *args, **kwargs)
   3634 
   3635     if meta is no_default:
-> 3636         meta = _emulate(func, *args, udf=True, **kwargs2)
   3637 
   3638     if all(isinstance(arg, Scalar) for arg in args):

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3595     """
   3596     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3597         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3598 
   3599 

/nfs/tools/lib/anaconda/3-5.0.1/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    152                 "{2}")
    153         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 154         raise ValueError(msg)
    155 
    156 

ValueError: Metadata inference failed in `getattr`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
ValueError('Level values must be unique: [nan, nan] on level 0',)

Traceback:
---------
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/utils.py", line 137, in raise_on_meta_error
    yield
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py", line 3597, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py", line 3581, in _extract_meta
    return tuple([_extract_meta(_x, nonempty) for _x in x])
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py", line 3581, in <listcomp>
    return tuple([_extract_meta(_x, nonempty) for _x in x])
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py", line 3577, in _extract_meta
    return x._meta_nonempty if nonempty else x._meta
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/core.py", line 289, in _meta_nonempty
    return meta_nonempty(self._meta)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/utils.py", line 413, in __call__
    return meth(arg, *args, **kwargs)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/utils.py", line 431, in _nonempty_series
    idx = _nonempty_index(s.index)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/dask/dataframe/utils.py", line 388, in _nonempty_index
    return pd.MultiIndex(levels=levels, labels=labels, names=idx.names)
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 242, in __new__
    result._verify_integrity()
  File "/nfs/projects_nobackup/c/cidgrowlab/Mali/intl-atlas-api/env2/lib/python3.6/site-packages/pandas/core/indexes/multi.py", line 285, in _verify_integrity
    level=i))
```

**Comment by makmanalp** [comment] 2018-11-01 16:29
Some stuff around what changed in 0.23 that might have triggered this:

- Excluding unobserved categories in groupby: https://pandas.pydata.org/pandas-docs/version/0.23.0/whatsnew.html#whatsnew-0230-enhancements-categorical-grouping but this is defaulted to being backwards compatible.
- https://pandas.pydata.org/pandas-docs/version/0.23.0/whatsnew.html#categorical some other new categorical stuff but nothing jumps out at me

**Comment by makmanalp** [comment] 2018-11-01 20:51
I wonder if this might not be somewhat related to #2510

**Comment by mrocklin** [comment] 2018-11-16 13:43
Interesting!  Thank you for submitting an excellent bug report @makmanalp ! (and my apologies that no one responded here).  I'm able to reproduce.  It looks like it's failing when trying to guess the metadata of the index object.

I think that the next step to debug this issue is to dive in with the Python debugger.  I would probably run the code snippet that you've provided in ipython, let it fail, and then use the `%debug` magic to investigate what's going on with `pdb`.  Just a suggestion though.

**Comment by Allardvm** [comment] 2019-02-18 14:04
Ran into a related issue today and have some input that might help resolve this.

For me, the issue occurred with `groupby(['index_col', 'col']).apply(f)` on a Dask DataFrame (with 'index_col' as index) using the distributed scheduler. This triggers a call to `map_partitions`, where a call is made to Panda's `groupby`. Since Pandas defaults to  `group_keys=True` in a groupby.apply, it adds the two grouped keys to the DataFrame's index as a MultiIndex(..., names=['index_col', 'col', 'index_col']) (notice the duplicate 'index_col'). The Dask DAG is fine with this (it assumes that the groupby didn't change the index), but calling `compute()` triggers:
```
distributed.protocol.core - CRITICAL - Failed to deserialize
...
ValueError: Level values must be unique: [...] on level 2
```

Just calling `groupby(['index_col', 'col'], group_keys=False)` in a `map_partitions` function fixes the issue, but this makes accessing the keys (somewhat) more difficult. An alternative would be to drop the extra index levels in `_groupby_slice_apply`.

**Comment by mrocklin** [comment] 2019-02-18 23:29
It looks like you've taken the extra step of diving into the code a bit @Allardvm :)

If you have any interest in contributing a patch here, that would be very welcome.  (no obligation though, of course)

**Comment by jakirkham** [comment] 2019-04-30 16:15
Any thoughts on this one, @TomAugspurger?

**Comment by TomAugspurger** [comment] 2019-04-30 18:55
With some light modifications from Pandas API changes, the original issue seems fixed on dask master.

```python
import pandas as pd
import dask.dataframe as dd


df = pd.DataFrame({"a": [1,2,3,4,5], "b":[6,7,8,9,1], "c":[100,200,300,400,500], "d":[9, 99, 999, 9999, 99999]})
ddf = dd.from_pandas(df, npartitions=2) 

ddf.a = ddf.a.astype(pd.CategoricalDtype(range(1,10)))
ddf.b = ddf.b.astype(pd.CategoricalDtype(range(1,10)))
ddf.c = ddf.c.astype(pd.CategoricalDtype(range(100,1000)))

ddf.groupby(["a", "c"]).d.sum().index.compute()
MultiIndex(levels=[[1, 2, 3, 4, 5], [100, 200, 300, 400, 500]],
           codes=[[0, 1, 2, 3, 4], [0, 1, 2, 3, 4]],
           names=['a', 'c'])
```

LMK if you're still seeing issues @makmanalp or @Allardvm

**Closed by TomAugspurger** 2019-04-30 18:55 UTC
Labels: dataframe, good second issue
