### ISSUE TITLE
embarrassingly parallel dask cannot handle large amount of task?

### ISSUE THREAD

**Issue by b-y-f** [dask/dask#9693] opened 2022-11-24 14:29 UTC
Another problem is I cannot process list > 1000. So I have to chunk down the size to 999, when the list size > 1000. there is no reaction in the dashboard.

```
all_meter_lst = load('all_meter_lst.pkl')
for cks in chunks(all_meter_lst, 999):
    lazy_results = []
    for meter_url in cks:
        lazy_result = dask.delayed(do_prediction)(meter_url)
        lazy_results.append(lazy_result)
    dask.compute(*lazy_results)
```

**Comment by rjzamora** [comment] 2022-11-29 19:46
Hi @b-y-f  - You may need to provide more information about your data and expected result. Also, can you explain what  kind of work `do_prediction` is doing here?

At first glance, it seems like you may want to avoid calling `dask.compute` in a for-loop like this:

```python
for cks in chunks(all_meter_lst, 999):
    ...
    dask.compute(*lazy_results)
```

Every time you call `dask.compute`, (1) you are constructing a task graph, (2) sending it to the scheduler, (3) executing the graph on workers, and (4) copying the result(s) back to the client. Therefore, you are **not** parallelizing over the 999  loops at all.  Is it possible to cumpute the entire graph at once?  For example:

```python
all_meter_lst = load('all_meter_lst.pkl')
lazy_results = []
for cks in chunks(all_meter_lst, 999):
    for meter_url in cks:
        lazy_result = dask.delayed(do_prediction)(meter_url)
        lazy_results.append(lazy_result)
dask.compute(*lazy_results)
```

If the problem is that you are not getting good parallelism over the elements of `cks`, we will probably need to know more about `do_prediction` and `meter_url` to advise further.

**Comment by phobson** [comment] 2022-11-29 20:12
xref: https://github.com/dask/dask/issues/9692#issuecomment-1331233183

**Comment by b-y-f** [comment] 2022-11-29 21:36
>  Also, can you explain what kind of work do_prediction is doing here?

Load data from s3 -> feature engineering -> input data to classification model -> append result to original data -> upload that new data to s3

**Comment by b-y-f** [comment] 2022-11-29 21:37
> xref: [#9692 (comment)](https://github.com/dask/dask/issues/9692#issuecomment-1331233183)

Thanks, will try it later!

**Comment by phobson** [comment] 2022-12-05 21:40
@b-y-f I'm going to close this for now. If you try out the advice from @rjzamora and you think you find a bug, please reopen the issue.

**Closed by phobson** 2022-12-05 21:40 UTC
Labels: needs info, delayed
