### ISSUE TITLE
8 million nodes in the dask dict

### ISSUE THREAD

**Issue by crusaderky** [dask/dask#1916] opened 2017-01-16 11:23 UTC
Hi,
I'm trying to implement a Monte Carlo simulation for a large financial company using xarray + dask on Python 3.5.
I need to model the value of about 9,000 assets under stress under 0.5 million scenarios. The project is still ongoing (I currently implemented only 6000 instruments) but my final dask dict is already 8 million keys large; 5.7 million after culling, inlining and fusing. In the medium term future, I expect it to grow by at least a factor of 10.
Note that I am writing this after a solid 3 months of optimization work - meaning that I already went through all the usual tuning best practices. The numpy chunks I'm working on are 50-100MB large each. Make them any larger, and I would severely lose on parallelism and run out of RAM.

The current problems I'm facing are two:
1.
Generating the final dask dict takes literal hours. To reduce that I've already implemented two workarounds, taking the definition time down to about 30 minutes:
a. After every intermediate dask array is generated, I empty its dask dict into a central repository. All subsequent operations that take that array in input will run dsk.update() on an empty dict. At the very last moment, after I get the final array, I swap its dask attribute with the centra dsk dict. The performance boost is humongous as previously the program was spending most of its time on dict.update().
b. I've implemented a fairly complicated system which basically parallelised the dask array generation over multiple processes (dask-within-dask, or daskception as I like to call it). This works but incurs in massive overheads caused by pickling/unpickling.

2.
The optimization of the final dask dict takes 3 to 5 minutes. Starting the compute() takes another 10 minutes (that is, the time before I start seeing any multi-threaded load). Before any task is actually executed, the Python interpreter takes about 15GB of RAM.

I have plenty of parallel processing power at my disposal to solve the problem - 250 hosts with 16 CPUs and 64GB each - but what is killing me is the pure Python work, which is so hard to parallelise.

The obvious workaround would be to break down the problem at application level and have separate Python processes evaluate it (possibly even with separate dask distributed schedulers and workers).
This however is not simple to do, given how the various parts of the problem interact with each other.

Does anybody else have experience with problems of this magnitude on dask? What is the best practice in these cases?

**Comment by mrocklin** [comment] 2017-01-16 14:52
Hi @crusaderky , thanks for the detailed writeup.  We've anticipated that these issues might arise during talks with the XArray community (cc @shoyer).  However you appear to be the lucky individual who has actually run into this scaling problem first :)  

Here are a few things we can do to improve this situation in the near future.  If you're interested in doing some work here we can probably do some of this fairly soon.

1.  Immediately you could turn off optimizations.  `compute(..., optimize_graph=False)` and see if this is useful at all
2.  If you provide a reproducible example that we can profile there are probably significant speedups still hanging around.  This won't be a 10x improvement but could easily result in 2x-3x
3.  One of the challenges that you ran into was that copying dictionaries and merging them on each dask.array operation, while safe, can quickly become a computational bottleneck.  We can work to resolve this in two ways:
    1.  We can create a MutableMapping that is just a list of dicts.  This would make the `update` operation trivial.  See https://github.com/dask/dask/issues/1763
    2.  We could use an optional persistent data structure with structural sharing (cc @kwmsmith, not sure if you're still interested in working on [ozymandias](https://github.com/kwmsmith/ozymandias), but this would be an application)
4.  Eventually even the original generation of the graph will become a bottleneck.  For this we might generate programmatic "dicts".  This is also mentioned in #1763 

For serialization costs I suspect/hope that this is due to dynamically generated functions in your graph, which are much more costly to serialize than statically imported functions.  If this is the case then profiling should pick it out and we can probably fix this quickly.  Here is an example showing a 10x reduction in cost when only serializing statically imported functions:

```python
In [4]: from distributed.protocol.pickle import dumps

In [5]: %time len(dumps(lambda x: x + 1))
CPU times: user 888 µs, sys: 0 ns, total: 888 µs
Wall time: 663 µs
Out[5]: 201

In [6]: from operator import add

In [7]: %time len(dumps(add))
CPU times: user 49 µs, sys: 4 µs, total: 53 µs
Wall time: 56.7 µs
Out[7]: 32
```

**Comment by vincentschut** [comment] 2017-01-16 15:04
FWIW, I ran into this earlier, though a little bit different. I did create a very large DAG based on da, which usually could have been much more sparse in the end as I usually only needed a small part of the DAG to actually compute at a time. I decided to do 2 things:
- leave DA, go with delayed instead (making it possible to create much smaller DAG's of only the parts I really needed to run)
- work in 'levels', and have each level create it's own subgraph in a task, and run that by 'creating tasks from tasks' with local_client blocks.
Might or might not suit you, just my 2c.

**Comment by crusaderky** [comment] 2017-01-16 15:35
Hi @mrocklin ,
thanks for the quick and detailed answer.

**Optimization**
Yes I'm already doing the optimization by hand and then I'm invoking compute(optimiza_grah=False). Optimization takes about 3-5 minutes. The 10 minutes wait before I see the program actually breaking into threads is already taking this into account.

**Reproducible example**
I can try working on that but it's not very straightforward. Is it OK to give you the actual final dask array in a pickle file (~200-500 MB), plus a stub of the custom functions are used within the graph so that you can actually open the pickle?

**Serialization of lambdas**
While I do have lambdas, I resolve them at xarray level. 
Say that for example a user gives me in input "node2 = max(0, node1 * 3)". 

I run

fn = sympy.lambdify("maximum(0, node1 * 3)", modules=xarray.ufuncs)
node2 = fn(node1)

where node1 is an xarray with dask backend. So in dask You will end up with a mul node and a xarray.ufuncs.maximum node. This is extremely expressive for me as I heavily rely on xarray's labelled broadcasting (e.g. multiply a <scenario, time> variable by a <time, rating, currency> one to get a <time, rating, currency, scenario> output).

Note that all broadcasting always happen on dask arrays. I never do broadcasting between dask and numpy as it would cause the pickle files to rocket to GBs in size because of https://github.com/pydata/xarray/issues/1058.

**delayed**
@vincentschut I don't think delayed will work for me because in my calculation I start from a handful of constants + a random variable, then I expand to intermediate curves with a size of about half terabyte EACH and then I aggregate until I reach a single vector of 500k points. So there's no way to keep a whole intermediate curve in memory at once within a delayed.

**work in levels**
@vincentschut Yes, I've been hurting my brain for a while with the idea of somehow breaking down the computation in sub-graphs. The hard part is to do it transparently and in a straightforward way, even if it's slightly suboptimal from a computational perspective.
Could you expand on it please?

**Comment by shoyer** [comment] 2017-01-17 02:10
This is indeed an issue that I have encountered before for large dask graphs. I think some sort of lazy dict and/or structural sharing is definitely a good place to start -- dask.array does a lot of defensive copying, which is very expensive with large graphs.

One suggestion going beyond what @mrocklin writes here (but that I know he is also very aware of) is to consider building another "lazy array" library that acts at a higher level than dask.array for optimization (not using chunks) but that can they compile down into dask array with optimal chunks for actual execution. In principle, this could enable optimal parallelism while also preserving fast graph construction. This is especially useful for interacting purposes, when it isn't obvious ahead of time what the optimal access pattern is (see https://github.com/dask/dask/pull/755 for related discussion).

Also note: this isn't @crusaderky's problem, but I noticed `dask.delayed` can introduce some significant overhead. Constructing dask graphs by hand can be much faster.

**Comment by mrocklin** [comment] 2017-01-17 03:47
No objection to lazy array library.  However I am personally unlikely to build such a thing.

**Comment by shoyer** [comment] 2017-01-17 04:03
Same for me (I don't have the burning need). But I do really like the idea
;).

**Comment by crusaderky** [comment] 2017-01-18 00:18
Good news - I think I pinpointed _one_ problem, and it's something highly localised and definitely fixable.

I'll go with a bit of narrative instead of jumping to the actual dask bug - this is in the hope that someone will find my troubleshooting approach useful to solve his own similar problems.
If you care only about the bug, scroll down to "the problem".

# Background
I need to explain how my data structure looks like at application level.
I have 3 levels:
- A few dozens *discount curves*, with dimensions (time=120, scenario=524288) and chunksize (time=50, scenario=65536)
- 4000 *instruments*, each being a function of 2 or 3 of the discount curves with output dimensions (scenario=524288) and chunksize (scenario=65536)
- 400 *portfolios*, each being a weighted sum of a large subset of the instruments
- The final output is the stack of the portfolios, so dimensions (portfolio_id=400, scenario=524288) and chunksize(portfolio_id=1, scenario=65536)

The whole problem is embarassingly parallel on the scenario axis, that is no interaction whatsoever between scenarios, whereas there is some degree of interaction between chunks on the time axis.

Each instrument needs to perform a linear interpolation (on discrete days) on the time axis of its own discount curves, to extract around 50 time points to discount its cashflow, a numpy-based constant with dims (time=50).
e.g. the time coord of the discount curves is [2015-12-31, 2016-12-31, 2017-12-31,...] while the time coord of the cashflow could be [2016-06-30, 2017-09-15, 2017-10-25].

Since there is a very high amount of repetition (lots of cashflows fall on the same dates), I engineered  the problem as follows:
1. extract all required timesteps from the time coord of the cashflow of every instrument, and then deduplicate the result, thus obtaining 9400 unique time points in total
2. perform linear interpolation ONCE and produce interpolated discount curves with dims (time=9400, scenario=524288) and chunksize (time=50, scenario=65536)
3. each instrument performs a simple sel() on the interpolated discount curve, obtaining a new xarray with dims (time=50, scenario=524288) and chunksize (time=1, scenario=65536). The chunksize=1 is not a hard rule, but statistically a single instrument will never benefit from more than 1 point per chunk of the humongous interpolated discount curve.

I calculate the dozen-or-so discount curves ONCE; then I move away their (very big) dask array to a central repository, and finally I reuse them as input of the 4000 instruments.

# Profiling
I ran the whole thing to generate the dask dict of the final portfolios stack - the famous 8 million keys dict, and recorded the whole thing through the profiler. It took 45 minutes (serially).

The results were enlightening:
```
     7102075688 function calls (7084309151 primitive calls) in 2831.939 seconds

   Ordered by: cumulative time
   List reduced from 1892 to 189 due to restriction <0.1>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.063    0.063 2832.316 2832.316 pyinstruments/simulator/session.py:322(build_cache)
7874/7704    0.053    0.000 1886.360    0.245 pyinstruments/simulator/simulatable.py:109(sel)
    12021    0.060    0.000 1880.319    0.156 xarray/core/dataarray.py:660(sel)
    12782    0.063    0.000 1873.923    0.147 xarray/core/dataarray.py:648(isel)
    12782    0.408    0.000 1873.127    0.147 xarray/core/dataset.py:1049(isel)
    64796    0.289    0.000 1872.099    0.029 xarray/core/variable.py:521(isel)
    50015    0.410    0.000 1870.732    0.037 xarray/core/variable.py:355(__getitem__)
     8315    0.298    0.000 1868.605    0.225 xarray/core/indexing.py:481(__getitem__)
    15410    0.223    0.000 1868.230    0.121 /dask/array/core.py:1175(__getitem__)
  905/716    0.011    0.000 1863.294    2.602 pyinstruments/simulator/alias.py:52(values)
     8376    1.030    0.000 1852.186    0.221 /dask/optimize.py:14(cull)
  1744640   12.582    0.000 1731.129    0.001 /dask/core.py:159(get_dependencies)
    16082    1.344    0.000 1729.273    0.108 /dask/optimize.py:45(<listcomp>)
5397979/5392287  427.862    0.000 1589.409    0.000 {built-in method builtins.any}
  2963884    3.508    0.000 1588.784    0.001 collections/__init__.py:889(__contains__)
6522984901 1159.123    0.000 1159.123    0.000 collections/__init__.py:890(<genexpr>)
427891/8850    1.473    0.000  978.362    0.111 pyinstruments/simulator/util.py:14(wrapper)
```
And ta-dah.
You can see 12021 xarray sel() calls, some of which are on numpy backend and some are on the dask backend.
To be more specific, about 8000 of them are exactly the sel() calls that every instrument does to extract the timepoints of its cashflow from the interpolated discount curves.
The vast majority of the time is wasted by **dask.optimizer.cull()**, which is invoked automatically every time by dask.array.DataArray.\_\_getitem\_\_.

Also, you see the 1000s of distance between the first and the second function cumtime? That's garbage collector time.

I need to emphasize how the dask dict of the interpolated discount curve is supposedly EMPTY when it arrives in input to the instruments, as it has been flushed out into the central repository.
So even if there's a useless cull() call, why is it taking this much time? it's running on an empty dict after all, it should be super fast.

So I tried disabling it:
```
from unittest.mock import patch

def cull_mock(dsk, keys):
    return dsk, None
a.data.dask = {}

with patch('dask.array.core.cull', cull_mock):
    x = interpolated_discount_curve.sel(time=cashflow_timesteps)
```
I rerun everything, expecting to see 1850s of runtime evaporate... 
...except that 2 hours and 16 GB of RAM later, it's not done yet. I kill the process only to find myself with **180 MILLION KEYS** in my central dask repository (which is now a collections.ChainMap); the garbage collector was cycling like a madman taking about **40 SECONDS** per run. 
Eeek.

# The problem
The fundamental underlying issue is that **dask.array.Array.\_\_getitem\_\_ writes back to the dask dict of its input**, whereas it's supposed to be a purely read-only operation. So the first sel() finds itself with an empty dask dict in input. The second one, however, finds garbage left by the previous invocation, copies it over into its output, and then spends a massive amount of time culling it away. The third sel() will have to clean up the garbage of the first and second sel(), and so on.
Disable the cull() and you get 180 million keys.

I now replaced al sel() calls to operate on a deep copy of the interpolated discount curve (remember, there's no dask dict in it, so it's actually a much faster operation than it sounds).

The new profile report:
```
       591332287 function calls (573466547 primitive calls) in 878.835 seconds

   Ordered by: cumulative time
   List reduced from 1473 to 147 due to restriction <0.1>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.032    0.032  879.213  879.213 pyinstruments/simulator/session.py:329(build_cache)
427891/8850    1.851    0.000  877.578    0.099 pyinstruments/simulator/util.py:38(wrapper)
19100/704    0.115    0.000  535.371    0.760 pyinstruments/simulator/util.py:118(wrapper)
19055/704    0.539    0.000  535.362    0.760 pyinstruments/simulator/util.py:90(wrapper)
      543    1.309    0.002  474.460    0.874 pyinstruments/simulator/portfolio.py:56(values)
     13/5    0.000    0.000  395.160   79.032 pyinstruments/simulator/stack.py:15(values)
     22/5    0.003    0.000  395.157   79.031 pyinstruments/simulator/stack.py:45(_recursive_concat)
     18/5    0.002    0.000  392.535   78.507 pyinstruments/simulator/stack.py:47(<listcomp>)
   303093    1.938    0.000  391.373    0.001 xarray/core/dataarray.py:1477(func)
```
<img src="http://i1.kym-cdn.com/entries/icons/facebook/000/009/255/1328554698663.jpg">

Now, 15 minutes is still a lot, and the final dask dict is still **6 million keys** now - but that's something I'll look at tomorrow.
Also tomorrow, I'll dig into the actual dask code to find a way to prevent \_\_getitem\_\_ from writing back to its input.
Sleep time now. :)

**Comment by mrocklin** [comment] 2017-01-18 13:49
I really enjoyed hearing about your problem.  This is probably against your incentives, but I'd love to see more people publish blogposts about how they use Dask/XArray for other applications.

> The fundamental underlying issue is that `dask.array.Array.__getitem__` writes back to the dask dict of its input, whereas it's supposed to be a purely read-only operation

This surprises me.  Looking briefly at `__getitem__` nothing jumps out at me as mutating the underlying graph.  It could be that this is deep within the slicing code?  Still, surprising.

**Comment by jcrist** [comment] 2017-01-18 17:00
> This surprises me. Looking briefly at __getitem__ nothing jumps out at me as mutating the underlying graph. It could be that this is deep within the slicing code? Still, surprising.

If I understand the original comment, it was caused by making `cull` the identity. If it's the identity, these lines will update the graph on each call to `__getitem__`: https://github.com/dask/dask/blob/master/dask/array/core.py#L1212-L1213. If that's indeed what the problem described here, then I don't see this as a bug in dask, as we don't really support patching of the dask internals :).

**Comment by vincentschut** [comment] 2017-01-19 14:10
@crusaderky here's my try to explain how we work with sub-graphs. jThough our situation is probably not comparable with yours.

First a general overview: what we do is automate the processing of satellite data. That means we usually start with downloading the relevant data, which has usuallly a [dates, bands, y, x] structure. Then there are some processing steps, with in de end of the chain some reduction steps along the dates dimension. In real it's more complex with additional dependent auxiliary datasets etc., but this is the gist of it.

What I started with was the somewhat naive approach of creating a grande lazy dask.array based graph of the entire set of operations over all dates, bands, y, and x. Worldwide. For all available dates. That means that I got a da of dimensions in the [10000's, 10's, 100000's, 100000's] (with even much larger ones planned) with chunks of [1, 10's, 1000's, 1000's]. I soon found out that building that graph took too much time, even if yours are probably even worse. But in my case, large part of that graph would actually be unnecessary because we never need to process all of that. It was just convenience. So then I decided to go with delayed instead of da, and build only that part of the graph which I need for a certain area of interest and span in time.

It was the fact that we sometimes have to make decisions half-way of the processing about how to get the necessary inputs, which made me go with sub-graphs. For example, at some places in the processing chain we do save those intermediate results in a cache (on S3), enabling us to start a different processing based on the same half-way result later without the need to do all that costly reprocessing. So there that 'node' has to choose between getting its data from cache (if available), or otherwise continue to traverse the graph of delayeds and have it calculated. There's where I create and spawn subtasks: if in cache, to get the data from the cache, otherwise, to calculate (and put in the cache for the next time). Because this cache is worker-independent (and agnostic), it is different from what dask/distributed calls 'caching'.

Hope this makes it a bit more clear. (I find it hard to explain, so don't worry if something is not clear and please just ask further.)

**Comment by crusaderky** [comment] 2017-01-21 19:19
# subgraphs
@vincentschut thanks for the explanation. Indeed I'll probably end up with something similar - however it's not easy in my case because my dependencies are diamond-shaped. e.g. I can't just write a recursive algorithm that, once it reaches an instrument, calculates its numpy value and stores it to disk, because 1000s of instruments rely on the same dozen of underlying curves, which in turn are very expensive to calculate and at the same time I cannot precalculate the curves and store an intermediate result to disk because their size is in the terabytes.

# auto-cull and keys leaking to the input
@jcrist ah you're right. I changed my code to
```
from unittest.mock import patch

def cull_mock(dsk, keys):
    return dsk.copy(), None
a.data.dask = {}

with patch('dask.array.core.cull', cull_mock):
    x = interpolated_discount_curve.sel(time=cashflow_timesteps)
```
and the leak into the input dask dict disappeared.

Still, the fundamental problem remains that that automated cull() cripples my perfomance. How can we solve it? Ideas I'm coming with:
1. just remove it entirely, for everybody. This would make a lot of sense if the whole dask package migrated to a ChainMap (#1763)
2. leave it on by default and write a context manager to disable it for the people like me that manipulate large dask dicts, e.g.
```
with dask.optimizer.disable_auto_cull():
    out = in[some slice]
```
3. implement a package-wide config setting, e.g.
```
dask.settings.auto_cull = False
```
4. remain with my monkey-patch forever and check it still works at every dask release?

# ChainMap
I now switched to a collections.ChainMap as the central repository of my dask data, with much satisfaction. Basically before I had
```
central_repo = {}
res = [... a few dozens of array manipulations...]
central_repo.update(res.dask)
res.dask = {}
res = more_manipulations(res)
central_repo.update(res.dask)
res.dask = {}
[etc.]
```
Now I changed it to
```
central_repo = ChainMap()
blame = {}

res = [... a few dozens of array manipulations...]
central_repo.maps.append(res.dask)
blame[res.name] = res.dask
res.dask = {}
res = more_manipulations(res)
central_repo.maps.append(res.dask)
blame[res.name] = res.dask
res.dask = {}
[etc.]
```
This has no material performance boost over just updating the dict (I still need to merge the whole thing before optimization), but gives me two huge benefits:
1. I can analyse and plot the sub-graph of every application-level chunk of code independently thanks to my new "blame" dict above, which is something that was extremely hard before. Did you ever try running plot_graph() on 6 million keys? Don't ;)
2. I can start thinking about optimizing in parallel the sub-graph.

# Parallel optimization
Instead of calling cull(), inline(), and fuse() on a single 6-million keys dict, which can take minutes if not tens of minutes, I can spawn subprocesses that do the same on dicts that are 10,000 keys each at most - basically for every intermediate ChainMap.maps element.

Little problem: all of those optimizer functions crash with KeyError when you try feeding a partial dask graph.
Possible solutions:
1. change the dask code to silently ignore KeyErrors
2. add stub constants at the bottom of the graphs, optimize, and then remove the stubs

# Insulating an embarassingly parallel algorithm
My algorithm performs A LOT of broadcasting, e.g.

output = a * b
where a is a numpy-based xarray variable e.g. (<time: 100>) and b is a huge dask-based variable e.g. <scenario: 500k, rating: 10>.

The above kind of expression happens in a few hundreds of consequent steps.

This causes a big problem, as on paper the algorithm is embarassingly parallel on the scenario axis. In other words, you can start with the first scenario chunk, go up to the top to the final result, discard everything in the middle, and then start again with the second scenario chunk.
In practice, what I'm seeing is that, because of the kind of broadcasting above, dask is keeping in memory all scenario chunks for all steps - effectively increasing the RAM requirements to resolve the problem by a factor of 10.

To explain visually: if you run plot_graph() you'd want to see independent columns, where each column is a scenario chunk
```
# # #
# # #
# # #
# # #
# # #
```
whereas instead you'll see something that looks like a ladder:
```
# # #
#####
# # #
#####
# # #
```
where each "step" of the ladder is actually a constant that is being added/multiplied to the dask partial result.

I found a way to fix it through manual optimization, where I basically inform dask that it's OK to duplicate all work related to generating the "a" variable (if any) so that the first and second chunk of "output" do not have any key in common:
```
scendim_i = output.dims.index('scenario')
chunk0 = output.chunks[scendim_i][0]
chunk1 = output.chunks[scendim_i][1] + chunk0
slice0 = output.isel(scenario=slice(chunk0))
slice1 = output.isel(scenario=slice(chunk0, chunk1))
shared_keys = slice0.data.dask.keys() & slice1.data.dask.keys() # Python 3 only
output.data.dask = inline(output.data.dask, keys=shared_keys)
```
The above drastically deflates the RAM usage when resolving the problem.
I think it should be useful to implement something like it in the main dask.optimizer module?

e.g. ```def insulate(array, axis)``` where axis is either a single positional axis or a list of axis, on whose chunks you want no cross-talk whatsoever.
This would be the only optimizer function that works on arrays though - I cannot see a simple way to offer a simple generic interface on dsk dicts directly.

**Comment by mrocklin** [comment] 2017-02-17 15:28
This may be resolved by https://github.com/dask/dask/pull/1985

**Comment by jnmclarty** [comment] 2017-02-24 18:32
@crusaderky Thanks for sharing.

**Comment by mrocklin** [comment] 2017-03-14 18:14
I'm going to go ahead and close this.  I *think* that array graph performance is now vastly improved.

**Closed by mrocklin** 2017-03-14 18:14 UTC

**Comment by crusaderky** [comment] 2017-08-28 19:17
@mrocklin SharedDict made wonders in terms of time needed to build the dask graph, however when I hit compute() my 32GB computer was quickly running out of RAM.

I solved the problem as follows:
1. I found all points of the algorithm that produced an Array that was then used by 2+ other functions; in other words all point of the graph immediately before a fork upwards (2+ nodes depend on the output of 1 node). In my case this was an easy job.
2. To each of the above nodes I applied my custom hyper-aggressive optimisation function:
```

def dask_keys(array):
    """Return flat set of top-level dask keys.

    :param array: a :class:`dask.array.Array` object
    """
    def traverse(keys):
        for k in keys:
            if type(k) is list:
                yield from traverse(k)
            else:
                yield k

    return {*traverse(array._keys())}

def optimize(array, inline_all=True):
    """Optimize dask dict. If underneath the target array
    there are other arrays that were previously passed
    through :func:`optimize`, they won't be touched.

    :param array:
        a :class:`dask.array.Array` object
    :param bool inline_all:
        if True, perform an extreme compression of the graph where the output
        graph will contain exclusively the final keys of the target array, plus
        the keys of any underlying array that was previously passed through
        :func:`optimize`. This drastically reduces the size of the graph, but
        it can be very expensive to define and can lead to expensive
        recalculations of the inlined nodes.

        If the calculation is embarassingly parallel on one or more axes, setting
        this flag to True will drastically reduce RAM usage.
    :returns:
        A shallow copy of array, with an optimized dask ShareDict.
    """
    preserve_keys = dask_keys(array)
    dsk = {}
    for d in array.dask.dicts.values():
        dsk.update(d)
        if 'preserve_keys' in d:
            preserve_keys.update(d.keys())
    preserve_keys.discard('preserve_keys')
    logging.debug("Preserve %d keys", len(preserve_keys))
    logging.debug("dsk size before optimization: %d", len(dsk))

    dsk, deps = cull(dsk, keys=array._keys())
    logging.debug("dsk size after cull: %d", len(dsk))

    dsk, deps = fuse(dsk, dependencies=deps, keys=preserve_keys,
                     rename_keys=False, ave_width=9999)
    logging.debug("dsk size after fuse: %d", len(dsk))

    if inline_all:
        inline_keys = dsk.keys() - preserve_keys
        logging.debug("Inlining %d keys", len(inline_keys))
    else:
        inline_keys = None
    dsk = inline(dsk, dependencies=deps, keys=inline_keys)
    dsk, _ = cull(dsk, keys=array._keys())
    logging.debug("dsk size after inline: %d", len(dsk))

    dsk['preserve_keys'] = True
    array = array.copy()
    array.dask.dicts = {array.name: dsk}
    return array
```
Silly example:
```
a = dask.ones((10, 10), chunks=5)
b = a * 3
c = b + 2
d = optimize(c, inline_all=True)
# Diamond dependency graph
e = (d + 1).sum(axis=0)
f = (d + 2).sum(axis=0)
g = e * f
h = optimize(g, inline_all=True)
```
The dask dict of h will have _exclusively_ these keys, no matter how complex and long the intermediate passages are:
```
d.name, 0, 0
d.name, 0, 1
d.name, 1, 0
d.name, 1, 1
h.name, 0
h.name, 1
```
With this I squashed the graph from ~8 million nodes to a much, MUCH more manageable ~25,000. What's even more important, this optimization forces everything that is not an explicit optimization point into a silo, making it embarassingly parallel. Much of my RAM consumption was caused by tiny xarray constants, e.g. dims={time: 150, rating: 7} being added or multiplied to big dask variables e.g. dims={scenario: 500000}, chunks={scenario: 25000}. In the graph, the same constant was attached to each of the 20 chunks of the dask array and the scheduler was keeping everything in RAM because of it.
