### ISSUE TITLE
Dask cluster hangs while processing file using s3fs

### ISSUE THREAD

**Issue by shalin07** [dask/dask#7547] opened 2021-04-12 04:12 UTC
So I have a function which loads nc files from S3 using s3fs and then select some specific region from files and then push back to different S3 bucket. Here's my function. I'm doing every thing in JupyterLab

```
def get_records(rec):
    
    d=[rec[-1][0:4], rec[-1][4:6], rec[-1][6:8], rec[-1][9:11], rec[-1][11:13]] 
    
    yr=d[0]
    mo=d[1]
    da=d[2]
    hr=d[3]
    mn=d[4]
    
    ps = s3fs.S3FileSystem(anon=True)

    period = pd.Period(str(yr)+str('-')+str(mo)+str('-')+str(da), freq='D')
    dy=period.dayofyear
    print(dy)

    cc=[7,8,9,10,11,12,13,14,15,16]  #look at the IR channels only for now
    dy="{0:0=3d}".format(dy)

    # this loop is for 10 different channels
    for c in range(10):
        ch="{0:0=2d}".format(cc[c])

    # opening 2 different time slices of given particular record
        F1=xr.open_dataset(ps.open(ps.glob('s3://noaa-goes16/ABI-L1b-RadF/'+str(yr)+'/'+str(dy)+'/'+str("{0:0=2d}".format(hr))+'/'+'OR_ABI-L1b-RadF-M3C'+ch+'*')[-2]))[['Rad']]

        F2=xr.open_dataset(ps.open(ps.glob('s3://noaa-goes16/ABI-L1b-RadF/'+str(yr)+'/'+str(dy)+'/'+str("{0:0=2d}".format(hr))+'/'+'OR_ABI-L1b-RadF-M3C'+ch+'*')[-1]))[['Rad']]
      
    # Selecting data as per given record radiance
        G1 = F1.where((F1.x >= (rec[0]-0.005)) & (F1.x <= (rec[0]+0.005)) & (F1.y >= (rec[1]-0.005)) & (F1.y <= (rec[1]+0.005)), drop=True)
        G2 = F2.where((F2.x >= (rec[0]-0.005)) & (F2.x <= (rec[0]+0.005)) & (F2.y >= (rec[1]-0.005)) & (F2.y <= (rec[1]+0.005)), drop=True)
       
    # Concating 2 time slices togethere
        G = xr.concat([G1, G2], dim  = 'time')

    # Concatiating different channels
        if c == 0:
            T = G    
        else:
            T = xr.concat([T, G], dim = 'channel')

    # Saving into nc file and storing them to S3
    path = rec[-1]+'.nc'
    T.to_netcdf(path)
    fs.put(path, bucket+path)
```
Now I want to use dask cluster to run this function parallelly like this this:

```
files = [ ]
for i in range(0, 100):
        s3_ds = dask.delayed(get_records)(records[i])
        files.append(s3_ds)

    files = dask.compute(*files)
``` 
So this thing was running perfectly fine last month but now when I try to do it again my clusters are not processing any files after a while. For example if I give 100 files to 10 cluster they won't process any files after 60-70 even though they have memory left and will just sit idle and do nothing. So next time I tried to give just 50 files, then they'll process around 30 files and then will sit idle. Even though they have memory left in them. I don't know what I'm doing wrong or is it some bug in library.  I upgraded all the library I was using, dask, s3fs and fssps. But still nothing is working. 

Main thing is all this was working perfectly fine few weeks back, but now the same code is not working anymore.

**Environment**:

- Dask version: 2021.2.0
- Python version: 3.8.8
- S3fs version: 0.6.0
- Fsspec: 0.9.0

**Comment by jsignell** [comment] 2021-04-19 16:36
Thanks for writing this up and sorry no one has gotten to it yet. Are there any errors showing up? Pinging @martindurant in case you have seen something like this before.

**Comment by martindurant** [comment] 2021-04-19 16:51
If you suspect that s3fs is causing this, then I would recommend turning on logging (e.g., environment S3FS_LOGGING_LEVEL=DEBUG). You can try with previous version of s3fs/fsspec to see if there is a difference. 
However, with so many libraries working together, there is a chance that this is due to a change in xarray or distributed. If you could isolate the problem to a particular change, that would be greatly helpful to us. The trouble is, intermittent problems don't always show up, and your workload is rather large. Any further information you can give us would be helpful.

**Comment by jrbourbeau** [comment] 2021-06-11 14:22
@shalin07 are you able to provide more details? Otherwise it may be difficult for others to help

**Comment by stevengillard** [comment] 2021-06-24 06:13
I'm seeing the same (or very similar) behaviour.  Everything works fine with s3fs 0.4.2 / fsspec 0.7.4 but if I upgrade both to more recent versions such as 2021.5.0 some of the dask workers will hang while reading data from S3.

Below is the call stack from the dashboard of one of the hung workers:
```
Key: ('open_dataset-concatenate-78485af84bf7c7cd890edd891a3cac82', 78, 3, 3)
File "/opt/conda/lib/python3.8/threading.py", line 890, in _bootstrap self._bootstrap_inner()
File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner self.run()
File "/opt/conda/lib/python3.8/threading.py", line 870, in run self._target(*self._args, **self._kwargs)
File "/opt/conda/lib/python3.8/site-packages/distributed/threadpoolexecutor.py", line 55, in _worker task.run()
File "/opt/conda/lib/python3.8/site-packages/distributed/_concurrent_futures_thread.py", line 66, in run result = self.fn(*self.args, **self.kwargs)
File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 3910, in apply_function result = function(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/dask/array/core.py", line 104, in getter c = np.asarray(c)
File "/opt/conda/lib/python3.8/site-packages/numpy/core/_asarray.py", line 102, in asarray return array(a, dtype, copy=False, order=order)
File "/opt/conda/lib/python3.8/site-packages/xarray/core/indexing.py", line 507, in __array__ return np.asarray(self.array, dtype=dtype)
File "/opt/conda/lib/python3.8/site-packages/numpy/core/_asarray.py", line 102, in asarray return array(a, dtype, copy=False, order=order)
File "/opt/conda/lib/python3.8/site-packages/xarray/core/indexing.py", line 671, in __array__ return np.asarray(self.array, dtype=dtype)
File "/opt/conda/lib/python3.8/site-packages/numpy/core/_asarray.py", line 102, in asarray return array(a, dtype, copy=False, order=order)
File "/opt/conda/lib/python3.8/site-packages/xarray/core/indexing.py", line 572, in __array__ return np.asarray(array[self.key], dtype=None)
File "/opt/conda/lib/python3.8/site-packages/numpy/core/_asarray.py", line 102, in asarray return array(a, dtype, copy=False, order=order)
File "/opt/conda/lib/python3.8/site-packages/xarray/coding/variables.py", line 70, in __array__ return self.func(self.array)
File "/opt/conda/lib/python3.8/site-packages/xarray/coding/variables.py", line 137, in _apply_mask data = np.asarray(data, dtype=dtype)
File "/opt/conda/lib/python3.8/site-packages/numpy/core/_asarray.py", line 102, in asarray return array(a, dtype, copy=False, order=order)
File "/opt/conda/lib/python3.8/site-packages/xarray/core/indexing.py", line 572, in __array__ return np.asarray(array[self.key], dtype=None)
File "/opt/conda/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 48, in __getitem__ return indexing.explicit_indexing_adapter(
File "/opt/conda/lib/python3.8/site-packages/xarray/core/indexing.py", line 863, in explicit_indexing_adapter result = raw_indexing_method(raw_key.tuple)
File "/opt/conda/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 58, in _getitem return array[key]
File "/opt/conda/lib/python3.8/site-packages/h5netcdf/core.py", line 159, in __getitem__ return self._h5ds[key]
File "/opt/conda/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 787, in __getitem__ self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
File "/opt/conda/lib/python3.8/site-packages/fsspec/spec.py", line 1459, in readinto data = self.read(out.nbytes)
File "/opt/conda/lib/python3.8/site-packages/fsspec/spec.py", line 1449, in read out = self.cache._fetch(self.loc, self.loc + length)
File "/opt/conda/lib/python3.8/site-packages/fsspec/caching.py", line 390, in _fetch self.cache = self.fetcher(start, bend)
File "/opt/conda/lib/python3.8/site-packages/s3fs/core.py", line 1827, in _fetch_range return _fetch_range(
File "/opt/conda/lib/python3.8/site-packages/s3fs/core.py", line 1977, in _fetch_range return sync(fs.loop, resp["Body"].read)
File "/opt/conda/lib/python3.8/site-packages/fsspec/asyn.py", line 51, in sync event.wait(timeout)
File "/opt/conda/lib/python3.8/threading.py", line 558, in wait signaled = self._cond.wait(timeout)
File "/opt/conda/lib/python3.8/threading.py", line 302, in wait waiter.acquire()
```

Here is a snippet of the code, it is reading in from a bunch of NetCDF files in S3:
```
start_year = 2015
end_year = 2020
years = list(np.arange(start_year, end_year+1, 1))
months = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
file_pattern = 's3://era5-pds/{year}/{month}/data/air_temperature_at_2_metres.nc'

@dask.delayed
def s3open(path):
    fs = s3fs.S3FileSystem(anon=True, default_fill_cache=False)
    return fs.open(path)

files_mapper = [s3open(file_pattern.format(year=year,month=month)) for year in years for month in months]
ds = xr.open_mfdataset(files_mapper, engine='h5netcdf', chunks={'lon':200,'lat':200,'time0':720}, concat_dim='time0', combine='nested', coords='minimal', compat='override', parallel=True)
ds = client.persist(ds)
```

s3fs debug logs:
```
2021-06-24 05:45:50,225 - s3fs - DEBUG - _fetch_range -- Fetch: era5-pds/2015/05/data/air_temperature_at_2_metres.nc, 11920-5256896
2021-06-24 05:45:50,226 - s3fs - DEBUG - _call_s3 -- CALL: get_object - () - {'Bucket': 'era5-pds', 'Key': '2015/05/data/air_temperature_at_2_metres.nc', 'Range': 'bytes=11920-5256895', 'IfMatch': '"2a22882f022cf776b58a66ea75c9d7b2-58"'}
2021-06-24 05:45:50,282 - s3fs - DEBUG - _fetch_range -- Fetch: era5-pds/2015/05/data/air_temperature_at_2_metres.nc, 458049056-463292744
2021-06-24 05:45:50,283 - s3fs - DEBUG - _call_s3 -- CALL: get_object - () - {'Bucket': 'era5-pds', 'Key': '2015/05/data/air_temperature_at_2_metres.nc', 'Range': 'bytes=458049056-463292743', 'IfMatch': '"2a22882f022cf776b58a66ea75c9d7b2-58"'}
2021-06-24 05:46:06,673 - s3fs - DEBUG - _fetch_range -- Fetch: era5-pds/2016/08/data/air_temperature_at_2_metres.nc, 0-5242888
2021-06-24 05:46:06,674 - s3fs - DEBUG - set_session -- Setting up s3fs instance
```

I'm no dask expert, but happy to do what I can to help track it down.  Let me know if there's anything else that would help.

**Comment by jsignell** [comment] 2021-06-24 13:41
There have been some recent improvements in these libraries, so if possible the first step in debugging would be to upgrade dask, xarray, fsspec, and s3fs and see if the issue still persist.

**Comment by shalin07** [comment] 2021-06-24 13:50
@jsignell I have tried upgrading everything but the problem still persists. And I tried to used my code without s3fs and instead I pulled up data from Google cloud. But still I was having the same problem. The only library I was using were xarray, gcsfs and dask but still the same problem.

**Comment by martindurant** [comment] 2021-06-24 14:06
> I upgrade both to more recent versions such as 2021.5.0 

We are now on 2021.6.1

**Comment by martindurant** [comment] 2021-06-24 14:46
I'm not sure what your delayed mapper is supposed to achieve, but the following works, if slowly. If your data conforms to expectations, same common coords and attributes in all files, you can use kwargs to minimise the open time:
```
{
        "data_vars": "minimal",
        "coords": "minimal",
        "compat": "override",
        "join": "override",
        "combine_attrs": "override",
}
```
Both your original code and this simplified version works for me:
```
start_year = 2015
end_year = 2020
years = list(np.arange(start_year, end_year+1, 1))
months = ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
file_pattern = 's3://era5-pds/{year}/{month}/data/air_temperature_at_2_metres.nc'

fs = s3fs.S3FileSystem(anon=True, default_fill_cache=False)
files_mapper = [fs.open(file_pattern.format(year=year,month=month)) for year in years for month in months]
ds = xr.open_mfdataset(files_mapper, engine='h5netcdf', chunks={'lon':200,'lat':200,'time0':720}, concat_dim='time0', combine='nested', coords='minimal', compat='override', parallel=True)
```

**Comment by stevengillard** [comment] 2021-06-25 03:13
I've updated everything to the latest including dask 2021.6.2 and s3fs 2021.6.1 but it's still hanging.  Here's a list of the packages and their versions from my Dockerfile:

```
 RUN conda install --yes \
    -c conda-forge \
    python==3.8.10 \
    python-blosc==1.10.2 \
    dask==2021.6.2 \
    distributed==2021.6.2 \
    lz4==3.1.3 \
    nomkl==1.0 \
    msgpack-python==1.0.2 \
    netcdf4==1.5.7 \
    numpy==1.21.0 \
    pandas==1.2.5 \
    xarray==0.18.2 \
    bokeh==2.3.2 \
    s3fs==2021.6.1 \
    fsspec==2021.6.1 \
    h5netcdf==0.11.0 \
    tornado==6.1 \ 
    cloudpickle==1.6.0 \
    h5py==3.3.0 \
    zarr==2.8.3 \
    rechunker==0.4.2 \
```

Call stack is similar:
```
File "/opt/conda/lib/python3.8/threading.py", line 890, in _bootstrap self._bootstrap_inner()
File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner self.run()
File "/opt/conda/lib/python3.8/threading.py", line 870, in run self._target(*self._args, **self._kwargs)
File "/opt/conda/lib/python3.8/site-packages/distributed/threadpoolexecutor.py", line 55, in _worker task.run()
File "/opt/conda/lib/python3.8/site-packages/distributed/_concurrent_futures_thread.py", line 66, in run result = self.fn(*self.args, **self.kwargs)
File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 3909, in apply_function result = function(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/dask/array/core.py", line 104, in getter c = np.asarray(c)
File "/opt/conda/lib/python3.8/site-packages/xarray/core/indexing.py", line 507, in __array__ return np.asarray(self.array, dtype=dtype)
File "/opt/conda/lib/python3.8/site-packages/xarray/core/indexing.py", line 671, in __array__ return np.asarray(self.array, dtype=dtype)
File "/opt/conda/lib/python3.8/site-packages/xarray/core/indexing.py", line 572, in __array__ return np.asarray(array[self.key], dtype=None)
File "/opt/conda/lib/python3.8/site-packages/xarray/coding/variables.py", line 70, in __array__ return self.func(self.array)
File "/opt/conda/lib/python3.8/site-packages/xarray/coding/variables.py", line 137, in _apply_mask data = np.asarray(data, dtype=dtype)
File "/opt/conda/lib/python3.8/site-packages/xarray/core/indexing.py", line 572, in __array__ return np.asarray(array[self.key], dtype=None)
File "/opt/conda/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 48, in __getitem__ return indexing.explicit_indexing_adapter(
File "/opt/conda/lib/python3.8/site-packages/xarray/core/indexing.py", line 863, in explicit_indexing_adapter result = raw_indexing_method(raw_key.tuple)
File "/opt/conda/lib/python3.8/site-packages/xarray/backends/h5netcdf_.py", line 58, in _getitem return array[key]
File "/opt/conda/lib/python3.8/site-packages/h5netcdf/core.py", line 159, in __getitem__ return self._h5ds[key]
File "/opt/conda/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 762, in __getitem__ self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
File "/opt/conda/lib/python3.8/site-packages/fsspec/spec.py", line 1479, in readinto data = self.read(out.nbytes)
File "/opt/conda/lib/python3.8/site-packages/fsspec/spec.py", line 1469, in read out = self.cache._fetch(self.loc, self.loc + length)
File "/opt/conda/lib/python3.8/site-packages/fsspec/caching.py", line 390, in _fetch self.cache = self.fetcher(start, bend)
File "/opt/conda/lib/python3.8/site-packages/s3fs/core.py", line 1897, in _fetch_range return _fetch_range(
File "/opt/conda/lib/python3.8/site-packages/s3fs/core.py", line 2047, in _fetch_range return sync(fs.loop, resp["Body"].read)
File "/opt/conda/lib/python3.8/site-packages/fsspec/asyn.py", line 58, in sync if event.wait(1):
File "/opt/conda/lib/python3.8/threading.py", line 558, in wait signaled = self._cond.wait(timeout)
File "/opt/conda/lib/python3.8/threading.py", line 306, in wait gotit = waiter.acquire(True, timeout)
```

I'm running with 48 worker containers, each with 1 vCPU and 8GB memory.  Workers are started with the following command:
`["dask-worker","dask-scheduler.local-dask:8786","--memory-limit","7000MB","--worker-port","9000","--no-nanny","--no-dashboard","--death-timeout","30","--nthreads","2","--nprocs","1","--reconnect"]`

I've tried with `--nthreads 1` too but the behavior is the same.  Out of 48 about half the workers finish successfully, a few get stuck immediately, and some run for a while and then hang.

Reverting to s3fs 0.4.2 / fsspec 0.7.4 fixes the problem.

@martindurant your simplified version takes a long time on my smallish notebook instance - I lost patience after about 10min.  Running file mapping delayed on the workers is much faster (~8 seconds).

**Comment by stevengillard** [comment] 2021-06-25 04:39
Logs from one of the hung workers attached...
[log-events-viewer-result.txt](https://github.com/dask/dask/files/6713576/log-events-viewer-result.txt)

**Comment by stevengillard** [comment] 2021-07-01 21:30
I've tracked this down, at least in my case, to global locking performed in the h5py library which is used by the h5netcdf engine in xarray.

I managed to reproduce the issue semi-reliably on a single worker and hooked up gdb to the hung fsspecIO thread.  The stack trace shows the python garbage collector attempting to acquire a lock during clean-up of a h5py object. 

This is the sequence of events:
1. Dask worker thread acquires the global h5py lock through h5py [`Dataset.__getitem__`](https://github.com/h5py/h5py/blob/master/h5py/_hl/dataset.py#L661) as you can see in the call stack from my earlier comment (although sometimes it occurs via a different method, they all acquire the lock)
2. The request is passed to fsspec and s3fs as a read
3. An S3 range request is submitted as a coroutine to the fsspecIO thread's event loop in [`fsspec.sync`](https://github.com/intake/filesystem_spec/blob/master/fsspec/asyn.py#L55).  
4. Sometimes python garbage collection occurs during the fsspecIO thread's execution
5. If the garbage collector running in the fsspecIO thread decides to clean up a h5py object, it calls  [`ObjectID.__dealloc__`](https://github.com/h5py/h5py/blob/master/h5py/_objects.pyx#L194) and attempts to acquire the global h5py lock
6. The two threads are now deadlocked and the worker hangs indefinitely

I'm not sure what the best fix might be, but a few ideas that came to mind:
* A single-threaded mode for fsspec, that could be enabled through config when h5py is in use
* More of a work-around, disabling garbage collection during the  `fsspec.sync()` execution, or perhaps an explicit call to `gc.collect()` before handing off to the co-routine might work (I haven't tested though)
* Set timeouts on all `fsspec.sync()` calls
* More granular object-level locking in the h5py library (likely infeasible)

Is there anything else that could be done within dask or fsspec to avoid the deadlock?

Here's the stack trace: [fsspecIO-stacktrace.txt](https://github.com/dask/dask/files/6750864/fsspecIO-stacktrace.txt)

**Comment by martindurant** [comment] 2021-07-01 21:39
Thanks for digging! I **knew** it was hdf!

It might be interesting to see if this happens when fsspec io is on the same event loop as the worker. I'm not sure how you would arrange for that to happen with the current code.

On July 1, 2021 5:30:20 PM EDT, stevengillard ***@***.***> wrote:
>I've tracked this down, at least in my case, to global locking
>performed in the h5py library which is used by the h5netcdf engine in
>xarray.
>
>I managed to reproduce the issue semi-reliably on a single worker and
>hooked up gdb to the hung fsspecIO thread.  The stack trace shows the
>python garbage collector attempting to acquire a lock during clean-up
>of a h5py object. 
>
>This is the sequence of events:
>1. Dask worker thread acquires the global h5py lock through h5py
>[`Dataset.__getitem__`](https://github.com/h5py/h5py/blob/master/h5py/_hl/dataset.py#L661)
>as you can see in the call stack from my earlier comment (although
>sometimes it occurs via a different method, they all acquire the lock)
>2. The request is passed to fsspec and s3fs as a read
>3. An S3 range request is submitted as a coroutine to the fsspecIO
>thread's event loop in
>[`fsspec.sync`](https://github.com/intake/filesystem_spec/blob/master/fsspec/asyn.py#L55).
> 
>4. Sometimes python garbage collection occurs during the fsspecIO
>thread's execution
>5. If the garbage collector running in the fsspecIO thread decides to
>clean up a h5py object, it calls 
>[`ObjectID.__dealloc__`](https://github.com/h5py/h5py/blob/master/h5py/_objects.pyx#L194)
>and attempts to acquire the global h5py lock
>6. The two threads are now deadlocked and the worker hangs indefinitely
>
>I'm not sure what the best fix might be, but a few ideas that came to
>mind:
>* A single-threaded mode for fsspec, that could be enabled through
>config when h5py is in use
>* More of a work-around, disabling garbage collection during the 
>`fsspec.sync()` execution, or perhaps an explicit call to
>`gc.collect()` before handing off to the co-routine might work (I
>haven't tested though)
>* Set timeouts on all `fsspec.sync()` calls
>* More granular object-level locking in the h5py library (likely
>infeasible)
>
>Is there anything else that could be done within dask or fsspec to
>avoid the deadlock?
>
>Here's the stack trace:
>[fsspecIO-stacktrace.txt](https://github.com/dask/dask/files/6750864/fsspecIO-stacktrace.txt)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/dask/dask/issues/7547#issuecomment-872563337

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by martindurant** [comment] 2021-07-02 15:53
Might there be a simple solution by keeping hold of the h5py object's reference for the duration of IO? Maybe there are multiple objects that might get collected... 
Could that be done from the fsspec side?

**Comment by stevengillard** [comment] 2021-07-03 05:35
That's another option but it looks like the objects are being cleaned up during higher generations of garbage collection, so it probably can't be done from within fsspec.

I've run a few tests disabling and re-enabling garbage collection either side of the loop in `fsspec.sync()`, and that seems to do the trick.  I'll see how it goes at greater scale!

Looks like this issue has cropped up in a few other projects too, with the solution being to take control of when garbage collection runs: https://riverbankcomputing.com/pipermail/pyqt/2011-August/030378.html

**Comment by sharkinsspatial** [comment] 2021-10-11 19:48
@stevengillard, @cisaacstern has been working to create a simple, consistent reproducer for an equivalent issue.  I believe that your assessment of the stack trace here is the direction we should be looking and I was attempting to create an example where thread deadlock occurs due to the global h5py lock.  But my `h5py` operations don't seem to be creating a global lock even when opening in `a` mode in multiple threads simultaneously.
```
h5_file = h5py.File(file_path, "a")
```
Can you provide an example of the `xarray` operations (or lower level h5py operations) you were using which generated locks as you mentioned in "although sometimes it occurs via a different method, they all acquire the lock" https://github.com/dask/dask/issues/7547#issuecomment-872563337? This might be extremely helpful in creating a reproducer to tackle this issue.  Cheers.

**Comment by stevengillard** [comment] 2021-10-12 04:30
@sharkinsspatial below are the steps I used to reproduce on a single machine.  I'm running in AWS us-east-1, the same region as the [S3 dataset](https://registry.opendata.aws/ecmwf-era5/).  It's not consistent, for me the worker process deadlocks about 50% of the time.

First start a scheduler and single worker with s3fs debugging enabled:
```
export S3FS_LOGGING_LEVEL=DEBUG
dask-scheduler &   
dask-worker --nthreads 1 localhost:8786
```
Then run the following python script in a different terminal:
```
import xarray as xr
import s3fs
import dask
import time
import json
from dask.distributed import Client

@dask.delayed
def s3open(path):
    fs = s3fs.S3FileSystem(anon=True, default_fill_cache=False)
    return fs.open(path)

client = Client('localhost:8786')

# Opening a single file is usually enough
files_mapper = [s3open('s3://era5-pds/2020/12/data/sea_surface_temperature.nc')]
ds = xr.open_mfdataset(files_mapper, engine='h5netcdf',
                       chunks={'lon':200,'lat':200,'time0':720},
                       concat_dim='time0',
                       combine='nested',
                       coords='minimal',
                       compat='override',
                       parallel=True)

# A short pause here makes the deadlock more likely for some reason
time.sleep(1)
# Read dataset into worker memory
ds = client.persist(ds)

# Output the stats and worker call stack every 5 seconds to monitor progress
while(1):
    print(json.dumps(client.scheduler_info(),indent=2))
    print(json.dumps(client.call_stack(),indent=2))
    time.sleep(5)
```

Let it run for a little while, if the worker stops displaying s3fs debug logs while there are still queued tasks you've likely got it deadlocked.  You may need to run it a few times before it happens.

**Comment by TomAugspurger** [comment] 2021-12-17 20:27
We're making some progress on this in https://github.com/h5py/h5py/issues/2019, https://github.com/h5netcdf/h5netcdf/pull/117, and linked issues.

There might be some fixes possible at the fsspec level, but for now it seems like updating libraries to avoid circular references if possible is the best path forward. Either way, I don't think there's anything Dask can do, so I'm closing this.

**Closed by TomAugspurger** 2021-12-17 20:27 UTC
Labels: io, needs info

**Comment by ifenty** [comment] 2022-03-03 22:10
@TomAugspurger @stevengillard 

I think I'm confronting this same issue, indefinite thread hanging when using open_mfdataset + parallel=True with a dask cluster to read files via s3fs.

Is there a known set of library versions before or after this bug which are known to work (i.e., allow open_mfdataset to open s3fs files in parallel with dask?).

I'm operating on a 'brand new' juypterhub environment.
