### ISSUE TITLE
Second Dask DataFrame computation breaks due to sklearn import

### ISSUE THREAD

**Issue by bstadlbauer** [dask/dask#5718] opened 2019-12-17 10:03 UTC
Hi!

Using the example below, I observed that the second dataframe (`df1`) will not be loaded (`ProgressBar` gets stuck at 0%) when I import `sklearn`. When `sklearn` is not imported, everything works as expected.

```
import dask.diagnostics
import dask.dataframe as dd

import sklearn  # This import causes problems

dask.config.set(scheduler='processes')
pbar = dask.diagnostics.ProgressBar()
pbar.register()

df = dd.read_csv("data.csv").compute()
df1 = dd.read_csv("data.csv").compute()
```

Test data can be generated using the following script: 
```
import numpy as np
import pandas as pd

pd.DataFrame.from_dict({'foo': np.random.randn(int(1e7))}).to_csv('data.csv', header=None)

```

This was tested the following (`conda`) environment on macOS Mojave (10.14.6): 

```
channels:
  - defaults
dependencies:
  - blas=1.0=mkl
  - bokeh=1.4.0=py36_0
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py36_0
  - click=7.0=py36_0
  - cloudpickle=1.2.2=py_0
  - cytoolz=0.10.1=py36h1de35cc_0
  - dask=2.9.0=py_0
  - dask-core=2.9.0=py_0
  - distributed=2.9.0=py_0
  - freetype=2.9.1=hb4e5f40_0
  - fsspec=0.6.0=py_0
  - heapdict=1.0.1=py_0
  - intel-openmp=2019.4=233
  - jinja2=2.10.3=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=he5867d9_2
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.1.0=hcb84e12_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - locket=0.2.0=py36hca03003_1
  - markupsafe=1.1.1=py36h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py36hfbe908c_0
  - mkl_fft=1.0.15=py36h5e564d8_0
  - mkl_random=1.1.0=py36ha771720_0
  - msgpack-python=0.6.1=py36h04f5b5a_1
  - ncurses=6.1=h0a44026_1
  - numpy=1.17.4=py36h890c691_0
  - numpy-base=1.17.4=py36h6575580_0
  - olefile=0.46=py36_0
  - openssl=1.1.1d=h1de35cc_3
  - packaging=19.2=py_0
  - pandas=0.25.3=py36h0a44026_0
  - partd=1.1.0=py_0
  - pillow=6.2.1=py36hb68e598_0
  - pip=19.3.1=py36_0
  - psutil=5.6.7=py36h1de35cc_0
  - pyparsing=2.4.5=py_0
  - python=3.6.9=h359304d_0
  - python-dateutil=2.8.1=py_0
  - pytz=2019.3=py_0
  - pyyaml=5.2=py36h1de35cc_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.21.3=py36h27c97d8_0
  - scipy=1.3.2=py36h1410ff5_0
  - setuptools=42.0.2=py36_0
  - six=1.13.0=py36_0
  - sortedcontainers=2.1.0=py36_0
  - sqlite=3.30.1=ha441bb4_0
  - tblib=1.5.0=py_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py36h1de35cc_0
  - wheel=0.33.6=py36_0
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zict=1.0.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
```

**Comment by TomAugspurger** [comment] 2019-12-17 12:15
That's a strange one! @bstadlbauer can you provide a reproducible example? In particular, is the `read_csv` needed, or can you create a NumPy array in memory and pass that to the DataFrame? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports may be helpful.

**Comment by TomAugspurger** [comment] 2019-12-17 12:16
Ah, just saw your second code block making the data. Thanks.

**Comment by bstadlbauer** [comment] 2019-12-17 12:30
That seems strange, I just tested the same on my linux machine (Ubuntu 18.04.3 with `conda` 4.7.10). Environment was installed using:
`conda create -n dask-debug python=3.6 dask scikit-learn`
and can reproduce the error

**Comment by TomAugspurger** [comment] 2019-12-17 14:58
Yep, I used the same versions. Only difference is that I'm on MacOS. I don't really have any guesses about what the cause might be.

**Comment by bstadlbauer** [comment] 2019-12-18 09:00
Ok that is strange. I build a docker container and ran it on my Mac to get a reproducible example. Does the following also work for you: 
```
docker pull bstadlbauer/dask-debug
docker run -it bstadlbauer/dask-debug
```
And then in the container: 
`/opt/conda/envs/dask-debug/bin/python /data/dask_debug.py`

`dask_debug.py` is a copy of the script above.

**Comment by mrocklin** [comment] 2019-12-18 14:44
I also tried the original reproducer on both mac and linux and wasn't able to reproduce.  In the interests of time I'm going to pass on pulling down and running your docker image, my apologies.

**Comment by jrbourbeau** [comment] 2020-04-01 22:59
I'm also not able to reproduce using `conda create -n dask-debug python=3.6 dask scikit-learn` on a Mac. @bstadlbauer I'm going to close this issue for the time being as we haven't been able to reproduce the issue. We can reopen if someone is able to reproduce

**Closed** 2020-04-01 23:00 UTC
