### ISSUE TITLE
[bug] dask.dataframe.DataFrame.merge fails for inner join

### ISSUE THREAD

**Issue by trstovall** [dask/dask#4643] opened 2019-03-28 21:39 UTC
## Setup
```python
from pandas import DataFrame
from dask.delayed import delayed
from dask.dataframe import from_delayed

A = from_delayed([
  delayed(DataFrame)({'x': range(i, i+5), 'a': range(i, i+5)})
  for i in range(0, 10, 5)
])

B = from_delayed([
  delayed(DataFrame)({'x': range(i, i+5), 'b': range(i, i+5)})
  for i in range(0, 10, 5)
])

C = A.merge(
  B, on=('x',), how='inner'
)
```

## Traceback
```python
>>> C.compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/conda/lib/python3.6/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/conda/lib/python3.6/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/conda/lib/python3.6/site-packages/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "/conda/lib/python3.6/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/conda/lib/python3.6/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/conda/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/conda/lib/python3.6/site-packages/dask/optimization.py", line 942, in __call__
    dict(zip(self.inkeys, args)))
  File "/conda/lib/python3.6/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/conda/lib/python3.6/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/conda/lib/python3.6/site-packages/dask/compatibility.py", line 93, in apply
    return func(*args, **kwargs)
  File "/conda/lib/python3.6/site-packages/dask/dataframe/core.py", line 3794, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/conda/lib/python3.6/site-packages/dask/dataframe/shuffle.py", line 417, in partitioning_index
    return hash_pandas_object(df, index=False) % int(npartitions)
  File "/conda/lib/python3.6/site-packages/pandas/core/util/hashing.py", line 117, in hash_pandas_object
    h = Series(h, index=obj.index, dtype='uint64', copy=False)
  File "/conda/lib/python3.6/site-packages/pandas/core/series.py", line 262, in __init__
    .format(val=len(data), ind=len(index)))
ValueError: Length of passed values is 0, index implies 5
```
## Version
```python
>>> pandas.__version__
'0.23.4'
>>> dask.__version__
'1.1.4'
```

**Comment by mrocklin** [comment] 2019-03-28 21:51
Reproduced.  Thanks for the excellent bug report.

**Comment by trstovall** [comment] 2019-04-02 15:33
This bug doesn't occur when `pandas.DataFrame` is replaced by `cudf.DataFrame`.

**Comment by jakirkham** [comment] 2019-06-03 20:34
An thoughts on this one, @TomAugspurger?

**Comment by TomAugspurger** [comment] 2019-06-03 20:51
Due to https://github.com/pandas-dev/pandas/issues/24318, we need to not call `hash_pandas_object` on empty data frames. It's not clear what pandas should do in that case, so I think dask needs to work around it.

I suspect `shuffle` and `partitioning_index` would both need to be updated to handle empty partitions somehow, but I haven't looked into what they should do (and don't plan to any time soon).

**Comment by saravananpsg** [comment] 2020-10-11 11:43
I am facing the same issue when joining multiple dask data-frames using inner join on a multi-core cpu ?

Version:
Dask - '2.20.0'
Pandas - '0.24.2'

Code Snippet:
   dfs=[]
   for file in csv_files:
        df = pd.read_csv(file)
        df = dd.from_pandas(df, npartitions=20)
        df['key'] = df.map_partitions(
            lambda mdf: mdf.apply(lambda row: get_value(row), axis=1)
        ).compute(scheduler='processes')
       df.set_index('key')
        dfs.append(df)

    df_merged = reduce(lambda left, right: dd.merge(left, right,
                                                    left_index=True, 
                                                    right_index=True,
                                                    on=['key'],
                                                    how='inner', 
                                                    suffixes=('', '_y')), dfs)

The same inner join works fine when we pass the compute='sync'; however, compute='processes' yields incorrect results.

**Comment by saravananpsg** [comment] 2020-10-13 20:04
@mrocklin @TomAugspurger  any advise on this!

**Comment by TomAugspurger** [comment] 2020-10-13 20:36
@saravananpsg does https://github.com/dask/dask/issues/4643#issuecomment-498421892 answer your question?

This issue raises a traceback, but you mention incorrect results. Are you sure your issue is the same?

**Comment by saravananpsg** [comment] 2020-10-14 04:18
Yes. It may be related to this issue. 

In my case, the inner join results are more like a outer join. I am getting additional unmatched rows when joining multiple dataframes on a distributed systems. I tried with/without shuffle ~ with respect to task level(shuffle='task') during merging. No luck though :-(

Also tried to 
  - convert back to pandas df and reset the index 
  - tried to merge the results in pandas, the results are not the same as expected for inner join

Is there any workaround for this ? 

Kindly provide your thoughts on this!

**Comment by lfdversluis** [comment] 2020-12-08 14:18
I see the merge function is still bugged, both for outer and inner. Any way to mitigate this? I tried to use `align` to make sure the dataframes have the same indices/columns but that seems unsupported atm.

**Comment by saravananpsg** [comment] 2020-12-09 03:24
One way is to break down the functionalities (suppose if you are computing data at different points); then write the files as and when required, by this way the partitioned index can be wiped away.

**Comment by jsignell** [comment] 2020-12-09 22:07
I think this is fixed on dask master. I just failed to reproduce the MRE on dask master with pandas 1.1.4.

**Comment by jakirkham** [comment] 2020-12-14 07:39
We also just released on Friday. So this may already be fixed in a release. Would make sure to upgrade and see if there’s still an issue.

**Comment by jsignell** [comment] 2020-12-14 15:12
I am going to close this, but feel free to reopen or comment if you can still reproduce.

**Closed by jsignell** 2020-12-14 15:12 UTC
Labels: dataframe

**Comment by lampda** [comment] 2022-01-08 16:02
Has this bug fixed already? 

When I do outer merge,  I had this error message: 
*"ValueError: Length of passed values is 0, index implies 48679."*

My pandas is of version '1.1.5' while dask '2021.03.0'

**Comment by jakirkham** [comment] 2022-01-08 21:28
@lampda would suggest raising a new issue with a minimal reproducer
