### ISSUE TITLE
Numpy Ufunc behaves differently with Dask Arrays

### ISSUE THREAD

**Issue by theXYZT** [dask/dask#7651] opened 2021-05-12 19:02 UTC
When I use the `out` parameter in Numpy Ufuncs, Dask does not respect the `dtype` of the output array - this causes a discrepancy in the results when comparing the same code involving Numpy Arrays and Dask Arrays.

Here's a simple example:

**In Numpy:**

```python
In [1]: x, y, z = np.arange(8), np.arange(8), np.empty(8)

In [2]: x.dtype, y.dtype, z.dtype
Out[2]: (dtype('int32'), dtype('int32'), dtype('float64'))

In [3]: np.add(x, y, out=z)
Out[3]: array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.])

In [4]: z.dtype
Out[4]: dtype('float64')
```

I create two integer arrays `x` and `y`, and a floating-point empty array `z`. When `z` is used as the output of a ufunc, the result respects the original dtype. Since `z` is a `float64` array, it stays a `float64` array.

**In Dask:**

```python
In [1]: import dask.array as da

In [2]: x, y, z = da.arange(8), da.arange(8), da.empty(8)

In [3]: x
Out[3]: dask.array<arange, shape=(8,), dtype=int32, chunksize=(8,), chunktype=numpy.ndarray>

In [4]: y
Out[4]: dask.array<arange, shape=(8,), dtype=int32, chunksize=(8,), chunktype=numpy.ndarray>

In [5]: z
Out[5]: dask.array<empty, shape=(8,), dtype=float64, chunksize=(8,), chunktype=numpy.ndarray>

In [6]: np.add(x, y, out=z)

In [7]: z
Out[7]: dask.array<add, shape=(8,), dtype=int32, chunksize=(8,), chunktype=numpy.ndarray>
```

As you can see, `z` is simply replaced by `x + y` instead: It is now an `int32` array instead of `float64` - different behavior when compared to the pure Numpy case.

---

**Environment**:

- Dask version: 2021.4.1
- Python version: 3.8.8
- Operating System: Windows 10 Home 20H2
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment] 2021-05-14 16:31
Hmm that's an interesting issue. It seems like at the moment `out` is not fully supported in dask. There are two issues actually. One is that the meta does not stay consistent and the other is that the computed value does not stay consistent either because the dtype information isn't passed down into the actual computation. I am going to ping @rjzamora on this since it has to do with blockwise, but I'd be interested in thinking more about whether and how dask can better support `out` kwargs.

**Comment by douglasdavis** [comment] 2021-05-17 13:57
@rjzamora Julia pointed me here, pinging to let you know I'll be taking a look.

**Comment by jsignell** [comment] 2021-06-03 19:50
I like the direction that you are going down in your branch. Is the issue in the tests because the type coercion happens after the chunk is computed?

**Comment by douglasdavis** [comment] 2021-06-03 20:43
Julia Signell ***@***.***> writes:

> I like the direction that you are going down in your branch. Is the
> issue in the tests because the type coercion happens after the chunk
> is computed?

I would venture to guess that is the case! Another possible route would
be to cast the result to the dtype of out, then set out's inner
components (_chunks, dast, _meta, _name) to results. I haven't tried
this though.

It all begs the question: is even a reasonable thing to do in Dask :)

I see two arguments that go in opposite directions:

1. For the sake of maintaining compatibility with NumPy this type of call
should be supported

2. Suggest users avoid using `out=` because Dask does not follow the
pre-allocate-your-data pattern that `out=` accomplishes. a new array
will be allocated wherever the computation occurs, independent of
whatever dtypes are flying around.

**Comment by jsignell** [comment] 2021-06-03 21:07
If you are hitting a wall, I think it is totally reasonable to throw an error if the user includes out, and instead recommend that they use `dtype` since that is already supported and accomplishes the same thing :)

**Comment by douglasdavis** [comment] 2021-06-04 20:18
I agree that declaring a desired dtype is a better way to go; but there appears to be an issue there as well :)

```python
In [20]: x, y = da.arange(8), da.arange(8)

In [21]: x.dtype, y.dtype
Out[21]: (dtype('int64'), dtype('int64'))

In [22]: da.add(x, y, dtype='f8')
Out[22]: dask.array<add, shape=(8,), dtype=float64, chunksize=(8,), chunktype=numpy.ndarray>

In [23]: z = da.add(x, y, dtype='f8')

In [24]: z.dtype
Out[24]: dtype('float64')

In [25]: z.compute().dtype
Out[25]: dtype('int64')
```

The collection believes it has a certain dtype (in this case `float64`, but obviously the underlying graph will yield a result with a different dtype, the `int64`). 

It becomes more interesting if we try to use `da.astype`, first with `float64`:

```python
In [45]: z.astype(np.float64)
Out[45]: dask.array<add, shape=(8,), dtype=float64, chunksize=(8,), chunktype=numpy.ndarray>

In [46]: z.astype(np.float64).compute()
Out[46]: array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [47]: z.astype(np.float64).compute().dtype
Out[47]: dtype('int64')
```

It doesn't actually change the underlying type because the collection things we asked for astype with the existing type. If we ask for `astype` with a type different from what the collection believes, then we get expected behavior:

```python
In [48]: z.astype(np.float32)
Out[48]: dask.array<astype, shape=(8,), dtype=float32, chunksize=(8,), chunktype=numpy.ndarray>

In [49]: z.astype(np.float32).compute()
Out[49]: array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14.], dtype=float32)

In [50]: z.astype(np.float32).compute().dtype
Out[50]: dtype('float32')
```

**Comment by martindurant** [comment] 2021-06-04 20:27
It seems that dask *should* support the `dtype` parameter in a ufunc, and this should be fixed. In that case, all of the examples would work correctly. Nevertheless, `out=` still is contrary to how Dask works, so that's a separate issue.

**Comment by douglasdavis** [comment] 2021-06-16 20:14
The idea of an existing pre-allocated array does not exist for dask, if you use `out=` the dask graph of `out` just gets overwritten such that `z = x + y` and `da.add(x, y, out=z)` yield a `z` instance with exactly the same graph. In #7808 we fixed a bug to enforce dtype is conserved when explicitly requested. One can use `z = da.add(x, y, dtype=z.dtype)` to trigger that behavior. Going ahead and closing this.

**Closed by douglasdavis** 2021-06-16 20:14 UTC
Labels: array
