### ISSUE TITLE
timeseries resample import error

### ISSUE THREAD

**Issue by xysmas** [dask/dask#1075] opened 2016-04-01 16:56 UTC
When testing out dask for timeseries operations using [this notebook](https://app.mybinder.org:80/1781888879/notebooks/time-series-binder.ipynb), 
I get the following error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-d6f66cb86854> in <module>()
----> 1 df.A.cumsum().resample('1w', how='mean').compute().plot();

/ImportError                               Traceback (most recent call last)
<ipython-input-56-9333c6071787> in <module>()
----> 1 df.index.resample("1w", how='mean')

/home/aaron/anaconda3/lib/python3.5/site-packages/dask/dataframe/core.py in resample(self, rule, how, closed, label)
    980     @derived_from(pd.Series)
    981     def resample(self, rule, how=None, closed=None, label=None):
--> 982         from .tseries.resample import _resample
    983         return _resample(self, rule, how=how, closed=closed, label=label)
    984 

ImportError: No module named 'dask.dataframe.tseries'
```
This is on anaconda python 3.5.1, dask 0.8.1, and fedora 64bit. 
Note that another person, @basnjiholt, [sees this issue as well](https://github.com/binder-project/example-conda-environment/issues/2). 

I have a simple fix for it:

adding 
```
from .tseries.resample import _resample
```
to ```dask/dataframe/__init__.py```  but I am not sure how you guys want to handle it. 

Notably, this error doesn't occur on a freshly-built copy for OSX 10.10.5 with otherwise similar settings.

**Comment by jcrist** [comment] 2016-04-01 17:06
This was caused by https://github.com/dask/dask/issues/1067, and should be fixed in the latest release. If you pip install from git, everything should work:

`pip install git+https://github.com/dask/dask.git`

**Comment by xysmas** [comment] 2016-04-01 17:07
got it! that explains the mismatch between my test on my mac (installed from git) and the run from conda on the linux box.

thanks!

**Closed** 2016-04-01 17:10 UTC
