### ISSUE TITLE
Issue reading Parquet via Impala

### ISSUE THREAD

**Issue by nicolafourchette** [dask/dask#5856] opened 2020-01-31 20:11 UTC
Python : `3.6.9`
Dask : `2.6.0`
Related issue : [here](https://github.com/elastacloud/parquet-dotnet/issues/334)

I am saving a partitioned parquet file on a S3 bucket using Dask as such :
```python
dd.to_parquet(
    dd.from_pandas(df, npartitions=1),
    path='s3a://test/parquet',
    engine='fastparquet',
    partition_on='country',
    object_encoding='utf8',
    compression="gzip",
    write_index=False,
)
```
Parquet files are successfuly created ; I attached an [example](https://github.com/dask/dask/files/4141271/test.zip).
I am successfuly creating an Impala table from this parquet :
```sql
create external table tmp.countries_france
like parquet 's3a://test/parquet/_metadata'
partitioned by (country string)
stored as parquet location 's3a://test/parquet/'
```
As well as adding a partition to this table :
```sql
alter table tmp.countries_france add partition (sheet='belgium')
```
However when I do a `select * from tmp.countries_france` I get the following error :
> File 's3a://test/parquet/sheet=france/part.0.parquet' is corrupt: metadata indicates a zero row count but there is at least one non-empty row group.

I guess the problem comes from Dask because when I create a non-partitioned parquet this works fine. I've tried setting `write_index=True` but no luck.

**Comment by jrbourbeau** [comment] 2020-01-31 21:13
Thanks for opening an issue @nicolafourchette! Could you try with a newer version of Dask (e.g. `2.10.1`)? There have been several parquet-related updates since `2.6.0`.

If updating doesn't resolve the issue you're seeing, could you provide a minimal reproducer? https://blog.dask.org/2018/02/28/minimal-bug-reports

**Comment by nicolafourchette** [comment] 2020-02-03 07:34
Hi @jrbourbeau and thanks ! I've tried with the latest version however it still does not work. 
Here are the steps to reproduce : 

1. Create pandas dataframe and save it as parquet using Dask :
```python
import pandas as pd
import dask.dataframe as dd

d = {'col1': ['1', '2'], 'col2': ['3', '4']}
df = pd.DataFrame(data=d)

dd.to_parquet(
    dd.from_pandas(df, npartitions=1),
    path=f'./test/parquet/',
    engine='fastparquet',
    partition_on='col1',
    object_encoding='utf8',
    compression="gzip",
    write_index=False,
)
```
2. Upload the created parquet folders to S3 : 
```
test
    |-- parquet
        |-- _common_metadata
        |-- _metadata
        |-- col1=1
            |-- part.0.parquet
        |-- col2=2
            |-- part.0.parquet
```
3. Create Impala table from parquet : 
```sql
create external table tmp.test
like parquet 's3a://test/parquet/_metadata'
partitioned by (col1 string)
stored as parquet location 's3a:///test/parquet/'
```
Output `Table has been created.`

4. Add partition to newly created table : 
```sql
alter table tmp.test add partition (col1='1')
```
Output `New partition has been added to the table.`

5. Query table :
```sql
select * from tmp.test
```
Output

> Query 100% Complete (1 out of 1)
File 's3a://test/parquet/col1=1/part.0.parquet' is corrupt: metadata indicates a zero row count but there is at least one non-empty row group.

However when I write the parquet without partitionning it works well : 
```python
dd.to_parquet(
    dd.from_pandas(df, npartitions=1),
    path=f'./test/parquet/',
    engine='fastparquet',
    object_encoding='utf8',
    compression="gzip",
    write_index=False,
)
```
Let me know if you need anything !

**Comment by jcrist** [comment] 2020-02-04 16:22
Can you try using `engine="pyarrow"`? This would be useful to determine if the bug is with dask's wrapping of the backends, or a bug in `fastparquet` itself (my guess is the latter).

**Comment by nicolafourchette** [comment] 2020-02-05 09:03
@jcrist same behavior with `engine="pyarrow"`

**Comment by TomAugspurger** [comment] 2020-02-05 12:14
Can you post the full traceback?

Are you able to step through with a debugger to see where things go wrong?

**Comment by TomAugspurger** [comment] 2020-02-05 12:16
Ah, sorry, I see the reading is happening from Impala.

To debug this, I would create two similar datasets with the same values / partitioning; one created by dask and one by impala. Then you can look at the metadata files to see how they differ.

**Comment by TomAugspurger** [comment] 2020-02-07 14:03
@nicolafourchette have you had a chance to examine files generated by impala? Do you think the issue is in the files dask / pyarrow is writing, or is it on the impala reader side?

**Comment by nicolafourchette** [comment] 2020-02-10 08:06
@TomAugspurger, I haven't had the chance to examine the files yet, I'm using pandas `to_parquet` until I get to put more time into understanding where the problem comes from. However I cannot say whether the issue is in the files dask / pyarrow is writing or on the impala reader side but the parititioned parquet files written by pandas can be read by Impala if that helps. I'll examine as soon as I have a bit of time :)

**Comment by quasiben** [comment] 2020-04-30 14:02
@nicolafourchette there have been some changes in parquet handling in dask.  Would be good to test if latest dask fixes your issue

**Comment by nicolafourchette** [comment] 2020-05-04 14:12
@quasiben I've tried with version `2.15.0` and the problem still persists for both `pyarrow` and `fastparquet` engines

**Comment by jsignell** [comment] 2021-03-12 14:15
There have been lots more changes in parquet handling. So if you are able to try it again with dask 2021.03.0 you might find that it works, otherwise it'll be helpful to post a full traceback.

**Comment by jsignell** [comment] 2021-11-02 14:15
Closing this for now, but feel free to reopen if you are able to try with recent versions and provide a traceback.

**Closed by jsignell** 2021-11-02 14:15 UTC
Labels: dataframe, io, needs info, parquet
