### ISSUE TITLE
parquet RangeIndex gets dtype "object" with fastparquet

### ISSUE THREAD

**Issue by martindurant** [dask/dask#6975] opened 2020-12-15 15:07 UTC
From:
https://stackoverflow.com/questions/65307263/writing-a-dask-dataframe-to-parquet-typeerror/65308232

```
import pandas as pd
import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq
import dask.dataframe as dd

file = 'example.parquet'
file_res = 'example_res.parquet'

# Generate a random df
df = pd.DataFrame(np.random.randint(100,size=(100000, 1)),columns=['A'])

# Write 1st parquet file with pyarrow
table = pa.Table.from_pandas(df)
pq.write_table(table, file, version='1.0')

# Read it back with Dask, and write it again
dd_df = dd.read_parquet(file, engine="fastparquet")
dd_df.to_parquet(file_res, engine="fastparquet")
```

**What happened**:
`dd_df.index` has type "object", but contains `RangeIndex(start=0, stop=100000, step=1)`. Upon writing, fastparquet tries to encode the integers as UTF8 and fails: `TypeError: expected list of bytes`.

**Comment by jsignell** [comment] 2020-12-18 14:02
Hmm maybe we take inspiration from what the pyarrow engine does, since that one seems to work.

**Comment by bryanwweber** [comment] 2022-03-25 17:32
The reproducer in the original issue no longer raises a `TypeError` for me. I'm going to close the issue, but please feel free to reopen if I missed something 😄

**Closed by bryanwweber** 2022-03-25 17:32 UTC
Labels: dataframe, io, parquet
