### ISSUE TITLE
Reading parquet files from a google cloud storage raises not implemented error (under pyarrow engine at least)

### ISSUE THREAD

**Issue by cdagnino** [dask/dask#4009] opened 2018-09-24 18:15 UTC
Versions

Python 3.6.5 :: Anaconda, Inc.
Dask: 0.18.1
gcsfs: 0.1.2
Pandas: 0.23.3

```
import dask.dataframe as dd
pandas_df = pd.DataFrame({'x' : [2,3, 2], 'y': [1, 0, 0]})
dask_df = dd.from_pandas(pandas_df, npartitions=2)
dask_df.to_parquet("gcs://my_google_bucket/test/")
```

But when I try to read it back

`read_again_df = dd.read_parquet("gcs://my_google_bucket/test/")`

It gives me this traceback

```
AttributeError                            Traceback (most recent call last)
~/miniconda3/envs/env1/lib/python3.6/site-packages/dask/bytes/core.py in get_pyarrow_filesystem(fs)
    520     try:
--> 521         return fs._get_pyarrow_filesystem()
    522     except AttributeError:

AttributeError: 'DaskGCSFileSystem' object has no attribute '_get_pyarrow_filesystem'

During handling of the above exception, another exception occurred:

NotImplementedError                       Traceback (most recent call last)
<ipython-input-42-ef1fc41d04d5> in <module>()
----> 1 read_again = dd.read_parquet("gcs://my_google_bucket/test/")

~/miniconda3/envs/env1/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, infer_divisions)
    991 
    992     return read(fs, fs_token, paths, columns=columns, filters=filters,
--> 993                 categories=categories, index=index, infer_divisions=infer_divisions)
    994 
    995 

~/miniconda3/envs/env1/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in _read_pyarrow(fs, fs_token, paths, columns, filters, categories, index, infer_divisions)
    505         columns = list(columns)
    506 
--> 507     dataset = pq.ParquetDataset(paths, filesystem=get_pyarrow_filesystem(fs))
    508     if dataset.partitions is not None:
    509         partitions = [n for n in dataset.partitions.partition_names

~/miniconda3/envs/env1/lib/python3.6/site-packages/dask/bytes/core.py in get_pyarrow_filesystem(fs)
    522     except AttributeError:
    523         raise NotImplementedError("Using pyarrow with a %r "
--> 524                                   "filesystem object" % type(fs).__name__)

NotImplementedError: Using pyarrow with a 'DaskGCSFileSystem' filesystem object
```

I asked about this [here in stackoverflow](https://stackoverflow.com/questions/52482961/using-dask-to-read-parquet-files-from-a-google-cloud-storage/52483227#52483227) and @martindurant suggested using the `fastparquet` engine. This works for me:

```
pandas_df = pd.DataFrame({'x' : [2,3, 2], 'y': [1, 0, 0]}) 
dask_df = dd.from_pandas(pandas_df, npartitions=2) 
dask_df.to_parquet("gcs://my_bucket/test", engine='fastparquet') 
read_again_df = dd.read_parquet("gcs://my_bucket/test/", engine='fastparquet')
```

Not sure if this is a bug or if it's just not implemented under the `pyarrow` engine. If it's the latter, I think it would be nice to include a: "please try fastparquet engine" message.

**Comment by jcrist** [comment] 2018-09-24 18:33
The error is accurate - pyarrow with gcsfs isn't implemented.

I think for major filesystems - `s3`, `hdfs`, and `gcs`, it makes sense to push our wrappers into `dask.bytes`. In this case it would be pretty easy to wrap `gcsfs` to fit the arrow filesystem interface. We do this for `s3fs` as well.

**Comment by martindurant** [comment] 2018-09-24 19:07
Is this something that could/should be part of fsspec? Writing a generic wrapper for any conformant file-system seems like a better idea than writing wrappers for each - although the wrappers would be few and simple (and we already have some). Even better, what would it take to make a fsspec be directly compatible with arrow's expectations? The following methods are all part of the spec: isfile, isdir, open, glob, ukey, size; mkdirs is missing.

**Comment by jcrist** [comment] 2018-09-24 19:13
The major issue is that the implementation of `walk` in arrow matches that of `os.walk`, while the method in s3fs, gcsfs, etc... doesn't. Other than that, everything else is minor discrepancies and that arrow explicitly checks for a subclass for its filesystems (which can be handled with a trivial wrapper).

**Comment by martindurant** [comment] 2018-09-24 19:17
The fsspec implementation of [`walk()`](https://github.com/martindurant/filesystem_spec/blob/master/fsspec/spec.py#L183) matches the python builtin one (at least, with the default `simple=False`) - and only requires a subclass filesystem to implement `ls`. 

Therefore it might be attractive to arrow to use fsspec exactly for this purpose (note that memory, http and local file-systems are included as example implementations). Do you think we can encourage people to get onboard?

**Comment by jcrist** [comment] 2018-09-24 19:20
Why have the `simple` parameter at all? I really think we should match the python interface as much as possible.

> Do you think we can encourage people to get onboard?

I personally don't have the bandwidth to pursue this. I suggest discussing it on the arrow jira.

**Comment by martindurant** [comment] 2018-09-24 19:38
> I really think we should match the python interface as much as possible.

Fair enough, you have persuaded me on this.

**Comment by wesm** [comment] 2018-09-25 11:30
What action do we need to take?

**Comment by mrocklin** [comment] 2018-09-25 13:17
This seems to work:

```python
In [1]: import pyarrow.parquet as pq

In [2]: import gcsfs

In [3]: fs = gcsfs.GCSFileSystem(token='anon')

In [4]: f = fs.open('anaconda-public-data/nyc-taxi/nyc.parquet/part.0.parquet')

In [5]: table = pq.read_table(f)

In [6]: table.to_pandas().head(5)
Out[6]: 
  tpep_pickup_datetime  VendorID tpep_dropoff_datetime  passenger_count  \
0  2015-01-01 00:00:00         1   2015-01-01 00:11:26                5   
1  2015-01-01 00:00:00         2   2015-01-01 00:00:00                1   
2  2015-01-01 00:00:00         2   2015-01-01 00:00:00                3   
3  2015-01-01 00:00:01         1   2015-01-01 00:03:49                1   
4  2015-01-01 00:00:03         2   2015-01-01 00:21:48                2   

   trip_distance  pickup_longitude  pickup_latitude  RateCodeID  \
0           4.00        -73.971436        40.760201           1   
1           1.68        -73.991547        40.750069           1   
2           1.56        -74.001320        40.729057           1   
3           0.80        -73.860847        40.757294           1   
4           2.57        -73.969017        40.754269           1   

  store_and_fwd_flag  dropoff_longitude  dropoff_latitude  payment_type  \
0                  N         -73.921181         40.768269             2   
1                  N           0.000000          0.000000             2   
2                  N         -74.010208         40.719662             1   
3                  N         -73.868111         40.752285             2   
4                  N         -73.994133         40.761600             2   

   fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
0         13.5    0.5      0.5         0.0           0.0   
1         10.0    0.0      0.5         0.0           0.0   
2          7.5    0.5      0.5         0.0           0.0   
3          5.0    0.5      0.5         0.0           0.0   
4         14.5    0.5      0.5         0.0           0.0   

   improvement_surcharge  total_amount  
0                    0.0          14.5  
1                    0.3          10.8  
2                    0.3           8.8  
3                    0.0           6.3  
4                    0.3          15.8  
```

Are there specific APIs that we need that don't work?

**Comment by wesm** [comment] 2018-09-25 13:30
This gets back to the standard filesystem API discussion from a while back that languished. I don't have the bandwidth to be the champion of that, unfortunately, but as the Ursa Labs team grows over the next year we might be able to take it on

Currently we have some s3fs-specific wrapper code: https://github.com/apache/arrow/blob/master/python/pyarrow/filesystem.py#L385. It may work if we simply accept any of the created-for-Dask filesystem interfaces

**Comment by martindurant** [comment] 2018-09-25 13:31
If I understand, the problem is not with opening individual files, as in the example above, but with walking the directory structure to find all the components of a dataset. In the pyarrow branch of our parquet code, we just call the pyarrow ParquetFile constructor, which takes a `filesystem=` keyword and explicitly checks that this input subclasses arrow abstract filesystem. There is code to do this for s3fs, and it could be made for gcsfs too.

**Comment by mrocklin** [comment] 2018-09-25 13:33
> This gets back to the standard filesystem API discussion from a while back that languished. I don't have the bandwidth to be the champion of that, unfortunately, but as the Ursa Labs team grows over the next year we might be able to take it on

If memory serves @martindurant tried championing this but conversation stalled.  He might be able to point to active issues on the topic.

https://github.com/martindurant/filesystem_spec

**Comment by martindurant** [comment] 2018-09-25 13:39
I can find
- https://jira.apache.org/jira/browse/ARROW-1319 (only about hdfs)
and I think the conversation I attempted to start was on the arrow mailing list.

**Comment by wesm** [comment] 2018-09-25 13:42
IIRC, we had a round of code review, and the next step from here would be to publish an artifact to PyPI and start writing some PRs to update the Arrow filesystems to utilize the common API. The way that Apache projects work, in the absence of major discussion, consensus is "lazy" and it's up to individuals to contribute work

Here's what one project said about it

> Lazy Consensus means that when you are convinced that you know what the community would like to see happen you can simply assume that you already have consensus and get on with the work. You don't have to insist people discuss and/or approve your plan, and you certainly don't need to call a vote to get approval. You just assume you have the communities support unless someone says otherwise.

**Comment by martindurant** [comment] 2018-09-25 13:45
I did put up an issue for code review (https://github.com/martindurant/filesystem_spec/pull/7 ) as requested, but no review happened. It could happen now, but I don't suppose people are any less busy.

**Comment by wesm** [comment] 2018-09-25 13:51
Here were @pitrou's original comments

https://lists.apache.org/thread.html/b3b367381b29da1b25915d0d8bc3fcdec35054749fd8cc890a7a2562@%3Cdev.arrow.apache.org%3E

I wrote this response, but there were no more comments, nor a link to the PR https://github.com/martindurant/filesystem_spec/pull/7 to review https://lists.apache.org/thread.html/ce6f79b65bee58b0beb07b912e59990a3e0a8344f47f5e35d5c5bbc6@%3Cdev.arrow.apache.org%3E

In my experience, patches are the best way to instigate progress. Would you like to start a patch, or would you like one of us to? I can open a JIRA issue about conforming to a shared filesystem API

**Comment by martindurant** [comment] 2018-09-25 14:00
Ah, that is where the communication break happened. The PR I made for review was referenced in the issue on filesystem_spec, together with a copy of your message. I didn't even know I could comment on your message.

**Comment by martindurant** [comment] 2018-09-28 14:20
The following does seem to work for adding pyarrow support to an fsspec-conformant FS: https://github.com/martindurant/filesystem_spec/pull/15 , i.e., I could load files with pyarrow-parquet from the memory or local FS implementations. 
Am I right in thinking that only the arrow parquet read methods support a filesystem= parameter, but not for writing?

**Comment by wesm** [comment] 2018-09-28 15:00
I was thinking the dependency would go the other way, i.e. that conformant filesystems would have a common base class, similar to the way that DBAPI 2.0 works.

There is the `write_to_dataset` method with writes a partition schema to a directory using an input filesystem

**Comment by martindurant** [comment] 2018-09-28 15:02
> I was thinking the dependency would go the other way

Ideally yes, I agree, but this shim may still be helpful in the meantime

**Comment by mrocklin** [comment] 2018-10-22 21:06
@martindurant I thought I'd ping you again on this to put it on your radar.  This is, I think, fairly high priority.

**Comment by martindurant** [comment] 2018-10-22 23:08
@mrocklin  let's talk about this live. @wesm , are you the best person to give an arrow perspective here, or is there someone else we should be talking to?

**Comment by wesm** [comment] 2018-10-22 23:15
@xhochy @pitrou @kszucs or I can advise -- I doubt that very much work is required to make things work so someone will need to write a patch

**Comment by mrocklin** [comment] 2018-10-22 23:15
Sure, I'm around tomorrow if you want to chat @martindurant

**Comment by martindurant** [comment] 2018-10-24 20:17
@cdagnino , would you be willing to try with the linked PR (you will need to update gcsfs from the branch, on your client and any remote workers)?

**Comment by cdagnino** [comment] 2018-10-27 14:19
@martindurant Sure! I'll try looking into this once I return to work on Monday.

How should I install your branch?
Git clone https://github.com/martindurant/gcsfs/tree/pyarrow + `python setup.py install` with my current version of `dask` (0.18.1) already installed?

**Comment by cdagnino** [comment] 2018-11-02 14:52
@martindurant It seems to work!

I tried with your branch and this code gave me the right result

```
import dask.dataframe as dd
import pandas as pd

pandas_df = pd.DataFrame({'x' : [2,3, 2], 'y': [1, 0, 0]})
dask_df = dd.from_pandas(pandas_df, npartitions=2)
dask_df.to_parquet("gcs://my_google_bucket/test/")

read_again_df = dd.read_parquet("gcs://my_google_bucket/test/")
```

Let me know if you need me to perform further tests. Thanks!

**Comment by martindurant** [comment] 2018-11-02 14:56
Thanks, @cdagnino . The PR in gcsfs is now merged.

**Closed** 2018-11-02 14:55 UTC
Labels: dataframe, io

**Comment by krishanam** [comment] 2019-08-28 11:06
> This seems to work:
> 
> ```python
> In [1]: import pyarrow.parquet as pq
> 
> In [2]: import gcsfs
> 
> In [3]: fs = gcsfs.GCSFileSystem(token='anon')
> 
> In [4]: f = fs.open('anaconda-public-data/nyc-taxi/nyc.parquet/part.0.parquet')
> 
> In [5]: table = pq.read_table(f)
> 
> In [6]: table.to_pandas().head(5)
> Out[6]: 
>   tpep_pickup_datetime  VendorID tpep_dropoff_datetime  passenger_count  \
> 0  2015-01-01 00:00:00         1   2015-01-01 00:11:26                5   
> 1  2015-01-01 00:00:00         2   2015-01-01 00:00:00                1   
> 2  2015-01-01 00:00:00         2   2015-01-01 00:00:00                3   
> 3  2015-01-01 00:00:01         1   2015-01-01 00:03:49                1   
> 4  2015-01-01 00:00:03         2   2015-01-01 00:21:48                2   
> 
>    trip_distance  pickup_longitude  pickup_latitude  RateCodeID  \
> 0           4.00        -73.971436        40.760201           1   
> 1           1.68        -73.991547        40.750069           1   
> 2           1.56        -74.001320        40.729057           1   
> 3           0.80        -73.860847        40.757294           1   
> 4           2.57        -73.969017        40.754269           1   
> 
>   store_and_fwd_flag  dropoff_longitude  dropoff_latitude  payment_type  \
> 0                  N         -73.921181         40.768269             2   
> 1                  N           0.000000          0.000000             2   
> 2                  N         -74.010208         40.719662             1   
> 3                  N         -73.868111         40.752285             2   
> 4                  N         -73.994133         40.761600             2   
> 
>    fare_amount  extra  mta_tax  tip_amount  tolls_amount  \
> 0         13.5    0.5      0.5         0.0           0.0   
> 1         10.0    0.0      0.5         0.0           0.0   
> 2          7.5    0.5      0.5         0.0           0.0   
> 3          5.0    0.5      0.5         0.0           0.0   
> 4         14.5    0.5      0.5         0.0           0.0   
> 
>    improvement_surcharge  total_amount  
> 0                    0.0          14.5  
> 1                    0.3          10.8  
> 2                    0.3           8.8  
> 3                    0.0           6.3  
> 4                    0.3          15.8  
> ```
> 
> Are there specific APIs that we need that don't work?

i tried it but getting error ''No module named 'gcsfs'''

**Comment by mrocklin** [comment] 2019-08-28 14:17
Maybe we should use the dask.utils.import_required function here

**Comment by krishanam** [comment] 2019-08-28 18:35
> > i am using Binder(Online)
> 
> You need to `pip install gcsfs`
> 
> > applied for internship in Big data have to Load parquet format nyc taxi data
> 
> Good luck!

can you tell me how can i load the data in parquet format , i tried many too many times none of them working. i have NYC taxi data(gcs://anaconda-public-data/nyc-taxi/nyc.parquet/part.0.parquet) . i have to upload it on Binder online(jupyter). i sincerely appreciate  your Help

**Comment by krishanam** [comment] 2019-08-28 18:43
import pyarrow.parquet as pq
import gcsfs
fs = gcsfs.GCSFileSystem(token='anon')
f = fs.open('anaconda-public-data/nyc-taxi/nyc.parquet/part.0.parquet')
table = pq.read_table(1)
table.to_pandas().head(2)

Error 
TypeError                                 Traceback (most recent call last)
<ipython-input-3-93e9d19b91c5> in <module>
      3 fs = gcsfs.GCSFileSystem(token='anon')
      4 f = fs.open('anaconda-public-data/nyc-taxi/nyc.parquet/part.0.parquet')
----> 5 table = pq.read_table(1)
      6 table.to_pandas().head(2)

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/parquet.py in read_table(source, columns, use_threads, metadata, use_pandas_metadata, memory_map, filesystem, filters)
   1212                             filesystem=filesystem, filters=filters)
   1213     else:
-> 1214         pf = ParquetFile(source, metadata=metadata, memory_map=memory_map)
   1215     return pf.read(columns=columns, use_threads=use_threads,
   1216                    use_pandas_metadata=use_pandas_metadata)

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/parquet.py in __init__(self, source, metadata, common_metadata, memory_map)
    130                  memory_map=True):
    131         self.reader = ParquetReader()
--> 132         self.reader.open(source, use_memory_map=memory_map, metadata=metadata)
    133         self.common_metadata = common_metadata
    134         self._nested_paths_by_prefix = self._build_nested_paths()

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/_parquet.pyx in pyarrow._parquet.ParquetReader.open()

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/io.pxi in pyarrow.lib.get_reader()

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/io.pxi in pyarrow.lib._get_native_file()

TypeError: Cannot convert int to pyarrow.lib.NativeFile

> > i am using Binder(Online)
> 
> You need to `pip install gcsfs`
> 
> > applied for internship in Big data have to Load parquet format nyc taxi data
> 
> Good luck!

My code 
import pyarrow.parquet as pq
import gcsfs
fs = gcsfs.GCSFileSystem(token='anon')
f = fs.open('anaconda-public-data/nyc-taxi/nyc.parquet/part.0.parquet')
table = pq.read_table(1)
table.to_pandas().head(2)



TypeError                                 Traceback (most recent call last)
<ipython-input-3-93e9d19b91c5> in <module>
      3 fs = gcsfs.GCSFileSystem(token='anon')
      4 f = fs.open('anaconda-public-data/nyc-taxi/nyc.parquet/part.0.parquet')
----> 5 table = pq.read_table(1)
      6 table.to_pandas().head(2)

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/parquet.py in read_table(source, columns, use_threads, metadata, use_pandas_metadata, memory_map, filesystem, filters)
   1212                             filesystem=filesystem, filters=filters)
   1213     else:
-> 1214         pf = ParquetFile(source, metadata=metadata, memory_map=memory_map)
   1215     return pf.read(columns=columns, use_threads=use_threads,
   1216                    use_pandas_metadata=use_pandas_metadata)

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/parquet.py in __init__(self, source, metadata, common_metadata, memory_map)
    130                  memory_map=True):
    131         self.reader = ParquetReader()
--> 132         self.reader.open(source, use_memory_map=memory_map, metadata=metadata)
    133         self.common_metadata = common_metadata
    134         self._nested_paths_by_prefix = self._build_nested_paths()

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/_parquet.pyx in pyarrow._parquet.ParquetReader.open()

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/io.pxi in pyarrow.lib.get_reader()

/srv/conda/envs/notebook/lib/python3.7/site-packages/pyarrow/io.pxi in pyarrow.lib._get_native_file()

TypeError: Cannot convert int to pyarrow.lib.NativeFile

**Comment by krishanam** [comment] 2019-09-02 14:47
Sorry but again i am facing Error on binder while loading Parquet.


ArrowIOError: Unexpected end of stream: Page was smaller (5242764) than expected (6699768)

**Comment by mrocklin** [comment] 2019-09-02 15:14
I recommend providing a minimal reproducible example as a new issue.  

Please read through all of https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports
