### ISSUE TITLE
Out Of Memory Error with Dask arrays

### ISSUE THREAD

**Issue by faze-geek** [dask/dask#11492] opened 2024-11-05 08:44 UTC
**Describe the issue**:

Hi, my team uses **dask** to combine features (reindex and forward fill) with respect to unique timestamps and then run a linear regression. We load feature data through a config which has the hashes and as of now we are running a fit for 30 features with 30 dates. 

I am working on a server with 375 GB ram, but facing the Out of memory error which I wanted to discuss. I think my code breaks at the `to_dask_array` operation when all the data gets loaded into memory.
 
I will be highly obliged to you if you can help us out in tackling this issue, or any general comments on how I can prevent going out of memory.

**Minimal Complete Verifiable Example**:

```
def combine_feature_data(feature_hashes, objective_paths, dates, base_dir):
    combined_feature_dfs = []
    for feature_hash in feature_hashes:
        parquet_files = [os.path.join(base_dir, f"indicator_{feature_hash}_{date}/part.0.parquet") for date in dates]
        feature_df = read_parquet_files(parquet_files)
        combined_feature_dfs.append(feature_df)

    objective_dfs = [dd.read_parquet(path) for path in objective_paths]
    combined_feature_dfs.extend(objective_dfs)
    combined_features = dd.concat(combined_feature_dfs, axis=0, interleave_partitions=True)
    combined_features = forward_fill_combined_dataframe(combined_features)
    return combined_features

def forward_fill_combined_dataframe(combined_df):
    all_indices = sorted(set(combined_df.index))
    index_df = pd.DataFrame(all_indices, columns=['timestamp'])
    index_ddf = dd.from_pandas(index_df, npartitions=1).set_index('timestamp')
    reindexed_df = index_ddf.merge(combined_df, left_index=True, right_index=True, how='left').ffill().fillna(0)
    reindex_df = reindexed_df.drop_duplicates()
    return reindexed_df


X = combine_feature_data(feature_hashes, objective_paths, dates, base_dir)
X = X.to_dask_dataframe()
x = (X.iloc[:, :-1]).to_dask_array(lengths=True)
y = (X.iloc[:, -1]).to_dask_array(lengths=True)

model = LinearRegression()
model.fit(x, y)
```

**Comment by faze-geek** [comment] 2024-11-06 05:47
@phofl Would like to hear your comments on this. Thanks in advance.

**Comment by phofl** [comment] 2024-11-07 16:03
Hi,

I can't troubleshoot this from afar, the example is something I can't copy-paste because the data is coming from parquet. You'd either have to provide a more minimal example or run this on a platform where we have access to the metrics about the workload

**Comment by phofl** [comment] 2024-12-18 20:18
Closing this for now, please ping to reopen if you can provide a reproducer

**Closed by phofl** 2024-12-18 20:18 UTC
Labels: needs info
