### ISSUE TITLE
dask.dataframe.to_sql missing docstring

### ISSUE THREAD

**Issue by raybellwaves** [dask/dask#6291] opened 2020-06-05 18:29 UTC
https://docs.dask.org/en/latest/dataframe-create.html#api

![image](https://user-images.githubusercontent.com/17162724/83910672-f940c480-a738-11ea-8d1a-225541d13431.png)

**Comment by jsignell** [comment] 2020-06-05 20:49
Indeed! There are not actually missing docs in this case. The issue is that we build docs on the released version of dask, but we update them whenever someone pushes a .rst file to dask/docs/source. So if there are features for which docs have been added but that are not yet in the released version of dask (such as `to_sql` which was added 7 days ago in #6038), they'll show up as empty like that. I am going to close this since there is a pre-existing issue discussing this odd behavior #6266

**Closed by jsignell** 2020-06-05 20:49 UTC
