### ISSUE TITLE
_concat fail

### ISSUE THREAD

**Issue by verasativa** [dask/dask#7155] opened 2021-02-02 14:37 UTC
**What happened**:
value_counts fails on concatenation of partitions:
```
~/.local/lib/python3.8/site-packages/dask/dataframe/core.py in finalize(results)
    105 
    106 def finalize(results):
--> 107     return _concat(results)
    108 
    109 

~/.local/lib/python3.8/site-packages/dask/dataframe/core.py in _concat(args, ignore_index)
     96     # Ideally this would be handled locally for each operation, but in practice
     97     # this seems easier. TODO: don't do this.
---> 98     args2 = [i for i in args if len(i)]
     99     return (
    100         args[0]

~/.local/lib/python3.8/site-packages/dask/dataframe/core.py in <listcomp>(.0)
     96     # Ideally this would be handled locally for each operation, but in practice
     97     # this seems easier. TODO: don't do this.
---> 98     args2 = [i for i in args if len(i)]
     99     return (
    100         args[0]

/opt/conda/lib/python3.8/site-packages/pandas/core/series.py in __len__(self)
    550         Return the length of the Series.
    551         """
--> 552         return len(self._data)
    553 
    554     def view(self, dtype=None):

/opt/conda/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5268             or name in self._accessors
   5269         ):
-> 5270             return object.__getattribute__(self, name)
   5271         else:
   5272             if self._info_axis._can_hold_identifiers_and_holds_name(name):

AttributeError: 'Series' object has no attribute '_data'
```

**What you expected to happen**:
just get my value counts

**Minimal Complete Verifiable Example**:
not really, we have huge data set ~500 gigabytes, I was just trying a df.my_colun.value_counts.compute()

**Anything else we need to know?**:
I know is hard to diagnostic from that, but I'm stuck. Any ideas on how to debug it further will be pretty welcome. 

**Environment**:
I'm running the Docker Image: daskdev/dask:latest  (on notebook, scheduler and workers)

**Comment by jsignell** [comment] 2021-02-02 14:56
Yes this is extremely hard to diagnose without a minimal example. I tried to reproduce with `df = dask.datasets.timeseries()` and was not able to see the same behavior. I recommend inspecting your partitions to see what is going on in them. You can write a dummy function and use it in `map_partitions` to try to get a sense of what's going on, or you can iterate through `df.partitions`.

**Comment by ncclementi** [comment] 2021-08-11 20:23
@verasativa due to the lack of info I'm going to close this issue but if you still have this problem, and are able to provide a minimal reproducible example or some more information so we can help you, feel free to re-open it.

**Closed by ncclementi** 2021-08-11 20:23 UTC
Labels: dataframe, needs info
