### ISSUE TITLE
AttributeError: 'DaskS3FileSystem' object has no attribute 'passed_in_session'

### ISSUE THREAD

**Issue by wmlba** [dask/dask#4144] opened 2018-10-27 10:59 UTC
While loading  a dataframe from a csv file located in S3 bucket, I get the below error on the workers then all the workers get killed:

Client, Scheduler and workers are all the same version (latest). 

Logs from Worker:

value = future.result()
File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
yielded = self.gen.throw(*exc_info)
File "/opt/conda/lib/python3.6/site-packages/distributed/comm/tcp.py", line 203, in read
deserializers=deserializers)
File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
value = future.result()
File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
yielded = next(result)
File "/opt/conda/lib/python3.6/site-packages/distributed/comm/utils.py", line 79, in from_frames
res = _from_frames()
File "/opt/conda/lib/python3.6/site-packages/distributed/comm/utils.py", line 65, in _from_frames
deserializers=deserializers)
File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/core.py", line 131, in loads
value = _deserialize(head, fs, deserializers=deserializers)
File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 178, in deserialize
return loads(header, frames)
File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/serialize.py", line 57, in pickle_loads
return pickle.loads(b''.join(frames))
File "/opt/conda/lib/python3.6/site-packages/distributed/protocol/pickle.py", line 59, in loads
return pickle.loads(x)
File "/opt/conda/lib/python3.6/site-packages/s3fs/core.py", line 286, in __setstate__
self.s3 = self.connect()
File "/opt/conda/lib/python3.6/site-packages/s3fs/core.py", line 229, in connect
if not self.passed_in_session:
AttributeError: 'DaskS3FileSystem' object has no attribute 'passed_in_session'
distributed.worker - INFO - Connection to scheduler broken. Reconnecting...
distributed.worker - INFO - -------------------------------------------------
tornado.application - ERROR - Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f377cbd17b8>, <Future finished exception=AttributeError("'DaskS3FileSystem' object has no attribute 'passed_in_session'",)>)
Thank you for reporting an issue.

Regards

**Comment by martindurant** [comment] 2018-10-27 13:57
Could you specify how you created the future and the s3fs instance that you passed to it?

**Comment by willbadr** [comment] 2018-10-28 01:19
@martindurant I am reading directly from S3 then loading a CSV into a dataframe:

```
import s3fs
import dask.dataframe as dd
import boto3
import dask.distributed

df = dd.read_csv('s3://datasets-98HYG/train.csv',
                 parse_dates=['tpep_pickup_datetime', 'tpep_dropoff_datetime'],
                 storage_options={'anon': False})
df = client.persist(df)
#df.head()
grouped_df = df.groupby(df.col10).col17.mean().compute()
```

**Comment by martindurant** [comment] 2018-10-28 01:31
(^ you don't seem to have created a client here)

I'm afraid I am not seeing this with dask and s3fs both on master. This appears to be a serialisation issue, so you would do well to first ensure that dask and s3fs are all the same versions across your client, scheduler and workers (`client.get_versions(packages=['dask', 's3fs'])` with recent dask).

**Comment by willbadr** [comment] 2018-10-28 02:00
@martindurant Thanks for your reply. Apologies for not including the code that creates the client. I am creating a cluster in a different block that uses the same image which has the same version of all packages. (Except the client - s3fs==1.5 and on the cluster s3fs=1.6). I upgraded the s3fs package on the client and it seems like the issue is resolved.

I am wondering if S3FS package should be installed as part of dask package. that would be very useful.

Thanks for your help.

**Comment by martindurant** [comment] 2018-10-28 03:54
s3fs is useful for Dask, but there are many ways to use Dask that don't depend on it, so we would prefer not to have it as a hard dependency.
In any case, glad to see that your problem is solved. Closing.

**Closed by martindurant** 2018-10-28 03:54 UTC
