### ISSUE TITLE
IndexError: tuple index out of range.  Using the `merge_asof` 

### ISSUE THREAD

**Issue by JuanAntonio03** [dask/dask#6279] opened 2020-06-02 17:33 UTC
**What happened**:
`IndexError: tuple index out of range` trying to merge two dask.dataframes using the `merge_asof`. 
I was trying this:
```python
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster
import pandas as pd

cluster = LocalCluster(n_workers=2, threads_per_worker=1)
client = Client(cluster)

transactions = dd.from_pandas(data=pd.DataFrame([
                ['22gv2222', pd.Timestamp(2020,10,21), 100, '12234abdsds'],
                ['22gv2222', pd.Timestamp(2020,10,23), 200, '12234abdsds'],
                ['33333ku3', pd.Timestamp(2020,10,22), 1,   'aefwefwefsds'],
                ['444bv444', pd.Timestamp(2020,10,21), 99,  '1asdawd'],
               ],
                columns=['customerID', 'date', 'amount', 'code']
               ),
               npartitions=2
        ).set_index('date')

crm = dd.from_pandas(data=pd.DataFrame([
                ['22gv2222', pd.Timestamp(2020,6,11), 'A',  False],
                ['33333ku3', pd.Timestamp(2020,7,2), 'B',  True],
                ['444bv444', pd.Timestamp(2020,5,1), 'C',  False],
                ['444bv444', pd.Timestamp(2020,6,1), 'C',  True],
               ],
                columns=['customerID', 'date', 'type', 'decease']
               ),
               npartitions=2
        ).set_index('date')

dd.merge_asof(transactions, crm, 
              left_index=True, right_index=True,
              by=['customerID'], direction='backward').compute()
```
And gives this error:

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-233-34e994abee4e> in <module>
     31 dd.merge_asof(transactions, crm, 
     32               left_index=True, right_index=True,
---> 33               by=['customerID'], direction='backward').compute()

~/miniconda3/envs/.../lib/python3.7/site-packages/dask/dataframe/multi.py in merge_asof(left, right, on, left_on, right_on, left_index, right_index, by, left_by, right_by, suffixes, tolerance, allow_exact_matches, direction)
    865         raise ValueError("merge_asof input must be sorted!")
    866 
--> 867     result = merge_asof_indexed(left, right, **kwargs)
    868     if left_on or right_on:
    869         result = result.reset_index()

~/miniconda3/envs/.../lib/python3.7/site-packages/dask/dataframe/multi.py in merge_asof_indexed(left, right, **kwargs)
    771         dependencies.append(heads)
    772 
--> 773     for i, J in enumerate(pair_partitions(left.divisions, right.divisions)):
    774         frames = []
    775         for j, lower, upper in J:

~/miniconda3/envs/.../lib/python3.7/site-packages/dask/dataframe/multi.py in pair_partitions(L, R)
    672     n, m = len(L) - 1, len(R) - 1
    673     i, j = 0, -1
--> 674     while R[j + 1] <= L[i]:
    675         j += 1
    676     J = []

IndexError: tuple index out of range
```

But if I add this new record `['22gv2222', pd.Timestamp(2020,11,11), 'D',  True]` in the `crm` dataframe that is newer than all the transactions: 

```python
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster
import pandas as pd

cluster = LocalCluster(n_workers=2, threads_per_worker=1)
client = Client(cluster)

transactions = dd.from_pandas(data=pd.DataFrame([
                ['22gv2222', pd.Timestamp(2020,10,21), 100, '12234abdsds'],
                ['22gv2222', pd.Timestamp(2020,10,23), 200, '12234abdsds'],
                ['33333ku3', pd.Timestamp(2020,10,22), 1,   'aefwefwefsds'],
                ['444bv444', pd.Timestamp(2020,10,21), 99,  '1asdawd'],
               ],
                columns=['customerID', 'date', 'amount', 'code']
               ),
               npartitions=2
        ).set_index('date')

crm = dd.from_pandas(data=pd.DataFrame([
                ['22gv2222', pd.Timestamp(2020,11,11), 'D',  True],    # NEW RECORD
                ['22gv2222', pd.Timestamp(2020,6,11), 'A',  False],
                ['33333ku3', pd.Timestamp(2020,7,2), 'B',  True],
                ['444bv444', pd.Timestamp(2020,5,1), 'C',  False],
                ['444bv444', pd.Timestamp(2020,6,1), 'C',  True],
               ],
                columns=['customerID', 'date', 'type', 'decease']
               ),
               npartitions=2
        ).set_index('date')

dd.merge_asof(transactions, crm, 
              left_index=True, right_index=True,
              by=['customerID'], direction='backward').compute()
```
It works:

| | customerID | amount | code | type | decease | 
 -- | -- | -- | -- | -- | -- | 
**date** | | | | | | 
**2020-10-21** | 22gv2222 | 100 | 12234abdsds | A | False  | 
**2020-10-21** | 444bv444 | 99 | 1asdawd | C | True  | 
**2020-10-22** | 33333ku3 | 1 | aefwefwefsds | B | True  | 
**2020-10-23** | 22gv2222 | 200 | 12234abdsds | A | False | 

**What you expected to happen**:
I expect in the error case to obtain the same result as the example with the new record without errors.

**Environment**:

- Dask version: 2.16.0
- Python version: 3.7.7
- Operating System: Ubuntu 18.04.4 LTS
- Install method (conda, pip, source): Conda

**Comment by jsignell** [comment] 2020-06-02 19:40
I can't reproduce the error. I think this has been fixed in #6192. If you updated to dask 2.17.2 (available on conda-forge) you should no longer have this bug. 

I am closing this, but please reopen, if updating doesn't solve it.

**Closed by jsignell** 2020-06-02 19:40 UTC
