### ISSUE TITLE
CI failure: FutureWarning - test_dataframe_aggregations_multilevel

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#9598] opened 2022-10-25 20:57 UTC
Seeing the following failure [on CI]( https://github.com/dask/dask/actions/runs/3323678807/jobs/5494942864#step:7:23942 )

```python
FAILED dask/dataframe/tests/test_groupby.py::test_dataframe_aggregations_multilevel[corr-tasks-1-<lambda>3] - FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
```

**Comment by jrbourbeau** [comment] 2022-10-25 21:11
Thanks @jakirkham, closing as a duplicate of https://github.com/dask/dask/issues/8795

**Comment by jrbourbeau** [comment] 2022-10-25 21:11
Whoops -- Ian beat me to it. 

> I tried to reproduce it locally last week and have been thus far unsuccessful.

Yeah, if folks have bandwidth to look into this one, that would be very welcome

**Closed by jrbourbeau** 2022-10-25 21:11 UTC
Labels: tests

**Comment by jakirkham** [comment] 2022-10-25 22:25
Oh thought it might be different given the parameterization of this one
