### ISSUE TITLE
Using graphchain with Dask

### ISSUE THREAD

**Issue by CMCDragonkai** [dask/dask#4749] opened 2019-04-29 08:08 UTC
I'm trying to use graphchain (https://github.com/radix-ai/graphchain) with dask. It implements on-disk caching for Dask. However I've hit an error https://github.com/radix-ai/graphchain/issues/35. The main reason is that since Dask moved to using the HighLevelGraph, things like `copy` method no longer exists, and possibly other problems as well. Is it possible to add back copy operations to the HighLevelGraph, if not, how should the HighLevelGraph be copied?

**Comment by martindurant** [comment] 2019-04-29 13:25
Related: #4750

**Comment by jcrist** [comment] 2019-04-30 15:38
Closing as duplicate of #4750.

**Closed by jcrist** 2019-04-30 15:38 UTC
