### ISSUE TITLE
unexpected keyword argument 'file_scheme' in to_parquet

### ISSUE THREAD

**Issue by daniel-severo** [dask/dask#4510] opened 2019-02-19 18:50 UTC
Consider the following

```python3
import dask.dataframe as dd
import pandas as pd


df = pd.DataFrame({'a': range(3), 'b': range(3)})
ldf = dd.from_pandas(df, npartitions=1)

# both work fine and as expected
df.to_parquet('df-hive', engine='fastparquet', file_scheme='hive')
df.to_parquet('df-simple', engine='fastparquet', file_scheme='simple')

# TypeError: make_metadata() got an unexpected keyword argument 'file_scheme'
ldf.to_parquet('ldf-hive', engine='fastparquet', file_scheme='hive')
ldf.to_parquet('ldf-simple', engine='fastparquet', file_scheme='simple')
```

**Comment by avnovikov** [comment] 2019-03-04 17:42
Seems that I have the same problem.

**Comment by mrocklin** [comment] 2019-03-04 17:45
cc @martindurant

**Comment by martindurant** [comment] 2019-03-04 18:02
Dask cannot write to a single output parquet file, because the different workers are writing in parallel. The model, when writing from Dask, is that each partition of the dataframe is written to a separate file on disc, and then a single metadata file references all of the pieces to form a single dataset. This is the same model as used by other parallel engines writing to parquet, e.g., spark.

**Comment by avnovikov** [comment] 2019-03-04 18:47
Martin, thank you for the prompt answer; however, hive schema provides multiple partitions/files (if partitioned on index f.e.) with single metadata.

**Comment by martindurant** [comment] 2019-03-04 18:53
Yes, that is right - what are you wishing to see instead?

**Comment by avnovikov** [comment] 2019-03-04 19:00
Marin, sorry I'm afraid I don't fully understand your answer. In the best case scenario, I would like to be able to save a hive schema when saving via fastparquet, as it seems completely legitimate for parallelisation.

**Comment by martindurant** [comment] 2019-03-04 19:06
Yes, a hive scheme is exactly what you get
```
df = pd.DataFrame({'a': np.random.rand(100), 'b': np.random.choice(['first', 'second'], size=100)})
ddf = dd.from_pandas(df, 2)
ddf.to_parquet('/Users/mdurant/temp/out.parq', partition_on=['b'])
```
results in paths
```
/Users/mdurant/temp/out.parq
/Users/mdurant/temp/out.parq/_common_metadata
/Users/mdurant/temp/out.parq/b=first
/Users/mdurant/temp/out.parq/b=first/part.0.parquet
/Users/mdurant/temp/out.parq/b=first/part.1.parquet
/Users/mdurant/temp/out.parq/_metadata
/Users/mdurant/temp/out.parq/b=second
/Users/mdurant/temp/out.parq/b=second/part.0.parquet
/Users/mdurant/temp/out.parq/b=second/part.1.parquet
/Users/mdurant/temp/out.parq/part.0.parquet
```

**Comment by avnovikov** [comment] 2019-03-04 19:13
Ok so then it is an ambiguity in the documentation, as it is not obvious that hive schema is used by default when partitioning on the list and **kwargs are used only for specific arguments.
(Now "Extra options to be passed on to the specific backend.")

**Comment by martindurant** [comment] 2019-03-04 20:29
You are very welcome to propose changes to the to_parquet docstring as a PR; although you should be aware that the allowed kwargs and default behaviour is different for the two parquet engines. 
I will now close this as "works as intended", needing no code changes.

**Closed by martindurant** 2019-03-04 20:29 UTC
