### ISSUE TITLE
chisquare throwing TypeError: mean() got an unexpected keyword argument 'keepdims'

### ISSUE THREAD

**Issue by echo66** [dask/dask#4311] opened 2018-12-18 12:26 UTC
Greetings!

I'm trying to use `dask.array.stats.chisquare`. Here is the code I'm using:

```python
import dask
from dask.array.stats import chisquare
import numpy as np
import pandas as pd


np.random.seed(123)

example_df = pd.DataFrame({
    'f1': np.random.choice(['aa', 'bb', 'cc', 'dd'], size=100), 
    'f2': np.random.choice(['vv', 'xx', 'yy', 'zz'], size=100)
})

example_df_dask = dask.dataframe.from_pandas(example_df, npartitions=10)
example_df_dask['__dummy__'] = 1
example_df_dask = example_df_dask.categorize('f1').categorize('f2')
p = example_df_dask.pivot_table(index='f1', columns='f2', values='__dummy__', aggfunc='sum')
chisquare(p)
```

This is getting me the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-86-ee51d83fd939> in <module>
     10 example_df_dask = example_df_dask.categorize('f1').categorize('f2')
     11 p = example_df_dask.pivot_table(index='f1', columns='f2', values='__dummy__', aggfunc='sum')
---> 12 chisquare(p)

~/.local/share/virtualenvs/big-data-project-VHY2V5jl/lib/python3.6/site-packages/dask/array/stats.py in chisquare(f_obs, f_exp, ddof, axis)
    118 def chisquare(f_obs, f_exp=None, ddof=0, axis=0):
    119     return power_divergence(f_obs, f_exp=f_exp, ddof=ddof, axis=axis,
--> 120                             lambda_="pearson")
    121 
    122 

~/.local/share/virtualenvs/big-data-project-VHY2V5jl/lib/python3.6/site-packages/dask/array/stats.py in power_divergence(f_obs, f_exp, ddof, axis, lambda_)
    138         pass
    139     else:
--> 140         f_exp = f_obs.mean(axis=axis, keepdims=True)
    141 
    142     # `terms` is the array of terms that are summed along `axis` to create

TypeError: mean() got an unexpected keyword argument 'keepdims'
```

When I look into `p.mean`, there is no parameter named `keepdims`. 

Numpy version: 1.15.4
Pandas version: 0.23.4
Dask version: 1.0.0

**Comment by TomAugspurger** [comment] 2018-12-18 21:52
I can reproduce your error without dask.

```python
In [19]: df = example_df.astype('category').assign(__dummy__=1)

In [20]: p = df.pivot_table(index='f1', columns='f2', values='__dummy__', aggfunc='sum')
    ...: chisquare(p)
    ...:
    ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-c74c30443e53> in <module>
      1 p = df.pivot_table(index='f1', columns='f2', values='__dummy__', aggfunc='sum')
----> 2 chisquare(p)
      3

~/sandbox/dask/dask/array/stats.py in chisquare(f_obs, f_exp, ddof, axis)
    118 def chisquare(f_obs, f_exp=None, ddof=0, axis=0):
    119     return power_divergence(f_obs, f_exp=f_exp, ddof=ddof, axis=axis,
--> 120                             lambda_="pearson")
    121
    122

~/sandbox/dask/dask/array/stats.py in power_divergence(f_obs, f_exp, ddof, axis, lambda_)
    138         pass
    139     else:
--> 140         f_exp = f_obs.mean(axis=axis, keepdims=True)
    141
    142     # `terms` is the array of terms that are summed along `axis` to create

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/core/generic.py in stat_func(self, axis, skipna, level, numeric_only, **kwargs)
   9602     def stat_func(self, axis=None, skipna=None, level=None, numeric_only=None,
   9603                   **kwargs):
-> 9604         nv.validate_stat_func(tuple(), kwargs, fname=name)
   9605         if skipna is None:
   9606             skipna = True

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/compat/numpy/function.py in __call__(self, args, kwargs, fname, max_fname_arg_count, method)
     48                 validate_args(fname, args, max_fname_arg_count, self.defaults)
     49             elif method == 'kwargs':
---> 50                 validate_kwargs(fname, kwargs, self.defaults)
     51             elif method == 'both':
     52                 validate_args_and_kwargs(fname, args, kwargs,

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/util/_validators.py in validate_kwargs(fname, kwargs, compat_args)
    154     """
    155     kwds = kwargs.copy()
--> 156     _check_for_invalid_keys(fname, kwargs, compat_args)
    157     _check_for_default_values(fname, kwds, compat_args)
    158

~/Envs/dask-dev/lib/python3.7/site-packages/pandas/util/_validators.py in _check_for_invalid_keys(fname, kwargs, compat_args)
    125         raise TypeError(("{fname}() got an unexpected "
    126                          "keyword argument '{arg}'".
--> 127                          format(fname=fname, arg=bad_arg)))
    128
    129

TypeError: mean() got an unexpected keyword argument 'keepdims'
```

Pandas does some validation on parameters passed to methods like `mean` that it doesn't support. I don't think it's been updated for `keepdims`. I need to fix this anyway for another issue.

**Comment by jsignell** [comment] 2021-05-26 20:53
Closing since it seems like this is expected behavior.

**Closed by jsignell** 2021-05-26 20:53 UTC
