### ISSUE TITLE
dask-scheduler command error

### ISSUE THREAD

**Issue by liuwei0773** [dask/dask#7695] opened 2021-05-24 07:26 UTC
my environment is ubuntu18.04 & dask 2021.3.0, and follow is the traceback:

Traceback (most recent call last):
  File "/home/l/venv/bin/dask-scheduler", line 5, in <module>
    from distributed.cli.dask_scheduler import go
  File "/home/l/venv/lib/python3.6/site-packages/distributed/cli/dask_scheduler.py", line 122, in <module>
    @click.version_option()
  File "/home/l/venv/lib/python3.6/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/home/l/venv/lib/python3.6/site-packages/click/core.py", line 2482, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/home/l/venv/lib/python3.6/site-packages/click/core.py", line 2110, in __init__
    ) from None
ValueError: 'default' must be a list when 'multiple' is true.

**Comment by jrbourbeau** [comment] 2021-05-24 15:27
Thanks for raising an issue @liuwei0773. The latest release of `dask` and `distributed` (version `2021.05.0`) contains compatibility updates for `click >= 8`. We recommend either updating your versions of `dask` and `distributed` or pinning `click < 8`.

Closing as a duplicate of https://github.com/dask/distributed/issues/4817

**Closed by jrbourbeau** 2021-05-24 15:27 UTC
