### ISSUE TITLE
Pandas dataframe not created in Jupyter Notebook after compute()

### ISSUE THREAD

**Issue by lucazav** [dask/dask#7603] opened 2021-04-26 11:04 UTC
I downloaded and unzipped the `AirOnTimeCSV.zip` file from [this link](https://packages.revolutionanalytics.com/datasets/AirOnTime87to12/) in order to test Dask over 30 GB of CSV files.
I'm running the following code on Python 3.9.1 (through VS Code):

```
import pandas as pd
import dask.dataframe as dd
from dask.diagnostics import ProgressBar

main_path = os.path.join('D:\\', 'data', 'AirOnTime', 'AirOnTimeCSV')

ddf = dd.read_csv(
    os.path.join(main_path, 'airOT*.csv'),                 
    encoding='latin-1',
    dtype={'CRS_ELAPSED_TIME': 'float64',
           'CRS_ARR_TIME' : 'float64',
           'CRS_DEP_TIME' : 'float64',
           'CANCELLED': bool},
    usecols =['YEAR', 'MONTH', 'DAY_OF_MONTH', 'ORIGIN', 'DEP_DELAY']
)

ddf.head()

mean_dep_delay_ddf = ddf.groupby(['YEAR', 'MONTH', 'DAY_OF_MONTH'])['DEP_DELAY'].mean()

with ProgressBar():
    mean_dep_delay_df = mean_dep_delay_ddf.compute()
```

The progress bar reaches the 100%, but I can't see the `mean_dep_delay_df` Pandas variable into the the VS Code Variables Explorer.
Infact, if I run the following code:

`mean_dep_delay_df.head(10)`

I get the result after few minutes, so I assume `mean_dep_delay_df` is still a Dask dataframe. Am I doing something wrong in the code? I would have expected `mean_dep_delay_df` to be a Pandas dataframe.

Thanks

**Comment by jsignell** [comment] 2021-04-26 14:29
Can you check the type of `mean_dep_delay_df`? I would expect:

```python
type(mean_dep_delay_df)
# pandas.core.series.Series
```

You should also make sure that the dask version you are using is compatible with python 3.9. It'd be helpful to know what dask version you have and how you installed it.

**Comment by lucazav** [comment] 2021-04-26 17:05
I confirm the type is `pandas.core.series.Series`. The problem is that, when I run `mean_dep_delay_df.head(10)`, the result isn't shown in a fast way and all my CPU go up near 100%:

![image](https://user-images.githubusercontent.com/6104437/116121650-1ff54a00-a6c1-11eb-9546-01fa9670f6b5.png)

Moreover the `head()` output seems not the one of standard pandas dataframes in Jupyter Notebooks (take a look at the following picture).
The other strange thing is that the kernel remains in the "busy" state even after the progress bar has reached 100% and all the defined variables disappear from the Variable Explorer:

![image](https://user-images.githubusercontent.com/6104437/116122320-e6710e80-a6c1-11eb-812d-854a50a5a3ba.png)

I used `pip install "dask[complete]"` to install Dask and the installed version is `2021.4.1`.

**Comment by jrbourbeau** [comment] 2021-04-26 17:13
Note that `.head()` will trigger a compute by default (this is one of the rare places throughout Dask where this happens)

https://github.com/dask/dask/blob/2666809c913fdb215fa928abfcea0f87a028929f/dask/dataframe/core.py#L1047-L1048

There's a `compute=` keyword you can set to `False` if you would instead like to return a lazy Dask DataFrame

**Comment by rjzamora** [comment] 2021-04-26 17:17
>Note that .head() will trigger a compute by default

I don't think `mean_dep_delay_df.head()` should compute anything if `mean_dep_delay_df` is already a pandas object created with  `mean_dep_delay_df = mean_dep_delay_ddf.compute()`

**Comment by jsignell** [comment] 2021-04-26 17:34
Right, I am wondering if it is possible that this is a vscode thing? @lucazav do you see the same behavior in regular Jupyter?

**Comment by jsignell** [comment] 2021-04-26 17:39
It'd also be helpful if you are able to reproduce on a smaller dataset.

**Comment by jrbourbeau** [comment] 2021-04-26 17:43
Ah, yep thanks. I didn't read the the example snippet close enough

**Comment by lucazav** [comment] 2021-04-26 17:58
This is a repro using only the first file you can find in the `AirOnTimeCSV.zip` file [here](https://packages.revolutionanalytics.com/datasets/AirOnTime87to12/):

```# %%
import os
import pandas as pd
import dask.dataframe as dd
from dask.diagnostics import ProgressBar

# %%
main_path = os.path.join('D:\\', 'data', 'AirOnTime', 'AirOnTimeCSV')

# %%
ddf = dd.read_csv(
    os.path.join(main_path, 'airOT198710.csv'),                 
    encoding='latin-1',
    usecols =['YEAR', 'MONTH', 'DAY_OF_MONTH', 'ORIGIN', 'DEP_DELAY']
)

# %%
mean_dep_delay_ddf = ddf.groupby(['YEAR', 'MONTH', 'DAY_OF_MONTH'])['DEP_DELAY'].mean()

# %%
with ProgressBar():
    mean_dep_delay_df = mean_dep_delay_ddf.compute()

# %%
type(mean_dep_delay_df)

# %%
%whos DataFrame

# %%
mean_dep_delay_df.head(10)

# %%
test_df = pd.read_csv(os.path.join(main_path, 'airOT198710.csv'), nrows = 10)

# %%
test_df.head(10)

# %%
%whos DataFrame
```

Here what I get as output:

![image](https://user-images.githubusercontent.com/6104437/116128745-8e3e0a80-a6c9-11eb-8a2d-0f5cda69de45.png)

**Comment by lucazav** [comment] 2021-04-26 18:08
I also tested the same repro code (removing the `%whos DataFrame` code) on Python 3.8.8 into the console. Here the output:

![image](https://user-images.githubusercontent.com/6104437/116130010-0527d300-a6cb-11eb-8719-db1c3cf600ce.png)

As you can see, `mean_dep_delay_df` is not visualized as the `test_df` Pandas dataframe.

**Comment by jsignell** [comment] 2021-04-26 19:11
This just looks like the difference between a pandas DataFrame and a Series. 

If you do:

```python
mean_dep_delay_ddf = ddf.groupby(['YEAR', 'MONTH', 'DAY_OF_MONTH'])[['DEP_DELAY']].mean()
```

does that give your expected result?

**Comment by lucazav** [comment] 2021-04-26 20:26
You're right, @jsignell , it was my fault on that.
I've also verified that the issue of the "frozen" kernel when loading all the CSV files is due to the false output of the progress bar. Once the bar reaches 100%, you need to wait several more minutes for the kernel to return to idle state. Maybe the progress bar has to be fixed in this case.

Thank you for your support!

**Comment by jsignell** [comment] 2021-04-26 20:29
Great! I am going to go ahead and close this issue, but please don't hesitate to come back when/if you run into something else :)

**Closed by jsignell** 2021-04-26 20:29 UTC
Labels: dataframe, needs info
