### ISSUE TITLE
BUG: Dask dataframe cannot handle string index

### ISSUE THREAD

**Issue by ArcticLampyrid** [dask/dask#3269] opened 2018-03-10 14:29 UTC
I write the following code,but it doesn't work.
```python
import dask.bag as db
import dask.dataframe as dd
import dask.array as da
import pandas as pd
if __name__ == '__main__':
	#Just for test
	pWord = dd.from_pandas(pd.DataFrame({'word':["a","b","c","bc","abc"],'probability':[0.1,0.2,0.3,0.4,0.5]}),npartitions=3)
	wordInfoTable = dd.from_pandas(pd.DataFrame({'word':["bc","abc"]}),npartitions=3)
	pWord = pWord.set_index(pWord.word)
	pIfRandom = pWord.loc[wordInfoTable.word.str.slice(stop=1)].probability.reset_index(drop=True) * pWord.loc[wordInfoTable.word.str.slice(start=1)].probability.reset_index(drop=True)
	wordInfoTable["adhesiveness"] = pWord.loc[wordInfoTable.word].probability.reset_index(drop=True) / pIfRandom
	print(wordInfoTable.compute())
```

The following code works well, but very slow
```python
import dask.bag as db
import dask.dataframe as dd
import dask.array as da
import pandas as pd
if __name__ == '__main__':
	#Just for test
	pWord = dd.from_pandas(pd.DataFrame({'word':["a","b","c","bc","abc"],'probability':[0.1,0.2,0.3,0.4,0.5]}),npartitions=3)
	wordInfoTable = dd.from_pandas(pd.DataFrame({'word':["bc","abc"]}),npartitions=3)
	pWord = pWord.set_index(pWord.word)
	def getP(t):
		return next(pWord.loc[t].itertuples()).probability
	def applyAdhesiveness(row):
		word = row["word"]
		pIfRandom = getP(word[0]) * getP(word[1:])
		adhesiveness = getP(word) / pIfRandom
		row["adhesiveness"] = adhesiveness
		return row
	wordInfoTable["adhesiveness"] = None
	wordInfoTable = wordInfoTable.apply(applyAdhesiveness,axis=1,meta=wordInfoTable._meta)
	print(wordInfoTable.compute())
```

I know it may be not a suitable place to ask for help here, but I think it's the only place which I can get the answer.

**Comment by mrocklin** [comment] 2018-03-10 19:49
For faster feedback, I recommend constructing a minimal example.  

-  https://stackoverflow.com/help/mcve
-  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by 1354092549** [comment] 2018-03-11 01:10
When I try to use `pWord.loc[wordInfoTable.word.str.slice(stop=1)]`
The code doesn't work.

**Comment by gabrielelanaro** [comment] 2018-03-11 01:20
```pWord``` is indexed over ```word``` column. While ```wordInfoTable``` is indexed over some random integer index

**Comment by 1354092549** [comment] 2018-03-11 01:24
It seems I should use `pWord[pWord.word.isin(wordInfoTable.word.str.slice(stop=1))].probability`
but it doesn't work with dask too 
```python
import dask.bag as db
import dask.dataframe as dd
import dask.array as da
import pandas as pd
if __name__ == '__main__':
	#Just for test
	pWord = dd.from_pandas(pd.DataFrame({'word':["a","b","c","bc","abc"],'probability':[0.1,0.2,0.3,0.4,0.5]}),npartitions=3)
	wordInfoTable = dd.from_pandas(pd.DataFrame({'word':["bc","abc"]}),npartitions=3)
	pWord = pWord.set_index(pWord.word)
	print(pWord[pWord.word.isin(wordInfoTable.word.str.slice(stop=1))].probability)
```

It can work with pandas:
```python
import dask.bag as db
import dask.dataframe as dd
import dask.array as da
import pandas as pd
if __name__ == '__main__':
	wordInfoTable = pd.DataFrame({'word':["bc","abc"]})
	pWord=pd.DataFrame({'word':["a","b","c","bc","abc"],'probability':[0.1,0.2,0.3,0.4,0.5]})
	pWord = pWord.set_index(pWord.word)
	print(pWord[pWord.word.isin(wordInfoTable.word.str.slice(stop=1))].probability)
```

**Comment by gabrielelanaro** [comment] 2018-03-11 01:39
I think the problem is related to strings, I believe it's a bug in dask handling of string indices

```
import dask.dataframe as dd
import pandas as pd

a = dd.from_pandas(pd.DataFrame({'x':[0.1,0.2,0.3,0.4,0.5]}, index=["a","b","c","bc","abc"]), npartitions=3)
b = dd.from_pandas(pd.DataFrame({'word':["bc","abc"]}), npartitions=3)
a.loc[b.word]

TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by 1354092549** [comment] 2018-03-11 01:55
@gabrielelanaro 
When both `a` and `b` are the type of pandas
```python
import pandas as pd

a = pd.DataFrame({'x':[0.1,0.2,0.3,0.4,0.5]}, index=["a","b","c","bc","abc"])
b = pd.DataFrame({'word':["bc","abc"]})
print(a.loc[b.word])
```
It can work well

**Comment by mrocklin** [comment] 2018-03-11 12:46
Thanks for the minimal example in https://github.com/dask/dask/issues/3269#issuecomment-372082058 @gabrielelanaro !

I agree that this looks like a bug in dask dataframe.  When we call loc on a dask.dataframe.Series we are currently trying to align the two dataframe/series objects by divisions, which is where the exception is occurring.  Instead we actually need to do a more complex operation where every partition of the indexer talks to every partition of the indexed.  

This should be fixed if anyone has interest. 

It's worth pointing out though that this will never be nearly as fast as in the Pandas case.

**Comment by gabrielelanaro** [comment] 2018-03-11 21:46
I've been experimenting with this issue on my local copy. I would say the main issue is that ```DataFrame.map_partitions``` does not actually just map a functions to all partitions in the dataframe, but it also performs some alignment under the hood. That's because it dispatches to ```core.map_partitions```, which has a different semantics, because it perform alignment automatically (a more specific name would be ```align_map_partitions```) 

I feel the best way to do this is to actually implement a different version of 
```map_partitions``` that perform no alignment (or maybe use a keyword argument ```align_partitions```), so that we can dispatch the correct behavior.

In this case, if the Series is of type bool, you need to align partitions, otherwise, you need to broadcast the dataframe.

**Comment by OliverHofkens** [comment] 2020-01-15 09:13
Sorry for the necro, just wanted to put my 2 cents in.
I ran into this problem when I wanted to select the groupwise minima over a certain column like this:
```
indexes = df.groupby("grp")["val"].idxmin()
df.loc[indexes]
```

I implemented the suggested fix of having a `broadcast_map_partitions()` function which maps the given function over all combinations of partitions. I implemented this naively by copying `map_partitions`,  removing the alignment that happens, and changing `partitionwise_graph` to create a partition-to-partition graph. This worked great, but memory usage was insane. My adaptive cluster peaked at 11 terabyte of memory usage on a calculation that previously spiked at ~100 gigs. I guess each partition is copied to the worker where each other partition lives? Might be an oversight in my implementation too, but at least it worked.

Anyway, I found that just relying on Dask's divisions and alignment works way better.
```
def _loc(_part, _selector_part):
    try:
        return _part.loc[_part.index.intersection(_selector_part)]
    except KeyError:
         return []

indexes = df.groupby("grp")["val"].idxmin()
indexes_partitioned = indexes.to_frame().set_index("val", drop=False)["val"]
df.map_partitions(_loc, indexes_partitioned)
```
On my big dataset, this takes the same time but uses ~100x less memory. And in my specific case, I could even cut out the extra steps by combining `idxmin` and `loc` in a single pass using `groupby()._aca_agg()` directly.

**Comment by GenevieveBuckley** [comment] 2021-10-12 04:19
@dask/maintenance can someone edit the title of this issue to better reflect the contents? I'd suggest something like *"BUG: Dask dataframe cannot handle string index"*

A minimal, reproducible example for this issue is given here: https://github.com/dask/dask/issues/3269#issuecomment-372082058

**Closed** 2021-11-04 20:12 UTC
Labels: dataframe
