### ISSUE TITLE
dask dashboard missing one worker bar on task stream

### ISSUE THREAD

**Issue by simonm3** [dask/dask#8970] opened 2022-04-22 15:16 UTC
The dashboard shows 8 bars on the two charts on the left. However there are only 7 bars on the task stream.

![image](https://user-images.githubusercontent.com/1199593/164743782-a9c91f62-7ddc-4698-a8f8-a919dbf7df58.png)

**Comment by bryanwweber** [comment] 2022-04-22 15:24
Thanks for reporting this issue and welcome to Dask! Can you please add a [minimal, complete, verifiable example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) code to your post? That really helps us reproduce the issue to work out what to do. Thank you!

**Comment by mrocklin** [comment] 2022-04-22 18:16
This isn't a bug.  The task stream has one horizontal bar for every thread
that has run so far.  It can have more bars (if there are more threads than
workers) or fewer bars (if fewer threads have been active so far than there
are workers).  I suspect that if you run a bigger computation that you will
see more threads active

**Comment by simonm3** [comment] 2022-04-24 18:14
Thanks. I have 15 sets of 4 sequential tasks so expected up to 15 parallel tasks restricted to n_workers=8. I  have 8 vCPUs. Yet it does not go above 7 bars.

**Comment by pavithraes** [comment] 2022-04-28 11:11
@simonm3 Thanks for opening this issue!

> I have 15 sets of 4 sequential tasks so expected up to 15 parallel tasks restricted to n_workers=8. I have 8 vCPUs. Yet it does not go above 7 bars.

The bars (or, threads used) would depend on many things, including how many total threads your setup has and what your task graph looks like. As `@bryanwweber` mentioned, if you can share a minimal example, it'll allow us to better explain what's going on. :)

Also, this seems like more of a usage question than a bug report or feature request. We encourage people with such questions to ask them at the [Dask Discourse](https://dask.discourse.group/). Would you mind opening a discussion topic about this over there? If you do so, feel free to close this issue and we will continue the conversation on discourse.

**Closed** 2022-04-28 11:35 UTC
Labels: needs info
