### ISSUE TITLE
ProgressBar: cannot join thread before it is started

### ISSUE THREAD

**Issue by ndawe** [dask/dask#1424] opened 2016-07-29 04:34 UTC
If minimum > 0 then it appears there is some race condition causing the following problem:

```
Traceback
---------
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/dask/async.py", line 267, in execute_task
    result = _execute_task(task, data)
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/dask/async.py", line 248, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/dask/async.py", line 245, in _execute_task
    return [_execute_task(a, cache) for a in arg]
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/dask/async.py", line 249, in _execute_task
    return func(*args2)
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/dask/array/core.py", line 51, in getarray
    c = np.asarray(c)
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/numpy/core/numeric.py", line 482, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/dask/array/core.py", line 892, in __array__
    x = self.compute()
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/dask/base.py", line 86, in compute
    return compute(self, **kwargs)[0]
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/dask/base.py", line 179, in compute
    results = get(dsk, keys, **kwargs)
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/dask/threaded.py", line 57, in get
    **kwargs)
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/dask/async.py", line 497, in get_async
    f(dsk, state, False)
  File "/imports/rcs5_data/edawe/public/env/lib/python2.7/site-packages/dask/diagnostics/progress.py", line 97, in _finish
    self._timer.join()
  File "/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/python/2.7.4-x86_64-slc6-gcc48/sw/lcg/external/Python/2.7.4/x86_64-slc6-gcc48-opt/lib/python2.7/threading.py", line 938, in join
    raise RuntimeError("cannot join thread before it is started")
```

**Comment by ndawe** [comment] 2016-07-29 04:40
Actually, this runtime error occurs regardless. I'm registering a global progressbar:

```
from dask.diagnostics import ProgressBar                                        
pbar = ProgressBar()                                                            
pbar.register()
```

**Comment by jcrist** [comment] 2016-07-29 15:46
I'm unable to reproduce:

```python
In [1]: import dask.array as da

In [2]: a = da.random.normal(size=(10000, 1000), chunks=1000)

In [3]: x = a.dot(a.T).sum(axis=1).mean()

In [4]: from dask.diagnostics import ProgressBar

In [5]: pbar = ProgressBar()

In [6]: pbar.register()

In [7]: x.compute()
[########################################] | 100% Completed |  1.5s
Out[7]: 999.8781772877395
```

Do you have a reproducible example for this? Are you using the latest version of dask? What OS?

**Comment by ndawe** [comment] 2016-08-01 03:46
Yes, latest: 0.10.2. OS is EL6 (Red Hat Enterprise Linux). I'll check if I hit the same glitch on a small example I can post here.

**Comment by ndawe** [comment] 2016-08-01 07:52
Unable to reproduce with your test or a variant with many repetitions of smaller computations. Will try something similar to the mix present in my code.

**Comment by jcrist** [comment] 2016-08-29 15:48
@ndawe, were you ever able to reproduce this in a contained example?

**Comment by ndawe** [comment] 2016-08-31 03:15
I'm unable to reproduce in a contained example, unfortunately. Feel free to close this issue for now and I'll let you know if I hit it again in the future.

**Comment by jcrist** [comment] 2016-08-31 04:52
Ok, thanks for the update. Sorry we couldn't help you figure out the issue, feel free to reopen if it happens again. Closing.

**Closed by jcrist** 2016-08-31 04:52 UTC
Labels: scheduler
