### ISSUE TITLE
How do we use HTTPS by default on dask documentation

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#4270] opened 2018-12-05 18:20 UTC
When I type docs.dask.org into my browser it directs me to http:// ... rather than https://... 

Pardon my ignorance, but is there an easy way to resolve this?

**Comment by TomAugspurger** [comment] 2018-12-06 14:18
I think https://support.cloudflare.com/hc/en-us/articles/200170536-How-do-I-redirect-all-visitors-to-HTTPS-SSL- is the relevant doc.

cc @aterrel

**Comment by mrocklin** [comment] 2019-04-10 03:06
Cross referencing https://github.com/dask/dask.github.io/pull/2

**Comment by aterrel** [comment] 2019-04-10 13:08
I just threw the "Always Use HTTPS" setting on. Let me know if there are any issues that come up.

**Comment by aterrel** [comment] 2019-04-10 13:17
I've also set a page redirect rule for docs.dask.org. will wait to see if that fixes the issue.

**Comment by mrocklin** [comment] 2019-04-10 13:26
So far things are working for dask.org (thanks a ton!) and not yet for
docs.dask.org (I'll wait a bit though and report back)

**Comment by mrocklin** [comment] 2019-04-10 14:41
docs.dask.org is still insecure.  

I also tried the Always Use HTTPS setting from within RTD, which hasn't been successful (it has actually be checked for a while now)

I did happen upon these docs from RTD though: https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-ssl

There are a couple notes there that I don't understand fully, but may be relevant.

**Comment by aterrel** [comment] 2019-04-18 01:13
wll poo.

Can you add me as an admin for RTD then I can play with the setting and contact their support?

**Comment by mrocklin** [comment] 2019-04-18 01:26
Sure.  What is your RTD username?

**Comment by aterrel** [comment] 2019-04-18 03:34
aterrel

**Comment by mrocklin** [comment] 2019-04-18 13:12
- User aterrel does not exist

**Comment by aterrel** [comment] 2019-04-18 13:36
meh, RTD user stuff confuses me... Let me delete the account and see if I can make another that isn't just authenticated from github.

<img width="463" alt="Screen Shot 2019-04-18 at 8 34 19 AM" src="https://user-images.githubusercontent.com/30583/56364711-dbbb3f00-61b4-11e9-9055-cd03bb80c257.png">

**Comment by mrocklin** [comment] 2019-04-18 13:41
Hrm, still no luck.  I'll give it a few minutes and then try again.

**Comment by mrocklin** [comment] 2019-04-18 13:42
Alternatively, if you're around downtown Austin today or tomorrow I'd be
happy to meet up (regardless) and see if we can bang this out.

**Comment by aterrel** [comment] 2019-04-19 12:40
For those following along. We met in meatspace. Played with settings for an hour. Then enjoyed beer.

The internet seems to think that our current set up won't work... https://github.com/rtfd/readthedocs.org/issues/4907#issuecomment-439447749

But pypa works.... try http://pip.pypa.io/en/stable/ ... but look... they use fastly to cache.

```
$ dig pip.pypa.io

; <<>> DiG 9.10.6 <<>> pip.pypa.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 27636
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;pip.pypa.io.                   IN      A

;; ANSWER SECTION:
pip.pypa.io.            1799    IN      CNAME   dualstack.c.ssl.global.fastly.net.
dualstack.c.ssl.global.fastly.net. 29 IN A      151.101.0.175
dualstack.c.ssl.global.fastly.net. 29 IN A      151.101.64.175
dualstack.c.ssl.global.fastly.net. 29 IN A      151.101.128.175
dualstack.c.ssl.global.fastly.net. 29 IN A      151.101.192.175

;; Query time: 64 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fri Apr 19 07:38:30 CDT 2019
;; MSG SIZE  rcvd: 151

```

I'll ping folks at pypa and rtd to see if they have pointers.

**Comment by aterrel** [comment] 2019-04-19 12:48
Here is the active issue for RTD http->https redirects. https://github.com/rtfd/readthedocs.org/issues/4641

**Comment by mrocklin** [comment] 2019-04-19 13:20
At least it was good beer

**Comment by jakirkham** [comment] 2019-05-20 20:11
Was looking at this to see if there is anything we can improve here. Looks like you have done everything that really can be done until RTD adds support for this feature.

The only other thing we could try is adding [a workaround like this]( https://github.com/runwayml/model-sdk/pull/28 ). Happy to put up a PR if it is of interest. Though would understand if people don't want to do this.

**Comment by aterrel** [comment] 2019-05-21 13:09
Works for me.

**Comment by jrbourbeau** [comment] 2019-06-18 17:28
I can confirm that http://docs.dask.org now redirects to https://docs.dask.org. Closing this issue, thanks to all for your work on this!

**Closed by jrbourbeau** 2019-06-18 17:28 UTC
Labels: documentation

**Comment by mrocklin** [comment] 2019-06-18 17:29
Thanks James!
