### ISSUE TITLE
da.pad().flatten().compute() crashes when zeros are involved in the padding width

### ISSUE THREAD

**Issue by michaeldoron59** [dask/dask#4982] opened 2019-06-23 19:06 UTC
```
import dask.array as da

da.pad(da.ones((10000,1)),((0,0),(0,3)),mode='constant',constant_values=0).flatten().compute()
```

causes this error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-14-143d84eb9912> in <module>
----> 1 da.pad(da.ones((10000,1)),((0,0),(0,3)),mode='constant',constant_values=0).flatten().compute()

C:\ProgramData\Anaconda3\lib\site-packages\dask\base.py in compute(self, **kwargs)
    154         dask.base.compute
    155         """
--> 156         (result,) = compute(self, traverse=False, **kwargs)
    157         return result
    158

C:\ProgramData\Anaconda3\lib\site-packages\dask\base.py in compute(*args, **kwargs)
    396     keys = [x.__dask_keys__() for x in collections]
    397     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 398     results = schedule(dsk, keys, **kwargs)
    399     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    400

C:\ProgramData\Anaconda3\lib\site-packages\dask\threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         pack_exception=pack_exception, **kwargs)
     77
     78     # Cleanup pools associated to dead threads

C:\ProgramData\Anaconda3\lib\site-packages\dask\local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    460                         _execute_task(task, data)  # Re-execute locally
    461                     else:
--> 462                         raise_exception(exc, tb)
    463                 res, worker_id = loads(res_info)
    464                 state['cache'][key] = res

C:\ProgramData\Anaconda3\lib\site-packages\dask\compatibility.py in reraise(exc, tb)
    110         if exc.__traceback__ is not tb:
    111             raise exc.with_traceback(tb)
--> 112         raise exc
    113
    114     import pickle as cPickle

C:\ProgramData\Anaconda3\lib\site-packages\dask\local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    228     try:
    229         task, data = loads(task_info)
--> 230         result = _execute_task(task, data)
    231         id = get_id()
    232         result = dumps((result, id))

C:\ProgramData\Anaconda3\lib\site-packages\dask\core.py in _execute_task(arg, cache, dsk)
    117         func, args = arg[0], arg[1:]
    118         args2 = [_execute_task(a, cache) for a in args]
--> 119         return func(*args2)
    120     elif not ishashable(arg):
    121         return arg

C:\ProgramData\Anaconda3\lib\site-packages\dask\utils.py in __call__(self, obj, *args, **kwargs)
    770
    771     def __call__(self, obj, *args, **kwargs):
--> 772         return getattr(obj, self.method)(*args, **kwargs)
    773
    774     def __reduce__(self):

ValueError: cannot reshape array of size 0 into shape (13332,)

**Comment by jrbourbeau** [comment] 2019-06-24 03:20
Thanks for the report @michaeldoron59. What version of Dask are you using? I'm not able to reproduce the error on the current `master` branch 

```python
In [1]: import dask                                                                                                         

In [2]: dask.__version__                                                                                                    
Out[2]: '1.2.2+96.g243cb103'

In [3]: import dask.array as da                                                                                             

In [4]: da.pad(da.ones((10000,1)),((0,0),(0,3)),mode='constant',constant_values=0).flatten().compute()                      
Out[4]: array([1., 0., 0., ..., 0., 0., 0.])
```

**Comment by michaeldoron59** [comment] 2019-06-24 08:10
Thank you for your response @jrbourbeau,
My version is 1.2.2,
Then I assume that this bug has been fixed in the master branch already...
Well, thanks anyway, and I'll wait for the official update.
Cheers

**Comment by jakirkham** [comment] 2019-06-24 13:25
Would you like to submit a PR with such a test, @michaeldoron59?

**Comment by jakirkham** [comment] 2019-06-24 14:06
As a note, this was fixed by PR ( https://github.com/dask/dask/pull/4167 ) since `da.pad` uses `da.block` (which uses `da.concatenate` internally) to pad the edges. Now `da.concatenate` will simply ignore trivial arrays when constructing the final graph. Have added a test for `da.pad`'s new behavior to ignore trivial paddings in PR ( https://github.com/dask/dask/pull/4990 ).

**Comment by jakirkham** [comment] 2019-06-24 15:01
Also added PR ( https://github.com/dask/dask/pull/4991 ) to explicitly test that `da.block` drops trivial arrays. I think with both of these PRs in we can consider this issue resolved.

**Closed** 2019-06-24 20:28 UTC
Labels: array
