### ISSUE TITLE
Using dask-distributed for fitting random forest estimator from sklearn

### ISSUE THREAD

**Issue by haritaparikh** [dask/dask#5951] opened 2020-02-27 06:47 UTC
I am trying to use dask on random forest estimator written in sklearn. Dask client was created using the following parameters:
  
-   "n_workers": null
-   "threads_per_worker": null
-   "processes": true
-   "loop": null
-    "start": null
-    "host": null
-    "ip": null
-    "scheduler_port": 0
-    "silence_logs": 30
-    "dashboard_address": ":8787"
-    "worker_dashboard_address": null
-    "diagnostics_port": null
-    "services": null
-    "worker_services": null
-    "service_kwargs": null
-    "asynchronous": false
-    "security": null
-    "protocol": null
-    "blocked_handlers": null
-    "interface": null
-    "worker_class": null

Random forest estimator is instantiated with RandomForestClassifier() from sklearn using following parameters:
    

- "n_estimators": 100,
-  "epochs": 5,
-  "max_depth": 5,
-  "min_samples_split": 5,
-  "min_samples_leaf": 5,
-  "min_weight_fraction_leaf": 0,
-  "max_leaf_nodes": 5,
-  "min_impurity_decrease": 0.1,
-  "max_samples": 0.2,
-  "minibatch_size": 200
-  "criterion": "gini"
-  "max_features": "auto"
-  "n_jobs": null

fit() method on the classifier was called under the following scope:

   ` with joblib.parallel_backend("dask"):`

### which throws the error shown below:

 model.fit(x_data, y_data)
  File "venv\lib\site-packages\sklearn\ensemble\_forest.py", line 383, in fit
    for i, t in enumerate(trees))
  File "venv\lib\site-packages\joblib\parallel.py", line 950, in __call__
    n_jobs = self._initialize_backend()
  File "venv\lib\site-packages\joblib\parallel.py", line 711, in _initialize_backend
    **self._backend_args)
  File "venv\lib\site-packages\joblib\_dask.py", line 172, in configure
    return self.effective_n_jobs(n_jobs)
  File "venv\lib\site-packages\joblib\_dask.py", line 183, in effective_n_jobs
    effective_n_jobs = sum(self.client.ncores().values())
  File "venv\lib\site-packages\distributed\client.py", line 3109, in nthreads
    return self.sync(self.scheduler.ncores, workers=workers, **kwargs)
AttributeError: 'NoneType' object has no attribute 'ncores'

#### Versions
dask==2.10.0
distributed==2.10.0
joblib==0.14.1
scikit-learn==0.22.1

**Comment by TomAugspurger** [comment] 2020-02-27 11:47
Hmm do you have a reproducible example? For example this works:

```python
In [9]: from distributed import Client

In [10]: c = Client()

In [11]: import joblib

In [12]: from sklearn.ensemble import RandomForestClassifier

In [13]: import sklearn.datasets

In [14]: X, y = sklearn.datasets.make_classification()

In [15]: with joblib.parallel_backend("dask"):
    ...:     RandomForestClassifier().fit(X, y)
```

**Comment by TomAugspurger** [comment] 2020-03-03 18:06
@haritaparikh are you able to provide an example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by haritaparikh** [comment] 2020-03-30 07:07
While debugging, I figured, the argument asynchronous = False, with all the other arguments as default values, results in AttributeError: 'NoneType' object has no attribute 'ncores'.

However, commenting the argument results in the following error:

distributed.client - ERROR - Error in callback <function DaskDistributedBackend.apply_async.<locals>.callback_wrapper at 0x0000021B7233FAF8> of <Future: cancelled, type: builtins.list, key: _parallel_build_trees-batch-23dfcffa6ea74049a095fe0d9b5d9c6e>:
Traceback (most recent call last):
  File "C:\Users\Harita\Desktop\coding\workspace\localgit\Harita-Parikh-master\ML Algorithms\ensemble\random_forest_classifier\venv\lib\site-packages\distributed\client.py", line 287, in execute_callback
    fn(fut)
  File "C:\Users\Harita\Desktop\coding\workspace\localgit\Harita-Parikh-master\ML Algorithms\ensemble\random_forest_classifier\venv\lib\site-packages\joblib\_dask.py", line 260, in callback_wrapper
    result = future.result()
  File "C:\Users\Harita\Desktop\coding\workspace\localgit\Harita-Parikh-master\ML Algorithms\ensemble\random_forest_classifier\venv\lib\site-packages\distributed\client.py", line 224, in result
    raise result
concurrent.futures._base.CancelledError: _parallel_build_trees-batch-23dfcffa6ea74049a095fe0d9b5d9c6e

**Comment by mrocklin** [comment] 2020-03-30 14:32
@haritaparikh please provide a minimal reproducible example.  See Tom's post above for a link to an explanation of what we're looking for here, and why.

**Comment by jsignell** [comment] 2021-03-12 16:20
Closing due to lack of example.

**Closed by jsignell** 2021-03-12 16:20 UTC
