### ISSUE TITLE
No actual CPU/memory usage on Web UI after upgrading to distributed-1.20.2/dask-0.16.0

### ISSUE THREAD

**Issue by JR-Mayday** [dask/dask#3136] opened 2018-02-03 21:56 UTC
After upgrading to distributed-1.20.2/dask-0.16.0, CPU/memory usage on workers page cannot reflect real usage. Every host shows 8% or 10% CPU usage and <5% memory usage all the time. Jobs can finish without any problem. Just can not see any CPU/memory usage change.

<img width="885" alt="screen shot 2018-02-03 at 1 01 12 pm" src="https://user-images.githubusercontent.com/36115571/35771902-36d87dec-08e9-11e8-869e-0c1a6506e2d7.png">

Before upgrading, I'm using distributed-1.19.3/dask-0.15.4. I can see the usage change when running any job.

<img width="658" alt="screen shot 2018-02-03 at 1 53 23 pm" src="https://user-images.githubusercontent.com/36115571/35771938-eaf5eef4-08e9-11e8-9ec8-a97f15cc56e7.png">

**Comment by mrocklin** [comment] 2018-02-04 15:06
Unfortunately I'm unable to reproduce this.  Things seem to respond normally for me.  A couple things to check:

1.  Verify that you've created a client where you're running jobs and that that client is pointing to this cluster.  Maybe it's using a different set of resources?
2.  Look at the other pages in the dashboard to verify that computations are being run and that memory is being used.  As a simple example, perhaps try to persist some data on the cluster with the following:

    ```python
    import dask.array as da
    x = da.random.random((20000, 20000), chunks=(1000, 1000)).persist()

**Comment by JR-Mayday** [comment] 2018-02-05 05:58
It's same job running on same cluster. The only difference is dask/distributed version.

My use case is using subprocess.Popen to run another script in a new process:
```python
process = Popen(
    command, 
    stdin=PIPE,
    stdout=PIPE,
    stderr=STDOUT,
    shell=True
)
process.communicate()
```

Seems the resource usage of new process is not collected. Same code works well with old versions (distributed-1.19.3/dask-0.15.4).

**Comment by JR-Mayday** [comment] 2018-02-14 20:18
Can you reproduce this issue? We are very interested in dask after your presentation to our team. Popen may not be a good use case for dask. We just start testing dask cluster with existed executable scripts.

**Comment by mrocklin** [comment] 2018-02-14 21:05
I have not run into cases where the dashboard doesn't operate well.  It shows memory as measured by `psutil.Process().memory_info().rss`.  If you were concerned about the accruacy of the dashboard you might check your workers memory use while operating by using the `Client.run` method

```python
import psutil
def get_memory():
    return psutil.Process().memory_info().rss

client.run(get_memory)
```

Maybe we used to measure it differently before?  Maybe we used vms? 

If your tasks are running in a separate process then I wouldn't necessarily expect them to be counted under rss.

**Comment by NotSqrt** [comment] 2018-10-11 15:46
Maybe `children(recursive=True)` ? 
in https://github.com/dask/dask/blob/105649e2fdb36981529c9f267630e48ed8e88ff2/dask/diagnostics/profile.py#L225

**Comment by NotSqrt** [comment] 2018-10-15 17:32
Also, `.cpu_percent()` will return the percentage of time spent in this process, **since last call**.
But the code re-instanciates the children at each loop, so the `.cpu_percent()` will always be 0 for children, be it recursive or not.

Only `self.parent` has a correct value.

**Comment by mrocklin** [comment] 2018-10-15 17:56
That code isn't used for the dashboard.  That's used for the single-machine scheduler's diagnostics.

**Comment by mrocklin** [comment] 2018-10-15 17:59
Not saying it's not wrong, just that it's not related to the issue you were seeing.

I'm also surprised by what you say, because that diagnostic has been used for a while and, if memory serves, provided non-zero results.

**Comment by mrocklin** [comment] 2018-10-24 17:50
This conversation seems to have stalled.  Closing.

**Closed by mrocklin** 2018-10-24 17:50 UTC

**Comment by NotSqrt** [comment] 2018-10-24 17:55
Yes, and the problem is probably more in https://github.com/dask/distributed/blob/0dedc514caa08d7a177a13c8cc745fd22aaabb20/distributed/system_monitor.py#L48 than in dask itself.
