### ISSUE TITLE
Rows can be dropped when setting index on a categorical with non-lexical order.

### ISSUE THREAD

**Issue by markkoob** [dask/dask#5671] opened 2019-12-04 19:14 UTC
When setting the index on a partitioned dataframe to a categorical whose order is not lexical, rows can be lost. That's a mouthful for sure, and I'm not certain that it would be reasonable to expect otherwise, but I have produced an MRP.

```python
import os
import string, random

import pandas as pd
import numpy as np
import dask
import dask.dataframe as dd

print(dask.__version__)

def random_word(len=10):
    return ''.join(np.random.choice(list(string.ascii_letters), len))

rows = 5000
labels = [random_word(np.random.randint(15, 30)) for i in range(rows)]
data = [i for i in range(len(labels))]

df = pd.DataFrame({'ID': labels, 'data': data})


ddf = dd.from_pandas(df, npartitions=10)
print(ddf.shape[0].compute())

# Drop rows
ddf = ddf.categorize(columns=['ID'])
ddf['ID'] = ddf['ID'].cat.as_ordered()
ddf = ddf.set_index('ID')
print(ddf.shape[0].compute())

# Does not drop rows
ddf = dd.from_pandas(df, npartitions=10)
ddf = ddf.categorize(columns=['ID'])

# Order category lexically
cats = ddf['ID'].cat.categories.values
cats = sorted(cats)
ddf = ddf
ddf['ID'] = ddf['ID'].cat.reorder_categories(cats, ordered=True)

ddf.set_index('ID')
print(ddf.shape[0].compute())
```

In my case, the output generated is:

```
2.8.1
5000
1223
5000
```

This doesn't occur when the dataframe is a single partition. Digging around in the documentation makes me think there might be a scalar lexical comparison instead of a categorical compare somewhere. That or I'm not expecting the right behavior!

**Comment by jcrist** [comment] 2019-12-05 00:09
Thanks for the excellent issue report, I'm able to reproduce the issue. This is definitely a bug. I'd guess that it's an issue in our `set_index` code, which does sorting along the index to repartition. If you feel like debugging deeper, I'd start looking there.

**Comment by markkoob** [comment] 2019-12-05 19:56
I've spent some more time with this and I think I've narrowed it down to `dataframe.shuffle:rearrange_by_column_disk()` but wow it is pretty gnarly in there. I'm not familiar enough with dask's internals yet to figure out exactly what is going on. It looks like there are some `as_ordered` references in the shuffle-collect stage of the graph, `dsk4`, and I think they might be related.

**Comment by markkoob** [comment] 2019-12-10 16:38
Ok I think I've found the defect, but I'm unsure of the best way to patch it. In `dask.dataframe.shuffle.set_partitions_pre` the `divisions.searchsorted` operation returns invalid results since Series `s` has dtype `pandas.CategoricalDtype` while `divisions` is of type `object`. If I override the dtype of `divisions` to match `s` then the results are correct. Performing that operation in `set_partitions_pre` seems like a bad way to do this.

I think a better fix would be changing can be  `dask.dataframe.shuffle.set_partitions`:

`    divisions = df._meta._constructor_sliced(divisions)`

to

`    divisions = df._meta._constructor_sliced(divisions).astype(df[index].dtype)`

Making sure the types match seems like a good idea, but I note that in `dask.dataframe.shuffle.set_index` we have already explicitly changed them from a series of the correct type to a list(!):

`divisions = divisions.tolist()`

Swapping the type of divisions back and forth seems sub-optimal.

I'm going through the process testing a commit and all that, but wanted to post just incase this is a ridiculous proposal, and because I'm going to be traveling starting tomorrow and I don't want to forget the details.

**Comment by TomAugspurger** [comment] 2019-12-10 18:05
Thanks for continuing to update. Could you share snippets of input /outputs in `set_partitions` / `set_partitions_pre` and `searchsorted`? That'd make it easier for us to gauge things.

I'll also take a look locally now.

**Comment by TomAugspurger** [comment] 2019-12-10 18:18
A  bit easier of a reproducer since it doesn't modify `ddf`


```python
import string

import pandas as pd
import numpy as np
import dask
import dask.dataframe as dd

print(dask.__version__)


def random_word(len=10):
    return ''.join(np.random.choice(list(string.ascii_letters), len))


rows = 5000
labels = [random_word(np.random.randint(15, 30)) for i in range(rows)]
labels = pd.Categorical(labels, categories=pd.unique(labels), ordered=True)
data = np.arange(len(labels))

df = pd.DataFrame({'ID': labels, 'data': data})
ddf = dd.from_pandas(df, npartitions=10)
r = ddf.set_index("ID").shape[0].compute()
assert r == 5000, r
```

**Comment by markkoob** [comment] 2019-12-10 18:30
Unfortunately I don't have a nice and tidy debug session since this involved stepping through the scheduler and such to find exactly where things broke. Digging through what's left in my console history here are some interesting bits:

Broken:
```
> dask/dataframe/shuffle.py(560)set_partitions_pre()                                                                                                                                                                                                   
-> partitions = divisions.searchsorted(s, side="right") - 1                                                                                                                                                                                                                                                                  
(Pdb) !s                                                                                                                                                                                                                                                                                                                     
0       HLKqjkquDubWNrpAVdUZZiNMjzal                                                                                                                                                                                                                                                                                         
1      SOYeMUTdJUzwZliNjYBHEWWvpvTmk                                                                                                                                                                                                                                                                                         
2             focbliZQYtABAjrVdJZCEN                                                                                                                                                                                                                                                                                         
3                  DunGqQmGuJlbjCMoq                                                                                                                                                                                                                                                                                         
4                  wlErPVmTibdjGrEiZ                                                                                                                                                                                                                                                                                         
                   ...                                                                                                                                                                                                                                                                                                       
495           nPhmEiMMEcmJTzJYVAIOFQ                                                                                                                                                                                                                                                                                         
496    aWhjcqaiAMCfiypafmzTvGxfqGxzw                                                                                                                                                                                                                                                                                         
497     OcXGYFNaXuhtEjtikCAtkFEiCxKK                                                                                                                                                                                                                                                                                         
498                kbGMqzwPEWrSbiwxC                                                                                                                                                                                                                                                                                         
499     xjKOAmQADwMarfmqFYsBifdXxtxR                                                                                                                                                                                                                                                                                         
Name: ID, Length: 500, dtype: category                                                                                                                                                                                                                                                                                       
Categories (1000, object): [HLKqjkquDubWNrpAVdUZZiNMjzal < SOYeMUTdJUzwZliNjYBHEWWvpvTmk <                                                                                                                                                                                                                                   
                            focbliZQYtABAjrVdJZCEN < DunGqQmGuJlbjCMoq ... iqDRQaMxpCOuNaNCOOObJasR <                                                                                                                                                                                                                        
                            zCVyliMRpVtQAWvmFMZvqcpcPa < jexaZlCqfSEoIQAsfYivprkhtJG <                                                                                                                                                                                                                                       
                            hkzuLcghsBzShCwxHyTDPtzwBE]                                                                                                                                                                                                                                                                      
(Pdb) divisions                                                                                                                                                                                                                                                                                                              
0    HLKqjkquDubWNrpAVdUZZiNMjzal                                                                                                                                                                                                                                                                                            
1    xjKOAmQADwMarfmqFYsBifdXxtxR                                                                                                                                                                                                                                                                                            
2      hkzuLcghsBzShCwxHyTDPtzwBE                                                                                                                                                                                                                                                                                            
dtype: object                                                                                                                                                                                                                                                                                                                
(Pdb) divisions.searchsorted(s, side="right") - 1                                                                                                                                                                                                                                                                            
array([ 0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0,  0,  2,  2,                                                                                                                                                                                                                                                   
        2,  0, -1,  0,  0,  0,  0,  2,  0,  2,  0,  0,  2,  0,  0,  2, -1,                                                                                                                                                                                                                                                   
        0,  0,  2,  0, -1,  0,  0,  0, -1,  0,  2,  0,  2,  0,  2,  0,  0,                                                                                                                                                                                                                                                   
       -1,  0,  0,  0,  2,  0,  0,  2, -1,  0,  0,  0, -1,  0,  0,  0, -1,                                                                                                                                                                                                                                                   
        0,  0, -1,  0,  0,  2,  0,  2,  2,  0,  2,  0,  2,  0,  2,  2,  2,                                                                                                                                                                                                                                                   
        0,  0, -1,  0,  0,  2, -1,  0,  2,  0,  0,  2,  0, -1,  0, -1,  0,                                                                                                                                                                                                                                                   
        0,  2,  0,  0,  0,  0,  2, -1,  0,  2,  0,  0, -1, -1,  0,  0,  0,                                                                                                                                                                                                                                                   
        0,  0, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0,  2,  0,  2,  0,  0,                                                                                                                                                                                                                                                   
       -1,  0,  0,  0,  0,  0,  2,  0,  2,  0,  0,  0,  0, -1,  0,  2,  0,                                                                                                                                                                                                                                                   
        0,  0,  2, -1, -1, -1,  0,  0,  2,  0,  0,  2,  0,  2,  0,  0,  0,                                                                                                                                                                                                                                                   
        2,  0,  0,  0,  2,  2, -1,  0,  0,  0,  0,  2,  0,  0, -1,  0,  0,                                                                                                                                                                                                                                                   
        0,  2,  0,  2,  0,  2,  0,  0, -1,  0,  0,  0,  2,  0,  0,  0, -1,                                                                                                                                                                                                                                                   
        0, -1, -1,  0, -1,  0,  0,  2,  0,  0,  0, -1,  0,  0,  2,  0,  0,                                                                                                                                                                                                                                                   
        2,  0,  0, -1,  0,  0,  0,  0,  0,  0,  2,  0,  2, -1,  0,  0,  2,                                                                                                                                                                                                                                                   
        0,  2, -1,  0, -1, -1,  0, -1,  0,  0,  2,  0,  0,  0,  0,  2, -1,                                                                                                                                                                                                                                                   
        0,  0,  2,  0,  0,  2,  0,  0,  0,  2,  0,  0, -1,  0,  2, -1,  0,                                                                                                                                                                                                                                                   
        0,  2,  0,  0,  2,  0,  0,  0,  0,  2,  2, -1,  0,  0,  0,  2, -1,                                                                                                                                                                                                                                                   
       -1, -1,  0, -1,  0,  0,  0,  2,  0,  0,  2,  0,  2,  0,  2,  0,  2,                                                                                                                                                                                                                                                   
        0, -1,  0, -1,  0,  2,  0,  2, -1,  0,  2,  2, -1,  0,  2,  0,  0,                                                                                                                                                                                                                                                   
        0,  2,  0,  2,  0, -1,  0,  2,  0,  2,  0,  0,  0,  2,  2,  2,  0,                                                                                                                                                                                                                                                   
        0,  0,  2,  0,  0,  2,  0,  0,  2,  0,  0,  2,  0,  0,  2, -1,  0,                                                                                                                                                                                                                                                   
        0,  2,  0,  2,  0,  2,  2,  0, -1,  0,  2,  0,  0,  2,  2,  0,  2,                                                                                                                                                                                                                                                   
        0,  0, -1,  0,  0, -1,  0,  0,  0,  2, -1,  0,  0, -1,  0,  0, -1,                                                                                                                                                                                                                                                   
        0,  0, -1,  0,  0,  0,  0,  0,  0,  2,  0,  0,  2,  0,  2,  0,  0,                                                                                                                                                                                                                                                   
        0,  2,  0,  0,  0,  0, -1,  0,  0,  2, -1,  0,  0,  0,  2,  2,  0,                                                                                                                                                                                                                                                   
        0,  2,  0, -1,  0, -1, -1, -1,  0,  2,  0,  0,  0,  2, -1,  0,  0,                                                                                                                                                                                                                                                   
        0,  2,  0,  2,  0,  0,  2,  0,  0,  0, -1, -1,  2, -1,  0,  0,  0,                                                                                                                                                                                                                                                   
        2,  2,  0,  0,  0,  2,  0,  2,  0,  0,  0,  0, -1, -1,  0,  0,  2,                                                                                                                                                                                                                                                   
        0,  2,  0,  2,  0,  0,  0,  2,  0,  0,  0,  2,  2,  0,  0,  2,  2,                                                                                                                                                                                                                                                   
        0,  0,  0,  0,  0,  2,  2])
```

Not broken:

```
> dask/local.py(224)execute_task()                                                                                                                                                                                                                     
-> result = dumps((result, id))                                                                                                                                                                                                                                                                                              
(Pdb) result                                                                                                                                                                                                                                                                                                                 
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,                                                                                                                                                                                                                                                     
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,                                                                                                                                                                                                                                                     
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
```

Although I'm definitely concerned about the labels being clumped together like that, so maybe it's just broken in a different way. All the rows are at least in the dataframe at the end of the set_index operation this way!

Since I don't have a proper development environment I used a patch:

```
def set_partitions_pre(s, divisions):
    from pandas import CategoricalDtype
    if isinstance(s.dtype, CategoricalDtype):
        divisions = divisions.astype(s.dtype)
    partitions = divisions.searchsorted(s, side="right") - 1
    partitions[(s >= divisions.iloc[-1]).values] = len(divisions) - 2
    return partitions

dask.dataframe.shuffle.set_partitions_pre = set_partitions_pre
```

**Comment by markkoob** [comment] 2019-12-10 20:20
Oh, one other hint for reproducing - this still fails with npartitions = 2, so for debug I was using 1000 rows with two partitions.

**Comment by TomAugspurger** [comment] 2019-12-16 17:55
I think I have a fix for this. Basically, just extract the codes for these comparisions if we have a CategoricalDtype. Will put up a PR shortly.

**Comment by markkoob** [comment] 2019-12-18 14:06
Hey Tom - I can confirm this fixes the use case in my environment. Thanks a bunch for making the PR.

**Closed** 2019-12-28 17:06 UTC
Labels: dataframe
