### ISSUE TITLE
set_index on datetime column with microsecond precision removes one row from dataframe

### ISSUE THREAD

**Issue by dtourillon** [dask/dask#6864] opened 2020-11-19 17:48 UTC
**What happened**:

I created a pandas dataframe with shape (4, 2). One of the column is a datetime with microsecond precision.

If I create a dask dataframe from this pandas dataframe and call `set_index` on the datetime column, the resulting dataframe now has only 3 rows:
![image](https://user-images.githubusercontent.com/25746704/99700936-d180b700-2a61-11eb-966f-c534228cd26f.png)

**What you expected to happen**:

If I comment out the line where we convert the index column to a datetime, then I get a dataframe with 4 rows:
![image](https://user-images.githubusercontent.com/25746704/99701099-012fbf00-2a62-11eb-833c-1aa07b30e545.png)

I expected the original code snippet to produce the same output (i.e. 4 row dataframe), but with the index as a datetime instead of a number of microseconds since 1970-01-01. 

As a workaround, if I convert the column to datetime **after setting the index**, then I get what I really want:
![image](https://user-images.githubusercontent.com/25746704/99703034-9d5ac580-2a64-11eb-97d5-910c573a4fa1.png)

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

df = pd.DataFrame(
    [
        [1567703791155681, 1],
        [1567703792155681, 2],
        [1567703790155681, 0],
        [1567703793155681, 3],
    ],
    columns=["ts", "rank"]
)
df.ts = pd.to_datetime(df.ts, unit='us')  # comment this line to get a df with 4 lines

ddf = dd.from_pandas(df, npartitions=2)

ddf = ddf.set_index("ts")

ddf.compute()
```

**Anything else we need to know?**:
I suspect the problem comes from the fact that the divisions of the dask dataframe after `set_index` are as follows:
![image](https://user-images.githubusercontent.com/25746704/99702095-63d58a80-2a63-11eb-8297-87d579029c7a.png)

Notice that the divisions are precise to the nanosecond and that the first division is bigger than the timestamp of the row we've lost by 24 nanoseconds... Looks like numerical imprecision microseconds-to-datetime conversion maybe?

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.6
- Operating System: Linux (FROM python:3.8.6-buster in Dockerfile)
- Install method (conda, pip, source): pip

n.b. I ran the above snippet in a jupyter notebook.

**Comment by rjzamora** [comment] 2020-11-19 23:37
Thanks for the nice reproducer @dtourillon !

I was able to reproduce the problem and tracked the precision error to [the round-trip casting](https://github.com/dask/dask/blob/ff3ea6c74e8736a5823d648defcf9164f083d266/dask/array/percentile.py#L28) used to enable the `np.percentile` call on each partition of the index.  One possible fix is to check (after the conversion) that the first division is no greater than the minimum value in the index.  Or perhaps we could always set the first division to the minimum...

**Comment by dtourillon** [comment] 2020-11-20 01:11
@rjzamora I am relatively new to dask, so I might be overlooking something... but I suspect fixing only the first division would not be sufficient.

Try adding this before the code snippet above:
```
from dask.distributed import Client
client = Client(n_workers=1, memory_limit='1GB')
```

Then when I run the code snippet above, I get:
- ddf.known_divisions is True
- the same divisions as above
- 4 rows... but the dataframe is not sorted (I think each partition is sorted, but not globally):
![image](https://user-images.githubusercontent.com/25746704/99743130-02cda700-2aa3-11eb-88fc-e72d77d18f16.png)
- ddf.index.compute().is_monotonic is False

Sorry for not posting all these additional details earlier, I thought it would over-complicate the issue report...

**Comment by rjzamora** [comment] 2020-11-20 01:41
> but I suspect fixing only the first division would not be sufficient

There is a decent chance that your intuition is correct.  #6866 certainly feels more like a bandaid than a fix.

Regarding your `distributed`  `index.is_monotonic` check:  I can confirm that I get the correct result when only the first division is adjusted.  Although there are small precision errors in **all** the divisions, the first division is the most critical.  This is because the data will be lost, or assigned to the **last** partitions (this is because we use a `searchsorted` to assign the final partition for each row, and anythin below the first division will get `-1`).  When other divisions ar "off" there will only be an issue if two sequential divisions collide (which seems like a fairly *special* case).

**Comment by dtourillon** [comment] 2020-11-20 02:42
Alright, hopefully fixing the first division fixes the fact that the overall index is not sorted in the end... You certainly know better than I do! ;)

However, I am pretty sure (but not 100% certain) that I have also lost data (on my real 399 million rows dataframe) based on numerical imprecision of the last division... same problem with last and first divisions?

Oh, and thanks for such a fast analysis and answer to my issue... greatly appreciated!

**Comment by rjzamora** [comment] 2020-11-20 04:58
>However, I am pretty sure (but not 100% certain) that I have also lost data (on my real 399 million rows dataframe) based on numerical imprecision of the last division... same problem with last and first divisions?

Yeah - I wouldn't be surprised if there were knock-on effects that I am not thinking of.  I don't feel confident that correcting the first division will cover **all** cases, but my intuition tells me that error in the last division isn't likely to cause a problem.  Note that any element falling beyond the threshold of the last division [will be reassigned to the last division anyway](https://github.com/dask/dask/blob/ff3ea6c74e8736a5823d648defcf9164f083d266/dask/dataframe/shuffle.py#L1078).

**Closed** 2020-11-24 14:57 UTC
