### ISSUE TITLE
Error with the default tokenizer.

### ISSUE THREAD

**Issue by trivialfis** [dask/dask#11179] opened 2024-06-14 09:18 UTC
Hi, XGBoost is running into non-deterministic `Cancelled` errors with the latest dask. @rjzamora helped track down the cause to https://github.com/dask/dask/pull/10883 in https://github.com/dmlc/xgboost/pull/10398 .  The workaround helped fix the error, but still, it would be great if we could have better support in xgboost for the latest hashing procedure in dask and remove the custom tokenizer.

**Minimal Complete Verifiable Example**:

We don't have a MCVE, unfortunately. Also, it's non-deterministic. But it's not too difficult to reproduce with some of the existing XGBoost tests.

You can install the xgboost RC release `pip xgboost=2.1.0rc1` or from the master branch with [nightly](https://xgboost.readthedocs.io/en/stable/install.html#id1) build to avoid building XGBoost from source. Afterward, run one of the following commands with a GPU cluster under the xgboost source directory (repeatedly):
```
pytest -s ./tests/test_distributed/test_gpu_with_dask/test_gpu_with_dask.py::TestDistributedGPU::test_categorical
```
or
```
pytest -s ./tests/test_distributed/test_gpu_with_dask/test_gpu_with_dask.py::TestDistributedGPU::test_empty_partition
```
These are the two tests that work before the change in hashing but run into cancelled errors after the change. At the time of writing, XGBoost is on https://github.com/dmlc/xgboost/commit/cf0c1d08882751085b8e1a8cbc902510bb89065a 

cc @crusaderky

**Comment by crusaderky** [comment] 2024-06-14 13:48
I haven't looked at the xgboost code but I'm going to go on a blind guess here.

#10883 changes the tokenizer so that if two opaque objects pickle to the exact same bytes, they will produce the same token. This is very much by design and desirable.

However, this likely exposed you to a known race condition in `scatter()`, https://github.com/dask/distributed/issues/8576, where if you release a key and then `scatter()` the exact same key in rapid succession, you may end up with nothing in memory. The random UUID token was, accidentally, working around it.

As a way to verify my theory, you can add a `sleep(2)` immediately before all of your calls to `scatter()`.

Short of fixing https://github.com/dask/distributed/issues/8576 itself, I see two workarounds possible:
1. find out why your code dereferences and then immediately afterwards re-create the same exact object. Why do you need to do that? Could you keep the original reference instead?
2. Add a method to your class to restore the previous behaviour:
```python
class MyClass:
    _dask_token = None

    def __dask_tokenize__(self):
        """Two identical instances created in different places must have different tokens,
        but the same object should retain the same token even after a pickle roundtrip
        """
        if self._dask_token is None:
            self._dask_token = uuid.uuid4()
        return self._dask_token
```

**Comment by rjzamora** [comment] 2024-06-14 14:00
Thanks for taking a look at this @crusaderky !

>However, this likely exposed you to a known race condition in scatter(), https://github.com/dask/distributed/issues/8576, where if you release a key and then scatter() the exact same key in rapid succession, you may end up with nothing in memory. The random UUID token was, accidentally, working around it.

Aha - This sounds like a promising lead to me.

**Comment by trivialfis** [comment] 2024-06-14 15:47
Thank you for the explanation, that makes sense. I can verify the setting `hash=False` can workaround the issue. Should we close this one?

**Comment by crusaderky** [comment] 2024-06-14 16:40
Closed as duplicate of https://github.com/dask/distributed/issues/8576

**Closed by crusaderky** 2024-06-14 16:40 UTC
Labels: needs triage
