### ISSUE TITLE
groupby with index name

### ISSUE THREAD

**Issue by jreback** [dask/dask#957] opened 2016-02-04 15:54 UTC
```
ddf = dd.DataFrame(....)
g = ddf.set_index('name')

# works
g.groupby(g.index).apply(lambda x: x)
```

```
# fails (as the index name is not set/recognized)
g.groupby('name').apply(lambda x: x)
```

xref #956

**Comment by jcrist** [comment] 2016-02-12 21:16
Is this possible in pandas? I can't seem to get it to work:

```python
In [36]: df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': ['a', 'b', 'c', 'c']}).set_index('b')

In [37]: df.groupby('b')
<big traceback...>
KeyError: 'b'
```

**Comment by mrocklin** [comment] 2016-02-12 21:34
The goal is to be able to pass the name of the index in as groupby and have it trigger a proper groupby index.

E.g. if we have a dataframe with the index name `'date'` we want to be able to say `df.groupby('date')` and have it do a proper groupby-index call.

This wasn't possible before because we didn't track the name of the index.  As of #961 we do.

**Comment by jcrist** [comment] 2016-02-12 21:37
I understand what the goal is, what I mean is pandas doesn't support passing an index name. You need to use the `level` keyword to make it work. It's definitely doable, I'm just unsure if we want to break compatibility here.

**Comment by mrocklin** [comment] 2016-02-12 21:38
Oh, my bad.  I totally misread your original message.

**Comment by jreback** [comment] 2016-02-12 22:00
2 comments 

1) it's Unimplemented but pandas will at some point support inference on a name of it's an index level and unambiguous
2) if/when dask supports multi indexes the level arg is important (most of the time can be inferred as well)

**Comment by jcrist** [comment] 2017-05-02 22:01
Closing for now, as this behavior is unimplemented in pandas. Feel free to reopen when the issue is resolved upstream.

```python
In [8]: df = pd.DataFrame({'a': [1, 2, 3, 4], 'b': ['a', 'b', 'c', 'c']}).set_index('b')

In [9]: df
Out[9]:
   a
b
a  1
b  2
c  3
c  4

In [10]: df.groupby('b')
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/Users/jcrist/anaconda/envs/dask/lib/python3.5/site-packages/pandas/indexes/base.py in get_loc(self, key, method, tolerance)
   2133             try:
-> 2134                 return self._engine.get_loc(key)
   2135             except KeyError:

pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)()

pandas/index.pyx in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)()

pandas/src/hashtable_class_helper.pxi in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)()

pandas/src/hashtable_class_helper.pxi in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)()

KeyError: 'b'
```

**Closed by jcrist** 2017-05-02 22:01 UTC
Labels: dataframe, introductory

**Comment by h-vetinari** [comment] 2019-07-22 09:31
This can be reopened; pandas has implemented the ability to groupby on index columns a while ago. The example from @jchrist [above](https://github.com/dask/dask/issues/957#issuecomment-298774421) now works.
