### ISSUE TITLE
Dask apply function does not support using global python variables

### ISSUE THREAD

**Issue by sanjaymeena** [dask/dask#6321] opened 2020-06-15 01:25 UTC
Hello , 

I use dask heavily for my work (single machine)  and really pleased with its ease of use. 

I use global variables in the apply function for some logic. This worked with versions upto `dask 2.15.0` . Since Dask `2.16.0` , Global variables in the apply functions are no longer working. 

`df1.map_partitions(lambda df1: df1.apply(func, axis=1)).compute(
                scheduler="processes"
`

I get `NoneType` error for the global variable 

Do I need a workaround for using global variables ? 

**Environment**:

- Dask version: 2.16.0 + 
- Python version: 3.7
- Operating System: Ubuntu
- Install method (conda, pip, source):pip

**Comment by TomAugspurger** [comment] 2020-06-16 13:41
Thanks for the report. Do you have a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by ncclementi** [comment] 2021-08-19 21:28
@sanjaymeena It's been a while since this issue has the tag `needs info` and after a request for a minimal reproducible example, there has been no answer so I'm going to close this issue for now. But if you have such an example please feel free to re-open this issue with it.

**Closed by ncclementi** 2021-08-19 21:28 UTC
Labels: needs info
