### ISSUE TITLE
ValueError in groupby.get_group from read_csv

### ISSUE THREAD

**Issue by hellocoldworld** [dask/dask#7005] opened 2020-12-23 16:04 UTC
**What happened**:
In dask==2020.12.0, trying to save a csv raised 

```bash
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
 ```
Downgrading to dask==2.30 solved the issue. I think this is related to [PR 6878](https://github.com/dask/dask/pull/6878/files)

**What you expected to happen**:
The dataframe is saved.

**Anything else we need to know?**:
Full traceback:

```bash
  File "/home/nico/Escritorio/pcnt/blacklists_service/crawlers_service/worldsys.py", line 79, in save_subsetted_df
    data.to_csv(filepath, sep=",", index=False, encoding="utf-8", header=False, single_file=True)
  File "/home/nico/.local/share/virtualenvs/blacklists_service--dBzAapY/lib/python3.8/site-packages/dask/dataframe/core.py", line 1433, in to_csv
    return to_csv(self, filename, **kwargs)
  File "/home/nico/.local/share/virtualenvs/blacklists_service--dBzAapY/lib/python3.8/site-packages/dask/dataframe/io/csv.py", line 858, in to_csv
    dfs = df.to_delayed()
  File "/home/nico/.local/share/virtualenvs/blacklists_service--dBzAapY/lib/python3.8/site-packages/dask/dataframe/core.py", line 1493, in to_delayed
    graph = self.__dask_optimize__(graph, self.__dask_keys__())
  File "/home/nico/.local/share/virtualenvs/blacklists_service--dBzAapY/lib/python3.8/site-packages/dask/dataframe/optimize.py", line 28, in optimize
    dependencies = dsk.get_all_dependencies()
  File "/home/nico/.local/share/virtualenvs/blacklists_service--dBzAapY/lib/python3.8/site-packages/dask/highlevelgraph.py", line 532, in get_all_dependencies
    all_keys = self.keyset()
  File "/home/nico/.local/share/virtualenvs/blacklists_service--dBzAapY/lib/python3.8/site-packages/dask/highlevelgraph.py", line 501, in keyset
    self._keys.update(layer.keys())
  File "/home/nico/.local/share/virtualenvs/blacklists_service--dBzAapY/lib/python3.8/_collections_abc.py", line 720, in __iter__
    yield from self._mapping
  File "/home/nico/.local/share/virtualenvs/blacklists_service--dBzAapY/lib/python3.8/site-packages/dask/blockwise.py", line 293, in __iter__
    return iter(self._dict)
  File "/home/nico/.local/share/virtualenvs/blacklists_service--dBzAapY/lib/python3.8/site-packages/dask/blockwise.py", line 595, in _dict
    if io_key in dsk[k]:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.8.6
- Operating System: Ubuntu MATE 18.04, also happen on Alpine Lunux 3.12
- Install method (conda, pip, source): pip (vía pipenv in case of Ubuntu MATE)

**Comment by hellocoldworld** [comment] 2020-12-23 16:10
I'm working on a minimal reproducible example with mocked data, but didn't get there just yet, but while I'm working on it, I was using `to_csv` with the following keyword arguments `sep=",", index=False, encoding="utf-8", header=False, single_file=True`

**Comment by hellocoldworld** [comment] 2020-12-23 16:15
Interesting, I could only reproduce after running a `group_by`. Here's the minimal reproducible example

```python
import dask.dataframe as ddf

df = ddf.read_csv("input.csv", header="infer")

dfs = df.groupby("foo")
d_10 = dfs.get_group(10)
d_10.to_csv("output.csv",single_file=True)
```

**Comment by jrbourbeau** [comment] 2020-12-23 18:56
Thanks for opening an issue @hellocoldworld! Could you produce an example that doesn't rely on a local data file? For example, a maintainer can't run the above snippet because they won't have `input.csv` locally (see https://blog.dask.org/2018/02/28/minimal-bug-reports)

**Comment by hellocoldworld** [comment] 2020-12-28 21:40
Sorry @jrbourbeau I wasn't able to reproduce without using `read_csv` (which makes me think maybe it has something to do with how it was read?). However, I was able to narrow down `input.csv` to the following minimal case

```
foo,bar
10,4
```
Using the code above results in the bug I described.

However

```py
from dask.dataframe import from_pandas
from pandas import DataFrame

df = from_pandas(DataFrame([{"foo": 10, "bar": 4}]), npartitions=1)

dfs = df.groupby("foo")
d_10 = dfs.get_group(10)
d_10.to_csv("output.csv")
```

works just fine.

I know i/o bugs can be difficult, let me know how can I help.

**Comment by jsignell** [comment] 2021-01-06 16:07
Ok thanks for working on the example. I can reproduce with the following:

```python
from dask.dataframe import read_csv
from pandas import DataFrame

df = DataFrame([{"foo": 10, "bar": 4}])
df.to_csv("input.csv", index=False)

ddf = read_csv("input.csv")
ddfs = ddf.groupby("foo")
 ddfs.get_group(10).compute()
```

Pinging @rjzamora since this has to do with blockwise.

**Comment by hellocoldworld** [comment] 2021-01-06 17:43
Thank you @jsignell !

**Comment by rjzamora** [comment] 2021-01-08 14:42
#7042 should close this - I added a relevant test.

**Closed** 2021-01-13 14:59 UTC
Labels: dataframe, io
