### ISSUE TITLE
Trying to filter in dask.read_parquet tries to compare NoneType and str

### ISSUE THREAD

**Issue by filpano** [dask/dask#9764] opened 2022-12-15 13:18 UTC
**Describe the issue**:

I have a project where I pass the following `load_args` to `read_parquet` when loading partitioned data (in the form `s3://<bucket>/<root>/year=xxxx/month=yy/day=zz/wwww.parquet`) from `s3`:

```
load_args = {'filters': [('itemId', '=', '9403cfde-7fe5-4c9c-916c-41ff0b595c5c')]}
```

According to the [documentation](https://docs.dask.org/en/stable/generated/dask.dataframe.read_parquet.html), a `List[Tuple]` like this should be accepted and I should get all partitions which match the predicate (or equivalently, filter out those that do not).

However, it gives me the following error:

```
│                                                                                  │
│ /home/user/project/venv/lib/python3.10/site-packages/dask/dataframe/io/parquet/  |
| core.py:1275 in apply_conjunction                                                │
|                                                                                  |
|   1264 |   for part, stats in zip(parts, statistics):                            |
|   1265 |   |   |   |   if "filter" in stats and stats["filter"]:                 |
|   1266 |   |   |   |   |  continue  # Filtered by engine                         |
|   1267 |   |   |   |   try:                                                      |
|   1268 |   |   |   |   |  c = toolz.groupby("name", stats["columns"])[column][0] |
|   1269 |   |   |   |   |  min = c["min"]                                         |
|   1270 |   |   |   |   |  max = c["max"]                                         |
|   1271 |   |   |   |   except KeyError:                                          |
│   1272 │   │   │   │   │   out_parts.append(part)                                │
│   1273 │   │   │   │   │   out_statistics.append(stats)                          │
│   1274 │   │   │   │   else:                                                     │
│ ❱ 1275 │   │   │   │   │   if (                                                  │
│   1276 │   │   │   │   │   │   operator in ("==", "=")                           │
│   1277 │   │   │   │   │   │   and min <= value <= max                           │
│   1278 │   │   │   │   │   │   or operator == "!="                               │
╰──────────────────────────────────────────────────────────────────────────────────╯
TypeError: '<=' not supported between instances of 'NoneType' and 'str'
```
When debugging, I noticed that the `min` and `max` values (which shadow the builtins, by the way) are computed by `toolz.groupby(...)` to be `None`.
  
It seems that `read_parquet` tries to compute `min` and `max` values for my `str` value that I wish to filter on, but I'm not sure that makes sense in this case. Even so, `str` values should be comparable (though it might not make a huge amount of sense in this case, seeing how the `itemId` is a random UUID).

Still, I expected this to work although perhaps not be very performant. What am I doing wrong?

**Minimal Complete Verifiable Example**:

Since this is a c+p from a prior [StackOverflow](https://stackoverflow.com/questions/74478839/trying-to-filter-in-dask-read-parquet-tries-to-compare-nonetype-and-str?noredirect=1#comment132026379_74478839) post, I currently don't have the means to reproduce this since it was part of a Kedro dataset, but I'll try to attach a MCVE in the coming days.

**Anything else we need to know?**:

**Environment**:

- Dask version: `2022.10.2`
- Python version: `Python 3.10.6`
- Operating System: `Ubuntu 22.04.1 LTS`
- Install method (conda, pip, source): `pip 22.3.1`

**Comment by jrbourbeau** [comment] 2022-12-15 18:46
Thanks for opening an issue @filpano. I think a minimal reproducer here would be helpful. Here's a small example snippet that is (I think) similar to what you're describing:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({"x": range(10), "y": list("aabbccddee")})
ddf = dd.from_pandas(df, npartitions=5)
ddf.to_parquet("test.parquet", engine="pyarrow", partition_on="x")
ddf = dd.read_parquet("test.parquet", engine="pyarrow", filters=[("y", "==", "c")])
print(ddf.compute())
```

When I run with the latest `dask` release I'm not able to reproduce an error. 

This may differ from what you're actually doing though. If you can provide a reproducer, that would go a long way towards helping debug. 

Also cc @rjzamora who may know more

**Comment by aywandji** [comment] 2022-12-16 21:54
@jrbourbeau I had the same issue. Below is a snippet to reproduce the error. First we create 3 dataframe parquet files with the same columns (`name`, `number`). One of them (`number_name.parquet`) will have the columns in reversed order.

```python
pd.DataFrame(data={"name": ["a", "b"], "number":[0, 1]}).to_parquet("name_number.parquet")

pd.DataFrame(data={"number":[0, 1], "name": ["a", "b"]}).to_parquet("number_name.parquet")

pd.DataFrame(data={"name": ["a", "b"], "number":[1, 0]}).to_parquet("name_number_2.parquet")
```

When reading the files with the same columns order using `filters` everything went as expected:
```python
# No error
dd.read_parquet(["name_number.parquet", 'name_number_2.parquet'], filters=[("number", "==", 1)]).compute()
```

But when reading 2 parquet files with same columns but different order, we get the error:

```python
dd.read_parquet(["name_number.parquet", 'number_name.parquet'], filters=[("number", "==", 1)]).compute()
```
```
File /opt/conda/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py:1275, in apply_filters.<locals>.apply_conjunction(parts, statistics, conjunction)
   1273     out_statistics.append(stats)
   1274 else:
-> 1275     if (
   1276         operator in ("==", "=")
   1277         and min <= value <= max
   1278         or operator == "!="
   1279         and (min != value or max != value)
   1280         or operator == "<"
   1281         and min < value
   1282         or operator == "<="
   1283         and min <= value
   1284         or operator == ">"
   1285         and max > value
   1286         or operator == ">="
   1287         and max >= value
   1288         or operator == "in"
   1289         and any(min <= item <= max for item in value)
   1290     ):
   1291         out_parts.append(part)
   1292         out_statistics.append(stats)

TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

After some investigations, It looks like the column `number` doesn't have the same position in `pyarrow.dataset.schema` [here](https://github.com/dask/dask/blob/dcc77771c3bbd0f101945684aaa0b31e62cf9ace/dask/dataframe/io/parquet/arrow.py#L1224)  and in `row_group.metadata.column(i)` [here](https://github.com/dask/dask/blob/dcc77771c3bbd0f101945684aaa0b31e62cf9ace/dask/dataframe/io/parquet/arrow.py#L288). I think maybe you should use the column's name instead of its indice when getting column stats [here](https://github.com/dask/dask/blob/dcc77771c3bbd0f101945684aaa0b31e62cf9ace/dask/dataframe/io/parquet/arrow.py#L288).

**Comment by jrbourbeau** [comment] 2022-12-16 22:30
Ah, I see. Thanks for the nice reproducer @aywandji! Is this something you're interested in submitting a PR for? (no obligation though)

**Comment by jrbourbeau** [comment] 2023-01-19 18:09
Closed via https://github.com/dask/dask/pull/9772

**Closed by jrbourbeau** 2023-01-19 18:09 UTC
Labels: dataframe, parquet, needs attention
