### ISSUE TITLE
Creating a new index fails on the dask dataframe that has np.NaN division.

### ISSUE THREAD

**Issue by bkyryliuk** [dask/dask#2451] opened 2017-06-13 02:39 UTC
Dupe of the https://github.com/dask/dask/issues/2408.
Could not reopen that one.

Repro:
```
import pandas as pd
import numpy as np
from dask import dataframe as dd
df = pd.DataFrame({'a':range(10)}); df['b'] = df['a'] % 3; df['c'] = df['b'].astype(str)
ddf = dd.from_pandas(df, npartitions=3)
ddf.set_index('c', divisions=[1, 2, np.NaN]).compute()
```

**Comment by TomAugspurger** [comment] 2017-06-15 12:08
Sorry for not seeing this earlier.

I don't think this code is expected to work. `divisions` should be a tuple containing the same types as the values. I also suspect that having `NaN` as a division could cause problems, though it's not explicitly checked.

**Comment by bkyryliuk** [comment] 2017-06-15 17:15
@TomAugspurger thanks for the answer. The index is purely strings, but dask somehow gets np.NaN into the beginning and the end of divisions. I'll try to get a datadump and reproduce it locally some time this week,

**Comment by TomAugspurger** [comment] 2017-06-15 18:10
Yeah, that's possible, since pandas uses `np.nan` as a missing value for strings too. Let me know if you're able to reproduce it without the `divisions=` argument.

**Comment by mrocklin** [comment] 2018-10-23 22:54
Closing due to a lack of a reproducible example.

**Closed by mrocklin** 2018-10-23 22:54 UTC
