### ISSUE TITLE
`da.to_hdf5` fails when distributed client is registered

### ISSUE THREAD

**Issue by m-albert** [dask/dask#6522] opened 2020-08-17 10:25 UTC
**What happened**:

`da.to_hdf5` fails when a distributed client is registered. Error message:

> TypeError: h5py objects cannot be pickled

**What you expected to happen**:

That `da.to_hdf5` works regardless. In my understanding, this would involve making sure that `compute` calls either the "single-threaded" or "threads" dask schedulers (as opposed to using a distributed client).

**Minimal Complete Verifiable Example**:

```python
# these two lines need to be
# commented out for `.to_hdf5` to work
from distributed import Client
client = Client()

from dask import array as da
x = da.ones(5)
x.to_hdf5('/tmp/delme.h5','x')
```

**Anything else we need to know?**:

Suggestion to improve behaviour / usability:

Modify the call to `store` within `to_hdf5`, which currently is hardcoded regarding the scheduler used for its downstream `compute`.
https://github.com/dask/dask/blob/66c1ae2d7437de33657fff5aa66c4badaf1b7e43/dask/array/core.py#L4485

E.g. it could be useful to add sth like `**compute_kwargs` to the `to_hdf5` function call. The current `**kwargs` are only used for hdf5 dataset creation.

https://github.com/dask/dask/blob/66c1ae2d7437de33657fff5aa66c4badaf1b7e43/dask/array/core.py#L4438

**Environment**:

- Dask version: 2.20
- Python version: 3.8
- Operating System: MacOS
- Install method (conda, pip, source): conda

**Comment by m-albert** [comment] 2020-08-17 12:06
If `to_hdf5` (at least currently) shouldn't compute in a distributed setting, it could make sense to set the default scheduler to either 'single-threaded' or 'threads', with or without `**compute_kwargs`.

**Comment by jrbourbeau** [comment] 2020-08-17 22:51
Thanks for raising an issue @m-albert and providing a nice minimal example! I'm able to reproduce the pickling error.

This issue has come up in a few other issues (e.g. https://github.com/dask/dask/issues/2488, https://github.com/dask/dask/issues/3074, and https://github.com/dask/dask/issues/3351). To avoid having multiple issues on the same topic, I'm going to close this as a duplicate of https://github.com/dask/dask/issues/2488. If you're interested, you might consider reading through some of the linked issues for context on previous discussions that have happened around this topic and continue the conversation over in https://github.com/dask/dask/issues/2488

Currently, there are potential workarounds:

- Use a local scheduler
- Consider using [Zarr](https://zarr.readthedocs.io/en/stable/) which avoids some of the pickling issues Dask runs into (Dask arrays have a `.to_zarr` method)

Alternatively if you wanted to open a PR with a proposed fix, that would also be appreciated

**Closed by jrbourbeau** 2020-08-17 22:51 UTC
