### ISSUE TITLE
actually slowing down the function 

### ISSUE THREAD

**Issue by isaac-you** [dask/dask#5044] opened 2019-07-02 03:44 UTC
```
import pandas as pd
import numpy as np
input_params = pd.DataFrame(np.random.random(size=(500, 4)),
                            columns=['param_a', 'param_b', 'param_c', 'param_d'])

def func1(x):
    y = x ** 2
    z = np.sin(1/(1+np.exp(-y)))
    return sum(z)

def func2(inputM):
    n = inputM.shape[0]
    results = []
    for i in range(n):
        results.append(func1(inputM.values[i]))
    return results

def func3(inputM):
    n = inputM.shape[0]
    resultD = []
    for i in range(n):
        result_i = dask.delayed(func1)(inputM.values[i])
        resultD.append(result_i)
    return dask.compute(*resultD)
```

```
%timeit func2(input_params)
5.62 ms ± 286 µs per loop
%timeit func3(input_params)
75 ms ± 2.96 ms per loop
```

```
dask.__version__
'0.17.5'
python: 3.6
```

Why the func3 is so slow after using delayed approach? How can I fix the problem

**Comment by jrbourbeau** [comment] 2019-07-02 04:09
Thanks for the reproducible example @isaac-you. From the [Dask delayed best practices documentation](https://docs.dask.org/en/stable/delayed-best-practices.html#avoid-too-many-tasks), every `delayed` task has an overhead of a few hundred microseconds. In your example, there are 500 delayed tasks in `func3`. The associated `delayed` overhead seems to be able to account for the difference in timing of `func2` and `func3`

**Comment by isaac-you** [comment] 2019-07-02 05:29
@jrbourbeau 
Thank you for the reply. So if the single delayed task take a long enough time, the advantage of dask can finally  show up ? 
Am I right ?

**Comment by TomAugspurger** [comment] 2019-07-02 12:24
Correct.

**Comment by TomAugspurger** [comment] 2019-07-02 13:57
Anything else to do here @isaac-you?

**Comment by isaac-you** [comment] 2019-07-03 01:30
according to  'Dask delayed best practices documentation'     break up  many tasks into batches can speed up.  But there is no complete example. I don't know what to do next.

```
import dask.bag as db
b = db.from_sequence(1000000000, npartitions=1000)
b = b.map(f)
...
```

**Comment by TomAugspurger** [comment] 2019-07-03 02:01
I don't understand your example. Typically you don't mix dask.bag and
dask.delayed (though I don't see dask.delayed in your example)

**Comment by mrocklin** [comment] 2019-07-03 06:59
Perhaps you're looking for the Dask Bag documentation here:
https://docs.dask.org/en/latest/bag.html ?

**Comment by isaac-you** [comment] 2019-07-03 08:55
I mean too many delayed tasks, we can use batch to speed up.
' In this case, it’s often best to break up your many tasks into batches or use one of the Dask collections to help you.' this is from the 'best practise'  [https://docs.dask.org/en/latest/delayed-best-practices.html#avoid-repeatedly-putting-large-inputs-into-delayed-calls](url)

but the example is not complete, I don't know how to finish the code

**Comment by isaac-you** [comment] 2019-07-03 08:57
I mean too many delayed tasks, we can use batch to speed up.
' In this case, it’s often best to break up your many tasks into batches or use one of the Dask collections to help you.' this is from the 'best practise'

[https://docs.dask.org/en/latest/delayed-best-practices.html#avoid-too-many-tasks](url)

but the example is not complete, I don't know how to finish the code

**Comment by mrocklin** [comment] 2019-07-03 10:35
That just recommends that you consider using dask bag.  How you choose to use dask bag is up to you.

**Comment by jrbourbeau** [comment] 2019-07-10 14:33
Closing as the posted question seems to have been answered (there is some overhead associated with `dask.delayed`). @isaac-you feel free to re-open if this is not the case.

**Closed by jrbourbeau** 2019-07-10 14:33 UTC
