### ISSUE TITLE
Dask dataframe read_hdf raises TypeError

### ISSUE THREAD

**Issue by martijnende** [dask/dask#7333] opened 2021-03-08 09:41 UTC
**What happened**:

While reading an HDF5 file into a `dask.dataframe`, the following `TypeError` is raised:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-01a6622cf4bf> in <module>
----> 1 df = dd.read_hdf("test.h5", "/random")

~/anaconda3/envs/py38/lib/python3.8/site-packages/dask/dataframe/io/hdf.py in read_hdf(pattern, key, start, stop, columns, chunksize, sorted_index, lock, mode)
    514 
    515     return concat(
--> 516         [
    517             _read_single_hdf(
    518                 path,

~/anaconda3/envs/py38/lib/python3.8/site-packages/dask/dataframe/io/hdf.py in <listcomp>(.0)
    515     return concat(
    516         [
--> 517             _read_single_hdf(
    518                 path,
    519                 key,

~/anaconda3/envs/py38/lib/python3.8/site-packages/dask/dataframe/io/hdf.py in _read_single_hdf(path, key, start, stop, columns, chunksize, sorted_index, lock, mode)
    384         return new_dd_object(dsk, name, empty, divisions)
    385 
--> 386     keys, stops, divisions = get_keys_stops_divisions(
    387         path, key, stop, sorted_index, chunksize
    388     )

~/anaconda3/envs/py38/lib/python3.8/site-packages/dask/dataframe/io/hdf.py in get_keys_stops_divisions(path, key, stop, sorted_index, chunksize)
    315             divisions = []
    316             for k in keys:
--> 317                 storer = hdf.get_storer(k)
    318                 if storer.format_type != "table":
    319                     raise TypeError(dont_use_fixed_error_message)

~/anaconda3/envs/py38/lib/python3.8/site-packages/pandas/io/pytables.py in get_storer(self, key)
   1504             raise KeyError(f"No object named {key} in the file")
   1505 
-> 1506         s = self._create_storer(group)
   1507         s.infer_axes()
   1508         return s

~/anaconda3/envs/py38/lib/python3.8/site-packages/pandas/io/pytables.py in _create_storer(self, group, format, value, encoding, errors)
   1660                     tt = "generic_table"
   1661                 else:
-> 1662                     raise TypeError(
   1663                         "cannot create a storer if the object is not existing "
   1664                         "nor a value are passed"

TypeError: cannot create a storer if the object is not existing nor a value are passed
```

**What you expected to happen**:

I expected a Dask dataframe to be created, similar to reading the data with `h5py`

**Minimal Complete Verifiable Example**:

```python
# Importing stuff
import dask.dataframe as dd
import h5py
import numpy as np

# Create dummy data
data = np.random.rand(100, 100)

# Write data to HDF5
with h5py.File("test.h5", "w") as f:
    f.create_dataset("random", data=data)

# Read data from HDF5
with h5py.File("test.h5", "r") as f:
    data_read = f["random"][...]
   
# Check data is correct
np.allclose(data, data_read)

# Attempt to read same data with `read_hdf`:
df = dd.read_hdf("test.h5", "/random")
```

**Environment**:

- Dask version: `'2021.03.0'`
- Python version: `3.8.6`
- Operating System: `Linux Mint 19`
- Install method (conda, pip, source): `conda (4.9.2)`

**Comment by jsignell** [comment] 2021-03-08 16:47
This seems like a pandas bug or improper usage. It's not clear to me which, but you get the same error if you do: `pd.read_hdf("test.h5", "/random")`

**Comment by martijnende** [comment] 2021-03-09 07:23
Yes, you're right. I do get the same error with `pd.read_hdf`. I'll open an issue on their repo

**Comment by martijnende** [comment] 2021-03-09 12:53
**Update**: apparently [this is a known issue](https://github.com/pandas-dev/pandas/issues/9539) with Pandas. Data stored with `h5py` are incompatible with `pandas.DataFrame`. The solution that is offered is to convert the container using [Odo](https://github.com/blaze/odo). 

Given the prevalence of the HDF5 format for storing large datasets, it would be a useful to the _clientele_ of Dask to have direct access to tools like Odo that ensure compatibility of their data with Dask. Would this be an option?

**Comment by jrbourbeau** [comment] 2021-03-09 15:25
@martijnende since you're storing array data with `h5py` I recommend using Dask array (instead of Dask DataFrame) to load your data. There are examples of loading `h5py` datasets with Dask array at https://docs.dask.org/en/latest/array-creation.html. Dask arrays also have a `.to_dask_dataframe()` method if the DataFrame API is needed for your particular use case

**Comment by jsignell** [comment] 2021-09-16 17:22
I'm going to close this since James' suggestion seems like the right approach.

**Closed by jsignell** 2021-09-16 17:22 UTC
Labels: io

**Comment by RGBYCP** [comment] 2021-09-30 08:41
Hi, I have the same problem with my hdf5 files (when reading with dask or pandas), inside are arrays. When is `read_hdf()` supposed to work, please?

**Comment by jsignell** [comment] 2021-10-01 14:37
@RGBYCP it would help to have a reproducible example. Can you alter the original example in this issue to make it like the case you are describing? Here's my understanding of the situation you are describing:

```python
# Importing stuff
import dask.array as da
import dask.dataframe as dd
import h5py
import numpy as np

# Create dummy data
data = np.random.rand(100, 100)

# Write data to HDF5
with h5py.File("test.h5", "w") as f:
    f.create_dataset("random", data=data)

f = h5py.File("test.h5", "r")
d = f["random"][:, :3]
a = da.from_array(d, chunks=(100, 3))
ddf = dd.from_array(a, columns=["a", "b", "c"])
```

**Comment by RGBYCP** [comment] 2021-10-01 14:48
Dear @jsignell 
I am very sorry. I started like this

```
import numpy as np
import h5py
import dask.dataframe as dd
import dask.array as da
import dask
print('This is dask version', dask.__version__)



ra=np.ones([3,2700,3000])

print(ra.shape)
file_list=[]
for i in range(0,4):
    #print(i)
    fstr='data_{0}.h5'.format(str(i))
    #print(fstr)
    hf = h5py.File('./'+fstr, 'w')
    hf.create_dataset('dataset_{0}'.format(str(i)), data=ra)
    hf.close()
    file_list.append(fstr)

!ls

print(file_list)

for i,fn in enumerate(file_list):
    dd.read_hdf(fn,key='dataset_{0}'.format(str(i)))  #here it breaks and I don't reach the step where to create a dataframe.


```

**Comment by jsignell** [comment] 2021-10-01 15:06
It is not common to store 2d arrays as values in a dataframe. Have you considered using xarray instead? Otherwise you could just create a dictionary of 2d arrays and reference them that way.

For the record I tried using dd.from_array but it throws an error if the data > 2D:

```python
In [2]: arrays = []
   ...: for i,fn in enumerate(file_list):
   ...:     f = h5py.File(fn, "r")
   ...:     d = f[f"dataset_{i}"][...]
   ...:     a = da.from_array(d)
   ...:     arrays.append(a)
   ...: 
   ...: dd.from_array(da.stack(arrays), columns=["a", "b", "c", "d"])
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-b2e8f93980b1> in <module>
      6     arrays.append(a)
      7 
----> 8 dd.from_array(da.stack(arrays), columns=["a", "b", "c", "d"])

~/dask/dask/dataframe/io/io.py in from_array(x, chunksize, columns, meta)
    112     """
    113     if isinstance(x, da.Array):
--> 114         return from_dask_array(x, columns=columns, meta=meta)
    115 
    116     meta = _meta_from_array(x, columns, meta=meta)

~/dask/dask/dataframe/io/io.py in from_dask_array(x, columns, index, meta)
    446     dask.dataframe._Frame.to_records: Reverse conversion
    447     """
--> 448     meta = _meta_from_array(x, columns, index, meta=meta)
    449 
    450     if x.ndim == 2 and len(x.chunks[1]) > 1:

~/dask/dask/dataframe/io/io.py in _meta_from_array(x, columns, index, meta)
     25 
     26     if x.ndim > 2:
---> 27         raise ValueError(
     28             "from_array does not input more than 2D array, got"
     29             " array with shape %r" % (x.shape,)

ValueError: from_array does not input more than 2D array, got array with shape (4, 3, 2700, 3000)

```

**Comment by RGBYCP** [comment] 2021-10-01 15:16
Hi @jsignell,
"It is not common to store 2d arrays as values in a dataframe. Have you considered using xarray instead? Otherwise you could just create a dictionary of 2d arrays and reference them that way."
Sorry, if I ask embarrassing newbie questions. I did something recently in smaller with a pandas dataframe. It gives me a nice overview about my dataset and I can store in one row further information. I thought it could be nice to do this with dask as well. So when you say, it is not common, does it mean it is such a bad idea, I should not even try it?

Re xarray: Yes. I looked briefly into it. I understand it can work with dask as well for parallelisation. I just don't know yet how to start best in this direction. I have never used this package. Also I thought the idea of having this dataframe with all my values in one location seemed a good way to keep all information together in a nice way. I have even more hdf files with complementary data for each row, i.e. more columns.

Re dict: I don't understand this suggestion. Sorry. My idea was really to have one 2d array per row. Or should I then store in one cell a dict containing the array?

Re error: Yes, I saw this too when I tried to use `from_array()`. Isn't this the expected behaviour? I think the manual states this. 
Is there a way to convert a multidim array into a dask dataframe? I believe in Pandas this is done via multiindex, but I am not 100% sure. 

Thank you for your guidance.

**Comment by jsignell** [comment] 2021-10-01 15:41
For xarray, you could do something like (there is probably a better way):

```python
In [36]: arrays = []
    ...: for i,fn in enumerate(file_list):
    ...:     f = h5py.File(fn, "r")
    ...:     d = f[f"dataset_{i}"][...]
    ...:     a = da.from_array(d)
    ...:     arrays.append(a)
    ...: arr = xr.DataArray(da.stack(arrays))
    ...: ds = arr.to_dataset(dim="dim_0")
    ...: ds
Out[36]: 
<xarray.Dataset>
Dimensions:  (dim_1: 3, dim_2: 2700, dim_3: 3000)
Dimensions without coordinates: dim_1, dim_2, dim_3
Data variables:
    0        (dim_1, dim_2, dim_3) float64 dask.array<chunksize=(3, 1350, 1500), meta=np.ndarray>
    1        (dim_1, dim_2, dim_3) float64 dask.array<chunksize=(3, 1350, 1500), meta=np.ndarray>
    2        (dim_1, dim_2, dim_3) float64 dask.array<chunksize=(3, 1350, 1500), meta=np.ndarray>
    3        (dim_1, dim_2, dim_3) float64 dask.array<chunksize=(3, 1350, 1500), meta=np.ndarray>

```

Re dict, I just meant you might be ok with something simpler. Just a regular python dictionary where each item is a dask array.

Re error, yeah it's expected.

`read_hdf()` should work wherever `pd.read_hdf()` works.
