### ISSUE TITLE
Add NumPy pad

### ISSUE THREAD

**Issue by jakirkham** [dask/dask#2415] opened 2017-06-05 18:41 UTC
Would be nice to have NumPy's [`pad`]( https://docs.scipy.org/doc/numpy-1.12.0/reference/generated/numpy.pad.html ) implemented for Dask Arrays. May also help clean up some other code by having this exposed as part of the API.

**Comment by mrocklin** [comment] 2017-06-05 18:48
Presumably this would help with map_overlap?

**Comment by jcrist** [comment] 2017-06-05 20:32
Possible duplicate of #1926.

**Comment by jakirkham** [comment] 2018-01-22 07:12
Thinking on this one a bit more, the best approach IMHO is to manipulate the Dask graph directly.

Meaning inserting calls to `np.pad` on all edge chunks with parameters and updating the edge chunk sizes accordingly. This should avoid trying to implement to many details of `np.pad` in Dask while still providing maximal benefit of `np.pad`'s features. Also it should avoid needless operations on non-edge chunks.

There is one caveat though. If the parameters of `np.pad` end up requiring information outside of a chunk, we may need to error, warn/rechunk, or do something else.

**Comment by mrocklin** [comment] 2018-01-22 13:13
When you say inserting calls do you mean mutating the existing task graph?
If so then that seems somewhat dangerous to me.  Mutation in that way is
rare.

**Comment by jakirkham** [comment] 2018-01-23 00:49
Would be building a new Dask graph (so the input one would be unchanged), just adding selective functions calls to `np.pad` on the boundaries. Probably with some tweaks to the user provided parameters to handle padding only some sides of chunks. Similar to the current `triu`/`tril` implementations. This [code snippet]( https://github.com/dask/dask/blob/64420cb6c8450b3f328f2ac631804c418c8df2d4/dask/array/creation.py#L527-L532 ) should be illustrative.

**Comment by mrocklin** [comment] 2018-01-23 01:17
Ah, yeah sorry.  I have no objection to mutating task graphs while creating
them, just so long as we don't mutate the graphs of existing collections.

**Comment by jakirkham** [comment] 2018-04-25 21:06
OTOH maybe we could just re-present `ghost` under the `numpy.pad` API. We don't support every option that `numpy.pad` does, but maybe what we provide is already good enough for common use cases. That should allow us to get some feedback on these internals. It would also allow improvements to `ghost` to be captured by `map_overlap` pretty easily.

**Comment by jakirkham** [comment] 2018-06-13 04:51
Have an implementation of `pad` for Dask Arrays in PR ( https://github.com/dask/dask/pull/3578 ). Feedback welcome.

**Closed** 2018-06-16 17:42 UTC
Labels: array
