### ISSUE TITLE
Coverage check is failing

### ISSUE THREAD

**Issue by jrbourbeau** [dask/dask#10165] opened 2023-04-10 21:35 UTC
I've noticed our codecov check, both on PRs and on `main`, has started failing recently. Coverage is currently being reported as 41.96%, which seems off (way too low). 

When I click of the coverage check for this recent commit to `main` https://github.com/dask/dask/commit/2c8296c80ec436cc8a7fef98a2832a9032b287ff, I get taken [here](https://app.codecov.io/gh/dask/dask/commit/2c8296c80ec436cc8a7fef98a2832a9032b287ff), where I see a 

```
Commit YAML is invalid

Coverage data is unable to be displayed, as the commit YAML appears to be invalid.
```

warning. @charlesbluca @j-bennet, is this something either of you have bandwidth to look into?

**Comment by phofl** [comment] 2023-04-13 09:28
So looks our yaml file is invalid, this can be checked with

```
curl -X POST --data-binary @codecov.yml https://codecov.io/validate
```

The ``after_n_builds`` config seems to be in the wrong group, but moving it up or completely removing it did not solve the codecov problems, we are still only "testing" 40% of our code according to codecov

**Comment by jrbourbeau** [comment] 2023-04-13 17:14
cc @graingert for visibility

**Comment by graingert** [comment] 2023-04-19 14:11
I confirmed this with `git bisect` to be 1a1885943b42496686dfb1454b307dbec9e29cad

**Closed** 2023-04-19 15:39 UTC
Labels: tests
