### ISSUE TITLE
Cumsum in dask.dataframe does not work with empty partitions

### ISSUE THREAD

**Issue by morganics** [dask/dask#3004] opened 2017-12-15 12:15 UTC
The following errors out with ```IndexError: index 0 is out of bounds for axis 0 with size 0```.

Version of dask is 0.15.3, on Windows 7.

```
import dask.dataframe
import pandas as pd

something = [{'item1': 'value1', 'item2': 'value2', 'item3': 'value3'},
             {'item1': 'value1', 'item2': 'value2', 'item3': 'value3'}]

something_df = pd.DataFrame(something)
empty_df = pd.DataFrame.from_items([
                        (name, pd.Series(data=None, dtype=series.dtype))
                            for name, series in something_df.head(1).iteritems()])

def read(rows):
    return pd.DataFrame(rows)

def nothing():
    return empty_df

ddf = dask.dataframe.from_delayed([dask.delayed(read)(something) for _ in range(5)] + [dask.delayed(nothing)() for _ in range(5)])
ddf['cs'] = 1
ddf['cs'] = ddf.cs.cumsum()

print(ddf.compute())

```

**Comment by mrocklin** [comment] 2017-12-15 15:06
Reproduced on master.  Thanks for the excellent bug report!

**Comment by mrocklin** [comment] 2017-12-15 15:32
So here is the relevant function

```python
    def _cum_agg(self, token, chunk, aggregate, axis, skipna=True,
                 chunk_kwargs=None):
        """ Wrapper for cumulative operation """

        axis = self._validate_axis(axis)

        if axis == 1:
            name = '{0}{1}(axis=1)'.format(self._token_prefix, token)
            return self.map_partitions(chunk, token=name, **chunk_kwargs)
        else:
            # cumulate each partitions
            name1 = '{0}{1}-map'.format(self._token_prefix, token)
            cumpart = map_partitions(chunk, self, token=name1, meta=self,
                                     **chunk_kwargs)

            name2 = '{0}{1}-take-last'.format(self._token_prefix, token)
            cumlast = map_partitions(_take_last, cumpart, skipna,
                                     meta=pd.Series([]), token=name2)

            name = '{0}{1}'.format(self._token_prefix, token)
            cname = '{0}{1}-cum-last'.format(self._token_prefix, token)

            # aggregate cumulated partisions and its previous last element
            dask = {}
            dask[(name, 0)] = (cumpart._name, 0)

            for i in range(1, self.npartitions):
                # store each cumulative step to graph to reduce computation
                if i == 1:
                    dask[(cname, i)] = (cumlast._name, i - 1)
                else:
                    # aggregate with previous cumulation results
                    dask[(cname, i)] = (aggregate, (cname, i - 1),
                                        (cumlast._name, i - 1))
                dask[(name, i)] = (aggregate, (cumpart._name, i), (cname, i))
            return new_dd_object(merge(dask, cumpart.dask, cumlast.dask),
                                 name, chunk(self._meta), self.divisions)
```

I'm a little surprised that we compute `_take_last` after the `map_partitions(chunk, ...)` step rather than as part of the aggregation in the for loop below.  @sinhrks do you have any thoughts on this?

**Comment by morganics** [comment] 2018-10-13 22:13
As posted on stackoverflow, this method works nicely;

    def cull_empty_partitions(df):
        ll = list(df.map_partitions(len).compute())
        df_delayed = df.to_delayed()
        df_delayed_new = list()
        pempty = None
        for ix, n in enumerate(ll):
            if 0 == n:
                pempty = df.get_partition(ix)
            else:
                df_delayed_new.append(df_delayed[ix])
        if pempty is not None:
            df = dd.from_delayed(df_delayed_new, meta=pempty)
        return df

**Comment by TomAugspurger** [comment] 2020-09-11 15:03
Seems to be fixed now.

```python

In [59]: ddf = dd.from_pandas(pd.DataFrame({"A": pd.array([], dtype="int64")}), 2)

In [60]: ddf.A.cumsum().compute()
Out[60]: Series([], Name: A, dtype: int64)

```

**Closed by TomAugspurger** 2020-09-11 15:03 UTC
Labels: dataframe
