### ISSUE TITLE
convert code python multiprocessing into dask.multiprocessing ( The issue is that pool is not working error in dask multiprocessing)

### ISSUE THREAD

**Issue by mukulguptadsa** [dask/dask#6126] opened 2020-04-23 06:04 UTC
%%time
X_enhanced = npv_calculation_dataframe
for j in X_enhanced['pred'].unique():
    Xn = X_enhanced[X_enhanced['pred']==j]

    import time
    start = time.time()

    import multiprocessing
    df = Xn.copy()
    num_processes = multiprocessing.cpu_count()
    chunk_size = int(df.shape[0]/num_processes)
    chunks = [df.iloc[i:i + chunk_size] for i in range(0, df.shape[0], chunk_size)]
    cashflow_net_roeb_list = ['cashflow_net_roeb_m' + str(i) for i in range(1,25)]
    risk_adjusted_list = ['risk_adjusted_margin_m' + str(i) for i in range(1,25)]
    cost_function_list = ['cost_function_m' + str(i) for i in range(1,25)]
    cash_provisioning_list = ['cashprovisioning_m' + str(i) for i in range(1,25)]
    def func(d):
    
        d[cashflow_net_roeb_list + risk_adjusted_list +  cost_function_list + cash_provisioning_list] = \
        d.apply(lambda row: limit_bet_1_max_trans(row), axis = 1, result_type="expand")
        return d
       
    pool = multiprocessing.Pool(processes=num_processes)

    
    result = pool.map(func, chunks)
    new_df = pd.DataFrame()
    for i in range(len(result)):
        new_df = pd.concat([new_df, result[i]], axis = 0)
    new_df.to_csv('1imit_updated_min_7k_uncat_segment_'+str(j)+'.csv')
    end = time.time()
    print(end - start)

**Comment by mukulguptadsa** [comment] 2020-04-23 06:18
after python code, I will convert into dask.multiprocessing  code 
X_enhanced = npv_calculation_dataframe
for j in X_enhanced['pred'].unique():
    Xn = X_enhanced[X_enhanced['pred']==j]

    import time
    start = time.time()

    import dask.multiprocessing
    dask.config.set(scheduler='processes')
    df = Xn.copy()

    num_processes = dask.multiprocessing.CPU_COUNT
    shape=df.shape[0].compute()
    chunk_size = int(shape/num_processes)
    print(chunk_size)
    chunks = [df.iloc[:,:i + chunk_size] for i in range(0, shape, chunk_size)]
    cashflow_net_roeb_list = ['cashflow_net_roeb_m' + str(i) for i in range(1,25)]
    risk_adjusted_list = ['risk_adjusted_margin_m' + str(i) for i in range(1,25)]
    cost_function_list = ['cost_function_m' + str(i) for i in range(1,25)]
    cash_provisioning_list = ['cashprovisioning_m' + str(i) for i in range(1,25)]
    def func(d):
        d[cashflow_net_roeb_list + risk_adjusted_list +  cost_function_list + cash_provisioning_list] = \
        d.apply(lambda row: limit_bet_1_max_trans(row), axis = 1, result_type="expand")
        return d
       
    pool = dask.multiprocessing.get(processes=num_processes)
    print(pool)
    
    result = pool.map(func, chunks)
    new_df = pd.DataFrame()
    for i in range(len(result)):
        new_df = pd.concat([new_df, result[i]], axis = 0)
    new_df.to_csv('1imit_updated_min_7k_uncat_segment_'+str(j)+'.csv')
    end = time.time()
    print(end - start)

# error 
---------------------------------------------------------------------------
error is pool is not working in dask

**Comment by TomAugspurger** [comment] 2020-04-23 11:44
Can you provide a minimal example? http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Also, it seems like you think that `dask.multiprocessing.get` is a drop-in replacement for `multiprocessing.Pool`. It's not. Did you see something in the documentation that made you think it is?

**Comment by jrbourbeau** [comment] 2020-04-30 21:14
Closing for now due to lack of a [reproducible example](https://blog.dask.org/2018/02/28/minimal-bug-reports). Happy to re-open if you can provide a minimal code snippet we can run @mukulguptadsa

**Closed by jrbourbeau** 2020-04-30 21:14 UTC
