### ISSUE TITLE
Unstable dask causes unexpected compute results from xarray

### ISSUE THREAD

**Issue by djhoese** [dask/dask#7263] opened 2021-02-23 17:18 UTC
**What happened**:

See https://github.com/pydata/xarray/issues/4934 for details. Some change in dask master branch seems to be causing an internal xarray array wrapper to be returned instead of a numpy array.

**What you expected to happen**:
A numpy array to be returned by .compute().

**Minimal Complete Verifiable Example**:

```python
from PIL import Image
import xarray as xr
import numpy as np

# create a test image
Image.fromarray(np.zeros((5, 5, 3), dtype=np.uint8)).save('test.png')
r = xr.open_rasterio('test.png', chunks='auto')
print(r.data.compute())
# ImplicitToExplicitIndexingAdapter(array=CopyOnWriteArray(array=LazilyOuterIndexedArray(array=<xarray.backends.rasterio_.RasterioArrayWrapper object at 0x7f25e72bcc10>, key=BasicIndexer((slice(0, 2, 1), slice(0, 100, 1), slice(0, 100, 1))))))
```

**Anything else we need to know?**:
This was originally discovered in a CI environment with unstable dependencies installed (ex. numpy, xarray, dask, and rasterio), but seems to be tied to dask. Reverting dask versions to latest release fixes it.

**Environment**:

- Dask version: ad01acc14088d03127dfec4f881cce959f3ac4d9
- Python version:
- Operating System:
- Install method (conda, pip, source):

**Comment by jrbourbeau** [comment] 2021-02-23 17:52
Thanks for surfacing this @djhoese! Running your example against recent commits to Dask, the change from returning a NumPy array to a `ImplicitToExplicitIndexingAdapter` happened after https://github.com/dask/dask/pull/6738 was merged (cc @pentschev). 

> This was originally discovered in a CI environment with unstable dependencies installed

Woo, hooray for running CI against upstream 🎉

**Comment by pentschev** [comment] 2021-02-23 20:51
That is because starting from https://github.com/dask/dask/pull/6738 we moved from forcing a conversion to NumPy for objects that satisfy the [`is_arraylike`](https://github.com/dask/dask/blob/adb58fa7949eb673d49c45a7215e19deaaa34217/dask/utils.py#L1111-L1133) condition to just working on those arrays in its natural type. An easy way to modify that would be to add something to `is_arraylike` that would invalidate that condition for `ImplicitToExplicitIndexingAdapter`. Do you know of the existence of any such feature that we could use to invalidate `is_arraylike` in that situation that wouldn't be likely to affect other array-like objects @djhoese ?

**Comment by pentschev** [comment] 2021-02-23 21:03
Maybe `and not hasattr(indexer_cls)`? I'm not sure if that attribute could cause issues elsewhere though.

**Comment by djhoese** [comment] 2021-02-23 21:57
I know nothing about this internal xarray class (not an xarray dev). CC @jhamman @shoyer @rabernat

**Comment by mrocklin** [comment] 2021-02-25 17:31
It might be possible for Xarray to take control here by implementing the `__dask_postcompute__` protocol.

https://docs.dask.org/en/latest/custom-collections.html#__dask_postcompute__

**Comment by shoyer** [comment] 2021-02-25 17:55
> That is because starting from #6738 we moved from forcing a conversion to NumPy for objects that satisfy the [`is_arraylike`](https://github.com/dask/dask/blob/adb58fa7949eb673d49c45a7215e19deaaa34217/dask/utils.py#L1111-L1133) condition to just working on those arrays in its natural type. An easy way to modify that would be to add something to `is_arraylike` that would invalidate that condition for `ImplicitToExplicitIndexingAdapter`. Do you know of the existence of any such feature that we could use to invalidate `is_arraylike` in that situation that wouldn't be likely to affect other array-like objects @djhoese ?

The problem is that there are at least two means for "array like" objects that are used with Dask:

1. "Duck arrays": these arrays (numpy, sparse, cupy, etc) implement `__array_ufunc__` and `__array_function__` and can be used for computing inside Dask.
2. "Input arrays": these arrays (h5py, netCDF4, ImplicitToExplicitIndexingAdapter) implement indexing operations and `__array__` (for conversion into NumPy), but aren't suitable for computation. Note that "objects that implement `__array__`" is closer to NumPy's traditional definition of "array like."

My inclination is that only true "duck arrays" should be returned from `compute()` -- at least that's how dask has worked in the past. So that would mean objects that implement `__array_function__`.

**Comment by pentschev** [comment] 2021-02-26 13:31
> My inclination is that only true "duck arrays" should be returned from `compute()` -- at least that's how dask has worked in the past. So that would mean objects that implement `__array_function__`.

That sounds reasonable to me, but I'm concerned with whether this could cause issues with libraries that don't implement `__array_function__`, such as PyTorch. Does anybody have any insight on such cases?

**Comment by shoyer** [comment] 2021-02-26 17:57
> That sounds reasonable to me, but I'm concerned with whether this could cause issues with libraries that don't implement `__array_function__`, such as PyTorch. Does anybody have any insight on such cases?

I suspect putting a PyTorch tensor into dask currently results in undefined behavior? Or perhaps the tensors get converted into NumPy arrays?

**Comment by pentschev** [comment] 2021-02-26 23:30
> I suspect putting a PyTorch tensor into dask currently results in undefined behavior? Or perhaps the tensors get converted into NumPy arrays?

I have no idea, but it seems like [dask-pytorch-ddp](https://pypi.org/project/dask-pytorch-ddp/) is leveraging Dask somehow. It's not immediately clear to me how it's handled internally, I would need to have a better look at it. But PyTorch was one example, I'm not very familiar with other libraries that potentially use Dask and are not implementing `__array_function__`, whether the change you proposed would impose any drawbacks then. If nobody produces objections to handling it that way, we might as well try it out.

**Comment by jsignell** [comment] 2021-03-04 14:58
I am not sure if `dask-pytorch-ddp` would be affected, but @skirmer or @hhuuggoo would know.

**Comment by jakirkham** [comment] 2021-03-05 17:20
Should we close now that PR ( https://github.com/dask/dask/pull/7321 ) is merged or is there more to do here?

**Comment by jrbourbeau** [comment] 2021-03-05 17:23
This is good to close now, thanks for following up @jakirkham. And thank @djhoese for surfacing this issue to begin with!

**Closed by jrbourbeau** 2021-03-05 17:23 UTC
Labels: array

**Comment by djhoese** [comment] 2021-03-06 17:24
Can confirm unstable CI environments are passing again. Thanks everyone!
