### ISSUE TITLE
pure delayed gives wrong result for dataclass methods

### ISSUE THREAD

**Issue by kdebrab** [dask/dask#8376] opened 2021-11-12 06:19 UTC
**What happened**:

```python

from dask import delayed
from dataclasses import dataclass, field


@dataclass(frozen=True)
class A:
    param: float = field(repr=False)

    def get_param(self):
        return self.param

    def get_delayed_param(self, *args, **kwargs):
        return delayed(self.get_param, pure=True)(*args, **kwargs)

(A(1).get_delayed_param() - A(0).get_delayed_param()).compute()
Out[2]: 0
```
This is an incorrect result.

Apparently, `A(1).get_delayed_param().key` is erratically the same as `A(0).get_delayed_param().key`. It seems like the tokenize fails and falls back on something that gives the same result for both as `str(A(1)) == str(A(0))`.

**What you expected to happen**:
The correct result is obtained without delayed:
```python
A(1).get_param() - A(0).get_param()
Out[3]: 1
```

One also gets the correct result when **not** using dataclasses

```python

class B:

    def __init__(self, param):
        self.param = param

    def __repr__(self):
        return 'B()'

    def get_param(self):
        return self.param

    def get_delayed_param(self, *args, **kwargs):
        return delayed(self.get_param, pure=True)(*args, **kwargs)

(B(1).get_delayed_param() - B(0).get_delayed_param()).compute()
Out[4]: 1
```
Here, we get the correct result even though `str(B(1)) == str(B(0))`.

**Environment**:

- Dask version: 2021.10.0
- Python version: 3.9.4.final.0
- Operating System: Windows 10
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment] 2021-11-15 22:08
Thanks for writing this up so clearly. I think there might need to be a new `normalize_token` function registered to cover the `dataclass` case or at least `normalize_function`  needs some changes. If you are comfortable adding that I think it would go in here https://github.com/dask/dask/blob/main/dask/base.py#L942 

I will try to take a look at it later this week if you don't get to it first :)

**Comment by scharlottej13** [comment] 2021-12-01 16:50
Hi @jsignell, did you have a chance to look at this already? If not, I'm happy to take a look!

**Comment by jsignell** [comment] 2021-12-01 17:30
Yeah this slipped off my list. I'd be pleased for you to take it over!

**Comment by scharlottej13** [comment] 2021-12-14 22:15
@ian-r-rose and I were able to reproduce this, and it looks like the error is indeed in `_normalize_function` here: https://github.com/dask/dask/blob/0d4bdea8d5215270646c7b48413e4125f590166e/dask/base.py#L982
Testing `cloudpickle.dumps` with `protocol=None` works, but with `protocol=0` you get this error:
```python-traceback
TypeError: cannot pickle '_DataclassParams' object: a class that defines __slots__ without defining __getstate__ cannot be pickled with protocol 0
```
How important is `protocol=0` here?

**Comment by ian-r-rose** [comment] 2022-01-03 19:02
@jrbourbeau do you have any insight as to whether the specific protocol matters here?

@scharlottej13 I think it might be interesting to try out the test suite with `protocol=None` to see if anything fails.

**Comment by scharlottej13** [comment] 2022-01-03 20:03
> @scharlottej13 I think it might be interesting to try out the test suite with `protocol=None` to see if anything fails.
Sounds good! Locally, no tests fail in dask/tests/test_base.py nor dask/array/tests/test_ufunc.py. I'll push a draft PR w/ the change to see if anything in CI fails.

**Comment by scharlottej13** [comment] 2022-01-05 19:16
Since CI has been having some issues, I ran the dask/dask test suite locally and no new tests failed (3 failed, but these also fail on `dask:main`).

**Comment by jrbourbeau** [comment] 2022-02-23 01:29
Closed via https://github.com/dask/dask/pull/8527

**Closed by jrbourbeau** 2022-02-23 01:29 UTC
Labels: core
