### ISSUE TITLE
Task groups tab on dashboard fails with cycle error

### ISSUE THREAD

**Issue by Fogapod** [dask/dask#11451] opened 2024-10-21 15:28 UTC
**Describe the issue**:

Task groups dashboard tab is permanently in broken HTTP 500 state. Every other tab works.
Scheduler error:
```python
2024-10-21 15:20:04,779 - distributed.dashboard.components.scheduler - ERROR - Cycle detected between the following keys:
  ->
Traceback (most recent call last):
  File "/opt/backend/dask/bin.runfiles/rules_python~0.33.2~pip~pypi_312_distributed/site-packages/distributed/utils.py", line 812, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/backend/dask/bin.runfiles/rules_python~0.33.2~pip~pypi_312_distributed/site-packages/distributed/dashboard/components/scheduler.py", line 2616, in update_layout
    order = dask.order.order(
            ^^^^^^^^^^^^^^^^^
  File "/opt/backend/dask/bin.runfiles/rules_python~0.33.2~pip~pypi_312_dask/site-packages/dask/order.py", line 186, in order
    raise RuntimeError(
RuntimeError: Cycle detected between the following keys:
  ->
2024-10-21 15:20:04,780 - distributed.dashboard.components.scheduler - ERROR - Cycle detected between the following keys:
  ->
Traceback (most recent call last):
  File "/opt/backend/dask/bin.runfiles/rules_python~0.33.2~pip~pypi_312_distributed/site-packages/distributed/utils.py", line 812, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/backend/dask/bin.runfiles/rules_python~0.33.2~pip~pypi_312_distributed/site-packages/distributed/dashboard/components/scheduler.py", line 4686, in tg_graph_doc
    tg_graph.update()
  File "/opt/backend/dask/bin.runfiles/rules_python~0.33.2~pip~pypi_312_bokeh/site-packages/bokeh/core/property/validation.py", line 95, in func
    return input_function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/backend/dask/bin.runfiles/rules_python~0.33.2~pip~pypi_312_distributed/site-packages/distributed/dashboard/components/scheduler.py", line 2679, in update
    self.nodes_layout, self.arrows_layout = self.update_layout()
                                            ^^^^^^^^^^^^^^^^^^^^
  File "/opt/backend/dask/bin.runfiles/rules_python~0.33.2~pip~pypi_312_bokeh/site-packages/bokeh/core/property/validation.py", line 95, in func
    return input_function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/backend/dask/bin.runfiles/rules_python~0.33.2~pip~pypi_312_distributed/site-packages/distributed/utils.py", line 812, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/backend/dask/bin.runfiles/rules_python~0.33.2~pip~pypi_312_distributed/site-packages/distributed/dashboard/components/scheduler.py", line 2616, in update_layout
    order = dask.order.order(
            ^^^^^^^^^^^^^^^^^
  File "/opt/backend/dask/bin.runfiles/rules_python~0.33.2~pip~pypi_312_dask/site-packages/dask/order.py", line 186, in order
    raise RuntimeError(
RuntimeError: Cycle detected between the following keys:
  ->
2024-10-21 15:20:04,781 - tornado.application - ERROR - Uncaught exception GET /groups (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8787', method='GET', uri='/groups', version='HTTP/1.1', remote_ip='127.0.0.1')
```

Don't see any other relevant logs around (`DASK_LOGGING__DISTRIBUTED=DEBUG`)

**Minimal Complete Verifiable Example**:

I do not have reproducer yet. No idea where to start with this, the graph is pretty complex and error doesn't point to any code/function names outside dask

**Anything else we need to know?**:

**Environment**:

- Dask version: `2024.10.0`
- Python version: `3.12`
- Operating System: `Linux`
- Install method (conda, pip, source): `pip/bazel`

**Comment by phofl** [comment] 2024-10-24 08:10
Hi, thanks for your report. I can't reproduce this for a trivial example, so this seems like it's related to your computation?

Could you provide more information about what you are doing with Dark?

**Comment by Fogapod** [comment] 2024-10-24 13:02
I have a permanent dask cluster, it periodically receives small jobs. Each job is ~ 20 graph nodes including checkpoints. I use a single submit call on top to start processing. I use a couple persist and sync calls, 2 bags.

I'll try making a reproducer

**Comment by phofl** [comment] 2024-11-07 18:58
I am closing this for now, please just send a ping if you have a reproducer

**Closed by phofl** 2024-11-07 18:58 UTC
Labels: needs info
