### ISSUE TITLE
Using Delayed.key as an argument of another Delayed function

### ISSUE THREAD

**Issue by maurosilber** [dask/dask#6495] opened 2020-08-08 20:46 UTC
**What happened**:
I cannot use Delayed.key as a string argument in another subsequent Delayed function call, as it is replaced with its output during computation. Its easier to look at the example:

**Minimal Complete Verifiable Example**:

```python
from dask import delayed

@delayed
def func():
    return 1

@delayed
def func2(key, value):
    return key, value

a = func()
print(a.key)  # prints func-d8f...44c

b = func2(a.key, a)
print(b.compute())  # prints (1, 1), expected (func-d8f...44c, 1)
```

**Environment**:

- Dask version: 2.20.0
- Python version: Python 3.8.3 (default, Jul  2 2020, 16:21:59) [GCC 7.3.0] :: Anaconda, Inc. on linux
- Operating System: Ubuntu 20.04.1 LTS
- Install method (conda, pip, source): conda

**Comment by mrocklin** [comment] 2020-08-08 21:46
Yes, this is a corner case for which Dask's default behavior is not ideal.

To resolve the issue, try using `dask.core.quote`

**Comment by maurosilber** [comment] 2020-08-08 22:44
Thank you for the fast rasponse!

If this is what you meant:
```python
from dask.core import quote
...
b = func2(quote(a.key), a)
````
it's still not working.

**Comment by quasiben** [comment] 2020-08-12 14:50
I think this might be an issue .  The task coming in looks like the following:

> (<function func2 at 0x7fe759f92560>, 'func-8505983a-3791-40a0-951d-744329868434', 'func-8505983a-3791-40a0-951d-744329868434')

When we actually go to execute the task, the key name is used as a look up in the cache and is replaced by the cached value when the task is executed.

```python
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):

ipdb> pp args
('func-8505983a-3791-40a0-951d-744329868434',
 'func-8505983a-3791-40a0-951d-744329868434')
ipdb> cache
{'func-8505983a-3791-40a0-951d-744329868434': 1}
```

**Comment by maurosilber** [comment] 2020-08-12 17:56
I don't need this functionality anymore, but have you considered using a subclass of `str` for Dask keys?

```python
from collections import UserString

class DaskKey(UserString):
    pass
```

It would probably break other projects manipulating the Dask graph directly, so maybe it should be optional.

**Comment by nils-braun** [comment] 2020-08-19 20:52
Pickup up what @mrocklin said: you could use the `dask.core.literal` directly:

```python
from dask.core import literal
...
b = func2(literal(a.key), a)
...
print(b.compute())  # prints (literal<type=str>, 1)
```
but that would need you to call some "un-literal" in your function. 
Actually, maybe as a general question: would it make sense to have a second/different literal type, which is automatically unpacked before calling `func`?

**Comment by jcrist** [comment] 2020-09-11 14:45
> you could use the dask.core.literal directly

Wrapping the string key with any non-builtin python object would work, requirement here is that it's not a type that dask will "traverse" when converting to a delayed object.

```python
class Box:
    def __init__(self, val):
        self.val = val
...
b = func2(Box(a.key, a))
```

> but have you considered using a subclass of str for Dask keys?
> It would probably break other projects manipulating the Dask graph directly, so maybe it should be optional.

There has been talk of creating explicit `Task`/`Key` types to prevent issues like this in the past. See #2299 (and issues/prs linked from there) for example. Any efforts down this front should be done globally, rather just for dask delayed IMO. Closing as duplicate of #2299.

**Closed by jcrist** 2020-09-11 14:45 UTC
