### ISSUE TITLE
Dask Performance Degradation when executing same code repeatedly

### ISSUE THREAD

**Issue by jrdzha** [dask/dask#6603] opened 2020-09-05 04:02 UTC
**What happened**: Repeatedly running the same code leads to performance degradation.

**What you expected to happen**: Expected this code to take the same amount of time for each run.

**Minimal Complete Verifiable Example**:

```python
import time
import pandas as pd
import dask.dataframe as dd
import dask
from dask.distributed import Client, LocalCluster

cluster = LocalCluster()
client = Client(cluster)

df = dd.from_pandas(pd.DataFrame({'a': [0] * 10000, 'b': [0] * 10000}), npartitions=1)

def func():
    result = df

    result['c'] = result['a'].apply(lambda x: time.sleep(0.0000001), meta=('a', 'object'))
    result = result.persist()
    dask.distributed.wait(result)
    # Same issue exists with .compute() in place of .persist() and .wait()
    
for i in range(10):
    start = time.time()
    
    func()
    
    end = time.time()
    
    print(end - start, 's')

# Prints out:
# 0.9409093856811523 s
# 1.220930576324463 s
# 1.814140796661377 s
# 2.423081874847412 s
# 3.0193543434143066 s
# 3.635204553604126 s
# 4.258993864059448 s
# 4.8433003425598145 s
# 5.3967444896698 s
# 6.015292644500732 s
```

**Anything else we need to know?**: We are running this with a much higher volume of data with many partitions, and this same issue exists there, making performance unacceptably slow sometimes. This is especially pronounced when running the same jupyter cell multiple times.

This has also been tested without persist(), with compute() instead, and the same issue arises.

**Environment**:

- Dask version: 2.17.2
- Python version: 3.7
- Operating System: Linux
- Install method (conda, pip, source): Conda

**Comment by TomAugspurger** [comment] 2020-09-08 13:49
Are you intentionally mutating `df` inplace? If you look at the task graph of `df` (`len(df.dask)`) you'll notice that it's growing over time, because you're assigning to it.

**Comment by jrdzha** [comment] 2020-09-09 18:55
So this is the expected behavior? It seems strange to me that mutating a python variable in place (and overwriting the same column) could lead to this? Isn't it actually quite common for the same code blocks to be re-run in a Jupyter notebook?

**Comment by TomAugspurger** [comment] 2020-09-10 12:58
You might need to update your mental model of what Dask is doing. You've assigned `result = df` on the first line, so that mutating `result` mutates `df`. But then you persist `result`, which isn't an inplace operation. It returns a new result, which you wait for and then throw away when the function finish.

Then length of the task graph gives some indication to what's going on:

```python
   ...: for i in range(10):
   ...:     start = time.time()
   ...:
   ...:     func()
   ...:
   ...:     end = time.time()
   ...:
   ...:     print(end - start, 's', len(df.dask))
   ...:
0.16588497161865234 s 7
0.3261120319366455 s 10
0.3963158130645752 s 13
0.4376530647277832 s 16
0.4915320873260498 s 19
0.6152620315551758 s 22
0.6993727684020996 s 25
0.8067042827606201 s 28
0.8815453052520752 s 31
1.0762887001037598 s 34
```

The growing length indicates that the final result is being computed from scratch, including all the previous ones, since you're assigning a column that depends on the previous one (recursively back to the beginning).

**Comment by jrdzha** [comment] 2020-09-15 07:28
@TomAugspurger I see. So is watching the df.dask task graph a good way of making sure that I am writing performant Dask code? I'm not able to find this attribute in the API docs.

**Comment by mrocklin** [comment] 2020-09-15 14:28
The proper term today would be the __dask_graph__() method,  The full
interface is here: https://docs.dask.org/en/latest/custom-collections.html

You might also want to read through some of
https://docs.dask.org/en/latest/understanding-performance.html

**Comment by TomAugspurger** [comment] 2020-09-16 20:30
Thanks for providing those links. I think everything is working as intended here.

**Closed by TomAugspurger** 2020-09-16 20:30 UTC
Labels: dataframe, needs info
