### ISSUE TITLE
Rendered API docs not showing method summaries for DataFrame+ other methods

### ISSUE THREAD

**Issue by JohnZed** [dask/dask#5203] opened 2019-08-01 17:03 UTC
Some of the rendered API docs, such as those for DataFrameGroupBy, show the first summary line of the docstrings in the table of methods (https://docs.dask.org/en/latest/dataframe-api.html#groupby-operations)

These summaries do not appear for DataFrame methods https://docs.dask.org/en/latest/dataframe-api.html#dataframe

The DataFrame methods also lack a link to the more detailed function docs, suggesting that something is going wrong in the doc building.

**Comment by jrbourbeau** [comment] 2019-08-02 18:14
Thanks for raising this issue @JohnZed! I think this may be a duplicate of #5206, which was just fixed in #5207. If you revisit https://docs.dask.org/en/latest/dataframe-api.html#dataframe now, there should be a summary line and links to the full rendered docstrings

**Comment by jrbourbeau** [comment] 2019-08-02 18:16
Closing as I think this issue has already been resolved. But feel free to re-open if that's not the case @JohnZed

**Closed by jrbourbeau** 2019-08-02 18:16 UTC
