### ISSUE TITLE
Series EWM for algorethmic trading

### ISSUE THREAD

**Issue by aladdain** [dask/dask#11428] opened 2024-10-12 00:10 UTC
HI everyone , thanks for this amazing library, however implementing pandas Series EWM is a bare minimum for algorithmic trading , are you planing to add it ?

**Comment by rjzamora** [comment] 2024-10-14 14:25
Thanks for the feature request @aladdain !

I believe this is a duplicate of https://github.com/dask/dask/issues/4184 (I'll close this issue in favor of the historical context and community support that is already reflected in the older issue)

Related PRs: https://github.com/dask/dask/pull/6116 & https://github.com/dask/dask/pull/6796

**Note**: It looks like #6796 was getting close, but that was a few years ago. The logic in that PR can probably be translated into a dask-expr solution with a bit of effort.

**Closed by rjzamora** 2024-10-14 14:25 UTC
Labels: dataframe, feature, needs triage
