### ISSUE TITLE
Segfault in `std` in Dask 2.0.0 release

### ISSUE THREAD

**Issue by hameerabbasi** [dask/dask#5028] opened 2019-06-30 09:00 UTC
I have tried to create an MVCE but unfortunately I'm not able to debug any further, as the segfault happens in a complex combination of calls. I'm also not able to debug on my local machine, because it doesn't happen here, only on CI and on @peterbell10's machine.

The discussion and the resulting conclusion is at Quansight-Labs/uarray#170.

**Comment by peterbell10** [comment] 2019-06-30 09:39
Correction, it's in `std` and the segfault always happens in the `sqrt` part. Looks like infinite recursion in `PyUFunc_CheckOverride` based on the stack trace.

```
#0  get_ufunc_arguments (ufunc=ufunc@entry=0xd4c4c0, args=args@entry=0x7fff8e6fada0, kwds=kwds@entry=0x7fff8de7c168,
    out_op=out_op@entry=0x7fffff7f09b0, out_order=out_order@entry=0x7fffff7ef160,
    out_casting=out_casting@entry=0x7fffff7ef170, out_extobj=out_extobj@entry=0x7fffff7ef310,
    out_typetup=out_typetup@entry=0x7fffff7ef390, out_subok=out_subok@entry=0x7fffff7ef130,
    out_wheremask=out_wheremask@entry=0x7fffff7ef1f0, out_axes=out_axes@entry=0x0, out_axis=out_axis@entry=0x0,
    out_keepdims=out_keepdims@entry=0x0) at numpy/core/src/umath/ufunc_object.c:1042
#1  0x00007ffffb304bd9 in PyUFunc_GenericFunction (ufunc=ufunc@entry=0xd4c4c0, args=args@entry=0x7fff8e6fada0,
    kwds=kwds@entry=0x7fff8de7c168, op=op@entry=0x7fffff7f09b0) at numpy/core/src/umath/ufunc_object.c:3162
#2  0x00007ffffb3076de in ufunc_generic_call (ufunc=0xd4c4c0, args=0x7fff8e6fada0, kwds=0x7fff8de7c168)
    at numpy/core/src/umath/ufunc_object.c:4688
#3  0x00000000005b4266 in PyObject_Call ()
#4  0x0000000000518041 in _PyEval_EvalFrameDefault ()
#5  0x00000000005cd202 in _PyEval_EvalCodeWithName ()
#6  0x00000000005b11a2 in _PyFunction_FastCallKeywords ()
#7  0x00000000005cc6ea in ?? ()
#8  0x0000000000517a9e in _PyEval_EvalFrameDefault ()
#9  0x00000000005cd202 in _PyEval_EvalCodeWithName ()
#10 0x00000000005b2437 in _PyFunction_FastCallDict ()
#11 0x0000000000518041 in _PyEval_EvalFrameDefault ()
#12 0x00000000005cd202 in _PyEval_EvalCodeWithName ()
#13 0x00000000005b2437 in _PyFunction_FastCallDict ()
#14 0x00007ffffb3306f0 in PyUFunc_CheckOverride (ufunc=ufunc@entry=0xd4c4c0, method=<optimized out>,
    method@entry=0x7ffffb3a81e8 "__call__", args=args@entry=0x7fff8e6faba8, kwds=kwds@entry=0x7fff8de7c048,
    result=result@entry=0x7fffff7f1810) at numpy/core/src/umath/override.c:680                                          #15 0x00007ffffb30769c in ufunc_generic_call (ufunc=0xd4c4c0, args=0x7fff8e6faba8, kwds=0x7fff8de7c048)
    at numpy/core/src/umath/ufunc_object.c:4680                                                                         #16 0x00000000005b4266 in PyObject_Call ()
#17 0x0000000000518041 in _PyEval_EvalFrameDefault ()
#18 0x00000000005cd202 in _PyEval_EvalCodeWithName ()
#19 0x00000000005b2437 in _PyFunction_FastCallDict ()
#20 0x0000000000518041 in _PyEval_EvalFrameDefault ()
#21 0x00000000005cd202 in _PyEval_EvalCodeWithName ()
#22 0x00000000005b2437 in _PyFunction_FastCallDict ()
#23 0x0000000000518041 in _PyEval_EvalFrameDefault ()
#24 0x00000000005cd202 in _PyEval_EvalCodeWithName ()
#25 0x00000000005b2437 in _PyFunction_FastCallDict ()
#26 0x0000000000518041 in _PyEval_EvalFrameDefault ()
#27 0x00000000005cd202 in _PyEval_EvalCodeWithName ()
#28 0x00000000005b2437 in _PyFunction_FastCallDict ()
#29 0x0000000000518041 in _PyEval_EvalFrameDefault ()
#30 0x00000000005cd202 in _PyEval_EvalCodeWithName ()
#31 0x00000000005b2437 in _PyFunction_FastCallDict ()
#32 0x00007ffffb3306f0 in PyUFunc_CheckOverride (ufunc=ufunc@entry=0xd4c4c0, method=<optimized out>,
    method@entry=0x7ffffb3a81e8 "__call__", args=args@entry=0x7fff8e6fa9b0, kwds=kwds@entry=0x7fff8de75ab0,
    result=result@entry=0x7fffff7f2bf0) at numpy/core/src/umath/override.c:680
#33 0x00007ffffb30769c in ufunc_generic_call (ufunc=0xd4c4c0, args=0x7fff8e6fa9b0, kwds=0x7fff8de75ab0)
    at numpy/core/src/umath/ufunc_object.c:4680
[...]
```

And the stack keeps going through `PyUFunc_CheckOverride` for thousands of stack frames.

```
(gdb) p ufunc->name
$2 = 0x7ffffb3a3696 "sqrt"
```

**Comment by peterbell10** [comment] 2019-06-30 09:50
Also, The calling code is essentially this
```python
import dask.array as da
b = da.std(da.asarray([1, 3, 2]))
```
but that on its own isn't enough to reproduce the segfault.

**Comment by mrocklin** [comment] 2019-06-30 09:52
Finding a minimal example is probably the first step to fixing this.  If you all are able to track this down that would be welcome.  I'm not sure how much the Dask maintainers can do without a simple fail case.  I appreciate any time you're able to spend here (though of course, no obligation).

**Comment by jakirkham** [comment] 2019-07-08 15:24
Was there a version of Dask where this did work?

**Comment by hameerabbasi** [comment] 2019-07-08 15:25
1.x works fine.

**Comment by jakirkham** [comment] 2019-07-08 15:30
Admittedly I have very little knowledge of the work you are doing ATM. So this suggestion might not make much sense. That said, one thing to check would be whether things like operations on empty arrays work. As Dask is using empty arrays to determine how a result type might look and this could easily trip things up, that's where I would start.

**Comment by hameerabbasi** [comment] 2019-07-08 16:55
I'll try to call things in the exact order they're called, although I'll have to debug on CI as I cannot reproduce this locally (on Linux or Mac).

**Comment by pentschev** [comment] 2019-07-08 17:01
This may be a bit too much work, but I once created a [Dockerfile](https://gist.github.com/pentschev/dcbe78364640f3e143795f03c6faaed8) to try and mimic Dask's Travis CI, it worked for the issues I couldn't reproduce elsewhere. Maybe that's something that we can use to reproduce the issue?

**Comment by jakirkham** [comment] 2019-07-08 17:07
Following Peter's suggestion, Travis CI builds could generally be run locally as [explained in this blog]( https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e ). Things can probably be simplified there as these are public repos (not private).

**Comment by pentschev** [comment] 2019-07-08 17:10
> Following Peter's suggestion, Travis CI builds could generally be run locally as [explained in this blog](https://medium.com/google-developers/how-to-run-travisci-locally-on-docker-822fc6b2db2e). Things can probably be simplified there as these are public repos (not private).

Yes, I saw that once, but there was some caveat with that, I can't remember exactly what that was, but I think it wasn't easy (or possible) to break into the session and debug, just see the results that we see on PRs.

**Comment by jakirkham** [comment] 2021-10-12 18:56
If we are able to create an MRE, that would also be very helpful

**Comment by jrbourbeau** [comment] 2022-12-12 17:31
Closing as it's been >3 years since this issue was originally reported and don't currently have a reproducer. Let's reopen if someone is able to reproduce

**Closed by jrbourbeau** 2022-12-12 17:31 UTC
Labels: array, needs info
