### ISSUE TITLE
Weighted mean of masked dask array does not apply mask to weights

### ISSUE THREAD

**Issue by niallrobinson** [dask/dask#3846] opened 2018-08-03 12:35 UTC
```python
import dask.array as da
import numpy as np

my_arr = np.array(range(10))
my_mask = [True, True, True, False, False, False, False, False, False, False]
my_weights = np.array([100, 100, 2, 2, 1, 1, 1, 1, 1, 1], dtype='float64')
my_masked_arr = np.ma.array(my_arr, mask=my_mask)

print("numpy weighted masked avg (unmasked weights): ", ma.average(my_masked_arr, weights=my_weights))

my_masked_dask_arr = da.ma.masked_array(data=my_arr, mask=my_mask)
print("dask weights masked avg (unmasked weights): ", da.average(my_masked_dask_arr, weights=my_weights).compute())

my_masked_weights = ma.masked_array(my_weights, my_mask)
print("dask weights masked avg (weights): ", da.average(my_masked_dask_arr, weights=my_masked_weights).compute())
```

gives this output
```
numpy weighted masked avg (unmasked weights):  5.625
dask weights masked avg (unmasked weights):  0.214285714286
dask weights masked avg (weights):  5.625
```

Upon further investigation it seems that the weights are normalised by dask, but that normalisation doesn't take into account the array mask.

i.e. this line
https://github.com/dask/dask/blob/e823ecf51032ea7e4d57687a91d788cfb28e36ac/dask/array/routines.py#L1293

I'm not sure how to fix this - I don't think one has access to the mask without realising all the data, so the weight normalisation can't happen lazily(?) Maybe the way to solve this is to specify that the weights array must be masked by the user before being passed - this would make the API different to numpy.

**Comment by niallrobinson** [comment] 2018-08-03 12:37
@dkillick

**Comment by niallrobinson** [comment] 2018-08-03 13:39
@jcrist according to @bjlittle

**Comment by mrocklin** [comment] 2018-08-03 14:04
I agree that @jcrist is likely the person who best knows the situation here.  However, if the fix is feasible and not too crazy then I suggest that @jcrist helps someone in the Met office implement the fix, rather than fixing it directly.  I think that it would be good to start transferring knowledge over to you all if you're up for some work.

**Comment by jcrist** [comment] 2018-08-03 14:31
So the above example is using `np.ma.average` (a masked implementation), but `da.average` (not a masked implementation). Looks like all that's needed is a masked port. I'd handle this by doing the following:

- Look at how `np.ma.average` differs from `np.average`
- Port over `np.ma.average` to use dask functions (for `da.average` it was mostly just replacing numpy functions with their dask equivalents)
- See what shared functionality there can be between `da.average` and `da.ma.average`. On first glance it looks to be as simple as masking the weights and then forwarding to `da.average`.

I agree with @mrocklin that this would be a good first issue if anyone wants to take a try at it.

**Comment by dkillick** [comment] 2018-08-03 15:17
@mrocklin I think a number of us here are keen to know dask as more than users 👍

**Comment by TAdeJong** [comment] 2018-08-05 11:36
> See what shared functionality there can be between `da.average` and `da.ma.average`. On first glance it looks to be as simple as masking the weights and then forwarding to `da.average`.

After looking at all three functions I agree that there does not seems to happen any more magic in the masked version and passing the masked weights should be all that is required. Actually I am somewhat surprised that numpy does not do this internally as well...

**Comment by garaud** [comment] 2018-11-23 12:51
There is a slightly difference between `np.average` and `np.ma.average`. In the second on, before computing the sum of weights, there is a:

```python
if m is not nomask:
    wgt = wgt*(~a.mask)
```

It's quite simple to sum the weights taking into account the mask. It will be great if we have a way to determine if a dask array is a masked_array, i.e. a `nomask` dask equivalent.

I pushed a *work in progress* branch with a unit test. This is the first step of the PR: reproduce the issue. https://github.com/garaud/dask/commit/b332d9e2b9770bb93c61a75896bc383f48bee4ee

**Closed** 2018-11-29 17:51 UTC
Labels: array, good first issue
