### ISSUE TITLE
Consider supporting pathlib.Path within Dask Arrays `.to_zarr(...)` method

### ISSUE THREAD

**Issue by asmith26** [dask/dask#8006] opened 2021-08-06 15:57 UTC
Not sure if this should be raised in maybe the [zarr repo](https://github.com/zarr-developers/zarr-python), and I've looked through previous issues and couldn't find anything regarding this - it's feels like the Dask Array `.to_zarr(...)` method could support `pathlib.Path` (directly, i.e. without having to turn it into a `str`):

**Dask Version:** 2021.7.2

```python
>>> import pathlib, dask.array as da,  numpy as np
>>> da.from_array(np.array([1])).to_zarr("file.zarr")  # works
>>> da.from_array(np.array([1])).to_zarr(pathlib.Path("file.zarr"))  # yields:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../lib/python3.8/site-packages/dask/array/core.py", line 2649, in to_zarr
    return to_zarr(self, *args, **kwargs)
  File ".../lib/python3.8/site-packages/dask/array/core.py", line 3381, in to_zarr
    z = zarr.create(
  File ".../lib/python3.8/site-packages/zarr/creation.py", line 136, in create
    init_array(store, shape=shape, chunks=chunks, dtype=dtype, compressor=compressor,
  File ".../lib/python3.8/site-packages/zarr/storage.py", line 352, in init_array
    _init_array_metadata(store, shape=shape, chunks=chunks, dtype=dtype,
  File ".../lib/python3.8/site-packages/zarr/storage.py", line 382, in _init_array_metadata
    elif contains_array(store, path):
  File ".../lib/python3.8/site-packages/zarr/storage.py", line 96, in contains_array
    return key in store
TypeError: argument of type 'PosixPath' is not iterable
```

In particular I've noticed that Dask DataFrame `.to_parquet(...)` supports this:

```python
>>> import pathlib, dask.dataframe as dd, pandas as pd
>>> dd.from_pandas(pd.DataFrame({"a": [1]}), npartitions=1).to_parquet(pathlib.Path("file.parquet"))  # works
```

Many thanks for these awesome libs!

**Comment by jrbourbeau** [comment] 2021-08-10 19:58
Thanks for raising an issue @asmith26! The error you're running into looks similar to https://github.com/zarr-developers/zarr-python/issues/601. It looks like `zarr` itself doesn't have full support for `pathlib.Path` objects yet, but that it is currently in the works (xref https://github.com/zarr-developers/zarr-python/pull/768). I agree it would be reasonable for Dask to support them

cc @martindurant

**Comment by martindurant** [comment] 2021-08-10 20:05
fsspec handles Path objects in a few places (e.g., `fsspec.open`), but not generally, because there is no consensus on how to represent non-local paths.  I think zarr will defer to fsspec only if the path is URL-like (containing "://" or "::" - but probably not knowing to convert to string first), and `fsspec.get_mapper` does not support Path.

Do you think a `Path` is implicitly local?

**Comment by asmith26** [comment] 2021-08-11 10:33
Thanks for all the answers.

> Do you think a `Path` is implicitly local?

That's a good question - I had a little Google and would consider `pathlib.Path` to be intended only for local paths. In particular:
- I couldn't find any mentions of remote/s3/cloud/,.. in the [main docs](https://docs.python.org/3/library/pathlib.html).
- `pathlib.Path` supports a [`.home()` method](https://docs.python.org/3/library/pathlib.html#pathlib.Path.home), whilst for example s3 does not have the concept of "home"(as far as I'm aware?)
- Looks like a third party lib for using `pathlib.Path` with s3 has been created: https://github.com/liormizr/s3path

That said, I'm certainly no expert on `pathlib.Path`, so all thoughts/corrections very welcome.

**Comment by martindurant** [comment] 2021-08-11 16:09
I encourage you to comment at https://github.com/drivendataorg/cloudpathlib/issues/96 to push support for pathlib with fsspec. That would solve this kind of issue, without dask's explicit involvement, for local and remote paths both.

**Comment by clbarnes** [comment] 2021-08-17 13:35
> It looks like `zarr` itself doesn't have full support for `pathlib.Path` objects yet, but that it is currently in the works (xref [zarr-developers/zarr-python#768](https://github.com/zarr-developers/zarr-python/pull/768))

That PR is now merged; zarr will accept `pathlib.Path` in its convenience methods and store constructors (although it does so by normalising to `str`).

**Comment by clbarnes** [comment] 2021-09-01 08:46
Zarr's convenience methods accept Path objects as of 2.9.0: https://zarr.readthedocs.io/en/stable/release.html#enhancements

**Comment by jsignell** [comment] 2021-09-01 14:55
I just reran the original reproducer with zarr=2.9.0 and it worked as expected, so I think we can safely close this.

**Closed by jsignell** 2021-09-01 14:55 UTC
Labels: array, io

**Comment by jamestwebber** [comment] 2021-09-21 16:06
I could create a new issue it's _so_ close to this one: while `to_zarr` works as expected, `from_zarr` still raises the error mentioned in the original post. It'd be great if it worked both ways!

Just tested with `zarr=2.10` and `dask=2021.09.0`

**Comment by jrbourbeau** [comment] 2021-09-21 16:27
A new issue, or a PR, for `from_zarr` would be very welcome : )
