### ISSUE TITLE
Dask Dataframe index renaming doesn't work in place

### ISSUE THREAD

**Issue by marcelned** [dask/dask#8082] opened 2021-08-24 15:19 UTC
`Inplace` parameter doesn't behave as expected:

<img width="608" alt="Screenshot 2021-08-24 at 17 18 27" src="https://user-images.githubusercontent.com/82392567/130643593-54481251-a2d5-4afc-9311-e55f72cefc4d.png">

**Comment by jrbourbeau** [comment] 2021-08-24 22:12
Thanks for repoting @marcelned! I'm able to reproduce. My guess is that since we regenerate `.index` each time it's accessed: 

https://github.com/dask/dask/blob/ab69fe124eb36a63c092026ab082ccb08311fc79/dask/dataframe/core.py#L480-L489

There's some underlying state that `rename(..., inplace=True)` isn't updating that it should. Is this something you're interested in working on? (no obligation though)

**Comment by jsignell** [comment] 2021-09-10 14:29
Whoa I had no idea that a series could have a different name than its column name. For anyone else reading this, this is what pandas does:

```python
import pandas as pd

df = pd.DataFrame(
    {
        "Animal": ["Falcon", "Falcon", "Parrot", "Parrot"],
        "Max Speed": [380.0, 370.0, 24.0, 26.0],
    }
)
df["Animal"].rename("Bird", inplace=True)
print(df["Animal"])
# 0    Falcon
# 1    Falcon
# 2    Parrot
# 3    Parrot
# Name: Bird, dtype: object
```

I think you are right to bring up the option of removing the `inplace` option from rename. That seems like the safest and best path forward. Are you interested in opening a pull request to implement that change?

**Comment by jsignell** [comment] 2021-09-10 14:44
Incidentally the inplace rename _does_ work for a series in dask. The issue you are running into is that when you access the series by getting it off the dataframe like `ddf["Animal"]` you actually get a new object. So even if you then rename that inplace, you don't affect the real object. Here's where the new object gets created: 

https://github.com/dask/dask/blob/e1974bffd6067659bb250fd84b6eb3f224cdb79f/dask/dataframe/core.py#L3993

I still like your idea of not allowing inplace as an option for rename, just trying to give more context about what's going on.

**Comment by marcelned** [comment] 2021-09-10 22:56
@jsignell @jrbourbeau I made Pull request #8133, removing the inplace argument and associated logic from the renaming function.

@jsignell the inplace argument seems to be a highly contentious issue even in base pandas: https://github.com/pandas-dev/pandas/issues/16529. It is used in edge testing cases rather than user code.

Dask being lazily evaluated (so no saving memory by inplacing data on an existing object using `inplace=True`) , is there a case for `inplace` being *anywhere* in the dask API?

**Comment by GenevieveBuckley** [comment] 2021-10-14 08:20
Closed by https://github.com/dask/dask/pull/8136

**Closed by GenevieveBuckley** 2021-10-14 08:20 UTC
Labels: dataframe
