### ISSUE TITLE
Parallel random_state_data_python

### ISSUE THREAD

**Issue by jordan-jack-schneider** [dask/dask#10351] opened 2023-06-01 19:50 UTC
I've noticed my workers spend a lot of time on dask/bag/core.py random_sample computing the list comprehension in random_state_data_python. Currently this has to happen serially, as python.random.Random increments the state serially. However there are other sources of randomness (like SystemRandom) that can be accessed in parallel, but don't generate reproducible sequences.

Is reproducibility required here? Could we switch to SystemRandom (or similar) and parallelize this function?

**Comment by fjetter** [comment] 2023-06-13 13:38
I transferred this to the dask/dask repo since it doesn't require a distributed cluster.

My take on this is that for most practical purposes this is not required to be reproducible. At the very least the default is not strictly reproducible if the user does not provide a random seed. Accepting a random seed and ensuring reproducibility in this case is a useful feature, e.g. for testing and I would prefer keeping this.

However, I'm not entirely sure what level of parallelism you are looking for. I would be slightly concerned if we parallelized within `random_state_data_python`. What did you have in mind?

**Comment by jordan-jack-schneider** [comment] 2023-06-13 20:29
```python
def random_state_data_python(n, random_state=None):
    """Return a list of tuples that can be passed to
    ``random.Random.setstate``.

    Parameters
    ----------
    n : int
        Number of tuples to return.
    random_state : int or ``random.Random``, optional
        If an int, is used to seed a new ``random.Random``.
    """
    if not isinstance(random_state, Random):
        random_state = Random(random_state)

    maxuint32 = 1 << 32
    return [
        (
            3,
            tuple(random_state.randint(0, maxuint32) for i in range(624)) + (624,),
            None,
        )
        for i in range(n)
    ]
```
I'm finding I'm spending a bunch of time in that list comprehension, so yes I was imagining we parallelize that loop. What's the concern?

**Comment by fjetter** [comment] 2023-06-14 09:03
> What's the concern?

Primarily I'm concerned about complexity around managing a threadpool for this. I wouldn't want to initialize a new pool for this for various reasons and passing an existing one to this function also feels cumbersome.

Instead, I would prefer us thinking about whether we should not modify our algorithm here. Were generating `NPartitions * 624` random numbers to create a deterministic `RandomState`, see https://github.com/dask/dask/pull/1687 to fix the issue here https://github.com/dask/dask/issues/1684
there was also an alternative proposal to fix this issue here (https://github.com/dask/dask/pull/1689) which was rejected because it had inferior statistical properties about reproducibility. We may want to revisit this decision before considering to parallelize this. If we went back to simply generating seeds this would no longer be an issue.

cc @jcrist @shoyer @crusaderky

**Comment by crusaderky** [comment] 2023-06-14 10:18
I see no reason not to accelerate this function as a wrapper around `dask.utils.random_state_data`, and only fall back to pure Python if numpy isn't installed. This would mean that the random sequence would differ when numpy is installed from when it isn't, but I doubt this will be a problem for anybody.

The hardcoded number 624 at the end of the sequence also makes no sense to me.

numpy is 12~18x faster:
```python
%timeit random_state_data_python(1, 0)
265 µs ± 1.72 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
%timeit [a.tolist() for a in random_state_data(1, 0)]
134 µs ± 4.17 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

%timeit random_state_data_python(10, 0)
2.64 ms ± 16.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
%timeit [a.tolist() for a in random_state_data(10, 0)]
225 µs ± 780 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

%timeit random_state_data_python(100, 0)
26.5 ms ± 146 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit [a.tolist() for a in random_state_data(100, 0)]
1.37 ms ± 26.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

%timeit random_state_data_python(1000, 0)
272 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit [a.tolist() for a in random_state_data(1000, 0)]
16.8 ms ± 144 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by fjetter** [comment] 2023-06-14 12:32
I'm fine with this but it's quite possible that people do not have numpy installed when using bags. This is not an obvious requirement and the python implementation is indeed rather slow. I still believe it's worthwhile to consider rolling this back to seeds only which would be fast enough in python as well. I don't have sufficient context to understand why the full state initialization was necessary in the first place.
You already pointed out that your approach was faster https://github.com/dask/dask/issues/1684#issuecomment-255318057 ;)

**Closed** 2023-07-13 18:10 UTC
Labels: needs triage
