### ISSUE TITLE
Environment variables are not being picked up

### ISSUE THREAD

**Issue by cicdw** [dask/dask#4784] opened 2019-05-08 22:19 UTC
It appears that CLI environment variable behavior is different in the newest release of `dask` 1.2.2.

Specifically, if you set up an environment with `distributed==1.28.0` and `dask==1.2.1`, the following commands work as expected:
```
dask-scheduler
## distributed.scheduler - INFO -   Scheduler at:      tcp://10.0.0.41:8786

DASK_SCHEDULER_ADDRESS=tcp://10.0.0.41:8786 dask-worker
```

However, if you upgrade to `dask==1.2.2`, an error is raised, suggesting that the environment variable is not being picked up correctly:
```
dask-scheduler
## distributed.scheduler - INFO -   Scheduler at:      tcp://10.0.0.41:8786

DASK_SCHEDULER_ADDRESS=tcp://10.0.0.41:8786 dask-worker

ValueError: Need to provide scheduler address like
dask-worker SCHEDULER_ADDRESS:8786
```

This environment variable is how [dask-kubernetes spins up dask workers](https://github.com/dask/dask-kubernetes/blob/13ba99ca852817d1f823bfcede94c60d7da923b7/dask_kubernetes/core.py#L207-L208).

**Comment by cicdw** [comment] 2019-05-08 22:21
I assume this is being caused by [this commit](https://github.com/dask/dask/commit/cd1acd64afd9ad48c3068ef46f2c11e8299d2e3e)?

**Comment by jrbourbeau** [comment] 2019-05-09 01:28
Thanks for the report @cicdw, I'm able to reproduce. The issue is arising here

https://github.com/dask/distributed/blob/1b32bd30201ef6ced5029180143d2c37b393b586/distributed/cli/dask_worker.py#L210-L212

After the changes in #4742, the `DASK_SCHEDULER_ADDRESS` environment variable gets added to `dask.config.config` with the key `scheduler_address` instead of `scheduler-address`. Perhaps we should use `dask.config.get('scheduler-address')`, which is agnostic to hyphen/underscores, here. 

cc @jcrist

**Comment by jcrist** [comment] 2019-05-09 01:34
> Perhaps we should use dask.config.get('scheduler-address'), which is agnostic to hyphen/underscores, here.

Yeah, that's a bug in how distributed is using `dask.config`. No code should ever work with the raw `config` dict, but instead use the accessor methods. Would either of you care to make a PR changing this?

**Comment by jrbourbeau** [comment] 2019-05-09 01:35
I'm on it now

**Comment by jrbourbeau** [comment] 2019-05-09 02:46
Hmmm looks like `distributed.config.get` isn't agnostic to hyphen/underscores

```bash
DASK_SCHEDULER_ADDRESS=tcp://10.130.178.38:8786 ipython
```
```python
In [1]: from distributed.config import config                                                                                        

In [2]: config.get('scheduler_address')                                                                                              
Out[2]: 'tcp://10.130.178.38:8786'

In [3]: config.get('scheduler-address')                                                                                              

In [4]: type(config.get('scheduler-address'))                                                                                        
Out[4]: NoneType
```

**Comment by jcrist** [comment] 2019-05-09 03:00
That's the raw dict again (look at `type(config)`). You should just use `dask.config.get`.

**Comment by cicdw** [comment] 2019-05-09 05:32
Awesome, just getting back and seeing this - thank you both!  It looks like https://github.com/dask/distributed/pull/2676 is headed in the right direction, but let me know if I need to chip in anywhere and I'd be happy to.

**Comment by mrocklin** [comment] 2019-05-09 13:03
That PR is now in.  We should probably push out a bugfix release.

One concern is that I just merged a few breaking changes, and was hoping to let them simmer a while, but things are probably ok anyway.

**Comment by jrbourbeau** [comment] 2019-05-09 14:40
Just to clarify, we're okay doing a bugfix release for `distributed` today? If so, I'm happy to manage it

**Comment by mrocklin** [comment] 2019-05-09 14:43
In my ideal world we would `git checkout v1.2.2`, then apply your patch, and then push that to PyPI, ignoring the commits that were recently merged since the last release.  We would then not merge this into to mainline (it's already there in the future).  

However, I don't know if this approach has negative consequences down the line (Dask has always had a strictly linear history).  cc @jakirkham, I suspect that he has more experience here and may have thoughts?

**Comment by cicdw** [comment] 2019-05-09 15:40
I'm sure this affects others, but FWIW we are able to temporarily work around this.

**Comment by mrocklin** [comment] 2019-05-13 14:50
OK, this is affecting other people now (this came up I think in the pangeo gitter chat).  As mentioned a couple comments above I'd like to issue a bugfix release using only this commit on top of the last release.  This won't be in the mainline history.  @jakirkham at one point when I suggested doing this before you raised concerns, but I admit I don't recall them.  Is this going to cause some havoc if I branch off from mainline and do a release from there?

I plan to do this in 24 hours anyway if I don't hear a response.

**Comment by TomAugspurger** [comment] 2019-05-13 14:57
@mrocklin IIRC we did this for 0.17.5: https://github.com/dask/dask/issues/3503. I don't think it caused any issues.

**Comment by jakirkham** [comment] 2019-05-13 17:41
If this an active discussion can I ask that we please reopen it (am also asking this for future cases like this), it appears I’ve missed a few pings here and it’s most likely because it was closed.

**Comment by mrocklin** [comment] 2019-05-13 17:56
Yes.  I've reopened (and please feel free to reopen issues yourself in the future).

**Comment by jakirkham** [comment] 2019-05-13 18:28
Sure, just asking as a matter of procedure that we reopen issues if we think there is still something actionable. Happy to do my part in this as well. Otherwise people (including myself) are likely to miss that there is something to do. Thanks in advance 🙂

**Comment by jakirkham** [comment] 2019-05-13 18:32
Branching out for a patch release seems fine to me. I think projects that do branches for different versions (e.g. NumPy) usually branch at every minor release. Though their release process may be a bit too complex for our needs.

As we are using versioneer, it is nice to merge the patch release back into the history so versioneer gets the version correct on mainline.

**Comment by mrocklin** [comment] 2019-05-14 15:21
With the recent release, I suspect that this is now resolved.  Closing

**Closed by mrocklin** 2019-05-14 15:21 UTC

**Comment by jrbourbeau** [comment] 2019-05-14 15:33
Thanks for pushing this out @mrocklin

**Comment by cicdw** [comment] 2019-05-14 15:40
Thanks everyone!
