### ISSUE TITLE
dask/array/tests/test_creation.py::test_pad_3d_data[mean-pad_widths1-float32] FAILED

### ISSUE THREAD

**Issue by mgorny** [dask/dask#6477] opened 2020-08-01 06:56 UTC
**What happened**:

One of the tests fails in 2.22.0 release:

```
==================================================================== FAILURES =====================================================================
___________________________________________________ test_pad_3d_data[mean-pad_widths1-float32] ____________________________________________________

dtype = <class 'numpy.float32'>, pad_widths = (2,), mode = 'mean'

    @pytest.mark.parametrize("dtype", [np.uint8, np.int16, np.float32, bool])
    @pytest.mark.parametrize(
        "pad_widths", [2, (2,), (2, 3), ((2, 3),), ((3, 1), (0, 0), (2, 0))]
    )
    @pytest.mark.parametrize(
        "mode",
        [
            "constant",
            "edge",
            pytest.param(
                "linear_ramp",
                marks=pytest.mark.skipif(
                    not _numpy_118, reason="numpy changed pad behaviour"
                ),
            ),
            "maximum",
            "mean",
            "minimum",
            pytest.param(
                "reflect",
                marks=pytest.mark.skip(
                    reason="Bug when pad_width is larger than dimension: https://github.com/dask/dask/issues/5303"
                ),
            ),
            pytest.param(
                "symmetric",
                marks=pytest.mark.skip(
                    reason="Bug when pad_width is larger than dimension: https://github.com/dask/dask/issues/5303"
                ),
            ),
            pytest.param(
                "wrap",
                marks=pytest.mark.skip(
                    reason="Bug when pad_width is larger than dimension: https://github.com/dask/dask/issues/5303"
                ),
            ),
            pytest.param("median", marks=pytest.mark.skip(reason="Not implemented"),),
            pytest.param(
                "empty",
                marks=pytest.mark.skip(
                    reason="Empty leads to undefined values, which may be different"
                ),
            ),
        ],
    )
    def test_pad_3d_data(dtype, pad_widths, mode):
        np_a = np.arange(2 * 3 * 4).reshape(2, 3, 4).astype(dtype)
        da_a = da.from_array(np_a, chunks="auto")
    
        np_r = np.pad(np_a, pad_widths, mode=mode)
>       da_r = da.pad(da_a, pad_widths, mode=mode)

dask/array/tests/test_creation.py:824: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dask/array/creation.py:1216: in pad
    return pad_stats(array, pad_width, mode, stat_length)
dask/array/creation.py:1120: in pad_stats
    result_idx = result_idx.mean(axis=axes, keepdims=True)
dask/array/core.py:2024: in mean
    out=out,
dask/array/reductions.py:586: in mean
    dt = getattr(np.mean(np.empty(shape=(1,), dtype=a.dtype)), "dtype", object)
<__array_function__ internals>:6: in mean
    ???
/usr/lib64/python3.6/site-packages/numpy/core/fromnumeric.py:3373: in mean
    out=out, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

a = array([nan], dtype=float32), axis = None, dtype = None, out = None, keepdims = False

    def _mean(a, axis=None, dtype=None, out=None, keepdims=False):
        arr = asanyarray(a)
    
        is_float16_result = False
        rcount = _count_reduce_items(arr, axis)
        # Make this warning show up first
        if rcount == 0:
            warnings.warn("Mean of empty slice.", RuntimeWarning, stacklevel=2)
    
        # Cast bool, unsigned int, and int to float64 by default
        if dtype is None:
            if issubclass(arr.dtype.type, (nt.integer, nt.bool_)):
                dtype = mu.dtype('f8')
            elif issubclass(arr.dtype.type, nt.float16):
                dtype = mu.dtype('f4')
                is_float16_result = True
    
>       ret = umr_sum(arr, axis, dtype, out, keepdims)
E       RuntimeWarning: invalid value encountered in reduce

/usr/lib64/python3.6/site-packages/numpy/core/_methods.py:160: RuntimeWarning
```

**What you expected to happen**:

I expected the test to pass, I guess.

**Anything else we need to know?**:

This is with numpy 1.19.1.

**Environment**:

- Dask version: 2.22.0
- Python version: 3.6.10
- Operating System: Gentoo Linux
- Install method (conda, pip, source): package manager (source)

**Comment by gforsyth** [comment] 2020-08-03 13:29
Hey @mgorny -- thanks for reporting!  I can't reproduce this locally, but this does look like a bug we've seen pop up sporadically in CI that we've had trouble reproducing.

Does this test fail reliably?  Could you provide a list of the various package versions you're using if it does fail reliably?  And could you also send the output of `numpy.show_config()`?

**Comment by mgorny** [comment] 2020-08-03 15:41
I can't reproduce right now. It might have something to do with high system load at the time. Or with the fact that I did cleanup unnecessary dependencies from my system today. I'll let you know if I can hit it again.

```
system_info:
  NOT AVAILABLE
accelerate_info:
  NOT AVAILABLE
blas_info:
    libraries = ['cblas', 'blas']
    library_dirs = ['/usr/lib64']
    include_dirs = ['/usr/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['cblas', 'blas']
    library_dirs = ['/usr/lib64']
    include_dirs = ['/usr/include']
    language = c
flame_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack']
    library_dirs = ['/usr/lib64']
    language = f77
lapack_opt_info:
    libraries = ['lapack', 'cblas', 'blas']
    library_dirs = ['/usr/lib64']
    language = c
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    include_dirs = ['/usr/include']
```

**Comment by ncclementi** [comment] 2021-09-16 01:25
@mgorny and @gforsyth checking in here. I've personally haven't seen this on the CI but I might be missing something, I can't reproduce locally so I'm wondering, Is this issue still an issue or we should close it?

**Comment by mgorny** [comment] 2021-09-16 06:55
I haven't seen it since, so feel free to close.

**Closed** 2021-09-16 14:06 UTC
