### ISSUE TITLE
Strange ValueError when computing on Series of floats

### ISSUE THREAD

**Issue by fonnesbeck** [dask/dask#1816] opened 2016-11-28 15:11 UTC
After loading a largish dataset into a dask DataFrame, I attempt to summarize a numeric column by calculating the min and max:

    dd.compute(raw_data.weight.min(), raw_data.weight.max())

however, I get a `ValueError` on this computation, which seems to suggest there is date information in the column:

```
/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, queue, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, **kwargs)
    479                     _execute_task(task, data)  # Re-execute locally
    480                 else:
--> 481                     raise(remote_exception(res, tb))
    482             state['cache'][key] = res
    483             finish_task(dsk, key, state, results, keyorder.get)

ValueError: could not convert string to float: '03/01/2013'

Traceback
---------
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/dask/async.py", line 263, in execute_task
    result = _execute_task(task, data)
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/dask/async.py", line 245, in _execute_task
    return func(*args2)
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/dask/compatibility.py", line 47, in apply
    return func(*args, **kwargs)
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/dask/dataframe/csv.py", line 49, in bytes_read_csv
    coerce_dtypes(df, dtypes)
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/dask/dataframe/csv.py", line 74, in coerce_dtypes
    df[c] = df[c].astype(dtypes[c])
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/core/generic.py", line 3054, in astype
    raise_on_error=raise_on_error, **kwargs)
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/core/internals.py", line 3168, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/core/internals.py", line 3035, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/core/internals.py", line 462, in astype
    values=values, **kwargs)
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/core/internals.py", line 505, in _astype
    values = _astype_nansafe(values.ravel(), dtype, copy=True)
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/pandas/types/cast.py", line 537, in _astype_nansafe
    return arr.astype(dtype)
```

But, if I load the same dataset into a Pandas DataFrame, the column is numeric as expected:

```
>>> df.weight.mean()

206.02593543777544
```

Running Dask 0.11.1 on Python 3.5.2 (Anaconda) on macOS 10.12.

**Comment by jcrist** [comment] 2016-11-28 15:23
Hmmm, that is strange. I'd need to see the data (or a fake subset that reproduces) to debug. Alternatively, if you wanted to debug locally, using the synchronous scheduler and `pdb` can help. I usually run `ipython --pdb -i mytestfile.py`, with the following at the top of the test file:

```
import dask
dask.set_options(get=dask.get)
```

That will drop you into a `pdb` session upon error.

**Comment by fonnesbeck** [comment] 2016-11-28 15:36
I can't share the data because it is hospital patient information, but [here is a Gist with a little more info](https://gist.github.com/fonnesbeck/bc55b3f47e7c4865f602a887496d1e59).

**Comment by mrocklin** [comment] 2016-11-28 15:45
I wouldn't be surprised if the error came from some other column that you
were loading in on the side as well.  I second Jim's suggestion to try
dask.set_options(get=dask.get) .  I think that will help you to identify
the error quickly.

On Mon, Nov 28, 2016 at 10:36 AM, Chris Fonnesbeck <notifications@github.com

**Comment by fonnesbeck** [comment] 2016-11-28 15:48
I will poke around. Thanks.

**Comment by fonnesbeck** [comment] 2016-11-28 16:08
Its definitely coming from another column, but its unclear why this should matter if I am isolating a particular column and executing a summary method on it. Why would it want to convert some other column of dates into floats in order to do this?

**Comment by mrocklin** [comment] 2016-11-28 16:10
Perhaps in calling read_csv you're triggering computations you don't need?
  Perhaps isolate down to columns that you do need with use_cols=[...] ?

On Mon, Nov 28, 2016 at 11:08 AM, Chris Fonnesbeck <notifications@github.com

**Comment by jrwalk** [comment] 2017-05-01 20:53
I have been able to reproduce a similar error in dask 0.14.1, python 3.5.2, OSX 10.11.4.

The table contains a mix of string and numeric data.  Computing a trivial function mapping on a numeric column:

```python
In [6]: data.x.map(lambda x: int(x)).compute()
/usr/local/anaconda3/lib/python3.5/site-packages/dask/async.py:266: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  result = _execute_task(task, data)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-885d1124eb4f> in <module>()
----> 1 data.x.map(lambda x: int(x)).compute()

/usr/local/anaconda3/lib/python3.5/site-packages/dask/base.py in compute(self, **kwargs)
     93             Extra keywords to forward to the scheduler ``get`` function.
     94         """
---> 95         (result,) = compute(self, traverse=False, **kwargs)
     96         return result
     97 

/usr/local/anaconda3/lib/python3.5/site-packages/dask/base.py in compute(*args, **kwargs)
    200     dsk = collections_to_dsk(variables, optimize_graph, **kwargs)
    201     keys = [var._keys() for var in variables]
--> 202     results = get(dsk, keys, **kwargs)
    203 
    204     results_iter = iter(results)

/usr/local/anaconda3/lib/python3.5/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, **kwargs)
     74     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
     75                         cache=cache, get_id=_thread_get_id,
---> 76                         **kwargs)
     77 
     78     # Cleanup pools associated to dead threads

/usr/local/anaconda3/lib/python3.5/site-packages/dask/async.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, raise_on_exception, rerun_exceptions_locally, callbacks, dumps, loads, **kwargs)
    498                     _execute_task(task, data)  # Re-execute locally
    499                 else:
--> 500                     raise(remote_exception(res, tb))
    501             state['cache'][key] = res
    502             finish_task(dsk, key, state, results, keyorder.get)

ValueError: invalid literal for int() with base 10: '   '
```
results in an error, evidently from another column.  This was corrected by restricting the data read columns, e.g. 

```python
In [1]: data = dd.read_csv("data.csv",usecols=['x','y'])
```

However, I encountered another interesting variant on the error -- when forcing the read to be of type string, 

```python
In [1]: data = dd.read_csv("data.csv",dtype=str,usecols=['x','y'])
In [2]: data.x.map(lambda x: int(x).compute()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/anaconda3/lib/python3.5/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname)
    147     try:
--> 148         yield
    149     except Exception as e:

/usr/local/anaconda3/lib/python3.5/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3044     with raise_on_meta_error(funcname(func)):
-> 3045         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3046 

/usr/local/anaconda3/lib/python3.5/site-packages/dask/utils.py in __call__(self, obj, *args, **kwargs)
    937     def __call__(self, obj, *args, **kwargs):
--> 938         return getattr(obj, self.method)(*args, **kwargs)
    939 

/usr/local/anaconda3/lib/python3.5/site-packages/pandas/core/series.py in map(self, arg, na_action)
   2176         else:
-> 2177             new_values = map_f(values, arg)
   2178 

pandas/src/inference.pyx in pandas.lib.map_infer (pandas/lib.c:66124)()

<ipython-input-9-885d1124eb4f> in <lambda>(x)
----> 1 data.x.map(lambda x: int(x)).compute()

ValueError: invalid literal for int() with base 10: 'foo'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-9-885d1124eb4f> in <module>()
----> 1 data.x.map(lambda x: int(x)).compute()

/usr/local/anaconda3/lib/python3.5/site-packages/dask/dataframe/core.py in map(self, arg, na_action, meta)
   1751         dsk.update(self.dask)
   1752         if meta is no_default:
-> 1753             meta = _emulate(M.map, self, arg, na_action=na_action)
   1754         else:
   1755             meta = make_meta(meta)

/usr/local/anaconda3/lib/python3.5/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3043     """
   3044     with raise_on_meta_error(funcname(func)):
-> 3045         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3046 
   3047 

/usr/local/anaconda3/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)
     75                 value = type()
     76             try:
---> 77                 self.gen.throw(type, value, traceback)
     78                 raise RuntimeError("generator didn't stop after throw()")
     79             except StopIteration as exc:

/usr/local/anaconda3/lib/python3.5/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname)
    159                ).format(" in `{0}`".format(funcname) if funcname else "",
    160                         repr(e), tb)
--> 161         raise ValueError(msg)
    162 
    163 

ValueError: Metadata inference failed in `map`.

Original error is below:
------------------------
ValueError("invalid literal for int() with base 10: 'foo'",)

Traceback:
---------
  File "/usr/local/anaconda3/lib/python3.5/site-packages/dask/dataframe/utils.py", line 148, in raise_on_meta_error
    yield
  File "/usr/local/anaconda3/lib/python3.5/site-packages/dask/dataframe/core.py", line 3045, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/usr/local/anaconda3/lib/python3.5/site-packages/dask/utils.py", line 938, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.5/site-packages/pandas/core/series.py", line 2177, in map
    new_values = map_f(values, arg)
  File "pandas/src/inference.pyx", line 1207, in pandas.lib.map_infer (pandas/lib.c:66124)
  File "<ipython-input-9-885d1124eb4f>", line 1, in <lambda>
    data.x.map(lambda x: int(x)).compute()
```

There are, of course, no entries with value "foo" in the data... they seem to have been inserted during the CSV read?

**Comment by jcrist** [comment] 2017-05-01 21:00
This is a duplicate of https://github.com/dask/dask/issues/2265, and is a non-issue (besides our docs maybe needing improvement :)).

For methods that take user provided functions, dask tries to infer the metadata (column names, dtypes, etc...) by running the function on some fake data that matches the dtype. For columns with object type, the string `"foo"` is used. When it works this is nice, but for some functions (as you've found) this will fail. In these cases you'll need to specify the metadata yourself.

```python
>>> data.x.map(int, meta=('x', int))
```

For more information please see the doc for [`map_partitions`](http://dask.pydata.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.map_partitions) (will add to `map` as well).

**Comment by jcrist** [comment] 2017-05-01 21:40
> (will add to map as well).

Done in https://github.com/dask/dask/pull/2282

**Comment by jrwalk** [comment] 2017-05-01 21:53
@jcrist thanks for the quick reply.  Can confirm this corrected the issue, makes perfect sense to supply the explicit metadata :)  This leaves everything down to my version of @fonnesbeck's original issue, which (I assume) is the system choking on trying to apply the imputed column types on `compute()`.  Filtering via `usecols` or supplying appropriate metadata seems to have corrected it.

**Comment by jcrist** [comment] 2017-05-02 21:44
@fonnesbeck : closing for now as stale. If this is still an issue for you feel free to reopen (preferably with a reproducible test case :))

**Closed by jcrist** 2017-05-02 21:44 UTC
Labels: dataframe
