### ISSUE TITLE
Comparing two Dask arrays for equality 

### ISSUE THREAD

**Issue by bamal** [dask/dask#4399] opened 2019-01-17 21:45 UTC
Hello everyone !

I am trying to use the equality operation  (`==`) between dask arrays but I had an error. Now I am using Numpy arrays implementation instead.
I will post here (1) the code with Numpy arrays,  (2) the code with Dask arrays which is buggy, (3) the variables description from the Debugger and (4) the output error. 

### 1.  This is the Numpy array-based implementation 
```
masked_parts = np.copy(parts)
for sw_idx in range(0, n_sw):
    # extract only the voxels in the same cluster of the seed
     masked_parts[sw_idx, :] = masked_parts[sw_idx, : ] == masked_parts[sw_idx, :][mask_medoid]
```
### 2. This is the Dask array-based implementation
```
masked_parts = parts
for sw_idx in range(0, n_sw):
    # extract only the voxels in the same cluster of the seed
     masked_parts[sw_idx, :] = masked_parts[sw_idx, : ] == masked_parts[sw_idx, :][mask_medoid]
```
### 3. The variables 

_masked_parts: {Array} Dask Array, shape(9, 57k), dtype: int_
_mask_medoid: {Ndarray}[False, False, True, ... True], shape(57k), dtype: bool_

### 4. The output error
../dynpar/dynamic_parcellation.py:74: in __mask_region_for_medoid
    masked_parts[sw_idx, :] = masked_parts[sw_idx, :] == masked_parts[sw_idx, :][mask_medoid]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = dask.array<array, shape=(9, 57790), dtype=int64, chunksize=(9, 7223)>
key = (0, slice(None, None, None))
value = dask.array<eq, shape=(57790,), dtype=bool, chunksize=(7223,)>

    def __setitem__(self, key, value):
        from .routines import where
        if isinstance(key, Array):
            if isinstance(value, Array) and value.ndim > 1:
                raise ValueError('boolean index array should have 1 dimension')
            y = where(key, value, self)
            self.dtype = y.dtype
            self.dask = y.dask
            self.name = y.name
            self._chunks = y.chunks
            return self
        else:
            raise NotImplementedError("Item assignment with %s not supported)
E           NotImplementedError: Item assignment with <class 'tuple'> not supported

../../../.local/lib/python3.6/site-packages/dask/array/core.py:1221: NotImplementedError
------------------------------------

So it seems that this is not supported yet by Dask arrays ... 
If someone have thoughts related to how to implement my function differently using  dask arrays , I would appreciate any comments !

Thanks !

**Comment by mrocklin** [comment] 2019-01-17 22:19
Thanks for the bug report @bamal .  Can I ask you to provide a minimal reproducible example?  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

This will help everyone be able to reproduce and help you with your problem more quickly.

**Comment by jakirkham** [comment] 2019-02-09 21:15
FWICT the existing example is pretty minimal, but this may highlight the issue more clearly. In other words, this doesn't appear to be an issue of equality, but one of assignment. @bamal, would you be ok with having this issue retitled to reflect this?


```python
In [1]: import dask.array as da                                                 

In [2]: a = da.ones((10, 11), chunks=5)                                         

In [3]: a[5, :] = 0                                                             
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-3-0bcebd5d81b6> in <module>
----> 1 a[5, :] = 0

/zopt/conda3/envs/nanshenv3/lib/python3.6/site-packages/dask/array/core.py in __setitem__(self, key, value)
   1219         else:
   1220             raise NotImplementedError("Item assignment with %s not supported"
-> 1221                                       % type(key))
   1222 
   1223     def __getitem__(self, index):

NotImplementedError: Item assignment with <class 'tuple'> not supported
```

**Comment by mrocklin** [comment] 2019-02-19 02:29
> would you be ok with having this issue retitled to reflect this?

@jakirkham I encourage you to just change things as you see fit.  You probably have more understanding and context here than most people who raise issues.  I encourage you to feel comfortable taking charge.

Is there something to be done for this issue?  If so, can I ask you to briefly summarize it?

**Comment by safijari** [comment] 2019-09-13 23:35
I just started looking into `dask` as a way to scale some code beyond the limits of available ram and slammed headfirst into this problem. Both tuple and slice based item assignment are not a thing yet (I assume the focus is more on reading data than writing it?).

Is there a fundamental issue blocking the implementation of mutation?

**Comment by ashwinvis** [comment] 2019-10-11 05:00
Same here, the [only workaround is to use `dask.array.concatenate`](https://stackoverflow.com/a/36143234) and that is what we had to do for [fluidfft (unfinished API for dask FFT)](https://bitbucket.org/fluiddyn/fluidfft/src/2824f4f2f667a1ce79301d37219ef0510aeac57c/fluidfft/fft2d/operators.py#lines-394:406). I do hope there is a better way as this approach requires rewriting algorithms. If this is sorted out `dask.array` can truly be a drop-in replacement for `numpy`

**Comment by ashwinvis** [comment] 2021-04-14 08:14
Since #2000 is now closed, this issue can be closed as well?

**Comment by jakirkham** [comment] 2021-04-14 17:43
Yep I think so. The example I showed above runs without issues. If there are other remaining issues, please feel free to raise them separately. Thanks! 😄

**Closed by jakirkham** 2021-04-14 17:43 UTC
Labels: array
