### ISSUE TITLE
reading pandas dataframe (pyarrow) with time zone aware timestamp column loses timezone with read_parquet

### ISSUE THREAD

**Issue by keua** [dask/dask#6347] opened 2020-06-26 13:43 UTC
**What happened**:

When reading a pandas timezone aware dataframe written with pyarrow in a parquet file with snappy compression the time zone
in the dataframe is lost.

**What you expected to happen**:
the timezone aware column keeps timezone

**Minimal Complete Verifiable Example**:

Here below my example that reading with pandas works well and reading with desk doesnt.

```python
df = pd.read_parquet('2020-05-27.parquet')
#results in
#0       2020-05-27 00:00:10.204000+02:00
#1       2020-05-27 00:00:09.770000+02:00
#2       2020-05-27 00:00:40.444000+02:00
#3       2020-05-27 00:00:52.088000+02:00
#4       2020-05-27 00:01:03.304000+02:00

df = dd.read_parquet('2020-05-27.parquet', engine='pyarrow').compute()
# restuls in
# 0        2020-05-26 22:00:10.204000+00:00
# 1        2020-05-26 22:00:09.770000+00:00
# 2        2020-05-26 22:00:40.444000+00:00
# 3        2020-05-26 22:00:52.088000+00:00
# 4        2020-05-26 22:01:03.304000+00:00
```

**Anything else we need to know?**:

**Environment**:

- Dask version:  2.11.0
- Python version: 3.7
- Operating System: linux
- Install method (conda, pip, source): conda

**Comment by gforsyth** [comment] 2020-06-26 14:06
Thanks for reporting @keua !  If you can put together a reproducible example for us it will be a lot easier for us to debug.  There are some tips here: https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by keua** [comment] 2020-06-26 14:37
@gforsyth  In the link you share says to not share data but in this specific case my problem is with parquet files, what do I do?

**Comment by gforsyth** [comment] 2020-06-26 14:42
Hey @keua -- a code block that first creates a dataframe with timezone offsets, then saves it to parquet, then loads from parquet will work well.  The easier it is for us to copy and paste a code block and try it out, the easier it is to pick up the issue.  (And also helps us confirm that we see the same failure)

**Comment by keua** [comment] 2020-06-26 14:55
There you go, I hope that can make easy the follow up
```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({'t': ['2017-02-03', '2017-03-03', '2017-01-01']})
df['t'] = pd.to_datetime(df.t, utc=True).dt.tz_convert('Europe/Brussels')
print(df)
df.to_parquet('test.parquet', engine='pyarrow')
df = dd.read_parquet('test.parquet', engine='pyarrow').compute()
print(df)
```

**Comment by gforsyth** [comment] 2020-06-26 16:11
Great, thanks @keua !

so on current master, I can't reproduce this:

```
In [1]: import pandas as pd
   ...: import dask.dataframe as dd
   ...:
   ...: df = pd.DataFrame({'t': ['2017-02-03', '2017-03-03', '2017-01-01']})
   ...: df['t'] = pd.to_datetime(df.t, utc=True).dt.tz_convert('Europe/Brussels')
   ...: print(df)
   ...: df.to_parquet('test.parquet', engine='pyarrow')
   ...: df = dd.read_parquet('test.parquet', engine='pyarrow').compute()
   ...: print(df)
                          t
0 2017-02-03 01:00:00+01:00
1 2017-03-03 01:00:00+01:00
2 2017-01-01 01:00:00+01:00
                          t
0 2017-02-03 01:00:00+01:00
1 2017-03-03 01:00:00+01:00
2 2017-01-01 01:00:00+01:00
```

As a first check, can you try upgrading `pyarrow`?

I'm currently running:
```
(daskdev)   ~ $ python -c "import pyarrow; print(pyarrow.__version__)"
0.17.1
(daskdev)   ~ $ python -c "import pandas; print(pandas.__version__)"
1.0.1
(daskdev)   ~ $ python -c "import dask; print(dask.__version__)"
2.19.0+6.g7138f470f
```

**Comment by keua** [comment] 2020-06-26 16:18
I just upgrade to Dask 2.19.0 and it is now working thanks !

**Comment by gforsyth** [comment] 2020-06-26 16:28
Awesome!  Closing this out, then.

**Closed by gforsyth** 2020-06-26 16:28 UTC
Labels: dataframe, io
