### ISSUE TITLE
Distributed Dask Fails with to_sql

### ISSUE THREAD

**Issue by saul-gush** [dask/dask#6722] opened 2020-10-09 16:21 UTC
When I run the below without `client = Client('127.0.0.1:8786')` it works. 

```python
from dask.distributed import Client
# client = Client('127.0.0.1:8786')

import dask.dataframe as dd

df = dd.read_csv('./propdata/pp-complete.csv')
uristring = "postgresql://postgres@127.0.0.1:5432/mydb?sslmode=disable"
df.to_sql('test', uristring)
```

When I run it with distributed by uncommenting client = Client('127.0.0.1:8786'), I get the following error: 
```
Traceback (most recent call last):
  File "dask_prop_load_sql.py", line 32, in <module>
    df.to_sql('test', uristring)
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/dask/dataframe/core.py", line 1454, in to_sql
    parallel=parallel,
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/dask/dataframe/io/sql.py", line 414, in to_sql
    dask.compute(result)
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/dask/base.py", line 452, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/distributed/client.py", line 2725, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/distributed/client.py", line 1992, in gather
    asynchronous=asynchronous,
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/distributed/client.py", line 833, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/distributed/client.py", line 1851, in _gather
    raise exception.with_traceback(traceback)
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/dask/dataframe/io/sql.py", line 378, in make_meta
    return meta.to_sql(**kwargs)
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 2615, in to_sql
    method=method,
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/pandas/io/sql.py", line 598, in to_sql
    method=method,
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/pandas/io/sql.py", line 1827, in to_sql
    table.create()
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/pandas/io/sql.py", line 721, in create
    if self.exists():
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/pandas/io/sql.py", line 708, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/pandas/io/sql.py", line 1838, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
  File "/Users/saul/code/dask/venv/lib/python3.7/site-packages/pandas/io/sql.py", line 1679, in execute
    cur = self.con.cursor()
```

**Environment**:

- Dask version: 2.30.0
- Python version: 3.7
- Operating System: Mac
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment] 2020-10-12 15:54
Thanks for opening this issue @saul-gush. In order to figure out what's going on, we'll need to have a reproducible example. In this case, we'll also what to know more about the scheduler that you have at `'127.0.0.1:8786'` is that just a `LocalCluster`?

**Comment by ncclementi** [comment] 2021-08-20 17:13
@saul-gush I will close this issue, due to lack of information. If you are still having this problem? Please feel free to re-open with a minimal reproducible example as described [here](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)

**Closed by ncclementi** 2021-08-20 17:13 UTC
Labels: needs info
