### ISSUE TITLE
Writing to parquet with `.set_index("col", drop=False)` yields: `ValueError(f"cannot insert {column}, already exists")`

### ISSUE THREAD

**Issue by asmith26** [dask/dask#9328] opened 2022-07-28 15:30 UTC
**What happened**:
Writing to parquet with `.set_index("col", drop=False)` yields: `ValueError(f"cannot insert {column}, already exists")`. Interestingly when `drop=True` it works.

**What you expected to happen**:
I thought I would be able to set_index with `drop=False`.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd

(dd.from_pandas(pd.DataFrame({"Idx": list(range(10))}), npartitions=1)
 .set_index("Idx", drop=False)
 .to_parquet("ddf.parquet"))
```

**Anything else we need to know?**:
Thanks for any help! :)

**Environment**:

- Dask version: 2022.7.1  
- Python version: 3.10.4
- Operating System: Ubuntu
- Install method (conda, pip, source): mamba

**Comment by ncclementi** [comment] 2022-07-28 17:21
@asmith26 Thank you for reporting this. I can reproduce but it's not super clear to me what's happening. By looking at the traceback. 
<details>
<summary>Traceback:</summary>

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/Documents/git/my_forks/dask/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    194     try:
--> 195         yield
    196     except Exception as e:

~/Documents/git/my_forks/dask/dask/dataframe/core.py in _emulate(func, udf, *args, **kwargs)
   6425     with raise_on_meta_error(funcname(func), udf=udf):
-> 6426         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   6427 

~/Documents/git/my_forks/dask/dask/utils.py in __call__(self, _methodcaller__obj, *args, **kwargs)
   1069     def __call__(self, __obj, *args, **kwargs):
-> 1070         return getattr(__obj, self.method)(*args, **kwargs)
   1071 

~/mambaforge/envs/dask-dev/lib/python3.9/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    310                 )
--> 311             return func(*args, **kwargs)
    312 

~/mambaforge/envs/dask-dev/lib/python3.9/site-packages/pandas/core/frame.py in reset_index(self, level, drop, inplace, col_level, col_fill)
   5838 
-> 5839                 new_obj.insert(0, name, level_values)
   5840 

~/mambaforge/envs/dask-dev/lib/python3.9/site-packages/pandas/core/frame.py in insert(self, loc, column, value, allow_duplicates)
   4439             # Should this be a different kind of error??
-> 4440             raise ValueError(f"cannot insert {column}, already exists")
   4441         if not isinstance(loc, int):

ValueError: cannot insert Idx, already exists

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
/var/folders/1y/ydztfpnd11b6qmvbb8_x56jh0000gn/T/ipykernel_75840/1606690105.py in <module>
----> 1 ddf.to_parquet("ddf.parquet")

~/Documents/git/my_forks/dask/dask/dataframe/core.py in to_parquet(self, path, *args, **kwargs)
   5123         from dask.dataframe.io import to_parquet
   5124 
-> 5125         return to_parquet(self, path, *args, **kwargs)
   5126 
   5127     def to_orc(self, path, *args, **kwargs):

~/Documents/git/my_forks/dask/dask/dataframe/io/parquet/core.py in to_parquet(df, path, engine, compression, write_index, append, overwrite, ignore_divisions, partition_on, storage_options, custom_metadata, write_metadata_file, compute, compute_kwargs, schema, name_function, **kwargs)
    844         real_cols = set(df.columns)
    845         none_index = list(df._meta.index.names) == [None]
--> 846         df = df.reset_index()
    847         if none_index:
    848             df.columns = [

~/Documents/git/my_forks/dask/dask/dataframe/core.py in reset_index(self, drop)
    593             Do not try to insert index into dataframe columns.
    594         """
--> 595         return self.map_partitions(
    596             M.reset_index, drop=drop, enforce_metadata=False
    597         ).clear_divisions()

~/Documents/git/my_forks/dask/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    864         None as the division.
    865         """
--> 866         return map_partitions(func, self, *args, **kwargs)
    867 
    868     @insert_meta_param_description(pad=12)

~/Documents/git/my_forks/dask/dask/dataframe/core.py in map_partitions(func, meta, enforce_metadata, transform_divisions, align_dataframes, *args, **kwargs)
   6493     dfs = [df for df in args if isinstance(df, _Frame)]
   6494 
-> 6495     meta = _get_meta_map_partitions(args, dfs, func, kwargs, meta, parent_meta)
   6496 
   6497     if all(isinstance(arg, Scalar) for arg in args):

~/Documents/git/my_forks/dask/dask/dataframe/core.py in _get_meta_map_partitions(args, dfs, func, kwargs, meta, parent_meta)
   6605         # Use non-normalized kwargs here, as we want the real values (not
   6606         # delayed values)
-> 6607         meta = _emulate(func, *args, udf=True, **kwargs)
   6608         meta_is_emulated = True
   6609     else:

~/Documents/git/my_forks/dask/dask/dataframe/core.py in _emulate(func, udf, *args, **kwargs)
   6424     """
   6425     with raise_on_meta_error(funcname(func), udf=udf):
-> 6426         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   6427 
   6428 

~/mambaforge/envs/dask-dev/lib/python3.9/contextlib.py in __exit__(self, typ, value, traceback)
    135                 value = typ()
    136             try:
--> 137                 self.gen.throw(typ, value, traceback)
    138             except StopIteration as exc:
    139                 # Suppress StopIteration *unless* it's the same exception that

~/Documents/git/my_forks/dask/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    214         )
    215         msg = msg.format(f" in `{funcname}`" if funcname else "", repr(e), tb)
--> 216         raise ValueError(msg) from e
    217 
    218 

ValueError: Metadata inference failed in `reset_index`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
ValueError('cannot insert Idx, already exists')

Traceback:
---------
  File "/Users/ncclementi/Documents/git/my_forks/dask/dask/dataframe/utils.py", line 195, in raise_on_meta_error
    yield
  File "/Users/ncclementi/Documents/git/my_forks/dask/dask/dataframe/core.py", line 6426, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/Users/ncclementi/Documents/git/my_forks/dask/dask/utils.py", line 1070, in __call__
    return getattr(__obj, self.method)(*args, **kwargs)
  File "/Users/ncclementi/mambaforge/envs/dask-dev/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/Users/ncclementi/mambaforge/envs/dask-dev/lib/python3.9/site-packages/pandas/core/frame.py", line 5839, in reset_index
    new_obj.insert(0, name, level_values)
  File "/Users/ncclementi/mambaforge/envs/dask-dev/lib/python3.9/site-packages/pandas/core/frame.py", line 4440, in insert
    raise ValueError(f"cannot insert {column}, already exists")

```
</details>

Something is going on when trying to `reset_index` in to_parquet. `write_index=True` by default and is failing in this line https://github.com/dask/dask/blob/50ab8af982a31b186a8e47597f0ad7e5b59bcab5/dask/dataframe/io/parquet/core.py#L846

That then goes here https://github.com/dask/dask/blob/50ab8af982a31b186a8e47597f0ad7e5b59bcab5/dask/dataframe/core.py#L575-L597

in here drop=False, by default, and it says " Do not try to insert index into dataframe columns." but I don't fully get what's happening. But I do know that the `Idx` because it wasn't dropped is in the dataframe, and maybe this is causing the issue?

@rjzamora Do you know what could be causing the ValueError?

**Comment by rjzamora** [comment] 2022-07-28 18:05
> @rjzamora Do you know what could be causing the ValueError?

My immediate assumption is that the `read_parquet` code doesn't allow an overlap between the set of column names and the set of index names.  I'm sure we can add support for this case, but I'd have to know more about the "real-world" motivation.  The reproducer itself doesn't make much sense, because there is no reason to duplicate a column before writing to Parquet.  There is really no concept of an "index" within the Parquet specification (fastparquet and pyarrow just add extra "pandas metadata" to distinguish which columns should be treated as an index).

Is there a reason you want to store the same data twice, with two different column names? Or is the goal something else entirely?

Thanks for raising this @asmith26 - Hopefully I can help

**Comment by asmith26** [comment] 2022-07-28 18:20
Thanks for the quick responses all!

Regarding real-world motivation, I don't necessarily have to do this and I think I can easily work around it. Essentially I'm writing a pipeline that joins the original data with the processed data, hence at the start of the pipeline I create an `Idx` to track how to join the rows correctly at the end - using the dask.DataFrame index makes the join fast (hence I want to set it), and creating a column `Idx` allows me to keep the `Idx` information throughout my pipeline (in particular I set the dask.DataFrame index to other values throughout the pipeline to help with things like `.map_partitions(...)`.

So not a big problem on my end as I think I can easily work around this, but thought I'd raise an issue in case the behavior is a bug. Thanks again!

**Comment by rjzamora** [comment] 2022-07-28 18:34
>So not a big problem on my end as I think I can easily work around this, but thought I'd raise an issue in case the behavior is a bug. Thanks again!

That makes sense, and I appreciate you raising an issue!  For your workflow, I'd probably do something like `ddf.set_index(ddf["Idx"].rename("Idx_orig"), drop=False)` to persist the original `"Idx"` column with a distinct name (although you would be writing the same data twice if you don't actually modify `"Idx"` after that).

**Comment by asmith26** [comment] 2022-07-28 18:42
Happy to help, and thank you for the code suggestion, I like it thanks!

Happy to use this workaround, so I'm happy to close this issue if helpful - also happy to leave it open if you'd find it helpful for the record/if a fix is required(?)

**Comment by rjzamora** [comment] 2022-07-28 18:47
I'll close this for now, but if others feel there is a good reason to support column/index overlap (or duplicate column names for that matter), then they should feel free to re-open.  However, at the moment it isn't clear to me what Dask *should* do in this case: Ignore the redundant index, or just duplicate the data.

**Closed by rjzamora** 2022-07-28 18:47 UTC
Labels: dataframe, parquet, bug
