### ISSUE TITLE
The "Segmentation fault" error randomly happened when calling Scipy functions written by Fortran

### ISSUE THREAD

**Issue by cnwangfeng** [dask/dask#8904] opened 2022-04-08 01:14 UTC
**What happened**:
The "Segmentation fault" error randomly happened when calling Scipy functions written by Fortran under Dask, especially calling in the Dask context. 

**What you expected to happen**:
No such errors. 

**Minimal Complete Verifiable Example**:

```python
import numpy as np
import dask
from distributed import Client,LocalCluster
import functools
import scipy.special
import scipy.signal



def coordinates(n):
    n2 = n // 2
    if n % 2 == 0:
        return np.mgrid[-n2:n2] / n

def a_safe_func(n):
    # SCIPY Function
    pswf = scipy.special.pro_ang1(
                0,
                0,
                np.pi * 13.5 / 2,
                2 * coordinates(n),
            )[0]
    pswf[0] = 0  # zap NaN

    return pswf.real


def dask_wrapper(func):
    @functools.wraps(func)  # preserves information about the original function
    def wrapper(*args, **kwargs):
        try:
            use_dask = kwargs["use_dask"]
            nout = kwargs["nout"]
        except KeyError:
            use_dask = False
            nout = None

        if use_dask:
            result = dask.delayed(func, nout=nout)(*args, **kwargs)
        else:
            result = func(*args, **kwargs)
        return result

    return wrapper

class Barray:
    def __init__(self,n):
        self._Fb = None
        self._Fn = None
        self.n = n
        self.c = 0.5

    @property
    def Fb(self):
        #if self._Fb is None:
        self._Fb = np.ones(self.n) + a_safe_func(self.n)  
        return self._Fb


def a_func(fb,i,**kwargs):
    return fb

class A_simple(Barray):

    @dask.delayed
    def prepare_facet(self,f):
        return self.Fb

    
    def prepare_facet_new(self,f):
        print("done?",f)
        return self.Fb

def main():
    n=16384
    ba = A_simple(n)
    fb_list = [ba.prepare_facet_new(i) for i in range(2000)]
    fb_list_2 = [ba.prepare_facet_new(i) for i in fb_list]
    print(fb_list_2[0])

if __name__ =="__main__":
    nworker = 5
    njob = 5000
    cluster = LocalCluster(n_workers=nworker,threads_per_worker=1,memory_limit="50GiB")
    client = Client(cluster)
    # in Client context, pro_ang1 get Segmentation fault
    main()

```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2022.1.0
- Python version: Python 3.9/3.8/3.7
- Operating System: Linux Centos7, MacOS 12.3
- Install method (conda, pip, source): conda

<details>
<summary>Cluster Dump State:</summary>

</details>

**Comment by pavithraes** [comment] 2022-04-08 14:20
Hi @cnwangfeng , thanks for opening this issue! I'm not able to reproduce this directly (my jupyterlab kernel does die+restart, but your exact code seems to not use the delayed functions at all during the run?) A more [minimal example](https://stackoverflow.com/help/minimal-reproducible-example) and the complete error traceback will allow us to help you better. :)

It also looks like this is more of a usage question than a bug report or feature request. We encourage people with such questions to ask them at the [Dask Discourse](https://dask.discourse.group/). Would you mind opening a discussion topic about this over there? If you do so, feel free to close this issue and we will continue the conversation on discourse. :)

**Comment by pavithraes** [comment] 2022-04-25 13:48
I'll go ahead and close this, please feel free to re-open if needed!

**Closed by pavithraes** 2022-04-25 13:48 UTC
Labels: needs info

**Comment by cnwangfeng** [comment] 2022-04-26 04:47
Hi @pavithraes , 

Sorry for re-opening the issue. I don't think that we didn't use the delayed functions. ;) May you please try the following codes? I guess that it would be right if you jupyterlab kernel crashed because the issue we presented would make the application crashed. 

`import numpy as np
from distributed import Client,LocalCluster
import scipy.special




def a_safe_func(n):
    coord = np.arange(-n//2,n//2).astype(float)/n
    #print(coord.shape,coord.dtype)
    pswf = scipy.special.pro_ang1(
                0,
                0,
                np.pi * 13.5 / 2,
                2 * coord
            )[0]
    pswf[0] = 0  # zap NaN
    return pswf.real


def main():
    n=8192
    print("call before client context ......")
    for i in range(100):
        tmp = a_safe_func(n)
        print("call %d times"%i)
    print("============================")

    print("setup client")
    nworker = 16
    cluster = LocalCluster(n_workers=nworker,threads_per_worker=1,memory_limit="50GiB")
    client = Client(cluster)
    print("call in client context.......")
    # In this loop, the main thread would be crash, and the get Segmentation fault
    for i in range(100):
        tmp = a_safe_func(n)
        print("call %d times"%i)
    print("============================")

if __name__ =="__main__":
    main()`
