### ISSUE TITLE
Dask dataframe - divisions don't seem to be consistent

### ISSUE THREAD

**Issue by thequackdaddy** [dask/dask#1057] opened 2016-03-18 22:45 UTC
Hello, 

I wanted to point out that the definition of a "division" is not consistent between the different input formats. 

divisions appear to be a tuple which is either

- Style A
  (first index in first division, last index is first division, last index in second division, ... , last index in n-1 division, last index in n division)

- Style B
  (first index in first division, first index in second division, ... , first index in n division, last index in n division)

- Style C
  All divisions are labeled as None. 

I think this is how this is currently set-up...

- read_csv uses Style C
- from_array uses Style B (Except that it skips the last division when the index is already the last record. Based on the logic, I'm not sure this can every happen, actually. See [here](https://github.com/dask/dask/blob/master/dask/dataframe/io.py#L314).
- from_pandas uses Style B
- from_bcolz uses Style B
- from_dask_array uses Style B
- from_castra uses Style A
- read_hdf uses Style C

So which one is the most "correct"? 

Essentially, I'm trying to use a `series.where` statement where if a condition is met, you use one column, otherwise, you use another (the others is actually a sequence in a `from_pandas` array.) I think the fact the divisions are slightly different is breaking this. 

Happy to program a fix. It looks straightforward enough for all but the from_castra and read_hdf. 

Thanks.

---
Update: I started watching march madness too early and messed up some of these

**Comment by mrocklin** [comment] 2016-03-18 22:53
That's unfortunate.  Styles B and C are both correct.  We use style C when we don't have sufficient information to split intelligently (such as happens in read_csv, when we don't know how many lines have passed or can't read values).

Generally the documentation is a good place to go in order to determine intended behavior.  In this case the following section of the dask.dataframe docs: http://dask.readthedocs.org/en/latest/dataframe.html#partitions

> Divisions includes the minimum value of every partition’s index and the maximum value of the last partition’s index.  ... Often we do not have such information about our partitions. When reading CSV files for example we do not know, without extra user input, how the data is divided. In this case .divisions will be all None:

A fix for this would be most welcome.

**Comment by mrocklin** [comment] 2016-03-18 23:24
One way to ensure good behavior in the future would be to add a check inside the `eq` function in `test_dataframe_core`.  That way we could test this broadly throughout the codebase.

**Closed** 2016-04-25 17:18 UTC
Labels: dataframe
