### ISSUE TITLE
Dask Dataframe cannot handle the lazy evaluation of dd.Scalar object in fillna

### ISSUE THREAD

**Issue by DigitalPig** [dask/dask#5461] opened 2019-10-03 22:37 UTC
This issue is somewhat related to #1701 

#1701 reveals the issue when fillna with a dask dataframe ops. In some cases, we have to fill each column using the columnwise ops like `.mean`:

Minimal reproducible example:

```python
from pandas.util.testing import makeMissingDataframe
import dask.dataframe as dd


df_t = makeMissingDataframe(0.8, 1000)

ddf_t = dd.from_pandas(df_t, npartitions=5)

ddf_t.fillna(ddf_t.mean()).compute() # Works
ddf_t["A"].fillna(ddf_t["A"].mean().compute()).compute() # Works

ddf_t["A"].fillna(ddf_t["A"].mean()).compute() # Does not work.

```

**Comment by quasiben** [comment] 2019-10-04 03:01
@DigitalPig Thank you for the report.  The `does not work` line is a duplicate of the line above.  

> ddf_t["A"].fillna(ddf_t["A"].mean().compute()).compute() # Works
ddf_t["A"].fillna(ddf_t["A"].mean()).compute() # Does not work.

Can you post with the problematic line ?

**Comment by mrocklin** [comment] 2019-10-04 09:50
He's saying that passing a `dask.dataframe.Scalar` object into fillna doesn't work, but that passing a concrete value, like a float, does.

**Comment by mrocklin** [comment] 2019-10-04 09:51
Fixed by https://github.com/dask/dask/pull/5463

**Closed** 2019-10-04 10:29 UTC
