### ISSUE TITLE
cannot import name 'compute'

### ISSUE THREAD

**Issue by Abdou24MR** [dask/dask#8837] opened 2022-03-24 00:18 UTC
ImportError                               Traceback (most recent call last)

c:\....\dask\array\__init__.py in <module>()
      1 try:
----> 2     from .blockwise import blockwise, atop
      3     from .core import (

c:\....\dask\array\blockwise.py in <module>()
    287 
--> 288 from .core import new_da_object

c:\....\dask\array\core.py in <module>()
     22 from . import chunk
---> 23 from .. import config, compute
     24 from ..base import (

ImportError: cannot import name 'compute'

**Comment by pavithraes** [comment] 2022-03-24 18:31
Hi @Abdou24MR, thanks for opening this issue. I can't reproduce this with the latest Dask. Could you please share some details about how you're installing Dask, the versions of Python+Dask, your OS, etc.? Since we resolved your other question at #8839 by upgrading Python, did that help resolve this error too?

Also, this looks like more of a usage question than a bug report or feature request. We encourage people with such questions to ask them at the [Dask Discourse](https://dask.discourse.group/). Would you mind opening a discussion topic about this over there? If you do so, feel free to close this issue and we will continue the conversation on discourse. We can always re-open this issue if needed. :)

**Comment by pavithraes** [comment] 2022-03-30 16:07
I'll go ahead and close this, looking forward to your Discourse topic!

**Closed by pavithraes** 2022-03-30 16:07 UTC
Labels: needs info
