### ISSUE TITLE
KilledWorker error when accessing S3 (again)

### ISSUE THREAD

**Issue by haje01** [dask/dask#5818] opened 2020-01-22 04:52 UTC
This is similar issue with #5651, which was closed without much attention.

This might look tiny glitch, but does exist. 

My Environment:
* HW: MacBook Pro, Quad Core i7, 16 GB RAM
* OS: macOS Catalina (10.15.2)
* Python: 3.7.2
* Dask: 2.9.0
* Jupyter: 1.0.0
* Jupyter Lab: 0.35.5
* Tornado: 6.0.2

To reproduce the problem publicly, I made an open S3 bucket `dask-error` (will be open for a while..), and uploaded following file ( `test.csv` ).

```
id, name, score
0, kjj, 100
1, jji, 80
2, kbj, 70
```

Code (Run in Jupyter Lab or Console )

```python
from dask import dataframe as dd
from dask.distributed import Client

client = Client()

dd.read_csv('s3://dask-error/test.csv').head()
```

Error message:

```
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
---------------------------------------------------------------------------
KilledWorker                              Traceback (most recent call last)
<ipython-input-5-0c9e200ad40f> in <module>
----> 1 dd.read_csv('s3://dask-error/test.csv').head()

~/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/dask/dataframe/core.py in head(self, n, npartitions, compute)
    957             Whether to compute the result, default is True.
    958         """
--> 959         return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
    960 
    961     def _head(self, n, npartitions, compute, safe):

~/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/dask/dataframe/core.py in _head(self, n, npartitions, compute, safe)
    990 
    991         if compute:
--> 992             result = result.compute()
    993         return result
    994 

~/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    163         dask.base.compute
    164         """
--> 165         (result,) = compute(self, traverse=False, **kwargs)
    166         return result
    167 

~/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    434     keys = [x.__dask_keys__() for x in collections]
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 436     results = schedule(dsk, keys, **kwargs)
    437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 

~/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2570                     should_rejoin = False
   2571             try:
-> 2572                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2573             finally:
   2574                 for f in futures.values():

~/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1870                 direct=direct,
   1871                 local_worker=local_worker,
-> 1872                 asynchronous=asynchronous,
   1873             )
   1874 

~/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    765         else:
    766             return sync(
--> 767                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    768             )
    769 

~/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    332     if error[0]:
    333         typ, exc, tb = error[0]
--> 334         raise exc.with_traceback(tb)
    335     else:
    336         return result[0]

~/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/distributed/utils.py in f()
    316             if callback_timeout is not None:
    317                 future = gen.with_timeout(timedelta(seconds=callback_timeout), future)
--> 318             result[0] = yield future
    319         except Exception as exc:
    320             error[0] = sys.exc_info()

~/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/tornado/gen.py in run(self)
    727 
    728                     try:
--> 729                         value = future.result()
    730                     except Exception:
    731                         exc_info = sys.exc_info()

~/.pyenv/versions/3.7.2/envs/ml2/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1726                             exc = CancelledError(key)
   1727                         else:
-> 1728                             raise exception.with_traceback(traceback)
   1729                         raise exc
   1730                     if errors == "skip":

KilledWorker: ("('from-delayed-pandas_read_text-read-block-head-1-5-from-delayed-5b643fa54bf8b8523ee8b28a3610566a', 0)", <Worker 'tcp://127.0.0.1:55944', memory: 0, processing: 1>)
```

---

If I explictly launch `dask-scheduler` and `dask-worker`, and run following code:

```python
from dask import dataframe as dd
from dask.distributed import Client

client = Client('localhost:8786')

dd.read_csv('s3://dask-error/test.csv').head()
```

Same error occurs. Worker log says:
```
distributed.core - INFO - Starting established connection
objc[71288]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[71288]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
distributed.nanny - INFO - Worker process 71288 was killed by signal 6
distributed.nanny - WARNING - Restarting worker
```

I hope the issue fixed soon (so I can close free bucket access).

**Comment by gvelchuru** [comment] 2020-01-29 00:28
Does your worker have enough memory to read from the CSV?

**Comment by haje01** [comment] 2020-01-29 00:41
@gvelchuru Yes. My MacBook Pro has 16 GB RAM, and `test.csv` has only 4 lines.

**Comment by haje01** [comment] 2020-01-29 01:23
Pandas reads with out problem.


```python
import pandas as pd

df = pd.read_csv('s3://dask-error/test.csv')
print(df.head())
```

Results:

```
   id  name   score
0   0   kjj     100
1   1   jji      80
2   2   kbj      70
```

**Comment by haje01** [comment] 2020-01-29 01:28
If you do not have AWS Credential, you can reproduce the problem via URL (in macOS):

```python
from dask import dataframe as dd
from dask.distributed import Client

client = Client()

df = dd.read_csv('https://dask-error.s3.amazonaws.com/test.csv')
print(df.head())
```

**Comment by TomAugspurger** [comment] 2020-01-29 20:53
@haje01 is your code in a `__main__` block?

**Comment by haje01** [comment] 2020-01-30 08:51
@TomAugspurger I ran above code in Jupyter Notebook. I also tested the code in the python file(.py) with `__main__` block, and the result was same.

**Comment by TomAugspurger** [comment] 2020-01-30 12:02
Are you able to debug things any further? I can't reproduce it locally.

**Comment by haje01** [comment] 2020-01-31 15:49
@TomAugspurger During this weekend, I'm going to find another Mac machine and test the issue, then report.

**Comment by haje01** [comment] 2020-02-01 03:06
@TomAugspurger I appreciate for your attention.

I succeeded in reproducing the problem in another Mac.

* HW: Mac mini 2018, Quad Core i3, 8 GB RAM
* OS: macOS Catalina (10.15.2)
* Python: 3.7.4 (with pyenv)
* Dask: 2.10.1
* Tornado: 6.0.3
* Xcode: 11.3.1

Test Code:

```python
from dask import dataframe as dd
from dask.distributed import Client

if __name__ == "__main__":
    client = Client()

    df = dd.read_csv('https://dask-error.s3.amazonaws.com/test.csv')
    print(df.head())
```

Error Message:
```
objc[15827]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[15827]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
distributed.nanny - WARNING - Restarting worker
objc[15826]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[15826]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
distributed.nanny - WARNING - Restarting worker
objc[15828]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[15828]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
distributed.nanny - WARNING - Restarting worker
objc[15825]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[15825]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    print(df.head())
  File "/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/dask/dataframe/core.py", line 971, in head
    return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
  File "/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/dask/dataframe/core.py", line 1004, in _head
    result = result.compute()
  File "/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/dask/base.py", line 165, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/dask/base.py", line 436, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/distributed/client.py", line 2587, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/distributed/client.py", line 1885, in gather
    asynchronous=asynchronous,
  File "/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/distributed/client.py", line 767, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/distributed/utils.py", line 345, in sync
    raise exc.with_traceback(tb)
  File "/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/distributed/utils.py", line 329, in f
    result[0] = yield future
  File "/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/distributed/client.py", line 1741, in _gather
    raise exception.with_traceback(traceback)
distributed.scheduler.KilledWorker: ("('from-delayed-pandas_read_text-read-block-head-1-5-from-delayed-b28569967b861afb3c43202844a2112f', 0)", <Worker 'tcp://127.0.0.1:53421', name: 0, memory: 0, processing: 1>)
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
distributed.nanny - WARNING - Restarting worker
```

**Comment by mrocklin** [comment] 2020-02-01 03:54
Some questions:

Does this require that you read a file from http or would a local file also
cause a failure?

Does this happen only with dask dataframe?

Is there a particular version of dask or distributed when this started
occurring?  If so, would you be willing to use git bisect to help identify
when the bug was introduced?

**Comment by haje01** [comment] 2020-02-02 12:27
@mrocklin My answers:

1. Local file reading is just OK.

2. Dask Bag `read_text` of S3 file also raises same error.

3. I uninstalled current version, and tried following versions (I used same version for dask & distributed)

2.5.0
2.8.0
2.9.0
2.9.1

They succeeded in getting the result! (though most of them showed *Worker process killed* warnings) :

```
/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/dask/dataframe/utils.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/dask/dataframe/utils.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/dask/dataframe/utils.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/dask/dataframe/utils.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/dask/dataframe/utils.py:15: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/Users/jeongjukim/.pyenv/versions/ml2/lib/python3.7/site-packages/dask/dataframe/core.py:5667: UserWarning: Insufficient elements for `head`. 5 elements requested, only 3 elements available. Try passing larger `npartitions` to `head`.
  warnings.warn(msg.format(n, len(r)))
   id  name   score
0   0   kjj     100
1   1   jji      80
2   2   kbj      70
distributed.process - WARNING - reaping stray process <ForkServerProcess(Dask Worker process (from Nanny), started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(Dask Worker process (from Nanny), started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(Dask Worker process (from Nanny), started daemon)>
distributed.process - WARNING - reaping stray process <ForkServerProcess(Dask Worker process (from Nanny), started daemon)>
distributed.nanny - WARNING - Worker process 22673 was killed by signal 15
distributed.nanny - WARNING - Worker process 22675 was killed by signal 15
distributed.nanny - WARNING - Worker process 22676 was killed by signal 15
distributed.nanny - WARNING - Worker process 22674 was killed by signal 15
```

Oddly, version 2.9.0 alone did not showed any warnings and works well.
It seemed to me that this problem started after dask==2.9.2 & distributed==2.9.2.

I hope my answers could give you some hint.

**Comment by mrocklin** [comment] 2020-02-02 20:44
Would you be willing to use `git bisect` to help identify where the error was introduced?

**Comment by haje01** [comment] 2020-02-03 01:31
@mrocklin 

OK, I've done `git biect` :

```
32cb96effe9287fdc42dd73be36989be13abe99d is the first bad commit
commit 32cb96effe9287fdc42dd73be36989be13abe99d
Author: Matthew Rocklin <mrocklin@gmail.com>
Date:   Wed Jan 8 18:38:21 2020 -0800

    Rework version checking (#2627)
    
    This creates automatic version checks whenever a worker or client joins
    the cluster and raises informative errors letting users know about the
    mismatched versions.

:040000 040000 a6f9072502d52ee8c4a16cc669a8f26167627fe9 13a9e9ffcdafc6a19c416b81513b343da1afea75 M	distributed
```

I hope this helps.

**Comment by haje01** [comment] 2020-02-10 03:30
I'm sorry but I shall remove public S3 bucket `dask-error` to reduce cost. But I think it would be fairly easy for anyone to create one by upload `test.csv` to their own S3 bucket.

**Comment by TomAugspurger** [comment] 2020-02-10 12:10
Thanks @haje01. FWIW, I'm unable to reproduce the failure with the following test

```diff
diff --git a/dask/bytes/tests/test_s3.py b/dask/bytes/tests/test_s3.py
index 050ba5ccb..61d1e7adb 100644
--- a/dask/bytes/tests/test_s3.py
+++ b/dask/bytes/tests/test_s3.py
@@ -448,3 +448,16 @@ def test_get_pyarrow_fs_s3(s3):
     pa = pytest.importorskip("pyarrow")
     fs = DaskS3FileSystem(anon=True)
     assert isinstance(fs, pa.filesystem.FileSystem)
+
+
+def test_killed_worker(s3):
+    import dask.dataframe as dd
+    data = (
+        "id, name, score\n"
+        "0, kjj, 100\n"
+        "1, jji, 80\n"
+        "2, kbj, 70")
+
+    s3.s3.put_object(Bucket=test_bucket_name, Key="test.csv", Body=data)
+    s3.invalidate_cache()
+    dd.read_csv(f's3://{test_bucket_name}/test.csv').compute()
```

**Comment by haje01** [comment] 2020-02-13 07:25
@TomAugspurger 

What happens if you create `Client` explicitly like following code?

```python
def test_killed_worker(s3):
    import dask.dataframe as dd

    cl = Client()  # <--

    data = (
        "id, name, score\n"
        "0, kjj, 100\n"
        "1, jji, 80\n"
        "2, kbj, 70")

    s3.put_object(Bucket=test_bucket_name, Key="test.csv", Body=data)
    dd.read_csv(f's3://{test_bucket_name}/test.csv').compute()
```

In my case, it raises `KilledWorker`.

**Comment by TomAugspurger** [comment] 2020-02-13 13:52
It raises with the same traceback?

I just noticed the messages about `objc[71288]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.`.

It's possible this was fixed by https://github.com/dask/distributed/pull/3461. Can you try out distributed master?

**Comment by haje01** [comment] 2020-02-14 00:46
I pulled `distributed` master and tested it. The error has gone!

https://github.com/dask/distributed/pull/3461 seems to have solved the problem.

Thank you all!

**Comment by jrbourbeau** [comment] 2020-02-14 02:34
> The error has gone!

Glad to hear it! Thanks @haje01 and @TomAugspurger!

**Closed by jrbourbeau** 2020-02-14 02:34 UTC
