### ISSUE TITLE
`compute()` changes a dataframe column dtype from uint64 to float64

### ISSUE THREAD

**Issue by dtourillon** [dask/dask#6947] opened 2020-12-09 19:24 UTC
**What happened**:

I created 2 pandas dataframes with a single cell each (containing a UUID), and saved them to disk.
I then created a dask dataframe from these 2 pandas dataframes using `read_csv(...)` + added a second column (`uuid_0`) derived from the first one (`uuid`).

The dtype of column `uuid_0` is `uint64` before calling `ddf.compute()`... and `float64` after:
```
Dask dtypes before compute:
uuid      object
uuid_0    uint64
dtype: object

Pandas dtypes after compute:
uuid       object
uuid_0    float64
dtype: object
```

**What you expected to happen**:
I expected the dtype of column `uuid_0` to be `uint64` both before and after `ddf.compute()`.

**Minimal Complete Verifiable Example**:

```python
# imports
import glob
import dask
import dask.dataframe as dd
import pandas as pd

from dask.distributed import Client
client = Client(n_workers=1, memory_limit='1GB')

# save 2 pandas dataframes to disk
df1 = pd.DataFrame(
    [
        ["873ba3b6983a40e89f0a97cad14f7c05"],
    ],
    columns=["uuid"]
)
df1.to_csv("df1.csv")

df2 = pd.DataFrame(
    [
        ["2a09e98e7cec4d40ab52cd52e0aea266"]
    ],
    columns=["uuid"]
)
df2.to_csv("df2.csv")

# read CSVs into dask dataframe
ddf = dd.read_csv(sorted(glob.glob(f"df*.csv")),
                  skiprows=1,
                  names=['uuid'])

# create a second column derived from 'uuid'
ddf["uuid_0"] = ddf["uuid"].str.slice(stop=16).apply(func=int, base=16, meta=("uuid_0", "uint64"))

# check dtypes
print(f"Dask dtypes before compute:\n{ddf.dtypes}\n")
df = ddf.compute()
print(f"Pandas dtypes after compute:\n{df.dtypes}")
```

**Anything else we need to know?**:
Because my unsigned integers are large, I loose numerical precision during the uint->float conversion ;(

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.6
- Operating System: Linux (FROM python:3.8.6-buster in Dockerfile)
- Install method (conda, pip, source): poetry

n.b. I ran the above snippet in a jupyter notebook.

**Comment by dtourillon** [comment] 2020-12-09 19:25
@chrish42 ^^

**Comment by jsignell** [comment] 2020-12-09 21:31
With your example, I tried just calling apply on the pandas dataframes. The first one produced a `uint` as expected, but the second one didn't:

```python
df2.uuid.str.slice(stop=16).apply(int, base=16)
```
gives:
```
0    3029209022573858112
Name: uuid, dtype: int64
```

I think this is the root of the issue, because when the partition dataframes are concatenated if the dtypes don't match they are upcast. I am not sure if this is a pandas bug or expected behavior. As a workaround I would suggest adding in an `astype`

```python
ddf["uuid_0"] = ddf["uuid"].str.slice(stop=16).apply(int, base=16, meta=("uuid_0", "uint64")).astype("uint")
```

**Comment by dtourillon** [comment] 2020-12-09 22:08
Thanks @jsignell for the quick investigation and workaround suggestion, it also worked on my side for the code snippet above... I'll give it a try on my real data set.

I didn't think about adding an `astype`, assuming the `meta` arg passed to `dask.apply` was essentially doing the same thing (and more)... clearly I was wrong!

**Comment by jsignell** [comment] 2020-12-09 22:12
As far as I understand, setting meta like that sets the expectation for the output, but doesn't do any work to coerce the output to that.

**Comment by chrish42** [comment] 2021-01-06 22:01
Nice catch & thank you @jsignell. Totally didn't think of looking for signed vs. unsigned when I was shown this. Hopefully when Pandas has good, solid NA support, these kinds of implicit lossy conversions can be disabled. They certainly are a source of bugs and problems. I'm assuming that's still further down the road, though. Right?

@dtourillon Does that solve this problem on your real dataset?

In the meantime, what do we do with this issue? Can we do something in the meantime to surface those potential problems a bit more? A warning? Or would that be too disruptive? If that's the case, I guess we can simply close this.

**Comment by dtourillon** [comment] 2021-01-07 17:55
> @dtourillon Does that solve this problem on your real dataset?

Yes it does, thanks to @jsignell 's suggestion.

I am therefore ok closing this issue... but will leave it to someone more experienced in dask to decide if we should close as is or add a warning as suggested by @chrish42 .

**Comment by jsignell** [comment] 2021-01-07 19:32
My inclination is to close. Unless someone has a clear idea of where such a warning would go

**Closed** 2021-10-14 06:18 UTC
Labels: dataframe
