### ISSUE TITLE
min and max misbehave combined with da.as_gufunc (regression since 2.30.0)

### ISSUE THREAD

**Issue by TAdeJong** [dask/dask#7384] opened 2021-03-13 11:15 UTC
`min()` and `max()` do not work anymore when combined with at least some `da.as_gufunc()` signatures for recent dask releases, seemingly back to the 2020.12.0 update. Although this might be somewhat of a fringe use case, it seems it might signal some deeper issue, as other reductions do seem to behave correctly.

With a signature of `signature="(i,j) ->(i,j), ()"`, in past versions, for an input shape of NxMxL, a tuple of dask arrays of shapes NxMxL and N would be returned which can be computed. In recent versions, only the NxMxL array is returned for `min()` and `max()` (and related functions, e.g. nanmax), while `mean()`, `sum()` and even `np.argmax()` work as expected.

**Minimal Complete Verifiable Example**:

```python
import dask.array as da
import numpy as np

stack = da.ones((1,50,60), chunks=(1,-1,-1))

@da.as_gufunc(signature="(i,j) ->(i,j), ()", output_dtypes=(stack.dtype, np.float))
def correctImages_mean(image):
    multiplier = image.mean()
    # Normally do some other stuff to image here.
    return image, np.atleast_1d(multiplier)

@da.as_gufunc(signature="(i,j) ->(i,j), ()", output_dtypes=(stack.dtype, np.float))
def correctImages_max(image):
    multiplier =  image.max()
    return image, np.atleast_1d(multiplier)

print(da.compute(*correctImages_mean(stack))) # tuple of two arrays
print(da.compute(*correctImages_max(stack))) # tuple of only 1 array.
```

Looking at the changelog for 2020.12.0, it seems that #6736 might be related?
Unfortunately, I don't have time to dig deeper at the moment.

Finally, as I was crafting the MWE, I stumbled upon the following question, which might or might not be related: is it expected behavior that the following `da.compute()` call would return a tuple of a numpy as a dask array? I thought da.compute was supposed to traverse down the data structure?

```python
@da.as_gufunc(signature="(i,j) ->(i,j), ()", output_dtypes=(stack.dtype, np.float))
def correctImages_nanmax(image):
    multiplier = da.nanmax(image)
    return image, np.atleast_1d(multiplier)

print(da.compute(*correctImages_nanmax(stack)))
>>> (array([[[1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        ...,
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.],
        [1., 1., 1., ..., 1., 1., 1.]]]), 
        dask.array<transpose, shape=(1,), dtype=float64, chunksize=(1,), chunktype=numpy.ndarray>)
```

**Environment**:

- Dask version: 2020.12.0 up to at least 2021.03.0
- Python version: 3.7.10, 3.8.8
- Operating System: Ubuntu and Windows
- Install method (conda, pip, source): conda.

**Comment by jsignell** [comment] 2021-03-18 21:34
Thank you for the well-crafted bug report. I'll ping @pentschev and @quasiben since they were involved in the PR you linked.

**Comment by pentschev** [comment] 2021-03-19 19:26
TBH, I'm not very skilled with gufuncs. However, I spent some (too much) time trying to understand what's going on here, I can confirm changes from https://github.com/dask/dask/pull/6736 are indeed responsible for this. The problem lies on those divergences between how libraries treat scalars, 0D and ND arrays, and I'm fairly certain this is to some extent very similar to the problem discussed in https://github.com/dask/dask/issues/6690 .

Right now, I don't have an optimal solution to offer, but a perhaps decently acceptable solution is to specify `meta=` in `as_gufunc`, as has been the trend for such corner cases that are really difficult to get working right among all different libraries. I opened https://github.com/dask/dask/pull/7423 to attempt providing a solution for this, but unfortunately I don't have the bandwidth now dig deeper on a solution that wouldn't require `meta=`.

**Comment by TAdeJong** [comment] 2021-03-21 16:08
Thanks for looking into this @pentschev.
I am not an expert in the inner workings of gufuncs either, nor am I familiar with the difficulties and intricacies of `meta=` and the different libraries. It might be a good idea to start using a `meta=` kwarg for gufuncs in general to make them more consistent with the rest of the library.

That being said, I am unsure whether #7423 would be the direction to go in to solve this issue. As it stands, the `meta=` kwarg has overlap with the existing kwargs `output_dtypes=` and `output_sizes=`.  Do I understand correctly that somehow the final part of `meta=`, the array type, is not correctly inferred automatically? 
Of course in an ideal world, it would be the nicest to be able to write `gufuncs` that work for different array types without needing to specialize by `meta=`.

What is however more concerning to me, is that different reductions behave so differently here, with only `min`/`max` related reductions giving problems, maybe signalling inconsistencies between the reductions at a lower level? Does anybody know what is causing this difference?

**Comment by pentschev** [comment] 2021-03-22 10:33
> That being said, I am unsure whether #7423 would be the direction to go in to solve this issue. As it stands, the `meta=` kwarg has overlap with the existing kwargs `output_dtypes=` and `output_sizes=`.

I can't say if it's overlapping with `output_sizes=`, but I would imagine it shouldn't, as `meta=` is generally expected to be a 0-D array. However, for `output_dtypes=` that is probably true, as in most other functions (e.g., `blockwise`), the `dtype` of `meta=` is used to infer the array's `dtype`, although in those cases the argument is called `dtype=` instead of `output_dtypes=`. IOW, if you specify the correct `dtype` to each `meta=` array, that is what one _should_ (emphasis here because otherwise could be a bug or simply that I don't understand some specifics of `output_dtypes=` vs the normally used `dtype=`) get.

> Do I understand correctly that somehow the final part of `meta=`, the array type, is not correctly inferred automatically?

Yes, this is again normally because of some very specific ways 0-D arrays are treated by different NumPy (and other NumPy-like libraries) functions. Take for example `np.mean` and `np.max` in the example below:

```python
In [1]: import numpy as np

In [2]: np.mean(np.array(()))
/datasets/pentschev/miniconda3/envs/rn-110-0.19.210319/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3419: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/datasets/pentschev/miniconda3/envs/rn-110-0.19.210319/lib/python3.8/site-packages/numpy/core/_methods.py:188: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Out[2]: nan

In [3]: np.max(np.array(()))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-b009c47e74a1> in <module>
----> 1 np.max(np.array(()))

<__array_function__ internals> in amax(*args, **kwargs)

/datasets/pentschev/miniconda3/envs/rn-110-0.19.210319/lib/python3.8/site-packages/numpy/core/fromnumeric.py in amax(a, axis, out, keepdims, initial, where)
   2731     5
   2732     """
-> 2733     return _wrapreduction(a, np.maximum, 'max', axis, None, out,
   2734                           keepdims=keepdims, initial=initial, where=where)
   2735

/datasets/pentschev/miniconda3/envs/rn-110-0.19.210319/lib/python3.8/site-packages/numpy/core/fromnumeric.py in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     85                 return reduction(axis=axis, out=out, **passkwargs)
     86
---> 87     return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
     88
     89

ValueError: zero-size array to reduction operation maximum which has no identity
```

You see above that `np.mean` raises a warning but completes returning a scalar. However, `np.max` raises a `ValueError` with a very specific message, which is incidentally what I was aiming to parse in https://github.com/dask/dask/pull/6736 . Due of those differences, we need to special-case such functions which isn't trivial to do because of the implicit attempt within Dask to infer `meta=` correctly when it's not specified by the user, which is a process to parse those exceptions and attempting to find the correct output a function would return ahead of time, but at the same time not running that on a real N-D array to avoid doing potentially expensive work.

> Of course in an ideal world, it would be the nicest to be able to write `gufuncs` that work for different array types without needing to specialize by `meta=`.

I agree, but those corner cases makes it really hard to be consistent across all Dask-supported backend libraries, thus providing `meta=` is a way to at least give the user the possibility not to be blocked by such issues.

> What is however more concerning to me, is that different reductions behave so differently here, with only `min`/`max` related reductions giving problems, maybe signalling inconsistencies between the reductions at a lower level? i.e. as far as I can see, `np.max` behaves very similar in returning a scalar as `np.mean`. Does anybody know what is causing this difference?

Hopefully the explanation above answers this as well.

**Comment by mrocklin** [comment] 2021-03-22 14:06
cc'ing @dask/array for help with GUFuncs and @magonser in particular who did a lot of this work originally I believe.

**Comment by jsignell** [comment] 2021-06-21 17:53
I believe this has now been resolved. I re-ran the original issue and it works as expected. Closing.

**Closed by jsignell** 2021-06-21 17:53 UTC
Labels: array
