### ISSUE TITLE
[BUG] cannot dd.read_json

### ISSUE THREAD

**Issue by lmeyerov** [dask/dask#6961] opened 2020-12-12 04:18 UTC
**What happened**:

We're struggling to get a single json file to read.

**What you expected to happen**:

`dd.read_json('simple.json')`, and variants where we add hints like `orient`, do not seem to go through, and instead error:

```
    out = dd.read_json(file_path, **kwargs)
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/io/json.py", line 218, in read_json
    return dd.from_delayed(parts, meta=meta)
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/io/io.py", line 586, in from_delayed
    meta = delayed(make_meta)(dfs[0]).compute()
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py", line 453, in compute
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
TypeError: zip argument #1 must support iteration
```

**Minimal Complete Verifiable Example**:

```python

import asyncio, os, pandas as pd, pytest
pytestmark = pytest.mark.asyncio

### setup
def write_df_to_file(in_file: str, df: pd.DataFrame = pd.DataFrame({'x': [1, 2, 3]})):
    df.to_json(in_file, orient='records')

@pytest.fixture(scope='module')
def small_path():
    file_path = f'{__name__}.small.{FILE_TYPE}'
    df = pd.DataFrame({
        's': ['x', 'y', 'z'],
        'i': [2, 4, 6]
    })
    write_df_to_file(file_path, df)
    yield file_path
    os.remove(file_path)

###  test
@pytest.mark.timeout(30)
async def test_dask_json(small_path):
    import dask.dataframe as dd
    from dask.distributed import Client, LocalCluster
    async with await LocalCluster(**{
            'asynchronous': True,
            'processes': True,
            'dashboard_address': None,
            'worker_dashboard_address': None,        
        }) as cluster:
        async with await Client(cluster, **{'name': 'test 1', 'asynchronous': True}) as client:
            dd.read_json(small_path, orient='records')
```

**Anything else we need to know?**:

**Environment**:

docker -> conda -> rapids 0.17 (stable) -> dask

**Comment by jsignell** [comment] 2020-12-14 16:13
Hmm this seems to be an issue with the asynchronous client specifically since results is a coroutine in that traceback.

**Comment by lmeyerov** [comment] 2020-12-14 19:38
Happy to provide further info, lmk!

**Comment by lmeyerov** [comment] 2020-12-15 05:35
I wonder if it's this: https://github.com/dask/dask/issues/5518 ... basically any async client program that tries to interact with the world, as all i/o is chained off dd ("dd.write_parquet", "dd.read_csv", ...)...

**Comment by jsignell** [comment] 2020-12-15 15:45
Oh that definitely sounds like what you are seeing! As a workaround, something like: 

```python
import pandas as pd
import dask.dataframe as dd
from dask.distributed import Client

client = Client(asynchronous=True)

### setup
def write_df_to_file(in_file: str, df: pd.DataFrame = pd.DataFrame({'x': [1, 2, 3]})):
    df.to_json(in_file, orient='records')

file_path = f'{__name__}.small.json'
df = pd.DataFrame({
    's': ['x', 'y', 'z'],
    'i': [2, 4, 6]
})
write_df_to_file(file_path, df)

ddf = await client.submit(dd.read_json, file_path, orient='records')
await client.compute(ddf)
```

But if you want to take on that issue and open a PR you are more than welcome.

**Comment by lmeyerov** [comment] 2020-12-15 18:28
Good news / bad news:

Bad news: Trying to reuse the clean `compute=False` approach for async parquet io in https://github.com/dask/dask/issues/6971 throws an exception here. Maybe not surprising as `compute` is not an official parameter: https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.read_json .

Good news: @jsignell 's workaround via `submit` does get the `ddf`. Thanks!

**Comment by jsignell** [comment] 2020-12-18 13:52
It looks like there is a `compute=False` option for `to_json` but you aren't using `dd.to_json` in this case.

**Comment by lmeyerov** [comment] 2020-12-18 21:43
yes, this is read_json

**Comment by jsignell** [comment] 2020-12-18 22:29
Ok I am going to close this one since I think the issue is well-described in #5518. If you feel inspired to try to fix that it'd be much appreciated!

**Closed** 2020-12-18 22:31 UTC
