### ISSUE TITLE
Managing memory use for a simple vstack/rechunk/store pipeline

### ISSUE THREAD

**Issue by alimanfoo** [dask/dask#5105] opened 2019-07-17 09:43 UTC
This issue originates from @rsignell-usgs who is trying to load data from a collection of netcdf files and combine into a single zarr file with some rechunking. The essence of the workflow is this:

```python
# simulate the input netcdf files using random data
inputs = [da.random.random(size=2_000_000, chunks=900_000)
          for _ in range(2000)]
inputs_stacked = da.vstack(inputs)
inputs_rechunked = inputs_stacked.rechunk((50, 900_000))
store = zarr.DirectoryStore('spike.zarr')
root = zarr.group(store, overwrite=True)
dest = root.empty_like(name='dest', data=inputs_rechunked, 
    chunks=inputs_rechunked.chunksize, overwrite=True)
inputs_rechunked.store(dest, lock=False)
```

I.e., a 4 layer workflow (getitem, vstack, rechunk, store).

When I run this using a local cluster with a single worker and thread (`cluster = LocalCluster(n_workers=1, threads_per_worker=1)`) then the computation is perfectly depth-first, and memory remains stable at below 1G.

However, when I run this using a local cluster with two workers (`cluster = LocalCluster(n_workers=2, threads_per_worker=1)`) then memory use grows to >16G and workers start spilling to disk. I also see that the computation is not depth-first any more, particularly the vstack task layer starts running ahead and has many tasks with memory.

@rsignell-usgs has been unable to run the real computation because on his system memory use is growing >60 GB.

@rsignell-usgs pointed me previously to a related issue that @rabernat had previously posted about memory use during this kind of data format conversion, but I can't find it now, apologies.

I realise that task scheduling in general is hard, but this seems like a relatively simple task graph and I wonder if there might be any way to provide some hints to guide the scheduling.

**Comment by alimanfoo** [comment] 2019-07-17 09:44
@rsignell-usgs just to say, if you don't mind this going slow, then a workaround to get this to complete should be to use a single worker, i.e.:

```
from dask.distributed import LocalCluster, Client
cluster = LocalCluster(n_workers=1, threads_per_worker=1)
client = Client(cluster)
```

**Comment by rsignell-usgs** [comment] 2019-07-17 11:15
@alimanfoo , in fact, that's the approach I used to create my single-year-of-data National Water Model dataset.   It took 16 hours to complete.   So figuring out how to get dask to do the right thing would be great!   The other thread is https://github.com/dask/distributed/issues/2602

**Comment by TomAugspurger** [comment] 2019-07-17 11:19
Thanks for the excellent example. Taking a look now.

**Comment by alimanfoo** [comment] 2019-07-17 12:20
Thanks @TomAugspurger. Just to add, if I increase the number of inputs, e.g.:

```
inputs = [da.random.random(size=2_000_000, chunks=900_000)
          for _ in range(10000)]
```

...then memory usage increases faster. 

For this workflow, I would expect that memory usage would be independent of the number of inputs, because the number of inputs doesn't affect the structure of the task graph, just adds more chunks.

**Comment by alimanfoo** [comment] 2019-07-17 14:22
One other point of interest, when running with two workers I notice a lot of communication between the workers in the dashboard. This workflow is embarrassingly parallel and could be scheduled so that no communication at all is needed between workers. Again I realise that scheduling is hard and many factors have to be balanced somehow, however I wonder if there is some way of providing hints to guide scheduling in simple cases like this.

**Comment by TomAugspurger** [comment] 2019-07-17 14:42
> For this workflow, I would expect that memory usage would be independent of the number of inputs, because the number of inputs doesn't affect the structure of the task graph, just adds more chunks.

Yep. I think there's an issue with the runtime scheduling logic, and the number of independent chains amplifies that problem.

We do get the correct depth-first linear ordering, and the scheduler correctly moves those tasks to the "waiting" state. The problem comes when the distributed scheduler looks around and says "I have free workers, and all these waiting tasks. I'll start on these other `inputs` before this chain of "inputs -> concat -> merge -> store" is done, because they're ready to go".

**Comment by mrocklin** [comment] 2019-07-17 14:45
I haven't looked deeply at this but my guess is that different chunks are showing up on different machines that then need to be moved together in the rechunk step.  This communication takes time, during which the workers "helpfully" start doing other work that generates more data.  This is what @TomAugspurger has been working on recently in https://github.com/dask/distributed/issues/2602

@alimanfoo I suspect that while the computation is embarrassingly parallel at a coarse level, there are probably a few chunks that all have to end up on the same machines in order to make this happen.  Dask doesn't do a ton of future planning when deciding where to land tasks without dependencies, and so we end up with communication.  A quick and dirty way to avoid this is by expanding the allowable width of task fusion

```python
dask.config.set(fuse_ave_width=10)
```

This way if you have a few tasks that are all connected only to each other then Dask won't mind running them within the same task.

**Comment by m-albert** [comment] 2019-07-17 17:07
I often stumble upon similar issues, especially when doing rechunking in combination with `da.overlap`. Computing overlaps probably increases the communication time even further because more data needs to be moved.

> A quick and dirty way to avoid this is by expanding the allowable width of task fusion

Would there be a similar quick and dirty way of fusing tasks in case these are not completely independent?

I'm thinking about something like fusing all tasks of a subgraph computing a given chunk. With the disadvantage of duplicating some of the processing / loading, this would prevent a lot of communication and potentially stop workers from generating more data (and running into the described blow ups).

**Comment by TomAugspurger** [comment] 2019-07-17 17:20
> however I wonder if there is some way of providing hints to guide scheduling in simple cases like this.

I wouldn't recommend it, but if this is blocking you then [this gist](https://nbviewer.jupyter.org/gist/TomAugspurger/12509b24e7771cfb7c2004a970520aa0) shows an example using worker restrictions which pins specific tasks to specific works. I set it up to run all the task in a "chain" on a worker (so there's zero communication between workers).

I'd recommend against actually using that that since it's throwing out a bunch of nice things you get from regular scheduling, and I'm hopeful it can be fixed in the near term.

**Comment by TomAugspurger** [comment] 2019-07-17 19:16
>  A quick and dirty way to avoid this is by expanding the allowable width of task fusion

```python
>>> dask.config.set(fuse_ave_width=10)
```

FYI @alimanfoo I needed `fuse_ave_width=50` before calling `inputs_rechunked.store(dest, lock=False)` for this to take effect. With that, there wasn't any communication between workers and the workload with 2,000 batches finished.

**Comment by alimanfoo** [comment] 2019-07-18 08:36
Thanks @mrocklin, @TomAugspurger, with `fuse_ave_width=50` I can process any number of inputs with stable memory use. 

I'd be grateful if anyone could give me a quick intuition for what `fuse_ave_width` is doing. I guess it is no coincidence that here we need `fuse_ave_width=50` and the number of inputs I'm stacking and rechunking into a single chunk is also 50?

**Comment by TomAugspurger** [comment] 2019-07-18 15:16
@alimanfoo I turned this into an example at https://github.com/dask/dask-examples/pull/89. You're intuition about `fuse_ave_width` is correct. Hopefully the images make it clear (you can see them on the static site examples.dask.org once it's merged).

---

And to be clear, I still intend to fix the scheduling issue causing the cluster to fall over.

**Comment by davidbrochart** [comment] 2019-09-04 21:00
I'm not sure this is entirely related, but I'm having a problem "transposing" chunks, i.e. transforming a dataset that is e.g. chunked in time into a dataset that is e.g. chunked in space, or the other way around.
Here are two reproducible examples, for the former:
```python
import xarray as xr
import pandas as pd
import numpy as np

time = pd.date_range('2000-01-01', periods=4)
lat = np.arange(-90, 90)
lon = np.arange(-180, 180)
precip = np.zeros((4, 180, 360))

ds = xr.Dataset({'precipitation': (['time', 'lat', 'lon'], precip)},
                coords={'time': time,
                       'lat': lat,
                       'lon': lon})
ds = ds.chunk({'time': 1, 'lat': 180, 'lon': 360})
ds.to_zarr('precipitation1.zarr')
ds = xr.open_zarr('precipitation1.zarr')
ds = ds.chunk({'time': 4, 'lat': 10, 'lon': 10})
ds.to_zarr('precipitation2.zarr')
```
Which gives this error:
```
ValueError: Final chunk of Zarr array must be the same size or smaller than the first. The specified Zarr chunk encoding is (1, 180, 360), but (4,) in variable Dask chunks ((4,), (10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10), (10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10)) is incompatible. Consider rechunking using `chunk()`.
```

And for the latter:
```python
import xarray as xr
import pandas as pd
import numpy as np

time = pd.date_range('2000-01-01', periods=4)
lat = np.arange(-90, 90)
lon = np.arange(-180, 180)
precip = np.zeros((4, 180, 360))

ds = xr.Dataset({'precipitation': (['time', 'lat', 'lon'], precip)},
                coords={'time': time,
                       'lat': lat,
                       'lon': lon})
ds = ds.chunk({'time': 4, 'lat': 10, 'lon': 10})
ds.to_zarr('precipitation3.zarr')
ds = xr.open_zarr('precipitation3.zarr')
ds = ds.chunk({'time': 1, 'lat': 180, 'lon': 360})
ds.to_zarr('precipitation4.zarr')
```
Which gives that error:
```pythonerror
NotImplementedError: Specified zarr chunks (4, 10, 10) would overlap multiple dask chunks ((1, 1, 1, 1), (180,), (360,)). This is not implemented in xarray yet.  Consider rechunking the data using `chunk()` or specifying different chunks in encoding.
```

**Comment by TomAugspurger** [comment] 2019-09-04 21:22
I'm not sure if this is proper, but it avoids the error in the first case

```python
ds2 = ds.chunk({'time': 4, 'lat': 10, 'lon': 10})
encoding = {'precipitation': ds.precipitation.encoding.copy()}
encoding['precipitation']['chunks'] = (4, 10, 10)
ds2.to_zarr('precipitation2.zarr', mode='w', encoding=encoding)
```

As a novice xarray user, I might expect something like this to happen automatically when calling `Dataset.chunk`. But I probably don't fully understand what's going on.

**Comment by davidbrochart** [comment] 2019-09-04 21:31
Thanks a lot, this case was the most important for me. I will now see how it behaves on a large dataset.
For the second case, I understand that it's not that trivial and that it might be implemented in xarray in the future.

**Comment by davidbrochart** [comment] 2019-09-04 22:11
With the relatively small TRMM-3B42RT dataset, it keeps on reading the zarr over and over again, and it eventually crashes. I ran the following on the Pangeo binder, but you can change the client and run it locally too:
```python
import xarray as xr
from gcsfs import mapping
from dask_kubernetes import KubeCluster as Cluster
from dask.distributed import Client

cluster = Cluster(n_workers=10)
client = Client(cluster)

trmm_zarr = mapping.GCSMap('pangeo-data/trmm_3b42rt')
ds_p = xr.open_zarr(trmm_zarr)

ds2 = ds_p.chunk({'time': 41320, 'lat': 10, 'lon': 10})
encoding = {'precipitation': ds_p.precipitation.encoding.copy()}
encoding['precipitation']['chunks'] = (41320, 10, 10)
ds2.to_zarr('precipitation2.zarr', mode='w', encoding=encoding)
```

**Comment by davidbrochart** [comment] 2019-09-05 07:27
You can run the code above in the Pangeo Binder by clicking [this link](https://binder.pangeo.io/v2/gh/davidbrochart/pangeo-test/master) and opening `test0.ipynb`.

**Comment by TomAugspurger** [comment] 2019-09-05 14:44
Hmm, still thinking through the rechunking, but that pattern collapsing all the `time` chunks into a single one and chunking the other dims seems to require a lot of communication between chunks, right? So this isn't an embarrassingly parallel problem, so my earlier workarounds won't help here.

Better scheduling might not help too much either. There's just going to be a lot of communication here.

We do have some issues with workers dying during communication. So the scheduler can do a better job of not executing tasks while a worker is high on memory and either sending or receiving data from another worker.

For now, is rechunking just along the `time` dimension an option? That will result in larger chunks than in the other one.

```python
ds2 = ds.chunk({'time': 41320})
encoding = {'precipitation': ds.precipitation.encoding.copy()}
encoding['precipitation']['chunks'] = (41320,) + encoding['precipitation']['chunks'][1:]
ds2.to_zarr('precipitation2.zarr', mode='w', encoding=encoding)
```

seems to be progressing on the binder. Will see if it finishes.

**Comment by davidbrochart** [comment] 2019-09-05 14:52
But rechunking just along the time dimension will result in huge chunks that won't fit in memory, right?

**Comment by TomAugspurger** [comment] 2019-09-05 14:59
Oh, yes, I misread the chunk sizes. So that won't work...

**Comment by davidbrochart** [comment] 2019-09-05 15:04
Interestingly, dask doesn't seem to complain about that, but it hangs doing nothing in the `rechunk-merge` task.

**Comment by m-albert** [comment] 2019-09-05 15:41
I had a similar problem: Rechunking an array (and in my case performing `da.overlap`) read from a hdf5 source was killing the scheduler (crashing and filling up memory).

What turned out to help in my case was to fill in the chunks manually. I didn't check how your file  is saved @davidbrochart, but I guess typically data that doesn't fit into memory would be saved in some way supporting i/o chunks. Therefore one solution would be to outsource the chunking to the i/o library. What I mean by that is something like:

```python
import numpy as np
import dask.array as da
import h5py

# create example scenario
ar_size = (100, 110, 120)

# different chunk sizes between disk and in memory
hdf5_chunk_size = (10,11,12)
dask_chunk_size = (3, 4, 5)

# create and save example array
large_array = np.random.randint(0, 100, ar_size)
filename = '/tmp/tmp_dask.h5'
# import os
# if os.path.exists(filename): os.remove(filename)
file = h5py.File(filename)
file.create_dataset("array", data=large_array, chunks=hdf5_chunk_size)
# file.close()

# define function which loads a chunk
# use dasks block_info functionality
def load_chunk(x, filename, block_info=None):

    source = h5py.File(filename)['array']
    slices = [slice(*tuple(block_info[0]['array-location'][dim])) for dim in range(3)]
    loaded_chunk = source[tuple(slices)]

    return loaded_chunk

# create empty dask array
ar = da.empty(ar_size, chunks=dask_chunk_size)

# fill in chunk by chunk
ar = ar.map_blocks(load_chunk, filename = filename, dtype=large_array.dtype)

print(file['array'].chunks)
print(ar.chunksize)
```

This is just to illustrate the principle using `h5py`, but it should be easily adapted to other file formats. For sure the solution is not optimal, but it might be a workaround in some cases.

**Comment by davidbrochart** [comment] 2019-09-05 16:03
Thanks for the workaround @m-albert. In my case, it is saved in the zarr format using xarray, so I'm not sure I can go as low-level as you did, directly manipulating a Dask array.

**Comment by m-albert** [comment] 2019-09-05 17:43
I'm not very familiar with `xarray`, but the same trick could be used for dask arrays within the `xarray` dataset

Ok I overcomplicated things in the code above: Using `map_blocks` in my case was needed because I was performing a `da.overlap` at the same time. In your example, something like this should do the trick of outsourcing the rechunking:

```python
import zarr
source = zarr.open(trmm_zarr, mode='r')['precipitation']
res = da.from_array(source,chunks=(41320,10,10))

encoding = {'precipitation': ds.precipitation.encoding.copy()}
encoding['precipitation']['chunks'] = (41320, 10, 10)
res.to_zarr('precipitation.zarr', mode='w', encoding=encoding)
```

However, I just tried this in your binder and although the cluster doesn't crash it doesn't seem to be completing tasks..

**Comment by m-albert** [comment] 2019-09-05 18:04
I'm not very familiar with `xarray`, but if I understand it correctly the `.data` attributes of datasets are dask arrays.

I realised that in the code above I complicated things way to much using `map_blocks`. In my case I needed this because I was doing the chunk overlapping in the same processing step. In your case, a simple `from_array` could do the trick, because the `zarr` format seems to expose the data as an array:

```python
import dask.array as da
import zarr
source = zarr.open(trmm_zarr, mode='r')['precipitation']
ds['precipitation'].data = da.from_array(source,chunks=(41320,10,10))

encoding = {'precipitation': ds.precipitation.encoding.copy()}
encoding['precipitation']['chunks'] = (41320, 10, 10)
ds.to_zarr('precipitation.zarr', mode='w', encoding=encoding)
```
It's currently running in the binder you set up...

**Comment by davidbrochart** [comment] 2019-09-05 18:51
With your code, it hangs for a while and finally throws an error `ValueError: array not found at path 'precipitation'`.

**Comment by m-albert** [comment] 2019-09-05 19:07
Hmm yeah I just got the same, the error unfortunately is a bit cryptic.

**Comment by rsignell-usgs** [comment] 2019-11-05 15:59
I now have a workaround for this issue which works quite well.   My use case was using xarray to read a large collection of netcdf files, then rechunking and writing to zarr.   Instead of letting dask try to manage the whole thing, I just step through the dataset one output time chunk at a time, and use the xarray append functionality.   This way my dask workers stay busy reading/rechunking/writing all the spatial chunks contained in one time chunk, but dask has to finish writing one time chunk worth before reading anymore. 

Here's a notebook demonstrating this approach with National Water Model data:
https://gist.github.com/rsignell-usgs/35e1b44103118900d9b9d136ba2f2e9a

@TomAugspurger , @rabernat , @jhamman , @darothen

**Comment by rabernat** [comment] 2019-11-05 16:40
Thanks @rsignell-usgs for this very useful workaround for a common use case!

Hopefully we can continue to work with the dask devs to try to find a solution within the scheduling algorithm, rather than depending on such workarounds in the long term.

**Comment by TomAugspurger** [comment] 2020-05-07 14:15
A variant of this came up on the pangeo call yesterday. See https://discourse.pangeo.io/t/best-practices-to-go-from-1000s-of-netcdf-files-to-analyses-on-a-hpc-cluster/588/12?u=tomaugspurger for more. Here I want to focus on a case where the addition of a "base" key in `from_zarr` causes our task fusion to fail, which leads to high memory use with the distributed scheduler since tasks get scheduled on different machines.


Consider this array of `ones`. It's chunked along each dimension, and we'd like to merge the 4 chunks in the first dimension to 1 with `.rechunk({0: -1})`. As long as the `optimization.fuse.ave-width` config is larger than our rechunking factor (4 in this case) then we get the desired task graph.

```python
import dask.array as da

a = da.ones((4, 4000, 4000), chunks=(1, 2000, 2000))
b = a.rechunk(data4.chunks)

with dask.config.set(**{"optimization.fuse.ave-width": 4}):
    display(b.visualize(optimize_graph=True))
```

![Screen Shot 2020-05-07 at 9 14 16 AM](https://user-images.githubusercontent.com/1312546/81304783-266b5b80-9043-11ea-9492-61cf57c0121f.png)


However, the `from_zarr` graph doesn't look like the `ones` graph. Since it uses `from_array` there's a base key that all the tasks depend on. We'll simulate that with

```python
dsk = dict(b.dask)
for key in dsk:
    if key[0].startswith("ones-"):
        dsk[key] = dsk[key] + ("base",)
        
dsk["base"] = ()
with dask.config.set(**{"optimization.fuse.ave-width": 4}):
    display(dask.visualize(dsk))
```

![Screen Shot 2020-05-07 at 9 14 19 AM](https://user-images.githubusercontent.com/1312546/81304796-2a977900-9043-11ea-9833-829600dedbf6.png)

I'm looking into why that key prevents the desired fusing now.

**Comment by TomAugspurger** [comment] 2020-05-07 19:30
OK, I have a potential solution... In `dask.array.from_zarr`, we just inline the `from-zarr-` key, whose value is the `zarr.Array`.

```diff
diff --git a/dask/array/core.py b/dask/array/core.py
index 5d807fdcb..725801521 100644
--- a/dask/array/core.py
+++ b/dask/array/core.py
@@ -2847,6 +2847,7 @@ def from_zarr(
     kwargs: passed to ``zarr.Array``.
     """
     import zarr
+    from ..optimization import inline
 
     storage_options = storage_options or {}
     if isinstance(url, zarr.Array):
@@ -2862,7 +2863,9 @@ def from_zarr(
     chunks = chunks if chunks is not None else z.chunks
     if name is None:
         name = "from-zarr-" + tokenize(z, component, storage_options, chunks, **kwargs)
-    return from_array(z, chunks, name=name)
+    arr = from_array(z, chunks, name=name)
+    arr.dask = inline(arr.dask, keys=name)
+    return arr
 

 def to_zarr(
```

Is this a bad thing to do (perhaps @eriknw or @jcrist is familiar with `inline`)? That at least solves the `from_zarr(...).rechunk()` side of things.


```python
with dask.config.set(**{"optimization.fuse.ave-width": 4}):
    display(data4.visualize(optimize_graph=True))
```

![mydask](https://user-images.githubusercontent.com/1312546/81336608-4153c500-906f-11ea-91b2-0858a8ba4dfd.png)


Looking into a slightly different fusion / communication issue on the `to_zarr()` side (similar issue, but different cause).

**Comment by eriknw** [comment] 2020-05-08 02:10
@TomAugspurger, if it works, I'm not terribly concerned with that use of `inline`.  I would probably set `inline_constants=False` though.

What were you trying to show with the last diagram in https://github.com/dask/dask/issues/5105#issuecomment-625282112 (two comments ago)?

The issue with `from_zarr` graphs not fusing as one would hope has come up before.  I believe this is because `hold_keys` in `dask.array.optimization:optimize` specifically tells `fuse` *not* to fuse these keys.

This graph:
```python
display(dask.visualize(dsk))
```
![dsk1](https://user-images.githubusercontent.com/2058401/81362605-d625e500-90a6-11ea-983b-8e5704d92c66.png)
can be properly fused to this graph:
```python
display(dask.visualize(dask.optimization.fuse(dsk, ave_width=4)[0]))
```
![dsk2](https://user-images.githubusercontent.com/2058401/81362648-efc72c80-90a6-11ea-9ee0-7a019368c00e.png)

**Comment by TomAugspurger** [comment] 2020-05-08 11:23
> What were you trying to show with the last diagram in #5105 (comment) (two comments ago)?

That was showing the lack of fusion with the presence of a root node.

Your last graph is with the `hold_keys` check disabled, so that it doesn't prevent fusion? I'll check out your issue / PR on that topic again.

**Comment by mrocklin** [comment] 2020-11-28 01:28
@alimanfoo I took at look at this problem today using your original example (thanks for providing that by the way).  Unfortunately I wasn't able to reproduce the memory issue.  Perhaps this is because of fixes that @TomAugspurger has done recently? I get the sense though that this issue isn't entirely resolved yet.  Is there a better example today that fails reliably?  

Alternatively, if the example at the top still fails reliably for you let me know.  It could be that my hardware is different enough to matter.

My guess/hope is that we can reduce starting excessive chains of work by slowing down computation when we're under heavy communication load.  That's just a guess/hope though.

**Comment by jakirkham** [comment] 2022-11-17 02:13
Am curious what this looks like with 2022.11.0. Particularly in light of [these memory optimizations]( https://www.coiled.io/blog/reducing-dask-memory-usage ).

**Comment by rsignell-usgs** [comment] 2022-11-18 13:09
The answer is it works great!  I ran the [original test case](https://github.com/dask/dask/issues/5105) from @alimanfoo  (I used the[ notebook here](https://nbviewer.org/gist/7c60ed3a5564097231be76c418033bbb))  with both dask 2022.4.0 and with 2022.11.0:

2022.4.0:
![2022-11-18_07-46-59](https://user-images.githubusercontent.com/1872600/202711899-93144f82-60a1-4d91-ab1c-61cf46a777fe.png)

2022.11.0:
![2022-11-18_07-45-01](https://user-images.githubusercontent.com/1872600/202711960-546d1eb3-b9e2-466d-a7f0-a98984b7c1d8.png)

**Comment by mrocklin** [comment] 2022-11-18 13:11
Woot

**Comment by jakirkham** [comment] 2022-11-18 17:06
Agreed :)

Thanks for sharing Rich! 🙏

**Closed** 2022-11-18 17:08 UTC
Labels: array
