### ISSUE TITLE
Normalize chunks argument in Array constructor

### ISSUE THREAD

**Issue by drwelby** [dask/dask#5023] opened 2019-06-28 18:32 UTC
See https://github.com/dask/dask/issues/5023#issuecomment-506838487

---

This is tough to give an example, but something about creating new arrays with Dask 2.0.0 is throwing `TypeError: 'int' object is not iterable` when used in https://github.com/DigitalGlobe/gbdxtools 
 
The core of the error is:

```
File "/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/gbdxtools/images/meta.py", line 65, in __new__
    self = da.Array.__new__(cls, *dm.values)
  File "/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/dask/array/core.py", line 971, in __new__
    self._chunks = normalize_chunks(chunks, shape, dtype=dt)
  File "/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/dask/array/core.py", line 2342, in normalize_chunks
    return tuple(tuple(int(x) if not math.isnan(x) else x for x in c) for c in chunks)
  File "/anaconda3/envs/earth-analytics-python/lib/python3.6/site-packages/dask/array/core.py", line 2342, in <genexpr>
    return tuple(tuple(int(x) if not math.isnan(x) else x for x in c) for c in chunks)
TypeError: 'int' object is not iterable
```

What we are doing is creating a large dask array where the chunks are mapped to functions that download a piece of a satellite image. We are creating a custom Dask graph and passing that with the following values to `__new__`:

```
>>> dask
<big dask graph>
>>> name
'image-9365ef97-999a-5818-a932-bc57f8ddaa39'
>>> chunks
(8, 256, 256)
>>> dtype
'float32'
>>> shape
(8, 29696, 10752)
```

However the logic introduced in 2.0.0 here:

https://github.com/dask/dask/blob/2.0.0/dask/array/core.py#L962

```
>>> isinstance(chunks, tuple)
True
>>> any(isinstance(c, str) for c in chunks)
False
```
results in our `dtype` value getting set to `None`

Is this the expected behavior? Do we need to create arrays differently for 2.0.0?

**Comment by TomAugspurger** [comment] 2019-06-28 18:42
Are you creating those `chunks`, or is dask computing them. `chunks` is supposed to be a sequence of tuples, not just a tuple.

IIUC, the correct chunks should be the output of

```python
da.core.normalize_chunks((8, 256, 256), shape=(8, 29696, 10752))
```

**Comment by drwelby** [comment] 2019-06-28 18:49
It looks like we've always passed a single tuple, and this has functioned up to Dask 1.2.2 in a heavily used library.

And even if the format is wrong, why is that overriding the passed `dtype`?

**Comment by mrocklin** [comment] 2019-06-29 15:00
Maybe we should be normalizing chunks within the constructor?

**Comment by TomAugspurger** [comment] 2019-06-29 15:27
That seems sensible (that or validating and raising). Can calling
normalize_chunks be expensive, or is it expensive to validate the input?

**Comment by mrocklin** [comment] 2019-06-29 15:32
I don't think that it's likely to be expensive.

**Comment by drwelby** [comment] 2019-06-29 15:32
In our case we've built the graph around a known chunk size so we don't need to normalize it. We could also construct a more "valid" chunk description quite easily. It was mostly a surprise that the wrong input worked for so long.

**Comment by mrocklin** [comment] 2019-06-29 18:26
> results in our dtype value getting set to None

Can you verify this with a minimal example?  I'm unable to reproduce this with the following test:

```python
@pytest.mark.parametrize('chunks', [
    5,
    (5,),
    'auto',
    ('auto',)
])
def test_normalize_chunks_in_constructor(chunks):
    x = Array(
        {('x', 0): (np.ones, 5)},
        name='x',
        shape=(5,),
        chunks=chunks,
        dtype='int32',
    )
    assert x.dtype == 'int32'
```

**Comment by drwelby** [comment] 2019-06-29 22:24
> Can you verify this with a minimal example?

This was probably a misdiagnosis, based on looking at the changes between 1.2.2 (which worked with just passing a simple tuple) and 2.0.0 (which resulted in the above error). Reproducing the changes, it seems like the logic would have resulted in that output. I could revert my fix and see if it actually does that, but given that my input was wrong I'm not sure it worth pursuing. 

I couldn't figure out what that code addition was trying to accomplish either, so it made it extra suspicious to me. But whatever changed that changed the behavior is most likely somewhere else.

**Comment by TomAugspurger** [comment] 2019-07-02 15:00
The other big change for dask.array is that we're now tracking `_meta` to track things like `.dtype`. That refactor may have changed something you were relying on.

**Comment by drwelby** [comment] 2019-07-02 15:17
Everything else is working fine. For some reason we were passing something that maps more to the concept of `chunksize` than `chunks`. Now that we're passing real `chunks` things are working like they should. Either we missed a change a long time ago, and/or we were somehow lucky that it worked the wrong input anyway.

**Comment by TomAugspurger** [comment] 2019-07-08 16:14
OK, closing then.

**Closed by TomAugspurger** 2019-07-08 16:14 UTC
Labels: array

**Comment by jbrant** [comment] 2019-11-22 01:32
I'm getting this error with any image I try to download; even when just running the sample code from the gbdxtools docs:

`from gbdxtools import CatalogImage, WV03_VNIR

img = CatalogImage('104001001BA7C400')
print(img.shape, img.bounds)
print(isinstance(img, WV03_VNIR))`

**Comment by drwelby** [comment] 2019-11-22 15:24
@jbrant see https://github.com/DigitalGlobe/gbdxtools/issues/797

We can help you over there.
