### ISSUE TITLE
v2.17.0 unit test failure "KeyError: 'optimization'"

### ISSUE THREAD

**Issue by PureTryOut** [dask/dask#6254] opened 2020-05-28 13:53 UTC
**What happened**:
Running the unit tests for 2.17.0 on Alpine Linux with Python 3.8 fails in several places with `KeyError: 'optimization'`.

**What you expected to happen**:
All the unit tests to succeed

**Minimal Complete Verifiable Example**:
Well, just run the unit tests like normal on an Alpine Linux edge system.

```
(I don't know what a MCVE code is)
```

**Anything else we need to know?**:
Log:

```
_____________________________________ ERROR collecting dask/dataframe/tests/test_categorical.py _____________________________________
dask/dataframe/tests/test_categorical.py:28: in <module>
    cat_series.append((ds.compute().index, ds.index))
dask/base.py:166: in compute
    (result,) = compute(self, traverse=False, **kwargs)
dask/base.py:438: in compute
    dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
dask/base.py:217: in collections_to_dsk
    _opt_list.append(opt(_graph_and_keys[0], _graph_and_keys[1], **kwargs))
dask/dataframe/optimize.py:28: in optimize
    fuse_subgraphs = config.get("optimization.fuse.subgraphs")
dask/config.py:459: in get
    result = result[k]
E   KeyError: 'optimization'
______________________________________ ERROR collecting dask/dataframe/tests/test_dataframe.py ______________________________________
dask/dataframe/tests/test_dataframe.py:38: in <module>
    full = d.compute()
dask/base.py:166: in compute
    (result,) = compute(self, traverse=False, **kwargs)
dask/base.py:438: in compute
    dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
dask/base.py:217: in collections_to_dsk
    _opt_list.append(opt(_graph_and_keys[0], _graph_and_keys[1], **kwargs))
dask/dataframe/optimize.py:28: in optimize
    fuse_subgraphs = config.get("optimization.fuse.subgraphs")
dask/config.py:459: in get
    result = result[k]
E   KeyError: 'optimization'
______________________________________ ERROR collecting dask/dataframe/tests/test_indexing.py _______________________________________
dask/dataframe/tests/test_indexing.py:20: in <module>
    full = d.compute()
dask/base.py:166: in compute
    (result,) = compute(self, traverse=False, **kwargs)
dask/base.py:438: in compute
    dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
dask/base.py:217: in collections_to_dsk
    _opt_list.append(opt(_graph_and_keys[0], _graph_and_keys[1], **kwargs))
dask/dataframe/optimize.py:28: in optimize
    fuse_subgraphs = config.get("optimization.fuse.subgraphs")
dask/config.py:459: in get
    result = result[k]
E   KeyError: 'optimization'
_______________________________________ ERROR collecting dask/dataframe/tests/test_shuffle.py _______________________________________
dask/dataframe/tests/test_shuffle.py:38: in <module>
    full = d.compute()
dask/base.py:166: in compute
    (result,) = compute(self, traverse=False, **kwargs)
dask/base.py:438: in compute
    dsk = collections_to_dsk(collections, optimize_graph, **kwargs)
dask/base.py:217: in collections_to_dsk
    _opt_list.append(opt(_graph_and_keys[0], _graph_and_keys[1], **kwargs))
dask/dataframe/optimize.py:28: in optimize
    fuse_subgraphs = config.get("optimization.fuse.subgraphs")
dask/config.py:459: in get
    result = result[k]
E   KeyError: 'optimization'
```

**Environment**:

- Dask version: 2.17.0
- Python version: 3.8
- Operating System: Alpine Linux
- Install method: source

**Comment by TomAugspurger** [comment] 2020-05-28 14:23
Duplicate of https://github.com/dask/dask/issues/6221. We'll probably have a bugfix release later today.

**Closed by TomAugspurger** 2020-05-28 14:23 UTC
