### ISSUE TITLE
Memory explodes when reading multiple parquet files

### ISSUE THREAD

**Issue by PGryllos** [dask/dask#4256] opened 2018-11-29 12:00 UTC
When trying to read multiple relatively large parquet files (~500mb) the execution fails, usually with OutOfMemory error.

I have a large dataset consisting of ~100 parquet files that I am trying to process in a relatively large machine (70GB ram, 36 cores); when trying to read multiple files the total bytes stored exceeds the total memory of my machine and the whole computation fails; if I try to load smaller part of the files the workers get killed because at some point they exceed the memory threshold; regardless of what combinations of memory limits, number of workers and thresholds I have tried; Eventually if I read small enough part of the dataset the computation goes through. 

I am not sure if the problem lies with the parquet reading and how I could debug this. Do you have any suggestions?

**Comment by PGryllos** [comment] 2018-11-29 12:18
sorry, I know that this issue may lack concrete explanation from my side, ftm I am overwhelmed with options for looking into the problem and not sure where to start from, changing different things points to different issues :/ i.e. trying to process less files usually results in the workers getting killed due to exceeded memory limits. 

another thing that is not clear is what memory limit I should use. given that I have 36 cores giving 2gb to each worker would seem sensible, but then my workers almost immediately go above 95% and get killed; if I use bigger memory limits (e.g 6gb) then I am sacrificing some of the parallelism I guess? because obviously there is not enough memory for 36 workers. I have tried playing with the target, spill, pause configs but also without much luck. How would an experienced dask developer dive into this ? again sorry If this looks under documented.

**Comment by xhochy** [comment] 2018-11-29 12:41
@PGryllos The best starting point for us to help you with your problem would be to provide some sample code that exactly shows your problem. 

- Can you construct some Parquet files with code that highlight your problem but don't contain sensitive data?
- Can you create a minimal, reproducible code example with these files that highlights your memory problems?

**Comment by PGryllos** [comment] 2018-11-29 13:30
@xhochy thx a lot for taking the time. Sharing data is a bit tough both because of privacy concerns but also because the problem is shown when trying to process bigger than 5gb of that data. The data is split in either 180gb or 500gb files. 

but I can share part of the code that showcases the situation

```python


def _filter_transports_label(transports, label):
    for t in transports:
        if label in t['label']:
            return True


def load_dataset(path, sample_prob=None, random_state=None):
    """Expects mpla mpla mpla

    :param path: can be s3 or local
    :return:
    """
    ds = dd.read_parquet(path)
    assert (ds.columns == _schema).all()

    # convert dataset from DataFrame to Bag in order to store custom objects
    ds = ds.to_bag()

    ds = ds.map(
        lambda (session_id, transport, trip): (
            session_id,
            loads(b64decode(transport)),
            loads(b64decode(trip))
        )
    )

    if sample_prob:
        ds = ds.random_sample(sample_prob, random_state)

    ds = ds.filter(lambda (session_id, transport, trip): _filter_transports_label(transport, 'car'))

    return ds


from dask.distributed import Client, LocalCluster

cluster = LocalCluster(
    ip='127.0.0.1',
    n_workers=10,
    diagnostics_port=8786,
    memory_limit=6000000000,
)
client = Client(cluster)

PATH = '/home/ubuntu/data/input/merged_df_medium/test/*.parquet'
ds = load_dataset(PATH, sample_prob=None, random_state=42)

ds = client.persist(ds)
e = ds.take(10)
```

**Comment by PGryllos** [comment] 2018-11-29 13:34
@xhochy @martindurant updated my comment

**Comment by PGryllos** [comment] 2018-11-29 13:39
@martindurant so once I figure out the uncompressed size, how should I extrapolate this to consuming the whole dataset? should I set the target threshold to something very low for instance?

**Comment by martindurant** [comment] 2018-11-29 14:02
> `ds = ds.to_bag()`

This does not seem like a great idea, I would have thought you could do the same, but more efficiently, with dataframe methods such as `map_partitions`

> ds = client.persist(ds)

You are, I think, storing dicts here and this might be very inefficient. In this case, you *do* need to consider the whole dataset, since you will be storing it all in memory (on various workers). How much that is will depend on the effect of your filter.

> how should I extrapolate this

If a typical chunk is 500MB on disc and expands to 2GB in memory, you should allow for up to ~10GB of capacity in the worker for normal dataframe operations. Your numbers will differ.

**Comment by PGryllos** [comment] 2018-11-29 14:12
@martindurant  for the

```
ds = client.persist(ds)
```

in the original code at the point of persist the ds is a dataframe that contains two string column and one column where each row is a numpy array. does this seem as an anti-pattern as well ? I thought that persists can deal with out of memory data by dumping to disk

> if a typical chunk is 500MB on disc and expands to 2GB
so mine is ~500mb with snappy compression. 

> you should allow for up to ~10GB of capacity in the worker 
you mean set the memory limit to 10gb?

**Comment by martindurant** [comment] 2018-11-29 14:20
> one column where each row is a numpy array

A column of arrays is certainly unusual. Perhaps you actually have an xarray-like structure?

> you mean set the memory limit to 10gb

Actual available memory; dask will not be able to spill to disc during a pandas operation that creates lots of intermediates (experiment to see which these are; making dicts is likely to be one), but considers the memory limits at the end of each task.

**Comment by PGryllos** [comment] 2018-11-29 15:32
> Actual available memory;

this improved things significantly; Reducing the number of workers also helps but reducing the parallelisation seems like a big price to pay :/

Why is this  `ds = ds.to_bag()` a bad idea? do you suggest to not work on a bag at all but rather apply all operations on the dataframe?

**Comment by PGryllos** [comment] 2018-11-29 15:40
also the 

```
ds = client.persist(ds)
```
when ds is a dataframe means that the chunks of the dataframes will have to fit in the memory of the worker? so that implies that the whole dataframe will have to fit in the total ram of the instance?

**Comment by PGryllos** [comment] 2018-11-29 15:52
@martindurant I am thinking about your `map_partitions` suggestion; the reason why I choose a bag is because initially I need to work on custom python objects; does this make sense? In pandas I usually avoid storing custom objects in a dataframe.

**Comment by martindurant** [comment] 2018-11-29 16:04
> chunks of the dataframes will have to fit in the memory of the worker?

Yes, persist means that all of the data in the object (dataframe or bag or whatever) will be stored in the workers. Some of that may be spilled to disc.

> reducing the parallelisation seems like a big price to pay 

There are many levers to tune when approaching parallel work. Memory load versus parallelism is an ever-present trade-off in any system. If you can choose the size of the partitions, then you would start there.

> do you suggest to not work on a bag at all but rather apply all operations on the dataframe

In many cases, yes. As you say, though, there are things that pandas does badly, so experience is useful here. For some types of data, converting a piece of dataframe to a set of dicts will be expensive in memory; if you are, effectively, iterating over it, then it may be an unnecessary step. At this point, the best thing to do is profile the memory via the dashboard or with a sample chunk in your local process.

**Comment by PGryllos** [comment] 2018-11-29 16:17
> Yes, persist means that all of the data in the object (dataframe or bag or whatever) 

the reason why use persist is because later on I have two steps that will recompute the same things and I wanted to avoid duplicating the work.

* One is taking the unique values from the column of the df; this I have to compute because I later need to filter on those values (I haven't found a way to ask this lazily)
the unique values of the column definitely fit into memory; if I skip persist and do only the colum.unique.compute() still my memory explodes;

* I need to export the final df to disk

> At this point, the best thing to do is profile the memory via the dashboard or with a sample chunk in your local process

I tried using the dashboard profiler but the resulting flamegraph is one big green box which seems weird :/ 

>  If you can choose the size of the partitions

this will sound very noob, but where can I choose that? when loading the data? read_parquet doesn't allow you to specify such thing :|

**Comment by PGryllos** [comment] 2018-11-29 16:36
> You can share work between two graphs/operations without persisting, by including both in your call to compute

that's interesting I didn't know that; unfortunately I need the computed unique to filter columns of the dataframe that I later export. something like `df.column.isin(unique[:100])` isin wouldn't accept an future but it rather needs a list of values :/ 

wouldn't changing the number of partitions on later steps change the size of the partitions as well?

generally I feel like I need to revisit the construction my graphs from scratch :/

**Comment by martindurant** [comment] 2018-11-29 16:40
>  I have two steps that will recompute the same things 

Yes, you may be able to do that, but repartitioning itself is somewhat complex. You can try.

**Comment by PGryllos** [comment] 2018-11-29 16:42
from the conversation above I get the feeling that at whatever point the graph or graphs will be evaluated the results will have to be fit into memory of the workers if cannot be spilt to disk; which is counter intuitive given the fact that most distributed needs originate from the need of out of memory results :/ I am probably getting sth wrong right?

**Comment by martindurant** [comment] 2018-11-29 16:47
> the results will have to fit into memory of the workers if cannot be spilt to disk

The data of one partition per worker thread plus all intermediates needed in processing that partition; not all of the data. Dask executes python functions, it cannot interrupt them to take actions based on memory usage.

**Comment by PGryllos** [comment] 2018-11-29 16:52
so generally having smaller partitions makes the whole execution more resistant to oom but adds to the execution time since more individual chunks will have to be processed if i understand correctly

**Comment by martindurant** [comment] 2018-11-29 16:57
> but adds to the execution time since more individual chunks will have to be processed

There will be some extra overhead per task, but this may well remain very small compared to the total CPU time. Again, good to measure. Reckon a pessimistic ~1ms overhead per task, so make sure that the run time of the processing function on one chunk takes (much) longer than that.

Partitions too small: massive graph and lots of overhead. Partitions too big: OOM.

**Comment by martindurant** [comment] 2018-11-30 13:38
I would try the partition size first, I think. Also, if there is a way for the operation *not* to use that much memory...

**Comment by PGryllos** [comment] 2018-11-30 13:45
> I would try the partition size first
I am not in full control of that but will look into it;

> if there is a way for the operation not to use that much memory
that's even harder; the reason why it needs so much memory is because the only way I found for our etl job to feed my dask pipeline was the following; our etl job produces spark rdds that contain very large custom objects. from that I created a dataframe that contain the string representations of those objects; this can be exported to parquet and that's what I read in dask. So the first thing in my dask pipeline is to convert the strings back to objects; this is what explodes the memory for some of those objects; I havent found a better way to communicate between the two so really the only thing that I can do is read in strings and deserialize them back to objects (which I understand how it can make dask fully underestimate the size those objects will take) but if this isn't an option I am not sure I can connect dask to my dataset at all :/ wouldn't setting the target to sth very small fix the issue partially?

**Comment by PGryllos** [comment] 2018-11-30 15:36
@martindurant I figured a way to resize the partitions, created files of ~5mb instead of 180mb and now I am able to create much bigger thoughput in the pipeline. Thanks a lot :) I think it's clear now why the ooms where happening. Definitely learnt a lesson here :)

**Comment by birdsarah** [comment] 2019-07-26 03:59
Can this be closed?

**Comment by PGryllos** [comment] 2019-08-22 14:44
@birdsarah yep (:

**Comment by jrbourbeau** [comment] 2019-08-22 16:40
Closing. Thanks for following up on this @birdsarah!

**Closed by jrbourbeau** 2019-08-22 16:40 UTC
