### ISSUE TITLE
unexpected indices are out-of-bounds error

### ISSUE THREAD

**Issue by endremborza** [dask/dask#4859] opened 2019-05-30 07:35 UTC
**Bug report:**

I looked for quite a while, but couldn't find a reason for this:
```
>>> import dask.dataframe as dd
>>> import pandas as pd
>>> import numpy as np
>>> 
>>> pd.DataFrame(np.round(np.random.rand(1000000,10))
...                .astype(bool)).to_csv('tmp.csv',index_label='index')
>>> df = dd.read_csv('tmp.csv').set_index('index',sorted=True).persist()
>>> arr = df.loc[:,['0','1']].all(axis=1).values.persist()
>>> 
>>> arr.compute().shape
(1000000,)
>>> df.shape[0].compute()
1000000
>>> df.loc[arr.compute(),:].compute()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1518, in _getbool_axis
    return self.obj._take(inds, axis=axis)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py", line 3359, in _take
    verify=True)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/internals/managers.py", line 1341, in take
    indexer = maybe_convert_indices(indexer, n)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 2615, in maybe_convert_indices
    raise IndexError("indices are out-of-bounds")
IndexError: indices are out-of-bounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "/usr/local/lib/python3.6/dist-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/usr/local/lib/python3.6/dist-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/usr/local/lib/python3.6/dist-packages/dask/dataframe/methods.py", line 30, in loc
    return df.loc[iindexer, cindexer]
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 888, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1869, in _getitem_axis
    return self._getbool_axis(key, axis=axis)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py", line 1520, in _getbool_axis
    raise self._exception(detail)
KeyError: IndexError('indices are out-of-bounds',)
```

it works for smaller numbers, but gives KeyError: IndexError('indices are out-of-bounds',) for large enough ones, which it probably shouldn't. Doesn't give any other indication as to what is wrong.

**Comment by endremborza** [comment] 2019-05-30 07:38
oh, and if I leave off the last compute off the last arr,

```
df.loc[arr,:].compute()
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

this is rather unexpected as well

**Comment by jakirkham** [comment] 2019-05-31 16:32
@TomAugspurger, would you have a chance to look at this?

**Comment by TomAugspurger** [comment] 2019-05-31 16:36
@endremborza which versions of pandas and dask? I don't see an error on `df.loc[arr.compute(),:].compute()` with dask master and pandas 0.24.2

**Comment by TomAugspurger** [comment] 2019-05-31 16:38
> oh, and if I leave off the last compute off the last arr,

That's possibly a bug. For a boolean Dask Array mask, we should assume that the length of the array matches the length of the Dataframe, and raise a execution time if they aren't. Essentially the same as `df.loc[df['0']]`, but without the alignment.

**Comment by endremborza** [comment] 2019-06-01 12:10
1.2.2 and 0.24.2
you may need to increase the number of rows or force it to more partitions.

**Comment by TomAugspurger** [comment] 2019-06-01 12:14
Do you have an example that reliably reproduces?

**Comment by endremborza** [comment] 2019-06-01 12:30
I don't know what to tell you, it reliably reproduces for me. Ubuntu 16 docker image, python 3.6.8

```     
Python 3.6.8 (default, Dec 24 2018, 19:24:27) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> import dask
>>> import dask.dataframe as dd
>>> import pandas as pd
>>> import numpy as np
>>> 
>>> dask.__version__
'1.2.2'
>>> 
>>> pd.__version__
'0.24.2'
>>> 
>>> datetime.datetime.now().isoformat()
'2019-06-01T12:24:34.111039'
>>> 
>>> pd.DataFrame(np.round(np.random.rand(1000000,10))
...                .astype(bool)).to_csv('tmp.csv',index_label='index')
>>> 
>>> df = dd.read_csv('tmp.csv').set_index('index',sorted=True).persist()
>>> arr = df.loc[:,['0','1']].all(axis=1).values.persist()
>>> 
>>> arr.compute().shape
(1000000,)
>>> 
>>> df.shape[0].compute()
1000000
>>> 
```

after this both with or without ```.compute()``` after arr gives the same error as described above.

it works if i decrease the rownum from 1,000,000 to 100,000, thats why I suggested you increase that.

**Comment by TomAugspurger** [comment] 2019-06-04 11:59
Bumping your example to 10000000 rows still works for me. Can you try on dask master?

**Comment by endremborza** [comment] 2019-06-04 15:32
just did, on a different machine (ubuntu 16), not in docker, just venv, same result. both value error and index error.

**Comment by TomAugspurger** [comment] 2019-06-04 16:03
Strange. Are you interested in investigate this further, since you can
reproduce it?

**Comment by endremborza** [comment] 2019-06-04 16:16
it would be nice to know whether it affects others as well, but i am planning on using dask in the future, so i might as well look into it a bit.

do you have any idea where to start based on the traceback?

**Comment by TomAugspurger** [comment] 2019-06-04 16:26
I would look at

  File "/usr/local/lib/python3.6/dist-packages/dask/dataframe/methods.py", line 30, in loc
    return df.loc[iindexer, cindexer]


printing out `len(df), len(iindexer)` and move from there.

**Comment by endremborza** [comment] 2019-06-04 16:37
ok, will do.

one last try for reproducibility, ditching the csv and the big numbers, tried on dask-master:

```
>>> import dask.dataframe as dd
>>> import pandas as pd
>>> import numpy as np
>>> 
>>> pdf = pd.DataFrame([[True, True, False],
...                     [True, False, True],
...                     [True, False, True],
...                     [True, True, True],
...                     [True, False, True],
...                     [True, True, True],
...                     [True, False, True]] * 10)
>>> 
>>> 
>>> df = dd.from_pandas(pdf,npartitions=4)
>>> 
>>> 
>>> arr = df.loc[:,[0,1]].all(axis=1).values.persist()
>>> 
>>> arr.compute().shape
(70,)
>>> 
>>> df.shape[0].compute()
70
>>> 
>>> df.loc[arr.compute(),:].compute()
Traceback (most recent call last):
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/daskvenv/lib/python3.6/site-packages/pandas/core/indexing.py", line 1518, in _getbool_axis
    return self.obj._take(inds, axis=axis)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/daskvenv/lib/python3.6/site-packages/pandas/core/generic.py", line 3359, in _take
    verify=True)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/daskvenv/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 1341, in take
    indexer = maybe_convert_indices(indexer, n)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/daskvenv/lib/python3.6/site-packages/pandas/core/indexing.py", line 2615, in maybe_convert_indices
    raise IndexError("indices are out-of-bounds")
IndexError: indices are out-of-bounds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/compatibility.py", line 113, in reraise
    raise exc
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/dataframe/methods.py", line 30, in loc
    return df.loc[iindexer, cindexer]
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/daskvenv/lib/python3.6/site-packages/pandas/core/indexing.py", line 1494, in __getitem__
    return self._getitem_tuple(key)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/daskvenv/lib/python3.6/site-packages/pandas/core/indexing.py", line 888, in _getitem_tuple
    retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/daskvenv/lib/python3.6/site-packages/pandas/core/indexing.py", line 1869, in _getitem_axis
    return self._getbool_axis(key, axis=axis)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/daskvenv/lib/python3.6/site-packages/pandas/core/indexing.py", line 1520, in _getbool_axis
    raise self._exception(detail)
KeyError: IndexError('indices are out-of-bounds',)
>>> 
>>> df.loc[arr,:].compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/dataframe/indexing.py", line 92, in __getitem__
    return self._loc(iindexer, cindexer)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/dataframe/indexing.py", line 108, in _loc
    return self._loc_element(iindexer, cindexer)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/dataframe/indexing.py", line 160, in _loc_element
    part = self._get_partitions(iindexer)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/dataframe/indexing.py", line 177, in _get_partitions
    return _partition_of_index_value(self.obj.divisions, keys)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/dataframe/indexing.py", line 260, in _partition_of_index_value
    i = bisect.bisect_right(divisions, val)
  File "/home/borza/Dropbox/Programs/pet-projects/issues/dask/dask/dask/array/core.py", line 1192, in __bool__
    return bool(self.compute())
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Comment by endremborza** [comment] 2019-06-04 16:47
ok, the error is clearly that dask doesn't partition the values, so that it tries to index the partitioned dataframes with the entire boolean array.

where should dask break up the array to partitions?

**Comment by endremborza** [comment] 2019-06-04 16:54
in the value error case, dask, for some reason tries to evaluate ```dask.array<lt, shape=(nan,), dtype=bool, chunksize=(nan,)>```, which has size nan, so the built in check at arra/core.py:1187 doesnt catch it, then it gets computed to a (70,) shaped array which fails in the builtin bool().

even weirder, that all 70 are true, when they shouldn't be

**Comment by endremborza** [comment] 2019-06-04 17:23
For this second one, i see a simple solution, will post a PR, possibly later today

**Comment by jsignell** [comment] 2020-04-30 14:23
It seems like the error that is being raised for the first part of this issue is a different, more informative one now:

```python-traceback
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-11-a828d9165f3f> in <module>
----> 1 df.loc[arr.compute(),:].compute()

~/dask/dask/base.py in compute(self, **kwargs)
    164         dask.base.compute
    165         """
--> 166         (result,) = compute(self, traverse=False, **kwargs)
    167         return result
    168 

~/dask/dask/base.py in compute(*args, **kwargs)
    435     keys = [x.__dask_keys__() for x in collections]
    436     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 437     results = schedule(dsk, keys, **kwargs)
    438     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    439 

~/dask/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     82         get_id=_thread_get_id,
     83         pack_exception=pack_exception,
---> 84         **kwargs
     85     )
     86 

~/dask/dask/local.py in get_async(apply_async, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, **kwargs)
    484                         _execute_task(task, data)  # Re-execute locally
    485                     else:
--> 486                         raise_exception(exc, tb)
    487                 res, worker_id = loads(res_info)
    488                 state["cache"][key] = res

~/dask/dask/local.py in reraise(exc, tb)
    314     if exc.__traceback__ is not tb:
    315         raise exc.with_traceback(tb)
--> 316     raise exc
    317 
    318 

~/dask/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    220     try:
    221         task, data = loads(task_info)
--> 222         result = _execute_task(task, data)
    223         id = get_id()
    224         result = dumps((result, id))

~/dask/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/dask/dask/dataframe/methods.py in loc(df, iindexer, cindexer)
     28         return df.loc[iindexer]
     29     else:
---> 30         return df.loc[iindexer, cindexer]
     31 
     32 

~/conda/envs/dask-dev/lib/python3.7/site-packages/pandas/core/indexing.py in __getitem__(self, key)
   1760                 except (KeyError, IndexError, AttributeError):
   1761                     pass
-> 1762             return self._getitem_tuple(key)
   1763         else:
   1764             # we by definition only have the 0th axis

~/conda/envs/dask-dev/lib/python3.7/site-packages/pandas/core/indexing.py in _getitem_tuple(self, tup)
   1287                 continue
   1288 
-> 1289             retval = getattr(retval, self.name)._getitem_axis(key, axis=i)
   1290 
   1291         return retval

~/conda/envs/dask-dev/lib/python3.7/site-packages/pandas/core/indexing.py in _getitem_axis(self, key, axis)
   1912             return self._get_slice_axis(key, axis=axis)
   1913         elif com.is_bool_indexer(key):
-> 1914             return self._getbool_axis(key, axis=axis)
   1915         elif is_list_like_indexer(key):
   1916 

~/conda/envs/dask-dev/lib/python3.7/site-packages/pandas/core/indexing.py in _getbool_axis(self, key, axis)
   1780         # caller is responsible for ensuring non-None axis
   1781         labels = self.obj._get_axis(axis)
-> 1782         key = check_bool_indexer(labels, key)
   1783         inds = key.nonzero()[0]
   1784         return self.obj._take_with_is_copy(inds, axis=axis)

~/conda/envs/dask-dev/lib/python3.7/site-packages/pandas/core/indexing.py in check_bool_indexer(index, key)
   2326         result = check_array_indexer(index, result)
   2327     else:
-> 2328         result = check_array_indexer(index, result)
   2329 
   2330     return result

~/conda/envs/dask-dev/lib/python3.7/site-packages/pandas/core/indexers.py in check_array_indexer(array, indexer)
    399         if len(indexer) != len(array):
    400             raise IndexError(
--> 401                 f"Boolean index has wrong length: "
    402                 f"{len(indexer)} instead of {len(array)}"
    403             )

IndexError: Boolean index has wrong length: 70 instead of 18
```

This still feels like unexpected behavior to me but based on the discussion in #4882 I couldn't tell if people are interested in trying to support using pandas arrays in `.loc` like this.

**Comment by jsignell** [comment] 2020-04-30 16:01
At this point I think this is a duplicate of #1999.

**Closed by jsignell** 2020-04-30 16:01 UTC
Labels: dataframe
