### ISSUE TITLE
ValueError: Order of columns does not match

### ISSUE THREAD

**Issue by natsunami** [dask/dask#6856] opened 2020-11-19 11:17 UTC
Hello Dask community !

**What happened**:
While working on the [microsoft malware prediction](https://www.kaggle.com/c/microsoft-malware-prediction) I preprocessed my X_train dataset using pipelines to perform an XGBoost. Having now an X_train_processed dataset i just wanted to compute the number of rows but I'm facing the following ValueError:The columns in the computed data do not match the columns in the provided metadata
Order of columns does not match. I have the same issue when i want to save X_train_processed to a csv and also I suppose that's the reason why my XGBoost doesn't work.

I understand that it is due to my metadata order but the columns of X_train_processed and the metadata should match since i specified them in the same order...

```python

binary_processor = Pipeline(steps=[('imputer',SimpleImputer(strategy='most_frequent'))])

numerical_processor = Pipeline(steps=[('imputer',SimpleImputer(strategy='median')),
                                      ('scaler', StandardScaler())])

categorical_processor = Pipeline(steps=[('encoder',OneHotEncoder())])

#category_processor = Pipeline(steps=[('encoder',TargetEncoder(cols=category_columns))])

preprocessor = ColumnTransformer(transformers=
                                [('bin',binary_processor,binary_columns),
                                ('num',numerical_processor,numerical_columns),
                                ('cat',categorical_processor,category_columns)])

X_train_processed = preprocessor.fit_transform(X_train)

meta = pd.DataFrame(columns=X_train_processed.columns)

for col in X_train_processed.columns:
    meta[col] = meta[col].astype(X_train_processed[col].dtype)
    
    
#meta_train = {col:X_train_processed[col].dtype for col in X_train_processed}
X_train_processed = X_train_processed.map_partitions(lambda x: x, meta= meta)
X_train_processed = X_train_processed.persist()

X_train_processed.shape[0].compute()
```
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-342-50b3423c32e5> in <module>
----> 1 X_train_processed.shape[0].compute()

~/anaconda3/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    165         dask.base.compute
    166         """
--> 167         (result,) = compute(self, traverse=False, **kwargs)
    168         return result
    169 

~/anaconda3/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    450         postcomputes.append(x.__dask_postcompute__())
    451 
--> 452     results = schedule(dsk, keys, **kwargs)
    453     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    454 

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2723                     should_rejoin = False
   2724             try:
-> 2725                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2726             finally:
   2727                 for f in futures.values():

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1984             else:
   1985                 local_worker = None
-> 1986             return self.sync(
   1987                 self._gather,
   1988                 futures,

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    830             return future
    831         else:
--> 832             return sync(
    833                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    834             )

~/anaconda3/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]

~/anaconda3/lib/python3.8/site-packages/distributed/utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()

~/anaconda3/lib/python3.8/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/anaconda3/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1849                             exc = CancelledError(key)
   1850                         else:
-> 1851                             raise exception.with_traceback(traceback)
   1852                         raise exc
   1853                     if errors == "skip":

/opt/conda/lib/python3.8/site-packages/dask/optimization.py in __call__()

/opt/conda/lib/python3.8/site-packages/dask/core.py in get()

/opt/conda/lib/python3.8/site-packages/dask/core.py in _execute_task()

/opt/conda/lib/python3.8/site-packages/dask/utils.py in apply()

/opt/conda/lib/python3.8/site-packages/dask/dataframe/core.py in apply_and_enforce()

/opt/conda/lib/python3.8/site-packages/dask/dataframe/utils.py in check_matching_columns()

ValueError: The columns in the computed data do not match the columns in the provided metadata
Order of columns does not match
```
Thanks for the help !

**Environment**:

- Dask version: 2.30.0
- Python version: 3.8.5
- Operating System: Ubuntu 18.5.4 LTS
- Install method (conda, pip, source): pip

**Comment by jsignell** [comment] 2020-11-19 15:33
Thanks for raising this issue, but it it hard to debug without a reproducible example. I would suggest that you print the columns on each of the variables and that you call compute at several points on the dask.dataframes to check that the computed columns are what you expect.

**Comment by rjzamora** [comment] 2020-11-19 15:37
Yeah - A simple reproducer would help a lot here - Also, if `X_train_processed` is a dask DataFrame, it would be good to check what the `X_train_processed._meta` looks like after the fit, and to check that `X_train_processed.head()` shows the correct column order.

**Comment by jrbourbeau** [comment] 2021-11-02 22:50
Closing due to lack of reproducer (see https://blog.dask.org/2018/02/28/minimal-bug-reports for more details). @natsunami feel free to re-open if you're able to provide a reproducer others can run to help debug.

**Closed by jrbourbeau** 2021-11-02 22:50 UTC
Labels: needs info
