### ISSUE TITLE
Dask worker - kubernetes

### ISSUE THREAD

**Issue by devopsdymyr** [dask/dask#5840] opened 2020-01-29 15:27 UTC
I have create dask cluster setup using helm[https://docs.dask.org/en/latest/setup/kubernetes-helm.html],Which is working fine.
Tried to added some of the modules in that worker getting failed.
 Steps followed to executed required modules added in the dockerfile
Repo url: **https://github.com/learningdymyr/dask-docker/blob/master/base/Dockerfile**

git clone https://github.com/learningdymyr/dask-docker.git
docker build -t dask base/.

![Screenshot from 2020-01-29 20-55-08](https://user-images.githubusercontent.com/41105507/73370088-ab730600-42d9-11ea-9221-c2193dd9ad60.png)

**Comment by jrbourbeau** [comment] 2020-01-29 15:43
It looks like the problem is related to `conda` resolving the package dependencies you specified. Do you know if the versions you've pinned in the `Dockerfile` are consistent with one another?

**Comment by devopsdymyr** [comment] 2020-01-29 16:24
@jrbourbeau i have used to install all dependencies  as mentined in dockerfile.

Please let me know how to install all dependencies in dockerimage

I am doing some chnages in the dockerfile to install all module with help of requirements.txt but i am not sure this will work or not.
Dockerfile
FROM continuumio/miniconda3:4.7.12

RUN conda install --yes \
    -c conda-forge \
    python-blosc \
    cytoolz \
    dask==2.9.2 \
    lz4 \
    nomkl \
    numpy==1.17.3 \
    pandas==0.25.2 \
    tini==0.18.0 \
    && conda clean -tipsy \
    && find /opt/conda/ -type f,l -name '*.a' -delete \
    && find /opt/conda/ -type f,l -name '*.pyc' -delete \
    && find /opt/conda/ -type f,l -name '*.js.map' -delete \
    && find /opt/conda/lib/python*/site-packages/bokeh/server/static -type f,l -name '*.js' -not -name '*.min.js' -delete \
    && rm -rf /opt/conda/pkgs

COPY prepare.sh /usr/bin/prepare.sh && requirements.txt  /opt/

RUN pip3 --no-cache-dir install -r /opt/requirements.txt

RUN mkdir /opt/app

ENTRYPOINT ["tini", "-g", "--", "/usr/bin/prepare.sh"]

requirements.txt
Flask ==0.12 
cython 
simplejson==3.16.0 
pandas 
numpy==1.17.3 
statsmodels==0.9.0 
scipy==1.2.0 
python-dateutil==2.7.5 
requests==2.21.0 
glob2==0.6 
passlib==1.7.1 
joblib==0.13.2 
scikit-learn==0.22 
dask-ml==1.2.0 
distributed==2.9.3 
fsspec==0.6.2 

Please give me some idea on this issue.

**Comment by jrbourbeau** [comment] 2020-02-04 20:54
The docker images Dask maintains allow you install additional packages by specifying certain environment variables. For example, setting `EXTRA_CONDA_PACKAGES="numba xarray=0.15.0 -c conda-forge"` will install the `xarray` version 0.15.0 and the latest release of `numba` from the conda-forge channel. See https://docs.dask.org/en/latest/setup/docker.html#extensibility for more details

**Comment by devopsdymyr** [comment] 2020-02-05 05:36
Thanks , using conda is taking time to build,so i have used pip to install

**Comment by TomAugspurger** [comment] 2020-02-05 12:20
Sounds like everything is good here.

**Closed by TomAugspurger** 2020-02-05 12:20 UTC
