### ISSUE TITLE
read_sql returns "Metadata mismatch" when part of column is Null

### ISSUE THREAD

**Issue by pjarnhus** [dask/dask#2974] opened 2017-12-08 09:45 UTC
Hi,

I am trying to load a larger SQL table (18 Mrows and 800 columns) into a Dask Dataframe from a Microsoft SQL Server 2012. The `dask.dataframe.read_sql` call goes as planned using the code:

> server = 'SERVER'
db = 'DATABASE'
table = 'TABLE'
connection_string = 'DRIVER={SQL Server};SERVER=' + server + ';DATABASE=' + db + ';Trusted_Connection=yes'
connection_string = quote_plus(connection_string)
connection_string = 'mssql+pyodbc:///?odbc_connect='+connection_string
df = dd.read_sql_table(table,
                       connection_string,
                       sql.cast(sql.column("ID"),types.BigInteger).label("ID"))

When trying to compute something from it, e.g. `df.index.count().compute()`, I get a "Metadata mismatch" error with the full error dump of:

>---------------------------------------------------------------------------
>ValueError                                Traceback (most recent call last)
><ipython-input-4-507b56f31afd> in <module>()
>----> 1 df.index.count().compute()
>
>~\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\base.py in compute(self, **kwargs)
>    133         dask.base.compute
>    134         """
>--> 135         (result,) = compute(self, traverse=False, **kwargs)
>    136         return result
>    137 
>
>~\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\base.py in compute(*args, **kwargs)
>    331     postcomputes = [a.__dask_postcompute__() if is_dask_collection(a)
>    332                     else (None, a) for a in args]
>--> 333     results = get(dsk, keys, **kwargs)
>    334     results_iter = iter(results)
>    335     return tuple(a if f is None else f(next(results_iter), *a)
>
>~\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\threaded.py in get(dsk, result, cache, >num_workers, **kwargs)
>     73     results = get_async(pool.apply_async, len(pool._pool), dsk, result,
>     74                         cache=cache, get_id=_thread_get_id,
>---> 75                         pack_exception=pack_exception, **kwargs)
>     76 
>     77     # Cleanup pools associated to dead threads
>
>~\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\local.py in get_async(apply_async, >num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, >callbacks, dumps, loads, **kwargs)
>    519                         _execute_task(task, data)  # Re-execute locally
>    520                     else:
>--> 521                         raise_exception(exc, tb)
>    522                 res, worker_id = loads(res_info)
>    523                 state['cache'][key] = res
>
>~\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\compatibility.py in reraise(exc, tb)
>     58         if exc.__traceback__ is not tb:
>     59             raise exc.with_traceback(tb)
>---> 60         raise exc
>     61 
>     62 else:
>
>~\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\local.py in execute_task(key, task_info, >dumps, loads, get_id, pack_exception)
>    288     try:
>    289         task, data = loads(task_info)
>--> 290         result = _execute_task(task, data)
>    291         id = get_id()
>    292         result = dumps((result, id))
>
>~\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\local.py in _execute_task(arg, cache, >dsk)
>    269         func, args = arg[0], arg[1:]
>    270         args2 = [_execute_task(a, cache) for a in args]
>--> 271         return func(*args2)
>    272     elif not ishashable(arg):
>    273         return arg
>
>~\AppData\Local\Continuum\Anaconda3\lib\site-packages\dask\dataframe\utils.py in check_meta(x, >meta, funcname, numeric_equal)
>    490     raise ValueError("Metadata mismatch found%s.\n\n"
>   491                      "%s" % ((" in `%s`" % funcname if funcname else ""),
>--> 492                              errmsg))
>    493 
>    494 
>
>ValueError: Metadata mismatch found in `from_delayed`.

I believe that the error comes from how pandas behaves with `read_sql`, and how dask uses the pandas function. It looks to me like dask determines the data type for the column from the first few columns. In my table most of the columns are `tinyint` or `decimal(10,3)`, which dask/pandas pick up correctly. The issue, however, arise later on, if one of the subsets that dask reads from the table contains all NULLs in a column. Pandas then casts this column as an object, which causes dask to throw the `Metadata mismatch` error.

I am terribly sorry, that I have not been able to create an example, that I can provide. I hope that the explanation was clear nonetheless. If you need me to provide an example, I shall try to construct one over the weekend.

Thank you!

**Comment by martindurant** [comment] 2017-12-08 17:19
Note that `read_sql_table` takes keyword arguments which are passed to pandas. I do not see a way to *specify* the data-types using this mechanism, however. 
What perhaps you could do, is to construct the set of data types you would like (perhaps based on the `df.meta` empty data-frame) and use `df.map_partitions` to apply to each part of the dataframe.

**Comment by TomAugspurger** [comment] 2017-12-08 17:31
Pandas has an open issue to add a `dtype` parameter to `read_sql`: https://github.com/pandas-dev/pandas/issues/13049

**Comment by pjarnhus** [comment] 2017-12-09 19:02
Hi both,

Thank you for getting back to me on this!

@TomAugspurger I am aware of the open pandas issue, it is getting near legendary status :)

@martindurant I am not quite sure of the proper way to apply the `df.map_partitions` correctly. Perhaps you can give me some pointers on what I do wrong. I have constructed the follow example, which produces the error above, but I cannot seem to get it to work:

> import pandas as pd
>import dask.dataframe as dd
>import numpy as np
>import sqlite3 as sq
>
>conn = sq.connect('temp.db')
>
>cursor = conn.cursor()
>cursor.execute('CREATE TABLE test(id int, val real);')
>
>cursor.executemany('INSERT INTO test VALUES (?,?);',list(zip(range(50),list(np.random.randn(25))+[None]*25)))
>conn.commit()
>
>conn.close()
>
>dask_df = dd.read_sql_table('test',uri,index_col='id',npartitions=5)
>
>dask_df.map_partitions(lambda df: df.astype({c:t for c,t in zip(dask_df._meta.dtypes.index,
>                                                                dask_df._meta.dtypes)}),
>                      meta=dask_df._meta)
>
>dask_df.index.count().compute()

Also... It seems rather clunky, that you have to apply this after the extract. Is there a reason, why a data type coercing has not been applied in the function directly, where the individual pandas dataframes are extracted (line 136)?

**Comment by martindurant** [comment] 2017-12-09 22:04
The following code fixes your problem. I'm not sure if it is the *right* fix, especially given that pandas' function may soon accept a `dtypes` parameter. That is why this is not a PR. In the following, you can either provide a `dtypes` (which is a dictionary), or else the function will attempt to apply the dtypes of the head to all partitions.

```
--- a/dask/dataframe/io/sql.py
+++ b/dask/dataframe/io/sql.py
@@ -8,6 +8,7 @@ from .io import from_delayed

 def read_sql_table(table, uri, index_col, divisions=None, npartitions=None,
                    limits=None, columns=None, bytes_per_chunk=256 * 2**20,
+                   dtypes=None,
                    **kwargs):
     """
     Create dataframe from an SQL table.
@@ -96,6 +97,8 @@ def read_sql_table(table, uri, index_col, divisions=None, npartitions=None,

     q = sql.select(columns).limit(5).select_from(table)
     head = pd.read_sql(q, engine, **kwargs)
+    if dtypes:
+        head = head.astype(dtypes)

     if divisions is None:
         if limits is None:
@@ -128,6 +131,11 @@ def read_sql_table(table, uri, index_col, divisions=None, npartitions=None,
         cond = index <= upper if i == len(lowers) - 1 else index < upper
         q = sql.select(columns).where(sql.and_(index >= lower, cond)
                                       ).select_from(table)
-        parts.append(delayed(pd.read_sql)(q, uri, **kwargs))
+        d = delayed(pd.read_sql)(q, uri, **kwargs)
+        if dtypes:
+            d = delayed(pd.DataFrame.astype)(d, dtypes)
+        else:
+            d = delayed(pd.DataFrame.astype)(d, head.dtypes.to_dict())
+        parts.append(d)

     return from_delayed(parts, head, divisions=divisions)
```

**Comment by pjarnhus** [comment] 2017-12-10 13:53
@martindurant Thanks for the input. I asked the question regarding why it was not a part of current codebase to see, if I could offer up my help. It makes sense to wait for the pandas team to incorporate it at their level.

I was trying to make the `map_partitions` to work, but keep coming up short. Would you mind pointing me in the right direction? I have tried
```
import pandas as pd
import dask.dataframe as dd
import numpy as np
import sqlite3 as sq

conn = sq.connect('temp.db')

cursor = conn.cursor()
cursor.execute('DROP TABLE IF EXISTS test;')
cursor.execute('CREATE TABLE test(id int, val real);')
 
cursor.executemany('INSERT INTO test VALUES (?,?);',list(zip(range(50),list(np.random.randn(25))+None]*25)))
conn.commit()
conn.close()
 
dask_df = dd.read_sql_table('test','sqlite:///temp.db',index_col='id',npartitions=5)
new_dtypes = {c:t for c,t in zip(dask_df.dtypes.index,dask_df.dtypes)}
 
ddf = dask_df.map_partitions(lambda df: df.astype(new_dtypes), meta=dask_df._meta)

ddf.index.count().compute()
```

but it still produces the same error.

Sorry for all the questions, but I wish to provide the other data scientists in the team with a working example, when I recommend to them to use dask as part of their modelling flow.

**Comment by martindurant** [comment] 2017-12-10 21:47
@pjarnhus , are you willing to test the code that I posted above, to see if it suits your use? It certainly solves the sqlite test case you give.
With changes:
```
In [3]: uri = 'sqlite:///temp.db'

In [4]: dask_df = dd.read_sql_table('test',uri,index_col='id',npartitions=5)

In [5]: dask_df.index.count().compute()
Out[5]: 50
```

**Comment by Shellcat-Zero** [comment] 2018-01-16 21:56
Thanks @martindurant, after implementing your fix, I no longer have the error I was getting:
```
ValueError: Metadata mismatch found in `from_delayed`.

Partition type: `DataFrame`
+---------------+--------+----------------+
| Column        | Found  | Expected       |
+---------------+--------+----------------+
| date_of_birth | object | datetime64[ns] |
| pay_day1      | object | datetime64[ns] |
| pay_day2      | object | datetime64[ns] |
+---------------+--------+----------------+
```
However, now I am getting a different error I am not sure of how to debug here in Dask:
```
In [2]: df.head()
distributed.utils - ERROR - Month out of range in datetime string "0000-00-00 00:00:00"
Traceback (most recent call last):
  File "/opt/anaconda/lib/python3.5/site-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/opt/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/anaconda/lib/python3.5/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/anaconda/lib/python3.5/site-packages/distributed/client.py", line 1315, in _gather
    traceback)
  File "/opt/anaconda/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/anaconda/lib/python3.5/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.5/site-packages/pandas/core/generic.py", line 3997, in astype
    results.append(col.astype(dtype[col_name], copy=copy))
  File "/opt/anaconda/lib/python3.5/site-packages/pandas/util/_decorators.py", line 118, in wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.5/site-packages/pandas/core/generic.py", line 4004, in astype
    **kwargs)
  File "/opt/anaconda/lib/python3.5/site-packages/pandas/core/internals.py", line 3462, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/opt/anaconda/lib/python3.5/site-packages/pandas/core/internals.py", line 3329, in apply
    applied = getattr(b, f)(**kwargs)
  File "/opt/anaconda/lib/python3.5/site-packages/pandas/core/internals.py", line 544, in astype
    **kwargs)
  File "/opt/anaconda/lib/python3.5/site-packages/pandas/core/internals.py", line 625, in _astype
    values = astype_nansafe(values.ravel(), dtype, copy=True)
  File "/opt/anaconda/lib/python3.5/site-packages/pandas/core/dtypes/cast.py", line 703, in astype_nansafe
    return arr.astype(dtype)
ValueError: Month out of range in datetime string "0000-00-00 00:00:00"
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-2569c44faf66> in <module>()
----> 1 df.head()

/opt/anaconda/lib/python3.5/site-packages/dask/dataframe/core.py in head(self, n, npartitions, compute)
    844
    845         if compute:
--> 846             result = result.compute()
    847         return result
    848

/opt/anaconda/lib/python3.5/site-packages/dask/base.py in compute(self, **kwargs)
    133         dask.base.compute
    134         """
--> 135         (result,) = compute(self, traverse=False, **kwargs)
    136         return result
    137

/opt/anaconda/lib/python3.5/site-packages/dask/base.py in compute(*args, **kwargs)
    331     postcomputes = [a.__dask_postcompute__() if is_dask_collection(a)
    332                     else (None, a) for a in args]
--> 333     results = get(dsk, keys, **kwargs)
    334     results_iter = iter(results)
    335     return tuple(a if f is None else f(next(results_iter), *a)

/opt/anaconda/lib/python3.5/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, **kwargs)
   1997                 secede()
   1998             try:
-> 1999                 results = self.gather(packed, asynchronous=asynchronous)
   2000             finally:
   2001                 for f in futures.values():

/opt/anaconda/lib/python3.5/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1435             return self.sync(self._gather, futures, errors=errors,
   1436                              direct=direct, local_worker=local_worker,
-> 1437                              asynchronous=asynchronous)
   1438
   1439     @gen.coroutine

/opt/anaconda/lib/python3.5/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    590             return future
    591         else:
--> 592             return sync(self.loop, func, *args, **kwargs)
    593
    594     def __repr__(self):

/opt/anaconda/lib/python3.5/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    252             e.wait(1000000)
    253     if error[0]:
--> 254         six.reraise(*error[0])
    255     else:
    256         return result[0]

/opt/anaconda/lib/python3.5/site-packages/six.py in reraise(tp, value, tb)
    684         if value.__traceback__ is not tb:
    685             raise value.with_traceback(tb)
--> 686         raise value
    687
    688 else:

/opt/anaconda/lib/python3.5/site-packages/distributed/utils.py in f()
    236             yield gen.moment
    237             thread_state.asynchronous = True
--> 238             result[0] = yield make_coro()
    239         except Exception as exc:
    240             logger.exception(exc)

/opt/anaconda/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1053
   1054                     try:
-> 1055                         value = future.result()
   1056                     except Exception:
   1057                         self.had_exception = True

/opt/anaconda/lib/python3.5/site-packages/tornado/concurrent.py in result(self, timeout)
    236         if self._exc_info is not None:
    237             try:
--> 238                 raise_exc_info(self._exc_info)
    239             finally:
    240                 self = None

/opt/anaconda/lib/python3.5/site-packages/tornado/util.py in raise_exc_info(exc_info)

/opt/anaconda/lib/python3.5/site-packages/tornado/gen.py in run(self)
   1061                     if exc_info is not None:
   1062                         try:
-> 1063                             yielded = self.gen.throw(*exc_info)
   1064                         finally:
   1065                             # Break up a reference to itself

/opt/anaconda/lib/python3.5/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1313                             six.reraise(type(exception),
   1314                                         exception,
-> 1315                                         traceback)
   1316                     if errors == 'skip':
   1317                         bad_keys.add(key)

/opt/anaconda/lib/python3.5/site-packages/six.py in reraise(tp, value, tb)
    683             value = tp()
    684         if value.__traceback__ is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value
    687

/opt/anaconda/lib/python3.5/site-packages/pandas/util/_decorators.py in wrapper()
    116                 else:
    117                     kwargs[new_arg_name] = new_arg_value
--> 118             return func(*args, **kwargs)
    119         return wrapper
    120     return _deprecate_kwarg

/opt/anaconda/lib/python3.5/site-packages/pandas/core/generic.py in astype()
   3995             for col_name, col in self.iteritems():
   3996                 if col_name in dtype:
-> 3997                     results.append(col.astype(dtype[col_name], copy=copy))
   3998                 else:
   3999                     results.append(results.append(col.copy() if copy else col))

/opt/anaconda/lib/python3.5/site-packages/pandas/util/_decorators.py in wrapper()
    116                 else:
    117                     kwargs[new_arg_name] = new_arg_value
--> 118             return func(*args, **kwargs)
    119         return wrapper
    120     return _deprecate_kwarg

/opt/anaconda/lib/python3.5/site-packages/pandas/core/generic.py in astype()
   4002         # else, only a single dtype is given
   4003         new_data = self._data.astype(dtype=dtype, copy=copy, errors=errors,
-> 4004                                      **kwargs)
   4005         return self._constructor(new_data).__finalize__(self)
   4006

/opt/anaconda/lib/python3.5/site-packages/pandas/core/internals.py in astype()
   3460
   3461     def astype(self, dtype, **kwargs):
-> 3462         return self.apply('astype', dtype=dtype, **kwargs)
   3463
   3464     def convert(self, **kwargs):

/opt/anaconda/lib/python3.5/site-packages/pandas/core/internals.py in apply()
   3327
   3328             kwargs['mgr'] = self
-> 3329             applied = getattr(b, f)(**kwargs)
   3330             result_blocks = _extend_blocks(applied, result_blocks)
   3331

/opt/anaconda/lib/python3.5/site-packages/pandas/core/internals.py in astype()
    542     def astype(self, dtype, copy=False, errors='raise', values=None, **kwargs):
    543         return self._astype(dtype, copy=copy, errors=errors, values=values,
--> 544                             **kwargs)
    545
    546     def _astype(self, dtype, copy=False, errors='raise', values=None,

/opt/anaconda/lib/python3.5/site-packages/pandas/core/internals.py in _astype()
    623
    624                 # _astype_nansafe works fine with 1-d only
--> 625                 values = astype_nansafe(values.ravel(), dtype, copy=True)
    626                 values = values.reshape(self.shape)
    627

/opt/anaconda/lib/python3.5/site-packages/pandas/core/dtypes/cast.py in astype_nansafe()
    701
    702     if copy:
--> 703         return arr.astype(dtype)
    704     return arr.view(dtype)
    705

ValueError: Month out of range in datetime string "0000-00-00 00:00:00"
```

**Comment by martindurant** [comment] 2018-01-16 22:02
Wow, that is a fascinating one, @Shellcat-Zero . Could it be that your DB represents null values os time ZERO? Does attempting to load (some of) the same data directly with one of pandas' SQL functions cause the same error? I am not certain from the traceback whether this is happening during the initial calculation of the divisions or during the actual data load - you may want to try providing divisions yourself.

**Comment by Shellcat-Zero** [comment] 2018-01-16 22:27
Yes, @martindurant, my null values in the DB are represented as time zero.  In pandas, these are automatically transformed to 'NaT':
```
22     2011-10-14
23     2011-10-07
24     2011-10-28
25     2011-11-09
26     2011-11-09
27     2011-10-07
28     2011-10-28
29     2011-10-07
          ...
9970          NaT
9971          NaT
9972          NaT
9973          NaT
9974          NaT
9975          NaT
9976          NaT
9977          NaT
9978          NaT
9979          NaT
9980   2011-11-30
9981          NaT
9982          NaT
```

**Comment by Shellcat-Zero** [comment] 2018-01-16 22:32
Would manually providing divisions somehow fix this error?  In pandas, a manual conversion was once necessary to transform bad values to 'NaT', but this is now handled automatically within pandas (see https://github.com/pandas-dev/pandas/issues/3475).

**Comment by martindurant** [comment] 2018-01-17 00:58
That is interesting, because `pd.to_datetime("0000-00-00 00:00:00")` causes an exception for me. Providing divisions *might* fix the error, if this is happening during the stage where divisions are being calculated. From the traceback, I cannot tell. Does your index column contain NULLs? That might complicate things.

**Comment by Shellcat-Zero** [comment] 2018-01-17 01:48
I'm pretty new to Dask and might need some clarifications here.  This is how my dataframe was constructed (in an ipython session on the master node, built using dask-ec2):
```
import dask.dataframe as dd
from distributed import Client
from sqlalchemy import create_engine
c = Client('127.0.0.1:8786')
server = "xxx.xx.xx.xxx"
name = "myname"
pw = "mypass"
uri = 'mysql+pymysql://'+name+':'+pw+'@'+server+'/mydbname?charset=utf8'
df = dd.read_sql_table('mytable', uri, index_col='id')
df = c.persist(df)
```
I was under the impression that the index_col should just be the primary key index of the table in MySQL, is that correct?  My db schema does not allow the 'id' column to ever have null values, which I've re-confirmed and queried to check for nulls.  There are no nulls in the index_col.  

The fix that you posted earlier for /dask/dataframe/io/sql.py was implemented on all nodes in the cluster (4 nodes), but if there was an error on one of the other nodes I'm not sure how I would know about it.  These nodes are Ubuntu 16.04.3 LTS, the EC2 AMI is ami-82f4dae7, dask==0.16.1 and PyMySQL==0.8.0, if that information is pertinent.

**Comment by martindurant** [comment] 2018-01-17 14:21
OK, yes, that is exactly the right thing to do. Note that any DB-indexed column would do, not necessarily the primary key.
I wonder if `parse_dates=[]` may help.
Or perhaps change the partition size to make sure that some non-null values are found in every one?

**Comment by martindurant** [comment] 2018-01-17 14:31
Also, you might want to try [c.recreate_error_locally(df)](http://distributed.readthedocs.io/en/latest/api.html#distributed.recreate_exceptions.ReplayExceptionClient.recreate_error_locally) (after persist) and play debugger to figure out just where the faulty line is happening.

**Comment by Shellcat-Zero** [comment] 2018-01-17 21:22
@martindurant, when I say that pandas is automatically converting bad date values to 'NaT', I was implying that it is doing this during read_sql operations, not simply with pd.to_datetime().  It appears to be calling pandas.convert_objects(), but I'm not sure where I should put this modification in Dask, maybe after every pd.read_sql() call?.  See https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.convert_objects.html.

**Comment by martindurant** [comment] 2018-01-17 22:03
It is tricky, for some reason read_sql_table is behaving differently within a single call versus the several calls that dask makes. You may be right, that convert_objects would do the right thing if the columns arrived as objects - but we cannot, it seems, get the dataframe to operate on in the first place.

**Comment by Shellcat-Zero** [comment] 2018-01-17 22:30
The error is commonly triggered during the `df.head()` statement, can you elaborate on how to use c.recreate_error_locally(df)?  I haven't been able to do anything meaningful with it.

**Comment by martindurant** [comment] 2018-01-18 15:00
You would do
```
[ ] df = c.persist(df)
```
(now df contains futures, of which some have errors)
```
[ ] c.recreate_error_locally(df)
```
(now you see an error, from the first of the failed futures)
```
[ ] debug
```

**Comment by Shellcat-Zero** [comment] 2018-01-19 00:07
Thanks @martindurant, the `c.recreate_error_locally(df)` statement took around 60 minutes to finish, it was just a matter of giving it enough time.  Here is the output of the executed statement:
```
In [3]: c.recreate_error_locally(df)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-604672c73cb4> in <module>()
----> 1 c.recreate_error_locally(df)

/opt/anaconda/lib/python3.5/site-packages/distributed/recreate_exceptions.py in recreate_error_locally(self, future)
    179         func, args, kwargs = sync(self.client.loop,
    180                                   self._recreate_error_locally, future)
--> 181         func(*args, **kwargs)

/opt/anaconda/lib/python3.5/site-packages/distributed/worker.py in execute_task(task)
    651     if istask(task):
    652         func, args = task[0], task[1:]
--> 653         return func(*map(execute_task, args))
    654     elif isinstance(task, list):
    655         return list(map(execute_task, task))

/opt/anaconda/lib/python3.5/site-packages/pandas/util/_decorators.py in wrapper(*args, **kwargs)
    116                 else:
    117                     kwargs[new_arg_name] = new_arg_value
--> 118             return func(*args, **kwargs)
    119         return wrapper
    120     return _deprecate_kwarg

/opt/anaconda/lib/python3.5/site-packages/pandas/core/generic.py in astype(self, dtype, copy, errors, **kwargs)
   3975         """
   3976         if is_dict_like(dtype):
-> 3977             if self.ndim == 1:  # i.e. Series
   3978                 if len(dtype) > 1 or self.name not in dtype:
   3979                     raise KeyError('Only the Series name can be used for '

AttributeError: 'str' object has no attribute 'ndim'
```
Now entering the debugger to investigate:
```
In [4]: debug
> /opt/anaconda/lib/python3.5/site-packages/pandas/core/generic.py(3977)astype()
   3975         """
   3976         if is_dict_like(dtype):
-> 3977             if self.ndim == 1:  # i.e. Series
   3978                 if len(dtype) > 1 or self.name not in dtype:
   3979                     raise KeyError('Only the Series name can be used for '

ipdb>
```

Any input on what to look at or do next would be much appreciated.  I'm working with a table of >17M rows in MySQL, and transforming all datetime columns to DEFAULT NULL to then convert all of the "0000-00-00 00:00:00" strings to nulls (and there are A LOT of them) is a much more impractical approach.

**Comment by martindurant** [comment] 2018-01-19 16:10
Obviously I was hoping for something a bit more obvious (and quick!) than that. So int he above, `self` is the null string, but pandas is trying to treat is as a series. I wonder, might there be only a single row in this partition? (in which case, I can't imagine why it took so long to materialise). If you go up a couple of levels (`execute_task`), you will probably find that the inputs include a dataframe (i.e., successfully read from read_sql_table) and astype. If so, then everything about that dataframe is useful to know.

**Comment by Shellcat-Zero** [comment] 2018-01-19 23:30
Is this the debugging info you were wanting?  I see what looks like the dataframe and read_sql method, along with the attributes of the table it's trying to pull.  The offending columns would appear to be 'date_of_birth', 'pay_day1', 'pay_day2', and 'resubmitted', being the only columns containing datetime strings of "0000-00-00 00:00:00" in the database.
```
In [3]: c.recreate_error_locally(df)
> /opt/anaconda/lib/python3.5/site-packages/distributed/worker.py(653)execute_task()
-> if istask(task):
(Pdb) task
(<function NDFrame.astype at 0x7fc8fc0346a8>, 'read_sql-99a85b84-583d-46d6-b100-7f43f326b18e', (<class 'dict'>, [['employer_zip', dtype('O')], ['created', dtype('<M8[ns]')], ['bank_account_number_encrypted', dtype('O')], ['own_home', dty
pe('O')], ['date_of_birth', dtype('<M8[ns]')], ['referer_relation1', dtype('O')], ['referer_relation2', dtype('O')], ['referer_last_name2', dtype('O')], ['modified', dtype('<M8[ns]')], ['state', dtype('O')], ['ping_id', dtype('int64')], 
['client_ip', dtype('O')], ['client_id', dtype('int64')], ['referer_phone2', dtype('O')], ['months_at_bank', dtype('O')], ['ssn_encrypted', dtype('O')], ['address1', dtype('O')], ['pay_day1', dtype('<M8[ns]')], ['referer_phone3', dtype('O')], ['lead_response', dtype('O')], ['first_name', dtype('O')], ['user_agent', dtype('O')], ['phone_work_extension', dtype('O')], ['amount', dtype('float64')], ['referer_last_name3', dtype('O')], ['contact_time', dtype('O')], ['group_id', dtype('int64')], ['income_type', dtype('O')], ['pay_per_period', dtype('float64')], ['network_id', dtype('int64')], ['zip', dtype('O')], ['employer_state', dtype('O')], ['is_completed', dtype('int64')], ['is_live', dtype('O')], ['sms_optin', dtype('O')], ['drivers_license_number', dtype('O')], ['employer_name', dtype('O')], ['referer_relation3', dtype('O')], ['phone_work', dtype('O')], ['loan_amount', dtype('O')], ['employer_address', dtype('O')], ['address2', dtype('O')], ['direct_deposit', dtype('O')], ['r_response', dtype('O')], ['bank_account_type', dtype('O')], ['bank', dtype('O')], ['city', dtype('O')], ['supervisor_name', dtype('O')], ['phone_home', dtype('O')], ['bank_phone', dtype('O')], ['sold', dtype('int64')], ['months_at_address', dtype('O')], ['client_url', dtype('O')], ['salutation', dtype('O')], ['drivers_license_state', dtype('O')], ['is_military', dtype('O')], ['bank_routing_number', dtype('O')], ['subid', dtype('O')], ['country_code', dtype('O')], ['employer_city', dtype('O')], ['redirect_url', dtype('O')], ['referer_first_name1', dtype('O')], ['referer_first_name2', dtype('O')], ['referer_first_name3', dtype('O')], ['months_employed', dtype('O')], ['pay_frequency', dtype('O')], ['email', dtype('O')], ['resubmitted', dtype('O')], ['redirected', dtype('int64')], ['pay_day2', dtype('<M8[ns]')], ['gender', dtype('O')], ['referer_phone1', dtype('O')], ['last_name', dtype('O')], ['job_title', dtype('O')], ['supervisor_phone', dtype('O')], ['monthly_income', dtype('float64')], ['fax', dtype('O')], ['originating_url', dtype('O')], ['referer_last_name1', dtype('O')], ['supervisor_phone_ext', dtype('O')], ['param_type', dtype('O')], ['mobile', dtype('O')]]))
```

**Comment by martindurant** [comment] 2018-01-19 23:46
That should be read: "apply pandas 'astype' to the result of read_sql, with the following set of files/dtype mappings". 
This suggests that read_sql completed successfully, but produced columns with objects instead of times, and `astype()` apparently does not do the same thing as `convert_objects()`. Interestingly the set of datatypes to apply comes from the head of the query results, so presumably sometimes the times come back in the right time (perhaps there is no NULL in the first few rows?).

Can you perhaps try setting the dtypes of `df.meta` to object for the three columns? That should allow you to persist, and then apply `convert_objects()` on the three columns.

**Comment by Shellcat-Zero** [comment] 2018-01-20 00:16
The 'created' and 'modified' columns are also datetime columns, but they do not contain "0000-00-00 00:00:00" in the database.  In this output I see that 'resubmitted' is labeled as dtype('0') while the other datetime fields have been labeled as dtype('<M8[ns]'), so I would suspect that 'resubmitted' is triggering the error in this instance, if I'm not mistaken.

**Comment by Shellcat-Zero** [comment] 2018-01-20 00:20
Nevermind, I think I see what you're saying, those fields should be objects to avoid the data range error.

**Comment by Shellcat-Zero** [comment] 2018-01-22 21:19
@martindurant, is this the correct way to set the dtypes to objects?  I'm still getting the same 'datetime out of range' error.

```
...
df = dd.read_sql_table('pbleads',uri,index_col='id')
df.resubmitted = df.resubmitted.astype('str')
df.date_of_birth = df.date_of_birth.astype('str')
df.pay_day1 = df.pay_day1.astype('str')
df.pay_day2 = df.pay_day2.astype('str')
df = c.persist(df)
```
Then doing `df.head()` gives:
```
ValueError: Month out of range in datetime string "0000-00-00 00:00:00"
```

**Comment by martindurant** [comment] 2018-01-22 21:29
Unfortunately no, that is the same error: the first `df` you get out of `read_sql_table` already contains the two steps, reading the sql data, and then setting the dtypes as was found in the first certain number of rows - this fails. Everything you do after that with `astype()` never has a chance to happen.
You might try
```
df = dd.read_sql_table('mytable',uri,index_col='id')
df._meta = df._meta.astype({'resubmitted': str, 'date_of_birth': str, 'pay_day1': str, 'pay_day2': str})
```
or perhaps
```
df = dd.read_sql_table('mytable',uri,index_col='id')
df = df.map_partitions(lambda x: x.astype(
    {'resubmitted': str, 'date_of_birth': str, 'pay_day1': str, 'pay_day2': str}))
```

**Comment by Shellcat-Zero** [comment] 2018-01-22 21:51
I have now tried both of these and I am getting the same error.  Do you know where I might modify the task that is getting passed to execute_task so that I can set something like an error='coerce' option on the columns?

**Comment by martindurant** [comment] 2018-01-22 21:54
You can *in theory* edit the dask graph in `df.dask` directly, but it is not simple. It contains keys, and for each, a function and set of arguments that are to be fed to it, where those arguments can be other keys.

**Comment by martindurant** [comment] 2018-01-22 22:44
You have spent enough time on this by now...
At this point, you might want to directly change the code in `dask.dataframe.io.sql.read_sql_table`. You could put a `pdb.set_trace()`after the `head = ` line and play with the `head` variable, or explicitly put an `head = head.astype(...)` here.

**Comment by Shellcat-Zero** [comment] 2018-01-23 01:11
I'm going ahead and modifying the table to accept null values and converting all "0000-00-00 00:00:00" strings to nulls in the database so that I can move forward.  I'll keep playing with the `head` variable though to see what I can accomplish with better data type conversion and error handling.  

Is there and IRC channel for dask developers or someplace similar to chat?  I anticipate making heavy use of dask and I would like to start contributing to the code base if possible.

**Comment by martindurant** [comment] 2018-01-23 13:49
Yes: https://gitter.im/dask/dask for users, https://gitter.im/dask/dev for developers (the latter a fairly limited group).

**Comment by pjarnhus** [comment] 2018-01-31 10:57
@martindurant My apologies for a VERY long delay in getting back to you. I have not spent enough time in the office to test the fix on the real data set. I have now and it is working like a charm! Thanks for helping out and keep up the good work with dask.

Should I close the issue or are we holding off with that until the issue from @Shellcat-Zero has been resolved as well?

**Comment by Shellcat-Zero** [comment] 2018-01-31 17:54
@martindurant does PR #3100 fix both the metadata mismatch problem and the ValueError that I reported?  I've found that I cannot use dask without the fix you posted for the metadata mismatch issue, thanks for providing that.

**Comment by martindurant** [comment] 2018-01-31 17:57
@Shellcat-Zero , I don't know for certain whether `astype` will fix the parsing of your zero times. If not, I think it's a bug really with pd.read_sql_table or astype rather than dask.

**Comment by Shellcat-Zero** [comment] 2018-01-31 19:50
I'll keep digging into the issue then.  What I suspect is that now that the metadata mismatch problem is resolved, more similar `ValueError` problems will be occurring.  

Is there a way for me to inspect all of the individual partitions or dataframes that dask creates when it distributes the data set onto the nodes?  I think I would like to try replicating more of these individual dataframes in Pandas to see how it handles the data types, then I should be able to better raise the underlying issue with Pandas based on its behavior.

**Comment by martindurant** [comment] 2018-01-31 19:57
Yes, you can call `df.get_partition(i)` for each partition or `df.to_delayed()` to get all the components.

**Comment by Shellcat-Zero** [comment] 2018-03-05 21:48
@martindurant have your sql.py modifications been pushed out to some version of Dask?  If so, what Dask version should have that fix in it?

**Comment by martindurant** [comment] 2018-03-05 22:15
It was merged on Jan 30, 0.17.0 was released on Feb 9, and 0.17.1 on Feb 22.

**Comment by Shellcat-Zero** [comment] 2018-03-05 22:20
Thanks.

**Comment by mrocklin** [comment] 2018-10-24 14:48
@martindurant is this resolved?

**Closed** 2018-10-24 14:58 UTC
