### ISSUE TITLE
Import error for distributed.dashboard.components.scheduler if using bokeh<3 

### ISSUE THREAD

**Issue by jemissik** [dask/dask#10365] opened 2023-06-20 17:20 UTC
**Describe the issue**:

If dask 2023.6.0 is installed with bokeh<3, this causes an import error for distributed.dashboard.components.scheduler. It seems that dask only specifies bokeh >= 2.4.2 in the dependencies, but the distributed dashboard uses some newer features of bokeh. 

**Minimal Complete Verifiable Example**:

Create an environment with dask=2023.6.0 and bokeh<3: 

```shell
mamba create -n dask 'dask=2023.6.0' 'bokeh<3' 
``` 

```python
import distributed.dashboard.components.scheduler
```

Traceback: 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jmissik/mambaforge/envs/dask-test/lib/python3.11/site-packages/distributed/dashboard/components/scheduler.py", line 50, in <module>
    from bokeh.palettes import Viridis11, YlGnBu9, interp_palette
ImportError: cannot import name 'interp_palette' from 'bokeh.palettes' (/Users/jmissik/mambaforge/envs/dask-test/lib/python3.11/site-packages/bokeh/palettes.py)
``` 

**Environment**:

- Dask version: 2023.6.0
- Python version: 3.11.3
- Operating System: MacOS Ventura 13.4
- Install method (conda, pip, source): conda (mamba solver)

Full environment details: 
<details><summary>Details</summary>
<p>

```
# Name                    Version                   Build  Channel
abseil-cpp                20211102.0           hc377ac9_0  
arrow-cpp                 11.0.0               hc7aafb3_1  
aws-c-common              0.6.8                h80987f9_1  
aws-c-event-stream        0.1.6                h313beb8_6  
aws-checksums             0.1.11               h80987f9_2  
aws-sdk-cpp               1.8.185              ha71a6ea_1  
blas                      1.0                    openblas  
bokeh                     2.4.3           py311hca03da5_0  
boost-cpp                 1.73.0              h1a28f6b_12  
bottleneck                1.3.5           py311ha0d4635_0  
brotli                    1.0.9                h1a28f6b_7  
brotli-bin                1.0.9                h1a28f6b_7  
brotlipy                  0.7.0           py311h80987f9_1002  
bzip2                     1.0.8                h620ffc9_4  
c-ares                    1.19.0               h80987f9_0  
ca-certificates           2023.05.30           hca03da5_0  
certifi                   2023.5.7        py311hca03da5_0  
cffi                      1.15.1          py311h80987f9_3  
click                     8.0.4           py311hca03da5_0  
cloudpickle               2.2.1           py311hca03da5_0  
cryptography              39.0.1          py311h834c97f_2  
cytoolz                   0.12.0          py311h80987f9_0  
dask                      2023.6.0           pyhd8ed1ab_0    conda-forge
dask-core                 2023.6.0        py311hca03da5_0  
distributed               2023.6.0        py311hca03da5_0  
freetype                  2.12.1               h1192e45_0  
fsspec                    2023.4.0        py311hca03da5_0  
gflags                    2.2.2                hc377ac9_0  
giflib                    5.2.1                h80987f9_3  
glog                      0.5.0                hc377ac9_0  
grpc-cpp                  1.48.2               hc60591f_1  
heapdict                  1.0.1              pyhd3eb1b0_0  
icu                       68.1                 hc377ac9_0  
idna                      3.4             py311hca03da5_0  
importlib-metadata        6.0.0           py311hca03da5_0  
jinja2                    3.1.2           py311hca03da5_0  
jpeg                      9e                   h80987f9_1  
krb5                      1.20.1               hf3e1bf2_1  
lcms2                     2.12                 hba8e193_0  
lerc                      3.0                  hc377ac9_0  
libboost                  1.73.0              h49e8a49_12  
libbrotlicommon           1.0.9                h1a28f6b_7  
libbrotlidec              1.0.9                h1a28f6b_7  
libbrotlienc              1.0.9                h1a28f6b_7  
libcurl                   8.1.1                h3e2b118_1  
libcxx                    14.0.6               h848a8c0_0  
libdeflate                1.17                 h80987f9_0  
libedit                   3.1.20221030         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libevent                  2.1.12               h02f6b3c_1  
libffi                    3.4.4                hca03da5_0  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libiconv                  1.16                 h1a28f6b_2  
libnghttp2                1.52.0               h62f6fdd_1  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libprotobuf               3.20.3               h514c7bf_0  
libssh2                   1.10.0               h02f6b3c_2  
libthrift                 0.15.0               h73c2103_1  
libtiff                   4.5.0                h313beb8_2  
libwebp                   1.2.4                ha3663a8_1  
libwebp-base              1.2.4                h80987f9_1  
llvm-openmp               14.0.6               hc6e5704_0  
locket                    1.0.0           py311hca03da5_0  
lz4                       4.3.2           py311h80987f9_0  
lz4-c                     1.9.4                h313beb8_0  
markupsafe                2.1.1           py311h80987f9_0  
msgpack-python            1.0.3           py311h48ca7d4_0  
ncurses                   6.4                  h313beb8_0  
numexpr                   2.8.4           py311h6dc990b_1  
numpy                     1.24.3          py311hb57d4eb_0  
numpy-base                1.24.3          py311h1d85a46_0  
openssl                   3.0.8                h1a28f6b_0  
orc                       1.7.4                hdca1487_1  
packaging                 23.0            py311hca03da5_0  
pandas                    1.5.3           py311h6956b77_0  
partd                     1.2.0              pyhd3eb1b0_1  
pillow                    9.4.0           py311h313beb8_0  
pip                       23.1.2          py311hca03da5_0  
psutil                    5.9.0           py311h80987f9_0  
pyarrow                   11.0.0          py311h7575258_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.0.0          py311hca03da5_0  
pysocks                   1.7.1           py311hca03da5_0  
python                    3.11.3               hb885b13_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python-lmdb               1.4.1           py311h313beb8_0  
pytz                      2022.7          py311hca03da5_0  
pyyaml                    6.0             py311h80987f9_1  
re2                       2022.04.01           hc377ac9_0  
readline                  8.2                  h1a28f6b_0  
setuptools                67.8.0          py311hca03da5_0  
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.1.9                hc377ac9_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
sqlite                    3.41.2               h80987f9_0  
tblib                     1.7.0              pyhd3eb1b0_0  
tk                        8.6.12               hb8d0fd4_0  
toolz                     0.12.0          py311hca03da5_0  
tornado                   6.2             py311h80987f9_0  
typing_extensions         4.6.3           py311hca03da5_0  
tzdata                    2023c                h04d1e81_0  
urllib3                   1.26.16         py311hca03da5_0  
utf8proc                  2.6.1                h1a28f6b_0  
wheel                     0.38.4          py311hca03da5_0  
xz                        5.4.2                h80987f9_0  
yaml                      0.2.5                h1a28f6b_0  
zict                      2.2.0           py311hca03da5_0  
zipp                      3.11.0          py311hca03da5_0  
zlib                      1.2.13               h5a0b063_0  
zstd                      1.5.5                hd90d995_0  
```

</p>
</details>

**Comment by jrbourbeau** [comment] 2023-06-20 19:57
Thanks for reporting @jemissik. I think this may be a duplicate of https://github.com/dask/distributed/issues/7908, which was fixed by https://github.com/dask/distributed/pull/7910 and should be included in the release this Friday. I'm going to close this issue for now as a duplicate, but let me know if that's not the case and we can re-open

**Closed by jrbourbeau** 2023-06-20 19:57 UTC
Labels: needs triage
