### ISSUE TITLE
Dask and Skimage/ Pickling scipy fft objects not possible?

### ISSUE THREAD

**Issue by MaximilianHoffmann** [dask/dask#6994] opened 2020-12-18 20:26 UTC
I wanted to map the  [phase correlation](https://github.com/scikit-image/scikit-image/blob/73c210fe5f5452acb45e1bfd24e1cad832f76535/skimage/registration/_phase_cross_correlation.py#L11) sci-kit image onto a dask array, but the module prefers to use the [scipy fft module](https://github.com/scikit-image/scikit-image/blob/master/skimage/_shared/fft.py). 
This leads to a pickling error 
```
TypeError: can't pickle _FFTModule objects
``` 

, because, as I believe, the API doesn't switch to dask. 

I am not sure, whether this is something that is within the scope of the dask project.

**Comment by jrbourbeau** [comment] 2020-12-21 21:07
Thanks for raising an issue @MaximilianHoffmann! Are you able to post a [minimal, reproducible example](https://blog.dask.org/2018/02/28/minimal-bug-reports)?

FWIW functions and their arguments need to be serializable with cloudpickle for Dask to be able to use them with the distributed or multiprocessing scheduler

**Comment by jrbourbeau** [comment] 2021-03-12 15:22
Closing due to lack of a reproducible example. @MaximilianHoffmann feel free to re-open if you're able to provide a code snippet we can run to reproduce the `TypeError`

**Closed by jrbourbeau** 2021-03-12 15:22 UTC
Labels: needs info
