### ISSUE TITLE
confusing ValueError on dd.get_dummies or dask-ml OneHotEncoder

### ISSUE THREAD

**Issue by jerrytim** [dask/dask#5960] opened 2020-02-28 17:15 UTC
I was trying to do one hot encoding on huge dataframes with dask but failed with both dd.get_dummies and dask-ml OneHotEncoder.

The original dataset was about 8 million rows, I tried a smaller dataset (~500k rows) and did it in 2 ways, one was working fine (though I assume it's not efficient), the other failed.

```python
"""
This works
"""
ddf = dd.read_parquet('file.gz.parquet', engine='pyarrow').repartition(npartitions=12).persist()

# only operate on 1 column
ddf.domain.dtype
# CategoricalDtype(categories=['__UNKNOWN_CATEGORIES__'], ordered=False)

ddf_domain = ddf[['domain']].categorize() # 307 categories
ddf_domain.domain.dtype
# CategoricalDtype(categories=['a.com', 'b.com', .... 'xxa.com'], ordered=False)
ddf_dummies = dd.get_dummies(ddf_domain)
ddf_dummies = ddf_dummies.persist() # ~500k rows, 307 columns

"""
This failed
"""
ddf_dtypes = # read dtypes info beforehand from other source into a dict with {col: dtype, …} format
ddf_dtypes['domain'] # contained categories is exactly the same as ddf_domain.domain.dtype, only order is different
# CategoricalDtype(categories=['b.com', 'xxa.com', .... 'a.com'], ordered=False)

ddf_v2 = ddf.astype(ddf_dtypes).persist()
ddf_v2_dummies = dd.get_dummies(ddf_v2[['domain']])
ddf_v2_dummies = ddf_v2_dummies.persist()
```
It returned the following error.
```python
ValueError: The columns in the computed data do not match the columns in the provided metadata
  Extra:   []
  Missing: []
```
By looking at the [source code](https://github.com/dask/dask/blob/4ae913b13df7c5018e24eea6ee76392a6ef59f3e/dask/dataframe/reshape.py#L153) of `dd.get_dummies`, it maps the `pd.get_dummies` func to each partition.
The only difference I could found is from this line:
```python
package_name = data._meta.__class__.__module__.split(".")[0]
dummies = sys.modules[package_name].get_dummies
meta = dummies(
        data._meta,
```
With the above 2 approaches, the `meta` objects returned are both empty pd dataframe with the same columns, but the column order is different.
```python
# meta in the working approach
print(meta)
"""
Empty DataFrame
Columns: [domain_a.com, domain_b.com, ...domain_xxa.com]
Index: []
"""
# meta in the failed approach
print(meta_v2)
"""
Empty DataFrame
Columns: [domain_b.com, domain_xxa.com, ...domain_a.com]
Index: []
"""
```

The error message is confusing, I assume the second approach should be more efficient since it converts dtypes and tells all the known categories, therefore it avoids doing `categorize()` full data scan.
I went through all the related SO questions and answers but no very helpful.
Any ideas? @TomAugspurger @mrocklin 
Thanks in advanced.

**Comment by TomAugspurger** [comment] 2020-02-28 17:57
> ValueError: The columns in the computed data do not match the columns in the provided metadata

That error message has been improved in dask master I think: https://github.com/dask/dask/pull/5927

>  I assume the second approach should be more efficient since it converts dtypes and tells all the known categories, therefore it avoids doing categorize() full data scan.

I think that's correct. I'm not 100% sure why you're seeing the exception though... I would think that the astype to the categorical type would handle things. Can you provide a minimal, reproducible example http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports?

**Comment by ncclementi** [comment] 2021-08-20 14:39
I'm going to close this issue since it's been a while after Tom requested a minimal reproducible example and there was no answer. @jerrytim If you still have this problem, feel free to re-open the issue with a minimal reproducible example so we can help you.

**Closed by ncclementi** 2021-08-20 14:39 UTC
Labels: needs info
