### ISSUE TITLE
Support column assignment

### ISSUE THREAD

**Issue by mrocklin** [dask/dask#1321] opened 2016-06-23 04:34 UTC
This is feasible.  We would create a new dask graph and metadata and then assign those to the existing dataframe.  This ends up coming up often enough is user and stackoverflow questions that I'm tempted to allow mutation of dask.dataframe objects.

**Comment by nirizr** [comment] 2016-06-23 09:47
If the issue is not functionality but usability, i wonder if we can keep dask.dataframe's immutability in favor of clearer documentation or explicitly directing the user to use `dask.dataframe.assign` (instead of the generic python error).

**Comment by mrocklin** [comment] 2016-06-23 14:17
Can you construct motivating cases where column assignment would cause problems?

The graphs themselves are still immutable.  Other lazily evaluated computational projects like Theano have managed to support symbolic-in-place expressions while still producing pure computational graphs.

**Comment by nirizr** [comment] 2016-06-23 14:59
I don't think it would cause any real issues, i was just raising this as a possibility.
I was under the impression you would want to keep dask.dataframe immutable.

I don't have a strong opinion on this.

**Comment by nirizr** [comment] 2016-06-27 19:15
I think this is fixed in merged PR #1322

**Closed** 2016-06-27 19:17 UTC
