### ISSUE TITLE
Groupby rolling aggregations

### ISSUE THREAD

**Issue by beckernick** [dask/dask#7096] opened 2021-01-21 16:25 UTC
I'd like to be able to use rolling aggregations on groupby Series and DataFrame objects. Today, I can do this in pandas but not Dask. This may be dependent on MultiIndex support, which is covered by https://github.com/dask/dask/issues/1493

```python
import pandas as pd
import dask.dataframe as dd
​
pdf = pd.DataFrame({
    "a": [0,1,0,1,1,0],
    "b": range(6),
})
ddf = dd.from_pandas(pdf, 2)
print(pdf.groupby("a").rolling(2).sum())
ddf.groupby("a").rolling(2).sum()
       a    b
a            
0 0  NaN  NaN
  2  0.0  2.0
  5  0.0  7.0
1 1  NaN  NaN
  3  2.0  4.0
  4  2.0  7.0
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/raid/nicholasb/miniconda3/envs/rapids-gpubdb-20210120/lib/python3.7/site-packages/dask/dataframe/groupby.py in __getattr__(self, key)
   1834         try:
-> 1835             return self[key]
   1836         except KeyError as e:

/raid/nicholasb/miniconda3/envs/rapids-gpubdb-20210120/lib/python3.7/site-packages/dask/dataframe/groupby.py in __getitem__(self, key)
   1820         # error is raised from pandas
-> 1821         g._meta = g._meta[key]
   1822         return g

/raid/nicholasb/miniconda3/envs/rapids-gpubdb-20210120/lib/python3.7/site-packages/pandas/core/groupby/generic.py in __getitem__(self, key)
   1609             )
-> 1610         return super().__getitem__(key)
   1611 

/raid/nicholasb/miniconda3/envs/rapids-gpubdb-20210120/lib/python3.7/site-packages/pandas/core/base.py in __getitem__(self, key)
    227             if key not in self.obj:
--> 228                 raise KeyError(f"Column not found: {key}")
    229             return self._gotitem(key, ndim=1)

KeyError: 'Column not found: rolling'

The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)
<ipython-input-31-b4ae998a7b23> in <module>
      8 ddf = dd.from_pandas(pdf, 2)
      9 print(pdf.groupby("a").rolling(2).sum())
---> 10 ddf.groupby("a").rolling(2).sum()

/raid/nicholasb/miniconda3/envs/rapids-gpubdb-20210120/lib/python3.7/site-packages/dask/dataframe/groupby.py in __getattr__(self, key)
   1835             return self[key]
   1836         except KeyError as e:
-> 1837             raise AttributeError(e) from e
   1838 
   1839     @derived_from(pd.core.groupby.DataFrameGroupBy)

AttributeError: 'Column not found: rolling'
```

```
conda list | grep "pandas\|dask"
dask                      2021.1.0           pyhd8ed1ab_0    conda-forge
pandas                    1.1.5            py37hdc94413_0    conda-forge
```

**Comment by jrbourbeau** [comment] 2021-09-23 20:43
Thanks for raising an issue @beckernick -- closing as a duplicate of https://github.com/dask/dask/issues/5974

**Closed by jrbourbeau** 2021-09-23 20:43 UTC
Labels: dataframe

**Comment by beckernick** [comment] 2021-09-24 18:53
Thanks for deduping here @jrbourbeau !
