### ISSUE TITLE
PicklingError: Can't pickle <functools._lru_cache_wrapper

### ISSUE THREAD

**Issue by anujsainimca** [dask/dask#7987] opened 2021-08-03 19:17 UTC
I am trying to run Dask on Flair which is emeddings based model. It works fine without distrubuted cluster but with with cluster it gives an error or picklingerror. 

Code:
'''
from dask.distributed import Client, progress
import dask
import time
import random
import pandas as pd
import numpy as np
import time
import dask.bag as db
import dask.dataframe as ddf
from sklearn.datasets import fetch_20newsgroups
data = fetch_20newsgroups(subset="train")
from flair.data import Sentence
from flair.models import SequenceTagger
#Load NER Model
#tagger = SequenceTagger.load('ner')
def getFlairEntities(text):
    #passing text to sentence
    sentence = Sentence(text)
    # Run NER on sentence to identify Entities
    tagger.predict(sentence)
    # print the entities with below command
    entites=[]
    for entity in sentence.get_spans('ner'):
        temp={}
        temp['start_pos']=entity.start_pos
        temp['end_pos']=entity.end_pos
        temp['entity']=    entity.text
        temp['entity_type']=    entity.tag
        temp['score']=    round(entity.score, 4)
        entites.append(temp)
    return entites
def ner_flair(df):
    '''
    Take in a Dataframe, and process it
    '''
    df["entities"] = df.text.map(getFlairEntities)
    return df
if __name__ == "__main__":
    client = Client(processes=True)
    df = pd.DataFrame()
    df = df.assign(text=data["data"]).assign(target=data["target"])
    dask_dataframe = ddf.from_pandas(df.head(20), npartitions=20)
    t0 = time.time()
    result = dask_dataframe.map_partitions(ner_flair)
    dask_entities = result.compute()
    t1 = time.time()
    print("Time to process with Dask {}".format(t1-t0))
'''
PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x000001868E9D5EE0>: it's not the same object as flair.embeddings.token.WordEmbeddings.get_cached_vec

**Comment by jrbourbeau** [comment] 2021-08-03 19:30
Thanks for raising an issue @anujsainimca! Are you able to provide a minimal example (see https://blog.dask.org/2018/02/28/minimal-bug-reports)? 

Note that when using multiple processes (either with the single-machine "processes" scheduler or the distributed scheduler) tasks, and their results, will need to be serialized with pickle or cloudpickle so they can be sent between Python processes. IT may be that something in your workflow isn't pickle-able (I'm not familiar with Flair)

**Comment by anujsainimca** [comment] 2021-08-03 19:44
Thanks @jrbourbeau, my code example is there in my question. So dask pickle all objects and flair is generating something which isnt pickle-able. Though I am wondering, why there would be something which cant be pickled. This is my error

PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x000001868E9D5EE0>: it's not the same object as flair.embeddings.token.WordEmbeddings.get_cached_vec

**Comment by jrbourbeau** [comment] 2021-08-03 20:21
> Though I am wondering, why there would be something which cant be pickled

My guess is there's something in one of the non-Dask libraries you're using which isn't pickleable 

> This is my error

Can you post your full traceback?

**Comment by anujsainimca** [comment] 2021-08-03 20:31
PicklingError                             Traceback (most recent call last)
<ipython-input-3-7c93947f16ff> in <module>
     51     t0 = time.time()
     52     result = dask_dataframe.map_partitions(ner_flair)
---> 53     dask_entities = result.compute()
     54     t1 = time.time()
     55     print("Time to process with Dask {}".format(t1-t0))

~\Anaconda3\lib\site-packages\dask\base.py in compute(self, **kwargs)
    282         dask.base.compute
    283         """
--> 284         (result,) = compute(self, traverse=False, **kwargs)
    285         return result
    286 

~\Anaconda3\lib\site-packages\dask\base.py in compute(*args, **kwargs)
    564         postcomputes.append(x.__dask_postcompute__())
    565 
--> 566     results = schedule(dsk, keys, **kwargs)
    567     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    568 

~\Anaconda3\lib\site-packages\distributed\client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2644         Client.compute : Compute asynchronous collections
   2645         """
-> 2646         futures = self._graph_to_futures(
   2647             dsk,
   2648             keys=set(flatten([keys])),

~\Anaconda3\lib\site-packages\distributed\client.py in _graph_to_futures(self, dsk, keys, workers, allow_other_workers, priority, user_priority, resources, retries, fifo_timeout, actors)
   2552                 dsk = HighLevelGraph.from_collections(id(dsk), dsk, dependencies=())
   2553 
-> 2554             dsk = dsk.__dask_distributed_pack__(self, keyset)
   2555 
   2556             annotations = {}

~\Anaconda3\lib\site-packages\dask\highlevelgraph.py in __dask_distributed_pack__(self, client, client_keys)
    953                     "__module__": layer.__module__,
    954                     "__name__": type(layer).__name__,
--> 955                     "state": layer.__dask_distributed_pack__(
    956                         self.get_all_external_keys(),
    957                         self.key_dependencies,

~\Anaconda3\lib\site-packages\dask\highlevelgraph.py in __dask_distributed_pack__(self, all_hlg_keys, known_key_dependencies, client, client_keys)
    390             for k, v in dsk.items()
    391         }
--> 392         dsk = toolz.valmap(dumps_task, dsk)
    393         return {"dsk": dsk, "dependencies": dependencies}
    394 

~\Anaconda3\lib\site-packages\cytoolz\dicttoolz.pyx in cytoolz.dicttoolz.valmap()

~\Anaconda3\lib\site-packages\cytoolz\dicttoolz.pyx in cytoolz.dicttoolz.valmap()

~\Anaconda3\lib\site-packages\distributed\worker.py in dumps_task(task)
   3543             return d
   3544         elif not any(map(_maybe_complex, task[1:])):
-> 3545             return {"function": dumps_function(task[0]), "args": warn_dumps(task[1:])}
   3546     return to_serialize(task)
   3547 

~\Anaconda3\lib\site-packages\distributed\worker.py in dumps_function(func)
   3507             result = cache_dumps[func]
   3508     except KeyError:
-> 3509         result = pickle.dumps(func, protocol=4)
   3510         if len(result) < 100000:
   3511             with _cache_lock:

~\Anaconda3\lib\site-packages\distributed\protocol\pickle.py in dumps(x, buffer_callback, protocol)
     58         try:
     59             buffers.clear()
---> 60             result = cloudpickle.dumps(x, **dump_kwargs)
     61         except Exception as e:
     62             logger.info("Failed to serialize %s. Exception: %s", x, e)

~\Anaconda3\lib\site-packages\cloudpickle\cloudpickle_fast.py in dumps(obj, protocol, buffer_callback)
     71                 file, protocol=protocol, buffer_callback=buffer_callback
     72             )
---> 73             cp.dump(obj)
     74             return file.getvalue()
     75 

~\Anaconda3\lib\site-packages\cloudpickle\cloudpickle_fast.py in dump(self, obj)
    561     def dump(self, obj):
    562         try:
--> 563             return Pickler.dump(self, obj)
    564         except RuntimeError as e:
    565             if "recursion" in e.args[0]:

PicklingError: Can't pickle <functools._lru_cache_wrapper object at 0x00000223989A6430>: it's not the same object as flair.embeddings.token.WordEmbeddings.get_cached_vec

**Comment by jrbourbeau** [comment] 2021-08-03 20:38
Yeah, indeed it looks like Dask is attempting to pickle a task graph so it can be sent from from the `Client` to the `Scheduler`, but encounters something that isn't pickleable. As a next step, I'd recommend trying to reproduce the `PicklingError` without Dask and opening an issue in the relevant project's issue tracker (probably the Flair issue tracker).

**Comment by jrbourbeau** [comment] 2021-08-04 16:26
Closing as I don't think there's anything to do here on the Dask side

**Closed by jrbourbeau** 2021-08-04 16:26 UTC
