### ISSUE TITLE
Killed error while saving Dask DataFrame using to_csv method

### ISSUE THREAD

**Issue by Rajat700** [dask/dask#7596] opened 2021-04-23 11:36 UTC
I am using Dask library to read csv file, do some imputation, groupby and then finally saving the Dask DataFrame using the to_csv method on remote Red-hat OS but when I try to save the Dataframe it successfully saves 3 partitions out of 12 but after that the program gets killed.

Now when I run the same code on the same data in my MAC it runs properly everytime without throwing any error. The Dask versions are same on both the machines.  I am not able to figure out why the same code gets killed on remote RedHat machine with the message 'Killed'.

The RAM is same on both the machines which is 32GB.

- Dask version: 2021.01.1
- Python version: 3.7.6
- Operating System: RedHat 4.8.5-44
- Install method (conda, pip, source): pip

**Comment by jrbourbeau** [comment] 2021-04-23 19:37
Thanks for raising an issue @Rajat700. Could you provide the full traceback you're getting? Do you workers all have access to the same filesystem that's  available to your Dask `Client`?

**Comment by Rajat700** [comment] 2021-04-24 05:08
Thanks for the response. Please find my comments below:

1. I am not getting any traceback as such. I just get the message "Killed" while I try to save the dask dataframe. My Dask DataFrame has 12 partitions and it saves 3 partitions and then I get the message "killed" without any traceback.

2. I am not using Dask distributed for this. I am only using the Dask.dataframe module.

3. When you say filesystem you mean the csv files or something else. If you mean csv file then yes I am using the same csv files and same code on my remote as well as Mac machine. Just to be more clear I am running the same code on same data separately on both remote red hat linux machine and my local Mac machine. The code runs perfectly on my local Mac machine but gets killed on remote red hat machine.

Thanks

**Comment by jsignell** [comment] 2021-05-03 19:52
It's going to be really hard to figure this out without more information. How are you running the code? Are there maybe some logs that are not readily apparent that could hold more information (sometimes this is the case when running code in jupyter)?

The best way to figure this out will be if you can provide a minimal reproducible example that is self-contained and produces the same issue.

**Comment by ncclementi** [comment] 2021-08-05 16:06
@Rajat700 Are you still having this problem with the newer versions of Dask (2021.07.2)? 

I'm going to close this issue due to lack of information, but if you are still having the problem feel free to re-open with some more information so we can help you. Either logs or a minimal reproducible example (See https://blog.dask.org/2018/02/28/minimal-bug-reports for more information).

**Closed by ncclementi** 2021-08-05 16:06 UTC
Labels: dataframe, io, needs info
