### ISSUE TITLE
Non-deterministic dataframe shape on grouped interpolation

### ISSUE THREAD

**Issue by gsimbr** [dask/dask#9492] opened 2022-09-14 15:29 UTC
I'm currently trying to apply groupwise interpolation of missing values and our previous pandas implementation does not scale up well to the large number of groups we are working on.

Trying to refactor the code to dask, I've realized that with a possible implementation that I'm currently investigating, that the shape of the dataframe (i.e. the columns) returned by a certain groupby-operation change non-deterministically with every `compute()`.

I am aware that the implementation might not be perfect, still the non-deterministic results on invoking `compute()` seems spurious to me.

**What happened**:

The shape of the output of the groupby operation changes non-deterministically on invoking `compute` multiple times (see code example below)
```
Groupby column is available:
   group  level_1       date    a
0      2        0 2021-01-01  4.0
1      2        1 2021-02-01  5.0
2      2        2 2021-03-01  5.5
3      2        3 2021-04-01  6.0
4      2        4 2021-05-01  7.0
5      2        5 2021-06-01  7.0
0      1        0 2020-01-01  1.0
1      1        1 2020-02-01  2.0
2      1        2 2020-03-01  3.0
3      1        3 2020-04-01  4.0
4      1        4 2020-05-01  5.0
5      1        5 2020-06-01  6.0
6      1        6 2020-07-01  7.0
Groupby column is missing:
   index       date    a
0      0 2021-01-01  4.0
1      1 2021-02-01  5.0
2      2 2021-03-01  5.5
3      3 2021-04-01  6.0
4      4 2021-05-01  7.0
5      5 2021-06-01  7.0
0      0 2020-01-01  1.0
1      1 2020-02-01  2.0
2      2 2020-03-01  3.0
3      3 2020-04-01  4.0
4      4 2020-05-01  5.0
5      5 2020-06-01  6.0
6      6 2020-07-01  7.0
```

**What you expected to happen**:  To be able to reproduce a stable output that is similar to what I get from my pandas implementation:

```
Expected Pandas result:
    group       date    a
0       1 2020-01-01  1.0
1       1 2020-02-01  2.0
2       1 2020-03-01  3.0
3       1 2020-04-01  4.0
4       1 2020-05-01  5.0
5       1 2020-06-01  6.0
6       1 2020-07-01  7.0
7       2 2021-01-01  4.0
8       2 2021-02-01  5.0
9       2 2021-03-01  5.5
10      2 2021-04-01  6.0
11      2 2021-05-01  7.0
12      2 2021-06-01  7.0
```

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as dd
import pandas as pd


def interpolate_index_series(
        df: pd.DataFrame, time_column: str, column: str) -> pd.DataFrame:
    # if I return temp (as in pandas example), I get a failure that a Series
    # object does not have a columns attribute, hence return results "packaged"
    # in a dataframe
    temp = df.sort_values(time_column).set_index(
        time_column)[column].interpolate(how="time")
    ret_df = pd.DataFrame({time_column: temp.index, column: temp.values})
    return ret_df


def generate_dummy_data() -> (pd.DataFrame, dd.DataFrame):
    df1 = pd.DataFrame(
        {
            "date": pd.date_range("2020-01-01", "2020-07-01", freq="MS"),
            "a": [1, 2, None, None, 5, None, 7]})
    df1["group"] = 1
    df2 = pd.DataFrame(
        {
            "date": pd.date_range("2021-01-01", "2021-06-01", freq="MS"),
            "a": [4, 5, None, 6, 7, None]})
    df2["group"] = 2
    df_pd = pd.concat([df1, df2])
    df = dd.from_pandas(df_pd, npartitions=3)
    return df_pd, df


def wait_for_expected_result(grouped_df, result_success=True):
    i = 0
    while True:
        res = grouped_df.compute()
        # check whether the groupby-column "group" is in the columns which
        # were computed
        condition = (
            "group" in res.columns
            if result_success else "group" not in res.columns)
        if condition:
            break
        if i > 100:
            raise ValueError(
                f"Could not reproduce result after {i} iterations")
        i += 1
    if result_success:
        print(f"Groupby column is available:\n{res}")
    else:
        print(f"Groupby column is missing:\n{res}")
    print(f"Number of iterations: {i}")


def main():
    df_pd, df = generate_dummy_data()
    res_pd = df_pd.groupby(["group"]).apply(
        lambda x: x.sort_values("date").set_index("date")["a"].interpolate(
            how="time")).reset_index()
    print(f"Expected Pandas result:\n{res_pd}")
    schema_df = pd.DataFrame(
        {
            "date": pd.date_range("2020-01-01", "2020-02-01", freq="MS"),
            "a": [1.1, 2]})
    groupby_res = df.groupby("group").apply(
        lambda x: interpolate_index_series(x, "date", "a"),
        meta=schema_df).reset_index()
    wait_for_expected_result(groupby_res, result_success=True)
    wait_for_expected_result(groupby_res, result_success=False)


if __name__ == '__main__':
    main()
```
**Environment**:

- Dask version: 2022.9.0
- Python version: 3.10
- Operating System: Debian GNU/Linux 11 (bullseye) [reproduced with python:3.10 docker image]
- Install method (conda, pip, source): pip

**Comment by ncclementi** [comment] 2022-09-15 20:46
Hi there, thank you for opening this issue. 

@ian-r-rose and I took a look at this and you might be running into a pandas problem that you can read about here. https://pandas.pydata.org/docs/dev/whatsnew/v1.5.0.html?highlight=group_keys#using-group-keys-with-transformers-in-groupby-apply

We are guessing that maybe your index sometimes changes and sometimes it doesn't,  depending on the interpolation, and you might be hitting the issue with group_keys. 

Maybe trying setting `group_keys=False` in your groupby operations might fix it.

**Comment by jrbourbeau** [comment] 2022-09-16 16:27
Just noting that:

- I can consistently reproduce the issue using @gsimbr's example as is with `pandas=1.4.4`
- The issue goes away when I specify `group_keys=False` with `pandas=1.4.4` (as @ncclementi suggested)
- Using the latest nightly version of `pandas`, I'm not able to reproduce the issue with the original example

**Comment by ncclementi** [comment] 2022-09-16 17:19
@gsimbr given the comment above, would you be ok closing this issue?

**Comment by gsimbr** [comment] 2022-09-17 06:25
Hi @ncclementi @jrbourbeau & @ian-r-rose , first of all thanks so much for your quick analysis, much appreciated :+1: !

Using `group_keys = False` is unfortunately not really an option for me, as I need to retain the group information in the result.

But as @jrbourbeau has pointed out, I can obtain what seems a stable result with `group_keys = True` with the latest pandas dev builds (I built the latest pandas commit from source to confirm), so chances are good that it will work as soon as pandas 1.5.0 will be released.

So it is fine for me to close the issue, thank you so much for you support!

**Closed** 2022-09-19 14:49 UTC
Labels: needs triage
