### ISSUE TITLE
NotImplementedError() raised while trying apply 

### ISSUE THREAD

**Issue by everestial** [dask/dask#3555] opened 2018-06-04 16:01 UTC
I have several large dataframes with data something like this

    CHROM   POS    patHap    matHap  ms01e:PI
    1               22        A             T            21
    1               27        G             C           21
     ..................
     ......................
    2               15       C              G           12
    2               31       T              G           15

which I want to merge using dask. So, I am reading each file in a for-loop --> storing them as dask dataframe -->  updating the dataframe --> putting them in a list ---> and finally merge

In this problem I am having problem updating the dataframe before it goes into merge

**Read and Update the dataframe**
    df_by_pd = pd.read_csv(names, sep='\t', dtype={"CHROM": str, "POS": int})   

    # find sample name in that dataframe
    for cols in df_by_pd.columns:
        if cols.endswith(':PI'):
            sample_name = cols.split(':')[0]

    # drop the old "sampleName:PI" column
    df_by_pd = df_by_pd.drop([sample_name + ':PI'], axis=1)

    # create new columns
    df_by_pd[sample_name + ':PG_al'] = df_by_pd["patHap"] + '|' + df_by_pd["matHap"]

    # also create a new "sample_name:PI" column and update it with "CHROM" column except when "PG_al" is "."
    # But, I am getting error while working this out
    df_by_pd[sample_name + ':PI'] = df_by_pd['CHROM'].\
                apply(lambda x: '.' if '.' in df_by_pd[sample_name + ':PG_al'] else x, meta=(sample_name + ':PI', 'str'))

```
Traceback (most recent call last):
  File "/home/priyanka/PycharmProjects/SmallTools/MergeHaplotypes/merge_haplotypeDask.py", line 284, in <module>
    main()
  File "/home/priyanka/PycharmProjects/SmallTools/MergeHaplotypes/merge_haplotypeDask.py", line 138, in main
    pd_df_merged.to_csv(output +'/daskdf*.txt', sep='\t', index=False, header=True)
  File "/usr/local/lib/python3.6/dist-packages/dask/dataframe/core.py", line 1077, in to_csv
    return to_csv(self, filename, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/dataframe/io/csv.py", line 577, in to_csv
    delayed(values).compute(get=get)
  File "/usr/local/lib/python3.6/dist-packages/dask/base.py", line 154, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/base.py", line 407, in compute
    results = get(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/threaded.py", line 75, in get
    pack_exception=pack_exception, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/local.py", line 521, in get_async
    raise_exception(exc, tb)
  File "/usr/local/lib/python3.6/dist-packages/dask/compatibility.py", line 67, in reraise
    raise exc
  File "/usr/local/lib/python3.6/dist-packages/dask/local.py", line 290, in execute_task
    result = _execute_task(task, data)
  File "/usr/local/lib/python3.6/dist-packages/dask/local.py", line 271, in _execute_task
    return func(*args2)
  File "/usr/local/lib/python3.6/dist-packages/dask/dataframe/core.py", line 3530, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/dask/utils.py", line 688, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pandas/core/series.py", line 2551, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/src/inference.pyx", line 1521, in pandas._libs.lib.map_infer
  File "/home/priyanka/PycharmProjects/SmallTools/MergeHaplotypes/merge_haplotypeDask.py", line 244, in <lambda>
    apply(lambda x: '.' if '.' in df_by_pd[sample_name + ':PG_al'] else x, meta=(sample_name + ':PI', 'str'))
  File "/usr/local/lib/python3.6/dist-packages/dask/dataframe/core.py", line 1933, in __getitem__
    raise NotImplementedError()
NotImplementedError
```

What is wrong with my method here? And how could I fix it. 
I looked into this and other examples: https://stackoverflow.com/questions/42212496/assign-add-a-new-column-to-a-dask-dataframe-based-on-values-of-2-existing-colu
but, its not helping.

**Comment by mrocklin** [comment] 2018-06-04 17:07
Thanks for the bug report.  For faster response I recommend trying to craft
a minimal bug report:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by everestial** [comment] 2018-06-04 17:22
@matthewrocklin 
Is this a code problem or a bug ? 

I also reopened a closed issue (yesterday) which I think is more of a bug.

**Comment by everestial** [comment] 2018-06-04 18:55
I have shared 4 dataframes in this dropbox link along with other required files including `*.py` file. I am sharing the large dataframe because the error/issue might disappear in small dataframes.

https://www.dropbox.com/sh/z480pxg1wrfmv6f/AADdxiCCuEg9oo_Z9kzGSF1ka?dl=0

Simply run the code in bash: `$ python3 merge_haplotypeDask.py --hapList hapList-Set02.txt --f1List f1List-Set02.txt --output mergedSet02Dask02 --f1ParentIDs Sp,My`

**Comment by mrocklin** [comment] 2018-10-24 19:31
Closing due to lack of reproducible example (see blogpost linked to above)

**Closed by mrocklin** 2018-10-24 19:31 UTC
