### ISSUE TITLE
Getting XZ file size without the whole file

### ISSUE THREAD

**Issue by jseabold** [dask/dask#1229] opened 2016-06-06 04:49 UTC
Parking this here until I can spend some more time on it and thinking about potential issues. Working my way through seeing why the initial creating of a Bag from a blocked xz object in s3 is so slow. The first bottleneck is in reading the entire file AFAICT from s3 in `getsize` to get the uncompressed size and make the offsets. You can get this information from the XZ footer in many cases.

I'm not sure this will work on files with multiple streams or the other failure modes in which to fail gracefully yet. I think this is rare, but I'm not sure.

```
from io import BytesIO

import boto3
from lzmaffi import (SEEK_SET,
                     SEEK_CUR,
                     SEEK_END,
                     STREAM_HEADER_SIZE,
                     _peek,
                     decode_stream_footer,
                     decode_index
                     )


def get_xz_size(fp):
    # mostly cribbed from lzmaffi.LZMAFile
    fp.seek(0, SEEK_END)

    fp.seek(-4, SEEK_CUR)
    padding = 0
    while _peek(fp, 4) == b'\x00\x00\x00\x00':
        fp.seek(-4, SEEK_CUR)
        padding += 4

    fp.seek(-STREAM_HEADER_SIZE + 4, SEEK_CUR)
    stream_flags = decode_stream_footer(_peek(fp, STREAM_HEADER_SIZE))
    fp.seek(-stream_flags.backward_size, SEEK_CUR)

    new_index = decode_index(_peek(fp, stream_flags.backward_size), padding)

    return new_index.uncompressed_size


def getsize(path, compression, s3):
    # no real way to know about the padding AFAICT
    # could fail more gracefully and do increasing range sizes
    client = s3.session.client('s3')
    bucket, key = path.split('/', 1)
    obj = client.get_object(Bucket=bucket, Key=key, Range='bytes=-64000')
    return get_xz_size(BytesIO(obj['Body'].read()))
```

Incidentally, and this is probably known, but if you set a small blocksize on a big file, you can spend a lot of time in helper functions. Some profiling I did showed ~30 seconds being spent calling `isinstance`, for example.

**Edit** Adding some profiling info.

File information. xz zipped file of the Reddit data. Made with blocksizes of 2 *\* 28 bytes.

```
|12 $ xz -lv RC_2012-01.xz
RC_2012-01.xz (1/1)
  Streams:            1
  Blocks:             36
  Compressed size:    1,564.6 MiB (1,640,610,088 B)
  Uncompressed size:  8,985.2 MiB (9,421,643,851 B)
  Ratio:              0.174
  Check:              CRC32
  Stream padding:     0 B
  Streams:
    Stream    Blocks      CompOffset    UncompOffset        CompSize      UncompSize  Ratio  Check      Padding
         1        36               0               0   1,640,610,088   9,421,643,851  0.174  CRC32            0
  Blocks:
    Stream     Block      CompOffset    UncompOffset       TotalSize      UncompSize  Ratio  Check
         1         1              12               0      44,515,064     268,435,456  0.166  CRC32
         1         2      44,515,076     268,435,456      46,363,016     268,435,456  0.173  CRC32
         1         3      90,878,092     536,870,912      47,664,172     268,435,456  0.178  CRC32
         1         4     138,542,264     805,306,368      47,556,716     268,435,456  0.177  CRC32
         1         5     186,098,980   1,073,741,824      47,077,776     268,435,456  0.175  CRC32
         1         6     233,176,756   1,342,177,280      47,012,772     268,435,456  0.175  CRC32
         1         7     280,189,528   1,610,612,736      46,765,040     268,435,456  0.174  CRC32
         1         8     326,954,568   1,879,048,192      45,930,444     268,435,456  0.171  CRC32
         1         9     372,885,012   2,147,483,648      46,271,224     268,435,456  0.172  CRC32
         1        10     419,156,236   2,415,919,104      47,666,328     268,435,456  0.178  CRC32
         1        11     466,822,564   2,684,354,560      46,713,536     268,435,456  0.174  CRC32
         1        12     513,536,100   2,952,790,016      47,080,768     268,435,456  0.175  CRC32
         1        13     560,616,868   3,221,225,472      46,696,412     268,435,456  0.174  CRC32
         1        14     607,313,280   3,489,660,928      46,860,648     268,435,456  0.175  CRC32
         1        15     654,173,928   3,758,096,384      47,020,680     268,435,456  0.175  CRC32
         1        16     701,194,608   4,026,531,840      46,243,948     268,435,456  0.172  CRC32
         1        17     747,438,556   4,294,967,296      46,529,068     268,435,456  0.173  CRC32
         1        18     793,967,624   4,563,402,752      46,770,552     268,435,456  0.174  CRC32
         1        19     840,738,176   4,831,838,208      46,890,440     268,435,456  0.175  CRC32
         1        20     887,628,616   5,100,273,664      46,445,100     268,435,456  0.173  CRC32
         1        21     934,073,716   5,368,709,120      46,544,852     268,435,456  0.173  CRC32
         1        22     980,618,568   5,637,144,576      47,012,008     268,435,456  0.175  CRC32
         1        23   1,027,630,576   5,905,580,032      46,247,284     268,435,456  0.172  CRC32
         1        24   1,073,877,860   6,174,015,488      45,990,216     268,435,456  0.171  CRC32
         1        25   1,119,868,076   6,442,450,944      46,573,748     268,435,456  0.174  CRC32
         1        26   1,166,441,824   6,710,886,400      47,157,424     268,435,456  0.176  CRC32
         1        27   1,213,599,248   6,979,321,856      47,028,536     268,435,456  0.175  CRC32
         1        28   1,260,627,784   7,247,757,312      46,936,560     268,435,456  0.175  CRC32
         1        29   1,307,564,344   7,516,192,768      47,137,180     268,435,456  0.176  CRC32
         1        30   1,354,701,524   7,784,628,224      46,858,996     268,435,456  0.175  CRC32
         1        31   1,401,560,520   8,053,063,680      46,922,832     268,435,456  0.175  CRC32
         1        32   1,448,483,352   8,321,499,136      46,239,540     268,435,456  0.172  CRC32
         1        33   1,494,722,892   8,589,934,592      46,672,132     268,435,456  0.174  CRC32
         1        34   1,541,395,024   8,858,370,048      47,904,024     268,435,456  0.178  CRC32
         1        35   1,589,299,048   9,126,805,504      46,677,644     268,435,456  0.174  CRC32
         1        36   1,635,976,692   9,395,240,960       4,633,052      26,402,891  0.175  CRC32
```

Using the following snippet.

```
%prun bag = db.read_text(S3_URL, blocksize=2 ** 28)
```
### With original getsize

```
         4256026 function calls (4254493 primitive calls) in 68.786 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   379350   58.845    0.000   58.845    0.000 {method 'read' of '_ssl._SSLSocket' objects}
   379350    1.199    0.000   61.972    0.000 ssl.py:913(recv_into)
   379350    1.196    0.000   65.091    0.000 socket.py:561(readinto)
        7    1.133    0.162   68.512    9.787 core.py:747(_fetch)
     3129    1.107    0.000   65.922    0.021 {method 'read' of '_io.BufferedReader' objects}
    52/48    1.055    0.020    1.055    0.022 {method 'join' of 'bytes' objects}
   379350    0.902    0.000   60.437    0.000 ssl.py:778(read)
   379350    0.873    0.000    0.873    0.000 {method '_checkClosed' of '_io._IOBase' objects}
   379350    0.553    0.000   59.398    0.000 ssl.py:563(read)
   379355    0.542    0.000    0.542    0.000 socket.py:600(readable)
   379350    0.508    0.000    1.050    0.000 {method '_checkReadable' of '_io._IOBase' objects}
   758711    0.303    0.000    0.303    0.000 ssl.py:766(_checkClosed)
        3    0.217    0.072   67.229   22.410 client.py:422(read)
384048/383773    0.173    0.000    0.173    0.000 {built-in method builtins.len}
...
```
### with `getsize` defined above

```
         31610 function calls (30556 primitive calls) in 1.582 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       15    1.496    0.100    1.496    0.100 {method 'read' of '_ssl._SSLSocket' objects}
        2    0.013    0.006    0.013    0.006 {method 'load_verify_locations' of '_ssl._SSLContext' objects}
        2    0.011    0.006    0.011    0.006 {method 'do_handshake' of '_ssl._SSLSocket' objects}
        3    0.007    0.002    0.007    0.002 decoder.py:345(raw_decode)
      185    0.003    0.000    0.003    0.000 {built-in method posix.stat}
        2    0.002    0.001    0.002    0.001 {method 'connect' of '_socket.socket' objects}
       83    0.002    0.000    0.002    0.000 {built-in method posix.listdir}
        2    0.002    0.001    0.002    0.001 {built-in method _socket.getaddrinfo}
     5370    0.002    0.000    0.003    0.000 {built-in method builtins.isinstance}
        1    0.001    0.001    1.577    1.577 s3.py:16(read_bytes)
...
```
### Small block-size and the original `getsize`.

I suppose I should have expected this. Not sure there's much to do here. I expected this to be marginally more efficient, coupled with a smaller file block-size. It wasn't. These numbers don't reflect the run I did with a file with smaller blocks.

```
%prun bag = db.read_text(S3_URL, blocksize=10000)
```

```
         230604355 function calls (224009088 primitive calls) in 325.585 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   233566   68.062    0.000   68.062    0.000 {method 'read' of '_ssl._SSLSocket' objects}
14132475/10363815   31.472    0.000  107.444    0.000 delayed.py:34(to_task_dasks)
 72548124   27.335    0.000   60.224    0.000 {built-in method builtins.isinstance}
3768660/1884330   21.037    0.000  105.689    0.000 delayed.py:26(unzip)
 13190339   20.419    0.000   32.890    0.000 abc.py:178(__instancecheck__)
  1884330   14.197    0.000  159.794    0.000 delayed.py:356(__call__)
 26380663   12.471    0.000   12.471    0.000 _weakrefset.py:70(__contains__)
  1884332   12.162    0.000   35.430    0.000 base.py:236(tokenize)
  3768660    7.754    0.000   14.290    0.000 delayed.py:21(flat_unique)
   942165    7.415    0.000    7.415    0.000 {built-in method posix.urandom}
   942165    6.740    0.000    6.740    0.000 {built-in method _pickle.dumps}
  1884330    5.937    0.000   51.383    0.000 delayed.py:332(__init__)
  5652995    5.914    0.000   19.349    0.000 utils.py:473(__call__)
  2826495    5.905    0.000   60.374    0.000 delayed.py:94(tokenize)
   942165    5.091    0.000    7.579    0.000 uuid.py:106(__init__)
  4710825    4.943    0.000    5.506    0.000 itertoolz.py:193(unique)
  1884330    4.709    0.000   69.323    0.000 delayed.py:112(delayed)
        1    4.051    4.051  138.802  138.802 s3.py:72(<listcomp>)
  2826495    3.804    0.000    8.767    0.000 delayed.py:352(_data)
  3768660    3.521    0.000    5.564    0.000 itertoolz.py:314(first)
   942165    2.994    0.000    2.994    0.000 uuid.py:225(__str__)
  1884330    2.853    0.000   72.176    0.000 functoolz.py:279(__call__)
        1    2.720    2.720   99.938   99.938 text.py:87(<listcomp>)
   942165    2.438    0.000   17.431    0.000 uuid.py:600(uuid4)
 942167/2    2.192    0.000    6.605    3.303 dicttoolz.py:19(merge)
  1884330    2.156    0.000    2.156    0.000 delayed.py:268(__init__)
   942165    2.013    0.000    9.391    0.000 base.py:133(normalize_function)
  2826500    1.829    0.000    1.829    0.000 {method 'update' of 'dict' objects}
  7537329    1.800    0.000    1.800    0.000 {method 'pop' of 'dict' objects}
  1884333    1.571    0.000    1.571    0.000 {method 'hexdigest' of '_hashlib.HASH' objects}
   942166    1.570    0.000    1.571    0.000 {built-in method from_bytes}
  1884333    1.461    0.000    1.461    0.000 {built-in method _hashlib.openssl_md5}
   942365    1.272    0.000    1.272    0.000 {built-in method builtins.hasattr}
  1884330    1.213    0.000    1.812    0.000 delayed.py:388(<lambda>)
  3768660    1.158    0.000    1.158    0.000 delayed.py:283(key)
        7    1.133    0.162   75.653   10.808 core.py:747(_fetch)
...
```

**Comment by jseabold** [comment] 2016-06-06 15:01
[For reference](http://tukaani.org/xz/xz-file-format-1.0.4.txt). There's probably a lot of smart, custom logic that could be written around the blocked compress file formats and re-used. It's not for free, but it's fairly straightforward.

**Comment by jseabold** [comment] 2016-06-06 19:10
I guess I'm a little confused in general on how these blocked formats stored on something like s3 could work with dask efficiently without some more work.

It looks like even doing something like `take(1)` is going to download the *entire* file for *each* partition, wrap the entire file with LZMAFile, then use `read_block` to seek to an offset? Then it will pull all those together and grab a slice from it? Is that right?

I expected to be able to set something like 48 MB blocksize in the file, point dask to it and tell it the same blocksize, and that `take(1)` would get the first (or whichever) 48MB chunk using Range the range header to s3 and return in a few seconds. Am I totally misunderstanding?

**Comment by jseabold** [comment] 2016-06-06 19:15
I guess it's hitting the cache eventually? Is there a thundering herd problem?

**Comment by jseabold** [comment] 2016-06-06 22:55
Ah, digging in a bit more here, I was able to get the optimized dask graph, which is what's being computed not the default output from visualize. Is there an easy way to get this? The visualization tends to hide everything interesting that happens in a `list(...)`. I had to copy the logic in visualize

```
{('take-5a7336fb928041207b9a5bbb2a83acf5', 0): (list,
  (<function toolz.itertoolz.take>,
   1,
   (map,
    <function ujson.loads>,
    (<function dask.bag.text.decode>,
     (<function dask.bytes.s3.read_block_from_s3>,
      'S3_URL',
      0,
      268435456,
      (dict, [['anon', False]]),
      b'\n',
      'xz'),
     'utf-8',
     'strict'))))}
```

So I guess it doesn't download the entire file for this. I guess the only potential optimization that's missing is using ranges to download the blocks from s3.

**Comment by mrocklin** [comment] 2016-06-06 23:22
@jseabold you might appreciate https://github.com/dask/dask/pull/1224

There are two mechanisms to grab data from S3, one is reading in blocks using range queries, the other is to provide an `s3fs.S3File` object that streams things through.  If you provide `blocksize=` you'll get the first, if you don't provide that then you'll get the second.

Adding LZMA on top of this complicates things because it has *its own* blocksize which makes things a bit funky.

**Comment by jseabold** [comment] 2016-06-07 02:53
Thanks, yeah, I was reading the PR that included the bytes refactor. Nice bit of work.

I saw that it should do streaming with `blocksize=None`, but I didn't notice any appreciable difference doing the take in speed or in my profiling. The instantiation of the bag is certainly faster.

I also didn't see the logic to do Range queries in s3fs. It looked like it would read from the beginning of the file and seek to the offset you requested rather than explicitly passing a Range header as I did above. Am I missing it?

**Comment by mrocklin** [comment] 2016-06-07 03:01
I'll defer to @martindurant for the Range on S3 question.

Regarding streaming and performance, LZMA will have to download the entire block before it can decompress the first byte.  By default their blocksizes can be fairly large (or even the entire file is common) and so there will be a large upfront cost regardless.  You may want to download the file and then check the blocksizes using the xz command line tool.   There is, to my knowledge, no way to introspect within a block.

**Comment by martindurant** [comment] 2016-06-07 03:11
I'll look into what you've written above regarding timings tomorrow. Certainly, S3 is not meant for many short reads, as there is a significant cost to establishing connections.

The logic to pass `Range=` is in the `s3fs.core._fetch_range()` function: you can seek within a S3File before the first read and only get some specific piece (the block_size parameter defines the read buffer size), or call the S3FileSystem.read_block. If this isn't occurring as it should, let us know!

**Comment by jseabold** [comment] 2016-06-07 03:16
I created this file and was trying out different blocksizes, so I have control over that. I posted the blocksizes for this run above, but I'll need to go back and post profiling results for the smaller ones. I expected as you say, that I could pay a larger upfront cost, spending minutes in things like isinstance as noted above with the smaller blocksizes and get a faster take, but I'll need to go back and try with a smaller xz blocksize and a blocksize of None to dask to get closer to streaming behavior. I *think* I tried it but didn't notice substantially better behavior.

That said, and it's entirely possible I have a network bottleneck, but 44 MB (compressed) blocksizes should be a few seconds not the 300s spent in posix.read that I saw.

**Comment by mrocklin** [comment] 2016-06-07 03:18
OK, I should take a closer look at your numbers before I comment further.

**Comment by jseabold** [comment] 2016-06-07 03:19
I didn't post the profiling results for take that I saw yet. That's why I was trying to read the code more and get the optimized graph, so I could say something coherent about that.

This isn't anything urgent I'm just trying to fix my expectations and understanding.

**Comment by jseabold** [comment] 2016-06-07 03:24
@martindurant I'll have to look closer here to see if I can avoid my boto3 call above and use your range. I didn't see it, but I didn't look very hard. Would be nice to read the footer and save a minute here, but it's going to take a bit more work than my ideal case above. Some of the xz spec notes that things are optional and I just guessed at how big the tail of the file should be.

Full disclosure: I didn't know anything about xz until I read the seekable compression code in bytes.compression and then read the xz spec and the biopython posts about this, so this isn't something mission critical for me. Just seems like it could be an easy simple win for text files. Dev time would probably be better spent on something like parquet support.

**Comment by jseabold** [comment] 2016-06-07 03:46
If you feel like mucking around with this you can use

```
bunzip2 -d -k -c $INFILE | pixz -5 -f 32 -o $OUTFILE
```

to recreate the reddit data as an xz file. `man xz` tells you the dictionary size for the compression levels and `-f` is a multiple of that size. The above seemed to be a decent tradeoff between blocksize and compression.

**Comment by martindurant** [comment] 2016-06-07 14:36
The graph you show does seem to explicitly download the whole file in one go
```
{('take-5a7336fb928041207b9a5bbb2a83acf5', 0): (list,
  (<function toolz.itertoolz.take>,
   1,
   (map,
    <function ujson.loads>,
    (<function dask.bag.text.decode>,
     (<function dask.bytes.s3.read_block_from_s3>,
      'S3_URL',
      0,
      268435456,
      (dict, [['anon', False]]),
      b'\n',
      'xz'),
     'utf-8',
     'strict'))))}```
(the two numerical arguments to read_block_from_s3 are offset and length)

You can pass an S3File directly to your get_xz_size and it works totally fine - only reads the footer. Actually, the code could be cleaner: `f._peek(x)` does `f.read(x); f.seek(-x, 1)`. The cache is optimised for read-ahead rather than backwards as here, but the few required reads should be fast (boto reuses it's connection at least a few times).

**Comment by mrocklin** [comment] 2016-06-08 03:10
It feels like there might be a few issues here.  

### Getsize

Our current implementation is as follows:

```python
def getsize(path, compression, s3):
    if compression is None:
        return s3.info(path)['Size']
    else:
        with s3.open(path, 'rb') as f:
            g = seekable_files[compression](f)
            g.seek(0, 2)
            result = g.tell()
            g.close()
        return result
```

So I guess our questions boils down to whether the combination of `s3fs.S3File` and the `lzma.File` objects play sufficiently nicely to get the size without reading in the entire file.  My intuition here is that *yes* they can, but the 68s cost similarity is pretty strong in @jseabold 's profiles.

We could special case this per-compression format but I'd really like to think that that logic is already in the `lzma` library.  Does anyone know?

### Overhead cost

We should reduce the overhead to bag creation (for example calls to `isinstance` and `tokenize`) however there is only so much good we can do here.  Generally you should budget around 1ms per task/partition.  I suspect that, as you point out, your bag is *very* finely partitioned.

**Comment by martindurant** [comment] 2016-06-08 13:23
On a quick test (148-byte file!), lzma seems to read the whole file when seeking to the end:
```
f = s3.open('MDtemp/lzfile', 'rb')
lf = lzma.open(f)
lf.seek(0, 2)
len(f.cache) == 148
```
Whereas passing f to `get_xy_size` above only required the end
```
f = s3.open('MDtemp/lzfile', 'rb')
get_xz_size(f)
len(f.cache) == 24
```

**Comment by martindurant** [comment] 2016-06-08 13:28
From the docstring for lzma's seek:
```
        Note that seeking is emulated, so depending on the parameters,
        this operation may be extremely slow.
```

**Comment by jseabold** [comment] 2016-06-08 13:35
You have to use lzmaffi I believe.

**Comment by martindurant** [comment] 2016-06-08 13:53
`lzmaffi.open(f)` causes a read even before any seek. Which such a small file, I don't know how much of a larger file it would have read.

**Comment by mrocklin** [comment] 2016-06-08 15:11
OK, that solves the mystery of why things are slow.  Assuming that lzmaffi handles things well it seems like we have two options:

1.  Register getsize functions per compression (doable)
2.  Just depend on lzmaffi (also doable)

Thoughts on the maintenance/support tradeoff?

**Comment by martindurant** [comment] 2016-06-08 15:59
lzmaffi should be tested to see how it behaves within getsize and bag first. I suspect one-to-one replacement might not be enough, and option 1) will have to be the one.

**Comment by jseabold** [comment] 2016-06-08 17:11
My guess is it's reading the index of the stream like I'm doing above, so
it knows how to seek, but we can always check.

**Comment by jseabold** [comment] 2016-06-08 17:26
Actually, I'm fairly certain I cribbed that from LZMAFile.open in lzmaffi.

**Comment by martindurant** [comment] 2016-06-08 17:29
open seems to read the whole of my little file, while the get-size function above correctly only gets the footer. That doesn't matter of course for this little file. I'm interested to know how much is read for much bigger files like the ones you are dealing with.

**Comment by jseabold** [comment] 2016-06-08 17:36
This is the relevant code. Depending on how you created the file, it would
need to read from parts of the whole file to hit the blocks that it needs
to get all of the blocksize information, assuming that isn't all in the
index. I need to read the spec linked above a bit more carefully. That's
why I cribbed the part just to get the stream size since dask doesn't care
about anything else since it makes its own blocks.

I'm having trouble thinking about this in terms of the S3File because I
haven't spent enough time with that code. I'm a bit wary about seeking
through files by making separate s3 API calls through a file-like
abstraction though.

https://github.com/r3m0t/backports.lzma/blob/master/lzmaffi/__init__.py#L300

**Comment by martindurant** [comment] 2016-06-08 18:01
So it looks like opening using lzmaffi creates the whole block index, which involves stepping through the file block-by-block in reverse order. 
This will indeed read the whole file into cache in S3File, with one S3 read per block.
lzma's File only did a read on the first seek, I haven't looked yet to see if that too steps through the blocks at that point.

**Comment by martindurant** [comment] 2016-06-08 18:39
I addition, at lzmaffi always checks the magic value at the head of the file. 
S3File was designed to get some contiguous block out, so if you read at the head and then then foot, you will get the intermediate data too... Repeatedly calling S3FileSystem.read_block would avoid this. 
The blog post here http://blastedbio.blogspot.ca/2013/04/random-access-to-blocked-xz-format-bxzf.html suggests that the index should be at the end, and there should be no need to page through all the blocks.

**Comment by wabu** [comment] 2016-12-13 06:16
As a reference, lzmaffi already is loaded with #1096 if installed. But perhaps one should consolidate the documentation and/or give a warning when lzma is used.

**Comment by TomAugspurger** [comment] 2019-08-08 15:18
Note: I think we may have lost the usage of `lzmaffi`. I don't see usages of `dask.compatability.lzma_compress` anywhere inside dask/dataframe.

**Comment by martindurant** [comment] 2019-08-08 15:21
fsspec support xz files: https://github.com/intake/filesystem_spec/blob/master/fsspec/compression.py#L31

However, the "blocks" mode of xz is not standard and seems rare, so pseudo-random-access is not implemented.

`lzma_compress` can probably be removed from dask.

**Comment by martindurant** [comment] 2019-08-08 15:25
(I recommend closing this issue)

**Comment by mrocklin** [comment] 2019-08-08 15:31
FWIW my experience is similar to Martin's.  I'm not sure that supporting xz
is worth the time.

**Comment by mrocklin** [comment] 2019-08-08 15:31
Oh yeah, given the age of the issue I'm also in favor of just closing with a "this has gone stale, please reopen if this is still a live issue"

**Comment by mrocklin** [comment] 2019-08-08 15:32
Recognizing that conversation has some non-trivial cost.

**Closed** 2019-08-08 16:17 UTC
Labels: io
