### ISSUE TITLE
can't pickle_asyncio. task type using client.compute

### ISSUE THREAD

**Issue by jie666-6** [dask/dask#7412] opened 2021-03-17 11:30 UTC
Here is my code:
 ```
from dask import delayed
from dask.distributed import Client
....
params = ((rg_indx) for rg_indx in np.arange(RGindex_1 + 1, RGindex_2))
 values = [delayed(param_evaluate)(arg) for arg in params]
 l_future = client.compute(values)
 search_space = client.gather(l_future)
......
```

Then I got this error for the line of client.compute: can't pickle_asyncio. task type

```
Traceback (most recent call last):
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\distributed\worker.py", line 3398, in dumps_function
    result = cache_dumps[func]
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\distributed\utils.py", line 1523, in __getitem__
    value = super().__getitem__(key)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\collections\__init__.py", line 991, in __getitem__
    raise KeyError(key)
KeyError: <function HSBACD.fl_map.<locals>.param_evaluate at 0x000001E6171D2268>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\distributed\protocol\pickle.py", line 49, in dumps
    result = pickle.dumps(x, **dump_kwargs)
AttributeError: Can't pickle local object 'HSBACD.fl_map.<locals>.param_evaluate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\pydevd.py", line 1668, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.3.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File ".../probabilistic_urban_mask.py", line 403, in <module>
    probabilistic()
  File ".../probabilistic_urban_mask.py", line 369, in probabilistic
    Gaussian_parameters = Gaussian_fitting.fl_map()
  File ".../probabilistic_urban_mask.py", line 335, in fl_map
    l_future = client.compute(values)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\distributed\client.py", line 2846, in compute
    actors=actors,
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\distributed\client.py", line 2542, in _graph_to_futures
    dsk = dsk.__dask_distributed_pack__(self, keyset)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\dask\highlevelgraph.py", line 939, in __dask_distributed_pack__
    client_keys,
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\dask\highlevelgraph.py", line 392, in __dask_distributed_pack__
    dsk = toolz.valmap(dumps_task, dsk)
  File "cytoolz\dicttoolz.pyx", line 179, in cytoolz.dicttoolz.valmap
  File "cytoolz\dicttoolz.pyx", line 204, in cytoolz.dicttoolz.valmap
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\distributed\worker.py", line 3436, in dumps_task
    return {"function": dumps_function(task[0]), "args": warn_dumps(task[1:])}
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\distributed\worker.py", line 3400, in dumps_function
    result = pickle.dumps(func, protocol=4)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\distributed\protocol\pickle.py", line 60, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 409, in dump
    self.save(obj)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 745, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 687, in _save_reduce_pickle5
    save(state)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 736, in save_tuple
    save(element)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 751, in save_tuple
    save(element)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 610, in save_reduce
    save(args)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 736, in save_tuple
    save(element)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 605, in save_reduce
    save(cls)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 728, in save_global
    self._save_reduce_pickle5(*_dynamic_class_reduce(obj), obj=obj)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 687, in _save_reduce_pickle5
    save(state)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 736, in save_tuple
    save(element)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 745, in save_function
    *self._dynamic_function_reduce(obj), obj=obj
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 687, in _save_reduce_pickle5
    save(state)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 736, in save_tuple
    save(element)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 521, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 634, in save_reduce
    save(state)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 821, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 847, in _batch_setitems
    save(v)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 476, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 781, in save_list
    self._batch_appends(obj)
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 808, in _batch_appends
    save(tmp[0])
  File "C:\Users\AppData\Local\Continuum\anaconda3\envs\exclusion_map_clone\lib\pickle.py", line 496, in save
    rv = reduce(self.proto)
TypeError: can't pickle _asyncio.Task objects
```

So I would like to ask for help to solve this error here.
Thanks in advance

**Environment**:

- Dask version: 2021.3.0
- Python version: 3.6.7
- Operating System: Win10
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment] 2021-03-17 21:47
Thanks for raising an issue @jie666-6. It looks like Dask is having trouble pickling an object. Are you able to provide a minimal reproducer that we can run to try and debug? (see https://blog.dask.org/2018/02/28/minimal-bug-reports)

**Comment by jsignell** [comment] 2021-03-19 13:15
As a note, I often see issues like this when the library isn't available on the worker.

**Comment by jsignell** [comment] 2021-03-24 15:49
Closing this for now, but please reopen if you are able to create a reproducer

**Closed by jsignell** 2021-03-24 15:49 UTC
Labels: needs info
