### ISSUE TITLE
Bug with geopandas dataframe Point objects

### ISSUE THREAD

**Issue by nilslacroix** [dask/dask#8953] opened 2022-04-20 13:19 UTC
I do not know if this is related to a bad implementation of pandas or dask, so I don't know how relevant it is.

Problem description:

When I use a dask.dataframe, apply it to a function and this functions uses the POINT datastructure I get an
IndexError('index out of range') error. This is usually a problem if empty points are in a list 
( see: https://github.com/geopandas/geopandas/issues/2223 ) , but this is not the case this time (I triple checked). 

I took a look at the dask.dataframe which looked like this:

```
  Nightlife     geometry
1       foo  POINT EMPTY
2       foo  POINT EMPTY
```

I do not know what foo is, but I guess some placeholder variable for dask? If that is the case it is very strange that POINT EMPTY is in the second column.

An example which produces an similiar error, but not exactly the same:

```

import pandas as pd
import geopandas as gpd
from dask import compute, dataframe

df = pd.DataFrame({"Feature": [(54.0490878,9.916783),(53.0490878,8.816783)],"Feature2": [(51.0490878,7.916783),(58.0490878,6.816783)]})
ddf = dataframe.from_pandas(df, npartitions=2)



def f(d):
    for col in d:
        x = [i[1] for i in d[col].values]
        y = [i[0] for i in d[col].values]
        print(y)
        frame = gpd.GeoDataFrame(d, geometry=gpd.points_from_xy(x,y)).set_crs("epsg:4326").to_crs("epsg:25832")
        frame.dropna(inplace=True)
        tmp = pd.DataFrame(zip(frame.geometry.x,frame.geometry.y), columns=["lon","lat"])
    return tmp


result = ddf.map_partitions(f)
print("Start Compute...")
result.compute()
```

**Comment by pavithraes** [comment] 2022-04-20 18:37
@nilslacroix Thanks for opening this! I was able to reproduce some errors:

First, we get a `ValueError: Metadata inference failed in f`, which can be fixed by passing a `meta` keyword argument to `map_partitions`:

```python
result = ddf.map_partitions(f, meta=pd.DataFrame(columns=["lon","lat"]))
```

Next, `result.compute()` seems to produce the correct output on the first run but throws this error on subsequent runs: `TypeError: 'Point' object is not subscriptable`. Looks like pandas is changing your DataFrame inplace, inside your function `f`, but we can fix that by using `d.copy`:

```python
frame = gpd.GeoDataFrame(d.copy(), geometry=gpd.points_from_xy(x,y)).set_crs("epsg:4326").to_crs("epsg:25832")
```

Does this help resolve your question?

Also, this looks more like a usage question than a bug report or feature request. We encourage people with such questions to ask them at the [Dask Discourse](https://dask.discourse.group/). Would you mind opening a discussion topic about this over there? If you do so, feel free to close this issue and we will continue the conversation on discourse. :)

**Comment by nilslacroix** [comment] 2022-04-20 19:01
Yes thanks that solves some of my problems. Thanks for your fast reply, I will close this issue. But I have a question in general before I do this, I presume you can answer.

When I pass a dask.dataframe to a function, which was originally a pd.Dataframe - can I still do something like this?

```
for col in some_pandas_dataframe:
        dask_dataframe[col]=pd.NaT
```

I think I have some misconeptions here, since I often get errors when I try to manipulate dask dataframes.

**Comment by pavithraes** [comment] 2022-04-21 11:30
@nilslacroix You _can_, but it's generally not recommended to mix pandas and Dask DataFrames and their corresponding functions. When working with Dask DataFrame, we recommend using [Dask's AP](https://docs.dask.org/en/stable/dataframe-api.html)I (which tries to match/mimic pandas as much as possible).

So, in your example, I'd do something like `for col in dask_dataframe.columns`

The one exception here is when you are sure to be working with the underlying pandas DataFrames, like when using `map_partitions`. But, note that we don't encourage using `map_partitions` when the workflow can use `apply` or `map` directly. Does this help answer your question?

You may find [these DataFrame best practices](https://docs.dask.org/en/stable/dataframe-best-practices.html) interesting as well. :)

**Closed** 2022-04-21 13:27 UTC
Labels: dataframe
