### ISSUE TITLE
pandas 2.0 uses RangeIndex for empty DataFrames, including empty DataFrames after merge

### ISSUE THREAD

**Issue by phofl** [dask/dask#10141] opened 2023-04-04 11:43 UTC
**Describe the issue**:

Not sure if this is a real issue, before pandas 2.0 the returned Index in a merge operation always had dtype ``object``. This changed to ``RangeIndex`` with 2.0. 

We keep the index dtype, e.g. an empty merge and a non-empty merge will have the same index dtype. 

Do we want to keep this or follow the pandas behaviour starting from 2.0?

This causes a failure in distributed, https://github.com/dask/distributed/actions/runs/4605359632/jobs/8137298140

**Minimal Complete Verifiable Example**:

```python
pdf = DataFrame({"a": [1, 2]}, index=["a", "b"])
pdf2 = DataFrame({"b": [1, 2]}, index=["x", "y"])

ddf = dask.dataframe.from_pandas(pdf, npartitions=1)
ddf2 = dask.dataframe.from_pandas(pdf2, npartitions=1)

ddf.join(ddf2, how="inner").compute().index
pdf.join(pdf2, how="inner").index
```

**Anything else we need to know?**:

**Environment**:

- Dask version: dev
- Python version: 3.10
- Operating System: Mac 
- Install method (conda, pip, source): mamba

**Comment by jrbourbeau** [comment] 2023-04-04 16:48
Thanks for the issue and nice reproducer @phofl. I think this is a duplicate of https://github.com/dask/dask/issues/9957, so I'm going to close this issue in favor of that one. Let me know if that's not the case and we can re-open this one

**Closed by jrbourbeau** 2023-04-04 16:48 UTC
Labels: needs triage
