### ISSUE TITLE
Keyword overwrite not supported? 

### ISSUE THREAD

**Issue by mengaldo** [dask/dask#7465] opened 2021-03-25 02:23 UTC
I strongly support @hayesgb. 
I am trying to use the keyword `overwrite=True`, but I get this error: 

```
File "/usr/local/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 443, in to_parquet
    meta, i_offset = engine.initialize_write(
  
File "/usr/local/lib/python3.8/site-packages/dask/dataframe/io/parquet/fastparquet.py", line 413, in initialize_write
    fmd = fastparquet.writer.make_metadata(

TypeError: make_metadata() got an unexpected keyword argument 'overwrite'

```

_Originally posted by @mengaldo in https://github.com/dask/dask/issues/6824#issuecomment-806311757_

**Comment by rjzamora** [comment] 2021-03-25 02:26
Thanks @mengaldo - Can you share a reproducer, and specify the version of dask you are using?

**Comment by mengaldo** [comment] 2021-03-25 02:44
Thank you for the prompt reply @rjzamora.
Version: dask==2.3.0

```
import numpy as np
import pandas as pd
import dask.dataframe as dd

A = np.random.rand(300,200)
df = pd.DataFrame(A)
print(df)
sd = dd.from_pandas(df, npartitions=1)
sd.to_parquet(
	'sd.parquet', engine='fastparquet', compression='default',
	write_index=True, overwrite=True, append=False)

sd.to_parquet(
	'sd.parquet', engine='pyarrow', compression='default',
	write_index=True, overwrite=True, append=False)
```

**Comment by rjzamora** [comment] 2021-03-25 03:24
Thanks for the info @mengaldo - If I am understanding correctly, you are using dask-2.30, which was released in October 2020.  The `overwrite` argument was not added until November 2020.  Can you try updatinag to the latest version of Dask (at least something >2020.12.0 - note that the versioning changed to calver after 2.30).

**Comment by rjzamora** [comment] 2021-03-25 03:26
I'm going to close this since I am pretty sure the issue has been resolved.  However, if I am wrong about this (very possible), please do feel free to re-open :)

**Closed by rjzamora** 2021-03-25 03:26 UTC
Labels: dataframe, io

**Comment by mengaldo** [comment] 2021-03-25 03:29
Thank you @rjzamora - it seems indeed to be fixed.
