### ISSUE TITLE
DASK slow down the IDE

### ISSUE THREAD

**Issue by korosig** [dask/dask#8444] opened 2021-12-02 19:00 UTC
**What happened**:

Hi there, I have installed a new Anaconda 2021.11 with a new Spyder 5.1.5 on my Windows 10 with a New DASK

When I open the new file and import packages, everything goes well, but if I read parquet, it kills my machine.
A simple +,-,/  or another task like asking `timedelta(hours=200)` takes 10 or more seconds.

Do you have an idea to solve that problem?

**Minimal Complete Verifiable Example**:

```
import pandas as pd 
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
import tensorflow as tf
import numpy as np
import dask.dataframe as dd
import dask
from datetime import timedelta
import json

timedelta(hours=200)

df = dd.read_parquet('dataset/flat_table1116.pq/')

timedelta(hours=200)
```
**imported packages**
pandas
1.3.4
tensorflow 
2.3.0
numpy 
1.20.3
dask 
2021.10.0
json 
2.0.9

**Video about the bug**:
https://youtu.be/XLkxrfZeQwc
**Machine**
64GB Ram, iCore9, SSD 1T, 2x 3080 11GB Nvida

**Environment**
Syder IDE 5.1.5| Python 3.8.12 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Windows 10

Mandatory:
atomicwrites >=1.2.0 : 1.4.0 (OK)
chardet >=2.0.0 : 4.0.0 (OK)
cloudpickle >=0.5.0 : 2.0.0 (OK)
cookiecutter >=1.6.0 : 1.7.2 (OK)
diff_match_patch >=20181111 : 20200713 (OK)
intervaltree >=3.0.2 : 3.1.0 (OK)
IPython >=7.6.0 : 7.29.0 (OK)
jedi >=0.17.2;<0.19.0 : 0.18.0 (OK)
jsonschema >=3.2.0 : 3.2.0 (OK)
keyring >=17.0.0 : 23.1.0 (OK)
nbconvert >=4.0 : 6.1.0 (OK)
numpydoc >=0.6.0 : 1.1.0 (OK)
paramiko >=2.4.0 : 2.7.2 (OK)
parso >=0.7.0;<0.9.0 : 0.8.2 (OK)
pexpect >=4.4.0 : 4.8.0 (OK)
pickleshare >=0.4 : 0.7.5 (OK)
psutil >=5.3 : 5.8.0 (OK)
pygments >=2.0 : 2.10.0 (OK)
pylint >=2.5.0;<2.10.0 : 2.9.6 (OK)
pyls_spyder >=0.4.0 : 0.4.0 (OK)
pylsp >=1.2.2;<1.3.0 : 1.2.4 (OK)
pylsp_black >=1.0.0 : None (OK)
qdarkstyle =3.0.2 : 3.0.2 (OK)
qstylizer >=0.1.10 : 0.1.10 (OK)
qtawesome >=1.0.2 : 1.0.2 (OK)
qtconsole >=5.1.0 : 5.1.1 (OK)
qtpy >=1.5.0 : 1.10.0 (OK)
rtree >=0.9.7 : 0.9.7 (OK)
setuptools >=49.6.0 : 58.0.4 (OK)
sphinx >=0.6.6 : 4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 : 2.1.3 (OK)
textdistance >=4.2.0 : 4.2.1 (OK)
three_merge >=0.1.1 : 0.1.1 (OK)
watchdog >=0.10.3 : 2.1.3 (OK)
zmq >=17 : 22.2.1 (OK)

Optional:
cython >=0.21 : 0.29.24 (OK)
matplotlib >=2.0.0 : 3.4.3 (OK)
numpy >=1.7 : 1.20.3 (OK)
pandas >=1.1.1 : 1.3.4 (OK)
scipy >=0.17.0 : 1.7.1 (OK)
sympy >=0.7.3 : 1.9 (OK)

**Comment by scharlottej13** [comment] 2021-12-08 18:16
Hi @korosig, thanks for opening this issue! It seems this is more of a usage question and we encourage people to ask such questions on the [Dask Discourse](https://dask.discourse.group/). Would you mind opening a discussion topic about this over there? If you do so, feel free to close this issue and we will continue the conversation on discourse.

To get the conversation started though, I think you're looking for the [`%timeit` magic command](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-timeit), rather than `timedelta`. You can use this is an IPython session (info on using IPython in Spyder [here](https://docs.spyder-ide.org/current/panes/ipythonconsole.html)), e.g.:
```python
import dask.dataframe as dd
%timeit dd.read_parquet("~/tmp/x.parq")
```
Second, since you're lazily reading in the parquet file, I wouldn't expect the jump in memory you described since you haven't actually executed the function yet (more on that [here](https://docs.dask.org/en/latest/10-minutes-to-dask.html#computation)). It's a bit hard to test, though, without a [minimal reproducer](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Looking forward to continuing the conversation on Discourse!

**Comment by korosig** [comment] 2021-12-08 19:57
Hi,

I have created almost the same ISSUE on SPYDER GIT ISSUE.... and they figured out, that the problem is not about the DASK. 
It is about the Spyder Variable Explorer. When we run a part of the python script the Spyder Variable Explorer refreshes every variable size ....  While checking the DASK data frame size is not a fast action, it takes time.  The (next) Spyder 5.2.2 will solve this problem. 

https://github.com/spyder-ide/spyder/issues/16937

Spyder Support answer:
"...... I think to fix this we should give up computing the representation I mentioned after a timeout, and only show those results we could compute before it..."

**Comment by scharlottej13** [comment] 2021-12-08 20:21
Thanks for the update @korosig! We'll go ahead and close this issue, then.

**Closed** 2021-12-08 20:26 UTC
