### ISSUE TITLE
Problems reading from S3 for dask.array

### ISSUE THREAD

**Issue by marsupialtail** [dask/dask#8884] opened 2022-04-05 23:14 UTC
I am using Dask 2022.4.0. Dask.array s3fs read hdf5 works on local but *does not work* on a cluster.

I have tried to create a CLI cluster and a coiled cluster, both don't work. I have put the data in a public bucket called dask-problem. You can run the following code, it will work on one machine. But if you make a cluster, and uncomment the lines with distributed client and run the code, it will fail. 

```
#from dask.distributed import Client
import s3fs, h5py
import dask.array as da
#client = Client('127.0.0.1:8786')
s3 = s3fs.S3FileSystem()
f = h5py.File(s3.open("s3://dask-problem/matrix.hdf5", "rb"))
x = da.from_array(f["data"],chunks=(12500,1000))
da.matmul(da.transpose(x),x).compute()
```

Each worker complains that they cannot find the file in S3. Even though they should all have correct configs to read the data, since I can run the script locally from each worker and it works.

This could be related to: https://github.com/dask/dask/issues/5818

**Comment by jsignell** [comment] 2022-04-07 14:34
Yeah thanks for opening this @marsupialtail. This feels like a duplicate of https://github.com/dask/dask/issues/7930 and https://github.com/dask/dask/issues/7926 specifically see @martindurant's comment: https://github.com/dask/dask/issues/7926#issuecomment-886823901

**Closed by jsignell** 2022-04-07 14:34 UTC
Labels: array, needs triage

**Comment by marsupialtail** [comment] 2022-04-07 18:12
I don't think my issue is related. I think it's more of a problem with how dask interfaces with S3. On each worker it's complaining that it can't even find the S3 file.

**Comment by martindurant** [comment] 2022-04-07 18:43
> Each worker complains that they cannot find the file in S3

Can you be more explicit, please?
