### ISSUE TITLE
inconsistencies between numpy and dask pad() function

### ISSUE THREAD

**Issue by uturuncoglu** [dask/dask#6882] opened 2020-11-24 05:14 UTC
I am not sure why but following code create different answers for NumPy and Dask,

```
import dask.array as da
import numpy as np

# numpy
arr = [[1,2,3],[3,4,5],[6,7,8]]
arr1 = np.pad(arr, (2,2), mode='reflect', reflect_type='odd')
print(arr1)

# dask
arr2 = da.pad(da.from_array(arr), (2,2), mode='reflect', reflect_type='odd').compute()
print(arr2)
```

The result is

```
arr1 = 
[[-6 -5 -4 -3 -2 -1  0]
 [-3 -2 -1  0  1  2  3]
 [-1  0  1  2  3  4  5]
 [ 1  2  3  4  5  6  7]
 [ 4  5  6  7  8  9 10]
 [ 7  8  9 10 11 12 13]
 [ 9 10 11 12 13 14 15]]
```

and 

```
arr2 =
[[8 7 6 7 8 7 6]
 [5 4 3 4 5 4 3]
 [3 2 1 2 3 2 1]
 [5 4 3 4 5 4 3]
 [8 7 6 7 8 7 6]
 [5 4 3 4 5 4 3]
 [3 2 1 2 3 2 1]]
```

the first one is true but second one not.

**Comment by uturuncoglu** [comment] 2020-11-24 05:33
If array is converted to Dask Array using `da.from_array(arr)` and pass to the NumPy then `np.pad()` function also calculates as `da.pad()`. I am not sure this is expected behavior or not.

**Comment by quasiben** [comment] 2020-11-24 14:12
Thanks @uturuncoglu for raising this.  I believe https://github.com/dask/dask/pull/6579 should resolve this once merged in.  

As for np.pad() operating on a dask array, yes, this is expected.  NumPy has a [protocol](https://numpy.org/neps/nep-0018-array-function-protocol.html) for allowing numpy to dispatch to another array library.

**Comment by jsignell** [comment] 2020-11-24 15:31
I am closing this since it seems like a duplicate of #6127, but thanks for bringing this up!

**Closed by jsignell** 2020-11-24 15:31 UTC

**Comment by uturuncoglu** [comment] 2020-11-24 16:22
@jsignell thank you for your help.

**Comment by mark-boer** [comment] 2020-11-24 16:29
I see I made a typo in the following line. That should have said `reflect_type` instead of `reflect`:

https://github.com/dask/dask/blob/b3707ffac2563c2fa925bc9247564c1c8929e6dd/dask/array/creation.py#L1057 

The `mode='reflect', reflect_type='odd'` has not yet been implemented, but it should have thrown a `NotImplementedError`. @jsignell is right that #6579 should have this fixed as it implements this option.
