### ISSUE TITLE
Chunk size in bytes overflows in _repr_html_ display

### ISSUE THREAD

**Issue by alihaydaroglu** [dask/dask#9561] opened 2022-10-10 13:34 UTC
**Describe the issue**:
After a large dask array with large chunks, displaying the array information in an ipython notebook (using `display()`, or the `_repr_html_` function of the Array class) shows an incorrect chunk size in bytes, seemingly because of an overflow. On my system, running the following command on an IPython notebook displays the correct array size (65.45 GiB) but the incorrect chunk size 
(-390871296 B). Reducing the chunk size to (8,100,1202,1015) fixes the issue. There are no overflow warnings.

**Minimal Complete Verifiable Example**:

```python
import dask.array as darr
import numpy as np
x = darr.ones(shape = (8,3600,1202,1015), dtype=np.int16, chunks=(8,200,1202,1015))
display(x)
```

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/15041006/194878238-93f78e4c-a7e9-4bc2-8dae-786d4b3a6c9f.png)

**Environment**:
- Dask version: 2022.02.01
- Python version: 3.8.13
- Operating System: Windows
- Install method (conda, pip, source): Installed using conda, running on a jupyter notebook

**Comment by jrbourbeau** [comment] 2022-10-11 15:58
Thanks for reporting @alihaydaroglu. I believe this is fixed in more recent versions of `dask` (xref https://github.com/dask/dask/issues/7870). I'm not able to reproduce with the latest `dask=2022.9.2` release

**Comment by jrbourbeau** [comment] 2022-10-11 15:59
Closing for now as fixed, but let us know if upgrading doesn't resolve the issue

**Closed by jrbourbeau** 2022-10-11 15:59 UTC
Labels: needs info

**Comment by alihaydaroglu** [comment] 2022-10-24 09:01
Upgrading fixed the issue, thanks @jrbourbeau
