### ISSUE TITLE
Reading parquet with category dtype

### ISSUE THREAD

**Issue by sephib** [dask/dask#5677] opened 2019-12-05 09:41 UTC
Hi,
We have encountered a problem reading `category` dtype format from `parquet` file.  
versions:
 dask: 2.8.1
 pandas: 0.25.3
 pyarrow: 0.15.1 
 fastparquet:0.3.2

```python
import dask.dataframe as dd
import dask.datasets as ds
import pandas as pd

df = ds.timeseries()
df.name = df.name.astype('category')
df.dtypes
```  
prints out

> id                    int64
> name               category
> x                   float64
> y                   float64
  

```
df.to_parquet('test_parq', engine='pyarrow')
dff = dd.read_parquet('test_parq', engine='pyarrow')
dff.dtypes  
```

prints out 

> id                    int64
> name         datetime64[ns]
> x                   float64
> y                   float64
  

  
It is worth to note that:  
1. when running with `dask engine=fastparquet` the categorical column is preserved.  
2. when reading the parquet file directly with `pandas engine=pyarrow` the categorical column is preserved.

**Comment by TomAugspurger** [comment] 2019-12-05 12:49
Thanks for the report. Can you reproduce this issue when writing / reading using pandas or PyArrow directly? Or is it just with Dask?

**Comment by sephib** [comment] 2019-12-05 14:17
>     2. when reading the parquet file directly with `pandas engine=pyarrow` the categorical column is preserved.

When using `pandas` there is no problem.

Also we used `PyArrow` directly (`read_table/write_table') and the dtype was successfully preserved. Thus it seams only an issue with `dask` implementation.

**Comment by TomAugspurger** [comment] 2019-12-06 22:39
Thanks for confirming. cc @rjzamora if you have a chance to take a look next week.

**Comment by rjzamora** [comment] 2019-12-09 03:06
Thanks for raising @sephib - You are correct.  We don't seem to be using the dtype information stored in the pandas metadata.  Therefore, the type isn't corrected to  categorical until you call `compute()`, etc.  This is definitely something we should be able to fix.

In the mean time, you can still read categorical data *correctly* if you explicitly specify the categorical columns in the `read_parquet` command.   This is likely the reason we haven't bothered auto-detect the categorical columns so far. For example:

```python
df.to_parquet('test_parq', engine='pyarrow')
dff = dd.read_parquet('test_parq', engine='pyarrow', categories=["name"])
dff.dtypes  
```
**Out**:
```
id         int64
name    category
x        float64
y        float64
dtype: object
```

**Comment by sephib** [comment] 2019-12-09 07:33
Thx for the work around.

**Comment by TomAugspurger** [comment] 2019-12-09 14:43
We'll keep this open till #5690 is merged.

**Closed** 2019-12-10 19:36 UTC
