### ISSUE TITLE
Remove test code in apply_along_axis

### ISSUE THREAD

**Issue by zqwei** [dask/dask#3829] opened 2018-07-31 03:24 UTC
I tried to use dask.apply_along_axis to do `interp.make_lsq_spline` over some axis. It always returns some mismatch error of the data dimension which turns out related to the test block in the code. What is the reason for having these codes?

https://github.com/dask/dask/blob/b341ac841234cb06c170c7af0fc65b2827be2cef/dask/array/routines.py#L323-L325

should not comment out in future?

**Comment by d-v-b** [comment] 2018-07-31 20:56
This test exists so dask can guess the output dtype and shape. I agree that the test case is not idea for functions like smoothing filters. I think the original thought behind `apply_along_axis` was for applying functions like `mean` or `max` etc that don't preserve the shape of the input, hence the minimal test. A PR is in the works (https://github.com/dask/dask/pull/3742) that should address this.

**Comment by jakirkham** [comment] 2018-08-02 17:53
Should we close and continue the conversation in issue ( https://github.com/dask/dask/issues/3727 )? Seems like this is a duplicate of that issue.

**Comment by d-v-b** [comment] 2018-08-02 17:58
yes i think so

**Comment by jakirkham** [comment] 2018-08-02 18:03
Thanks for the report @zqwei. Feel free to join the discussion in issue ( https://github.com/dask/dask/issues/3727 ).

**Closed** 2018-08-02 18:03 UTC
Labels: array
