### ISSUE TITLE
Read the docs show an error page for documentation

### ISSUE THREAD

**Issue by mitar** [dask/dask#2446] opened 2017-06-09 07:57 UTC
I am trying to open http://dask.pydata.org/en/latest/ and I get:

SORRY
This page does not exist yet.

**Comment by mrocklin** [comment] 2017-06-09 10:04
I've been running into this as well recently.  Refreshing a few times seems to get it to a decent state.  

Clearly something weird is going on though.  I'll ask around.

**Comment by mrocklin** [comment] 2017-06-09 10:15
Thank you for raising this as an issue by the way

**Comment by Joshuaalbert** [comment] 2017-06-09 12:35
I'm also getting this for many pages on the docs.

**Comment by aterrel** [comment] 2017-06-09 14:24
so now cloudflare is in between the user and readthedocs. Not sure what the issue is but there could be some problem with the cacheing. I do see this happen like 1 out of 10 refreshes.

**Comment by aterrel** [comment] 2017-06-09 14:28
I've turned off the cloudflare proxy (so now https will appear insecure). It sometimes takes a day for all the caches to clear appropriately. Let's leave it off and see if the problem persists

**Comment by mrocklin** [comment] 2017-06-09 20:45
This appears to also be affecting http://distributed.readthedocs.io

Oddly I can't get other non-dask websites to reproduce this behavior.

**Comment by aterrel** [comment] 2017-06-10 14:48
Looks like it wasn't cloudflare. I've turned the proxy back on.

**Comment by jcrist** [comment] 2018-01-30 00:48
This is no longer an issue. Closing.

**Closed by jcrist** 2018-01-30 00:48 UTC
