### ISSUE TITLE
dask parallel backend for sklearn GridSearchCV not working

### ISSUE THREAD

**Issue by ramanan-subramanian** [dask/dask#4511] opened 2019-02-20 01:36 UTC
The first `fit()` call to `GridSearchCV` works fine, but with dask parallel backend, it is stuck eternally. Reproducible example:

```import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

from sklearn.datasets import make_classification

from sklearn.externals import joblib
from dask.distributed import Client

client = Client('localhost:8786')

X, y = make_classification(1000, 10, random_state=42)

clf = Pipeline([('impute', SimpleImputer()),
                ('scale', StandardScaler()),
                ('model', LogisticRegression())])

param_grid = {'model__penalty': ['l1', 'l2'], 
              'model__solver': ['newton-cg', 'lbfgs']}

gscv = GridSearchCV(clf, param_grid, cv=3, verbose=10, error_score=np.nan)

gscv.fit(X, y)

with joblib.parallel_backend('dask'):
    gscv.fit(X, y)

**Comment by TomAugspurger** [comment] 2019-02-20 02:38
What’s happening on the dashboard during the fit?

Do you have workers?

**Comment by ramanan-subramanian** [comment] 2019-02-20 03:37
Hi @TomAugspurger ,

The dashboard shows two jobs stuck in memory forever. (`_fit_and_score-batch`). On the task stream, I can see one `deserialize-_fit_and_score-batch`, two `logistic_regression` tasks, and two `_fit_and_score` jobs. None of the workers are busy in terms of CPU or memory usage.

I have one scheduler + four workers running in a server on premises. I am connecting through a client. The scheduler and workers are containers spawned from the same docker image. The client is also run from a container spawned from the same docker image. Below is what we see on the logs of one worker. The other workers did not produce anything on the console other than the initial startup messages:

```
\\+ '[' '' ']'
+ '[' -e /opt/app/environment.yml ']'
+ echo 'no environment.yml'
no environment.yml
+ '[' '' ']'
+ '[' '' ']'
+ dask-worker localhost:8786
distributed.nanny - INFO -         Start Nanny at: 'tcp://127.0.0.1:38153'
distributed.worker - INFO -       Start worker at:      tcp://127.0.0.1:38345
distributed.worker - INFO -          Listening to:      tcp://127.0.0.1:38345
distributed.worker - INFO -              nanny at:            127.0.0.1:38153
distributed.worker - INFO -              bokeh at:            127.0.0.1:37561
distributed.worker - INFO - Waiting to connect to:       tcp://localhost:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                         16
distributed.worker - INFO -                Memory:                   67.25 GB
distributed.worker - INFO -       Local Directory:           /worker-m72b4cmv
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:       tcp://localhost:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
[CV] model__penalty=l2, model__solver=newton-cg ......................
[CV]  model__penalty=l2, model__solver=newton-cg, score=0.8562874251497006, total=   0.1s
[CV] model__penalty=l2, model__solver=newton-cg ......................
[CV]  model__penalty=l2, model__solver=newton-cg, score=0.8348348348348348, total=   0.0s

```

On the client side, it get stuck with the following:

```
In [8]: with joblib.parallel_backend('dask'): 
   ...:     gscv.fit(X, y) 
   ...:                                                                                                                                                                                                     
Fitting 3 folds for each of 2 candidates, totalling 6 fits
[Parallel(n_jobs=-1)]: Using backend DaskDistributedBackend with 64 concurrent workers.
```

**Comment by TomAugspurger** [comment] 2019-02-20 12:01
And you have the same versions of scikit-learn, dask, and distributed on all those machines? `client.check_versions()`

**Comment by ramanan-subramanian** [comment] 2019-02-20 12:46
Yes, I have checked it with the command you specified. Plus, as I had stated, they are all spawned from the same docker image.

**Comment by ramanan-subramanian** [comment] 2019-02-25 05:22
Hi,
Is there any update on the issue? Hoping it can be resolved.

**Comment by TomAugspurger** [comment] 2019-02-25 11:31
Unfortunately, we don't have much information to go off of to determine what the issue is. You may be in the best place to debug this.

Have you tried with a  LocalCluster, instead od an existing cluster? Have you tried with different versions of scikit-learn, distributed, and dask?  Have you ensured that your package versions match? Have you looked through the worker logs (possibly with DEBUG level)? Have you tried with a simpler model?

**Comment by ramanan-subramanian** [comment] 2019-02-25 11:56
Thanks for the additional suggestions. I did really do the version check and it  passes without problwms. Will try the LocalCluster and the other ones today. Looking for help here since we desperately need to get it to work to parallelise sklearn on the cloud.

I am using sklearn version 0.20.2 (latest stable release). Should I try with a lower one i.e. 0.18 or something similar?

Also, I would like to know if the reproducible example I provided works for anybody here.

I

**Comment by TomAugspurger** [comment] 2019-02-25 12:02
The example you provided works for me when

1. I add an `import numpy as np`
2. I remove the scheduler address when creating the Client (to use a newly
created LocalCluster)

I don't think downgrading scikit-learn that far would be helpful. It would
require also downgrading dask and distributed, and changing your imports.

**Comment by ramanan-subramanian** [comment] 2019-02-25 22:57
> The example you provided works for me when 1. I add an `import numpy as np` 2. I remove the scheduler address when creating the Client (to use a newly created LocalCluster) 

I tried your changes above and it worked as you stated, but just once. I then re-issued the GridSearchCV from the same interactive python session, and it gets stuck after one or two fits:

```
Fitting 3 folds for each of 4 candidates, totalling 12 fits
[Parallel(n_jobs=-1)]: Using backend DaskDistributedBackend with 2 concurrent workers.
[CV] model__penalty=l1, model__solver=newton-cg ......................
/home/ramanan/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py:559: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver newton-cg supports only l2 penalties, got l1 penalty.

  FitFailedWarning)
[CV]  model__penalty=l1, model__solver=newton-cg, score=nan, total=   0.0s
```

**Comment by afzalmushtaque** [comment] 2019-03-24 08:36
I have the exact same problem; worker gets stuck after two fits with no error messages.
Here's a link to a github [repo](https://github.com/afzalmushtaque/dask_distributed) with reproducible example.
I have used an example from the dask-ml doc page [here](https://dask-ml.readthedocs.io/en/latest/joblib.html).

**Comment by afzalmushtaque** [comment] 2019-03-24 13:18
I fixed my issue by changing 
from **sklearn**.model_selection import RandomizedSearchCV
to
from **dask_ml**.model_selection import RandomizedSearchCV

**Comment by quancore** [comment] 2019-05-11 20:21
I am facing a similar issue on dask-yarn. See: https://github.com/dask/dask-yarn/issues/64

**Comment by quancore** [comment] 2019-05-13 20:06
Bump for the issue about resolution other than changing function. This issue also occurs in cross_val_score in sklearn.

**Comment by mrocklin** [comment] 2019-05-13 20:09
@quancore you may not be aware, but the behavior of "bumping" an issue can be seen as somewhat rude.  It gives the impression that you think that it is someone's job to solve these problems for you.   As an OSS project, this is as much your responsibility as anyone's.

If you have something constructive to add to the conversation then please participate.  If you are willing to contribute a solution then that would be great.

**Comment by mrocklin** [comment] 2019-05-13 20:10
http://matthewrocklin.com/blog/work/2016/08/25/supporting-users

**Comment by TomAugspurger** [comment] 2019-08-09 15:59
It's possible this is fixed by https://github.com/joblib/joblib/pull/914.

Let us know if it's still an issue.

**Closed by TomAugspurger** 2019-08-09 15:59 UTC

**Comment by pranav-kohli** [comment] 2019-11-15 11:09
I am having the exact same issue. I had raised a separate issue here
https://github.com/dask/dask/issues/5567
But closed this because xgboost upgrade seemed to solve the problem but its now back.
Dask workers get stuck while fitting an xgboost model
<img width="1434" alt="Screenshot 2019-11-15 at 4 38 01 PM" src="https://user-images.githubusercontent.com/9332650/68939392-84229780-07c6-11ea-8509-36da20c59a1e.png">
<img width="1440" alt="Screenshot 2019-11-15 at 4 38 16 PM" src="https://user-images.githubusercontent.com/9332650/68939394-84229780-07c6-11ea-9a58-cacb7ec7481f.png">





joblib : 0.14.0
