### ISSUE TITLE
Unbounded memory usage in tensordot

### ISSUE THREAD

**Issue by tomwhite** [dask/dask#6916] opened 2020-12-01 09:50 UTC
**What happened**:

Following #6846 the memory usage of `tensordot` (and `dot`, which delegates to `tensordot` in Dask) is much higher than before, and grows as a function of array size.

**What you expected to happen**:

The memory usage should be related to chunk size (as it was previously), not the size of the array. This was achieved previously by avoiding `concatenate=True` in the call to `blockwise` from `tensordot`. As a general rule, `concatenate=True` should be avoided since it causes these memory issues for very large inputs.

**Minimal Complete Verifiable Example**:

The "Multiplication Only" part of [this notebook](https://gist.github.com/eric-czech/daae30d54a5c96fd09f13ffa58a3bafe) - with `X.T @ Y` replaced with `da.dot(X.T, Y)` - demonstrates the problem. The memory usage should be flat, not growing with the size of the array.

**Anything else we need to know?**:

#6874 is a related issue that aims to remove the same memory issue from `matmul`.

**Environment**:

- Dask version: latest head (unreleased)
- Python version: 3.7.6
- Operating System: MacOS
- Install method (conda, pip, source): source

**Comment by zklaus** [comment] 2020-12-01 17:55
Note that there seems to have been a hidden bug in dask's tensordot for a long time that was coincidentally resolved by #6846. For a few more details see #6907.

**Comment by jakirkham** [comment] 2020-12-03 01:29
Good to know. Maybe we should include a test then? Would you be willing to submit a PR? 🙂

**Comment by ravwojdyla** [comment] 2020-12-03 17:05
From https://github.com/dask/dask/pull/6846#issuecomment-735763407:

> We could have a special case for sparse array (based on type) that introduces the contraction in _tensordot only for sparse arrays? But I wonder if there is a more generic solution 🤔

Afaiu https://github.com/dask/dask/pull/6924 also adds a special case but just for {1,2}d. Should I give it a try to produce a PR for the sparse array special case, to compare? Wdyt @tomwhite and the rest?

**Comment by zklaus** [comment] 2020-12-04 18:15
> Good to know. Maybe we should include a test then? Would you be willing to submit a PR? slightly_smiling_face

I would. The problem is that I am not completely sure what is going on. In
```python
x = da.random.random((4,4), chunks=(2,2))
x[x < 0.65] = 0
y = x.persist()
r1 = da.dot(x, x).compute()
r2 = da.dot(y, y).compute()
```
`r1` is wrong and `r2` is correct (with a dask version prior to fbccc4ef3e1974da2b4a9cb61aa83c1e6d61efba). This is not due to special values; when I take the problematic values and create an array from a numpy array with them, the problem does not occur. The problem is also not with the (tensor)dot implementation of the blocks, but rather that they get fed wrong blocks. But I was not able yet to track down why and therefore I am not sure how to set up the test. I think having `random` stuff in tests should rather be avoided.

What do you think? Include a test with random as above? Track down the problem in more detail before writing the test?

**Comment by mrocklin** [comment] 2020-12-04 20:00
Can I ask folks to try this with the single-threaded scheduler `.compute(scheduler="single-threaded")`

If it's fine there then I suspect that this is the numpy/glibc threaded leak issue.

**Comment by zklaus** [comment] 2020-12-04 20:05
Sorry I didn't mention this here before, but in the full script I had a `dask.config.set(scheduler='single-threaded')` at the beginning, so the error does occur with the single-threaded scheduler. (I now edited the snippet above to include the scheduler change.)

**Comment by mrocklin** [comment] 2021-08-03 02:23
@GenevieveBuckley and I ran into this today.  My apologies for only understanding what had happened until now.

Short term, we can revert the previous change.  I think that tensordot on numpy is more important than tensordot on *sparse.

A solution that it a little better would be to look at the `_meta` of the input arrays and special casing those with sparse in the type name.

However a best solution would be to find a way to use the `sum` trick with sparse arrays.  I think that this trick is necessary for memory efficient operation at large scale.

**Comment by mrocklin** [comment] 2021-08-03 02:24
I think that @GenevieveBuckley is taking a look at this now.  Genevieve, I recommending spending an hour or two to see if you can respect the current concatenate choice for sparse arrays, and if not then just revert the previous commit.

**Comment by GenevieveBuckley** [comment] 2021-08-03 02:41
Yes, I am looking at it (well, eating lunch and then back to it). What you've commented above is what I had in mind. I think it should be relatively straightforward to keep the current situation with sparse arrays, and use sum for other array types. Once that's done we can look at a better long term plan using the sum trick for sparse arrays too.

**Comment by dcherian** [comment] 2022-03-24 09:39
I think this can be closed now.

**Closed** 2022-04-01 13:53 UTC
Labels: array
