### ISSUE TITLE
Dask Crashes While Loading Very Large Line Limited JSON Files

### ISSUE THREAD

**Issue by Srj** [dask/dask#7614] opened 2021-04-27 19:58 UTC
**What happened**:
I have 5 .jsonl files which is each of 3 GB. I tried to load them with dask bag apply json.loads function ,convert them to dataframe and save as parquet. ( I will have an process function applied before converting to dask anyways) . But it crashes all the time. I tried with 1 to 8 worker, repartitioning to 1024 . But it always crashes. I have 16 GB of memory. Can anyon say what is wrong?

**What you expected to happen**:

**Minimal Complete Verifiable Example**:

```python

# @dask.delayed  !!!Tried
def json_load(line):
    try:
        return json.loads(line)
    except:
        return None

bg = db.read_text(os.path.join('*.jsonl'))
# bg = bg.repartition(npartitions = 128)  !!!!Tried
bg = bg.map(json_load)
bg = bg.to_dataframe()
# bg = bg.to_dataframe().repartition(npartitions=128)  !!!!Tried
bg.to_parquet('*.parquet',engine='pyarrow')

```

**Anything else we need to know?**:
I tried to predict the behaviour from dashboard. It seems it tries to load all 5 file at once instead of loading a chunk, process , save and continue. What am i missing?

**Environment**:

- Dask version: 2021.04.1
- Python version: 3.9
- Operating System: Fedora
- Install method (conda, pip, source): conda

**Comment by Srj** [comment] 2021-04-28 09:07
Okay. It seems like the problem is with read_text where i have to pass an argument blocksize to limit the loading of file into memory, otherwise it try to read the whole file at once. 

```Python
bg = db.read_text(os.path.join('*.jsonl'),blocksize=1e6) #Read 1 MB block
```

**Comment by jrbourbeau** [comment] 2021-04-29 18:35
Thanks for raising an issue @Srj. As you mentioned, `read_text` will read in each file into its own partition by default. Can you post a traceback of the `repartition` crash? Additionally, if you're able to provide a minimal, reproducible example (see https://blog.dask.org/2018/02/28/minimal-bug-reports) that will go a long way towards helping debug

**Comment by Srj** [comment] 2021-04-29 19:12
````python
def json_load(line):
    try:
        return json.loads(line)
    except:
        return None

bg = db.read_text('*.jsonl',blocksize=1e6)      #16 GB Tweet Data
bg = bg.repartition(npartitions = 128)    """!!! Crashes for this line. Runs fine without it."""
bg = bg.map(json_load).filter(bool)
bg = bg.to_dataframe()
bg = bg[['id_str']].repartition(npartitions=128)   # Saving only tweet id for simplicity
bg.to_hdf('t.hdf','*')
````

System Ram : 16 GB
OS : Fedora
 There is no traceback to show as my whole system crashes after processing around 30-40% data  (Seen from Dask Dashboard).

**Comment by ncclementi** [comment] 2021-08-11 16:49
@Srj Are you still having this problem in Dask 2021.07.2? If so, a minimal reproducible example that we can run would be helpful. The example that you show us unfortunately is not reproducible since we don't have the data available.

**Comment by ncclementi** [comment] 2021-08-20 14:48
Closing this one due to the lack of info, @Srj  if you still having this issue please feel free to re-open with a minimal reproducible example so we can help you.

**Closed by ncclementi** 2021-08-20 14:48 UTC
Labels: bag, needs info
