### ISSUE TITLE
Failure with upstream pandas

### ISSUE THREAD

**Issue by xhochy** [dask/dask#7610] opened 2021-04-27 14:20 UTC
In Kartothek we are seeing some failures with `dask` (master and `2021.4.0`) and the latest `pandas` nightly https://github.com/JDASoftwareGroup/kartothek/issues/464 We could trim this down to the following minimal example that is solely using `dask`:

```python
import dask
import dask.dataframe as dd
import pandas as pd
import uuid

dd.from_pandas(
    pd.DataFrame(
        {
            "primary": [3, 1, 2, 0, 2, 1, 3, 0, 1, 2, 0, 3, 0, 1, 3, 2, 0, 2, 1, 3],
            "__KTK_HASH_BUCKET": 0,
        }
    ),
    chunksize=4,
).groupby(["primary", "__KTK_HASH_BUCKET"]).apply(
    lambda x: uuid.uuid4(), meta=object
).reduction(chunk=lambda x:x).compute()
```

With the latest `pandas=1.2.4` release I get the following output on 

```
                                      0                                     1                                     2                                     3
                                      0                                     0                                     0                                     0
0                                   NaN  f07f221b-1805-4c3d-9217-a9feef05a161                                   NaN                                   NaN
0                                   NaN                                   NaN  5b1d7f5a-ea84-47f3-88ca-c3cd4fbfe387  0619a818-600b-4a63-b45e-0a7d3e3f1506
0                                   NaN                                   NaN                                   NaN                                   NaN
0                                   NaN                                   NaN                                   NaN                                   NaN
0  1c361993-3317-4ac8-9f6a-b3f2979653dc                                   NaN                                   NaN                                   NaN
```

Using `pandas` master since https://github.com/pandas-dev/pandas/pull/38671, I get the following error with `dask=2021.4.0` (on master I get a different, unrelated error)

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-1-590c5f42c74d> in <module>
      4 import uuid
      5 
----> 6 dd.from_pandas(
      7     pd.DataFrame(
      8         {

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/base.py in compute(self, **kwargs)
    282         dask.base.compute
    283         """
--> 284         (result,) = compute(self, traverse=False, **kwargs)
    285         return result
    286 

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/base.py in compute(*args, **kwargs)
    564         postcomputes.append(x.__dask_postcompute__())
    565 
--> 566     results = schedule(dsk, keys, **kwargs)
    567     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    568 

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/threaded.py in get(dsk, result, cache, num_workers, pool, **kwargs)
     77             pool = MultiprocessingPoolExecutor(pool)
     78 
---> 79     results = get_async(
     80         pool.submit,
     81         pool._max_workers,

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/local.py in get_async(submit, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, chunksize, **kwargs)
    512                             _execute_task(task, data)  # Re-execute locally
    513                         else:
--> 514                             raise_exception(exc, tb)
    515                     res, worker_id = loads(res_info)
    516                     state["cache"][key] = res

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/local.py in reraise(exc, tb)
    323     if exc.__traceback__ is not tb:
    324         raise exc.with_traceback(tb)
--> 325     raise exc
    326 
    327 

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/local.py in execute_task(key, task_info, dumps, loads, get_id, pack_exception)
    221     try:
    222         task, data = loads(task_info)
--> 223         result = _execute_task(task, data)
    224         id = get_id()
    225         result = dumps((result, id))

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/core.py in <genexpr>(.0)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    113     """
    114     if isinstance(arg, list):
--> 115         return [_execute_task(a, cache) for a in arg]
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/core.py in <listcomp>(.0)
    113     """
    114     if isinstance(arg, list):
--> 115         return [_execute_task(a, cache) for a in arg]
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/core.py in _execute_task(arg, cache, dsk)
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/dataframe/core.py in _concat(args, ignore_index)
    101         args[0]
    102         if not args2
--> 103         else methods.concat(args2, uniform=True, ignore_index=ignore_index)
    104     )
    105 

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/dataframe/methods.py in concat(dfs, axis, join, uniform, filter_warning, ignore_index, **kwargs)
    427     else:
    428         func = concat_dispatch.dispatch(type(dfs[0]))
--> 429         return func(
    430             dfs,
    431             axis=axis,

~/mambaforge/envs/kartothek/lib/python3.9/site-packages/dask/dataframe/methods.py in concat_pandas(dfs, axis, join, uniform, filter_warning, ignore_index, **kwargs)
    565                 if filter_warning:
    566                     warnings.simplefilter("ignore", FutureWarning)
--> 567                 out = pd.concat(dfs3, join=join, sort=False)
    568     else:
    569         if is_categorical_dtype(dfs2[0].dtype):

~/Development/pandas/pandas/core/reshape/concat.py in concat(objs, axis, join, ignore_index, keys, levels, names, verify_integrity, sort, copy)
    284     ValueError: Indexes have overlapping values: ['a']
    285     """
--> 286     op = _Concatenator(
    287         objs,
    288         axis=axis,

~/Development/pandas/pandas/core/reshape/concat.py in __init__(self, objs, axis, join, keys, levels, names, ignore_index, verify_integrity, copy, sort)
    464         self.copy = copy
    465 
--> 466         self.new_axes = self._get_new_axes()
    467 
    468     def get_result(self):

~/Development/pandas/pandas/core/reshape/concat.py in _get_new_axes(self)
    534     def _get_new_axes(self) -> List[Index]:
    535         ndim = self._get_result_dim()
--> 536         return [
    537             self._get_concat_axis if i == self.bm_axis else self._get_comb_axis(i)
    538             for i in range(ndim)

~/Development/pandas/pandas/core/reshape/concat.py in <listcomp>(.0)
    535         ndim = self._get_result_dim()
    536         return [
--> 537             self._get_concat_axis if i == self.bm_axis else self._get_comb_axis(i)
    538             for i in range(ndim)
    539         ]

~/Development/pandas/pandas/core/reshape/concat.py in _get_comb_axis(self, i)
    541     def _get_comb_axis(self, i: int) -> Index:
    542         data_axis = self.objs[0]._get_block_manager_axis(i)
--> 543         return get_objs_combined_axis(
    544             self.objs,
    545             axis=data_axis,

~/Development/pandas/pandas/core/indexes/api.py in get_objs_combined_axis(objs, intersect, axis, sort, copy)
     90     """
     91     obs_idxes = [obj._get_axis(axis) for obj in objs]
---> 92     return _get_combined_index(obs_idxes, intersect=intersect, sort=sort, copy=copy)
     93 
     94 

~/Development/pandas/pandas/core/indexes/api.py in _get_combined_index(indexes, intersect, sort, copy)
    143             index = index.intersection(other)
    144     else:
--> 145         index = union_indexes(indexes, sort=sort)
    146         index = ensure_index(index)
    147 

~/Development/pandas/pandas/core/indexes/api.py in union_indexes(indexes, sort)
    215         else:
    216             for other in indexes[1:]:
--> 217                 result = result.union(other)
    218             return result
    219     elif kind == "array":

~/Development/pandas/pandas/core/indexes/base.py in union(self, other, sort)
   2705                 unpack_nested_dtype(other)
   2706             ):
-> 2707                 raise NotImplementedError(
   2708                     "Can only union MultiIndex with MultiIndex or Index of tuples, "
   2709                     "try mi.to_flat_index().union(other) instead."

NotImplementedError: Can only union MultiIndex with MultiIndex or Index of tuples, try mi.to_flat_index().union(other) instead.
```

cc @jorisvandenbossche for the `pandas` side. I'm not sure whether `dask` is doing weird things here or whether `pandas` has a regression.

**Comment by jorisvandenbossche** [comment] 2021-04-27 15:40
A reproducer with just pandas:

```
df1 = pd.DataFrame([[1, 2]], columns=pd.MultiIndex.from_tuples([('B', 1), ('C', 1)]))
df2 = pd.DataFrame(index=[0], columns=pd.RangeIndex(0))

pd.concat([df1, df2])
```

What triggers the error here is the `columns=pd.RangeIndex(0)` for the empty `df2` (by default pandas creates a zero-length object dtype Index, which works fine, but if it's an empty RangeIndex, we now get this error). 

This is a regression in itself in pandas. But I am also wondering a bit where the empty RangeIndex is coming from (it seems that the groupby operation in dask results in some empty partitions)

**Comment by mlondschien** [comment] 2021-04-28 12:35
IIUC this can be traced to this example:

```
In [1]: import pandas as pd 
   ...: import dask.dataframe as dd 
   ...:  
   ...: df = pd.DataFrame({"a": [0, 0], "b": [1, 2]}) 
   ...:  
   ...: dsk = { 
   ...: ^I("from_pandas", 0): (df), 
   ...: ^I("from_pandas", 1): (df.iloc[:0]) 
   ...: } 
   ...:  
   ...: ddf_1 = dd.DataFrame(dsk=dsk, name="from_pandas", meta=df, divisions=(0,
   ...:  2, 2)) 
   ...:  
   ...: ddf_2 = ddf_1.map_partitions(dd.groupby._groupby_slice_apply, ["a", "b"]
   ...: , None, lambda x: 1, meta="foo") 
   ...:  
   ...: ddf_2.to_delayed()[1].compute().index
Out[1]: RangeIndex(start=0, stop=0, step=1)
```
Note that this must have something to do with the `meta` kwarg to `map_partitions`:
```
In [2]: ddf_2 = ddf_1.map_partitions(dd.groupby._groupby_slice_apply, ["a", "b"]
   ...: , None, lambda x: 1) 
   ...:  
   ...: ddf_2.to_delayed()[1].compute().index                                   
Out[2]: MultiIndex([], names=['a', 'b'])
```

**Comment by mlondschien** [comment] 2021-04-29 10:16
This line

https://github.com/dask/dask/blob/bcb2fcabdf9b2ca510162119a806671af5111939/dask/dataframe/core.py#L5565

assumes that the output of `map_partitions` has the same index as the input. 

These lines

https://github.com/dask/dask/blob/bcb2fcabdf9b2ca510162119a806671af5111939/dask/dataframe/utils.py#L352-L364

ignore the `index` argument if `x` is a scalar.

This (not so pretty) draft PR fixes the above failure:
https://github.com/dask/dask/pull/7619

**Comment by jsignell** [comment] 2021-04-29 15:12
There is a line in the docs that makes this assumption explicit: 

> Note that the index and divisions are assumed to remain unchanged. - [source](https://github.com/dask/dask/blob/bcb2fcabdf9b2ca510162119a806671af5111939/dask/dataframe/core.py#L592:L592)

I am not sure if we want to change that requirement in dask.

**Comment by mlondschien** [comment] 2021-04-29 16:10
Then maybe the issue lies here:
https://github.com/dask/dask/blob/bcb2fcabdf9b2ca510162119a806671af5111939/dask/dataframe/groupby.py#L1699-L1700
The function `_groupby_slice_apply` sets a new index (it's a `groupby`).

**Comment by mlondschien** [comment] 2021-04-30 12:10
IIUC to fix this we need to either implement `groupby.apply` differently (without using `map_partitions`) or allow `map_partitions` to return different indices (and then get the `meta_index` right). Is there another option? My understanding of the inner workings of dask is rather limited. What is your understanding and opinion on this @jsignell?

**Comment by jsignell** [comment] 2021-04-30 18:43
Sorry I got derailed yesterday you are totally right I think we abuse `map_partitions` a bit within dask. I am hesitant about your original approach because it involves calling the function before compute even if the user passes `meta`. This feels odd to me, but I can't think of a better solution.

**Comment by jsignell** [comment] 2021-04-30 20:02
Regarding the original example I think @jorisvandenbossche is on the right track about the empty partitions. You'll notice that you get a reasonable output if you change the reduction to:

```python
.reduction(chunk=lambda x: x if len(x) else [])
```

**Comment by mlondschien** [comment] 2021-05-03 05:07
> I am hesitant about your original approach because it involves calling the function before compute even if the user passes meta. This feels odd to me, but I can't think of a better solution.

I agree. The solution is a bit clunky.

> Regarding the original example I think @jorisvandenbossche is on the right track about the empty partitions

Yes, as can also be seen from the example I posted above. I have opened https://github.com/pandas-dev/pandas/issues/41234 to track this. If this was fixed, this would resolve @xhochy's original issue. However it will not solve that an empty partition after a groupby has the wrong index (an empty `RangeIndex` instead of an empty `MultiIndex`). I am not sure whether this is a problem in general, however I could imagine this leading to other bugs / issues in the future.

I can have another go and try to resolve this more neatly.

**Comment by jsignell** [comment] 2021-05-03 13:23
> However it will not solve that an empty partition after a groupby has the wrong index (an empty `RangeIndex` instead of an empty `MultiIndex`).

Yeah I think this is likely a general problem that just hasn't been noticed since it didn't fail. I think one potential solution could be to discard empty partitions rather than acting on them. This seems like it might be more expected behavior. 

> I can have another go and try to resolve this more neatly.

That would be great! If you can get the tests passing that'd be a good first step.

**Comment by jrbourbeau** [comment] 2021-06-11 14:07
It looks like https://github.com/pandas-dev/pandas/pull/41275 fixed the original issue posted by @xhochy https://github.com/JDASoftwareGroup/kartothek/issues/464 (thanks @mlondschien!). @mlondschien are you still running into the groupby issue? Is this something you'd be interested in working on? (no obligation though)

**Comment by mlondschien** [comment] 2021-06-14 06:23
No. We only ran into the groupby issue through https://github.com/JDASoftwareGroup/kartothek/issues/464. https://github.com/pandas-dev/pandas/pull/41275 is suffient to fix this.

To properly address the issue that `groupby` does not return the correct index for multiindices, we should rewrite the `groupby` to no longer make use of `map_partitions` or make `map_partitions` more flexible and allow it to return a separate index ([above](https://github.com/dask/dask/issues/7610#issuecomment-830050325)). Though this should be a separate issue and tackled by someone with more in depth experience of dask.

**Comment by jsignell** [comment] 2021-11-05 17:13
Ok I'm going to close this since the issue is resolved.

**Closed** 2021-11-09 15:27 UTC
Labels: dataframe, upstream
