### ISSUE TITLE
Memory leak with dask versions greater than  2021.03.1

### ISSUE THREAD

**Issue by AliceBalfanz** [dask/dask#7748] opened 2021-06-02 14:45 UTC
**What happened**:

Memory Error occurs with dask and dask-core versions greater than `2021.03.1`.

**What you expected to happen**:

I would expect no Memory Errors with versions greater than `2021.03.1`

**Minimal Complete Verifiable Example**:
I am reading an array from a zarr file, and then compute its mean. With dask version `2021.03.1` this is not an issue, when using versions greater than `2021.03.1` the process terminates with a memory error. 

with dask version `2021.03.1` 
![image](https://user-images.githubusercontent.com/23457217/120494523-2c557c80-c3bc-11eb-8b89-17837f117bce.png)

with dask version `2021.04.0` 
![image](https://user-images.githubusercontent.com/23457217/120494583-3aa39880-c3bc-11eb-926c-93db502608ce.png)

```
from dask.diagnostics import ProgressBar
import dask.array as da
import dask

# print version of dask
dask.__version__

ESDC_hi_cfc = da.from_zarr("https://s3.eu-central-1.amazonaws.com/esdl-esdc-v2.1.1/esdc-8d-0.083deg-1x2160x4320-2.1.1.zarr/cfc")

# take a look at the array
ESDC_hi_cfc

# compute mean 
with ProgressBar():
    CFC_globalmean = ESDC_hi_cfc.mean().compute()
```

**Anything else we need to know?**:

**Environment**:

- Dask version: Memory issue with all versions greater than `2021.03.1`
- Python version: `3.9.4`
- Operating System: Linux
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment] 2021-06-02 14:49
Thanks for reporting @AliceBalfanz. This might be a duplicate of https://github.com/dask/dask/issues/7583. Could you try using a local distributed cluster instead of the default multi-threaded scheduler? That is, put

```python
from dask.distributed import Client
client = Client()
```

at the beginning of your notebook

**Comment by pont-us** [comment] 2021-06-02 14:51
I tried the test code as a command-line script on a system with 13.6 GB RAM available to confirm that the problem is due to an OOM error:

```
$ /usr/bin/time ./dasktest.py 
2021.04.1
dask.array<from-zarr, shape=(1840, 2160, 4320), dtype=float32, chunksize=(1, 2160, 4320), chunktype=numpy.ndarray>
[#####                                   ] | 13% Completed | 32.8sCommand terminated by signal 9
8.70user 49.05system 0:35.04elapsed 164%CPU (0avgtext+0avgdata 13250948maxresident)k
183880inputs+0outputs (1254major+1787235minor)pagefaults 0swaps
$ echo $?
137
```

Relevant dmesg entries:

```
[30853.530398] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/user@1000.service,task=python,pid=26900,uid=1000
[30853.530460] Out of memory: Killed process 26900 (python) total-vm:29909480kB, anon-rss:13090252kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:54740kB oom_score_adj:0
[30854.307902] oom_reaper: reaped process 26900 (python), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

On a system with 112 GB available, the script completed successfully, having consumed about 66 GB:

```
$ /usr/bin/time -v ./dasktest.py
2021.05.0
dask.array<from-zarr, shape=(1840, 2160, 4320), dtype=float32, chunksize=(1, 2160, 4320), chunktype=numpy.ndarray>
[########################################] | 100% Completed | 38.7s
        Command being timed: "./dasktest.py"
        User time (seconds): 48.96
        System time (seconds): 330.76
        Percent of CPU this job got: 938%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:40.45
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 66333548
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 4
        Minor (reclaiming a frame) page faults: 1215262
        Voluntary context switches: 67579
        Involuntary context switches: 3376
        Swaps: 0
        File system inputs: 1864
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
```

**Comment by jrbourbeau** [comment] 2021-06-02 16:41
Thanks for confirming @pont-us. Could you try with the `distributed` scheduler (xref https://github.com/dask/dask/issues/7748#issuecomment-853093517)?

**Comment by pont-us** [comment] 2021-06-03 15:27
@jrbourbeau I've successfully tested on both systems with the `distributed` scheduler. Completed on the smaller machine with about 450 MB RAM used, and about 1.8 GB on the larger machine.

**Closed** 2021-06-03 16:00 UTC
