### ISSUE TITLE
Dask dataframe read_csv error: Could not serialize object of type tuple.

### ISSUE THREAD

**Issue by vaibhavsingh007** [dask/dask#5156] opened 2019-07-24 19:41 UTC
Hi,
Encountered the following error when reading this CSV (https://github.com/h2oai/h2o-tutorials/blob/master/tutorials/data/allyears2k.csv):
**Code**:
```
from dask.distributed import Client
import dask.dataframe as dd
client = Client()
file = "allyears2k.csv"
df = dd.read_csv(file, encoding='latin-1', blocksize=None)
df.head()
```

**Error**:

TypeError: ('**Could not serialize object of type tuple**.', "(<function safe_head at 0x7f5e909f4a60>, (<function check_meta at 0x7f5e90a33c80>, (<function apply at 0x7f5f16e917b8>, <function pandas_read_text at 0x7f5e9099b9d8>, [<function _make_parser_function.<locals>.parser_f at 0x7f5e922f46a8>, (<function read_block_from_file at 0x7f5e911b1488>, <dask.bytes.core.OpenFile object at 0x7f5f14cae4e0>, 0, None, b'\\n'), b'Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,TailNum,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Origin,Dest,Distance,........

It works fine using the following Pandas code: 

```
import pandas as pd
datafile = "allyears2k.csv"
df=pd.read_csv(datafile, encoding='latin-1', dtype='object')
```

Please help.

**Comment by jcrist** [comment] 2019-07-25 15:02
Thanks for filing an issue, I've moved this to `dask/dask` since it has to do with the dask library not the scheduler.

I'm unable to reproduce your issue (note that I had to specify some dtype hints to prevent a different error, but that was it).

```
In [1]: import dask.dataframe as dd

In [2]: from dask.distributed import Client

In [3]: client = Client()

In [4]: ddf = dd.read_csv("allyears2k.csv", encoding="latin-1", dtype={'CRSElapsedTime': 'float64',
   ...:        'CancellationCode': 'object',
   ...:        'Distance': 'float64',
   ...:        'TailNum': 'object'})

In [5]: ddf.head()
Out[5]:
   Year  Month  DayofMonth  DayOfWeek  DepTime  CRSDepTime  ArrTime  CRSArrTime UniqueCarrier  FlightNum TailNum  ...  TaxiOut  Cancelled  CancellationCode  Diverted  CarrierDelay WeatherDelay NASDelay  SecurityDelay  LateAircraftDelay  IsArrDelayed  IsDepDelayed
0  1987     10          14          3    741.0         730    912.0         849            PS       1451     NaN  ...      NaN          0               NaN         0           NaN          NaN      NaN            NaN                NaN           YES           YES
1  1987     10          15          4    729.0         730    903.0         849            PS       1451     NaN  ...      NaN          0               NaN         0           NaN          NaN      NaN            NaN                NaN           YES            NO
2  1987     10          17          6    741.0         730    918.0         849            PS       1451     NaN  ...      NaN          0               NaN         0           NaN          NaN      NaN            NaN                NaN           YES           YES
3  1987     10          18          7    729.0         730    847.0         849            PS       1451     NaN  ...      NaN          0               NaN         0           NaN          NaN      NaN            NaN                NaN            NO            NO
4  1987     10          19          1    749.0         730    922.0         849            PS       1451     NaN  ...      NaN          0               NaN         0           NaN          NaN      NaN            NaN                NaN           YES           YES

[5 rows x 31 columns]
```

What versions of `dask`/`distributed`/`pandas`/`python` are you using? What operating system?

**Comment by vaibhavsingh007** [comment] 2019-07-25 16:02
Hi Jim, thanks for the prompt response. Using the dtype hints didn't help either. Here are the versions you requested. 

Python 3
Pandas 0.25.0
OS: 
sh-4.2$ cat /etc/*release*
NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.6"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.6 (Maipo)"

I just pip installed **dask[complete]** and **dask distributed**. Where can I see the version?

**Comment by jcrist** [comment] 2019-07-25 16:21
Most python libraries have their versions stored as `__version__` on the library:

```python
import dask
import distributed
print(dask.__version__)
print(distributed.__version__)
```

Alternatively you can use `pip list`:

```bash
$ pip list | grep "dask\|distributed\|pandas"
```

**Comment by jcrist** [comment] 2019-07-25 16:23
Generally when writing bug reports you should provide steps to reproduce, including commands run and package versions. See https://blog.dask.org/2018/02/28/minimal-bug-reports.

**Comment by vaibhavsingh007** [comment] 2019-07-25 16:25
2.1.0
2.1.0

**Comment by vaibhavsingh007** [comment] 2019-07-26 13:32
Hi @jcrist 
were you able to replicate the issue? Can you share the version of Python and Dask you are using so I can try those instead?

**Comment by vaibhavsingh007** [comment] 2019-07-30 14:45
Will pass on Dask and revert to Spark until there is better support available. Good luck with your funding.

**Comment by mrocklin** [comment] 2019-07-30 15:18
> Can you share the version of Python and Dask you are using so I can try those instead?

I suspect Python 3.7 and git master.

> Will pass on Dask and revert to Spark until there is better support available. 

Great.  Good luck!  Closing.

See also http://matthewrocklin.com/blog/work/2016/08/25/supporting-users

> Good luck with your funding.

??

**Closed by mrocklin** 2019-07-30 15:18 UTC

**Comment by aprowe** [comment] 2019-09-16 20:24
I am also getting a similar error, with a trivial example:

```python
from dask.distributed import Client
from dask.dataframe import read_csv

if __name__ == '__main__':
    client = Client()
    df = read_csv('test.csv')
    df.compute()
```

test.csv:
```csv
a,b,c
1,2,3
4,5,6
```

This seems like a pretty fundamental error. Is there something I am missing or something wrong with my configuration?

If I create the dataframe in-code, it works:
```
from dask.distributed import Client
from dask.dataframe import from_pandas
import pandas as pd

if __name__ == '__main__':
    client = Client()
    df = from_pandas(pd.DataFrame({
        'a': [1, 4],
        'b': [2, 5],
        'c': [3, 6],
    }), npartitions=1)
    print(df.compute())
```

What could be different between the dataframes?

**Comment by jrbourbeau** [comment] 2019-09-16 20:52
What version of Python and `cloudpickle` are you using? There was recently an issue which was fixed in the most recent `cloudpickle==1.2.2`  release

**Comment by aprowe** [comment] 2019-09-17 15:39
Im on python 3.6.7, cloudpickle 1.2.1
updating to cloudpickle 1.2.2 fixed it, thanks!

**Comment by jsignell** [comment] 2022-06-20 20:32
latest dask is 2022.6.0, so I would recommend updating dask and distributed.
