### ISSUE TITLE
dask merge in distributed mode: 'Buffer' object has no attribute 'memory_usage'

### ISSUE THREAD

**Issue by ankravch** [dask/dask#1360] opened 2016-07-09 10:03 UTC
[akravchenko@hnode1 nfs]$ ipython
Python 3.5.1 |Anaconda custom (64-bit)| (default, Dec  7 2015, 11:16:01)
Type "copyright", "credits" or "license" for more information.

In [1]: import dask.dataframe as dd

In [2]: import pandas as pd

In [3]: import numpy as np

In [4]: import dask, random

In [5]: from datetime import datetime

In [6]:

In [6]: from distributed import Executor

In [7]: e=Executor('192.168.102.220:8786', set_as_default=True)

In [8]:

In [8]: from dask.diagnostics import ProgressBar

In [9]: pbar = ProgressBar()

In [10]: pbar.register()

In [11]: ddgn_pb_r_i = dd.read_hdf(r'/mnt/nfs/ddgn_pb_r_i.h5', 'test', lock=False)

In [12]: ddgn_pb_r_i
Out[12]: dd.DataFrame<read-hd..., npartitions=2>

In [13]: ddgn_pb_r_i.head()
Out[13]:
               CLAIMNO    DGN
DGN
11111  136013369414744  11111
11111  136013337865560  11111
11111  136013325798514  11111
11111  136013350533520  11111
11111  136013332347645  11111

In [14]: ddgn_finder_r_i = dd.read_hdf(r'/mnt/nfs/ddgn_finder_r_i.h5', 'test', lock=False)

In [15]: ddgn_finder_r_i
Out[15]: dd.DataFrame<read-hd..., npartitions=1>

In [16]: ddgn_finder_r_i.head()
Out[16]:
         DGN
DGN
11111  11111
11112  11112
11113  11113
11114  11114
1111A  1111A

In [17]: dclm_pb_r_i = dd.read_hdf(r'/mnt/nfs/dclm_pb_r_i_10M.h5', 'test', lock=False)

In [18]: dclm_pb_r_i
Out[18]: dd.DataFrame<read-hd..., npartitions=10>

In [19]: dclm_pb_r_i.head()
Out[19]:
                         CLAIMNO  EDB_MONTH2
CLAIMNO
136013300000009  136013300000009    20080806
136013300000012  136013300000012    20080128
136013300000042  136013300000042    20080270
136013300000053  136013300000053    20080184
136013300000066  136013300000066    20080733

In [20]: step0 = dd.merge(ddgn_pb_r_i, ddgn_finder_r_i, how='inner')[['CLAIMNO']]

In [21]: step1 = dd.merge(dclm_pb_r_i, step0, left_index=True, right_on='CLAIMNO', how='inner')[['CLAIMNO']].count()

In [22]: res = dask.compute(step1)

And on my worker node I see repeating Error messages:
Traceback (most recent call last):
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/utils.py", line 206, in log_errors
    yield
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/worker.py", line 397, in compute_many
    good, bad, data, num_transferred = yield self.gather_many(msgs)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/worker.py", line 268, in gather_many
    permissive=True, rpc=self.rpc, close=False)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/client.py", line 122, in gather_from_workers
    StreamClosedError)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/utils.py", line 62, in ignore_exceptions
    result = yield wait_iterator.next()
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/core.py", line 441, in send_recv_from_rpc
    result = yield send_recv(stream=stream, op=key, **kwargs)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/core.py", line 337, in send_recv
    six.reraise(*clean_exception(**response))
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/core.py", line 206, in handle_stream
    result = yield gen.maybe_future(handler(stream, **msg))
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/worker.py", line 578, in get_data
    return {k: dumps(self.data[k]) for k in keys if k in self.data}
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/worker.py", line 578, in <dictcomp>
    return {k: dumps(self.data[k]) for k in keys if k in self.data}
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/core.py", line 60, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 629, in dumps
    cp.dump(obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 520, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 547, in save_reduce
    save(state)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 810, in save_dict
    self._batch_setitems(obj.items())
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 836, in _batch_setitems
    save(v)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 495, in save
    rv = reduce(self.proto)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/partd/buffer.py", line 26, in __getstate__
    'total_memory': self.memory_usage,
AttributeError: 'Buffer' object has no attribute 'memory_usage'
distributed.worker - INFO - Deleted 3 keys
Opening /mnt/nfs/ddgn_finder_r_i.h5 in read-only mode
distributed.worker - WARNING -  Compute Failed
Function: partition
args:     ("('read-hdf-eeafab2cf14c967c1247f06a62d1171d', 2)", "('read-hdf-eeafab2cf14c967c1247f06a62d1171d-index', 2)", 10, "('zpartd-d2f47b04456811e69e750f11733774a4',)")
kwargs:   {}

distributed.worker - WARNING -  Compute Failed
Function: partition
args:     ("('read-hdf-eeafab2cf14c967c1247f06a62d1171d', 7)", "('read-hdf-eeafab2cf14c967c1247f06a62d1171d-index', 7)", 10, "('zpartd-d2f47b04456811e69e750f11733774a4',)")
kwargs:   {}

**Comment by ankravch** [comment] 2016-07-09 10:25
Running the same query on a single machine sometimes works/sometimes does not (see below):

[akravchenko@hnode1 nfs]$ python
Python 3.5.1 |Anaconda custom (64-bit)| (default, Dec  7 2015, 11:16:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask.dataframe as dd
>>> import pandas as pd
>>> import numpy as np
>>> import dask, random
>>>
>>> from dask.diagnostics import ProgressBar
>>> pbar = ProgressBar()
>>> pbar.register()
>>> ddgn_pb_r_i = dd.read_hdf(r'/mnt/nfs/ddgn_pb_r_i.h5', 'test', lock=True)
>>> ddgn_finder_r_i = dd.read_hdf(r'/mnt/nfs/ddgn_finder_r_i.h5', 'test', lock=True)
>>> dclm_pb_r_i = dd.read_hdf(r'/mnt/nfs/dclm_pb_r_i_10M.h5', 'test', lock=True)
>>> step0=dd.merge(ddgn_pb_r_i, ddgn_finder_r_i, how='inner')[['CLAIMNO']]
>>> step1=dd.merge(dclm_pb_r_i, step0,left_index=True, right_on='CLAIMNO', how='inner')[['CLAIMNO']].count()
>>> dask.compute(step1)
[########################################] | 100% Completed | 15.3s
(CLAIMNO    150489
dtype: int64,)
>>>
>>> dask.compute(step1)
[########################################] | 100% Completed | 15.3s
(CLAIMNO    150489
dtype: int64,)
>>> dask.compute(step1)
[########################################] | 100% Completed | 15.2s
(CLAIMNO    150489
dtype: int64,)
>>> dask.compute(step1)
[########################################] | 100% Completed | 16.2s
(CLAIMNO    150489
dtype: int64,)
>>> dask.compute(step1)
[########################################] | 100% Completed | 16.1s
(CLAIMNO    150489
dtype: int64,)
>>> dask.compute(step1)
[########################################] | 100% Completed | 16.1s
(CLAIMNO    150489
dtype: int64,)
>>> dask.compute(step1)
[###########                             ] | 28% Completed |  7.9sSegmentation fault
[akravchenko@hnode1 nfs]$

**Comment by ankravch** [comment] 2016-07-09 10:35
Running the same query in dask.async.get_sync mode always works (10 out of 10)
>>> #res = dask.compute(step1)
... res=dask.compute(step1, get=dask.async.get_sync)
[########################################] | 100% Completed | 15.1s
>>>

**Comment by ankravch** [comment] 2016-07-09 10:45
A reproducible example:

import dask.dataframe as dd
import pandas as pd
import numpy as np
import dask, random

# prepare h5 files (ddgn_pb_r_i.h5, ddgn_finder_r_i.h5, dclm_pb_r_i_10M.h5)
dgn_values= list([''.join(random.choice('ABCD1234') for _ in range(5)) for i in range(1500000)])
dgn_pb_r=pd.DataFrame({'DGN':dgn_values[:1500000],'CLAIMNO':random.sample(range(136013300000000,136013400000000), 1500000)})
ddgn_pb_r = dd.from_pandas(dgn_pb_r, npartitions=10)
ddgn_pb_r_i = ddgn_pb_r.set_index('DGN', drop=False)
ddgn_pb_r_i.to_hdf('ddgn_pb_r_i.h5', 'test', format='table', mode='w')

dgn_finder = list(dgn_pb_r['DGN'].drop_duplicates())
random.shuffle(dgn_finder)
dgn_finder_r = pd.DataFrame({'DGN':dgn_finder})
ddgn_finder_r = dd.from_pandas(dgn_finder_r, npartitions=10)
ddgn_finder_r_i = ddgn_finder_r.set_index('DGN', drop=False)
ddgn_finder_r_i.to_hdf('ddgn_finder_r_i.h5', 'test', format='table', mode='w')

clm_pb_r=pd.DataFrame({'CLAIMNO':random.sample(range(136013300000000,136013400000000), 10000000), 'EDB_MONTH2':np.random.randint(20080000,20081231,(10000000,))})
dclm_pb_r = dd.from_pandas(clm_pb_r, npartitions=10)
dclm_pb_r_i = dclm_pb_r.set_index('CLAIMNO', drop=False)
dclm_pb_r_i.to_hdf('dclm_pb_r_i_10M.h5', 'test', format='table', mode='w')

# run query
from distributed import Executor
e=Executor('192.168.102.220:8786', set_as_default=True)

ddgn_pb_r_i = dd.read_hdf(r'/mnt/nfs/ddgn_pb_r_i.h5', 'test', lock=False)
ddgn_finder_r_i = dd.read_hdf(r'/mnt/nfs/ddgn_finder_r_i.h5', 'test', lock=False)
dclm_pb_r_i = dd.read_hdf(r'/mnt/nfs/dclm_pb_r_i_10M.h5', 'test', lock=False)

step0 = dd.merge(ddgn_pb_r_i, ddgn_finder_r_i, how='inner')[['CLAIMNO']]
step1 = dd.merge(dclm_pb_r_i, step0, left_index=True, right_on='CLAIMNO', how='inner')[['CLAIMNO']].count()
res = dask.compute(step1)

**Comment by jcrist** [comment] 2016-07-09 14:27
Thanks for the reproducible example. The failure is a segfault, most likely caused by thread safety issues when reading from hdf5. You have `lock=False` in your code, does it work with `lock=True`?

**Comment by nirizr** [comment] 2016-07-09 14:43
Someone at my work had the same mistake some time ago, may i suggest a hinting warning or change in default values based on other input (#1293 changes the default value of `lock`)?

**Comment by ankravch** [comment] 2016-07-10 00:18
>You have lock=False in your code, does it work with lock=True?
right, using lock=True in distributed mode gives 'TypeError: can't pickle _thread.lock objects'

Here is a full backtrace:
[akravchenko@hnode1 nfs]$ python
Python 3.5.1 |Anaconda custom (64-bit)| (default, Dec  7 2015, 11:16:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask.dataframe as dd
>>> import pandas as pd
>>> import numpy as np
>>> import dask
>>>
>>> from distributed import Executor
>>> e=Executor('192.168.102.220:8786', set_as_default=True)
>>>
>>> from dask.diagnostics import ProgressBar
>>> pbar = ProgressBar()
>>> pbar.register()
>>> ddgn_pb_r_i = dd.read_hdf(r'/mnt/nfs/ddgn_pb_r_i.h5', 'test', lock=True)
>>> ddgn_finder_r_i = dd.read_hdf(r'/mnt/nfs/ddgn_finder_r_i.h5', 'test', lock=True)
>>> dclm_pb_r_i = dd.read_hdf(r'/mnt/nfs/dclm_pb_r_i_10M.h5', 'test', lock=True)
>>> step0 = dd.merge(ddgn_pb_r_i, ddgn_finder_r_i, how='inner')[['CLAIMNO']]
>>> step1 = dd.merge(dclm_pb_r_i, step0,\
...                  left_index=True, right_on='CLAIMNO', how='inner')[['CLAIMNO']].count()
>>> res = dask.compute(step1)
distributed.core - INFO - Failed to serialize ('/mnt/nfs/dclm_pb_r_i_10M.h5', '/test', <unlocked _thread.lock object at 0x7f7d7ffa58c8>, {'start': 8000000, 'stop': 9000000, 'columns': Index(['CLAIMNO', 'EDB_MONTH2'], dtype='object')})
Traceback (most recent call last):
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/core.py", line 47, in dumps
    result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle _thread.lock objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/core.py", line 60, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 629, in dumps
    cp.dump(obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 495, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.lock objects
distributed.utils - ERROR - can't pickle _thread.lock objects
Traceback (most recent call last):
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/core.py", line 47, in dumps
    result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle _thread.lock objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/utils.py", line 102, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/executor.py", line 967, in _get
    'tasks': valmap(dumps_task, dsk3),
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/toolz/dicttoolz.py", line 84, in valmap
    rv.update(zip(iterkeys(d), map(func, itervalues(d))))
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/worker.py", line 709, in dumps_task
    'args': dumps(task[1:])}
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/core.py", line 60, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 629, in dumps
    cp.dump(obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 495, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.lock objects
Traceback (most recent call last):
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/core.py", line 47, in dumps
    result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
TypeError: can't pickle _thread.lock objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/dask/base.py", line 179, in compute
    results = get(dsk, keys, **kwargs)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/executor.py", line 1007, in get
    raise_on_error=False, **kwargs)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/utils.py", line 116, in sync
    six.reraise(type(error[0]), error[0], traceback[0])
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/six.py", line 686, in reraise
    raise value
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/utils.py", line 102, in f
    result[0] = yield gen.maybe_future(func(*args, **kwargs))
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/executor.py", line 967, in _get
    'tasks': valmap(dumps_task, dsk3),
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/toolz/dicttoolz.py", line 84, in valmap
    rv.update(zip(iterkeys(d), map(func, itervalues(d))))
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/worker.py", line 709, in dumps_task
    'args': dumps(task[1:])}
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/distributed/core.py", line 60, in dumps
    return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 629, in dumps
    cp.dump(obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/site-packages/cloudpickle/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 408, in dump
    self.save(obj)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 475, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 740, in save_tuple
    save(element)
  File "/home/SECDEV.LOCAL/akravchenko/anaconda3/lib/python3.5/pickle.py", line 495, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.lock objects
>>>

**Comment by mrocklin** [comment] 2016-07-10 00:20
This will be resolved by https://github.com/dask/dask/issues/1355

**Comment by jcrist** [comment] 2016-07-21 15:26
The "'Buffer' object has no attribute 'memory_usage'" error is fixed by https://github.com/dask/partd/pull/12. You can get the latest version of partd using:

`pip install --upgrade git+https://github.com/dask/partd.git`

**Comment by ankravch** [comment] 2016-07-21 15:55
thanks a lot, I just tested it on my cluster and it worked like a charm!

**Closed** 2016-07-27 17:57 UTC
