### ISSUE TITLE
da.histogram just loops and never completes on a small dataset. 

### ISSUE THREAD

**Issue by Sh4zKh4n** [dask/dask#8048] opened 2021-08-16 14:48 UTC
**What happened**:
I am finding that dask array histogram is just looping for ever. I have tried this on a large dataset and have tried it on a small dataset. On both occasions the histogram takes for ever. This is a recent issue because it used to work. All the files are 3d arrays saved as zarr files but I am not sure what is going on here

- Dask version:
- Python version: 3.8
- Operating System: ubuntu 18.04
- Install method (conda, pip, source): conda

**Comment by douglasdavis** [comment] 2021-08-16 15:05
Thanks for raising the issue! Would it be possible to provide a [reproducible example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports)? Perhaps additional help would be to include the Dask version where you are seeing the issue.

**Comment by ncclementi** [comment] 2021-09-10 18:42
@Sh4zKh4n I will close this issue since it's been a while since there was a request for a minimal reproducible example. If you are still having this problem please feel free to re-open the issue with a minimal reproducible example. Otherwise, it's a bit difficult to provide some guidance/help.

**Closed by ncclementi** 2021-09-10 18:42 UTC
Labels: array, needs info
