### ISSUE TITLE
.loc results in empty parquet files

### ISSUE THREAD

**Issue by jendrikjoe** [dask/dask#4300] opened 2018-12-14 19:22 UTC
**Bug report:** 
I am currently trying to split up data given multiple columns.
One of them contains a year after which the data are sorted.
When I am now using a .loc on the data and then a to_parquet. Only the first 5 parquet files contain data. However, all parquet files are written to disk. 

    df = dd.read_csv(f)
    df = df.loc[df['split_col'] == val]
    df.to_parquet(new_file)

When reading it back in, I am then getting an error, that the schema change:
ValueError: Schema in /part.10.parquet was different. 
With it having null for all columns as the column type.

Even re partitioning does not help as it only merges the partitions, which are close to each other.
From my understanding this makes sense as one is filtering the partitions here. However, not writing the empty parquet files would be what I expect.

Could anyone elaborate on how to solve this issue?

Thank you very much,

Jendrik

**Comment by jendrikjoe** [comment] 2018-12-16 12:58
Found this on StackOverflow:
https://stackoverflow.com/questions/47812785/remove-empty-partitions-in-dask#50613803
Would it be possible to add this within the getitem function?
Or to the API of the dask dataframe?
It will decrease the efficiency, but it would resolve a lot of issues for multiple users.

Thank you very much,

Jendrik

**Comment by TomAugspurger** [comment] 2018-12-16 16:04
> Would it be possible to add this within the getitem function?

No, I don't think so because it requires computing the graph up to that point.

I'd rather ensure that our operations are robust to empty partitions. Do you have a [reproducible example](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) for the failure?

**Comment by jendrikjoe** [comment] 2018-12-17 10:34
Valid point @TomAugspurger .
Sorry as well for not providing a reproducible example directly.
Producing it, I realized that the bug only appears with string columns.
If one removes the v4 column from the following example dataframe everything works fine.

```
import dask.dataframe as dd
import pandas as pd
from dask.distributed import Client
import numpy as np

client = Client(memory_limit='auto')

df = pd.DataFrame(
    {'v0': np.arange(0, 100000000) + np.random.randint(1,100000, (100000000,)),
    'v4': np.arange(0, 100000000) + np.random.randint(1,100000, (100000000,))})

df['v4'] = df['v4'].astype(str)
df = dd.from_pandas(df, chunksize=1000000)
df.loc[df['v0'] < 10000000].to_parquet('test.temp')
df = pd.read_parquet('test.temp')
df.head(100)
df.tail(100)

```

Cheers,

Jendrik

**Comment by TomAugspurger** [comment] 2018-12-17 12:15
Did you intend to read the file back in with pandas?

**Comment by jendrikjoe** [comment] 2018-12-17 20:57
No but with Dask at a later point.

On 17. Dec 2018, at 13:15, Tom Augspurger <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you intend to read the file back in with pandas?

**Comment by bryanwweber** [comment] 2022-03-28 17:42
I can't reproduce this error with the example in https://github.com/dask/dask/issues/4300#issuecomment-447797889. I'm going to close this, but please feel free to reopen if this is still an issue. Thanks! 😄

**Closed by bryanwweber** 2022-03-28 17:42 UTC
Labels: dataframe, io, parquet
