### ISSUE TITLE
How to get worker stdout in dask?

### ISSUE THREAD

**Issue by liucimin** [dask/dask#5577] opened 2019-11-11 13:05 UTC
1.  
Wo.
I have some puzzle about the "stdout " in worker's tasks.
Such as blow codes.How can i get the print from the worker？

```
def func():
    print(1)

rs = client.map(func,[1,2,3,4,54])
client.gather(rs)
```

Thx for your help~

**Comment by TomAugspurger** [comment] 2019-11-11 13:32
That likely depends on the cluster manager you're using, if any. Some will capture stdout and forward it to their logging system.

**Comment by liucimin** [comment] 2019-11-11 13:35
I can’t understand what’s the cluster manager? I use the dask worker but I could not find the print.



发自我的iPhone


------------------ Original ------------------

**Comment by liucimin** [comment] 2019-11-11 13:36
I just see the log from the worker itself.But how can I get the print in the func?

发自我的iPhone


------------------ Original ------------------

**Comment by mrocklin** [comment] 2019-11-11 15:42
Dask does not communicate stdout/stderr.

If you start Dask with Kubernetes or Yarn or PBS/LSF/SLURM or some other cluster system then that system can give you stderr/stdout.

How do you set up your workers?  Are you using the `dask-worker` command, or a project like `dask_kubernetes`?

**Comment by liucimin** [comment] 2019-11-11 15:52
Yes,I use helm to create my dask cluster.In the worker pod it use dask-work to start worker in pod
That’s my puzzle if I use kubectl logs to show the worker pod I just find the logs from the dask-worker process.It can not get the print from the task when I use Client.map or Client.submit . But when I use Local cluster I can see it in my screen.
So my quesstion is when I submit a function in the k8s cluster worker is the stdout hook by the worker or the docker just stdout the logs from the main command what is the start command for a container ？

发自我的iPhone


------------------ Original ------------------

**Comment by mrocklin** [comment] 2019-11-11 15:55
If you call `print` from your task then it should show in your dask-worker logs.  

Dask does not move stdout/stderr.  We just do whatever Python does.  Nothing special.

**Comment by liucimin** [comment] 2019-11-11 16:08
Thx for your reply.
I will try again tomorrow.
And then get more details.



发自我的iPhone


------------------ Original ------------------

**Comment by liucimin** [comment] 2019-11-12 07:06
@mrocklin 
I have two work pods and start with these args.
![image](https://user-images.githubusercontent.com/8232349/68649371-833afd00-055d-11ea-978f-1cbdf6161cb8.png)

And then i use the k8s dask cluster with this way:

![image](https://user-images.githubusercontent.com/8232349/68649182-01e36a80-055d-11ea-9477-cfc5c6584008.png) 

When the task all done.I try to find the worker logs on the dashboard or from pod. I cannot get the "123123123" in the log details.
![image](https://user-images.githubusercontent.com/8232349/68649461-c1382100-055d-11ea-9999-1abdbd301a8b.png)
![image](https://user-images.githubusercontent.com/8232349/68649538-e593fd80-055d-11ea-8fd0-938162cd40c1.png)

**Comment by mrocklin** [comment] 2019-11-12 15:29
Right, the dashboard only shows the logs that come from the Python logging
module, not stdout.  For full output from the process you should use
Kubernetes.

**Comment by liucimin** [comment] 2019-11-13 06:45
@mrocklin 
Since i use kubectl logs the worker pod.
The logs is the same as dashboard show.

It seem the dask-worker use the stdout as its logging module output way?
Then the print in task can not show out?

![image](https://user-images.githubusercontent.com/8232349/68739615-32daa280-0624-11ea-9800-f822221ef356.png)

**Comment by mrocklin** [comment] 2019-11-13 15:14
> It seem the dask-worker use the stdout as its logging module output way?

Dask uses the standard Python `logging` module.  We don't do anything special.

**Comment by TomAugspurger** [comment] 2019-11-19 19:35
Closing this as a duplicate of https://github.com/dask/distributed/issues/2033, though it's not clear that there's a solution there / desire to implement this.

**Closed by TomAugspurger** 2019-11-19 19:35 UTC
