### ISSUE TITLE
'_LocIndexer' object does not support item assignment

### ISSUE THREAD

**Issue by arhwang12** [dask/dask#7252] opened 2021-02-20 04:34 UTC
**What happened**: can't reassign values in a particular row and column entry

**What you expected to happen**: it's supposed to assign the particular row and column with 'abc'

**Minimal Complete Verifiable Example**:

```python
train_set.loc[0,'SibSp']='abc'
```

**Anything else we need to know?**:

**Environment**: conda

- Dask version: 2.9.0
- Python version: 3.7.9
- Operating System: Windows 10
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment] 2021-02-20 16:57
Thanks for raising an issue @arhwang12. Closing as a duplicate of https://github.com/dask/dask/issues/2426 and https://github.com/dask/dask/issues/5648.

**Closed by jrbourbeau** 2021-02-20 16:57 UTC
