### ISSUE TITLE
String comparison for index fails.

### ISSUE THREAD

**Issue by jendrikjoe** [dask/dask#5378] opened 2019-09-09 12:35 UTC
**Bug report:** 

When doing comparisons with the index and filtering a dask dataframe with it I get a `NonImplementedError`. This seems to be related to #3227 and #3230. It happens for all kinds of data types stored in the index

```python
import pandas as pd
import dask.dataframe as dd

if __name__ == '__main__':
    # String index
    df = pd.DataFrame([['1000_5008', 'a'], ['1000_5009', 'b'], ['1234_5010', 'c']], columns=['a', 'b'])

    ddf = dd.from_pandas(df, npartitions=1)

    ddf2 = ddf.set_index(ddf['a']).drop('a', axis=1)
    # The following fails
    # ddf2 = ddf2[ddf2.index < '1234_5010'].compute()
    # with NotImplementedError: dask.array<lt, shape=(nan,), dtype=bool, chunksize=(nan,)>
    # A possible workaround is:

    ddf2['a'] = ddf2.index
    ddf2 = ddf2[ddf2['a'] < '1234_5010']
    ddf2 = ddf2.set_index(ddf2['a']).drop('a', axis=1)
    print(ddf2.compute()) 
    print(ddf2.divisions)

    # Integer Index
    df = pd.DataFrame([[0, 'a'], [100, 'b'], [200, 'c']], columns=['a', 'b'])

    ddf = dd.from_pandas(df, npartitions=1)

    ddf2 = ddf.set_index(ddf['a']).drop('a', axis=1)

    # The following fails
    # ddf2 = ddf2[ddf2.index < 200].compute()
    # with NotImplementedError: dask.array<lt, shape=(nan,), dtype=bool, chunksize=(nan,)>
    # A possible workaround is:

    ddf2['a'] = ddf2.index
    ddf2 = ddf2[ddf2['a'] < 200]
    ddf2 = ddf2.set_index(ddf2['a']).drop('a', axis=1)

    print(ddf2.compute())
    print(ddf2.divisions)
```

**Comment by quasiben** [comment] 2019-09-09 15:16
@jendrikjoe thanks for the bug report and reproducible example.  Indeed this is an issue

A couple of things:
1) dask recently merged functionality to help compute unknown sizes: https://github.com/dask/dask/pull/5312 -- `(ddf2.index < '1234_5010').compute_chunk_sizes()` . This may prove useful in resolving this and other bugs as we may to call that instead of erroring or at least make users aware of that option
2) In the string index part I don't there should be an expectation for it to work ?   What should the behavior of `ddf2['a'] < '1234_5010' -- you may generate TypeErrors between the comparison ?

**Comment by jendrikjoe** [comment] 2019-09-09 15:47
@quasiben thanks for the speedy reply :slightly_smiling_face: 
I tried doing `ddf2 = ddf2[(ddf2.index < '1234_5010').compute_chunk_sizes()].compute()`, but it gives me `AttributeError: 'Array' object has no attribute 'compute_chunk_sizes'`
Regarding you second question, it actually works when not filtering on the index and does simple string comparison. In the particular case, it removes the last element from the data_frame. As an example:
```python
import pandas as pd
import dask.dataframe as dd

if __name__ == '__main__':
    df = pd.DataFrame([['1000_5008', 'a'], ['1000_5009', 'b'], ['1234_5010', 'c']], columns=['a', 'b'])

    ddf = dd.from_pandas(df, npartitions=1)
    ddf = ddf[ddf['a'] < '1234_5010']
    print(ddf.compute()) 

# Out:
#            a  b
# 0  1000_5008  a
# 1  1000_5009  b

```

**Comment by quasiben** [comment] 2019-09-09 16:25
you will mostly likely need dask from master on github.  The comments i made probably won't fully work but will help you take the next step -- though perhaps @TomAugspurger may have thoughts on filtering with an index.

**Comment by jendrikjoe** [comment] 2019-09-09 16:43
Hey @quasiben, I used master in the above comment and it got me further such that the error message is `NotImplementedError: dask.array<lt, shape=(3,), dtype=bool, chunksize=(3,), chunktype=numpy.ndarray>'` instead of `NotImplementedError: dask.array<lt, shape=(nan,), dtype=bool, chunksize=(nan,)>` :slightly_smiling_face:

**Comment by quasiben** [comment] 2019-09-09 19:16
after chatting with @TomAugspurger i'm don't think filtering on index is fully supported.  Instead, if you want to select into the DF with the index I would recommend using `loc`.  For example to select everything but the last line:

```python
In [50]: ddf2.loc[:'1234_5009'].compute()                                                                                                                                                                                                                            
Out[50]: 
           b
a           
1000_5008  a
1000_5009  b
```

Notice that the value is inclusive.  

Dask could implement boolean indexing with a dask array but it currently doesn't .  Effectively when dask filters on a column a dask series is constructed.  This series shares and index with the original dataframe.  With a boolean dask array, there is no index -- what should happen here?  Probably the chunk lengths of match the partition lengths but we don't know that for sure.  If you are interested in resolving this probably within dask that would be really cool!  If not, and the `loc` solution works for you that's great too.

**Comment by jendrikjoe** [comment] 2019-09-09 22:44
Awesome thank you for all those hints :slightly_smiling_face: 
I will go for the slicing solution for the time being :wink: 
I will as well try implementing it, when I have a bit more spear time here :+1:

**Comment by GenevieveBuckley** [comment] 2021-10-13 01:37
These examples run without error using a newer version of dask (I'm using dask 2021.09.0), so it looks like this has been fixed. I'll close this issue, but if anyone is still having trouble please let us know.

**Closed** 2021-10-13 01:37 UTC
Labels: dataframe
