### ISSUE TITLE
Dataframe drops rows after set index

### ISSUE THREAD

**Issue by dvirginz** [dask/dask#6145] opened 2020-04-28 06:03 UTC
Code:
```
dataset = {'a' : list(range(1000000)),'b': list(range(1000000))}
df = pd.DataFrame.from_dict(data)
sd = dd.from_pandas(df, npartitions=len(dataset)/10000)
sd = sd.astype(str)

random_idx = np.random.permutation(len(sd.index))
print(len(sdd.index)) -------> This gives 1717049
sdd = sd.assign(random_idx=dd.from_array(random_idx))
print(len(sdd.index)) -------> This gives 1717049
sddd = sdd.set_index('random_idx')
print(len(sddd .index)) -------> This gives 50000
```
The reasoning behind my code is to permute the rows in a random way (there is probably a better way, but that's not the point of the post:) )

After setting the index to the newly generated column, the number of rows drops to 50,000, a number that seems pretty arbitrary...

edit: I now understand that dd.from_array has a default value of 50000 chunk_size, which is still not that clear to my why the meaning is that only the first 50000 elements are kept after the operation.

**Comment by TomAugspurger** [comment] 2020-04-28 11:25
Do you have a reproducible example? `df` and `dataset` don't seem to be defined.

**Comment by dvirginz** [comment] 2020-04-29 08:06
Added the example and a possible explanation which is not 100% clear to me.

**Comment by brl0** [comment] 2020-05-11 00:39
I got curious and tried to explore this issue a little bit.

Simple goal: assign array to a column in a dataframe

Scenario 1, Works with pandas:
```
dataset = {'a' : list(range(1000000)),'b': list(range(1000000))}
df = pd.DataFrame.from_dict(dataset)
random_idx = np.random.permutation(len(sd.index))
df['random_idx'] = random_idx

	a	b	random_idx
0	0	0	589080
1	1	1	660573
...	...	...	...
999998	999998	999998	777414
999999	999999	999999	149339
```


Scenario 2, Unexpected results with Dask:
```
dataset = {'a' : list(range(1000000)),'b': list(range(1000000))}
df = pd.DataFrame.from_dict(dataset)
random_idx = np.random.permutation(len(sd.index))
sd = dd.from_pandas(df, npartitions=len(dataset)/10000)
sd['random_idx'] = dd.from_array(random_idx)
sd.compute()

	a	b	random_idx
0	0	0	283499.0
1	1	1	641156.0
...	...	...	...
999998	999998	999998	NaN
999999	999999	999999	NaN
```

Scenario 3, Using Dask to compute the array into a Pandas series before assigning to a column generates an error:
```
dataset = {'a' : list(range(1000000)),'b': list(range(1000000))}
df = pd.DataFrame.from_dict(dataset)
random_idx = np.random.permutation(len(sd.index))
sd = dd.from_pandas(df, npartitions=len(dataset)/10000)
ds = dd.from_array(random_idx).compute()
sd['random_idx'] = ds
```

<details><summary>`ValueError: cannot reindex from a duplicate axis`</summary>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-55-b5ddb12cf820> in <module>
      3 random_idx = np.random.permutation(len(sd.index))
      4 sd = dd.from_pandas(df, npartitions=len(dataset)/10000)
----> 5 sd['random_idx'] = dd.from_array(random_idx).compute()
      6 sd.compute()

~/miniconda3/envs/default/lib/python3.7/site-packages/dask/dataframe/core.py in __setitem__(self, key, value)
   3433             df = self.assign(**{k: value for k in key})
   3434         else:
-> 3435             df = self.assign(**{key: value})
   3436 
   3437         self.dask = df.dask

~/miniconda3/envs/default/lib/python3.7/site-packages/dask/dataframe/core.py in assign(self, **kwargs)
   3698 
   3699         # Figure out columns of the output
-> 3700         df2 = self._meta_nonempty.assign(**_extract_meta(kwargs, nonempty=True))
   3701         return elemwise(methods.assign, self, *pairs, meta=df2)
   3702 

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/frame.py in assign(self, **kwargs)
   3565 
   3566         for k, v in kwargs.items():
-> 3567             data[k] = com.apply_if_callable(v, data)
   3568         return data
   3569 

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/frame.py in __setitem__(self, key, value)
   2936         else:
   2937             # set column
-> 2938             self._set_item(key, value)
   2939 
   2940     def _setitem_slice(self, key, value):

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/frame.py in _set_item(self, key, value)
   2998 
   2999         self._ensure_valid_index(value)
-> 3000         value = self._sanitize_column(key, value)
   3001         NDFrame._set_item(self, key, value)
   3002 

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/frame.py in _sanitize_column(self, key, value, broadcast)
   3611 
   3612         if isinstance(value, Series):
-> 3613             value = reindexer(value)
   3614 
   3615         elif isinstance(value, DataFrame):

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/frame.py in reindexer(value)
   3602                     if not value.index.is_unique:
   3603                         # duplicate axis
-> 3604                         raise err
   3605 
   3606                     # other

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/frame.py in reindexer(value)
   3597                 # GH 4107
   3598                 try:
-> 3599                     value = value.reindex(self.index)._values
   3600                 except ValueError as err:
   3601                     # raised in MultiIndex.from_tuples, see test_insert_error_msmgs

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/series.py in reindex(self, index, **kwargs)
   4028     @Appender(generic.NDFrame.reindex.__doc__)
   4029     def reindex(self, index=None, **kwargs):
-> 4030         return super().reindex(index=index, **kwargs)
   4031 
   4032     def drop(

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/generic.py in reindex(self, *args, **kwargs)
   4542         # perform the reindex on the axes
   4543         return self._reindex_axes(
-> 4544             axes, level, limit, tolerance, method, fill_value, copy
   4545         ).__finalize__(self)
   4546 

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/generic.py in _reindex_axes(self, axes, level, limit, tolerance, method, fill_value, copy)
   4565                 fill_value=fill_value,
   4566                 copy=copy,
-> 4567                 allow_dups=False,
   4568             )
   4569 

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/generic.py in _reindex_with_indexers(self, reindexers, fill_value, copy, allow_dups)
   4611                 fill_value=fill_value,
   4612                 allow_dups=allow_dups,
-> 4613                 copy=copy,
   4614             )
   4615 

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/internals/managers.py in reindex_indexer(self, new_axis, indexer, axis, fill_value, allow_dups, copy)
   1249         # some axes don't allow reindexing with dups
   1250         if not allow_dups:
-> 1251             self.axes[axis]._can_reindex(indexer)
   1252 
   1253         if axis >= self.ndim:

~/miniconda3/envs/default/lib/python3.7/site-packages/pandas/core/indexes/base.py in _can_reindex(self, indexer)
   3096         # trying to reindex on an axis with duplicates
   3097         if not self.is_unique and len(indexer):
-> 3098             raise ValueError("cannot reindex from a duplicate axis")
   3099 
   3100     def reindex(self, target, method=None, level=None, limit=None, tolerance=None):

ValueError: cannot reindex from a duplicate axis
</details>


Scenario 4, Assigning from a Pandas series works:
```
dataset = {'a' : list(range(1000000)),'b': list(range(1000000))}
df = pd.DataFrame.from_dict(dataset)
random_idx = np.random.permutation(len(sd.index))
sd = dd.from_pandas(df, npartitions=len(dataset)/10000)
ds = pd.Series(random_idx)
sd['random_idx'] = ds
sd.compute()
```

Scenario 5, As a sanity check, I tried the following with Pandas to try to better understand the behavior:
```
dataset = {'a' : list(range(1000000)),'b': list(range(1000000))}
df = pd.DataFrame.from_dict(dataset)
df.index = range(500000, 1500000)
random_idx = np.random.permutation(len(sd.index))
df['random_idx'] = pd.Series(random_idx)
df

        a	b	random_idx
500000	0	0	184815.0
500001	1	1	77642.0
...	...	...	...
1499998	999998	999998	NaN
1499999	999999	999999	NaN
```

Scenario 6, An attempt to more accurately replicate the scenario with Pandas results in the same `ValueError` as above.
```
dataset = {'a' : list(range(1000000)),'b': list(range(1000000))}
df = pd.DataFrame.from_dict(dataset)
random_idx = np.random.permutation(len(sd.index))
ds = pd.Series(random_idx)
ds.index = list(range(50000)) * 20
df['random_idx'] = ds
```

I find the behavior of `Scenario 2` troubling because the issue seems non-obvious and silent, I think it would be better if an error was raised in that situation.

I hope this helps, let me know if I can be of assistance.

**Comment by TomAugspurger** [comment] 2020-05-11 20:34
@brl0 only looking at your scenario 2, but it seems that `DataFrame.__setitem__` only sets into the first partition when the value is an ndarray

```python
In [20]: sd.random_idx.map_partitions(lambda x: x.isna().sum()).compute()
Out[20]:
0         0
1     50000
2     50000
3     50000
4     50000
5     50000
6     50000
7     50000
8     50000
9     50000
10    50000
11    50000
12    50000
13    50000
14    50000
15    50000
16    50000
17    50000
18    50000
19    50000
dtype: int64
```

This isn't great, but I think it's also unusual for a person to set an ndarray into a dask DataFrame. You'd be better off setting a delayed object like a Dask Array

```python

**Comment by TomAugspurger** [comment] 2020-09-11 15:26
I believe things are better here now.

1. We raise in DataFrame.__setitem__ for NumPy.ndarrays.
2. We verify that the number of partitions match for Dask Arrays
3. We align for Dask Series / DataFrames

**Closed by TomAugspurger** 2020-09-11 15:26 UTC
Labels: dataframe
