### ISSUE TITLE
dask_searchcv not found

### ISSUE THREAD

**Issue by bansalr** [dask/dask#2728] opened 2017-09-29 02:18 UTC
I am getting dask_searchcv not found. Installed this from conda-forge. Also created new env but get the same error. 
Thank You!
```
$ conda install -c conda-forge dask dask-core dask-searchcv

$ conda list | grep dask
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
dask                      0.15.3                     py_0    conda-forge
dask-core                 0.15.3                     py_0    conda-forge
dask-searchcv             0.1.0                      py_0    conda-forge
 $ python
Python 2.7.13 | packaged by conda-forge | (default, May  2 2017, 12:48:11) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask_searchcv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named dask_searchcv

```

**Comment by jcrist** [comment] 2017-09-29 02:22
This is not a bug in dask but rather in how you're installing it. Are you sure you're in your environment? I am unable to reproduce.

```
(dask) jcrist dask $ conda install -c conda-forge dask-searchcv
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/jcrist/anaconda/envs/dask:

The following NEW packages will be INSTALLED:

    dask:          0.15.0-py35_0 conda-forge
    dask-searchcv: 0.1.0-py_0    conda-forge
    distributed:   1.16.1-py35_0 conda-forge

The following packages will be UPDATED:

    toolz:         0.8.0-py35_0  conda-forge --> 0.8.2-py_2 conda-forge

toolz-0.8.2-py 100% |############################################################################################################################################################| Time: 0:00:00 460.05 kB/s
dask-0.15.0-py 100% |############################################################################################################################################################| Time: 0:00:00   1.06 MB/s
distributed-1. 100% |############################################################################################################################################################| Time: 0:00:00   1.02 MB/s
(dask) jcrist dask $ python -c "import dask_searchcv;print(dask_searchcv.__version__)"
0.1.0
```

**Comment by TomAugspurger** [comment] 2017-09-29 10:45
In particular, make sure that the `python` on your path is the same as your `conda`.

`which conda`

`which python`.

**Comment by bansalr** [comment] 2017-09-29 15:39
I think that is the problem, we will fix and post and update so google can
find the answer in the future.

**Comment by jcrist** [comment] 2017-10-13 23:03
Closing this for now as it's unrelated to dask. If you find the solution to your problem please post it here so it's google-able.

**Closed by jcrist** 2017-10-13 23:03 UTC
