### ISSUE TITLE
Dask worker utilises enormous amount of memory before distributing load to other workers.

### ISSUE THREAD

**Issue by avnovikov** [dask/dask#4700] opened 2019-04-14 13:24 UTC
Dask worker utilises an enormous amount of memory before distributing load to other workers when loading relatively large ~1Gb gziped parquet files for the simple _repartition - apply - save_ operation 
```
ddf = dd.read_parquet(symbol)
npartitions = 1000
ddf = ddf.repartition(npartitions = npartitions)
ddf['start_timestamp'] = ddf['datetime'] - pd.Timedelta('1m')
ddf['end_timestamp'] = ddf['datetime'] + pd.Timedelta('1m')
assert 'imo' in ddf.columns
ddf['imo_grouper'] = ddf['imo'] #Is it a bug in the DASK?
final_df = ddf.groupby('imo_grouper').apply(lambda x: generate_port_events_map(x), meta=meta)
final_df.to_parquet(HOURLY_FINAL, partition_on=['imo'], compression='GZIP', append=True)
```
running on the distributed client on the single node

1) one of the worker processes reads the parquet file and grows up to 8Gb
2) it continues to grow up to maximum allowed limit and dies for the following combinations

```
# of workers = 8 memory_limit = 32

# of workers = 16 memory_limit = 16
# of workers = 16 memory_limit = 32
# of workers = 16 memory_limit = 60

# of workers = 32 memory_limit = 32
# of workers = 32 memory_limit = 60
```
it works at 
```
# of workers = 8 memory_limit = 64
# of workers = 16 memory_limit = 128
# of workers = 32 memory_limit = 256 (max memory at 72Gb)
```
Only after the worker reaches that high memory level it distributes the load to all other workers.

**Comment by martindurant** [comment] 2019-04-14 13:31
(edited the syntax so we could read it - note that github will render text as markdown)

**Comment by jcrist** [comment] 2019-04-15 12:34
How is this file partitioned? How large is the uncompressed data? A 1 GB file may expand to a much larger amount of data - if it's not partitioned it would have to be loaded all on the same machine before splitting out amount workers.

**Comment by avnovikov** [comment] 2019-04-15 13:19
It has just one partition - the problem as stated is that it first seems to load it into the memory (that seems fine, however, no read is shown on dashboard)  but then it rereads it and occupies memory roughly proportional to the number of workers. 
The problem was solved by loading pandas dataframe and doing 
```
            future_pe = []
            future_pe.extend(ddf.groupby('imo_grouper').apply(lambda x: client.submit(generate_port_events_map, x)).tolist())
            pe = client.gather(future_pe)
            final_df = pd.concat(pe, sort=False)
```
This is definetely not the solution for the file larger than a memory clause.

**Comment by jcrist** [comment] 2019-04-30 16:31
The first ready is just extracting the metadata (schema, etc...), and shouldn't be reading the whole file (although gzipped files will require decompression to read). Since it's only a single partition, you'd need to repartition it to divide the work up (which you're doing). This *may* be a scheduler fail case - we'd expect the scheduler to do the partitioning task on the same node that the data exists, then send the smaller partition to the new worker, but this may instead be sending the full dataset to the worker and then doing the partitioning there instead (thus increasing your memory usage). Scheduling is done heuristically, and our heuristics may be deciding that the cost to send the data is less than the cost of letting your other workers remain idle waiting for work.

Why are you scaling up to 1000 partitions? Generally you want around 10-100 MiB of data per partition, I would expect a 1 GiB gzipped parquet file to be much smaller than that. You might try with fewer partitions, or using the threaded scheduler which wouldn't serialize data out-of-process.

A [reproducible example](https://blog.dask.org/2018/02/28/minimal-bug-reports) would make it easier for us to help diagnose your issue.

**Comment by mrocklin** [comment] 2019-04-30 18:48
> It has just one partition

I would just use Pandas.  Dask won't provide any benefits to single-partition parquet files.

**Comment by avnovikov** [comment] 2019-05-01 11:08
> > It has just one partition
> 
> I would just use Pandas. Dask won't provide any benefits to single-partition parquet files.

The problem is to use groupby apply on approx 20 000 groups in parallel as done in my example workaround.

**Comment by mrocklin** [comment] 2019-05-01 13:55
Dask dataframe is particularly slow for groupby apply if the thing on which
you're grouping isn't the index.

**Comment by avnovikov** [comment] 2019-05-01 17:35
> Dask dataframe is particularly slow for groupby apply if the thing on which you're grouping isn't the index.
 Do you think that map_partitions may work better in this case?

**Comment by TomAugspurger** [comment] 2019-05-23 17:54
> > Dask dataframe is particularly slow for groupby apply if the thing on which you're grouping isn't the index.
> 
> Do you think that map_partitions may work better in this case?

map_partitions doesn't need to communicate data across partitions, so probably.

Going to close this since we're lacking a reproducible example, but if you can provide one @avnovikov we'll reopen. http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports may be worth reading through.

**Closed by TomAugspurger** 2019-05-23 17:54 UTC
