### ISSUE TITLE
dataframe.map_partitions creates additional partitions

### ISSUE THREAD

**Issue by olivier-lacroix** [dask/dask#2453] opened 2017-06-13 22:39 UTC
Hi,

I am using dask (0.14.3) (Python 3.6.1 :: Anaconda 4.4.0 (64-bit)) and have run into an issue using dataframe.map_partitions

X is a dask dataframe with 4532 partitions, that I want to transform thanks to a function of the type

```
def f(df, other_input):
      ...
     return df2
```

Trying the following, Y has 2 additional partitions when compared to X

`Y = X.map_partitions(f,other_input,meta={'Timestamp':'datetime64[ns]','result':'float32'})`

but the following works OK

`Y = X.map_partitions(lambda df: f(df,other_input),meta={'Timestamp':'datetime64[ns]','result':'float32'})`

While, according to the documentation, both statements should be equivalent?

**Comment by mrocklin** [comment] 2017-06-14 12:32
Thanks for the bug report @olivier-lacroix .  What you describe certainly sounds odd and undesired.  Are you able to provide a small example that we can use to easily reproduce this bug?  That would greatly help us to identify and resolve the problem.

**Comment by jcrist** [comment] 2017-06-16 17:16
Is your `other_input` a pandas dataframe/series? If so, `map_partitions` will automatically convert it to a dask dataframe, and then align the partitions, resulting in a change in partitioning. For many pandas operations this is what's desired (e.g. elementwise operations aligned on the index). I suspect that this is the cause here.

```python
In [1]: import pandas as pd

In [2]: import dask.dataframe as dd

In [3]: df = pd.DataFrame({'a': range(1000)})

In [4]: ddf = dd.from_pandas(df, npartitions=10)

In [5]: extra = pd.DataFrame({'b': range(100)})

In [6]: def f(x, extra):
   ...:     return x  # identity, just for showing alignment step with `extra`
   ...:

In [7]: ddf.npartitions
Out[7]: 10

In [8]: res = ddf.map_partitions(f, extra)  # extra is a pandas dataframe

In [9]: res.npartitions  # repartitioned to `11` partitions during alignment with `extra`
Out[9]: 11
```

If you want to pass the same pandas dataframe/series to a function mapped across all partitions, you can avoid this behavior by wrapping the dataframe/series in a tuple/list (or any other python object), or refer to it as a global as you demonstrated in your issue. Note that if you're working in multiple processes/distributed, using a global may result in performance penalties due to serialization.

```python
# avoid partitioning/alignment by wrapping in a tuple
In [10]: res = ddf.map_partitions(f, (extra,))

In [11]: res.npartitions  # same number of partitions as `ddf`
Out[11]: 10
```

**Comment by olivier-lacroix** [comment] 2017-06-17 04:13
Hi Jim, yes, the `other_input` was a pandas dataframe. Thanks for your explanations! 

I understand this behavior makes sense in many cases, but it was still a bit unexpected, especially since it does not seem to be documented ?

Maybe adding the information to the documentation as well as your suggestions to work around it would be a good idea?

Cheers,

Olivier

**Comment by mrocklin** [comment] 2018-10-23 22:54
Seems to be resolved.  Closing.

**Closed by mrocklin** 2018-10-23 22:54 UTC
