### ISSUE TITLE
delayed class method

### ISSUE THREAD

**Issue by eddienko** [dask/dask#3317] opened 2018-03-23 21:18 UTC
There seems to be an issue using  delayed as decorator in classes. I found a similar issue in the toolz library here that may be related (https://github.com/pytoolz/toolz/issues/219). Example code:

```python
class A:
    @dask.delayed
    def test(self, a, b):
        return a + b
    
t = A()
t.test(3, 4).compute()
```

produces the following error:

```python
TypeError: test() missing 1 required positional argument: 'b'
```
Removing the decorator and using:

```python
dask.delayed(t.test)(3, 4).compute()
```
works as expected.

Versions: dask=0.17.1, cytoolz=0.9.0.1, Python=3.6.4

**Comment by jakirkham** [comment] 2018-05-27 00:38
As a workaround, can always rewrite this to use a `delayed` function like so...

```python
class A:
    def test(self, a, b):
        return A_test(self, a, b)

@dask.delayed
def A_test(A_obj, a, b):
    return A_obj.test(a, b)
    
t = A()
t.test(3, 4).compute()
```

**Comment by ZiyaoWei** [comment] 2018-07-08 00:55
I looked at this and it seems @eddieko is absolutely correct - the linked issue's fix will also work here. I would prefer `types.MethodType` over `curry` since the former is builtin, but other than that all the tests pass and class methods also work.

The cause is somewhat cool - since `@delayed` is a decorator, it basically set `test=delayed(test)`, which means `test` isn't a method but is instead a callable object. However, the wrapper treats `test` as a regular three argument function, which caused the issue. Using descriptor and `__get__` can bind `self` correctly to the first argument when the decorator is on a method, thus resolving the bug.

I'll submit a pull request if all that sounds about right!

**Closed** 2018-07-14 21:09 UTC
