### ISSUE TITLE
Showing ellipsis instead of values (Python3, Jupyter)

### ISSUE THREAD

**Issue by tigikay** [dask/dask#3497] opened 2018-05-15 08:50 UTC
Trying to read a csv file that was compiled in Pandas and then saved. I now try to open the file with dask.DataFrame and instead of values I'm shown ellipsis and the format of values (float64, etc).

Some of my values are string, don't know if that is the issue.

The resulting columns look like this:

```
a=dd.read_csv('APG.csv')

a=dd.read_csv('APG.csv')

a.ra_x

a.ra_x
Dask Series Structure:
npartitions=8
    float64
        ...
     ...   
        ...
        ...
Name: ra_x, dtype: float64
Dask Name: getitem, 32 tasks
```

Can't find any related questions or issues, so apologies if this issue has been resolved in the past.

**Comment by tigikay** [comment] 2018-05-15 08:51
Also, when I try to select a part of a column via index I am met with this error:

`
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-36-d70f603725d9> in <module>()
----> 1 a.ra_x[100]

/usr/local/lib/python3.6/site-packages/dask/dataframe/core.py in __getitem__(self, key)
   1930             return Series(merge(self.dask, key.dask, dsk), name,
   1931                           self._meta, self.divisions)
-> 1932         raise NotImplementedError()
   1933 
   1934     @derived_from(pd.DataFrame)

NotImplementedError: `

**Comment by mrocklin** [comment] 2018-05-15 11:41
Dask dataframes are lazy.  They do not load values until you call compute.  In your case you probably want the `.head()` method.

Dask dataframes also don't support indexing with numeric locations.  This is also hard to do lazily.

**Comment by TomAugspurger** [comment] 2018-05-18 02:18
@tigikay I think both of these are by design, and not bugs, so I'll close this.

**Closed by TomAugspurger** 2018-05-18 02:18 UTC
