### ISSUE TITLE
dask.dataframe read_csv, to_csv crashes when '#' in path

### ISSUE THREAD

**Issue by schnekke** [dask/dask#5036] opened 2019-07-01 14:49 UTC
$ pip freeze | grep -E 'dask|pandas'
dask==2.0.0
pandas==0.24.2

```
import dask.dataframe as ddf
import pandas as pd
from os import mkdir
from os.path import join
folder='Fdcm #31H~Vell 1_Out'
mkdir(folder)
df = pd.DataFrame({'A': [1, 1], 'B': [3, 3]})
df.to_csv(join(folder,'fil.csv'))
df2=ddf.from_pandas(df,npartitions=1)
df2.to_csv(join(folder,'fil2*.csv'))
```

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\dataframe\core.py", line 1167, in to_csv
    return to_csv(self, filename, **kwargs)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\dataframe\io\csv.py", line 661, in to_csv
    delayed(values).compute(scheduler=scheduler)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\compatibility.py", line 112, in reraise
    raise exc
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*args2)
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\dataframe\io\csv.py", line 508, in _write_csv
    with fil as f:
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\bytes\core.py", line 183, in __enter__
    f = SeekableFile(self.fs.open(self.path, mode=mode))
  File "%USERPROFILE%\Miniconda3\lib\site-packages\dask\bytes\local.py", line 61, in open
    return open(self._normalize_path(path), mode=mode)
FileNotFoundError: [Errno 2] No such file or directory: '%USERPROFILE%\\Projects\\Fdcm \\0.part'
```

**Comment by TomAugspurger** [comment] 2019-07-01 15:51
cc @martindurant 

In `infer_storage_options`, we have

```python
(Pdb) ll
329     def infer_options(urlpath):
330         if hasattr(urlpath, "name"):
331             # deal with pathlib.Path objects - must be local
332             urlpath = str(urlpath)
333             ispath = True
334         else:
335             ispath = False
336
337         options = infer_storage_options(urlpath)
338  ->     protocol = options.pop("protocol")
339         urlpath = options.pop("path")
340
341         if ispath and protocol != "file":
342             raise ValueError("Only use pathlib.Path with local files.")
343
344         return urlpath, protocol, options
(Pdb) pp options
{'path': 'Fdcm ',
 'protocol': 'file',
 'url_fragment': '31H~Vell 1_Out/fil2*.csv'}
```

I'm not sure what the expected behavior with `#` is here.

**Comment by martindurant** [comment] 2019-07-01 15:57
urllib's urlsplit apparently does `<scheme>://<netloc>/<path>?<query>#<fragment>`
(because URLs can include anchors?)

So we could just join the fragment back on? That would be in `infer_storage_options`. I can do it tomorrow.

**Comment by TomAugspurger** [comment] 2019-07-01 16:45
Seems reasonable. I don't imagine the current behavior is preferable to that.

**Comment by jrbourbeau** [comment] 2019-11-26 04:06
Closing as the original failing example is passing on the current `master` branch of `dask` (0ecb05ffb0eda4d85a332c5d3c09bd37228ee4b2) and `fsspec` (https://github.com/intake/filesystem_spec/commit/3e2abdc5ce1617c3faa4946833050f684cf4bb66). @schnekke feel free to re-open if you're still experiencing issues.

**Closed by jrbourbeau** 2019-11-26 04:06 UTC
Labels: dataframe, io
