### ISSUE TITLE
Bug? Dask randomly hangs on 1-2 open tasks if the memory target is reached.

### ISSUE THREAD

**Issue by cgi1** [dask/dask#6460] opened 2020-07-27 16:14 UTC
Pretty random I get the following situation: 

The dask `cluster = LocalCluster(n_workers=28, host='192.168.56.11')` works good until some lonely task is hanging. 

Checking the logs, I see a traceback (check below) but the code does not throw the error as well as the operation which causes it. What would be a suggestion to find out, which worker hangs on which piece of code?

<img width="1675" alt="grafik" src="https://user-images.githubusercontent.com/18695252/88564971-38520e80-d034-11ea-92f5-18311456a40c.png">

**Environment**:

- Dask version:
```
dask==2.17.0
dask-jobqueue==0.7.1
```
- Python version: 3.8
- Operating System: Ubuntu 20.04
- Install method (conda, pip, source): pip3

**Tracebacks**:

```
distributed.worker - ERROR - cannot reshape array of size 0 into shape (4,687654)
Traceback (most recent call last):
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/worker.py", line 2511, in execute
    data[k] = self.data[k]
  File "/usr/lib/python3/dist-packages/zict/buffer.py", line 70, in __getitem__
    return self.slow_to_fast(key)
  File "/usr/lib/python3/dist-packages/zict/buffer.py", line 57, in slow_to_fast
    value = self.slow[key]
  File "/usr/lib/python3/dist-packages/zict/func.py", line 39, in __getitem__
    return self.load(self.d[key])
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 502, in deserialize_bytes
    return deserialize(header, frames)
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 302, in deserialize
    return loads(header, frames)
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 64, in pickle_loads
    return pickle.loads(x, buffers=buffers)
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 64, in loads
    return pickle.loads(x, buffers=buffers)
  File "/home/cgi/.local/lib/python3.8/site-packages/numpy/core/numeric.py", line 1783, in _frombuffer
    return frombuffer(buf, dtype=dtype).reshape(shape, order=order)
ValueError: cannot reshape array of size 0 into shape (4,687654)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fa5a27aea90>>, <Task finished name='Task-4908' coro=<Worker.execute() done, defined at /home/cgi/.local/lib/python3.8/site-packages/distributed/worker.py:2494> exception=ValueError('cannot reshape array of size 0 into shape (4,687654)')>)
Traceback (most recent call last):
  File "/home/cgi/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/cgi/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/worker.py", line 2511, in execute
    data[k] = self.data[k]
  File "/usr/lib/python3/dist-packages/zict/buffer.py", line 70, in __getitem__
    return self.slow_to_fast(key)
  File "/usr/lib/python3/dist-packages/zict/buffer.py", line 57, in slow_to_fast
    value = self.slow[key]
  File "/usr/lib/python3/dist-packages/zict/func.py", line 39, in __getitem__
    return self.load(self.d[key])
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 502, in deserialize_bytes
    return deserialize(header, frames)
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 302, in deserialize
    return loads(header, frames)
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 64, in pickle_loads
    return pickle.loads(x, buffers=buffers)
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 64, in loads
    return pickle.loads(x, buffers=buffers)
  File "/home/cgi/.local/lib/python3.8/site-packages/numpy/core/numeric.py", line 1783, in _frombuffer
    return frombuffer(buf, dtype=dtype).reshape(shape, order=order)
ValueError: cannot reshape array of size 0 into shape (4,687654)
```

**Comment by mrocklin** [comment] 2020-07-27 16:33
cc @jakirkham due to the serialization focus in case this looks familiar to
him.

**Comment by jakirkham** [comment] 2020-07-27 18:53
Are you able to share the code you are running, @cgi1? Or if not that code, is there code that you could create that reproduces the error and could be shared?

**Comment by cgi1** [comment] 2020-07-27 23:38
@jakirkham. Sadly I am not.. This is a 300 million row data set and I can not provide any data. Regarding the code: So this are a lot of different operations and if I would know, which kind of operation causes the issue I would be happy to share... But the traceback does not offer a chance to get the exact code around it. 

It is good to be mentioned, that the issue does not appear every time when the code runs, but it just triggered a second time (now 4 tasks are hanging).. So are there specific operations to look for?:

![grafik](https://user-images.githubusercontent.com/18695252/88602268-bfbe7280-d072-11ea-8a26-0aa5b001cf7e.png)

**Comment by jakirkham** [comment] 2020-07-27 23:52
Hard to say without knowing more about the workflow 😢

Looking at the traceback it appears to be related to loading some data back into memory that was previously spilled. The error also seems to indicate that maybe some of the data was lost, but I'm not sure why that would be. Though this doesn't necessarily relate to a specific operation.

My only suggestion at this point would be to start simplifying this workflow down to the point where the issue can be isolated. Better still if it results in code that can be more easily shared. Though the exercise of reducing the code alone may already make it more clear where the issue is coming from.

**Comment by cgi1** [comment] 2020-07-28 01:21
Could it be an issue because of a worker which died during processing? It looks like during processing the system runs into a load 42 over a certain time and from the original 28 workers only 24-27 overstay the complete workflow everytime. 

Furthermore, I see these warnings:

```
distributed.utils_perf - WARNING - full garbage collections took 28% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 23% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 29% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 30% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 21% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 24% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 22% CPU time recently (threshold: 10%)
```

On that amount of data splitting and re-running the code again piece-by-pice would consum a lot of time due to the loading times from CSV into a ddf between each step (up to three minutes each).. So I just want to make sure that the issue is not somewhere else..

**Comment by cgi1** [comment] 2020-07-28 01:48
Oh so I guess it is this piece of code: 

Pre: It is loading 8 huge CSVs (up to 70.000.000 rows each) into a dictonary called `ddf_all`, where the key name is the file name:

```
    def get_ddf_from_csv(...):
        mydateparser = lambda x: pd.to_datetime(x, format=DATETIME_FORMAT, errors='coerce')
        if v: print("Start to load (%s) into dask cluster." % csv_path)
        ddf = dd.read_csv(csv_path,
                      infer_datetime_format=False,
                      parse_dates=[ts_col],
                      date_parser=mydateparser,
                      keep_date_col=False,
                      assume_missing=True,
                      sep=',')
        s_ts_is_na = datetime.datetime.now()
        ddf[ts_col] = ddf[ts_col].fillna(np.datetime64('NaT'))
        isna_ddf = ddf.ts.isna()
        ddf = ddf.loc[~isna_ddf]
        e_ts_is_na = datetime.datetime.now()
        print("Debug>Took (%s) to filter na ts rows." % (e_ts_is_na - s_ts_is_na))
        # ...
        return ddf

    def async_get_ddf_from_csv(csv_path, sorted_data=False, v=True):
        fname = csv_path.split('/')[-1]
        if v: print("\nCreating %s in ddf_all" % fname)
        ddf_all[fname] = None
        try:
            ddf_all[fname] = get_ddf_from_csv(dd=dd, client=client, symbol_dict_ids_first=symbol_dict_ids_first,
                                              all_stats_m1=all_stats_m1, csv_path=csv_path,
                                              persist=True, sorted_data=sorted_data)
        except:
            print("Error>Failed to get_ddf_from_csv (%s) (%s)" % (csv_path, traceback.format_exc()))

    # Async loading of CSVs in dict called df_all[$name_of_file], where each value is a dask dataframe.
    with ThreadPoolExecutor(max_workers=MAX_WORKERS_csvs_to_ddf) as executor:
        futures_to_todo = []
        submitted_fnames = []
        for fname in sorted(os.listdir(ASCII_DIR)):
            if not fname.endswith(suffix):
                print("Skipping %s" % fname)
                continue
            if prefix != '*' and not fname.startswith(prefix):
                print("Skipping %s" % fname)
                continue
            csv_path = os.path.join(ASCII_DIR, fname)
            if show_status: print("Start future for %s" % csv_path)
            futures_to_todo.append(executor.submit(async_get_ddf_from_csv, csv_path=csv_path, sorted_data=sorted_data, v=show_status))
            submitted_fnames.append(csv_path)
        if show_status: print("Created %s futures for (%s)." % (len(futures_to_todo), submitted_fnames))
        wait(futures_to_todo)
```

Afterwards, the code which executes very slowly and finally throws the exception is this one:

        print("# BATCH-LOAD DDF REPORT")
        for fname, loaded_l1sorted in ddf_all.items():
            try:
                if DEBUG:
                    s_index_len = datetime.datetime.now()
                    len_of_chunk = len(loaded_l1sorted.index) # <<< HERE <<< This takes up to 6 minutes with very low CPU load to count 70.000.000 rows.. strange!
                    e_index_len = datetime.datetime.now()
                    print("DebugEXPENSIVE>Took %s to count %s rows in %s." % ((e_index_len-s_index_len), len_of_chunk, fname))

**Comment by cgi1** [comment] 2020-07-29 20:55
And another one.. This time all workers are alive:

<img width="1228" alt="grafik" src="https://user-images.githubusercontent.com/18695252/88851936-d0472800-d1ed-11ea-951b-dda52269159f.png">

Hangs there in `len(ddf_c.index)` from a `published dataset`. The `dataset` has been `client.persist()` before going to the `datasets`. As soon as I cancel the operation from Jupyter Notebook, the hanging tasks disapear, but when I rerun the operation, the same `len(ddf.index)` hangs on that 16 processes forever and there is no movement in the CPU:

<img width="764" alt="grafik" src="https://user-images.githubusercontent.com/18695252/88852234-48ade900-d1ee-11ea-8992-96834ffcf06b.png">

But when I look into `LocalCluster` logs I now see

```
e other process is leaking memory?  Process memory: 12.47 GB -- Worker memory limit: 15.22 GB
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 12.47 GB -- Worker memory limit: 15.22 GB
[...repeated 20 times a second round about...]
```

When I then `restart` the whole cluster, reload the data and run the same code it works for some time again.. Strange!

**Comment by cgi1** [comment] 2020-07-30 21:35
Another one, this time with five freezed `loc-series`. All workers alive. The error also persists when re-reading the data from the `published dataset`. Only a `cluster.restart()` helps, then five minute re-loading the data into the cluster and then loading it via `client.datasets[$dataset_name]`... Takes like 6 mintes each time it crashes.. What could be a good starting point to debug it?

<img width="742" alt="grafik" src="https://user-images.githubusercontent.com/18695252/88976604-9bee6d00-d2bc-11ea-9fa5-2f0d1f52b9b4.png">

Equal stacktrace:

```
ValueError: cannot reshape array of size 0 into shape (4,650059)
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <torna
bject at 0x7f6d93beca30>>, <Task finished name='Task-56115' coro=<Worker.execute() done, defined at /home/cgi/.local/lib/py
/worker.py:2494> exception=ValueError('cannot reshape array of size 0 into shape (4,651255)')>)
Traceback (most recent call last):
  File "/home/cgi/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/cgi/.local/lib/python3.8/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/worker.py", line 2511, in execute
    data[k] = self.data[k]
  File "/usr/lib/python3/dist-packages/zict/buffer.py", line 70, in __getitem__
    return self.slow_to_fast(key)
  File "/usr/lib/python3/dist-packages/zict/buffer.py", line 57, in slow_to_fast
    value = self.slow[key]
  File "/usr/lib/python3/dist-packages/zict/func.py", line 39, in __getitem__
    return self.load(self.d[key])
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 502, in deserialize_bytes
    return deserialize(header, frames)
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 302, in deserialize
    return loads(header, frames)
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 64, in pickle_loads
    return pickle.loads(x, buffers=buffers)
  File "/home/cgi/.local/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 64, in loads
    return pickle.loads(x, buffers=buffers)
  File "/home/cgi/.local/lib/python3.8/site-packages/numpy/core/numeric.py", line 1783, in _frombuffer
    return frombuffer(buf, dtype=dtype).reshape(shape, order=order)
ValueError: cannot reshape array of size 0 into shape (4,651255)
```

**Comment by cgi1** [comment] 2020-07-30 23:15
Ok, so I further narrowed it down. I can run operations, such as

```
len(ddf.index)
```
successfully multiple times, but everytime I run the cluster needs to perform some operations, so I tried to `ddf = client.persist(ddf)`. And that it the point from where I can not recover the data, because it looks like something (related to the tracebacks) went wrong during `ddf=client.persist(ddf)`

**Comment by jakirkham** [comment] 2020-07-31 01:31
Is `local_directory` specified in the `Client` or `Cluster` (if a custom cluster is being used)? Alternatively is `temporary-directory` specified in [the `dask.config`]( https://docs.dask.org/en/latest/configuration.html#configuration )? If so, where does that point to? If not, what directory is Dask (and Dask `Worker`s) being started in? Is the directory (in any of these cases) pointed to somewhere that allows fast reading and writing (like node local scratch space on solid state) or is something with slow reading and writing (like NFS or a RAID)? If the latter, that may be the source of issues here as it will cause Dask lots of issues when it tries to spill data to disk when memory is running out.

**Comment by cgi1** [comment] 2020-08-01 22:30
`local_dir` is defined as follow:

```
n_workers = 20
host = '192.168.56.11'
DASK_WORKER_SPACE = "/var/dask-worker-space/"
cluster = LocalCluster(n_workers=n_workers, host=host, local_dir=DASK_WORKER_SPACE)
```

..so I would change it to `cluster = LocalCluster(n_workers=n_workers, host=host, local_dir=DASK_WORKER_SPACE, temporary_directory='/var/dask-worker-temp/')`

There is enough space:
```
/dev/mapper/[...]--var   2.0T  524G  1.4T  27% /var
```

Disk is virtual with VmWare
```
cgi@CGI-Research-System2:~$ sudo lshw -C disk
  *-disk:1
       description: SCSI Disk
       product: Virtual disk
       vendor: VMware
       physical id: 0.1.0
       bus info: scsi@32:0.1.0
       logical name: /dev/sdb
       version: 2.0
       size: 2TiB (2199GB)
       capabilities: 7200rpm gpt-1.00 partitioned partitioned:gpt
       configuration: ansiversion=6 guid=33cd60ea-2a65-4fcc-b0ac-bf36853c9d2a logicalsectorsize=512 sectorsize=512
```
 
hdparm timings:

```
cgi@CGI-Research-System2:~$ sudo hdparm -Tt /dev/sdb

/dev/sdb:
 Timing cached reads:   17120 MB in  1.99 seconds = 8589.80 MB/sec
SG_IO: bad/missing sense data, sb[]:  70 00 05 00 00 00 00 0a 00 00 00 00 20 00 00 c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 Timing buffered disk reads: 2034 MB in  3.00 seconds = 677.63 MB/sec
```

So looks fine?

**Comment by cgi1** [comment] 2020-08-02 00:27
`temporary_directory` is not a valid option for `LocalCluster`

**Comment by cgi1** [comment] 2020-08-03 20:09
So - I narrowed it down and it crashes with the mentioned Expection (`ValueError: cannot reshape array of size 0 into shape (4,651255)`), when I try to `persist` a dask dataframe like this:

```
ddf_c['pair_code'] = (ddf_c.a + ';' + ddf_c.mdate.astype(str))
ddf_c = client.persist(ddf_c) # This hangs forever
```

I scrolled back to the first exception, which is really a **connection timeout between worker and scheduler**:

```
ERROR - Worker stream died during communication: 'tcp://192.168.56.11:42691' 

OSError: Timed out trying to connect to 'tcp://192.168.56.11:42691' after 3 s: connect() didn't finish in time.

During handling of above expection, another exception occurred:
[...]
ValueError: cannot reshape array of size 0 into shape (4,611409)
```

So I wonder what causes a Timeout here, because the operation is a very simple assign..

**Comment by jakirkham** [comment] 2020-08-03 22:31
Maybe [this doc section]( https://docs.dask.org/en/latest/debugging.html#logs ) is helpful?

**Comment by cgi1** [comment] 2020-08-05 18:28
So I further digged into it and this HANGING really pops up, **when we reach the `memory target`, as defined in `dask.config.config`**:


Original:
````
   'memory': {'target': 0.60, 'spill': 0.7, 'pause': 0.8, 'terminate': 0.9},
```

The code hangs at around 172GB in memory and that looks fitting to the original 60% of 283GB RAM in the server (60% equals 170GB).


So next I changed the `memory` limits accordingly:

````
   'memory': {'target': 0.75, 'spill': 0.8, 'pause': 0.9, 'terminate': 0.96},
```

and restarted the code. And everything worked perfect, because we have been under `memory->target` boundaries. 

So what actually happens, after the memory `target/spill` has been reached? I was thinking, that there is some outsaving to the `temporary_directory` or some other disk location? Instead it crashes (for me) at this point in time.

**Comment by cgi1** [comment] 2020-08-05 21:37
# I can definitly validate, that the Error occures every time when `target` or `spell` memory limit is hit. Also on other operations.

**Comment by jakirkham** [comment] 2020-08-05 22:52
Great, would you be able to refine that into an [MRE]( http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports )? I think that is what we would need to diagnose where it is coming from, devise a fix, and include an appropriate test (based on that MRE).

**Comment by jcrist** [comment] 2020-09-11 14:52
Any update here @cgi1?

**Comment by cgi1** [comment] 2020-09-12 08:36
The update is, that it is still happening as written in the big characters.

To dig deeper into this, this question is still open:

> So what actually happens, after the memory target/spill has been reached? I was thinking, that there is some outsaving to the temporary_directory or some other disk location? Instead it crashes (for me) at this point in time.

**Comment by jakirkham** [comment] 2021-04-09 19:32
@cgi1 are you still seeing this issue with the recent release? There have been a ton of changes to serialization and communication over the past several months. So would be good to confirm whether it still exists

**Comment by quasiben** [comment] 2023-03-14 17:32
Closing as there have been many improvements since this was first opened.   Feel free to reopen if you are able to get an MRE

**Closed by quasiben** 2023-03-14 17:32 UTC
