### ISSUE TITLE
Issue with reading parquet file output from Spark with partition columns using pyarrow-dataset engine

### ISSUE THREAD

**Issue by liuyangc1** [dask/dask#7512] opened 2021-04-02 20:32 UTC
**What happened**: I am reading a parquet file output from sparklyr code and partitioned on column ['a', 'b', 'c'] using `pyarrow-dataset` engine, but encounter below error message: 
`ValueError: partition(s) should not exist in columns.`

I went to the source code and find that it's due to these lines of code. [https://github.com/dask/dask/blob/main/dask/dataframe/io/parquet/arrow.py#L1090-L1094](https://github.com/dask/dask/blob/main/dask/dataframe/io/parquet/arrow.py#L1090-L1094)
It's because the column names have overlap with partition keys. I think it's because the output from sparkly doesn't contain metadata file, dask didn't recognize it properly. There is no issue reading this file with `pyarrow` or `pyarrow-legacy` engine. If reading the file in using `pyarrow-legacy` engine, and write out using dask, then read back in with `pyarrow-dataset`, there is no issue. 

**What you expected to happen**: I want to be able to read the parquet file output from spark with partition columns directly using `pyarrow-dataset` engine with dd.read_parquet(),  becuase `pyarrow-dataset` is said to be faster and with more advanced filtering options. 

One more question is that will `pyarrow` or `pyarrow-legacy` engine deprecated some time? If so, what's the estimate time?

**Minimal Complete Verifiable Example**:

```python
# Put your MCVE code here
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2021.03.1
- Python version: 3.8
- Operating System:
- Install method (conda, pip, source):

**Comment by jsignell** [comment] 2021-04-05 19:41
From your description it seems like sparklyr is writing the file incorrectly. Is that also your interpretation?

**Comment by jsignell** [comment] 2021-04-05 19:42
Ping @rjzamora for estimate on `pyarrow-legacy` deprecation plan.

**Comment by liuyangc1** [comment] 2021-04-05 19:46
No,  sparklyr is writing the file properly, we are using databricks to run the sparklyr code, which gives parquet files with no metadata. We are okay with the file created by the sparklyr code, I am able to consume it elsewhere, but not using pyarrow-dataset engine on dask.

**Comment by jsignell** [comment] 2021-04-05 20:14
Ok thanks for that, there might be some issues with pyarrow 3, so you could try using pyarrow 2 instead.

**Comment by rjzamora** [comment] 2021-04-06 16:53
>One more question is that will pyarrow or pyarrow-legacy engine deprecated some time? If so, what's the estimate time?

I don't personally have a great estimate at the moment. There are a few downstream libraries that have yet to move to `ArrowDatasetEngine`, because the legacy engine is still a bit faster in some cases (or at least they *were* - I'll need to check pyarrow-3).

>No, sparklyr is writing the file properly, we are using databricks to run the sparklyr code, which gives parquet files with no metadata. We are okay with the file created by the sparklyr code, I am able to consume it elsewhere, but not using pyarrow-dataset engine on dask.

You should be able to read a partitioned dataset without the "_metadata" file, so I agree that there is a problem in Dask if you have problems doing this.  With that said, is your dataset "partitioned" in the conventional (hive-partitioning) sense?  That is, if you read a single file from your dataset, does it include the partitioned column?

For example, if a file is in the `id=1/` directory, it should not include an "id" column if you read the file by itself:
```python
import pyarrow.parquet as pq

pq.ParquetFile('/tmp/test_parquet/id=1/part.0.parquet').read().to_pandas()
```
```
    x
0   1
1   4
2   7
3  10
4  13
```

**Comment by jorisvandenbossche** [comment] 2021-04-07 11:38
In general: there are indeed other systems that write partitioned datasets with keeping the partition columns also as physical columns in the files (as opposed to dask which drops them before writing the files), so I think it would be good for dask to support reading such data (plain ``pyarrow.dataset`` does support that).

Trying to create a reproducible example:

```python
import tempfile
import pathlib
path = pathlib.Path(tempfile.mkdtemp())

df1 = pd.DataFrame({'part': 'a', 'col': range(5)})
df2 = pd.DataFrame({'part': 'b', 'col': range(5)})
(path / "part=a").mkdir()
(path / "part=b").mkdir()
df1.to_parquet(path / "part=a" / "data.parquet", index=False, engine="pyarrow")
df2.to_parquet(path / "part=b" / "data.parquet", index=False, engine="pyarrow")
```

However, the above example fails for me with both `pyarrow-legacy` as `pyarrow-dataset`:

```
In [21]: dd.read_parquet(path, engine="pyarrow-legacy")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-21-0d5b08436f3e> in <module>
----> 1 dd.read_parquet(path, engine="pyarrow-legacy")

~/scipy/repos/dask/dask/dataframe/io/parquet/core.py in read_parquet(path, columns, filters, categories, index, storage_options, engine, gather_statistics, split_row_groups, read_from_paths, chunksize, **kwargs)
    305         index = [index]
    306 
--> 307     read_metadata_result = engine.read_metadata(
    308         fs,
    309         paths,

~/scipy/repos/dask/dask/dataframe/io/parquet/arrow.py in read_metadata(cls, fs, paths, categories, index, gather_statistics, filters, split_row_groups, read_from_paths, **kwargs)
    516 
    517         # Process metadata to define `meta` and `index_cols`
--> 518         meta, index_cols, categories, index = cls._generate_dd_meta(
    519             schema, index, categories, partition_info
    520         )

~/scipy/repos/dask/dask/dataframe/io/parquet/arrow.py in _generate_dd_meta(cls, schema, index, categories, partition_info)
   1094 
   1095         if set(column_names).intersection(partitions):
-> 1096             raise ValueError(
   1097                 "partition(s) should not exist in columns.\n"
   1098                 "categories: {} | partitions: {}".format(column_names, partitions)

ValueError: partition(s) should not exist in columns.
categories: ['part', 'col'] | partitions: ['part']

```

**Comment by rjzamora** [comment] 2021-04-07 13:33
>In general: there are indeed other systems that write partitioned datasets with keeping the partition columns also as physical columns in the files (as opposed to dask which drops them before writing the files), so I think it would be good for dask to support reading such data (plain pyarrow.dataset does support that).

Ah - Interesting.  This actually makes a lot of sense to me, but my only exposure to "partitioned" datasets has been through Dask :)

In the case that the partition column actually exists in the data, I assume that we should always **use** that data (rather than the value embedded in the partition name)?  I can imagine a scenario where the data type is coarsened for the partitioning (e.g. rounding to the nearest day for a timestamp), but the parquet file includes the fully-resolved data type.

**Comment by rjzamora** [comment] 2021-04-08 16:48
Are there systems that use mixed behavior here while partitioning on multiple columns?  That is, is it possible that one partition column will be included in the file while others are not?  I ask, because it is slightly easier to support all or nothing.

**Comment by liuyangc1** [comment] 2021-04-19 17:42
Thank you a quick look at this issue, @rjzamora ! I didn't see mixed behavior while partitioning on multiple columns in my use case. I saw the PR #7541 , do you know this PR will be included in which dask release version?

**Comment by liuyangc1** [comment] 2021-05-18 13:35
Hi @rjzamora @jsignell, can you help to re-open this isssue? I saw there is a new release and tested the pyarrow-dataset engine. I am still having issue reading parquet file output from Spark with partition columns using pyarrow-dataset engine. I found that the previous error message disappear. But another error arises. 

When using dask version 2020.4.1 or older dask version, I saw `ValueError: partition(s) should not exist in columns.` when trying to read parquet output from spark with partition columns.

When using dask version 2021.5.0, the read_parquet() didn't give any error, but when I print head or try to write out the file I just read, it raises the `KeyError: "['partition_column_1', 'partition_column_2'] not in index"`.

**Comment by rjzamora** [comment] 2021-05-18 13:49
No problem @liuyangc1 - I'm happy to re-open, but I don't hink I will personally have time to debug and fix the problem unless someone can offer a simple self-contained reproducer (without using Spark).

**Comment by liuyangc1** [comment] 2021-05-18 15:22
Thank you @rjzamora. I can not find a case that will reproduce this error without using Spark so far. But I can provide more observations. First, pyarrow engine doesn't have this issue. But we still prefers to use pyarrow-dataset to incorporate the new features of pyarrow-dataset engine.

Second, when I am testing the new release using dask version 2021.5.0, I found that if I read the parquet using pyarrow-dataset engine, and specify the columns to exclude the columns ['partition_column_1', 'partition_column_2'], it allows me to print the head and didn't give the error message. But as long as the 'partition_column_1' or 'partition_column_2' are included when reading the parquet, it will give the above error.

**Comment by liuyangc1** [comment] 2021-06-01 19:15
I tested the pyarrow.dataset package, it doesn't have issue to read the parquet output from spark with partition keys by running below code ```import pyarrow.dataset as ds
df = ds.dataset(“file”)
df.to_table().to_pandas()``` This works well. 
```df = dd.read_parquet("file", engine = "pyarrow") ```This also works well. 
```df = dd.read_parquet("file", engine = "pyarrow-dataset") ``` This generates the ```KeyError: "['partition_column_1', 'partition_column_2'] not in index"```

**Comment by isaiahc0** [comment] 2021-07-30 05:32
As a workaround, add a filters=[[('partition_by_col', '!=', '')]] when reading Dataset created by hive when using the pyarrow-dataset engine. There appears to be an issue creating the index by dask otherwise.

Using ParquetDataset from pyarrow is working without any issues.

**Comment by jcrist** [comment] 2022-04-27 20:55
Since we cannot reproduce this issue (both with and without spark), I'm going to close this for now. If someone can provide a reproducible example please feel free to reopen.

**Closed by jcrist** 2022-04-27 20:55 UTC
Labels: dataframe, io, parquet
