### ISSUE TITLE
Internal Server Error 500, when client is interrupted

### ISSUE THREAD

**Issue by nilslacroix** [dask/dask#8949] opened 2022-04-19 13:54 UTC
**What happened**:
I am using a distributed client on a local machine with:

```
from dask.distributed import Client
client = Client(n_workers=6, threads_per_worker=2)
client
```
Sometimes when I compute something with compute() and cancel the processes in Jupyter Notebook by Interrupting the Kernel (while dask is still working), the next time I restart the client with the code above I get an "Internal Server Error 500".

I tried to do:

```
client.restart()
client.close()
client.shutdown()
```

But nothing was able to get the dask dashboard running again.
I just would like to know a way to restart the server/cluster/client, withoutt rebooting the whole machine.

**Environment**:

- Used in Jupyter Notebook
- Anaconda, Windows 10
- Dask 2022 4.1

The error message I got:
C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\distributed\node.py:177: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 64123 instead
  warnings.warn(

```
2022-04-19 15:44:06,815 - distributed.utils - ERROR - 'str' object has no attribute 'text'
Traceback (most recent call last):
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\distributed\utils.py", line 693, in log_errors
    yield
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\distributed\dashboard\components\scheduler.py", line 355, in update
    self.root.title.text = title
AttributeError: 'str' object has no attribute 'text'
2022-04-19 15:44:06,817 - distributed.utils - ERROR - 'str' object has no attribute 'text'
Traceback (most recent call last):
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\distributed\utils.py", line 693, in log_errors
    yield
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\distributed\dashboard\components\scheduler.py", line 3645, in status_doc
    cluster_memory.update()
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\bokeh\core\property\validation.py", line 95, in func
    return input_function(*args, **kwargs)
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\distributed\dashboard\components\scheduler.py", line 355, in update
    self.root.title.text = title
AttributeError: 'str' object has no attribute 'text'
2022-04-19 15:44:06,819 - tornado.application - ERROR - Uncaught exception GET /status (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:63474', method='GET', uri='/status', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\bokeh\server\views\doc_handler.py", line 54, in get
    session = await self.get_session()
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\bokeh\server\views\session_handler.py", line 144, in get_session
    session = await self.application_context.create_session_if_needed(session_id, self.request, token)
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\bokeh\server\contexts.py", line 243, in create_session_if_needed
    self._application.initialize_document(doc)
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\bokeh\application\application.py", line 194, in initialize_document
    h.modify_document(doc)
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\bokeh\application\handlers\function.py", line 143, in modify_document
    self._func(doc)
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\distributed\dashboard\components\scheduler.py", line 3645, in status_doc
    cluster_memory.update()
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\bokeh\core\property\validation.py", line 95, in func
    return input_function(*args, **kwargs)
  File "C:\Users\nish\miniconda3\envs\Master_ML\lib\site-packages\distributed\dashboard\components\scheduler.py", line 355, in update
    self.root.title.text = title
AttributeError: 'str' object has no attribute 'text'

```

**Comment by bryanwweber** [comment] 2022-04-19 14:02
@nilslacroix Thanks for reporting this issue! Can you please add a [minimal, complete, verifiable example](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) code to your post? That really helps us reproduce the issue to work out what to do. Thank you!

**Comment by mrocklin** [comment] 2022-04-19 19:50
So, I took a look at this briefly and was surprised by the error message.  It seems to imply that `self.root.title` is a string, which is strange because it's a bokeh object that we never touch directly.

**Comment by mrocklin** [comment] 2022-04-19 19:52
If the scheduler is borked in some way then there is no way to restart it other than restarting the scheduler process.  Calling client.restart clears out scheduler state and does a full process restart on the workers, but doesn't restart the scheduler itself.

**Comment by mrocklin** [comment] 2022-04-19 19:53
Typically the scheduler is run by something else that keeps it up, like Kubernetes or systemd.  It is very rare for it to shut down itself.  We don't do it intentionally.

**Comment by pavithraes** [comment] 2022-04-25 14:33
@nilslacroix Could you please share the bokeh version you're running? There was [this change in bokeh=2.4](https://github.com/bokeh/bokeh/pull/11580) which might be related.

**Comment by pavithraes** [comment] 2022-04-28 15:35
@nilslacroix Thanks, in that case, I'll go ahead and close this. Please feel free to re-open if you see this again!

**Closed by pavithraes** 2022-04-28 15:35 UTC
Labels: needs info
