### ISSUE TITLE
Assign alters dtypes of dataframe columns it should not

### ISSUE THREAD

**Issue by Azorico** [dask/dask#3907] opened 2018-08-27 16:53 UTC
This is my first issue so I apologize for any gaping flaws that might occur.

Say you have a dask dataframe such as:

```
df_raw = dd.from_pandas(pd.DataFrame(data=
                                     {'col1': ['a', 'b', 'c', 'd'],
                                      'col2': [1, 2, 3, 4],
                                      'col3': ['a', 'b', 'c', 'd'] },
                                     columns=['col1', 'col2', 'col3']),
                        npartitions=2)
```
The column dtypes are as follows:

![image_to_issue](https://user-images.githubusercontent.com/25220090/44672235-bf00aa00-aa1f-11e8-92d8-f50a12dd8d4f.png)

Now say you do some operations and wish to assign those to a dictionary :

```
dict_temp = {}
dict_temp['col1_operation'] = pd.Series(['0', '1', '0', '1'])
```
You should get:

`print(dict_temp)`
```
{'col1_operation':
0    0
1    1
2    0
3    1
dtype: object}
```
Then you assign those to the original dataframe such as:

`df_raw.assign(**dict_temp)`

Which gives you:

![image_to_issue](https://user-images.githubusercontent.com/25220090/44672689-13585980-aa21-11e8-9f3e-c4ffbbf18421.png)

As you can see the 'col2' column dtype is changed from 'int64' to 'float64'. As far as I can tell there is no mention of this sort of behaviour. Is this the expected behaviour?

**Comment by TomAugspurger** [comment] 2018-08-27 17:44
https://github.com/dask/dask/blob/54ffe4330d217d50d5a10a8a5869cd0a70d9267c/dask/dataframe/core.py#L2676-L2684 seems faulty to me.

For pandas Series, that ends up doing `self._meta.assign(col=series)`, which forces a `reindex`, which converts the int columns to float.

```python
In [7]: df = pd.DataFrame({"A": pd.Series([], dtype=int), "B": pd.Series([], dtype=object)})

In [8]: df.dtypes
Out[8]:
A     int64
B    object
dtype: object

In [9]: df.assign(col=pd.Series([1, 2, 3])).dtypes
Out[9]:
A      float64
B       object
col      int64
dtype: object
```

We should ensure that for pandas series, we pass through `series.iloc[:0]`, an empty series, rather than the entire series. We can either update `_extract_meta` to ensure we do that, or make an `_extract_meta_empty` if changing `_extract_meta` breaks too many things. Does that make sense?

**Comment by Azorico** [comment] 2018-08-29 12:56
Thank you for your swift reply and your splendorous work. 

Yeah, I think it does, keep the columns we do not wish to tamper with out of the meta inference method. I'll see if I can get around to submit a pull request on this.

**Comment by jhb9** [comment] 2018-10-05 23:08
'astype" is also 'leaking' and affecting other columns as well.  I am working on a large distributed problem and can cast columns to floats, bools or category.  But as soon as I cast any column to 'int', it breaks all functionality on my category columns.  Any operation now returns an error `Cannot convert non-finite values (NA or inf) to integer` for any operation.

**Comment by mrocklin** [comment] 2018-10-05 23:50
@jhb9 if you can provide a small reproducible example (like what is above) and add it here then that would be helpful.

**Comment by jhb9** [comment] 2018-10-06 00:15
I'm trying but I have a million row by 250 column dask dataframe on a distributed cluster that's a mix of floats, ints, bools, and category columns.  It's not share-able . The Dataframe is read from parquet, and one column is an object  with elements from a set of ~3000 strings.  Whether I cast it to category or not,  changing any other column to int will render that column (and others) DOA.  Errors look like

`~/miniconda3/envs/dask-dev/lib/python3.6/site-packages/pandas/core/internals.py in _astype()
    662 
    663                 # _astype_nansafe works fine with 1-d only
--> 664                 values = astype_nansafe(values.ravel(), dtype, copy=True)
    665                 values = values.reshape(self.shape)
    666 

~/miniconda3/envs/dask-dev/lib/python3.6/site-packages/pandas/core/dtypes/cast.py in astype_nansafe()
    700 
    701         if not np.isfinite(arr).all():
--> 702             raise ValueError('Cannot convert non-finite values (NA or inf) to '
    703                              'integer')
    704 

ValueError: Cannot convert non-finite values (NA or inf) to integer`

For some reason changing one column to int, has induced dask to attempt to change this column (and others) to int as well.

**Comment by mrocklin** [comment] 2018-10-06 00:18
If you are able to construct a simple example that exhibits the same
behavior then that would help people identify and resolve the problem.

http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

**Comment by jhb9** [comment] 2018-10-06 01:46
Ah, yes I was recasting some columns that got change to float back to int, in the process I cast some columns that were never int in the first place and contained a NaN, that got integrated into task graph and gave the error when accessing different columns.  I will delete my comments to not clutter the other issue.

**Comment by asmith26** [comment] 2019-07-01 21:41
Hi there,

I just tried the other code, and everything seems to be working now - possibly fixed within: https://github.com/dask/dask/commit/87954ec9d30fcf468bde9dece2d453a5c8dc8d1a ?

**Comment by jrbourbeau** [comment] 2019-07-02 03:22
Thanks for checking on this @asmith26, this issue does appear to be fixed in `master`. Do you have an interest in adding a test to `dask/dataframe/tests/test_dataframe.py` to ensure this bug doesn't pop up again? (no obligation though)

**Comment by asmith26** [comment] 2019-07-02 08:01
Good idea @jrbourbeau - please see https://github.com/dask/dask/pull/5047

Any feedback very welcome.

**Comment by asmith26** [comment] 2019-07-02 12:32
Hmmm.... it seems to have failed, but I can't find the error?

**Closed** 2019-07-02 13:27 UTC
Labels: dataframe, good first issue
