### ISSUE TITLE
GroupBy-Aggregate on multiple categorical columns fails with MemoryError due to pre-allocating full Cartesian product of categories

### ISSUE THREAD

**Issue by ig248** [dask/dask#5820] opened 2020-01-22 13:56 UTC
# Issue
GroupBy-Aggregate on multiple categorical columns appears to lead to pre-allocating the full cartesian product of all categorical values. The length of the resulting array can exceed the size of the original dataframe by far.

In the example below, we use 20 categorical columns with 10 categories each in a dataframe with only 10 rows. The full cartesian product will have dim `10 ** 20`, exceeding any available RAM by far.

# Example
## Code
```python
import pandas as pd
import dask.dataframe as dd

data = {f"col_{i}": pd.np.arange(10) for i in range(20)}
cols = list(data.keys())
df = pd.DataFrame(data, dtype="category")
ddf = dd.from_pandas(df, npartitions=1)

ddf.groupby(cols).apply(len).compute()  # works

ddf.groupby(cols).count()  # fails with MemoryError
ddf.groupby(cols).agg({"col_0": "count"}).compute()  # fails with MemoryError
```

## Traceback
Error message:
```
MemoryError: Unable to allocate 6.74 EiB for an array with shape (7766279631452241920,) and data type int8
```

<details><summary>Full traceback</summary>

```python

MemoryError                               Traceback (most recent call last)
<ipython-input-32-71c1cacc1e40> in <module>
----> 1 ddf.groupby(cols).count()

~/.pyenv/versions/3.7.4/envs/data/lib/python3.7/site-packages/dask/dataframe/groupby.py in count(self, split_every, split_out)
   1311             aggfunc=M.sum,
   1312             split_every=split_every,
-> 1313             split_out=split_out,
   1314         )
   1315 

~/.pyenv/versions/3.7.4/envs/data/lib/python3.7/site-packages/dask/dataframe/groupby.py in _aca_agg(self, token, func, aggfunc, split_every, split_out, chunk_kwargs, aggregate_kwargs)
   1071             aggfunc = func
   1072 
-> 1073         meta = func(self._meta_nonempty)
   1074         columns = meta.name if is_series_like(meta) else meta.columns
   1075 

~/.pyenv/versions/3.7.4/envs/data/lib/python3.7/site-packages/dask/utils.py in __call__(self, obj, *args, **kwargs)
    879 
    880     def __call__(self, obj, *args, **kwargs):
--> 881         return getattr(obj, self.method)(*args, **kwargs)
    882 
    883     def __reduce__(self):

~/.pyenv/versions/3.7.4/envs/data/lib/python3.7/site-packages/pandas/core/groupby/generic.py in count(self)
   1603         blk = map(make_block, map(counter, val), loc)
   1604 
-> 1605         return self._wrap_agged_blocks(data.items, list(blk))
   1606 
   1607     def nunique(self, dropna=True):

~/.pyenv/versions/3.7.4/envs/data/lib/python3.7/site-packages/pandas/core/groupby/generic.py in _wrap_agged_blocks(self, items, blocks)
   1562             result = result.T
   1563 
-> 1564         return self._reindex_output(result)._convert(datetime=True)
   1565 
   1566     def _iterate_column_groupbys(self):

~/.pyenv/versions/3.7.4/envs/data/lib/python3.7/site-packages/pandas/core/groupby/groupby.py in _reindex_output(self, output)
   2469         levels_list = [ping.group_index for ping in groupings]
   2470         index, _ = MultiIndex.from_product(
-> 2471             levels_list, names=self.grouper.names
   2472         ).sortlevel()
   2473 

~/.pyenv/versions/3.7.4/envs/data/lib/python3.7/site-packages/pandas/core/indexes/multi.py in from_product(cls, iterables, sortorder, names)
    537 
    538         codes, levels = _factorize_from_iterables(iterables)
--> 539         codes = cartesian_product(codes)
    540         return MultiIndex(levels, codes, sortorder=sortorder, names=names)
    541 

~/.pyenv/versions/3.7.4/envs/data/lib/python3.7/site-packages/pandas/core/reshape/util.py in cartesian_product(X)
     56             np.repeat(np.asarray(com.values_from_object(x)), b[i]), np.product(a[i])
     57         )
---> 58         for i, x in enumerate(X)
     59     ]

~/.pyenv/versions/3.7.4/envs/data/lib/python3.7/site-packages/pandas/core/reshape/util.py in <listcomp>(.0)
     56             np.repeat(np.asarray(com.values_from_object(x)), b[i]), np.product(a[i])
     57         )
---> 58         for i, x in enumerate(X)
     59     ]

<__array_function__ internals> in repeat(*args, **kwargs)

~/.pyenv/versions/3.7.4/envs/data/lib/python3.7/site-packages/numpy/core/fromnumeric.py in repeat(a, repeats, axis)
    480 
    481     """
--> 482     return _wrapfunc(a, 'repeat', repeats, axis=axis)
    483 
    484 

~/.pyenv/versions/3.7.4/envs/data/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     59 
     60     try:
---> 61         return bound(*args, **kwds)
     62     except TypeError:
     63         # A TypeError occurs if the object does have such a method in its

MemoryError: Unable to allocate 6.74 EiB for an array with shape (7766279631452241920,) and data type int8
```
</details>

## Details
- the issue appears with all aggregation methods, e.g. `.count()`, `.min`, `.max`.
- error is raised in `.count()` before (w/o) calling `.compute()`
- error is raised in `.agg().compute()` after calling `.compute()`
- the issue does not occur with non-categorical columns, e.g. after changing to `.., dtype='int'` in the example above.

## Update
Same issue appears to exist in plain `pandas`:
```python
...
df.groupby(cols).count()  # fails just as with Dask Dataframe
```

**Comment by ig248** [comment] 2020-01-22 14:06
Since this issue appears to stem from `pandas`, I will raise it there as well.

The remaining decision is whether this is something that can/should be fixed in `dask.dataframe` independently from upstream `pandas` - any input much appreciated. 

If not, I am happy to close the `dask` issue for now.

**Comment by TomAugspurger** [comment] 2020-01-22 14:10
Probably no need to open a pandas issue, this is the intended behavior. You can pass `observed` keyword to control whether unobserved categories are included.

**Comment by ig248** [comment] 2020-01-22 14:10
seems related to https://github.com/pandas-dev/pandas/issues/30552

**Comment by ig248** [comment] 2020-01-22 14:12
Thank you very much @TomAugspurger, the `observed` kwarg makes it clear that trying to create a series with lots of `0`s for un-observed categories is indeed the intended behaviour. This answers my question, thanks.

**Comment by ig248** [comment] 2020-01-22 14:14
The outstanding issue then becomes whether the `observed` kwarg should be available in `dask`?

**Comment by ig248** [comment] 2020-01-22 14:22
There appears to be an [open issue](https://github.com/dask/dask/issues/4371) already - would you accept PRs for this feature?

**Comment by TomAugspurger** [comment] 2020-01-22 14:35
Yep. We'll close this in favor of https://github.com/dask/dask/issues/4371

**Closed by TomAugspurger** 2020-01-22 14:35 UTC
