### ISSUE TITLE
Forgiving dtypes on dataframe read_json

### ISSUE THREAD

**Issue by msmicker** [dask/dask#6152] opened 2020-04-29 02:43 UTC
Perhaps a feature request.

I am reading a set of ~100+ largish (~3GB each) json files. They are record form, line by line and flat. Certain attributes are mixed as integer/string - e.g. values 1 and 'a1' but when numeric it is not '1'. Without setting metadata it happens to read them as int since they are in the early samples of the files. Setting the meta information for these columns as int fails as expected. I was surprised that setting as object also fails. I suspect json can be parsed a bit more strictly?

Would it make sense to have an attribute that allows numeric types to be accepted as object type?

Also, my initial solution was to use a dask bag, map to json.loads, map to a function which casts all values for these columns as string. Then run to_dataframe on the bag. I was surprised that the bag method also works without my string conversion (blocksizes are same in dd read_json and db read_text).

I appreciate any feedback on ways to handle.

ValueError: Metadata mismatch found in `from_delayed`.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-a6ec8f1a68ea> in <module>
     18                         meta=get_meta(file_json)
     19                        )
---> 20 df_d2v2g.head()

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/dask/dataframe/core.py in head(self, n, npartitions, compute)
    999             Whether to compute the result, default is True.
   1000         """
-> 1001         return self._head(n=n, npartitions=npartitions, compute=compute, safe=True)
   1002 
   1003     def _head(self, n, npartitions, compute, safe):

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/dask/dataframe/core.py in _head(self, n, npartitions, compute, safe)
   1032 
   1033         if compute:
-> 1034             result = result.compute()
   1035         return result
   1036 

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
    164         dask.base.compute
    165         """
--> 166         (result,) = compute(self, traverse=False, **kwargs)
    167         return result
    168 

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/dask/base.py in compute(*args, **kwargs)
    435     keys = [x.__dask_keys__() for x in collections]
    436     postcomputes = [x.__dask_postcompute__() for x in collections]
--> 437     results = schedule(dsk, keys, **kwargs)
    438     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    439 

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2593                     should_rejoin = False
   2594             try:
-> 2595                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2596             finally:
   2597                 for f in futures.values():

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1886             else:
   1887                 local_worker = None
-> 1888             return self.sync(
   1889                 self._gather,
   1890                 futures,

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    775             return future
    776         else:
--> 777             return sync(
    778                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    779             )

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    346     if error[0]:
    347         typ, exc, tb = error[0]
--> 348         raise exc.with_traceback(tb)
    349     else:
    350         return result[0]

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/distributed/utils.py in f()
    330             if callback_timeout is not None:
    331                 future = asyncio.wait_for(future, callback_timeout)
--> 332             result[0] = yield future
    333         except Exception as exc:
    334             error[0] = sys.exc_info()

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1751                             exc = CancelledError(key)
   1752                         else:
-> 1753                             raise exception.with_traceback(traceback)
   1754                         raise exc
   1755                     if errors == "skip":

~/.conda/envs/jupyterlab/lib/python3.8/site-packages/dask/dataframe/utils.py in check_meta()
    661         )
    662 
--> 663     raise ValueError(
    664         "Metadata mismatch found%s.\n\n"
    665         "%s" % ((" in `%s`" % funcname if funcname else ""), errmsg)

ValueError: Metadata mismatch found in `from_delayed`.
Partition type: `pandas.core.frame.DataFrame`
+------------+-------+----------+
| Column     | Found | Expected |
+------------+-------+----------+
| col_abc    | int64 | object   |
| col_xyz    | int64 | object   |
+------------+-------+----------+
```

**Comment by jrbourbeau** [comment] 2020-04-30 01:39
Thanks for raising an issue @msmicker. Are you able to provide a minimal example? (see https://blog.dask.org/2018/02/28/minimal-bug-reports)

**Comment by jrbourbeau** [comment] 2020-05-04 23:10
Just checking in @msmicker, could you provide a code snippet that maintainers can run to reproduce the error?

**Comment by msmicker** [comment] 2020-05-06 03:42
Let me know if this works. To recap:
1 - a json file dataset where values of a key are mixed int and string
2 - large json dataset breaks individual worker/node when reading fully so I must use blocksize
3 - when using blocksize the file is not fully read for schema detection, it guesses the dtype as int. When doing an operation that goes across other blocks of the file it detects the string values which go against the int dtype
4 - when using meta to set the dtype as object, the early blocks are detected as int and it fails

The json data may be technically incorrect, but I thought it was interesting to see it is fine to use a dtype=object when the sample size includes both, but not when only int is in the sample. (hopefully that makes sense!). My suggestion would be to only warn if int values are read into a schema (defined by meta) where dtype is object.

p.s. I did resolve by using bags and converting values of keys like this to proper strings (e.g. "key":"1" rather than "key":1 ). The power of dask is mighty :) :)

```python
import json
import os
os.remove('sample.json')
with open('sample.json', 'a+') as f:
    d = {}
    for x in range(10000):
        if x < 9900:
            d = {"col_abc":1}
        else:
            d = {"col_abc":"a" + str(1)}
        json.dump(d, f)
        f.write('\n')


import dask.dataframe as dd
df = dd.read_json('sample.json')

# no issue, default blocksize reads full file and correctly sets 
uniq = df['col_abc'].unique().compute()
print(uniq)

df = dd.read_json('sample.json', blocksize=10000, sample=10000)

uniq = df['col_abc'].unique().compute()
print(uniq)
```

This fails because early data types are int
```python
df = dd.read_json('sample.json', blocksize=10000, sample=10000, meta={'col_abc':'object'})

uniq = df['col_abc'].unique().compute()
print(uniq)
```

**Comment by jsignell** [comment] 2020-05-28 22:13
I can reproduce. I originally expected that dask would upcast to the meta dtype. But then I saw that other `dd.read_*` methods have `dtype` as a key word argument.  Since extra kwargs on `dd.read_json` get passed along to `pandas.read_json` and `pandas.read_json` has a `dtype` option, this works:

```python
import json
import os
if os.path.exists("sample.json"):
    os.remove('sample.json')
with open('sample.json', 'a+') as f:
    d = {}
    for x in range(10000):
        if x < 9900:
            d = {"col_abc":1}
        else:
            d = {"col_abc":"a" + str(1)}
        json.dump(d, f)
        f.write('\n')


import dask.dataframe as dd
df = dd.read_json('sample.json')

# no issue, default blocksize reads full file and correctly sets 
uniq = df['col_abc'].unique().compute()
print(uniq)

df = dd.read_json('sample.json', blocksize=10000, sample=10000, dtype={"col_abc": "object"})

uniq = df['col_abc'].unique().compute()
print(uniq)
```

I am closing this issue since it seems like that should fix your issue, but if you have any docs suggestions please open a pull request :)

**Closed by jsignell** 2020-05-28 22:13 UTC
Labels: dataframe, io

**Comment by msmicker** [comment] 2020-06-22 20:50
Thanks very much for looking - for the real dataset, I still get this error:
ValueError: Metadata mismatch found in `from_delayed`.

```
Partition type: `pandas.core.frame.DataFrame`
+------------+--------+----------+
| Column     | Found  | Expected |
+------------+--------+----------+
| col_abc    | object | int64    |
+------------+--------+----------+
```

**Comment by TomAugspurger** [comment] 2020-06-22 20:54
> It may be due to different types across different partitions?

Yeah, you should ensure that the dtypes are consistent by casting before passing a pandas DataFrame to `from_delayed`.
