### ISSUE TITLE
Dask failure with datashader?

### ISSUE THREAD

**Issue by apiszcz** [dask/dask#2519] opened 2017-07-14 14:34 UTC
This appears to be more of a dask error, however I'm getting when using datashader.
`https://github.com/bokeh/datashader/issues/409
`

DataShader '0.6.0dev2'
Dask 0.15.1

**Comment by jcrist** [comment] 2017-07-14 14:46
This is not a bug in dask. The error you're seeing there is a `MemoryError` (meaning you've used up all your memory) - this is in the datashader code and has to do with how much memory is needed to create an image of the size you requested in parallel.

I'm going to close this here, as it's not caused by dask.

**Closed by jcrist** 2017-07-14 14:46 UTC

**Comment by apiszcz** [comment] 2017-07-14 14:50
Thank you will test on a system with more memory soon.
