### ISSUE TITLE
Errors in quantile calculation

### ISSUE THREAD

**Issue by grzes314** [dask/dask#3115] opened 2018-01-30 12:35 UTC
I generated simple data: numbers 1-100, split into 10 shards, so that the first shard contains numbers 1-10, the second 11-20, and so on. I read the data with
`df = dd.read_csv(os.path.join('/home/grzegorz/shards', 'shard_*.csv'))`
and then I try to summarize it:
`df.describe().compute()`
The result is:
```
                a
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     33.250000
50%     65.500000
75%     97.750000
max    100.000000
```
Clearly the quantiles are far from the right value. I understand that calculation of quantiles in a distributed data set is very troublesome and obtaining the exact value might be even impossible, but it seems like a relatively big error for such a simple data set. It puts in question whether the results are reliable for instance for data with trend.

Please, let know if quantile computation is going to be improved. 

Python 3.5.2
dask 0.16.0

**Comment by martindurant** [comment] 2018-01-30 15:00
You will find that, if the numbers are more randomly distributed, the estimate accuracy of the quartiles will increase greatly. This is a limitation of the algorithm used.

**Comment by martindurant** [comment] 2018-01-30 15:01
cf https://github.com/dask/dask/issues/3099

**Comment by jcrist** [comment] 2018-01-30 15:27
Correct. This has been reported a number of times. I hope to have some time in the next week to port over the use of crick (see discussion in #3099 for the same issue but in dask array). Closing as duplicate of #731.

**Closed by jcrist** 2018-01-30 15:27 UTC
