### ISSUE TITLE
Failing tests with OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by ArchangeGabriel** [dask/dask#7390] opened 2021-03-15 05:42 UTC
**What happened**: Test suite fails with multiple `OSError: [Errno 24] Too many open files`

**What you expected to happen**: Test suite passes.

**Minimal Complete Verifiable Example**:

```bash
pytest dask/tests dask/array/tests dask/bag/tests dask/bytes/tests dask/dataframe/tests
```

Output of failing tests:
```
_______________________ test_rearrange[processes-tasks] ________________________

shuffle = 'tasks', scheduler = 'processes'

    @pytest.mark.parametrize("shuffle", ["tasks", "disk"])
    @pytest.mark.parametrize("scheduler", ["threads", "processes"])
    def test_rearrange(shuffle, scheduler):
        df = pd.DataFrame({"x": np.random.random(10)})
        ddf = dd.from_pandas(df, npartitions=4)
        ddf2 = ddf.assign(_partitions=ddf.x % 4)
    
        result = rearrange_by_column(ddf2, "_partitions", max_branch=32, shuffle=shuffle)
        assert result.npartitions == ddf.npartitions
        assert set(ddf.dask).issubset(result.dask)
    
        # Every value in exactly one partition
>       a = result.compute(scheduler=scheduler)

dask/dataframe/tests/test_shuffle.py:277: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/base.py:283: in compute
    (result,) = compute(self, traverse=False, **kwargs)
dask/base.py:565: in compute
    results = schedule(dsk, keys, **kwargs)
dask/multiprocessing.py:197: in get
    pool = context.Pool(num_workers, initializer=initialize_worker_process)
/usr/lib/python3.9/multiprocessing/context.py:119: in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
/usr/lib/python3.9/multiprocessing/pool.py:212: in __init__
    self._repopulate_pool()
/usr/lib/python3.9/multiprocessing/pool.py:303: in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
/usr/lib/python3.9/multiprocessing/pool.py:326: in _repopulate_pool_static
    w.start()
/usr/lib/python3.9/multiprocessing/process.py:121: in start
    self._popen = self._Popen(self)
/usr/lib/python3.9/multiprocessing/context.py:284: in _Popen
    return Popen(process_obj)
/usr/lib/python3.9/multiprocessing/popen_spawn_posix.py:32: in __init__
    super().__init__(process_obj)
/usr/lib/python3.9/multiprocessing/popen_fork.py:19: in __init__
    self._launch(process_obj)
/usr/lib/python3.9/multiprocessing/popen_spawn_posix.py:58: in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

path = '/usr/bin/python'
args = ['/usr/bin/python', '-c', 'from multiprocessing.spawn import spawn_main; spawn_main(tracker_fd=20, pipe_handle=1021)', '--multiprocessing-fork']
passfds = (20, 953, 954, 955, 956, 1019, ...)

    def spawnv_passfds(path, args, passfds):
        import _posixsubprocess
        passfds = tuple(sorted(map(int, passfds)))
>       errpipe_read, errpipe_write = os.pipe()
E       OSError: [Errno 24] Too many open files

/usr/lib/python3.9/multiprocessing/util.py:450: OSError
________________________ test_rearrange[processes-disk] ________________________

shuffle = 'disk', scheduler = 'processes'

    @pytest.mark.parametrize("shuffle", ["tasks", "disk"])
    @pytest.mark.parametrize("scheduler", ["threads", "processes"])
    def test_rearrange(shuffle, scheduler):
        df = pd.DataFrame({"x": np.random.random(10)})
        ddf = dd.from_pandas(df, npartitions=4)
        ddf2 = ddf.assign(_partitions=ddf.x % 4)
    
        result = rearrange_by_column(ddf2, "_partitions", max_branch=32, shuffle=shuffle)
        assert result.npartitions == ddf.npartitions
        assert set(ddf.dask).issubset(result.dask)
    
        # Every value in exactly one partition
>       a = result.compute(scheduler=scheduler)

dask/dataframe/tests/test_shuffle.py:277: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/base.py:283: in compute
    (result,) = compute(self, traverse=False, **kwargs)
dask/base.py:565: in compute
    results = schedule(dsk, keys, **kwargs)
dask/multiprocessing.py:197: in get
    pool = context.Pool(num_workers, initializer=initialize_worker_process)
/usr/lib/python3.9/multiprocessing/context.py:119: in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
/usr/lib/python3.9/multiprocessing/pool.py:191: in __init__
    self._setup_queues()
/usr/lib/python3.9/multiprocessing/pool.py:344: in _setup_queues
    self._outqueue = self._ctx.SimpleQueue()
/usr/lib/python3.9/multiprocessing/context.py:113: in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
/usr/lib/python3.9/multiprocessing/queues.py:341: in __init__
    self._reader, self._writer = connection.Pipe(duplex=False)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

duplex = False

    def Pipe(duplex=True):
        '''
        Returns pair of connection objects at either end of a pipe
        '''
        if duplex:
            s1, s2 = socket.socketpair()
            s1.setblocking(True)
            s2.setblocking(True)
            c1 = Connection(s1.detach())
            c2 = Connection(s2.detach())
        else:
>           fd1, fd2 = os.pipe()
E           OSError: [Errno 24] Too many open files

/usr/lib/python3.9/multiprocessing/connection.py:532: OSError
____________________________ test_rearrange_cleanup ____________________________

    def test_rearrange_cleanup():
        df = pd.DataFrame({"x": np.random.random(10)})
        ddf = dd.from_pandas(df, npartitions=4)
        ddf2 = ddf.assign(_partitions=ddf.x % 4)
    
        tmpdir = tempfile.mkdtemp()
    
        with dask.config.set(temporay_directory=str(tmpdir)):
            result = rearrange_by_column(ddf2, "_partitions", max_branch=32, shuffle="disk")
>           result.compute(scheduler="processes")

dask/dataframe/tests/test_shuffle.py:294: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/base.py:283: in compute
    (result,) = compute(self, traverse=False, **kwargs)
dask/base.py:565: in compute
    results = schedule(dsk, keys, **kwargs)
dask/multiprocessing.py:197: in get
    pool = context.Pool(num_workers, initializer=initialize_worker_process)
/usr/lib/python3.9/multiprocessing/context.py:119: in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
/usr/lib/python3.9/multiprocessing/pool.py:191: in __init__
    self._setup_queues()
/usr/lib/python3.9/multiprocessing/pool.py:343: in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
/usr/lib/python3.9/multiprocessing/context.py:113: in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
/usr/lib/python3.9/multiprocessing/queues.py:341: in __init__
    self._reader, self._writer = connection.Pipe(duplex=False)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

duplex = False

    def Pipe(duplex=True):
        '''
        Returns pair of connection objects at either end of a pipe
        '''
        if duplex:
            s1, s2 = socket.socketpair()
            s1.setblocking(True)
            s2.setblocking(True)
            c1 = Connection(s1.detach())
            c2 = Connection(s2.detach())
        else:
>           fd1, fd2 = os.pipe()
E           OSError: [Errno 24] Too many open files

/usr/lib/python3.9/multiprocessing/connection.py:532: OSError
__________________ test_rearrange_disk_cleanup_with_exception __________________

    def test_rearrange_disk_cleanup_with_exception():
        # ensure temporary files are cleaned up when there's an internal exception.
    
        with mock.patch("dask.dataframe.shuffle.shuffle_group_3", new=mock_shuffle_group_3):
            df = pd.DataFrame({"x": np.random.random(10)})
            ddf = dd.from_pandas(df, npartitions=4)
            ddf2 = ddf.assign(_partitions=ddf.x % 4)
    
            tmpdir = tempfile.mkdtemp()
    
            with dask.config.set(temporay_directory=str(tmpdir)):
                with pytest.raises(ValueError, match="Mock exception!"):
                    result = rearrange_by_column(
                        ddf2, "_partitions", max_branch=32, shuffle="disk"
                    )
>                   result.compute(scheduler="processes")

dask/dataframe/tests/test_shuffle.py:318: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/base.py:283: in compute
    (result,) = compute(self, traverse=False, **kwargs)
dask/base.py:565: in compute
    results = schedule(dsk, keys, **kwargs)
dask/multiprocessing.py:197: in get
    pool = context.Pool(num_workers, initializer=initialize_worker_process)
/usr/lib/python3.9/multiprocessing/context.py:119: in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
/usr/lib/python3.9/multiprocessing/pool.py:191: in __init__
    self._setup_queues()
/usr/lib/python3.9/multiprocessing/pool.py:343: in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
/usr/lib/python3.9/multiprocessing/context.py:113: in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
/usr/lib/python3.9/multiprocessing/queues.py:341: in __init__
    self._reader, self._writer = connection.Pipe(duplex=False)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

duplex = False

    def Pipe(duplex=True):
        '''
        Returns pair of connection objects at either end of a pipe
        '''
        if duplex:
            s1, s2 = socket.socketpair()
            s1.setblocking(True)
            s2.setblocking(True)
            c1 = Connection(s1.detach())
            c2 = Connection(s2.detach())
        else:
>           fd1, fd2 = os.pipe()
E           OSError: [Errno 24] Too many open files

/usr/lib/python3.9/multiprocessing/connection.py:532: OSError
_____________________ test_set_index_consistent_divisions ______________________

    @pytest.mark.slow
    def test_set_index_consistent_divisions():
        # See https://github.com/dask/dask/issues/3867
        df = pd.DataFrame(
            {"x": np.random.random(100), "y": np.random.random(100) // 0.2},
            index=np.random.random(100),
        )
        ddf = dd.from_pandas(df, npartitions=4)
        ddf = ddf.clear_divisions()
    
        ctx = mp.get_context("spawn")
>       pool = ctx.Pool(processes=8)

dask/dataframe/tests/test_shuffle.py:435: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/lib/python3.9/multiprocessing/context.py:119: in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
/usr/lib/python3.9/multiprocessing/pool.py:191: in __init__
    self._setup_queues()
/usr/lib/python3.9/multiprocessing/pool.py:343: in _setup_queues
    self._inqueue = self._ctx.SimpleQueue()
/usr/lib/python3.9/multiprocessing/context.py:113: in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
/usr/lib/python3.9/multiprocessing/queues.py:341: in __init__
    self._reader, self._writer = connection.Pipe(duplex=False)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

duplex = False

    def Pipe(duplex=True):
        '''
        Returns pair of connection objects at either end of a pipe
        '''
        if duplex:
            s1, s2 = socket.socketpair()
            s1.setblocking(True)
            s2.setblocking(True)
            c1 = Connection(s1.detach())
            c2 = Connection(s2.detach())
        else:
>           fd1, fd2 = os.pipe()
E           OSError: [Errno 24] Too many open files

/usr/lib/python3.9/multiprocessing/connection.py:532: OSError
__________________ test_disk_shuffle_check_actual_compression __________________

    def test_disk_shuffle_check_actual_compression():
        # test if the compression switch is really respected by testing the size of the actual partd-data on disk
        def generate_raw_partd_file(compression):
            # generate and write a dummy dataframe to disk and return the raw data bytes
            df1 = pd.DataFrame({"a": list(range(10000))})
            df1["b"] = (df1["a"] * 123).astype(str)
            with dask.config.set({"dataframe.shuffle-compression": compression}):
                p1 = maybe_buffered_partd(buffer=False, tempdir=None)()
                p1.append({"x": df1})
                # get underlying filename from partd - depending on nested structure of partd object
                filename = (
                    p1.partd.partd.filename("x") if compression else p1.partd.filename("x")
                )
                return open(filename, "rb").read()
    
        # get compressed and uncompressed raw data
>       uncompressed_data = generate_raw_partd_file(compression=None)

dask/dataframe/tests/test_shuffle.py:1055: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
dask/dataframe/tests/test_shuffle.py:1047: in generate_raw_partd_file
    p1.append({"x": df1})
/usr/lib/python3.9/site-packages/partd/encode.py:25: in append
    self.partd.append(data, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <partd.file.File object at 0x7f4525e5dc10>
data = {'x': b'\xf0\x17\x02\x00\x00\x00\x00\x000\x01\x00\x00\x00\x00\x00\x00\x80\x05\x95%\x01\x00\x00\x00\x00\x00\x00]\x94((\... \x08284e \x08285e \x08286e \x08287e \x08288e \x08290e \x08291e \x0c2926%@\x0493e \x08295e \x08296e 029754\xa71229877'}
lock = True, fsync = False, kwargs = {}, k = 'x'
v = b'\xf0\x17\x02\x00\x00\x00\x00\x000\x01\x00\x00\x00\x00\x00\x00\x80\x05\x95%\x01\x00\x00\x00\x00\x00\x00]\x94((\x8c\x1...e \x08284e \x08285e \x08286e \x08287e \x08288e \x08290e \x08291e \x0c2926%@\x0493e \x08295e \x08296e 029754\xa71229877'
fn = '/tmp/tmp2beefpll.partd/x'

    def append(self, data, lock=True, fsync=False, **kwargs):
        if lock: self.lock.acquire()
        try:
            for k, v in data.items():
                fn = self.filename(k)
                if not os.path.exists(os.path.dirname(fn)):
                    os.makedirs(os.path.dirname(fn))
>               with open(fn, 'ab') as f:
E               OSError: [Errno 24] Too many open files: '/tmp/tmp2beefpll.partd/x'

/usr/lib/python3.9/site-packages/partd/file.py:43: OSError
```

**Anything else we need to know?**: Packaging for Arch Linux

**Environment**:

- Dask version: 2021.3.0
- Python version: 3.9
- Operating System: Arch Linux
- Install method (conda, pip, source): source

**Comment by ArchangeGabriel** [comment] 2021-03-15 06:01
Apparently this seems intermittent, as re-running did not made these failures happen again. Not sure whether that’s worth investigating then…

**Comment by jrbourbeau** [comment] 2021-03-15 15:36
Thanks for raising an issue @ArchangeGabriel. Does it happen, but infrequently, or are you not able to trigger the `OSError` again?

**Comment by jsignell** [comment] 2021-03-15 16:34
I think this is a duplicate of #7291

**Closed by jsignell** 2021-03-15 16:34 UTC

**Comment by ArchangeGabriel** [comment] 2021-03-15 21:10
Indeed seems a duplicate.
