### ISSUE TITLE
Chained exceptions not fully displayed in client process

### ISSUE THREAD

**Issue by stuarteberg** [dask/dask#4384] opened 2019-01-14 23:01 UTC
When handling an exception in Python 3, one can raise a new exception without discarding the original traceback.  (I'm referring to "exception chaining" syntax: `raise new_exc from orig_exc`.)

In dask, exceptions from worker threads are pickled and shown in the client process, which is nice.  But chained exceptions aren't shown correctly.

When using the `single-threaded` scheduler, the chained exception traceback appears correctly.  The following program produces a chained exception:

```python
import dask
import dask.bag as db

def raise_twice(x):
    try:
        raise RuntimeError("Oops 1")
    except Exception as ex:
        raise RuntimeError("Oops 2") from ex
    return x

dask.config.set(scheduler='single-threaded')
db.from_sequence([1,2,3]).map(raise_twice).compute()
```

Here's the traceback:

<br>
<details>

<summary>Chained traceback</summary>

```pytb
Traceback (most recent call last):
  File "test.py", line 6, in raise_twice
    raise RuntimeError("Oops 1")
RuntimeError: Oops 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    db.from_sequence([1,2,3]).map(raise_twice).compute()
  File "/prefix/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/prefix/lib/python3.6/site-packages/dask/base.py", line 397, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/prefix/lib/python3.6/site-packages/dask/local.py", line 542, in get_sync
    return get_async(apply_sync, 1, dsk, keys, **kwargs)
  File "/prefix/lib/python3.6/site-packages/dask/local.py", line 488, in get_async
    fire_task()
  File "/prefix/lib/python3.6/site-packages/dask/local.py", line 484, in fire_task
    callback=queue.put)
  File "/prefix/lib/python3.6/site-packages/dask/local.py", line 531, in apply_sync
    res = func(*args, **kwds)
  File "/prefix/lib/python3.6/site-packages/dask/local.py", line 277, in execute_task
    result = pack_exception(e, dumps)
  File "/prefix/lib/python3.6/site-packages/dask/local.py", line 272, in execute_task
    result = _execute_task(task, data)
  File "/prefix/lib/python3.6/site-packages/dask/local.py", line 253, in _execute_task
    return func(*args2)
  File "/prefix/lib/python3.6/site-packages/dask/bag/core.py", line 1562, in reify
    seq = list(seq)
  File "/prefix/lib/python3.6/site-packages/dask/bag/core.py", line 1722, in map_chunk
    yield f(*a)
  File "test.py", line 8, in raise_twice
    raise RuntimeError("Oops 2") from ex
RuntimeError: Oops 2
```

</details>
<br>

But when using the `processes` or `distributed` scheduler, the original traceback is omitted.  Only the newly-raised exception is shown:
<br>
<details>
<summary>Incomplete traceback</summary>

```pytb
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    db.from_sequence([1,2,3]).map(raise_twice).compute()
  File "/prefix/lib/python3.6/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/prefix/lib/python3.6/site-packages/dask/base.py", line 397, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/prefix/lib/python3.6/site-packages/dask/multiprocessing.py", line 192, in get
    raise_exception=reraise, **kwargs)
  File "/prefix/lib/python3.6/site-packages/dask/local.py", line 501, in get_async
    raise_exception(exc, tb)
  File "/prefix/lib/python3.6/site-packages/dask/compatibility.py", line 111, in reraise
    raise exc.with_traceback(tb)
  File "/prefix/lib/python3.6/site-packages/dask/local.py", line 272, in execute_task
    result = _execute_task(task, data)
  File "/prefix/lib/python3.6/site-packages/dask/local.py", line 253, in _execute_task
    return func(*args2)
  File "/prefix/lib/python3.6/site-packages/dask/bag/core.py", line 1562, in reify
    seq = list(seq)
  File "/prefix/lib/python3.6/site-packages/dask/bag/core.py", line 1722, in map_chunk
    yield f(*a)
  File "test.py", line 8, in raise_twice
    raise RuntimeError("Oops 2") from ex
RuntimeError: Oops 2
```

</details>
<br>

I haven't investigated whether or not this is a problem in dask per se, or if it's due to a problem in `cloudpickle`.

**Comment by jakirkham** [comment] 2019-02-12 04:11
Thanks for the nice reproducer. Was able to reproduce it with cloudpickle alone and filed upstream as issue ( https://github.com/cloudpipe/cloudpickle/issues/248 ).

**Comment by martindurant** [comment] 2019-04-30 16:08
This issue remains live, but there is nothing that we can do about it on our side.

**Comment by jakirkham** [comment] 2019-05-01 06:06
IIRC we tracked this down to CPython itself in the cloudpickle issue linked above. FWIW would be ok closing this as it is not a Dask issue. That said, I do appreciate the effort everyone put in to isolate this one.

**Comment by jakirkham** [comment] 2020-02-05 03:40
PR ( https://github.com/dask/distributed/pull/3430 ) may be relevant.

**Comment by crusaderky** [comment] 2020-02-05 16:37
This is fixable through tblib >= 1.6; I'd suggest reopening the ticket

**Comment by jakirkham** [comment] 2020-02-05 18:19
I think we can leave this closed since we are already tracking this through issue ( https://github.com/dask/distributed/issues/3158 ) and a fix is already in flight (via the PR above). Though please correct me if you think the issue is different somehow. 🙂

**Comment by crusaderky** [comment] 2020-02-05 19:42
The above PR won't fix dask.multiprocessing

**Comment by jakirkham** [comment] 2020-02-05 20:20
Makes sense. Would you be comfortable outlining the recommended course of action then?

**Comment by crusaderky** [comment] 2020-02-05 22:29
I can take care of it (can't promise to be fast though)

**Comment by jakirkham** [comment] 2020-02-05 22:45
That would be great if you can. 😄

If not, just some guidance for someone to pick up later would also be good. 🙂

**Comment by crusaderky** [comment] 2020-02-05 23:41
literally just need to copy what's been done in https://github.com/dask/distributed/pull/3430 in a slave-side wrapper function inside the multiprocessing.Pool. tblib would become an optional dependency. Probably a good idea to raise a warning if it's not installed and you would benefit from it.

**Comment by bernardpazio** [comment] 2020-07-21 16:41
This does appear to be working correctly for multiprocessing

```python
import dask
import dask.bag as db

def raise_twice(x):
    try:
        raise RuntimeError("Oops 1")
    except Exception as ex:
        raise RuntimeError("Oops 2") from ex
    return x

dask.config.set(scheduler='multiprocessing')
db.from_sequence([1,2,3]).map(raise_twice).compute()
```

<details>
<summary>Exception chain</summary>

```
Traceback (most recent call last):
  File "<ipython-input-2-545e40ee9fda>", line 6, in raise_twice
    raise RuntimeError("Oops 1")
RuntimeError: Oops 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bert/.conda/envs/dask-dev/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-545e40ee9fda>", line 12, in <module>
    db.from_sequence([1,2,3]).map(raise_twice).compute()
  File "/home/bert/projects/dask/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/bert/projects/dask/dask/base.py", line 447, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/bert/projects/dask/dask/multiprocessing.py", line 208, in get
    result = get_async(
  File "/home/bert/projects/dask/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/bert/projects/dask/dask/local.py", line 316, in reraise
    raise exc
  File "/home/bert/projects/dask/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/bert/projects/dask/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/bert/projects/dask/dask/bag/core.py", line 1797, in reify
    seq = list(seq)
  File "/home/bert/projects/dask/dask/bag/core.py", line 1984, in __next__
    return self.f(*vals)
  File "<ipython-input-2-545e40ee9fda>", line 8, in raise_twice
    raise RuntimeError("Oops 2") from ex
RuntimeError: Oops 2
```
</details>

Not sure if this is relevant but it doesn't work for exceptions with are not from another but simply occur during handling of another exception eg.

```python
import dask
import dask.bag as db

def raise_twice(x):
    try:
        raise RuntimeError("Oops 1")
    except Exception as ex:
        raise RuntimeError("Oops 2")
    return x

dask.config.set(scheduler='multiprocessing')
db.from_sequence([1,2,3]).map(raise_twice).compute()
```

<details>
<summary>Exception chain</summary>

```
Traceback (most recent call last):
  File "/home/bert/.conda/envs/dask-dev/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-97c5b88499b5>", line 12, in <module>
    db.from_sequence([1,2,3]).map(raise_twice).compute()
  File "/home/bert/projects/dask/dask/base.py", line 167, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/bert/projects/dask/dask/base.py", line 447, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/bert/projects/dask/dask/multiprocessing.py", line 208, in get
    result = get_async(
  File "/home/bert/projects/dask/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/home/bert/projects/dask/dask/local.py", line 316, in reraise
    raise exc
  File "/home/bert/projects/dask/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/home/bert/projects/dask/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/bert/projects/dask/dask/bag/core.py", line 1797, in reify
    seq = list(seq)
  File "/home/bert/projects/dask/dask/bag/core.py", line 1984, in __next__
    return self.f(*vals)
  File "<ipython-input-4-97c5b88499b5>", line 8, in raise_twice
    raise RuntimeError("Oops 2")
RuntimeError: Oops 2
```
</details>

Distributed has this same behavior, which is probably due to the fact that exceptions raised with the from syntax are stored in the `__cause__` attribute however ones which are not are stored in the `__context__` attribute which is not handled in [dask/distributed#3158](https://github.com/dask/distributed/issues/3158 . [See PEP 3134](https://www.python.org/dev/peps/pep-3134/). Either way this ticket doesn't really make any sense any more and should probably be closed.

**Comment by jakirkham** [comment] 2020-07-21 17:06
Thanks for sharing @bernardpazio! 😄

Actually retrying this today, I find all of the scheduling modes `"single-threaded"`, `"threads"`, and `"processes"` work. 🎉

Sure let's go ahead and close. Do you mind raising any remaining tasks as new issues? 😉

**Closed by jakirkham** 2020-07-21 17:06 UTC
Labels: good first issue
