### ISSUE TITLE
parallel the two def in class

### ISSUE THREAD

**Issue by orangeSi** [dask/dask#3676] opened 2018-06-27 13:51 UTC
hi, my code is as this:
```
from time import sleep
class caculater():
    def __init__(self):
        self.x = 1
        self.y = 1
`
    @dask.delayed
    def addx(self, n):
        sleep(1)
        self.x += n

    @dask.delayed
    def muly(self, n):
        sleep(1)
        self.y *= n
        
    def sumxy(self):
        self.xy = self.x + self.y
        print (f"xy:{self.xy};x:{self.x};y:{self.y}")

c = caculater()
dask.delayed(c.addx)(1)
dask.delayed(c.muly)(3)

out = dask.delayed(c.sumxy)()
out.visualize()
out.compute()
```
that output:
`xy:2;x:1;y:1`

So how do i change the code to get `xy:5;x:2;y:3` ?
beacause i want to parallel `addx` and `muly`, and  finally run `sumxy`~

thanks~
si

**Comment by orangeSi** [comment] 2018-06-27 14:58
```
from time import sleep
class caculater():
    def __init__(self):
        self.x = 1
        self.y = 1
`
    @dask.delayed
    def addx(self, n):
        sleep(1)
        self.x += n

    @dask.delayed
    def muly(self, n):
        sleep(1)
        self.y *= n
        
    def sumxy(self, t1, t2):
        self.xy = self.x + self.y
        print (f"xy:{self.xy};x:{self.x};y:{self.y}")

c = caculater()
t1 = dask.delayed(c.addx)(1)
t2 = dask.delayed(c.muly)(3)

out = dask.delayed(c.sumxy)(t1, t2)
out.visualize()
out.compute()
```
when I change to that, it works!

**Comment by orangeSi** [comment] 2018-06-27 15:02
but when I change to this:
```
from time import sleep
class caculater():
    def __init__(self):
        self.x = 1
        self.y = 1
`
    @dask.delayed
    def addx(self, n):
        sleep(1)
        self.x += n

    @dask.delayed
    def muly(self, n):
        sleep(1)
        self.y *= n
        
    def sumxy(self):
        self.xy = self.x + self.y
        print (f"xy:{self.xy};x:{self.x};y:{self.y}")

c = caculater()
t1 = c.addx(1)
t2 = c.muly(3)

out = dask.delayed(c.sumxy)(t1, t2)
out.visualize()
out.compute()
```
got this error:
`TypeError: addx() missing 1 required positional argument: 'n'`

**Comment by martindurant** [comment] 2018-06-27 15:16
- you are calling delayed twice, once as a decorator and once as a function
- the `@dask.delayed` notation is meant for functions or objects, not methods. You *could* delay the (bound) method `delayed(c.addx)`, as you tried in the first attempt, or you *could* delay the instance `delayed(c)`. This causes the `missing 1 argument`, because binding of the method did not happen.
- your methods work by in-place mutation of data, not by returning values, which might work when executing in threads, but is not the recommended design for delayed. This is why you find you are needing to pass fake parameters `t1` and `t2` to `sumxy` to get the first two delayed objects evaluated, but ignoring them.

**Comment by orangeSi** [comment] 2018-06-28 00:21
got it! thanks~

**Comment by jakirkham** [comment] 2018-06-30 21:11
Duplicate of issue ( https://github.com/dask/dask/issues/3317 )?

**Comment by orangeSi** [comment] 2018-07-01 00:46
For decorator usage in the class, they are duplication. But before that I first wanted to know how to parallel two method of one class instead of using return vaule. Now maybe not supported yet.

**Closed** 2018-07-12 01:05 UTC
