### ISSUE TITLE
dataframe.read_hdf raises exception for empty datasets

### ISSUE THREAD

**Issue by struktured** [dask/dask#8707] opened 2022-02-10 21:48 UTC
**What happened**:

```ValueError: Start row number (0) is above or equal to stop row number (0)``` when calling `dataframe.read_hdf`

**What you expected to happen**:

An empty dataframe to be loaded without error.

**Minimal Complete Verifiable Example**:

```python
import dask.dataframe as ddf
# Exception is thrown below
ddf.read_hdf('some_data.h5', key='an_empty_dataset')
```

**Environment**:

- Dask version: 2021.10.0
- Python version: 3.8
- Operating System: Linux
- Install method (conda, pip, source): conda

**Comment by pavithraes** [comment] 2022-02-16 17:29
@struktured Thanks for opening this issue, and for including a minimal example! I'll take a look at this :)

**Comment by pavithraes** [comment] 2022-02-28 15:06
@struktured Thanks for your patience!

I couldn't reproduce this error, and I'm wondering if it's specific to your data? I'm also curious if you can read this (or smaller+similar data) successfully with [pandas' read_hdf](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_hdf.html#pandas-read-hdf)?

[A minimal example that shows this erorr](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) will allow us to help you better. :) You can do something like:

```python
import dask
import dask.dataframe as dd

ddf = dask.datasets.timeseries()
ddf.to_hdf("some_data.h5", "data") # create toy dataset (similar to your actual data)
ddf_hdf = dd.read_hdf("some_data.h5", "data'")
```

Also, since this is a usage question, I'd encourage you to move it to [Dask's Discourse forum](https://dask.discourse.group/) and close this issue. We can open a dedicated issue if this turns out to be a bug in Dask!

**Comment by struktured** [comment] 2022-03-11 21:30
It's definitely a bug but I can only manage to produce the empty dataset shape using proprietary tools.  Here's an example h5 schema that would generate the error. It has one dataset inside called `maybe_empty` with two columns `x` and `y`:

```
h5ls -v empty.h5
Opened "empty.h5" with sec2 driver.
maybe_empty              Dataset {0/0}
    Location:  1:800
    Links:     1
    Chunks:    {512} 8192 bytes
    Storage:   0 logical bytes, 0 allocated bytes
    Filter-0:  blosc-32001 OPT {2, 2, 16, 8192, 6, 1, 1}
    Type:      struct {
                   "x"                +0    native double
                   "y"                +8    native double
               } 16 bytes
```

```python
import dask.dataframe as ddf
r = ddf.read_hdf("empty.h5", key='maybe_empty')
```

will then produce:

```python
ValueError: Start row number (0) is above or equal to stop row number (0)
```

I can upload the empty h5 file to github if that helps debug it. I might also take a stab at fixing the bug myself next week if time permits.

**Comment by jsignell** [comment] 2022-03-15 13:54
I tried creating an empty dataset  and wrote it to a file like this:

```python
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({"A": [], "B": []}, index=[])
df.to_hdf("data.h5", format="fixed", key="df", mode="w")
dd.read_hdf("data.h5", "df")
```

<details>
<summary>Error from trying to read file written with <code>format="fixed"</code></summary>

```python-traceback
IndexError                                Traceback (most recent call last)
Input In [3], in <module>
      4 df = pd.DataFrame({"A": [], "B": []}, index=[])
      5 df.to_hdf("data.h5", format="fixed", key="df", mode="w")
----> 6 dd.read_hdf("data.h5", "df")

File ~/dask/dask/dataframe/io/hdf.py:412, in read_hdf(pattern, key, start, stop, columns, chunksize, sorted_index, lock, mode)
    410 with pd.HDFStore(paths[0], mode=mode) as hdf:
    411     meta_key = _expand_key(key, hdf)[0]
--> 412 meta = pd.read_hdf(paths[0], meta_key, mode=mode, stop=0)
    413 if columns is not None:
    414     meta = meta[columns]

File ~/conda/envs/dask-dev/lib/python3.9/site-packages/pandas/io/pytables.py:455, in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    450                 raise ValueError(
    451                     "key must be provided when HDF5 "
    452                     "file contains multiple datasets."
    453                 )
    454         key = candidate_only_group._v_pathname
--> 455     return store.select(
    456         key,
    457         where=where,
    458         start=start,
    459         stop=stop,
    460         columns=columns,
    461         iterator=iterator,
    462         chunksize=chunksize,
    463         auto_close=auto_close,
    464     )
    465 except (ValueError, TypeError, KeyError):
    466     if not isinstance(path_or_buf, HDFStore):
    467         # if there is an error, close the store if we opened it.

File ~/conda/envs/dask-dev/lib/python3.9/site-packages/pandas/io/pytables.py:875, in HDFStore.select(self, key, where, start, stop, columns, iterator, chunksize, auto_close)
    861 # create the iterator
    862 it = TableIterator(
    863     self,
    864     s,
   (...)
    872     auto_close=auto_close,
    873 )
--> 875 return it.get_result()

File ~/conda/envs/dask-dev/lib/python3.9/site-packages/pandas/io/pytables.py:1943, in TableIterator.get_result(self, coordinates)
   1940     where = self.where
   1942 # directly return the result
-> 1943 results = self.func(self.start, self.stop, where)
   1944 self.close()
   1945 return results

File ~/conda/envs/dask-dev/lib/python3.9/site-packages/pandas/io/pytables.py:859, in HDFStore.select.<locals>.func(_start, _stop, _where)
    858 def func(_start, _stop, _where):
--> 859     return s.read(start=_start, stop=_stop, where=_where, columns=columns)

File ~/conda/envs/dask-dev/lib/python3.9/site-packages/pandas/io/pytables.py:3197, in BlockManagerFixed.read(self, where, columns, start, stop)
   3194 for i in range(self.ndim):
   3196     _start, _stop = (start, stop) if i == select_axis else (None, None)
-> 3197     ax = self.read_index(f"axis{i}", start=_start, stop=_stop)
   3198     axes.append(ax)
   3200 items = axes[0]

File ~/conda/envs/dask-dev/lib/python3.9/site-packages/pandas/io/pytables.py:2904, in GenericFixed.read_index(self, key, start, stop)
   2902 elif variety == "regular":
   2903     node = getattr(self.group, key)
-> 2904     index = self.read_index_node(node, start=start, stop=stop)
   2905     return index
   2906 else:  # pragma: no cover

File ~/conda/envs/dask-dev/lib/python3.9/site-packages/pandas/io/pytables.py:3008, in GenericFixed.read_index_node(self, node, start, stop)
   2999     index = factory(
   3000         _unconvert_index(
   3001             data, kind, encoding=self.encoding, errors=self.errors
   (...)
   3004         **kwargs,
   3005     )
   3006 else:
   3007     index = factory(
-> 3008         _unconvert_index(
   3009             data, kind, encoding=self.encoding, errors=self.errors
   3010         ),
   3011         **kwargs,
   3012     )
   3014 index.name = name
   3016 return index

File ~/conda/envs/dask-dev/lib/python3.9/site-packages/pandas/io/pytables.py:4928, in _unconvert_index(data, kind, encoding, errors)
   4924     index = _unconvert_string_array(
   4925         data, nan_rep=None, encoding=encoding, errors=errors
   4926     )
   4927 elif kind == "object":
-> 4928     index = np.asarray(data[0])
   4929 else:  # pragma: no cover
   4930     raise ValueError(f"unrecognized index type {kind}")

IndexError: list index out of range

```
</details>

When you read the same file with pandas you get back an empty dataframe. 

Note that by default pandas was using `format="fixed"`. I tried changing that to `format="table"` and I got a different error about the datafile not containing the dataset in question. 

<details>
<summary>Error from trying to read file written with <code>format="table"</code></summary>

```python-traceback
File ~/dask/dask/dataframe/io/hdf.py:412, in read_hdf(pattern, key, start, stop, columns, chunksize, sorted_index, lock, mode)
    410 with pd.HDFStore(paths[0], mode=mode) as hdf:
    411     meta_key = _expand_key(key, hdf)[0]
--> 412 meta = pd.read_hdf(paths[0], meta_key, mode=mode, stop=0)
    413 if columns is not None:
    414     meta = meta[columns]

File ~/conda/envs/dask-dev/lib/python3.9/site-packages/pandas/io/pytables.py:455, in read_hdf(path_or_buf, key, mode, errors, where, start, stop, columns, iterator, chunksize, **kwargs)
    450                 raise ValueError(
    451                     "key must be provided when HDF5 "
    452                     "file contains multiple datasets."
    453                 )
    454         key = candidate_only_group._v_pathname
--> 455     return store.select(
    456         key,
    457         where=where,
    458         start=start,
    459         stop=stop,
    460         columns=columns,
    461         iterator=iterator,
    462         chunksize=chunksize,
    463         auto_close=auto_close,
    464     )
    465 except (ValueError, TypeError, KeyError):
    466     if not isinstance(path_or_buf, HDFStore):
    467         # if there is an error, close the store if we opened it.

File ~/conda/envs/dask-dev/lib/python3.9/site-packages/pandas/io/pytables.py:850, in HDFStore.select(self, key, where, start, stop, columns, iterator, chunksize, auto_close)
    848 group = self.get_node(key)
    849 if group is None:
--> 850     raise KeyError(f"No object named {key} in the file")
    852 # create the storer and axes
    853 where = _ensure_term(where, scope_level=1)

KeyError: 'No object named /df in the file'
```

</details>

**Comment by jsignell** [comment] 2022-03-15 14:01
I opened a PR to get around the error that I think you are encountering, but I think there is a larger issue with your setup which is that the file that you are trying to read seems like it was written with `fixed` format rather than `table`. And that is not supported by dask.

**Comment by struktured** [comment] 2022-03-15 18:29
@jsignell  I see your point and appreciate you making the PR! However, the data loads perfectly fine *and* efficiently using `dd.read_hdf` with a glob pattern as long as none of the files have empty records. For instance, many millions of google stock quotes are loaded from hundreds of hdf5 files structured this way in just a few minutes.

**Closed** 2022-03-15 18:34 UTC
Labels: dataframe, io

**Comment by jsignell** [comment] 2022-03-15 18:53
>  the data loads perfectly fine *and* efficiently using `dd.read_hdf` with a glob pattern as long as none of the files have empty records. For instance, many millions of google stock quotes are loaded from hundreds of hdf5 files structured this way in just a few minutes.

Cool! I think you shouldn't be seeing the same error, but if you are please feel free to reopen and try to provide an example that raises the error that you are seeing, or at least include more of the error message.

**Comment by KristinaGagalova** [comment] 2025-02-25 04:20
Hi, 
Looks like we have a series of errors
```
h5ls -d -e FAL03712_a37eb560_104.fast5
HDF5-DIAG: Error detected in HDF5 (1.10.7) thread 1:
  #000: ../../../src/H5L.c line 1226 in H5Literate_by_name(): link iteration failed
    major: Links
    minor: Iteration failed
  #001: ../../../src/H5L.c line 3350 in H5L__iterate(): link iteration failed
    major: Links
    minor: Iteration failed
  #002: ../../../src/H5Gint.c line 853 in H5G_iterate(): error iterating over links
    major: Symbol table
    minor: Iteration failed
  #003: ../../../src/H5Gobj.c line 677 in H5G__obj_iterate(): can't iterate over dense links
    major: Symbol table
    minor: Iteration failed
  #004: ../../../src/H5Gdense.c line 1020 in H5G__dense_iterate(): error building table of links
    major: Symbol table
    minor: Can't get value
  #005: ../../../src/H5Gdense.c line 820 in H5G__dense_build_table(): error iterating over links
    major: Symbol table
    minor: Can't move to next iterator location
  #006: ../../../src/H5Gdense.c line 1011 in H5G__dense_iterate(): link iteration failed
    major: Symbol table
    minor: Iteration failed
  #007: ../../../src/H5B2.c line 438 in H5B2_iterate(): node iteration failed
    major: B-Tree node
    minor: Unable to list node
  #008: ../../../src/H5B2int.c line 1569 in H5B2__iterate_node(): node iteration failed
    major: B-Tree node
    minor: Unable to list node
  #009: ../../../src/H5B2int.c line 1569 in H5B2__iterate_node(): node iteration failed
    major: B-Tree node
    minor: Unable to list node
  #010: ../../../src/H5B2int.c line 1574 in H5B2__iterate_node(): iterator function failed
    major: B-Tree node
    minor: Unable to list node
  #011: ../../../src/H5Gdense.c line 903 in H5G__dense_iterate_bt2_cb(): heap op callback failed
    major: Symbol table
    minor: Can't operate on object
  #012: ../../../src/H5HF.c line 707 in H5HF_op(): can't operate on object from fractal heap
    major: Heap
    minor: Can't operate on object
  #013: ../../../src/H5HFman.c line 536 in H5HF__man_op(): unable to operate on heap object
    major: Heap
    minor: Can't operate on object
  #014: ../../../src/H5HFman.c line 400 in H5HF__man_op_real(): unable to protect fractal heap direct block
    major: Heap
    minor: Unable to protect metadata
  #015: ../../../src/H5HFdblock.c line 496 in H5HF__man_dblock_protect(): unable to protect fractal heap direct block
    major: Heap
    minor: Unable to protect metadata
  #016: ../../../src/H5AC.c line 1517 in H5AC_protect(): H5C_protect() failed
    major: Object cache
    minor: Unable to protect metadata
  #017: ../../../src/H5C.c line 2501 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #018: ../../../src/H5C.c line 7647 in H5C_load_entry(): incorrect metadatda checksum after all read attempts
    major: Object cache
    minor: Read failed
H5tools-DIAG: Error detected in HDF5:tools (1.10.7) thread 1:
  #000: ../../../../tools/lib/h5trav.c line 1060 in h5trav_visit(): traverse failed
    major: Failure in tools library
    minor: error in function
  #001: ../../../../tools/lib/h5trav.c line 295 in traverse(): H5Literate_by_name failed
    major: Failure in tools library
    minor: error in function
```
Any suggestions on how to treat these file or fix them?
