### ISSUE TITLE
How to handle control "not null" behavior for columns written to/read from Parquet files?

### ISSUE THREAD

**Issue by randerzander** [dask/dask#9920] opened 2023-02-04 02:12 UTC
I have a workflow where I need to shuffle a dataset w/ a large number of null values in my shuffle column. To avoid skewed size in the null valued partition, I first filter the nulls and write them to their own Parquet files:

```
ddf_null = ddf[ddf[partition_col].isna()].repartition(partition_size=new_size)
name_function = lambda x: f"nulls_{x}.parquet"
ddf_null.to_parquet(f"{out_dir}_nulls", name_function=name_function)

ddf_nonull = ddf[ddf[partition_col].notnull()]
ddf_nonull = ddf_nonull.shuffle(partition_col)...
name_function = lambda x: f"nonulls_{x}.parquet"
ddf_nonull.to_parquet(f"{out_dir}_nonulls", name_function=name_function)
```

The writes succeed, but when doing non-trivial reads where I specify a number of row groups along w/ `aggregate_files=True`, I'll get failures about inconsistent schemas:
```
len(dd.read_parquet(out_dir, split_row_groups=100, aggregate_files=True))

pyarrow.lib.ArrowInvalid: Schema at index 8 was different:                       
my_shuffle_col: int32 not null                                                                   
__null_dask_index__: int64 not null     
vs                                                                                                
my_shuffle_col: int32                                                                            
__null_dask_index__: int64 not null                                                               
>>>        
```

How can I control the Parquet writer such that it doesn't specify that `my_shuffle_col` is `not null`?

cc @rjzamora

**Comment by j-bennet** [comment] 2023-02-06 21:00
Hi @randerzander,

I was not able to reproduce your case with a simple example. I tried to write a small dataframe with nulls, but `pyarrow` doesn't seem to apply the `not null` restriction. However, you can provide an explicit schema in `dd.to_parquet`, for example:

```python
import pyarrow as pa

ddf_null.to_parquet(
    f"{out_dir}_nulls", 
    name_function=name_function, 
    schema={"my_shuffle_col": pa.int32()}
)
```

You can provide a dict of columns with dtypes, or an instance of `pyarrow.Schema`. If it's a dict, you can provide a subset of columns and they will override the inferred dtypes. If it's a `pyarrow.Schema`, it will be taken as-is, so it should be full schema.

https://docs.dask.org/en/stable/generated/dask.dataframe.to_parquet.html#dask.dataframe.to_parquet

I hope it helps. Let us know it you're still experiencing problems.

**Comment by rjzamora** [comment] 2023-02-06 22:07
Thanks for looking at this @j-bennet - I think the problem here is specific to `cudf.to/from_parquet`.  That is, it looks like the problem only shows up when you use cudf to write and read the parquet files, and I'm  assuming that @randerzander is using the "cudf" backend for `ddf_nonull` here. 

My preference is to close this in favor of https://github.com/rapidsai/cudf/issues/12702 (which could **also** be fixed on the `cudf.read_parquet` side).

**Comment by j-bennet** [comment] 2023-02-06 22:27
@rjzamora Thank you! How did you know that the issue is related to cudf? There seemed to be nothing in description to point that out for me.

**Comment by randerzander** [comment] 2023-02-06 22:34
> and I'm assuming that @randerzander is using the "cudf" backend for ddf_nonull here.

That's correct. My bad for not specifying it clearly in the description.

**Comment by rjzamora** [comment] 2023-02-06 22:34
>There seemed to be nothing in description to point that out for me.

Oops! There was no way for you to know this - Forgot to mention that I discussed this issue with @randerzander offline, so he told me :)

**Closed** 2023-02-06 22:35 UTC
Labels: dataframe, parquet
