### ISSUE TITLE
Dask distributed have a problem with DataFrames with shapely geometries

### ISSUE THREAD

**Issue by avnovikov** [dask/dask#3972] opened 2018-09-11 10:08 UTC
Thanks for the great tool. It seems that there is some problem with DASK when trying to work with DataFrames with objects from shapely (GeoDataFrames f.e.) when there is more then one column of such objects.
```
import pandas as pd
import numpy as np
import geopandas as gpd

import dask.dataframe as dd
from distributed import Client
from shapely.geometry import Point

client = Client('127.0.0.1:8786', processes=True)
length = 10000
data_pos = (np.random.rand(length,2)-0.5)*90
z = list(map(Point, data_pos))

df = gpd.GeoDataFrame({'116': list(np.ones((length, 1))), 'geometry': z}, crs={'init': 'epsg:4326'})
buffer = df.geometry.buffer(0.05)
df['buffer'] = buffer

sharbours = client.scatter(buffer)
sharbours = client.scatter(df)
```
The first scatter works fine, however the second rises an error
```

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-49-db7cc83a6225> in <module>()
      1 sharbours = client.scatter(buffer)
----> 2 sharbours = client.scatter(df)

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/client.py in scatter(self, data, workers, broadcast, direct, hash, maxsize, timeout, asynchronous)
   1790                              broadcast=broadcast, direct=direct,
   1791                              local_worker=local_worker, timeout=timeout,
-> 1792                              asynchronous=asynchronous, hash=hash)
   1793 
   1794     @gen.coroutine

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    643             return future
    644         else:
--> 645             return sync(self.loop, func, *args, **kwargs)
    646 
    647     def __repr__(self):

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    275             e.wait(10)
    276     if error[0]:
--> 277         six.reraise(*error[0])
    278     else:
    279         return result[0]

/anaconda3/envs/mariquant/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/utils.py in f()
    260             if timeout is not None:
    261                 future = gen.with_timeout(timedelta(seconds=timeout), future)
--> 262             result[0] = yield future
    263         except Exception as exc:
    264             error[0] = sys.exc_info()

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/client.py in _scatter(self, data, workers, broadcast, direct, local_worker, timeout, hash)
   1658                                              client=self.id,
   1659                                              broadcast=broadcast,
-> 1660                                              timeout=timeout)
   1661 
   1662         out = {k: Future(k, self, inform=False) for k in data}

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/core.py in send_recv_from_rpc(**kwargs)
    572             try:
    573                 comm = yield self.live_comm()
--> 574                 result = yield send_recv(comm=comm, op=key, **kwargs)
    575             except (RPCClosed, CommClosedError) as e:
    576                 raise e.__class__("%s: while trying to call remote method %r"

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1111                             exc_info = None
   1112                     else:
-> 1113                         yielded = self.gen.send(value)
   1114 
   1115                     if stack_context._state.contexts is not orig_stack_contexts:

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/core.py in send_recv(comm, reply, serializers, deserializers, **kwargs)
    464     if isinstance(response, dict) and response.get('status') == 'uncaught-error':
    465         if comm.deserialize:
--> 466             six.reraise(*clean_exception(**response))
    467         else:
    468             raise Exception(response['text'])

/anaconda3/envs/mariquant/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/core.py in handle_comm()
    338                         if type(result) is gen.Future:
    339                             self._ongoing_coroutines.add(result)
--> 340                             result = yield result
    341                     except (CommClosedError, CancelledError) as e:
    342                         if self.status == 'running':

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run()
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run()
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/scheduler.py in scatter()
   2212         keys, who_has, nbytes = yield scatter_to_workers(ncores, data,
   2213                                                          rpc=self.rpc,
-> 2214                                                          report=False)
   2215 
   2216         self.update_data(who_has=who_has, nbytes=nbytes, client=client)

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run()
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run()
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/utils_comm.py in scatter_to_workers()
    129         out = yield All([rpcs[address].update_data(data=v, report=report,
    130                                                    serializers=serializers)
--> 131                          for address, v in d.items()])
    132     finally:
    133         for r in rpcs.values():

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run()
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run()
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/utils.py in All()
    212     while not tasks.done():
    213         try:
--> 214             result = yield tasks.next()
    215         except Exception:
    216             @gen.coroutine

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run()
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run()
   1105                     if exc_info is not None:
   1106                         try:
-> 1107                             yielded = self.gen.throw(*exc_info)
   1108                         finally:
   1109                             # Break up a reference to itself

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/core.py in send_recv_from_rpc()
    634             comm = yield self.pool.connect(self.addr)
    635             try:
--> 636                 result = yield send_recv(comm=comm, op=key, **kwargs)
    637             finally:
    638                 self.pool.reuse(self.addr, comm)

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run()
   1097 
   1098                     try:
-> 1099                         value = future.result()
   1100                     except Exception:
   1101                         self.had_exception = True

/anaconda3/envs/mariquant/lib/python3.6/site-packages/tornado/gen.py in run()
   1111                             exc_info = None
   1112                     else:
-> 1113                         yielded = self.gen.send(value)
   1114 
   1115                     if stack_context._state.contexts is not orig_stack_contexts:

/anaconda3/envs/mariquant/lib/python3.6/site-packages/distributed/core.py in send_recv()
    466             six.reraise(*clean_exception(**response))
    467         else:
--> 468             raise Exception(response['text'])
    469     raise gen.Return(response)
    470 

Exception: Wrong number of items passed 10000, placement implies 1
```
The versions of the libraries are:

```
# Name                    Version                   Build  Channel
dask                      0.19.1                     py_0    conda-forge
dask-core                 0.19.1                     py_0    conda-forge
shapely                   1.6.4            py36h164cb2d_1    conda-forge
geopandas                 1.0.0.dev                py36_2    conda-forge/label/dev
tornado                   5.0.2                    py36_0    conda-forge
```

**Comment by avnovikov** [comment] 2018-09-11 18:58
Dear Tom,
thank you for the prompt answer. I will create the mirrored issue in the GeoPandas GitHub. The funny thing is that 
1) Somewhere deep in the errors I found that dask was not able to guess the size of the GeometryArray, although it was perfectly calculated by pandas.
2) The scatter approach it working fine (I almost managed to make it working in real-life code for the current version).
3) The regular map_partitions (but probably not scatter) with GeoPandas was working in dask v. 0.17.x. Moreover there are numerous examples all over the net when people are using map_partitions to overcome the above mentioned incompatibility. 

Is it a problem with GeoPandas or with GEOS arrays (underlying structures of the Shapely and GeoPandas) ?

**Comment by TomAugspurger** [comment] 2018-09-11 19:37
I'm not sure.

FWIW, I can't reproduce your failure with dask & distributed master. You could try upgrading.

**Comment by avnovikov** [comment] 2018-09-12 07:09
> I'm not sure.
> 
> FWIW, I can't reproduce your failure with dask & distributed master. You could try upgrading.

Tested on current master - the same error. Should I mention that I'm on macOS ?

**Comment by TomAugspurger** [comment] 2018-09-12 11:40
I'm also on a mac.

**Comment by avnovikov** [comment] 2018-09-12 11:52
Let's see what will be the reaction of the GeoPandas team on [819](https://github.com/geopandas/geopandas/issues/819). BTW I'm almost sure that this error is caused by the wrong calculation of size of the geodataframe/geoseries.

**Comment by avnovikov** [comment] 2018-09-12 11:53
> I'm also on a mac.
> […](#)

Can I guess that you have the regular version of the geopandas?

**Comment by jorisvandenbossche** [comment] 2018-09-13 13:20
> It looks like you're using the geopandas-dev with the cython extensions. AFAIK, the geometries will not be serialized correctly. 

It should work (it works on a GeoSeries, but apparently not on a GeoDataFrame), so this is a bug in the current geopandas-cython branch (opened an issue about that here: https://github.com/geopandas/geopandas/issues/820).

> I think the best path for is for geopandas to implement the pandas extension array interface (geopandas/geopandas#701), and for the geopandas, dask, and pandas developers to settle on an API for describing and serializing extension arrays.

Yep, I have a branch doing this (implementing the ExtensionArray interface), but have had little time lately to finish it.

**Comment by avnovikov** [comment] 2018-09-13 14:08
> 
> It should work (it works on a GeoSeries, but apparently not on a GeoDataFrame), so this is a bug in the current geopandas-cython branch (opened an issue about that here: [geopandas/geopandas#820](https://github.com/geopandas/geopandas/issues/820)).
> 
The most strange thing is that the [issue with nbytes](https://github.com/dask/dask/issues/3976) manifests when scattering GeoSeries, but not when scattering GeoDataFrames so this is apparently not related to the pickle issue IMHO.

**Comment by jorisvandenbossche** [comment] 2018-09-13 14:20
It are indeed two separate, unrelated issues

**Comment by jrbourbeau** [comment] 2019-04-30 16:22
Closing as this issue based on

> FWIW, I can't reproduce your failure with dask & distributed master. 

> It are indeed two separate, unrelated issues

and the separate issue / PR opened in geopandas. Also, there is a separate issue (#3976) related to the `nbytes` issue

**Closed by jrbourbeau** 2019-04-30 16:22 UTC
