### ISSUE TITLE
Error importing Parquet from HDFS using PyArrow

### ISSUE THREAD

**Issue by stuckeyr** [dask/dask#2801] opened 2017-10-20 06:11 UTC
Hi,

I get the following error when attempting to read a parquet file stored on hdfs:

    df = dataframe.read_parquet('hdfs://hdfsnn:8020/user/hdfs/ndsparq/Test.parquet', engine='arrow')
    ---------------------------------------------------------------------------
    OSError                                   Traceback (most recent call last)
    <ipython-input-3-22d8573a1d6f> in <module>()
    ----> 1 df = dataframe.read_parquet('hdfs://hdfsnn:8020/user/hdfs/ndsparq/Test.parquet', engine='arrow')

    /opt/anaconda3/envs/env0/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in read_parquet(path, columns, filters, categories, index, storage_options, engine)
        293         return _read_pyarrow(fs, paths, file_opener, columns=columns,
        294                              filters=filters,
    --> 295                              categories=categories, index=index)
        296 
        297 

    /opt/anaconda3/envs/env0/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in _read_pyarrow(fs, paths, file_opener, columns, filters, categories, index)
        164         columns = list(columns)
        165 
    --> 166     dataset = api.ParquetDataset(paths)
        167     schema = dataset.schema.to_arrow_schema()
        168     task_name = 'read-parquet-' + tokenize(dataset, columns)

    /opt/anaconda3/envs/env0/lib/python3.6/site-packages/pyarrow/parquet.py in __init__(self, path_or_paths, filesystem, schema, metadata, split_row_groups, validate_schema)
        619 
        620         (self.pieces, self.partitions,
    --> 621          self.metadata_path) = _make_manifest(path_or_paths, self.fs)
        622 
        623         if self.metadata_path is not None:

    /opt/anaconda3/envs/env0/lib/python3.6/site-packages/pyarrow/parquet.py in _make_manifest(path_or_paths, fs, pathsep)
        779             if not fs.isfile(path):
        780                 raise IOError('Passed non-file path: {0}'
    --> 781                               .format(path))
        782             piece = ParquetDatasetPiece(path)
        783             pieces.append(piece)

    OSError: Passed non-file path: hdfs://hdfsnn:8020/user/hdfs/ndsparq/Test.parquet

The same parquet file can be read using PyArrow without issue:

    with hdfs.open('/user/hdfs/ndsparq/Test.parquet', 'rb') as f:
        table = pq.read_table(f)
    df = table.to_pandas()

Are you able to help? It looks like the filesystem is not passed to `api.ParquetDataset` in `_read_pyarrow()`.

Thanks very much!

**Comment by martindurant** [comment] 2017-10-20 13:54
@stuckeyr : where you have `with hdfs.open`, does this refer to arrow's hdfs interface, or is it a HDFileSystem from hdfs3?

**Comment by stuckeyr** [comment] 2017-10-20 20:26
Yes, Arrow's interface:

    import pyarrow as pa
    hdfs = pa.hdfs.connect('hdfsnn', 8020, user='hdfs')

**Comment by mrocklin** [comment] 2017-10-30 17:05
@martindurant I would have expected this to `import distributed.hdfs` and then either fail with an informative error message or else work.  Do you have any thought on why @stuckeyr might be passed a filename instead?

**Comment by martindurant** [comment] 2017-10-30 19:01
@mrocklin , this is not using `distributed.hdfs` at all, but arrow's built-in hdfs interface. 
My guess would be, that parquet expects to be able to open directories, but they fail the isFile check.

**Comment by xhochy** [comment] 2017-11-01 17:55
I think the problem here is that `pyarrow` isn't fed the correct Filesystem instance but always a local one. This should be fixed with https://github.com/dask/dask/pull/2527 ( @fjetter As my index fix is now in master, can you rebase?)

**Comment by xhochy** [comment] 2017-11-01 17:56
@stuckeyr You could test this assumption by changing this line:

```diff
diff --git a/dask/dataframe/io/parquet.py b/dask/dataframe/io/parquet.py
index f4b37346..0dd743af 100644
--- a/dask/dataframe/io/parquet.py
+++ b/dask/dataframe/io/parquet.py
@@ -173,7 +173,7 @@ def _read_pyarrow(fs, paths, file_opener, columns=None, filters=None,
     if isinstance(columns, tuple):
         columns = list(columns)

-    dataset = api.ParquetDataset(paths)
+    dataset = api.ParquetDataset(paths, filesystem=fs)
     schema = dataset.schema.to_arrow_schema()
     has_pandas_metadata = schema.metadata is not None and b'pandas' in schema.metadata
     task_name = 'read-parquet-' + tokenize(dataset, columns)
```

**Comment by fjetter** [comment] 2017-11-01 21:31
@xhochy For #2527 to actually work `pyarrow` needed to introduce the `S3FSWrapper`. I'd assume the same needs to be done for HDFS, see [here](https://github.com/apache/arrow/blob/142e6ee69bd6a4dc316d00d9efd6d86d119df075/python/pyarrow/parquet.py#L780)

We should maybe think of a more elaborate mechanism to ensure consistent interfaces

**Comment by stuckeyr** [comment] 2017-11-01 21:54
Guys, I'm moving house today. Will get back onto it next week. Thanks for all your efforts!

**Comment by mrocklin** [comment] 2017-11-01 21:55
Good luck!

**Comment by jcrist** [comment] 2017-11-09 23:23
#2527 is now merged, I believe this to be fixed. @stuckeyr could you try out the master branch and see if it resolves your issue?

**Comment by stuckeyr** [comment] 2017-11-10 03:48
Sorry, still not working. It seems the Arrow's `ParquetDataset._ensure_filesystem()` does not handle HDFS, and create a connection. @fjetter, do you want me to submit an issue to that project?

```
df = dataframe.read_parquet('hdfs://hdfsnn:8020/user/hdfs/ndsparq/Test.parquet', engine='arrow')
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-cf8b5e1e9563> in <module>()
----> 1 df = dd.read_parquet('hdfs://hdfsnn:8020/user/hdfs/ndsparq/Test.parquet', engine='arrow')

/opt/anaconda3/envs/env1/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in read_parquet(path, columns, filters, categories, index, storage_options, engine)
    331         return _read_pyarrow(fs, paths, file_opener, columns=columns,
    332                              filters=filters,
--> 333                              categories=categories, index=index)
    334 
    335 

/opt/anaconda3/envs/env1/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in _read_pyarrow(fs, paths, file_opener, columns, filters, categories, index)
    175     dataset = api.ParquetDataset(
    176         path_or_paths=paths,
--> 177         filesystem=fs
    178     )
    179     schema = dataset.schema.to_arrow_schema()

/opt/anaconda3/envs/env1/lib/python3.6/site-packages/pyarrow/parquet.py in __init__(self, path_or_paths, filesystem, schema, metadata, split_row_groups, validate_schema)
    614             self.fs = LocalFileSystem.get_instance()
    615         else:
--> 616             self.fs = _ensure_filesystem(filesystem)
    617 
    618         self.paths = path_or_paths

/opt/anaconda3/envs/env1/lib/python3.6/site-packages/pyarrow/parquet.py in _ensure_filesystem(fs)
    748                 return LocalFileSystem.get_instance()
    749 
--> 750         raise IOError('Unrecognized filesystem: {0}'.format(fs_type))
    751     else:
    752         return fs

OSError: Unrecognized filesystem: <class 'distributed.hdfs.DaskHDFileSystem'>
```

**Comment by xhochy** [comment] 2017-11-10 08:28
@stuckeyr yes, please open an issue with Arrow at https://issues.apache.org/jira/projects/ARROW about this.

**Comment by jcrist** [comment] 2017-11-10 14:28
Looks like the issue is with this logic here: https://github.com/apache/arrow/blob/master/python/pyarrow/parquet.py#L786-L792. This seems like a really fragile way to handle this. Perhaps a better way would be to remove this logic, and have dask pass the wrapped filesystems directly. Whether these live in pyarrow or dask is debatable.

**Comment by fjetter** [comment] 2017-11-10 16:26
@jcrist Yes, this is a fragile way to handle this but it avoids having `pyarrow` explicitly depend on `S3FS`. It is already possible for external libraries to define their own wrapper which inherits from `pyarrow.filesystem.FileSystem`. 
I think `pyarrow` should have an interest in supporting common filesystem types which I think it would make more sense to implement this wrapper there.

**Comment by jcrist** [comment] 2017-11-10 16:33
Sorry, I didn't mean that `pyarrow` should depend on `s3fs`. Rather I meant that instead of dask passing in its filesystem objects and pyarrow inferring and converting, we should just pass in a valid `pyarrow.filesystem.FileSystem` originally (and skip the classname string inference hack).

Whether the `S3FSWrapper` and needed `HDFSWrapper` live in pyarrow or dask is debatable. I mildly think they should live in dask, since we'd be a consumer of the pyarrow library and would be responsible for passing in a valid `pyarrow.filesystemFileSystem` object. Ping @xhochy, @wesm for thoughts.

**Comment by mrocklin** [comment] 2017-11-10 18:02
I wonder if it is feasible to agree on a single FileSystem interface between these projects.

**Comment by mrocklin** [comment] 2017-11-10 18:03
Having such a standard here would also make it easier to convince other groups (like Azure) to adhere to that standard.

**Comment by jcrist** [comment] 2017-11-10 19:17
> I wonder if it is feasible to agree on a single FileSystem interface between these projects.

Filed a separate issue to discuss this: #2880.

**Comment by wesm** [comment] 2017-11-10 19:20
We could create a pure Python library to define a abstract public API for these sorts of things. Then we aren't relying on duck typing

**Comment by jcrist** [comment] 2017-11-11 19:35
This should be fixed in #2881, although I'll probably move things around a bit to make testing possible.

**Comment by jcrist** [comment] 2017-11-16 19:39
HDFS integration has been moved out of distributed and into hdfs3. A pyarrow compatibility wrapper has been added there, as well as a test for reading parquet from hdfs using pyarrow (https://github.com/dask/hdfs3/blob/master/hdfs3/tests/test_dask.py#L442-L461). 

See #2894, https://github.com/dask/distributed/pull/1561, and https://github.com/dask/hdfs3/pull/144 for reference.

At this point parquet using pyarrow from hdfs works if you install dask, distributed, and hdfs3 from their respective master branches. We should have a release out of all of these in the next week or so, at which point you can just install the latest version from conda-forge.

Closing.

**Closed by jcrist** 2017-11-16 19:39 UTC

**Comment by Leo223** [comment] 2019-02-01 13:38
You should check libraries version. I had the same problem and resetting versions to:
- pyarrow = 0.11.1
- dask =1.0.0
With this configuration it works

**Comment by sushmit86** [comment] 2019-06-07 18:53
I am getting this error on databricks environment? 

import pyarrow.parquet as pq
print(pyarrow.__version__)

data1 = pq.read_table("output/rfm_data.parquet")

I am getting this error 


---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<command-2212940796894983> in <module>()
      2 print(pyarrow.__version__)
      3 data = sqlContext.read.parquet("output/rfm_data.parquet")
----> 4 data1 = pq.read_table("output/rfm_data.parquet")

/local_disk0/pythonVirtualEnvDirs/virtualEnv-dda14358-e6b1-4176-82cf-11f68d2d5859/lib/python3.5/site-packages/pyarrow/parquet.py in read_table(source, columns, use_threads, metadata, use_pandas_metadata, memory_map, filesystem)
   1150         return fs.read_parquet(path, columns=columns,
   1151                                use_threads=use_threads, metadata=metadata,
-> 1152                                use_pandas_metadata=use_pandas_metadata)
   1153 
   1154     pf = ParquetFile(source, metadata=metadata)

/local_disk0/pythonVirtualEnvDirs/virtualEnv-dda14358-e6b1-4176-82cf-11f68d2d5859/lib/python3.5/site-packages/pyarrow/filesystem.py in read_parquet(self, path, columns, metadata, schema, use_threads, use_pandas_metadata)
    177         from pyarrow.parquet import ParquetDataset
    178         dataset = ParquetDataset(path, schema=schema, metadata=metadata,
--> 179                                  filesystem=self)
    180         return dataset.read(columns=columns, use_threads=use_threads,
    181                             use_pandas_metadata=use_pandas_metadata)

/local_disk0/pythonVirtualEnvDirs/virtualEnv-dda14358-e6b1-4176-82cf-11f68d2d5859/lib/python3.5/site-packages/pyarrow/parquet.py in __init__(self, path_or_paths, filesystem, schema, metadata, split_row_groups, validate_schema, filters, metadata_nthreads, memory_map)
    933          self.metadata_path) = _make_manifest(
    934              path_or_paths, self.fs, metadata_nthreads=metadata_nthreads,
--> 935              open_file_func=self._open_file_func)
    936 
    937         if self.common_metadata_path is not None:

/local_disk0/pythonVirtualEnvDirs/virtualEnv-dda14358-e6b1-4176-82cf-11f68d2d5859/lib/python3.5/site-packages/pyarrow/parquet.py in _make_manifest(path_or_paths, fs, pathsep, metadata_nthreads, open_file_func)
   1108             if not fs.isfile(path):
   1109                 raise IOError('Passed non-file path: {0}'
-> 1110                               .format(path))
   1111             piece = ParquetDatasetPiece(path, open_file_func=open_file_func)
   1112             pieces.append(piece)

OSError: Passed non-file path: output/rfm_data.parquet

**Comment by martindurant** [comment] 2019-06-07 18:56
@sushmit86 , this appears to have nothing to do with Dask, maybe post on the pyarrow tracker.

**Comment by RoelantStegmann** [comment] 2019-11-19 16:07
Somehow have the same errors. We are working with pyarrow 0.15.1

```python
table2 = pq.read_table('C:/Data/test-parquet')
``` 

works fine in contrast to 

```python
parquet_file = pq.ParquetFile('C:/Data/test-parquet')
table2.parquet_file.read_row_group(0)
```

which raises

`ArrowIOError: Failed to open local file 'C:/Data/test-parquet', error: Access is denied.`

**Comment by martindurant** [comment] 2019-11-19 16:12
@RoelantStegmann , this again seems to be specific to pyarrow, no dask or even fsspec code is being used here. I can't even speculate what the Access Denied error might mean.

**Comment by RoelantStegmann** [comment] 2019-11-19 16:14
Thanks, will move it to their issue tracker. :)
