### ISSUE TITLE
big join scalability issue

### ISSUE THREAD

**Issue by jangorecki** [dask/dask#1545] opened 2016-09-15 01:26 UTC
I wonder if any speedup is possible for big joins. Currently dask join seems to scale poorly on high cardinality key and no partitions, it takes much too long. I surely wouldn't code that faster, but comparing to impala, spark, h2o and presto, there a significant gap to catch up.

[1e7 rows example](https://mega.nz/#!JpgXHCTA!fIntjGl-XHcea-xc_6P8idt_MkylnOEczTxSs7fRSdM), same file as shared few days ago.
1e10 rows took ~4.5h, but scaling is easy to notice on 1e9 and 5e9 already. Code to generate bigger tables.

``` py
import h2o
h2o.init()
N=int(1e9)

X=h2o.create_frame(rows=N,cols=2,integer_range=N,integer_fraction=1,categorical_fraction=0,binary_fraction=0,missing_fraction=0,seed=7639657576)
X.set_name('C1','KEY')
X.set_name('C2','X2')
h2o.download_csv(X,'X1e9_2c.csv')

Y=h2o.create_frame(rows=N,cols=2,integer_range=N,integer_fraction=1,categorical_fraction=0,binary_fraction=0,missing_fraction=0,seed=3756386978)
Y.set_name('C1','KEY')
Y.set_name('C2','Y2')
h2o.download_csv(Y,'Y1e9_2c.csv')
```

In [docs](http://dask.pydata.org/en/latest/dataframe-api.html?highlight=merge#dask.dataframe.DataFrame.merge) there is an argument `shuffle` but has no description, it sounds like it could be related to merge strategy.

**Comment by ankravch** [comment] 2016-09-15 02:07
Have you tried to use hdf5/bcolz data format with dask? Persisting data on cluster?

P.S. I can confirm that presto is scary fast (i will try to add a benchmark tomorrow). And when dask is doing big join that does not fit in RAM, then its performance gets really bad.

**Comment by mrocklin** [comment] 2016-09-15 04:01
Dask.dataframe definitely won't have the performance of a dedicated database-like system.  That being said I wouldn't expect it to be orders of magnitude slower.  If you're seeing something that's way off then it would be good to produce a reproducible example that can be easily benchmarked.  I recommend using dd.demo.make_timeseries for this so that people don't have to manage custom datasets.

**Comment by jangorecki** [comment] 2016-09-15 12:35
@ankravch actually presto isn't so fast for big joins. On 5e9 rows it appears to be twice faster then dask, but other big data apps are getting up to 10x faster. Big joins are meant to not fit into single node mem.
@mrocklin those datasets are just examples, can be any integer column really, just needs to be produced with good random number generator (and this gets tricky for >1e9 rows), otherwise you get big row explosion. Any info about `shuffle` argument, it sounds to be related here?

Task stream shows there isn't much idle cpus.
![dask-join-1e10](https://cloud.githubusercontent.com/assets/3627377/18549694/eb831756-7b47-11e6-9d2b-8bc79fe40f59.png)

**Comment by mrocklin** [comment] 2016-09-15 12:42
Dask.dataframe has two shuffles.  One for on-disk and one using the task system.  

*  On-disk is generally faster but doesn't work if you are on multiple machines
*  Task-based runs on multiple machines but requires that the dataset fits in RAM

On-disk is the default until you start a distributed Client, which changes the default to task-based.

**Comment by ankravch** [comment] 2016-09-16 22:49
In presto they have 'hash' join and 'distributed' join. The first one is used when joining one the tables is really small.

Using cluster with 12 cpu cores (3 CPU x 4 CentOS machines) and data tables
```python
presto:default> select count(*) from dgn9_finder2;
 _col0
-------
  1152
(1 row)

Query 20160916_222424_00017_9h4je, FINISHED, 2 nodes
http://192.168.102.223:8081/query.html?20160916_222424_00017_9h4je
Splits: 2 total, 2 done (100.00%)
CPU Time: 0.0s total,   72K rows/s,  397KB/s, 57% active
Per Node: 0.0 parallelism,  1.6K rows/s, 8.85KB/s
Parallelism: 0.0
0:00 [1.15K rows, 6.36KB] [3.21K rows/s, 17.7KB/s]

presto:default> select count(*) from dgn_claimno_pb_yos2008_partitioned;
   _col0
-----------
 693206260
(1 row)

Query 20160916_222442_00018_9h4je, FINISHED, 4 nodes
http://192.168.102.223:8081/query.html?20160916_222442_00018_9h4je
Splits: 434 total, 434 done (100.00%)
CPU Time: 5.3s total,  130M rows/s, 20.5MB/s, 23% active
Per Node: 0.8 parallelism,  107M rows/s, 16.8MB/s
Parallelism: 3.3
0:02 [693M rows, 109MB] [428M rows/s, 67.2MB/s]
```

presto 'hash join' performance
```python
[akravchenko@hnode1 ~]$ ./presto --server 192.168.102.223:8081 --catalog hive --schema default --debug
presto:default> set SESSION distributed_join=false;
SET SESSION
presto:default> select count(claimno) from dgn_claimno_pb_yos2008_partitioned as b, dgn9_finder2 as c where b.dgn = c.dgn;
   _col0
-----------
 308004217
(1 row)

Query 20160916_221604_00015_9h4je, FINISHED, 4 nodes
http://192.168.102.223:8081/query.html?20160916_221604_00015_9h4je
Splits: 455 total, 455 done (100.00%)
CPU Time: 381.7s total, 1.82M rows/s, 4.64MB/s, 40% active
Per Node: 1.7 parallelism, 3.17M rows/s, 8.11MB/s
Parallelism: 7.0
0:55 [693M rows, 1.73GB] [12.7M rows/s, 32.4MB/s]

presto:default> select count(claimno) from dgn_claimno_pb_yos2008_partitioned as b, dgn9_finder2 as c where b.dgn = c.dgn;
   _col0
-----------
 308004217
(1 row)

Query 20160916_222224_00016_9h4je, FINISHED, 4 nodes
http://192.168.102.223:8081/query.html?20160916_222224_00016_9h4je
Splits: 455 total, 455 done (100.00%)
CPU Time: 388.1s total, 1.79M rows/s, 4.57MB/s, 40% active
Per Node: 1.5 parallelism, 2.67M rows/s, 6.83MB/s
Parallelism: 6.0
1:05 [693M rows, 1.73GB] [10.7M rows/s, 27.3MB/s]
```

presto 'distributed join' performance
```python
[akravchenko@hnode1 ~]$ ./presto --server 192.168.102.223:8081 --catalog hive --schema default --debug
presto:default> set SESSION distributed_join=true;
SET SESSION
presto:default> select count(claimno) from dgn_claimno_pb_yos2008_partitioned as b, dgn9_finder2 as c where b.dgn = c.dgn;
   _col0
-----------
 308004217
(1 row)

Query 20160916_223640_00020_9h4je, FINISHED, 3 nodes
http://192.168.102.223:8081/query.html?20160916_223640_00020_9h4je
Splits: 465 total, 465 done (100.00%)
CPU Time: 484.8s total, 1.43M rows/s, 3.65MB/s, 57% active
Per Node: 0.4 parallelism,  597K rows/s, 1.52MB/s
Parallelism: 1.3
6:27 [693M rows, 1.73GB] [1.79M rows/s, 4.57MB/s]

presto:default> select count(claimno) from dgn_claimno_pb_yos2008_partitioned as b, dgn9_finder2 as c where b.dgn = c.dgn;
   _col0
-----------
308004217
(1 row)

Query 20160916_013713_00003_eqst6, FINISHED, 4 nodes
http://192.168.102.223:8081/query.html?20160916_013713_00003_eqst6
Splits: 475 total, 475 done (100.00%)
CPU Time: 445.8s total, 1.56M rows/s, 3.98MB/s, 46% active
Per Node: 0.7 parallelism, 1.02M rows/s, 2.62MB/s
Parallelism: 2.6
2:49 [693M rows, 1.73GB] [4.09M rows/s, 10.5MB/s]

presto:default> select count(claimno) from dgn_claimno_pb_yos2008_partitioned as b, dgn9_finder2 as c where b.dgn = c.dgn;
   _col0
-----------
308004217
(1 row)

Query 20160916_014010_00004_eqst6, FINISHED, 4 nodes
http://192.168.102.223:8081/query.html?20160916_014010_00004_eqst6
Splits: 475 total, 475 done (100.00%)
CPU Time: 500.4s total, 1.39M rows/s, 3.54MB/s, 50% active
Per Node: 0.5 parallelism,  654K rows/s, 1.67MB/s
Parallelism: 1.9
4:25 [693M rows, 1.73GB] [2.62M rows/s, 6.69MB/s]
```

Dask performance
```python
In [1]: import dask.dataframe as dd

In [2]: from dask.distributed import Executor

In [3]: import dask

In [4]: e=Executor('192.168.102.220:8786', set_as_default=True)

In [5]: e
Out[5]: <Executor: scheduler="192.168.102.220:8786" processes=12 cores=12>

In [6]: dgn_claim_pb = dd.from_bcolz(r'/mnt/nfs/bench/bcolz_large/dgn_claimno_pb_yos2008_all.bcolz',\
   ...:                            chunksize=int(1e6), lock=False, categorize=False)

In [7]:

In [7]: dgn_finder = dd.from_bcolz(r'/mnt/nfs/bench/bcolz_large/dgn9_finder_2.bcolz',\
   ...:                            chunksize=int(1e6), lock=False, categorize=False)

In [8]: step0_claim_finder = dd.merge(dgn_claim_pb[['DGN','CLAIMNO']],dgn_finder, on='DGN',\
   ...:                               how='inner')[['CLAIMNO']].count()

In [9]: %time dask.compute(step0_claim_finder)
CPU times: user 592 ms, sys: 29 ms, total: 621 ms
Wall time: 2min 32s
Out[9]:
(CLAIMNO    330634336
 dtype: int64,)
```

**Comment by ankravch** [comment] 2016-09-16 23:20
>actually presto isn't so fast for big joins. On 5e9 rows it appears to be twice faster then dask, but other big data apps are getting up to 10x faster. Big joins are meant to not fit into single node mem.

@jangorecki I would be curious to see your detailed benchmarks for 'other big data apps are getting up to 10x faster'

**Comment by jangorecki** [comment] 2016-09-17 00:59
@ankravch Everything is already in the issue. Better than being convinced by somebody's benchmark is to run it yourself. Timings you provided seems to be related to different join use case. Join "big to small" requires different strategy than "big to big" where key column doesn't fit into single node memory.

**Comment by mrocklin** [comment] 2018-10-23 21:54
I'm going to close this.  Certainly join performance could be better (I suspect that it has improved substantially since this issue) but conversation here seems to be over.

**Closed by mrocklin** 2018-10-23 21:54 UTC
Labels: dataframe, scheduler

**Comment by jangorecki** [comment] 2018-10-24 07:29
@mrocklin does it means that *big to big join* slow performance is not going to be improved?

**Comment by mrocklin** [comment] 2018-10-24 12:18
I think that it probably has been improved and will continue to improve in the future.

However this issue is probably no longer being helpful with that endeavor.  In general we'd like to avoid issues that stay open forever.  As an extreme example of this you could imagine an issue of "improve performance with dask dataframe".  Certainly that will continue to be valid, but it is sufficiently broad so as not to be very useful.

If there are other benchmarks or analyses of this benchmark that provide specific suggestions on how to speed up joins (or any other algorithm) then they would be welcome.

Things have also changed a lot since this issue and so it's hard to tell if the statements made above continue to be valid.  For anyone that remains interested in this issue I recommend constructing a reproducible example, perhaps with `dask.datasets.timeseries` that others can run to get the same results.
