### ISSUE TITLE
Is it possible to batch the rows of a csv in dask?

### ISSUE THREAD

**Issue by xiskoct** [dask/dask#5581] opened 2019-11-12 11:55 UTC
I'm trying to batch with the csv rows from dask:

```python
batch_size = 1000 # 1000rows
batch = []
count = 0

df = dd.read_csv (path, header = 0)
df_dask ['output'] = df.apply (lambda x: batch_row_csv (
         x), axis = 1, meta = object) .compute ()

def batch_row_csv (row):
       global batch 
       global count
       batch.append(row)
       if len (batch) < batch_size:
             return
       json.dump (batch) // save batch
       count = count +1
       batch = []
       return
```

Is there a problem with global variables and multiprocessing? In the good practices of Dask, they advise not to use global variables ... What would be the alternative?

Can this task be done with dask?

**Comment by mrocklin** [comment] 2019-11-12 15:34
Unfortunately after reading your question I'm still not sure what you
want.  Are you looking for the blocksize= keyword of the read_csv function?

**Comment by mrocklin** [comment] 2019-11-12 15:49
Duplicate of https://stackoverflow.com/questions/58810244/is-it-possible-to-batch-the-rows-of-a-csv-in-dask

Closing.

**Closed by mrocklin** 2019-11-12 15:49 UTC
