### ISSUE TITLE
cannot copy dask array returning python integer (when dtype=object)

### ISSUE THREAD

**Issue by mathause** [dask/dask#7081] opened 2021-01-17 21:27 UTC
**What happened**:

I think this is easiest to understand with a minimal example:

```python
import dask.array as da

a1 = da.array([1, 1]).prod()
a1.compute() # -> 1
a1.copy().compute() # works

a2 = da.array([1, 1], dtype=object).prod()
a2.compute() # -> 1
a2.copy().compute() # fails
```

```python-traceback
AttributeError: 'int' object has no attribute 'copy'
```

**What you expected to happen**:

That the second copy succeeds as well, but of course this is quite the corner case... 

**Anything else we need to know?**:

**Environment**:

- Dask version: 2020.12.0
- Python version: 2.8
- Operating System: linux
- Install method (conda, pip, source): conda

**Comment by jsignell** [comment] 2021-01-18 21:00
Wow that certainly is an odd one. I poked around and I think the issue is that `a2.compute()` is a regular `int` and `a1.compute()` is a `numpy.int64`. If you do `dir(a1.compute())` and `dir(a2.compute())` you'll see that the first has `copy` and the second does not. 

I thought you'd be able to do a workaround with `a2.astype(np.int64)` or something, but that doesn't seem to work how I expected it would.

**Comment by mathause** [comment] 2021-01-18 21:09
Yes, that makes sense! I think it's possible to do

```python
import copy
copy.copy(a2).compute()
```

**Comment by ncclementi** [comment] 2021-08-11 21:45
@jsignell what is the status of this issue? Since there is a workaround, should we close it?

**Comment by jsignell** [comment] 2021-08-12 15:23
Thanks for the ping - I think we can go ahead and close. This same behavior can be found using pure numpy:

```python
import numpy as np

np.array([1,1], dtype=object).prod().copy()
```

**Closed by jsignell** 2021-08-12 15:23 UTC
