### ISSUE TITLE
``GroupBy.idxmin/idxmax`` is broken

### ISSUE THREAD

**Issue by phofl** [dask/dask#10345] opened 2023-06-12 15:54 UTC
**Describe the issue**:

It breaks, as soon as one group is distributed over 2 or more partitions. This needs a similar implementation to ``DataFrame.idxmin/idxmax``

**Minimal Complete Verifiable Example**:

```python
df = pd.DataFrame({"a": [11, 12, 31], "b": 1.0}, index=["x", "y", "z"])
ddf = dd.from_pandas(df, npartitions=2)
df.groupby("b").idxmax()
ddf.groupby("b").idxmax().compute()
```

returns

```
     a
b     
1.0  z
     a
b     
1.0  y
```

**Anything else we need to know?**:

**Environment**:

- Dask version: 2023.06
- Python version: 3.10
- Operating System: Mac
- Install method (conda, pip, source): conda

**Comment by jrbourbeau** [comment] 2023-06-12 16:00
Thanks @phofl. I think this might be a duplicate of https://github.com/dask/dask/issues/9882 (though feel free to correct me if that's not the case)

**Closed as completed** 2023-06-12 16:01 UTC
Labels: dataframe, needs triage
