### ISSUE TITLE
Better Textual `repr` of dask.array.

### ISSUE THREAD

**Issue by rainwoodman** [dask/dask#2628] opened 2017-08-25 20:05 UTC
Our users are constantly confused when they 'print' on a `dask.array`.

They expect to see some description of the data, e.g. first few items, and last items, like a numpy array.
But instead they only see a `<dask.array ...>`  textual representation that only describes the meta information of the data.

Should repr trigger compute()?

**Comment by jcrist** [comment] 2017-08-25 20:46
> Should repr trigger compute()?

That sounds dangerous, as `compute` could be really expensive. Instead we might imitate the repr for `dask.dataframe` and provide more information. There's already an open issue for this at #1676.

**Comment by jcrist** [comment] 2017-08-25 21:11
Closing as duplicate of #1676. Continuing discussion there.

**Closed by jcrist** 2017-08-25 21:11 UTC
