### ISSUE TITLE
Memoery issue in dask with using local cluster

### ISSUE THREAD

**Issue by enthusiastics** [dask/dask#8005] opened 2021-08-06 15:40 UTC
I'm trying to use Dask local cluster to manage system wide memory usage, 

    from dask.distributed import Client, LocalCluster
    cluster = LocalCluster(scheduler_port=5272, dashboard_address=5273,memory_limit='4GB')

I connect with:

    client = Client('tcp://127.0.0.1:5272')

I have 8 cores and 32 GB. The local cluster distributes 4GB * 4 = 16GB memory (I have another task that required about 10GB memory) into the local cluster. However, previously there are some tasks I could finish well without calling `client = Client('tcp://127.0.0.1:5272')`. After I call `client = Client('tcp://127.0.0.1:5272')`, memory error triggered. What can i do in this scenario? Thanks!

I'm thinking if it is because each worker is only allocated 4GB memory... but if I assign memory_limit='16GB'. If it uses all of the resources it would take 64GB. I don't have that much memory. What can I do?

**Comment by ncclementi** [comment] 2021-08-09 15:41
@enthusiastics Thank you for opening an issue, would you mind providing a [minimal reproducible example](https://blog.dask.org/2018/02/28/minimal-bug-reports) ? This will allow us to reproduce the problem and help you, otherwise is a bit complicated to know what is happening.

**Comment by ncclementi** [comment] 2021-08-20 14:42
Closing this one due to the lack of info, @enthusiastics if you still having this issue please feel free to re-open with a minimal reproducible example so we can help you.

**Closed by ncclementi** 2021-08-20 14:42 UTC
Labels: needs info
