### ISSUE TITLE
DataFrame.transform should ensure output has same index as input

### ISSUE THREAD

**Issue by fjetter** [dask/dask#10035] opened 2023-03-08 10:02 UTC
I believe a very common application for `DataFrame.transform` is to compute a new column of a dataframe. This is one of the examples in pandas, see at the bottom https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.transform.html

Effectively, this means that a very typical pattern is something like

```python
ddf["new_col"] = ddf.groupby("<column>").transform(func)
```

Consider the following example

```python
df = pd.DataFrame({
    'ints': [1, 2, 3],
    'grouper': [0, 1, 0]
})

ddf = dd.from_pandas(df, npartitions=2)
ddf["new"] = ddf.groupby('grouper').transform('first')['ints']
```

will raise a 

```python-traceback
ValueError: Not all divisions are known, can't align partitions. Please use `set_index` to set the index.
```

To make this work as expected, one has to sort the series index manually, e.g.

```python
df = pd.DataFrame({
    'ints': [1, 2, 3],
    'grouper': [0, 1, 0]
})

ddf = dd.from_pandas(df, npartitions=2)
ddf["new"] = (
    ddf.groupby('grouper')
    .transform('first')
    .reset_index()
    .set_index('index')
)['ints']
```

While the above exception tells you that you should use `set_index` I believe this is not very intuitive for users since the output of a transform is a series which doesn't have a `set_index`. At the very least, the series should offer a method `sort_index` that effective performs `reset_index().set_index()[self.name]` for the user.

This obviously comes with a performance penalty but is ultimately required to use `DataFrame.transform` for assignments.

Note: An even less intuitive way to trigger this problem is by using `dd.concat` which provides a slightly less helpful exception 

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[173], line 1
----> 1 dask.dataframe.concat([ddf, first_series], axis=1).compute()

File ~/mambaforge/envs/dask-311/lib/python3.11/site-packages/dask/dataframe/multi.py:1295, in concat(dfs, axis, join, interleave_partitions, ignore_unknown_divisions, ignore_order, **kwargs)
   1293         return concat_unindexed_dataframes(dfs, ignore_order=ignore_order, **kwargs)
   1294     else:
-> 1295         raise ValueError(
   1296             "Unable to concatenate DataFrame with unknown "
   1297             "division specifying axis=1"
   1298         )
   1299 else:
   1300     if all(df.known_divisions for df in dasks):
   1301         # each DataFrame's division must be greater than previous one

ValueError: Unable to concatenate DataFrame with unknown division specifying axis=1
```

**Comment by j-bennet** [comment] 2023-03-13 21:31
Note: whoever picks up the issue should also take a look at the original case, that has a reproduction example of concatenating `DataFrames` producing an incorrect result:

* https://github.com/coiled/support-two-sigma/issues/32

**Comment by j-bennet** [comment] 2023-04-12 20:57
@fjetter 

> While the above exception tells you that you should use set_index I believe this is not very intuitive for users since the output of a transform is a series which doesn't have a set_index. At the very least, the series should offer a method sort_index that effective performs reset_index().set_index()[self.name] for the user.

The output of the above `.transform` is a `DataFrame`:

```python
In [1]: import pandas as pd

In [2]: df = pd.DataFrame({
   ...:     'ints': [1, 2, 3],
   ...:     'grouper': [0, 1, 0]
   ...: })

In [3]: df.groupby('grouper').transform('first').__class__
Out[3]: pandas.core.frame.DataFrame
```

but you're getting a single item out of it with `__getitem__` accessor, and that's `Series`.

I agree, this is not intuitive that `__getitem__` requires you to reset an index first. Looking at the docstring of our `Groupby.transform`:

https://github.com/dask/dask/blob/fd31b9b67e105f4c63b391f5c24959e39e27a0cc/dask/dataframe/groupby.py#L2489

It says:

> This mimics the pandas version except for the following:
> 1.  If the grouper does not align with the index then this causes a full shuffle.  The order of rows within each group may not be preserved.

It says " if the grouper does not align with the index", in fact it's checking if the grouper contains the index, which seems more restrictive. If your grouper contains the index, the `__getitem__` will work fine:

```python
In [22]: df2 = df.set_index('grouper')

In [23]: ddf2 = dd.from_pandas(df2, 2)

In [30]: ddf2['new'] = ddf2.groupby('grouper').transform('first', meta=expected)['ints']

In [31]: ddf2.compute()
Out[31]:
         ints  new
grouper
0           1    1
0           3    1
1           2    2
```

In our [documentation](https://docs.dask.org/en/stable/dataframe-api.html#groupby-operations), I don't see a a section for `DataFrame.transform` and `DataFrame.GroupBy.transform`. This looks like an omission.

I'm going to look into the issue.

**Comment by jrbourbeau** [comment] 2023-05-02 15:09
Closed via https://github.com/dask/dask/pull/10184

**Closed by jrbourbeau** 2023-05-02 15:09 UTC
Labels: dataframe, bug
