### ISSUE TITLE
dask.array.linalg.svd signature is different from numpy.linalg.svd

### ISSUE THREAD

**Issue by sumanthratna** [dask/dask#6048] opened 2020-03-31 01:04 UTC
**Bug report** (maybe I'm just misunderstanding something):

```python
@dask.delayed(pure=True)
def load_image(filename, coords=None):
    return None if filename is None \
        else clip_image(<DASK ARRAY>, coords)


def clip_image(img, coords=None):
    # can be simplified to use_coords_target = coords_target is not None, 
    # but this is easier to read:
    use_coords = True if coords is not None else False

    if use_coords:
        x_start, x_end, y_start, y_end = coords
        img = img[x_start:x_end, y_start:y_end]
    return img

def my_method():
    # I want this to work but it won't:
    target_delayed = load_image(target, coords_target)  # dask delayed of dask array
    target_shape = target_delayed.shape.compute()  # tuple
    ihc_rgb_target = dask.array.from_delayed(
        target_delayed, target_shape, dtype=np.uint8)  # dask array
    print(ihc_rgb_target)


    # this works:
    ihc_rgb_target = load_image(
        target, coords_target).compute()  # dask array
    print(ihc_rgb_target)
```
Both `print` statements result in `dask.array<from-value, shape=(1, 1087, 5000, 3), dtype=uint8, chunksize=(1, 1087, 5000, 3), chunktype=numpy.ndarray>`. 

However, if I remove the line `ihc_rgb_target = load_image(target, coords_target).compute()`, I get the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "...lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "...lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "...lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "...lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "...lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/suman/quantum/pynuclei/pynuclei/cli.py", line 46, in compare
    contrast_limits=[0, 255]
  File "...lib/python3.6/site-packages/napari/components/add_layers_mixin.py", line 175, in add_image
    visible=visible,
  File "...lib/python3.6/site-packages/napari/layers/image/image.py", line 220, in __init__
    self._update_dims()
  File "...lib/python3.6/site-packages/napari/layers/base/base.py", line 383, in _update_dims
    self.refresh()
  File "...lib/python3.6/site-packages/napari/layers/base/base.py", line 600, in refresh
    self._set_view_slice()
  File "...lib/python3.6/site-packages/napari/layers/image/image.py", line 491, in _set_view_slice
    image = np.asarray(self.data[self.dims.indices]).transpose(order)
  File "...lib/python3.6/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "...lib/python3.6/site-packages/dask/array/core.py", line 1337, in __array__
    x = self.compute()
  File "...lib/python3.6/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "...lib/python3.6/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "...lib/python3.6/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "...lib/python3.6/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "...lib/python3.6/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "...lib/python3.6/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "...lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/suman/quantum/pynuclei/pynuclei/utils.py", line 151, in deconvolution_array
    return rgb_separate_stains_macenko_pca(ihc_rgb, 255.0)
  File ".../lib/python3.6/site-packages/histomicstk/preprocessing/color_deconvolution/rgb_separate_stains_macenko_pca.py", line 35, in rgb_separate_stains_macenko_pca
    return separate_stains_macenko_pca(im_sda, *args, **kwargs)
  File ".../lib/python3.6/site-packages/histomicstk/preprocessing/color_deconvolution/separate_stains_macenko_pca.py", line 83, in separate_stains_macenko_pca
    pcs = linalg.get_principal_components(m)
  File "...lib/python3.6/site-packages/histomicstk/preprocessing/color_deconvolution/_linalg.py", line 9, in get_principal_components
    return numpy.linalg.svd(m.astype(float), full_matrices=False)[0].astype(m.dtype)
  File "<__array_function__ internals>", line 6, in svd
  File ".../lib/python3.6/site-packages/dask/array/core.py", line 1382, in __array_function__
    return da_func(*args, **kwargs)
TypeError: svd() got an unexpected keyword argument 'full_matrices'
```
I'm suspecting that it's because `dask.array.linalg.svd` doesn't accept `full_matrices` as an optional parameter. Relevant dask code: https://github.com/dask/dask/blob/master/dask/array/linalg.py#L785-L807

Unfortunately, I'm unable to produce a more minimal example using `dask.array.random.random`, which leads me to think that this may be a bug. To be honest, I have no idea why this is happening, since printing both dask arrays had the same output. Regardless of whether this is a bug or not, better error output would be helpful.

**Comment by quasiben** [comment] 2020-03-31 15:15
@sumanthratna thanks for the report. Yes `full_matrices` is not currently a valid argument.  I think this was previously reported here: https://github.com/dask/dask/issues/3576

**Comment by jrbourbeau** [comment] 2020-03-31 22:08
Closing this issue as a duplicate of #3576. Thanks for raising an issue @sumanthratna!

**Closed by jrbourbeau** 2020-03-31 22:08 UTC
