### ISSUE TITLE
dask.dataframe.read_parquet fails unless written by fastparquet

### ISSUE THREAD

**Issue by caseyclements** [dask/dask#5774] opened 2020-01-08 18:37 UTC
The (current) pandas.Dataframe.to_parquet uses pyarrow as its parquet backend. dask.dataframe.read_parquet(_, engine='fastparquet') fails. It appears to be incorrectly handling "hive-style" partitioning.

I am using dask version ('2.8.1'), pyarrow ('0.15.1'), and fastparquet ('0.3.2').
```
$ conda create -c conda-forge -n dask.arrow.issue -y dask fastparquet pyarrow jupyterlab python-snappy
```

To reproduce

```
import dask, pyarrow, fastparquet
print((dask.__version__, pyarrow.__version__, fastparquet.__version__)) # ('2.9.1', '0.15.1', '0.3.2')

import pandas as pd
import dask.dataframe as dd
import pyarrow.parquet as pq

df = pd.DataFrame([{'str': str(i), 'int':i, 'group': 'ABC'[i%3]} for i in range(6)])

pq_dir = './parquet_partition_issue'
df.to_parquet(pq_dir, partition_cols=['group'])
# or the equivalent: df.to_parquet(pq_dir, partition_cols=['group'], engine='pyarrow')

ddf_fast = dd.read_parquet(pq_dir, engine='fastparquet')

# IsADirectoryError: [Errno 21] Is a directory: 'parquet_partition_issue/group=A'

```

**Comment by rjzamora** [comment] 2020-01-09 15:09
Just a note that it is [a known problem](https://github.com/dask/dask/blob/0ecef985bb7c75e02b0bc50aa1564f004103b0d1/dask/dataframe/io/tests/test_parquet.py#L133) that fastparquet has problems reading directories written with pyarrow.  The problem is likley in fastparquet, rather than dask.  For example, I also get an error when using pandas for both the write and read:

```python
import pandas as pd

df = pd.DataFrame([{'str': str(i), 'int':i, 'group': 'ABC'[i%3]} for i in range(6)])

pq_dir = 'parquet_partition_issue'
df.to_parquet(pq_dir, partition_cols=['group'], engine='pyarrow')

pd.read_parquet(pq_dir, engine='fastparquet') 

# Note: Setting `engine='pyarrow'` works fine
```

<details>
<summary>Click for Output</summary>
<br>

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
~/miniconda3/envs/cudf++12/lib/python3.7/site-packages/fastparquet/api.py in __init__(self, fn, verify, open_with, root, sep)
    109                 self.fn = fn2
--> 110                 with open_with(fn2, 'rb') as f:
    111                     self._parse_header(f, verify)

~/miniconda3/envs/cudf++12/lib/python3.7/site-packages/fastparquet/util.py in default_open(f, mode)
     37 def default_open(f, mode='rb'):
---> 38     return open(f, mode)
     39 

FileNotFoundError: [Errno 2] No such file or directory: 'parquet_partition_issue/_metadata'

During handling of the above exception, another exception occurred:

IsADirectoryError                         Traceback (most recent call last)
<ipython-input-2-38271898390a> in <module>
     10 os.system("rm -rf "+pq_dir)
     11 df.to_parquet(pq_dir, partition_cols=['group'], engine='pyarrow')
---> 12 pd.read_parquet(pq_dir, engine='fastparquet')

~/miniconda3/envs/cudf++12/lib/python3.7/site-packages/pandas/io/parquet.py in read_parquet(path, engine, columns, **kwargs)
    294 
    295     impl = get_engine(engine)
--> 296     return impl.read(path, columns=columns, **kwargs)

~/miniconda3/envs/cudf++12/lib/python3.7/site-packages/pandas/io/parquet.py in read(self, path, columns, **kwargs)
    197         else:
    198             path, _, _, _ = get_filepath_or_buffer(path)
--> 199             parquet_file = self.api.ParquetFile(path)
    200 
    201         return parquet_file.to_pandas(columns=columns, **kwargs)

~/miniconda3/envs/cudf++12/lib/python3.7/site-packages/fastparquet/api.py in __init__(self, fn, verify, open_with, root, sep)
    113             except (IOError, OSError):
    114                 self.fn = join_path(fn)
--> 115                 with open_with(fn, 'rb') as f:
    116                     self._parse_header(f, verify)
    117         self.open = open_with

~/miniconda3/envs/cudf++12/lib/python3.7/site-packages/fastparquet/util.py in default_open(f, mode)
     36 
     37 def default_open(f, mode='rb'):
---> 38     return open(f, mode)
     39 
     40 

IsADirectoryError: [Errno 21] Is a directory: 'parquet_partition_issue'
```

</details>

**Comment by TomAugspurger** [comment] 2020-01-14 19:31
Agreed that the issue most likely resides in the engine rather than dask (most likely in the fastparquet side of things). Closing here, though let us know if you make progress @caseyclements.

**Closed by TomAugspurger** 2020-01-14 19:31 UTC
